### ISSUE TITLE
BTC domain transfer doesn't display

### ISSUE THREAD

**Issue by nanonerd** [blockstack/blockstack-app#1706]
Hi, I did a transfer of a btc domain. Problems are in CAPS below.

**>>>>>  Account transferred from Wallet #A:** 
https://explorer.stacks.co/address/SP32QQ557KP1Q8DPBGJCZ6NTYXVC41AFK5AR28GGT?chain=mainnet
Transferred "amigo.btc" domain.
When I sign into btc.us website, it is not there (correct). 

![image](https://user-images.githubusercontent.com/5571462/133870772-7b63de32-e9fb-4781-bf5e-55baeb6b1d27.png)

**BUT IT STILL APPEARS IN THIS HIRO WALLET #A (NOT CORRECT).**

![image](https://user-images.githubusercontent.com/5571462/133870951-d755cf3a-d45b-4ea0-91fc-750f5112ed2e.png)

**>>>>> Account transferred to Wallet #B:**
https://explorer.stacks.co/address/SP3J8H2P4AFH1NK96BJJY9S2V5GW4SCV7MKW7A7P0?chain=mainnet
When I sign into btc.us website, I can see it in the Account page ( amigo.btc) so it looks like the transfer worked (correct).

![image](https://user-images.githubusercontent.com/5571462/133870854-5c300ed5-d470-49a1-993f-c67fc2dace65.png)

**HOWEVER, IT DOES NOT DISPLAY IN HIRO WALLET #B. IT SHOWS THE DEFAULT "ACCOUNT 46" (NOT CORRECT).**

![image](https://user-images.githubusercontent.com/5571462/133870955-b5ce37c9-9f4c-47ce-bba2-b644c6d1f74e.png)

Thanks and let me know if you have any questions.

**Comment by markmhendrickson** [comment]
Thanks for the report. Mind posting screenshots of what you see exactly?

**Comment by nanonerd** [comment]
@markmhx - Hi, I updated my original post with 4 images. Hope that makes it more clear. Thanks.

**Comment by fbwoolf** [comment]
This appears to be the same as https://github.com/blockstack/stacks-wallet-web/issues/1216. I remember coming across this before and commented that I have the same issue in my wallet. I have a successful transfer tx but the bns name still remains tied to me (the sender).

https://stacks-node-api.stacks.co/v1/names/will.btc
https://explorer.stacks.co/txid/0x30a1a3d18709ddcd70ddb4fb904feeaf3cf5538aa724b7b5e78081fed6395ad0?chain=mainnet

Where should I go from here in resolving this? My understanding is that it's an api issue?

**Comment by fbwoolf** [comment]
Related:
https://github.com/blockstack/stacks-blockchain-api/issues/714

**Comment by markmhendrickson** [comment]
@zone117x any idea if this is related to #1216 as indicated by @fbwoolf above, and if so, should https://github.com/blockstack/stacks-blockchain-api/issues/614 have resolved it?

**Comment by zone117x** [comment]
Yes, should be solved in latest API version (expected to be deployed today).

**Comment by markmhendrickson** [comment]
Brilliant ✨

**Comment by nanonerd** [comment]
Sorry fellas - @zone117x. I just grabbed the latest HIRO Wallet (v2.17.0). I saw there was an update to it on Sept 22. Is the corrective API that you speak of in this version? I checked both my wallets A and B. Unfortunately, the incorrect states still remain in both wallets with respect to the transferred domain name.  :-(

**Comment by zone117x** [comment]
@nanonerd can you test now?

https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP32QQ557KP1Q8DPBGJCZ6NTYXVC41AFK5AR28GGT
```json
{
  "names": [
    "amigo.btc"
  ]
}
```
https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP3J8H2P4AFH1NK96BJJY9S2V5GW4SCV7MKW7A7P0
```json
{
  "names": []
}
```

EDIT: looks like the order of name ownership is incorrect, I re-opened https://github.com/blockstack/stacks-blockchain-api/issues/714

**Comment by nanonerd** [comment]
@zone117x  - I again removed HIRO Wallet. Got the latest (looks to be same version as yesterday's - v2.17.0). Tested again. Same result.

**Comment by markmhendrickson** [comment]
@nanonerd can you confirm whether this is still a problem, and if so, I'll reopen?

**Comment by nanonerd** [comment]
Hi @markmhx - Thanks for the follow up. Here is an update to my initial post using Wallet A (amigo address) transferring to Wallet B address. 

Wallet A still shows "amigo.btc" when I do a Switch Account in the HIRO web extension. I think it will be better if "amigo.btc" doesn't show anymore once a BNS name is transferred out (see image below). When I click in, it shows BNS names = 0 (correct).

![image](https://user-images.githubusercontent.com/5571462/165978846-1f15cc18-b8d2-42c1-88ef-5afbec643bf2.png)

**Wallet B now shows "amigo.btc" (Cool, this was problem before). And when I click into account, it shows BNS names = 1 (correct).** 

I haven't tried a new/recent transfer. With "amigo.btc", it appears most of the mechanics are working. I think, if it is possible, it would be a cleaner transfer if "amigo.btc" stopped appearing in Wallet A address after it has been transferred out (see image above). This is not a major issue, but probably better for user experience. 

Thank you!

**Comment by markmhendrickson** [comment]
Thanks for the details, @nanonerd. I suspect you may be running into https://github.com/hirosystems/stacks-blockchain-api/issues/1158 over the past few days, which is causing accounts to show usernames they've already transferred to other addresses. We're actively working on a fix on the API-side. 🙏
