### ISSUE TITLE
Website redirect at btc.us

### ISSUE THREAD

**Issue by ikill4food2** [blockstack/blockstack-app#1711]
Hello,
 btc.us site is not saving updated website redirects.
Have tried to update a few forwarding addresses using web wallet with Brave browser - every transaction shows confirmed, but when btc.us account is later checked - the website redirect information at btc.us is never saved and remains blank.
 Here one of the latest attempts: 0xedfb8d4306bbe794e6be86ecc2d3ed8e81fa2dff072f4ee8ce2b4889566b55d1

**Comment by markmhendrickson** [comment]
I suspect this is an issue with the .BTC app itself. Mind opening this issue in the app's repository here? https://github.com/hirosystems/btc-us-website/issues/new
