### ISSUE TITLE
STX Transfer from contract not showing or showing incorrectly in wallet

### ISSUE THREAD

**Issue by mijoco-btc** [blockstack/blockstack-app#1713]
stx transfers, triggered within contract, don't show in web wallet activity stream and show with incorrect amount in desktop wallet.  

See 0x3a71f352639625737fa9377e1e0c5c8c65afc98772130fc1f0c1ee447734a6a1 for example the stx transfer from 
STX transfer of 0.3 STX from SP4DYYK99BZS7S95KYYEJAJE5VJ21F57M4NS0Q5F to SP4DYYK99BZS7S95KYYEJAJE5VJ21F57M4NS0Q5F
shows in desktop wallet as 0.1369 STX - the same amount as the gas fee charged to the buyer?

and this tx: 0x3b378fa6c80e471045cbee17ee33c3c3c5589904f0da0a35a3715036900fef7d
the 0.25 to SP162D87CY84QVVCMJKNKGHC7GGXFGA0TAR9D0XJW
(event 0) is not showing in the activity tab of web wallet of this address.

## Details

Network: mainnet
Contract: SP3QSAJQ4EA8WXEDSRRKMZZ29NH91VZ6C5X88FGZQ.thisisnumberone-v2
Client libs: 
    "@stacks/connect": "^6.2.0",
    "@stacks/network": "^2.0.1",
    "@stacks/storage": "^2.0.1",
    "@stacks/transactions": "^2.0.1",

## Screenshots

<img width="370" alt="Screenshot 2021-09-16 at 08 40 43" src="https://user-images.githubusercontent.com/4384929/133571206-a75fcb7b-4519-4b3d-beae-2907e14f0e3f.png">

<img width="522" alt="Screenshot 2021-09-16 at 08 42 55" src="https://user-images.githubusercontent.com/4384929/133571339-1811cddf-aef8-48f9-bac4-41052c05a885.png">

Desktop wallet receives the gas fee amount (should receive 0.25 stx)?
<img width="770" alt="Screenshot 2021-09-16 at 08 21 42" src="https://user-images.githubusercontent.com/4384929/133571259-e9430d67-9b72-4e9c-8d92-db62be184b30.png">

**Comment by markmhendrickson** [comment]
Has this transfer transaction settled by now, and if so, do you still see these discrepancies?

There is an API-borne issue with transactions in the mempool sometimes not getting represented properly for the wallet and other clients to process correctly. We have a fix in mind here: https://github.com/blockstack/stacks-wallet/issues/921

**Comment by mijoco-btc** [comment]
There are around 12 of these in my desktop wallet all corresponding to confirmed txs starting from the 9/9 showing 0.1936 (tx fee) - all link to confirmed transactions for which the buyer paid this amount and the contract paid a different amount to my address - as far as the explorers view shows. 

I've now switched the address paid by the contract to my web wallet and am tracking the balance to see what happens in that context.

**Comment by markmhendrickson** [comment]
I'm relabeling this as an enhancement since it appears related to changes we need to make for contract-based transactions to show up like regular ones as captured here in a milestone: https://github.com/blockstack/stacks-wallet-web/milestone/47

**Comment by mijoco-btc** [comment]
Ok thanks. I reported here but just to check it also affects desktop wallet?

**Comment by markmhendrickson** [comment]
Yep this work affects the desktop wallet and explorer as well.

**Comment by Eshwari007** [comment]
Logged an issue where the tx in Web wallet was shown incorrectly in explorer:https://github.com/blockstack/stacks-wallet-web/issues/1787

**Comment by Eshwari007** [comment]
Tested the issue with several contracts and having a similar issue in the past that upon Contract deploy,the ext (popup) is unable to be viewed
<img width="1342" alt="Screen Shot 2021-10-08 at 11 17 38 AM" src="https://user-images.githubusercontent.com/38872890/136581967-5399b0db-b69e-4749-8d15-d2042b20ac9e.png">
cc @beguene

**Comment by Eshwari007** [comment]
Yes @beguene ,yet similar issue was reproducible
https://stacks-wallet-web.vercel.app/

Upon contract deploy-user isnt able to view the ext
<img width="331" alt="Screen Shot 2021-10-08 at 12 57 32 PM" src="https://user-images.githubusercontent.com/38872890/136595028-2a30e406-bb0d-457d-9c68-30971f92a334.png">

**Comment by beguene** [comment]
@Eshwari007 I found the issue, the build in the PR was not produced from the latest commit. This is fixed now.

**Comment by Eshwari007** [comment]
@beguene attaching the screen shot in web wallet where the values undefined and -1e-9 which I have not seen in the past 
<img width="371" alt="Screen Shot 2021-10-24 at 6 43 26 PM" src="https://user-images.githubusercontent.com/38872890/138615959-3591e49f-0ff0-4b34-9566-3d1a55584249.png">
<img width="385" alt="Screen Shot 2021-10-24 at 6 44 55 PM" src="https://user-images.githubusercontent.com/38872890/138615960-a3fafa9e-e525-4ded-a764-8089343c79c2.png">

Found the above while testing the PR with Demo test app

**Comment by Eshwari007** [comment]
In desktop wallet no such values are shown
<img width="568" alt="Screen Shot 2021-10-24 at 6 47 04 PM" src="https://user-images.githubusercontent.com/38872890/138616012-928ade3f-7418-4c0c-8b52-2eab870c486e.png">

**Comment by beguene** [comment]
@Eshwari007 I made a fix, you can check now.
https://github.com/hirosystems/stacks-wallet-web/pull/1747

**Comment by Eshwari007** [comment]
@beguene Quick question:
I was testing few tx from Demo testnet app and compared between the web wallet and desktop wallet.
I see rocket token is displayed with value in desktop wallet ,however no values were displayed in Webwallet
https://explorer.stacks.co/txid/0x6e783674a275cced9c57e43ab963db30e30c53d8942517257fb1fabc83183e6d?utm_source=stacks-wallet&chain=testnet
is the explorer details of the tx
<img width="1241" alt="Screen Shot 2021-11-02 at 2 30 42 PM" src="https://user-images.githubusercontent.com/38872890/139924266-7db5cfc6-a846-4c31-a594-45a240a2fbd8.png">

Contract call -0.126 STX shown in Desktop wallet but in Web wallet its shown as transfer dull-sapphire-bird with no values.Seems to be inconsistent between the two tx in Desktop wallet and Web wallet.In other words,the function is shown with no value in WW but upon selecting in activity is directing to the same desktop wallet tx of value in contract call

**Comment by Eshwari007** [comment]
Other issues have been fixed such as the unknown values and unable to click the STX icon again.

**Comment by beguene** [comment]
There were always a difference between desktop wallet and web wallet. In desktop next to the contract_call the tx fee is shown (here 0.126 STX) but nothing else

In the production web wallet it's shown only 'transfer' see below


<img width="558" alt="transfer" src="https://user-images.githubusercontent.com/1501454/140525905-93a3971e-5d62-43c0-aeb7-f8a30eb73117.png">

With my fix it should show an amount, but for this particular token contract, there is no metadata returned by the api

https://stacks-node-api.testnet.stacks.co/extended/v1/tokens/ST1X6M947Z7E58CNE0H8YJVJTVKS9VW0PHEG3NHN3.dull-sapphire-bird/ft/metadata?unanchored=true

So we don't show the transfer amount

While with Stella the metadata are here
https://stacks-node-api.testnet.stacks.co/extended/v1/tokens/ST6G7N19FKNW24XH5JQ5P5WR1DN10QWMKQSPSTK7.stella-the-cat/ft/metadata?unanchored=true
And we show the amount

**Comment by beguene** [comment]
@timstackblock can you please check this ?

**Comment by timstackblock** [comment]
It looks like this is an NFT purchased on https://thisisnumberone.com/

I will use your new build to purchases from the same contract (if possible) and compare the web wallet with the explorer and the desktop wallet.

**Comment by Eshwari007** [comment]
The issue seems to be fixed from web wallet end but the duplicate func tx seems to be apparent in desktop wallet.
@timstackblock was able to reproduce the issue as well 
Shall I create a separate ticket in desktop wallet? cc @beguene
