### ISSUE TITLE
Improve loading state for networks to select

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1717]
Right now the "Loading" label gets offset temporarily further to the left than loaded network, creating a strange animation effect:

![image](https://user-images.githubusercontent.com/28991/133630068-10a7a062-6f7a-44b4-878d-ae7ccf88f7a3.png)

**Comment by Eshwari007** [comment]
Test Passed.Moving it to QA Done

**Comment by Eshwari007** [comment]
https://user-images.githubusercontent.com/38872890/135337294-67c6f8a5-7396-450b-86b4-dd5b3572f64b.mov

Has similar issue in this PR build as well
