### ISSUE TITLE
Refactor drawer to be modal in full page view

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#1718]
Right now we use a drawer element, that should only really be used in the popup, not full screen.

We should refactor this so that it's a modal when in full screen.

@aulneau would be awesome if you could do this 🙏🏼

**Comment by Eshwari007** [comment]
@aulneau Can you share some input on what test steps I should see here with the refactor of the modal?

**Comment by aulneau** [comment]
> @aulneau Can you share some input on what test steps I should see here with the refactor of the modal?

Sure, for the PR https://github.com/blockstack/stacks-wallet-web/pull/1753, basically any "drawer" should appear as a modal when the screen is bigger than the default small extension view. The drawers are for switching network, switching accounts, etc.

**Comment by Eshwari007** [comment]
@aulneau Noticed an overlap of activity while testing the ticket
<img width="424" alt="Screen Shot 2021-09-29 at 3 10 03 PM" src="https://user-images.githubusercontent.com/38872890/135333286-e89df2ff-7456-41b2-8895-084f244dfe4d.png">

**Comment by Eshwari007** [comment]
Also noticed in this build when user is trying to send token,the below:

https://user-images.githubusercontent.com/38872890/135334304-3b513d5d-999b-4d59-9fdc-7372519279ea.mov

Do you want me to create the issues separately ? cc @aulneau

**Comment by Eshwari007** [comment]
The drawer refactor modal seems to be working fine.Test complete.

**Comment by aulneau** [comment]
> Also noticed in this build when user is trying to send token,the below:
> 
>  Screen.Recording.2021-09-29.at.3.14.51.PM.mov 
> Do you want me to create the issues separately ? cc @aulneau

Im not sure what this is showing? Can you elaborate?

**Comment by aulneau** [comment]
> @aulneau Noticed an overlap of activity while testing the ticket <img alt="Screen Shot 2021-09-29 at 3 10 03 PM" width="424" src="https://user-images.githubusercontent.com/38872890/135333286-e89df2ff-7456-41b2-8895-084f244dfe4d.png">

This is unrelated to this change

**Comment by Eshwari007** [comment]
@aulneau If you scroll the bar down in order to send some token,the scrollbar moves automatically by itself to upward motion thus prevents the user to select Preview

**Comment by kyranjamie** [comment]
what Esh found is almost certainly scroll snap CSS added in messaging PR

**Comment by Eshwari007** [comment]
I'll create separate ticket for the issue found due to scroll snap CSS added in messaging PR
cc @aulneau @kyranjamie
