### ISSUE TITLE
Hiro Wallet not connecting to StackPunks

### ISSUE THREAD

**Issue by SaadTahirTintash** [blockstack/blockstack-app#1721]
I faced an issue when I was working on some front end code and using @stacks/connect API to connect my wallet account to my website. When the popup of Hiro Wallet shows up to select an account, I select one and it is stuck in loading that account. The popup remains there and nothing happens. I can close the popup and the connection is interrupted. I tried reinstallation’s as well as changing the browser but no use. I also tested an official website to connect my wallet to StacksPunks but that didn’t work either.
I got it connected by creating a new account completely and it is now working. 
Kindly resolve this issue as soon as possible. I want my old wallet back as I have published contracts on Testnet from that.
It is only happening with my one account.
I can share my mnemonic code as well

**Comment by markmhendrickson** [comment]
Thanks for this report. Is there any error in the developer console when clicking the first account?

**Comment by SaadTahirTintash** [comment]
> Thanks for this report. Is there any error in the developer console when clicking the first account?

No There are no errors. The screen keeps on loading an account when I select it. Nothing happens after that.

**Comment by SaadTahirTintash** [comment]
I am facing another issue. The contracts the I deployed with this wallet address cannot be called. Only the read-only methods are returning me values however the public functions are in Pending state for several hours. 

1. https://explorer.stacks.co/txid/0xec79a1a0f102c690574da19250944f1238f80ea52f06f41c8b6259f0550973f6?chain=testnet
2. https://explorer.stacks.co/txid/0x190a265e2856c04180c9c38076eb3f0653901ccbb072c6b23aa9383174d589df?chain=testnet
3. https://explorer.stacks.co/txid/0xe8c85ac062127b957064b5b6857e376fd705bddca0efb7ca63586c5838a33cac?chain=testnet

You can test out this contract to test `ST5HYHBZ6CH0DHENSVCRTGKJ0CGTDFN09DRT38YK.free-copper-orca`

**Comment by SaadTahirTintash** [comment]
I was able to connect to StacksPunks now using this account. It's weird that why I wasn't able to connect before. Like it took 5-6 days to make my wallet work. Can you please investigate why was it happening? Did you guys make any changes to Hiro Wallet as well?

**Comment by markmhendrickson** [comment]
I'm glad to hear it's resolved, but yes that's odd it wasn't happening before and now suddenly works. I suspect there may have been a transitory issue with the API, since I don't believe we made any relevant changes to the wallet this past week.

I'll close for now but we should reopen if we see this reported again and can collect more diagnostic information.
