### ISSUE TITLE
Transaction delay causes nonce issue and 'locked' wallet for many hours

### ISSUE THREAD

**Issue by exploriter** [blockstack/blockstack-app#1723]
I have gone through this issue on many occasions now over many weeks and it makes the network quite impotent for things like limited NFTs.

1. Initiate a transaction via the web wallet. The correct nonce is generated. Let's say, `285`.
2. A `txid` is created but it **does not show in the explorer** (nor, obviously, under _Activity_ in the wallet).
3. I initiate a second transaction a few minutes later and a new `txid` is generated which is shown in the explorer immediately with the next nonce; `286`.
4. Now I have nonce `285` (which is still not shown) and nonce `286` (which is 'pending' in the explorer).
5. If I try a third transaction, the web wallet goes back to nonce `285` and issues the same initial `txid`, which still does not show in the explorer.

And then I'm stuck; my wallet is useless for many hours. Even if I manually go to the next nonce (`287`) with a third transaction (and get a new `txid`), that will usually not show in the explorer either. But even if it does, it's moot because none of them will go through until that first `txid` that is missing in action shows up. 

When I come back 6 or so hours later it is usually resolved but everything that came after the missing `txid` either never shows up or fails because it's taken so long. Meanwhile, many other wallets and transactions are going through just fine in a timely manner. Even that second `txid` that is 'pending' would have gone through quite quickly if it weren't for the fact that the prior nonce is nowhere to be found for hours.

**Comment by exploriter** [comment]
Example from today trying to mint Stacks Pops. It seems totally random which ones are broadcast to the explorer and which are not as I manually increment the nonce past the first missing one. Meanwhile, not a single `txid` will confirm after one that is missing from the explorer.

- [txid w/ nonce 285](https://explorer.stacks.co/txid/0xb9c84a19e9454467fb51f5da3d072ab852d92ba40b8f4ac0197e8c26c210e65a) (missing from the explorer for 13 hours and counting...)
- [txid w/ nonce 286](https://explorer.stacks.co/txid/0x310712951def4b98a570f56db6a10ccad3ab5575db0653f1843f15d8d7d68d5a?chain=mainnet) ('pending')
- [txid w/ nonce 287](https://explorer.stacks.co/txid/0xe5c974066f66b60620f338100a95736f7db5dc204a5fe69245bca440a1ac0dca) (missing)
- [txid w/ nonce 288](https://explorer.stacks.co/txid/0x4db28f48684cbf3b40492d2c825c8d08f5c654f4034b600dc63857c425cc6ca1?chain=mainnet) ('pending')
- [txid w/ nonce 289](https://explorer.stacks.co/txid/0x6c0a4630edcde0c01886a12d7ec58330f33863a027d70d0aa7d1a779be4ad1ec?chain=mainnet) ('pending')
- [txid w/ nonce 290](https://explorer.stacks.co/txid/0x6f159069b5d5c6eed8a2661d4e8938112b2c5eba5ef1b35452eaeb28d3b25145?chain=mainnet) ('pending')
- [txid w/ nonce 291](https://explorer.stacks.co/txid/0x2d88d1d9546221e5eb3e8ddd06f85acdf1a7d43841b44226945cf3d69d2d0df0?chain=mainnet) ('pending')
- [txid w/ nonce 292](https://explorer.stacks.co/txid/0x526110082329c3ff8f88c6e08892efb88528abab521fd5333da6de80b9102475) (missing)

**Comment by exploriter** [comment]
Some more context. If I try a different type of transaction (instead of minting a Stacks Pop NFT and try a STX transfer), the wallet obviously defaults to the first missing nonce, `285`, and I get a 'conflicting nonce' error.

**Comment by exploriter** [comment]
Perhaps related to https://github.com/blockstack/stacks-wallet/issues/921 and #1715.

**Comment by 314159265359879** [comment]
I have found that sometimes (or all the time?) these transactions get mined even though they do not appear in the explorer or the "activity" tab of the Hiro Wallet extension for web. 
This behavior seems unrelated by how full the mempool is.

**Comment by exploriter** [comment]
Interesting update.

The original `txid` w/ nonce `285` that did not show in the [stacks.co explorer](https://explorer.stacks.co/txid/0xb9c84a19e9454467fb51f5da3d072ab852d92ba40b8f4ac0197e8c26c210e65a), **_did_** show up immediately in the [planbetter.org explorer](https://explorer.planbetter.org/txid/0xb9c84a19e9454467fb51f5da3d072ab852d92ba40b8f4ac0197e8c26c210e65a). However, after about 2 hours it dropped from there and is now showing as "Transaction not found" in both explorers.

So, I tried a nonce `285` transaction again for a Stacks Pop and this time, it produced [a new `txid`](https://explorer.stacks.co/txid/0xd4ddcf6ecfaf0f3371ade1cbf983c9f8893cfec69f411d8f2e6609d373854309). But as before, it is **_not_** showing in the stacks.co explorer, and it **_is_** in the [planbetter.org explorer](https://explorer.planbetter.org/txid/0xd4ddcf6ecfaf0f3371ade1cbf983c9f8893cfec69f411d8f2e6609d373854309). I imagine the same series of events will occur and it will eventually show up as not found in the latter explorer, too.

Either way, unless I can get a transaction with nonce `285` to successfully broadcast to the stacks.co explorer, my wallet is effectively useless (as are all pending/missing transactions after nonce `285`).

**Comment by jeekwan** [comment]
That's very interesting and detailed findings. I've had the same issues too with what you're describing (however I hadn't taken note of the nonce exactly). What I would add is that its not the "wallet" that's locked up, but just the specific account within the wallet. I have a few accounts in the same Hiro Wallet and tried two transactions from Account 2 to mint Stacks Pops and both transactions don't appear, then switched to Account 4 (within same wallet) and minted one successfully while the other 2 transactions still haven't appear in stacks.co explorer. Didn't realise could check the Planbetter.org explorer but will take note to test that out next time.

**Comment by 314159265359879** [comment]
@gigawatson what version of the wallet are you on?

And have you tried making a new transaction and editing the nonce manually to fill in gaps (wallet version 2.16 and up)?

**Comment by markmhendrickson** [comment]
I suspect that this is indeed related to #1715, which links to a private Hiro DevOps issue that in turn links to the following public issue with details about an API fix for transaction propagation issues: https://github.com/blockstack/stacks-blockchain-api/issues/765

Essentially the API isn't propagating transactions reliably, so the wallet and explorer alike are unable to show some mempool / pending transactions quickly and reliably in their UIs. 

PlanBetter is running the same code for their own API instance to power their own Explorer instance, so presumably they're running into this issue as well, but it's not affecting transactions 1:1 with those affected by Hiro's API instance.

The client-side enhancement / patch we intend to release soon with https://github.com/blockstack/stacks-wallet-web/issues/1715 should in theory help prevent nonces from getting out of sorts, even with these API-side propagation issues.

I'll put this issue on our board so we can be sure to QA that fix by recreating the scenario you describe most exactly.

**Comment by exploriter** [comment]
> @gigawatson what version of the wallet are you on?

The problem persists with `v2.16.0` on Chrome and `v2.17.0` on Firefox.

> And have you tried making a new transaction and editing the nonce manually to fill in gaps (wallet version 2.16 and up)?

What gaps? My last successful transaction was nonce `284`. The problem began with `285` not being broadcast to the explorer. If I attempt to send any other transaction the wallet sets the nonce to `285` and I get a "nonce conflict" error.

**Comment by exploriter** [comment]
@markmhx 

What am I to do at this point? The previous "nonce issue" was resolved by pushing the UI change to the wallet to allow people to adjust the nonce manually but this issue is different and not resolved by adjusting nonces. 

I am now 23 hours without the ability to transact at all. My last successful nonce was `284`. 

The next nonce, `285`, [will not show in the mempool](https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool?sender_address=SP19WSDJWTH4CW3YG554XS5CAXJJGAN83P8CFZ4K1) and yet I get the "nonce conflict" error in the web wallet when trying another transaction with nonce `285`.

**Comment by gigawatson** [comment]
When I look here: https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool?sender_address=SP19WSDJWTH4CW3YG554XS5CAXJJGAN83P8CFZ4K1

... nonce `285` is not there, yet I get a "nonce conflict" error in the web wallet when trying another transaction with nonce `285`.

**Comment by exploriter** [comment]
Some patterns I've noticed...

1. If a transaction gets picked up by the API and is shown on the explorer, my average confirmation time is 25min.
    - Same if a transaction does not hit the API and is missing from the explorer if I DO NOT initiate another transaction and just wait for the (missing) transaction to show up _confirmed_.
2. The moment a transaction does not show up in the explorer AND I initiate another transaction by manually advancing the nonce +1 past the missing transaction's nonce (or the web wallet does if for me), my average time to confirmation jumps to 5 hours.
    - Sometimes as high as 24 hours when use is high—like when another 10K mint NFT hits the market.
    - This is the case even with very high fees set prior to initiating the (missing) transaction.
3. About 80% chance a transaction will not show up based on ~60 transaction attempts over the last 72 hours.

**Comment by exploriter** [comment]
What is this?

![CleanShot 2021-09-19 at 17 22 34@2x](https://user-images.githubusercontent.com/67083853/133947845-e95e9438-3788-493d-a7e4-3f75fc85f8fb.png)

**Comment by markmhendrickson** [comment]
@gigawatson I'm not seeing that "Non-canonical" message in either the [Hiro](https://explorer.stacks.co/txid/0x8ec8db0bad9ea47fe03b1ab2ec6f9102db7bb8e40e9862c0db865066eb0c980c?chain=mainnet) or [PlanBetter](https://explorer.planbetter.org/txid/0x8ec8db0bad9ea47fe03b1ab2ec6f9102db7bb8e40e9862c0db865066eb0c980c) explorers when checking now, so it appears to have been temporarily displayed? It's the first I've ever seen it in general. @aulneau may have insight on what it means.

> The moment a transaction does not show up in the explorer AND I initiate another transaction by manually advancing the nonce +1 past the missing transaction's nonce (or the web wallet does if for me), my average time to confirmation jumps to 5 hours.

I'm not sure why these wait time differences would be the case, but I'd suggest filing this observed behavior directly [in the API repository](https://github.com/blockstack/stacks-blockchain-api/issues/new) since I suspect the potential problem and solution are API or node-side.

> What am I to do at this point? The previous "nonce issue" was resolved by pushing the UI change to the wallet to allow people to adjust the nonce manually but this issue is different and not resolved by adjusting nonces.

I'm seeing the nonce listed now on [your address page](https://explorer.stacks.co/address/SP19WSDJWTH4CW3YG554XS5CAXJJGAN83P8CFZ4K1?chain=mainnet) as `308`. All pending or "in microblock" transactions appear to have nonces of `307` or below. 

I'm inclined to suggest you try another transaction, this one with `307`, to see if it succeeds (though I realize you've tried this manual setting approach before and it hasn't worked, so I'm 🤞 here a bit). Want to give that a go?

We'll be investigating and discussing these issues in general as a team as our top priority this week.

**Comment by aulneau** [comment]
a non-canonical transaction means the transaction has been included a fork, and as such is no longer part of the "canonical" chain. I don't have a lot of depth when it comes to the forking mechanisms, but maybe @zone117x can chime in if he has a free minute.

**Comment by thambisrinath** [comment]
I have pretty similar issue as well. When minting stack pops, nonce was not incrementing, so I incremented by one and submitted. However, my transactions were taking 10 to 15 hours to complete. But now, it's been over 34 hrs and still not processed. What I have noticed though is that all the stacks pop transactions that I have initiated are not showing up in Hiro Wallet but they are showing in web explorer and in mobile wallet.

Secondly, I have one transaction with nonce 95 that I have initiated to transfer STX from one of my wallet to another wallet of my own. This transaction had a fee of 0.00018 fee where as for all my stacks pop transactions fees are significantly higher 0.13, 0.26 etc. So, I went to web wallet and tried to increase the fee for nonce 95 but it gives me an error "incorrect nonce". So, I went back to all my transactions and could see that there was another stacks pop transaction with the same nonce already confirmed in anchor block. 

What can I do to fix this issue? I have about a day left, before I could submit my MIA for stacking.

**Comment by thambisrinath** [comment]
> I have pretty similar issue as well. When minting stack pops, nonce was not incrementing, so I incremented by one and submitted. However, my transactions were taking 10 to 15 hours to complete. But now, it's been over 34 hrs and still not processed. What I have noticed though is that all the stacks pop transactions that I have initiated are not showing up in Hiro Wallet but they are showing in web explorer and in mobile wallet.
> 
> Secondly, I have one transaction with nonce 95 that I have initiated to transfer STX from one of my wallet to another wallet of my own. This transaction had a fee of 0.00018 fee where as for all my stacks pop transactions fees are significantly higher 0.13, 0.26 etc. So, I went to web wallet and tried to increase the fee for nonce 95 but it gives me an error "incorrect nonce". So, I went back to all my transactions and could see that there was another stacks pop transaction with the same nonce already confirmed in anchor block.
> 
> What can I do to fix this issue? I have about a day left, before I could submit my MIA for stacking.

By the way, this nonce 95 transaction was submitted at 10:32PM on 9/18, more than 57 hours ago. Transactions not processed with in 256 blocks are supposed to cancel but it's not been cancelled yet. 

Appreciate any help in this regards. Here is the transaction -
https://explorer.stacks.co/txid/0x267e6dfe3747363320e73626f3150c7bd7e98da430a9cb39fd15492a066c06c6?chain=mainnet

**Comment by exploriter** [comment]
@markmhx Yes, the "non-canonical" message showed up that way for about an hour before being properly confirmed.

Apologies for the slow update. After about 24 hours I was finally able to get nonce `285` to take and it slowly corrected itself over the next 4-5 hours. At this point, I'm doing one transaction at a time (unless the transaction is broadcast) and waiting for confirmation before initiating another.

**Comment by 2snEM6** [comment]
Not sure if this is entirely related but the Planbetter node has 5 pending txs on mempool that have already been confirmed according to the stacks.co explorer.

https://stacks-node-two.planbetter.org/extended/v1/tx/mempool?sender_address=SP3TDKYYRTYFE32N19484838WEJ25GX40Z24GECPZ

**Comment by 2snEM6** [comment]
> Not sure if this is entirely related but the Planbetter node has 5 pending txs on mempool that have already been confirmed according to the stacks.co explorer.
> 
> https://stacks-node-two.planbetter.org/extended/v1/tx/mempool?sender_address=SP3TDKYYRTYFE32N19484838WEJ25GX40Z24GECPZ

Stacks.co API reports 0 txs on mempool for that address: https://stacks-node-api.stacks.co/extended/v1/tx/mempool?sender_address=SP3TDKYYRTYFE32N19484838WEJ25GX40Z24GECPZ

**Comment by beguene** [comment]
Those 2 api endpoints are now in sync (0 pending txs)
https://stacks-node-api.stacks.co/extended/v1/tx/mempool?sender_address=SP3TDKYYRTYFE32N19484838WEJ25GX40Z24GECPZ
https://stacks-node-api.stacks.co/extended/v1/tx/mempool?sender_address=SP3TDKYYRTYFE32N19484838WEJ25GX40Z24GECPZ

**Comment by 2snEM6** [comment]
> Those 2 api endpoints are now in sync (0 pending txs)
> https://stacks-node-api.stacks.co/extended/v1/tx/mempool?sender_address=SP3TDKYYRTYFE32N19484838WEJ25GX40Z24GECPZ
> https://stacks-node-api.stacks.co/extended/v1/tx/mempool?sender_address=SP3TDKYYRTYFE32N19484838WEJ25GX40Z24GECPZ

I think you meant comparing Planbetter's one to stacks-node-api one. I had to manually delete those transactions from the mempool table in postgres from our PB's nodes. The transactions were stuck in "pending" on the mempool for more than 12h, and I checked if those transactions were confirmed into a block and they indeed were confirmed.

**Comment by Eshwari007** [comment]
Transactions are viewable almost immediately and are in 'Queued" Status.
Nonce has been tested for each consecutive transactions
Various tokens and STX has been tested in the use case as well

Test passed .Moving ticket to QA Done.
