### ISSUE TITLE
Display optional server-side message

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1730]
As discussed in https://github.com/blockstack/stacks-wallet-web/discussions/1411

To display messages to users as needed based on network conditions, bugs, etc. that aren't resolved yet.

**Comment by jasperjansz** [comment]
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/📏Spec?node-id=516%3A7608

**Comment by Eshwari007** [comment]
The full mode looks good as it give user to learn more and also close the dialogue as needed
