### ISSUE TITLE
Nonce Issue

### ISSUE THREAD

**Issue by thambisrinath** [blockstack/blockstack-app#1731]
I have a transaction with nonce 95 stuck for 2 days and all the transactions after that are in the queue including my MIA stacking transaction.... Apparently there is another transaction with nonce 95 that went through... so, looks like this 95 nonce transaction is an orphan... how can I cancel this transaction, so I can let other transactions to process? Any help in this regards is greatly appreciated. It says transactions gets auto cancelled after 256 blocks but I think it went past 256 blocks long back!!

This is where my transactions are stuck...
https://explorer.stacks.co/txid/0x267e6dfe3747363320e73626f3150c7bd7e98da430a9cb39fd15492a066c06c6?chain=mainnet

Appreciate if anyone can help in this regards since I have less than a day to get this resolved and submit my MIA for stacking.

**Comment by markmhendrickson** [comment]
It appears the transaction you linked above is now cleared from network. If you're still in this sort of situation, you can submit a new transaction with a manually set nonce of whatever value you see on your address's Explorer page.

See https://www.hiro.so/questions/transactions-advanced-settings
