### ISSUE TITLE
Fix React rules of hooks issues

### ISSUE THREAD

**Issue by beguene** [blockstack/blockstack-app#1739]
Our code breaks the React rule of hook in a few components.
https://reactjs.org/docs/hooks-rules.html
This task is to fix those and add the eslint-plugin-react-hooks to enforce it in the future.
Fixing this will help prevent bugs and React re-render issues.

**Comment by kyranjamie** [comment]
Can you list the components that break these rules @beguene?

**Comment by beguene** [comment]
stacks-wallet-web/src/common/hooks/account/use-account-names.ts
stacks-wallet-web/src/common/hooks/use-onclickoutside.ts
stacks-wallet-web/src/components/asset-item.tsx
stacks-wallet-web/src/components/link.tsx
stacks-wallet-web/src/components/tooltip.tsx
