### ISSUE TITLE
Unable to Sign Out

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/blockstack-app#1740]
Ran into this today with `v2.17.0` in the Brave browser. My wallet is on the "Enter your password" screen and when I click the three dots then Sign Out, nothing happens.

![image](https://user-images.githubusercontent.com/9038904/134539441-c23b3c62-bcfc-4723-bf55-7153d8ce6041.png)

Nothing in the console logs either. I do see the URL changed at the top to:

`chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.html#/sign-out`

Completely removed it, reinstalled it, logged back in and tried again -  now I see there's a new modal! Maybe that's why I couldn't directly sign out?

![image](https://user-images.githubusercontent.com/9038904/134539878-53a06a25-86d4-4d19-9553-c80fbcd6009f.png)

**Comment by kyranjamie** [comment]
Good find. It only works when you're in the unlocked state, as the `sign-out` route is a child of the home screen.

**Comment by Eshwari007** [comment]
@kyranjamie Tested the issue in Brave and Chrome.Test passed
