### ISSUE TITLE
Extension are not working correctly for MIA deposit & withdrawal from Hiro wallet

### ISSUE THREAD

**Issue by KriptoFati** [blockstack/blockstack-app#1744]
Hello guys. I have some issue about withdrawing MIA from my Hiro Wallet to Okcoin. On Chrome i can see MIA on withdrawal list click on it, paste the address and memo from Okcoin but nothing happened. On Brave same issues happened. On Firefox i cant even see MIA on withdrawal list. I cant do this process for 2 weeks. What should be my problem?

**Comment by markmhendrickson** [comment]
Can you confirm this is a problem in version v2.18.0 of the wallet in particular? This is the latest we pushed to the Chrome and Firefox stores this past week, so if you've installed from there, it should have updated automatically (or will soon if it hasn't yet).

**Comment by KriptoFati** [comment]
Yes it is the latest version v2.18.0. 
When i click preview after adding my address and memo, nothing happens. I did everything. Tried on firefox and brave. In firefox v2.17.0 was installed. Upgraded now. MIA is now on transfer screen but still nothing happened when i clicked preview. Using windows 10. Browsers are working perfectly except Hiro wallet on MIA transfers. I want to trade MIA at Okcoin to increase mine. Also will keep stacking after cycle 3. But i locked up in here.
![image](https://user-images.githubusercontent.com/91287666/134864320-0d9a8b96-81a6-410d-bde1-cc7c45423a14.png)

**Comment by markmhendrickson** [comment]
Thanks for the additional information. We'll investigate 👍

**Comment by fbwoolf** [comment]
I just successfully completed sending MIA to/from our Hiro wallet to okcoin in all browsers successfully with no problem. I cannot reproduce this. Maybe restart your computer and try again? This might be a problem on your end?

**Comment by fbwoolf** [comment]
@markmhx I am going to move this into QA bc I can't reproduce it.

**Comment by fbwoolf** [comment]
@Eshwari007 can you see if you can reproduce this, I can't.

**Comment by Eshwari007** [comment]
@fbwoolf Am able to view/select MIA in all of the browsers as well-Chrome,FF and Brave.
@timstackblock Can you kindly test the transfers between OKcoin to WW,my account with Okcoin hasnt been confirmed yet.

**Comment by timstackblock** [comment]
@Eshwari007 my account is still pending as well I have a support ticket in to see why mine is still on hold. As soon as its unlocked I can test.

**Comment by KriptoFati** [comment]
Finally found the problem. Im from Turkey and my Windows is Turkish. When i change my language into English everything becomes normal. Thanks for your help.

**Comment by fbwoolf** [comment]
> Finally found the problem. Im from Turkey and my Windows is Turkish. When i change my language into English everything becomes normal. Thanks for your help.

That is great feedback, thanks! Happy this is resolved for you!

**Comment by fbwoolf** [comment]
@markmhx this is helpful to know, I didn't realize a translation issue would cause problems.

**Comment by markmhendrickson** [comment]
That's interesting. Do we know how the translation issue is affecting things exactly? @Eshwari007 @timstackblock could you perhaps test with Turkish turned on for your browser and see if you get the same result?
