### ISSUE TITLE
Post conditions token metadata even if user doesn't have token in their wallet

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#1745]
We don't currently query token metadata to display in post conditions if the user doesn't have that token in their wallet. This creates some funkiness in the UI for some apps (see linked issue as an example). Data displayed in the UI isn't correct if a user selects a token to swap that they don't have in their wallet (ex. decimals aren't parsed and the ticker is incorrect).

https://github.com/blockstack/stacks-wallet-web/issues/1700#issuecomment-926134817

**Comment by fbwoolf** [comment]
@aulneau am I reading this correctly that only `canTransfer` is set to true for the STX token?
https://github.com/blockstack/stacks-wallet-web/blob/b470c7a574b67e3dfc9547b03c13300222026ac5/src/store/assets/utils.ts#L45

I am trying to understand `useTransferableAssets` a bit better:
https://github.com/blockstack/stacks-wallet-web/blob/b470c7a574b67e3dfc9547b03c13300222026ac5/src/common/transactions/postcondition-utils.ts#L146

**Comment by fbwoolf** [comment]
I found where it is setting `const canTransfer = meta?.ftTrait;`

**Comment by Eshwari007** [comment]
@fbwoolf Can you shed some steps to test the issue?

**Comment by fbwoolf** [comment]
> @fbwoolf Can you shed some steps to test the issue?

There is a testing instruction on the PR. Just make sure all the post conditions render correctly in the test-app. Try to test that one renders decimal amount and ticker correctly even if you don't have that token in your wallet. Images on PR should help.

**Comment by Eshwari007** [comment]
@fbwoolf Here are the findings : I tested the ticket with testnet demo app and upon selection of the contracts in demo app ,the extension isnt opening up.The popup seems to appear in flash and returns a square symbul near the Hiro ext.
Attaching the video and error logs

https://user-images.githubusercontent.com/38872890/135522134-94a707bc-0fbb-4b9f-95a9-89547cf41fef.mov

<img width="1413" alt="Screen Shot 2021-09-30 at 3 51 00 PM" src="https://user-images.githubusercontent.com/38872890/135522153-6871b551-ed2a-422c-8d6c-5eaf04fc7737.png">

**Comment by fbwoolf** [comment]
@Eshwari007 what version are you testing? I am not seeing that behavior on my end.

**Comment by Eshwari007** [comment]
<img width="860" alt="Screen Shot 2021-09-30 at 4 06 52 PM" src="https://user-images.githubusercontent.com/38872890/135523214-ae0d8ba0-87b5-48fb-a9fb-9151b5b5b592.png">
 cc @fbwoolf

**Comment by Eshwari007** [comment]
@fbwoolf I deleted the extension and reinstalled the extension.Its seems to work now.But am going to try the same steps earlier to see if I can reproduce the issue
<img width="1345" alt="Screen Shot 2021-09-30 at 4 10 53 PM" src="https://user-images.githubusercontent.com/38872890/135523736-cc4011cf-4927-45fe-8940-eb348f38759d.png">

**Comment by fbwoolf** [comment]
@Eshwari007 ok, great. I just downloaded the PR build and was trying fresh too and worked for me. Let me know if you can reproduce again but maybe have just needed a fresh start up.

**Comment by Eshwari007** [comment]
@fbwoolf Am able to reproduce the issue,upon selecting 'Contract Deploy' and submit /confirm it.When I try to select the ext,received the below:
<img width="263" alt="Screen Shot 2021-09-30 at 5 13 50 PM" src="https://user-images.githubusercontent.com/38872890/135531257-026fb143-04c7-40ab-9771-6698c7499f47.png">

**Comment by Eshwari007** [comment]
<img width="1310" alt="Screen Shot 2021-09-30 at 5 16 12 PM" src="https://user-images.githubusercontent.com/38872890/135531322-87e3d34a-2f25-482d-ae17-c5b1fcbbc939.png">
cc @fbwoolf

**Comment by fbwoolf** [comment]
@Eshwari007 ok great, that is helpful. Yep, that is from my changes. I will fix!

**Comment by fbwoolf** [comment]
@Eshwari007 actually, I don't think anything with a tx would be from me? I bet that is on main? Let me check.

**Comment by fbwoolf** [comment]
@Eshwari007 I can repro on my end so will investigate it.

**Comment by fbwoolf** [comment]
Seems to be my branch and not on main, so that is good.

**Comment by fbwoolf** [comment]
This is happening in `local-tx-item` which seems odd to me since that was just released. I bet I tested the old version from the Chrome download and this is on main. Will try to test released version.

**Comment by fbwoolf** [comment]
@Eshwari007 I just confirmed this is on main!

**Comment by fbwoolf** [comment]
I will create an issue

**Comment by fbwoolf** [comment]
@Eshwari007 is this one good to go since the bug was fixed on main?

**Comment by Eshwari007** [comment]
Test passed .Moving it to QA Done
