### ISSUE TITLE
Use non-persistent background script

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#1746]
Manifest v2 Web Extensions run with background scripts that either persist, or are destroyed when determined as idle by the browser. Non-persistent extensions are triggered by events.

The Hiro Wallet uses a persistent background script, primarily to keep the unencrypted key in memory longer, minimising users having to enter their passwords on return to the wallet.

Using an in-memory store isn't advised with a non-persistent bg script, as the values are lost when the script becomes idle

https://github.com/blockstack/stacks-wallet-web/blob/994ade33faf2358f776e6d0bdaf5cb1f53b0bc4a/src/background/vault.ts#L44-L45

There are a few reasons why we should flip this to using a non-persistent "event-driven" background page:

- **Best practice**: [Chrome's docs explain why](https://developer.chrome.com/docs/extensions/mv2/background_migration/) the default option should be to build non-persistent background scripts. They use fewer resources etc. We don't really need to have a persistent background script.

- **Preparation for Manifest v3**: Manifest v3 extensions use Service Workers, rather than background scripts. These work by passing events between the worker and the extension. Using an event-driven pattern now will ease our transition to the newer extension format.

- **Preparation for [Safari mobile, iOS15 extensions](https://developer.apple.com/safari/extensions/)**: Safari mobile extensions _only_ work with non-persistent background scripts.

These changes would have a relatively minimal impact on UX. A simpler implementation would result in more wallet unlock actions. There are other mechanisms we could use to cache the key, though it might be more secure to require password more regularly anyway.

**Comment by markmhendrickson** [comment]
Would this also increase security somewhat given the increase in lock frequency?

**Comment by kyranjamie** [comment]
To some extent, yeah. The less time your wallet's unlocked, the less time a malicious actor has to access your computer and withdraw funds—though that isn't the motivation for the switch.

**Comment by markmhendrickson** [comment]
Is this still relevant?

**Comment by kyranjamie** [comment]
No, closed with MV3 release
