### ISSUE TITLE
Instrument event metrics

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1748]
- [x] Install Segment and perform initial setup.

The app should trigger a "View [route]" event every time the user opens a new view with a "time to render" parameter that measures the complete paint time in milliseconds.

Additionally the app should trigger events for the following actions (priority ones in **bold**):

- **Generate new Secret Key**: When user generates new Secret Key
- Authenticate application: When user authenticates application (attributes: app_domain => string)
- Start active session: When user opens any view for first time or after 4 hours since the last view open
- Copy Secret Key to clipboard: When user selects option to copy Secret Key to clipboard
- Copy address to clipboard: When user selects option to copy address to clipboard
- Submit valid Secret Key: When user submits a valid Secret Key for sign in
- Submit invalid Secret Key: When user submits a valid Secret Key for sign in
- Submit valid password: When user submits a valid password for sign up or in
- Submit invalid password: When user submits a valid password for sign up or in
- Select asset for send: When user selects asset for send form
- Enter amount for send: When user enters any value into amount input for send form
- Select maximum amount for send: When user selects maximum value for send form
- Enter recipient for send: When user enters any value into recipient input for send form
- Enter memo for send: When user enters any value into memo input for send form
- Choose to view balances: When user chooses to view list of asset balances tab
- Choose to view activity: When user chooses to view recent activity tab
- Choose to create account: When user chooses to create new account from app menu
- Choose to change network: When user chooses to change network from app menu
- Change network: When user selects network
- Add network: When user submits new network
- Lock session: When user locks session manually
- Sign out: When user signs out manually
- View transaction: When user selects transaction for view in Explorer
- **Broadcast transaction**: When user submits transaction for broadcast
- **Transaction state change**: When outbound or inbound transaction is recognized with new state (attributes: type => inbound|outbound, state => pending|microblock|anchor|failed, time_since_last_state => time in milliseconds)
- Toggle transaction signing inputs: When user opens or closed view of transaction signing inputs (attributes: action => open|close)
- View API error (attributes: code => number, message => string)

All events should have these default properties:

- Anonymous ID for user by account
- Authenticated (boolean): Indicating whether the user has authenticated or not upon triggering event
- Route (string): Path of current view upon triggering event
- User agent (string)
- Version (string)
- Timestamp
- Selected network (string: mainnet, testnet, devnet or other)
- Has STX (boolean): Whether current account has positive STX balance
- Has FT (boolean): Whether current account has positive non-STX FT balance
- Has NFT (boolean): Whether current account has one or more NFTs

**Comment by agraebe** [comment]
with the data above, would we be able to distinguish between sign up (first time to auth into an app) and sign in (consecutive auths)?

**Comment by markmhendrickson** [comment]
Yep, "Generate new Secret Key" is for sign up and "Submit valid Secret Key" for sign in (to the wallet). "Authenticate application" is specifically for authenticating apps.

**Comment by fbwoolf** [comment]
@beguene a P1 bug came up so I wasn't able to start this yet.

**Comment by beguene** [comment]
@fbwoolf No issue, I will do it today.

**Comment by beguene** [comment]
Note that User Agent, Timestamp and Anonymous ID are automatically handled by segment.

**Comment by beguene** [comment]
@Eshwari007 @timstackblock I made the changes suggested by @markmhx i.e. moving the diagnostics dialog to the beginning of the user flow (before wallet creation).

**Comment by beguene** [comment]
All implemented event are listed in the top of the PR
https://github.com/hirosystems/stacks-wallet-web/pull/1784

**Comment by timstackblock** [comment]
User agent on chrome reads as follows: 
```userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"```

**Comment by timstackblock** [comment]
I created the issues below to capture the bugs I found testing this

https://github.com/hirosystems/stacks-wallet-web/issues/1892
https://github.com/hirosystems/stacks-wallet-web/issues/1893
https://github.com/hirosystems/stacks-wallet-web/issues/1894
https://github.com/hirosystems/stacks-wallet-web/issues/1895
https://github.com/hirosystems/stacks-wallet-web/issues/1896
https://github.com/hirosystems/stacks-wallet-web/issues/1897

**Comment by beguene** [comment]
@timstackblock @Eshwari007 I made some new changes, can you have a look at this ?

**Comment by andresgalante** [comment]
@beguene please have a final look and merge this PR

- Can we fire an event to understand if the once calculation is being used?
- We are not going to implement the change transaction state when the user is not in the app
