### ISSUE TITLE
Overlapping message in Activity tab

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1756]
User is testing a PR build:v2.18.0.975

User notices upon testing the WW using the Stacks test app,there were a overlapping of activity details in the tab
Attaching the screenshot for perusal
<img width="424" alt="overlapping activity details" src="https://user-images.githubusercontent.com/38872890/135338264-35b3faea-4190-40af-9692-d28d2fe5ff70.png">

**Comment by fbwoolf** [comment]
@landitus any preference on how to handle possible long text here? Should we do ellipses instead of wrapping it so there are always just two lines for the activity list item?

**Comment by fbwoolf** [comment]
Putting up a PR for this so you can give feedback on the PR.

![Screen Shot 2022-05-03 at 1 37 57 PM](https://user-images.githubusercontent.com/6493321/166520478-0a2c83d8-3df3-4571-ba6a-b5cd641994a8.png)

**Comment by fbwoolf** [comment]
@timstackblock @Eshwari007 the two closed issues assigned to me in the QA column were merged into dev, so they can be tested once a release PR is created. There is no need to test them on the PR branch.
