### ISSUE TITLE
Remove disabled regtest option from networks list

### ISSUE THREAD

**Issue by agraebe** [blockstack/blockstack-app#1763]
As announce here: https://forum.stacks.org/t/hiro-is-decommissioning-the-regtest-network/12444

Repo mentions for regtest: https://github.com/blockstack/stacks-wallet-web/search?q=regtest

cc @markmhx @andresgalante

**Comment by markmhendrickson** [comment]
This is related to https://github.com/blockstack/stacks-wallet-web/issues/1580 in that we should replace the Regtest option with DevNet, correct?

**Comment by agraebe** [comment]
> This is related to #1580 in that we should replace the Regtest option with DevNet, correct?

absolutely right!

**Comment by markmhendrickson** [comment]
Regtest will begin decommissioning this week: https://github.com/hirosystems/devops/issues/763#issuecomment-964243878
