### ISSUE TITLE
Activities tab shows transaction as queued even after they have been mined

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#1769]
This is on testnet
Environment: Windows 10, Brave browser. Opening the wallet (version 2.19.2) in a new tab and doing a hard refresh made no difference. 

![image](https://user-images.githubusercontent.com/33360391/135833326-fb7924d4-045d-4a4f-812c-dac4ba5f45c5.png)

I think the queued instances in the overview should go away ounce they are confirmed/failed which all these transactions have been. 

the address: https://explorer.stacks.co/address/ST2PBEZB3ZPHJE1XJHFQKGF6E08SV29K96WCRJA13?chain=testnet
transactions with nonce 11, 12, 13 

I will post here if I see this again to get an idea of how it can be reproduced.

**Comment by markmhendrickson** [comment]
Thanks for the report! We'll investigate.

**Comment by 314159265359879** [comment]
This transaction was queued at first because it could not be found in the mempool but now that it is in the mempool and shown as such should it still be up there as queued, this looks redundant and I think this is not how it was intended. 
![image](https://user-images.githubusercontent.com/33360391/135835432-ea82b1df-3eec-460f-ba2a-cb3e6fe5f345.png)

**Comment by nas3rr** [comment]
All transactions (both failed and successful) that took place since yesterday morning are queued, been more than 24 hours and the situation is the same. Is this expected?

**Comment by Eshwari007** [comment]
Test passed from QA end as well
