### ISSUE TITLE
inconsistent state when transactions deployed on two networks

### ISSUE THREAD

**Issue by aviculturist** [blockstack/blockstack-app#1770]
Deploy a contract on testnet, while waiting for it to confirm, switch to regtest and deploy a contract.
Both contract transactions get stuck in Queued even if they eventually fail or succeed, they end up in both lists. See screenshot below.
<img width="344" alt="screenshot" src="https://user-images.githubusercontent.com/88842484/135923191-aa6f9592-e711-46ed-aa36-1d9daa5623f9.png">
.

**Comment by markmhendrickson** [comment]
I suspect this may result from the same underlying issue as https://github.com/blockstack/stacks-wallet-web/issues/1769

**Comment by Eshwari007** [comment]
At the moment Contract call is failing and an investigation ticket has been created :https://github.com/blockstack/stacks-wallet-web/issues/1778
Contract deploy however passed and has no issues with the state's
