### ISSUE TITLE
The wallet shows blank when a user is not already logged into the extension

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#1782]
when trying to use the wallet on [Stackstarts](https://www.stacksart.com/) I noticed that while I was logged out and click on the action the buy an nft the windows came up blank.

I am using Chrome and wallet `2.19.2`
`
<img width="732" alt="Screen Shot 2021-10-06 at 09 26 34" src="https://user-images.githubusercontent.com/1832037/136223425-849c51c9-7208-480f-8227-6e0e251d08b0.png">
<img width="1033" alt="Screen Shot 2021-10-06 at 10 34 22" src="https://user-images.githubusercontent.com/1832037/136223445-5e898cde-3a71-430c-9acc-aadd1eba4287.png">

**Comment by andresgalante** [comment]
@Eshwari007 @timstackblock Can you please reproduce this bug and confirm this bug and understand when it happens please?

**Comment by Eshwari007** [comment]
Yes,the issue was reproducible both from my end and @timstackblock

**Comment by timstackblock** [comment]
This is working as expected now

**Comment by Eshwari007** [comment]
Tested from my end as well for sanity purposes and test passed

**Comment by markmhendrickson** [comment]
Note that if anyone encounters this, they can select the Hiro Wallet extension icon in their browser and enter their password:

![image](https://user-images.githubusercontent.com/28991/136571020-cb18e81b-1985-423a-b1c5-b7455c13a4b8.png)

They should then be able to proceed with whatever action they were trying to do / transaction they were trying to sign from within an app.
