### ISSUE TITLE
Stella token tx is not accurate in explorer upon tx in Web Wallet

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1787]
User is testing;#1747
https://explorer.stacks.co/txid/0x7eab8eade7112a46444593f3c671deb7a7d840a7057cc98748184759cb6042af?chain=testnet
I transferred only 1 Stella but its indicating 
<img width="409" alt="Screen Shot 2021-10-07 at 2 09 49 PM" src="https://user-images.githubusercontent.com/38872890/136467914-294afc75-d83c-4373-a428-77f81c1c9ff8.png">
Same thing transferred 3.9 Stella but showing the below amount
<img width="890" alt="Screen Shot 2021-10-07 at 2 14 48 PM" src="https://user-images.githubusercontent.com/38872890/136468007-f6da87d9-fb3f-4316-b71b-9c8b852f8092.png">
https://explorer.stacks.co/txid/0x84517930e13e2ed43103731beef9f6e9da01aacf32416d7fcd1a274caf0dd829?chain=testnet

**Comment by beguene** [comment]
@Eshwari007 This is normal: stella token is a token with 9 decimals specified in the contract so amount of 1000000000 = 1 Stella Token

It was the same even before see this tx https://explorer.stacks.co/txid/0x6448dfc73f613b29a5f06a96fda81b3bd6feee1b511ee480cdc781e1d72f1134?chain=testnet

**Comment by Eshwari007** [comment]
@beguene This is a tx which transfered 1 Stella-8 days ago.If you look at the explorer -amount details its indicating only '1'
https://explorer.stacks.co/txid/0x4a648535e06bb21a3ebea8128f09137f9deb0a19bff838fc6aba2b6113896f0e?chain=testnet
