### ISSUE TITLE
fix misalignment on the activity feed's balance

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#1789]
The activity feed's balance number(?) are misaligned on the right

<img width="380" alt="Screen Shot 2021-10-08 at 09 32 48" src="https://user-images.githubusercontent.com/1832037/136557425-79e0496a-68f6-4c61-b0d6-8a2553a8637a.png">

**Comment by fbwoolf** [comment]
I fixed this while fixing the overlapping text in the activity list, so I'm going to reassign to myself and link to my open PR.
