### ISSUE TITLE
Speed up "Increase fee" interaction

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack-app#1790]
The buttons to increase fee in the wallet are slow - I thought they were just not working at first but seems like if you wait a bit the numbers do change. It feels unclear if the page is responding when trying to click the different fee options (1x, 2x, 5x) as nothing happens and there is no hover reaction (in some instances it just seemed like 2x remained highlighted when clicking 5x).

**Comment by markmhendrickson** [comment]
@GinaAbrams I'm closing this out, but please comment if these interactions still feel slow to you and I'll reopen 🙏
