### ISSUE TITLE
Using a custom fee is not working

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#1792]
Reported by user and I reproduced the issue. Using the test-app, the custom fee does not change the fee being applied in the app.

Images provided by arkadiko:
![image](https://user-images.githubusercontent.com/6493321/136660154-7c6a7415-1841-4184-97bf-993bacc10936.png)

![image](https://user-images.githubusercontent.com/6493321/136660156-7a210365-f0c8-4a5d-ab3a-43e573f9fbbb.png)

**Comment by markmhendrickson** [comment]
cc @philipdesmedt

**Comment by philiphacks** [comment]
thanks! I'll follow along this issue and implement custom fees once fixed

**Comment by fbwoolf** [comment]
> thanks! I'll follow along this issue and implement custom fees once fixed

This was merged and will be released (hopefully today) with: https://github.com/blockstack/stacks-wallet-web/pull/1788

**Comment by philiphacks** [comment]
@fbwoolf awesome, that was fast! I'll try again when the wallet has been released 👀
