### ISSUE TITLE
StacksProvider not injected to local sites in dev mode

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-app#1795]
I was trying to fix a bug in the wallet last night and saw that if i'm running the wallet in dev mode, and trying to use an app that interacts with it which is also local (eg at localhost:3000), it seems that `StacksProvider` is no longer injected. 

These combinations work:
- local wallet in prod mode & local web app
- local wallet in dev mode & external web app (eg stacks-wallet-web.vercel.app)

This does not:
- local wallet in dev mode & local web app

**Comment by fbwoolf** [comment]
@aulneau do you think this has to do with this? https://github.com/blockstack/stacks-wallet-web/pull/1791 ...maybe I should revert updating the `webpack-dev-server` to test it a bit better? I am running into an error still w/ the test-app with HMR, not sure if related to what you are seeing?

![Screen Shot 2021-10-10 at 1 27 59 PM](https://user-images.githubusercontent.com/6493321/136709908-b71d5280-f97a-40f0-aac4-fc72ddd443ff.png)

**Comment by fbwoolf** [comment]
I bet it's bc I added the `background` to the excluded entries? Still getting familiar with what all the config is doing, but that would make sense if you are working off current `fix/webpack-dev-server`.

**Comment by kyranjamie** [comment]
So I'm pretty sure that this error is caused by issues relating to running two webpack instances at once. 

If you build the wallet and load that in, this doesn't happen. I'm working on a simplified webpack set up that builds on your changes @fbwoolf
