### ISSUE TITLE
Automatically update "Install from source" page with latest build

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1799]
Currently the URL for the latest build and indication of which version it is are hard-coded:

https://www.hiro.so/wallet/install-web-source

We should set up these values to automatically update so they don't fall behind.

**Comment by markmhendrickson** [comment]
@kyranjamie can you t-shirt this one given your knowledge of how the GitHub releases API / JS snippets work? And provide any quick guidance on how we could possibly tackle this, if you have it top of mind?

I'm labeling this as a P2 bug since presumably the few power users who want to build and install the latest version from source are unable to do so with our current instructions, which are out of date on the website and confusing / dysfunctional in the repo README.

**Comment by kyranjamie** [comment]
This is quite trivial. We can just adjust the script that's used for the desktop install from source on Webflow

**Comment by markmhendrickson** [comment]
The page now automatically updates the following button up top with the latest release's source-code URL:

<img width="760" alt="Screen Shot 2021-11-16 at 12 52 55" src="https://user-images.githubusercontent.com/28991/141980778-d997cbf7-ccef-4317-bc61-74afd71843a9.png">
