### ISSUE TITLE
Display standardized FT images (e.g. MIA)

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1800]
It appears as though despite supporting API-based metadata for standardized FT attributes, we aren't showing token images yet, such as for MiamiCoin:

![image](https://user-images.githubusercontent.com/28991/136791410-52d82536-ac9a-4dca-9ec0-0ceebd2fc976.png)

**Comment by markmhendrickson** [comment]
@andresgalante Can you help track down what's technically necessary to make this enhancement given where things stand?

**Comment by pstan26** [comment]
On behalf of the MiamiCoin community, thank you. This will reduce confusion, and put our brand on display in the web wallet.

**Comment by headlock161** [comment]
NYC coin is also facing this issue.

![image](https://user-images.githubusercontent.com/79287151/141828160-613953f5-25ae-4e9d-a4b7-81b765aac385.png)

**Comment by markmhendrickson** [comment]
Yep, this is affecting any standardized fungible tokens with assets external to the Stacks blockchain, such as the main icon / image, since the Stacks Blockchain API doesn't support such assets yet. 

Hiro is investigating ways to support such assets. cc @zone117x

**Comment by zone117x** [comment]
Minimal FT metadata is supported, e.g.
```
https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-token/ft/metadata
```
```json
{
  "token_uri": "https://cdn.citycoins.co/metadata/newyorkcitycoin.json",
  "name": "newyorkcitycoin",
  "description": "A CityCoin for New York City, ticker is NYC, Stack it to earn Stacks (STX)",
  "image_uri": "https://stacks-api.imgix.net/https%3A%2F%2Fcdn.citycoins.co%2Flogos%2Fnewyorkcitycoin.png?s=38a8d89aa6b4ef3fcc9958da3eb34480",
  "image_canonical_uri": "https://cdn.citycoins.co/logos/newyorkcitycoin.png",
  "symbol": "NYC",
  "decimals": 0,
  "tx_id": "0x9c8ddc44fcfdfc67af5425c4174833fc5814627936d573fe38fc29a46ba746e6",
  "sender_address": "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5"
}
```

**Comment by markmhendrickson** [comment]
Good to know. So we should be able to proceed here with the image integration.

**Comment by markmhendrickson** [comment]
Let's address token impersonation along with this (e.g. prevent STX as name).

**Comment by ginny-d** [comment]
I'm not sure what's the task I need to complete here - is it to share the .svg icons for MIA and NYC? 

In that case, @pstan26 can you please share the source files for both logos?

**Comment by kyranjamie** [comment]
No need to update/share assets. 

I think Mark may've assigned you as some considerations need to be made as to how we make sure that legit STX doesn't look visually the same as a scam token called STX with the exact same logo. Some sort of wallet-approved token emblem, or UI element that sits outside the image bounds, so can't be mocked by an external image.

**Comment by ginny-d** [comment]
Would something like this work? Adding it next to the ticker vs. the token icon:

<img width="945" alt="Group 5447" src="https://user-images.githubusercontent.com/78865845/150325572-804e2688-e102-477d-b72a-61434143a3c6.png">

Open to other options / revisions too

**Comment by kyranjamie** [comment]
Something like this, yeah. We'd need to keep a whitelist, which is fine (ETH does similar).

I wonder if grouping by token type would also help weed out the scams: network tokens first (stx, btc), FTs, NFTs? Also interested how we might show a warning on a FT if its symbol matches a known-good whitelisted token.

**Comment by markmhendrickson** [comment]
Sorry for the lack of guidance here earlier. Let's discuss as a team again now that @landitus has joined to figure out next steps.

**Comment by markmhendrickson** [comment]
On further reflection, let's tackle impersonation (which is a potential problem with or without image support) as a separate issue so that we can get this image support through.

**Comment by andresgalante** [comment]
To prevent impersonation we can filter out any FT named Stacks (STX)

**Comment by timstackblock** [comment]
I get the image for MIA @markmhx 

I don't for DIKO, USDA or anything else, shouldn't we have images for the other assets?


![Image](https://user-images.githubusercontent.com/49165468/171450097-7dd808fb-d306-48a6-aa67-ed2c0d29cbb6.png)

**Comment by andresgalante** [comment]
@beguene please check if the metadata for DIKO or USDA has an image

**Comment by beguene** [comment]
@timstackblock It's because DIKO and USDA have not added the metadata in their contract
https://explorer.stacks.co/txid/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.usda-token?chain=mainnet
https://explorer.stacks.co/txid/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-token?chain=mainnet

while MiamiCoin has the metadata
https://explorer.stacks.co/txid/SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-token?chain=mainnet

@andresgalante We can therefore release this.

**Comment by Eshwari007** [comment]
Moving the ticket to. merge as per @beguene 's comment above

**Comment by philiphacks** [comment]
@beguene apologies - my bad. I now updated the metadata on USDA and DIKO. How long does it take for the Stacks API to include this in the metadata endpoint? Can we refresh this manually somehow?

**Comment by zone117x** [comment]
@philipdesmedt see https://github.com/stacksgov/sips/pull/72

**Comment by philiphacks** [comment]
@zone117x thanks! I sent this TX 22 days ago but the logo has not updated (https://explorer.stacks.co/txid/0xe01ac9df7eb35236fde3e0dc28c74a483d94f69e1c3a7acd2931a9c89f6239ef?chain=mainnet)... what am I doing wrong?

The token URI was set here https://explorer.stacks.co/txid/0x46c367bc35271379aee674a907b4ab5941d37af5eae7e99e218d35276391981e?chain=mainnet, which links to https://arkadiko.finance/metadata/diko-token.json
