### ISSUE TITLE
Improve welcome screen

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1807]
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/📏Spec?node-id=62%3A3622

![image](https://user-images.githubusercontent.com/28991/136820376-128a0e44-65f4-4b5e-a995-fcbc33b4d2d7.png)

**Comment by markmhendrickson** [comment]
@eugeniadigon did you want to update this illustration?

**Comment by ginny-d** [comment]
> @eugeniadigon did you want to update this illustration?

Yes also! - nothing wrong with it but mainly because it's part of Stacks brand illustration system vs. just Hiro

**Comment by ginny-d** [comment]
Update screens with new design / new illustration system:

~~1) Download wallet modal: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=80%3A2592~~ Moved to Connect: https://github.com/hirosystems/stacks-wallet-web/issues/1807#issuecomment-1022732154

2) Wallet installed:
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=80%3A2659
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=80%3A2678

<img width="1352" alt="start" src="https://user-images.githubusercontent.com/78865845/150508177-3238d469-72bb-48e8-ad0b-b8559712dec9.png">

<img width="488" alt="start-1" src="https://user-images.githubusercontent.com/78865845/150508196-b8e02b1e-c74e-469d-992f-0abea2fb8e8d.png">

**Comment by fbwoolf** [comment]
Note, the first image here needs to be updated in Connect. I will make a new issue there for it.

**Comment by Eshwari007** [comment]
@fbwoolf Notice that on the '`Help us improve screen'`, the learn more link is shown in the window full view wallet and now in the popup wallet as per Figma. Was this designed intentionally?
Also on the full window view, am not able to view the 'Learn more' link as well
<img width="592" alt="Screen Shot 2022-02-01 at 9 55 04 AM" src="https://user-images.githubusercontent.com/38872890/151992551-770ea3f7-5f54-43ac-8e39-ca96500423ae.png">
<img width="1044" alt="Screen Shot 2022-02-01 at 9 56 49 AM" src="https://user-images.githubusercontent.com/38872890/151992555-dbd469cb-9421-436b-a5c7-7fa02cd8c5a0.png">

**Comment by fbwoolf** [comment]
@Eshwari007 see comment here: https://github.com/hirosystems/stacks-wallet-web/issues/1678#issuecomment-1027009121

**Comment by Eshwari007** [comment]
@fbwoolf Believe the new 'Add Hiro Wallet to Chrome ' can only be tested upon release to Prod?

**Comment by fbwoolf** [comment]
> @fbwoolf Believe the new 'Add Hiro Wallet to Chrome ' can only be tested upon release to Prod?

That is actually a change that needs to happen in Connect. I made an issue for it last week here: https://github.com/hirosystems/connect/issues/188

I can remove it from the issue here to avoid confusion.

**Comment by fbwoolf** [comment]
https://github.com/hirosystems/stacks-wallet-web/issues/1807#issuecomment-1022732154
