### ISSUE TITLE
Update empty state illustrations for balances and activity

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1809]
![image](https://user-images.githubusercontent.com/28991/136827244-89a6f9a8-927b-4e01-9475-ef6debf6c329.png)
![image](https://user-images.githubusercontent.com/28991/136827270-23609b00-4fbe-4bb4-9210-9869abe923b8.png)

**Comment by ginny-d** [comment]
Please update empty states illustrations with new illustration system:

1) Balances: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=603%3A17688
<img width="489" alt="empty balances" src="https://user-images.githubusercontent.com/78865845/150506655-6592d13f-b30f-464d-b971-ac9d7ba457c0.png">

2) Activity: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=603%3A16925
<img width="489" alt="empty state" src="https://user-images.githubusercontent.com/78865845/150506696-45dae27a-20c1-485b-b641-fda330a1b9f7.png">

EDIT: 3) Was moved to https://github.com/hirosystems/connect/issues/192

**Comment by fbwoolf** [comment]
I am going to move the last illustration here to a new issue in the Connect repo.

**Comment by Eshwari007** [comment]
Test passed.Moving it out of QA
