### ISSUE TITLE
Folder structure: Group by script context

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#1813]
Our root folder looks like this currently:

```
src
├── app.tsx
├── background
├── common
├── components
├── content-scripts
├── features
├── index.tsx
├── inpage
├── pages
├── routes.tsx
├── store
└── workers
```

We have separate folders for `background`, `inpage` and `content-script`, but all the code for the main wallet code (the `popup` or whatever we call it), is just mixed in without the same separation. I'm not sure why I didn't make this separation when we last changed the folder structure: its odd to not group one of the 4 script contexts.

Further, what is `common` for? Currently it's only really code _common_ to the popup script. There are hooks and other utils etc in there. The folder has a mixed responsibility.

We should create a separate folder for all of the popup script's code, so that we communicate clearly which code is for the popup script. The common folder should then only be used for code that is shared _between_ script contexts.

```
src
├── background
├── common
├── content-scripts
├── inpage
└── popup <-- all the code is now nested in here
```

I don't really like the name popup though. Other name suggestions?

**Comment by fbwoolf** [comment]
Agree, I like this approach. It's hard to move away from `popup` bc of Chrome using it, but it doesn't seem quite right bc it doesn't describe either view well. I looked at MetaMask and they use `ui` (all their scripts are in another folder called `app`).
