### ISSUE TITLE
Remove mention of 24 words from within reset confirmation

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1815]
We shouldn't specify the length of a given Secret Key during reset confirmation since keys can actually vary in length (e.g. 12 words):

![image](https://user-images.githubusercontent.com/28991/136690548-cdaf92a2-4eec-4d43-ac3b-d78c9856e06c.png)

**Comment by andresgalante** [comment]
What would you like this to read? just remove "24-word"?

**Comment by markmhendrickson** [comment]
Yep, just "...of your Secret Key"
