### ISSUE TITLE
Fix Release PR CI

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#1817]
There's something really funky going on with our release PRs.

On the first build, CI runs. It fails as 'Version Release' don't conform to our commit standard.

![image](https://user-images.githubusercontent.com/1618764/136979154-78c29c86-f7dd-4470-91eb-95ea3146396e.png)

Subsequent updates don't seem to run CI at all, and it just hangs on the above screen

cc/ @fbwoolf @CharlieC3 @beguene

**Comment by fbwoolf** [comment]
@CharlieC3 I can't seem to catch the release PR to see if the checks run before the force pushes. @kyranjamie did you notice? Charlie asked me in the devops channel yesterday.

**Comment by kyranjamie** [comment]
I did, yes. It runs correctly (and fails, as expected)
