### ISSUE TITLE
Refactor vault 'reducer' and message handler

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#1822]
We need to revisit the vault 'reducer' which handles a lot of our messaging around wallet security.

Files of importance:
`vault.ts`
`vault-loader.tsx`
`vault-types.ts`

Used in:
`app.tsx`
`container.tsx`
`account-gate.tsx`
`background.ts`
`use-vault-messenger.ts`
`use-wallet.ts`
`wallet.hooks.ts`
`wallet.ts`
`state-utils.tsx`

**Comment by kyranjamie** [comment]
See notion doc I've written on this https://www.notion.so/hiropbc/Killing-the-vault-reducer-be18b314260c458299b12fcce2951454

**Comment by Eshwari007** [comment]
@fbwoolf @kyranjamie What would be the use case(s) for testing the ticket? Appreciate some input.Thx

**Comment by kyranjamie** [comment]
> @fbwoolf @kyranjamie What would be the use case(s) for testing the ticket? Appreciate some input.Thx

This is a refactor PR, so the functionality should remain exactly the same. It needs a full regression test, with special note of the up grade behaviour described in the PR description.

**Comment by Eshwari007** [comment]
The issue below was also reported in revert PR but wanted to keep the issue open for wider team's input hence posting it here as well:
https://github.com/hirosystems/stacks-wallet-web/pull/2259#issuecomment-1049333567


Issue :One thing that is noticed is that when a user creates a new account, a brief moment of a blank screen is produced when I don't recall seeing it earlier.

Attaching two versions below for perusal:


https://user-images.githubusercontent.com/38872890/155564624-61653a47-e8b6-4f9d-a7ed-ac13ea248f29.mov


https://user-images.githubusercontent.com/38872890/155564633-9d220ae6-8e18-4d13-8246-6516e349b838.mov


cc @kyranjamie @fbwoolf

**Comment by kyranjamie** [comment]
Good observation, @Eshwari007. We now derive the the accounts, and this is why there's a small delay with a ~~blank screen~~ loading spinner. Do you think this is a problem?

**Comment by Eshwari007** [comment]
> Good observation, @Eshwari007. We now derive the the accounts, and this is why there's a small delay with a ~blank screen~ loading spinner. Do you think this is a problem?

@kyranjamie it may look like an issue from user's point of view( as it's not the usual expected behavior ) though I don't see it as a blocker. Maybe we can run it out with @markmhx on his input of the add new account behavior above.

**Comment by andresgalante** [comment]
@markmhx please take a look at this one since it's blocking merging #2172 to `dev`

**Comment by kyranjamie** [comment]
A significant amount of more refactoring will be needed to prevent this. It's a loading spinner seen only when a user creates an account. Sure, it'd be great to avoid it, but is it such a problem?

**Comment by Eshwari007** [comment]
@markmhx I can move the issue found as a minor bug hence will allow us to merge the parent ticket  #1822. Does that sound good to you? cc @andresgalante @kyranjamie

**Comment by markmhendrickson** [comment]
I'd suggest breaking out this minor bug into its own issue and treating it as a non-blocking change for https://github.com/hirosystems/stacks-wallet-web/pull/2172 to get merged.

**Comment by Eshwari007** [comment]
> I'd suggest breaking out this minor bug into its own issue and treating it as a non-blocking change for #2172 to get merged.

Done. PR: 2271
