### ISSUE TITLE
Distribute Hiro Wallet Preview

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#1823]
Chrome allows extensions to be published to the store _Unlisted_. I imagine Firefox has something similar.

I propose we create a new beta release version of the wallet, _Hiro Wallet Preview_, that we distribute internally, to our QA team, and eager community members, in a way which doesn't require manual installation/updating.

This'll allow us to push a release for thorough testing among a small group of testers, before releasing to the wider userbase, collecting necessary segment/sentry feedback in the meantime.

Along with these changes, I think we should kill changesets in favour of semantic release. They each have their merits, but as an organisation we use semantic release more widely and it'll work well with this release model.

**Comment by markmhendrickson** [comment]
Great idea 👍

**Comment by andresgalante** [comment]
@markmhx Do you think we can do this during Q4? it'll be great to end the quarter with an improved release process

**Comment by markmhendrickson** [comment]
I might suggest time boxing some research into how much work this will take to implement fully. Then we can assess alongside other Q4 priorities.

**Comment by kyranjamie** [comment]
I would advocate doing this asap, next week if possible. A solid release process will help us with all the other Q4 goals.

This task is really "Improve our release process/Use Semantic Release". Releasing a beta wallet version is just a bonus that comes with it (and basically just duplicates the release action we already have)

**Comment by andresgalante** [comment]
We talked about this yesterday, it'd take one person a week
