### ISSUE TITLE
Support BNS names in recipient field for sends

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-app#1840]
Currently, bns names are not accepted as recipients 

![Screenshot from 2021-10-19 10-19-16](https://user-images.githubusercontent.com/1449049/137873216-06f8a93a-8b76-480d-9699-1d2e3b478115.png)

**Expected behaviour**
Allow to enter a bns name in preview and show the resolved address + bns name in final screen

**Comment by xanbots** [comment]
Yes please, big +1

**Comment by sleepiJoe** [comment]
+1 (we have the demand!)

**Comment by friedger** [comment]
What should the UI look like? Should the preview just show the address and the name?

**Comment by markmhendrickson** [comment]
Assigning @landitus to design

**Comment by pors** [comment]
Interesting comment here: https://twitter.com/axopoa/status/1519572653278908417

> I think we will need a autorenewal service for BTC names. Because it can be very dangerous if someone renews a name you own before you do.

**Comment by markmhendrickson** [comment]
From @kyranjamie:

> Would be a great feature, but it isn't entirely trivial. We need to consider homoglyph attacks: I could buy bruffstаr.btc (Cyrillic letter а). We need to show address still in UI and warn against dodgy chars, similar to how vscode does

**Comment by friedger** [comment]
homoglyph attacks are not possible because names are limited to a-z, 0-9 and - and _

**Comment by kyranjamie** [comment]
That does indeed limit the scope. We should still use a clear display type, so Oliver.btc is visibly different to OIiver.btc (capital i not L).

**Comment by aulneau** [comment]
> That does indeed limit the scope. We should still use a clear display type, so Oliver.btc is visibly different to OIiver.btc (capital i not L).

only lower case letters are allowed in BNS names

**Comment by RagnarLifthrasir** [comment]
+1 for BNS names in recipient fields.

**Comment by friedger** [comment]
A blocker is still https://github.com/hirosystems/stacks-blockchain-api/issues/1333

**Comment by aulneau** [comment]
> A blocker is still [hirosystems/stacks-blockchain-api#1333](https://github.com/hirosystems/stacks-blockchain-api/issues/1333)

does not need to be a blocker, you can use the NFT history endpoint (gamma does this)

see https://discord.com/channels/621759717756370964/909867922971820102/1033008587804520459

> yes, you can use the NFT history endpoint but you'll have to provide the name Clarity encoded. This is an example for eliherf.stacksparrot: https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/nft/history?asset_identifier=SP000000000000000000002Q6VF78.bns::names&value=0x0c00000002046e616d650200000007656c6968657266096e616d657370616365020000000c737461636b73706172726f74

**Comment by friedger** [comment]
> does not need to be a blocker, you can use the NFT history endpoint (gamma does this)

How do we reach all developers to switch from one api endpoint to the other? Seems not an option
