### ISSUE TITLE
Withdrew 508.5stx from Binance but only received 496stx

### ISSUE THREAD

**Issue by Hero-Gamer** [blockstack/blockstack-app#1848]
Hi my 

wallet address: SPYQW63PYXA8DFQS34GRMT5DPNRA6WR0TN19RY9F
TX ID: 0x6f1b0d50b7d3d23af15d3be4f81bba123e45c700f8c096c4d9ffb3fec800e2fc

Issue: 
What I did:
- Withdrew approx. 510stx from Binance, they take 1.5stx fee off me, so I should have approx. 508.5stx send to my wallet after fee. 
- I can see within one of the tx in the SEND MEMO says 508.5stx, but that's not what I actually received/displayed in my wallet
- I only received 496stx to my wallet address (12.5stx gone missing!)

>I have not made any transactions since to keep activities things clear.
>I attach all my Binance activities and my wallet balance for your info.

What is the issue here? Will that missing stx be reimbersed?

Thank you team!!!!

![ISSUE-A001-01](https://user-images.githubusercontent.com/92864860/138097570-179056e8-11c1-40b2-ac5f-5e829df646ef.PNG)
![ISSUE-A001-02](https://user-images.githubusercontent.com/92864860/138097739-d44bc386-3022-4771-be64-68181370fc67.PNG)

![ISSUE-A001-03](https://user-images.githubusercontent.com/92864860/138097755-9059725d-f6a9-4e85-94fd-2fe7ca03804b.PNG)
![ISSUE-A001-04](https://user-images.githubusercontent.com/92864860/138097765-095b6944-394f-4542-be48-08a30d2ad5cb.PNG)

**Comment by kyranjamie** [comment]
@Hero-Gamer can you confirm the values in the wallet are still displayed incorrectly?

There are no STX missing. [You can see on the explorer your full balance is there.](https://explorer.stacks.co/address/SPYQW63PYXA8DFQS34GRMT5DPNRA6WR0TN19RY9F?chain=mainnet)

**Comment by Hero-Gamer** [comment]
> @Hero-Gamer can you confirm the values in the wallet are still displayed incorrectly?
> 
> There are no STX missing. [You can see on the explorer your full balance is there.](https://explorer.stacks.co/address/SPYQW63PYXA8DFQS34GRMT5DPNRA6WR0TN19RY9F?chain=mainnet)

Just check, the values displayed in my wallet is still incorrect.

Today I received 135stx boombox back from stacking. So my balance "without" boombox stacking stx would still be 496stx, which should not be the case when I have definitely withdrawn 508.5stx from Binance as per tx shown.

**Comment by Hero-Gamer** [comment]
Hi Kyan, 

I restored the wallet on CHROME, still displaying the incorrect balance.

These are the steps I took exactly:
1. Sign out from SPYQ... wallet on Brave. (plus signing out my other chrome wallet...)
2. Restore my SPYQ wallet onto Chrome
I did not close down my browsers or clean any cache or restart my computer.

![Brave B03](https://user-images.githubusercontent.com/92864860/138278901-b78c61a1-2822-4c36-9810-8e86b6cff719.PNG)

**Comment by kyranjamie** [comment]
This is a different balance to above, and the one that is shown on the explorer/API. 

This balance is inaccurate? You're expecting it to be 12.5 STX more?

We can see the correct amount was transferred from binance `"stx_received": "508500000",`

<details>
<summary>API response</summary>

```json
{
  "tx": {
    "tx_id": "0x6f1b0d50b7d3d23af15d3be4f81bba123e45c700f8c096c4d9ffb3fec800e2fc",
    "nonce": 2616,
    "fee_rate": "2255451",
    "sender_address": "SP2J6HSSDYSTM71S0K0KK4YWRKX59JN1AD52M4B59",
    "sponsored": false,
    "post_condition_mode": "deny",
    "post_conditions": [
      {
        "type": "stx",
        "condition_code": "sent_equal_to",
        "amount": "1087870800",
        "principal": {
          "type_id": "principal_standard",
          "address": "SP2J6HSSDYSTM71S0K0KK4YWRKX59JN1AD52M4B59"
        }
      }
    ],
    "anchor_mode": "any",
    "is_unanchored": false,
    "block_hash": "0xf4f36afc46c716ecd693cb2d8be899b703d9b1937fdc8b24eec8c1aa47e58279",
    "parent_block_hash": "0xabb12eb1856c009ea3e282faf0d3cf44cf0a1a1ec38f9bba1626360c7685def2",
    "block_height": 34114,
    "burn_block_time": 1634487052,
    "burn_block_time_iso": "2021-10-17T16:10:52.000Z",
    "parent_burn_block_time": 1634486806,
    "parent_burn_block_time_iso": "2021-10-17T16:06:46.000Z",
    "canonical": true,
    "tx_index": 16,
    "tx_status": "success",
    "tx_result": {
      "hex": "0x0703",
      "repr": "(ok true)"
    },
    "microblock_hash": "0x274b881b743c805ab44c695d512c5892d2e6e5c6ff1158310913f3f4531fd5e1",
    "microblock_sequence": 0,
    "microblock_canonical": true,
    "event_count": 8,
    "events": [],
    "execution_cost_read_count": 7,
    "execution_cost_read_length": 738,
    "execution_cost_runtime": 55164000,
    "execution_cost_write_count": 4,
    "execution_cost_write_length": 4,
    "tx_type": "contract_call",
    "contract_call": {
      "contract_id": "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.send-many-memo",
      "function_name": "send-many",
      "function_signature": "(define-public (send-many (recipients (list 200 (tuple (memo (buff 34)) (to principal) (ustx uint))))))",
      "function_args": [
        {
          "hex": "0x0b000000040c00000003046d656d6f020000000002746f05168f355f558c6c1ee3bcb563a64e43f05e813e16a204757374780100000000000000000000000001a639100c00000003046d656d6f020000000002746f0516f8d9a031f2dec7bdeacb4e3cd230da086e10db730475737478010000000000000000000000001c52fa000c00000003046d656d6f020000000002746f05163d7e1876f75486bef919218a68adb570a37300d50475737478010000000000000000000000001e4f18200c00000003046d656d6f020000000002746f05166a0ee7af9ff1991a6d1f7ec08bfc34db19511c8d047573747801000000000000000000000000048f4c20",
          "repr": "(list (tuple (memo 0x) (to SP27KAQTNHHP1XRXWPNHTCKJ3Y1F82FGPM9K3CBB5) (ustx u27670800)) (tuple (memo 0x) (to SP3WDK81HYBFCFFFASD73SMHGV846W46VEFVBYYB2) (ustx u475200000)) (tuple (memo 0x) (to SPYQW63PYXA8DFQS34GRMT5DPNRA6WR0TN19RY9F) (ustx u508500000)) (tuple (memo 0x) (to SP1N0XSXFKZRSJ6KD3XZC12ZW6KDHJM8WHPVG02P1) (ustx u76500000)))",
          "name": "recipients",
          "type": "(list 200 (tuple (memo (buff 34)) (to principal) (ustx uint)))"
        }
      ]
    }
  },
  "stx_sent": "0",
  "stx_received": "508500000",
  "stx_transfers": [
    {
      "amount": "508500000",
      "sender": "SP2J6HSSDYSTM71S0K0KK4YWRKX59JN1AD52M4B59",
      "recipient": "SPYQW63PYXA8DFQS34GRMT5DPNRA6WR0TN19RY9F"
    }
  ]
}
```

</details>

**Comment by Hero-Gamer** [comment]
> lance to above, and the one that is shown on the explorer/API.
> 
> This balance is inaccurate? You're expecting it to be 12.5 STX more?

That's because a BOOMBOX stacking cycle just finished, and I have 135stx returned to me. I wish Boombox stacking can display as a tx so u can see the history of the balance..

but yeah if the boombox stacking did not return the 135stx to my wallet today. 
My balance would still be displaying 496stx, which is 12.5stx short of what was withdrawn 508.5stx.

**Comment by kyranjamie** [comment]
Are you talking about this transaction? https://explorer.stacks.co/txid/0x7674e1af1f52f98be906f0ba28c4de457ba8a42e3543efd5ff5604d692dd3115?chain=mainnet

It returned 110 STX, not 135 STX.

**Comment by Hero-Gamer** [comment]
> Are you talking about this transaction? https://explorer.stacks.co/txid/0x7674e1af1f52f98be906f0ba28c4de457ba8a42e3543efd5ff5604d692dd3115?chain=mainnet
> 
> It returned 110 STX, not 135 STX.


No, that's just a standalone STX transfer out from SPYQ.. account, into a sub account in the wallet. Nothing to do with Boombox.

This is the 135stx Boombox Delegate tx (which was unlocked back to me today):
https://explorer.stacks.co/txid/0x5bfe6cd962444c1026dabce4913e6da986addff40b5e1366893fc1c8293293c9?chain=mainnet

Boombox tx does not appear in the activity list, which is confusing for users. I've asked them if they can make activities appear.
One of the reasons it does not appear may be due to when Stacking stx in Boombox cycle, the STX actually doesn't leave your wallet, it just locked in your wallet.

**Comment by kyranjamie** [comment]
@Hero-Gamer, we've confirmed that the wallet displays the same information that the API returns. So, if there is an issue, it isn't with the wallet. How can you be sure your own accounting isn't mistaken? I see failed minting transactions on this address. These have cost you fees.

If there's actually a missing transaction, the boombox one you speak of, this would be an API issue. You can open an issue there https://github.com/blockstack/stacks-blockchain-api

**Comment by kyranjamie** [comment]
As discussed on Discord, this is relating to API issue reported here https://github.com/blockstack/stacks-blockchain-api/issues/804
