### ISSUE TITLE
Displayed balance & available balance DOES NOT match the pop-up window's balance which is actually what's transactable

### ISSUE THREAD

**Issue by Hero-Gamer** [blockstack/blockstack-app#1849]
Wallet ID: SP3.........X20
Browser: Microsoft Edge 
Hiro wallet version: v2.19.4

Issue: 
- I am supposed to have around 373stx in the wallet that is available to spend in theory, that's what's displayed. But when I actually transact anything, the pop up confirmation window says a different amount, only 162stx available.
- There is about 211stx difference that I am supposed to have, but aren't able to spend for whatever reason..
- so say if I wanna make a 350stx NFT transaction right now, tho my wallet says I have 373stx available, IT WILL FAIL. (I failed to buy an NFT due to this issue last week, I had 460stx in the wallet displayed, made a 450stx purchased, but it failed. :/ ) 
- Explorer also says the balance available matching what's displayed in Hiro wallet. 

someone help?!

Thank you team, love u!

![ISSUE-B001-01](https://user-images.githubusercontent.com/92864860/138102022-81dba172-50b5-4a61-ad51-a34cb02d87f7.PNG)
![ISSUE-B001-02](https://user-images.githubusercontent.com/92864860/138102039-47084138-8fff-4545-8c9f-949a3476653e.PNG)

**Comment by Eshwari007** [comment]
I tried to reproduce the issue on btc.us using latest Hiro Wallet Web release ,however wasnt able to do .The balance was accurate both from API front and as well from UI.cc @andresgalante

**Comment by Hero-Gamer** [comment]
Hi, just checking balance again today, still showing wrong balance on another platform. 
I believe I got my stacked Boombox STX returned to me today, so my Explorer's balance is cleared, should be just 443Stx.
but still only 232stx actually available to transact..

![ISSUE-B001-03](https://user-images.githubusercontent.com/92864860/138270224-12b0ae34-4c47-4bfc-a0bd-d6620815377d.PNG)
![ISSUE-B001-04](https://user-images.githubusercontent.com/92864860/138270512-26c5e050-db14-4bd4-b3e4-0671008811a5.PNG)

**Comment by Hero-Gamer** [comment]
> I tried to reproduce the issue on btc.us using latest Hiro Wallet Web release ,however wasnt able to do .The balance was accurate both from API front and as well from UI.cc @andresgalante


Hi, I just checked my balance again today, now the total available balance have come right down, I haven't spent anything on big items, I've only been buying a few BNS which doesn't cost a lot. The 211stx difference just disappeared out of nowhere between my last post and this post!
Can someone help?

https://explorer.stacks.co/address/SP3.......X20?chain=mainnet

**Comment by fbwoolf** [comment]
@Hero-Gamer there is a fix for this that was merged in the api repo today. I confirmed on the test network your balance shows correctly, so please be patient as this fix for the api is released and these apps can consume the right data. @zone117x or @rafaelcr can you confirm when these changes to the api will be live?

**Comment by rafaelcr** [comment]
@fbwoolf @Hero-Gamer apologies for the delay, the changes are now live in the mainnet API (v0.70.1)

**Comment by fbwoolf** [comment]
@Hero-Gamer can you confirm if this is fixed?

**Comment by Hero-Gamer** [comment]
> @Hero-Gamer can you confirm if this is fixed?

Hello fbwoolf, as far as all balances matching up in various windows (hiro wallet, popup, explorer) yes they all match and fixed. 

As far as the missing balance of the 200 something difference, i do not know where those tokens are gone, or if they should have been there in the first place. What's ur thought on that?

Thanks

![image](https://user-images.githubusercontent.com/92864860/138749190-7dc26cc4-e877-4f20-9746-9800de88a259.png)

**Comment by fbwoolf** [comment]
> 
> As far as the missing balance of the 200 something difference, i do not know where those tokens are gone, or if they should have been there in the first place. What's ur thought on that?
> 

I don't recognize the screenshot with the `232` balance, if that is not in our wallet you would have to open an issue with that app bc that would be an issue with how they are displaying data?

**Comment by Hero-Gamer** [comment]
That was just a pop up window from a Loop Boom NFT. But it's nothing to do with them. 

What I meant was, since the very first message of this open issue, there has always been 211stx difference no matter which platform I go to, it is not platform specific as u can see i first noticed this issue when buying BNS (see pic attached). 

The Hiro web wallet was always higher than any pop up window, leading myself to think I always have 211stx more.. 
So yeah.. I'm confused myself how much money I am supposed to have now. lol

 

![image](https://user-images.githubusercontent.com/92864860/138750952-290edb1d-9728-430a-80f9-45f6c7f0012e.png)

**Comment by andresgalante** [comment]
@beguene would you be able to take a look at this tomorrow please?

**Comment by beguene** [comment]
Sure I will check

**Comment by beguene** [comment]
I check this address, and currently the balances @Hero-Gamer are the same in the home tab and in the popup. But looking into our code I see that in the home tab we show the available balance while in the popup we display the unanchored balance.
The available balance is calculated like this: available balance = AnchoredBalance - stx locked 
which is different from the Unanchored balance. 
I suspect that's why there are some differences sometimes and can cause confusion for the user.
@andresgalante @markmhx I think this is a bug. Putting it in backlog to prioritize.

**Comment by Hero-Gamer** [comment]
Thank you guys, I'd just like to clarify and update:
- 6 days ago: did not match (first reported, 1 lower amount, 1 higher amount))
- 5 days ago: did not match (1 lower amount, 1 higher amount)
- 4 days ago: Matched (to the lower balance amount)
- 20 hours ago: Matched (to the lower balance amount)
- Current check: Matching (to the lower balance amount)

**Comment by markmhendrickson** [comment]
@Hero-Gamer is this safe to close out given your latest check matches?

**Comment by Hero-Gamer** [comment]
> @Hero-Gamer is this safe to close out given your latest check matches?

Yes I think so, somehow.
