### ISSUE TITLE
Prevent revoked username from showing up for account

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1850]
https://btc-website.tintashlabs.com/get/testhiro.btc
While testing PR:#1827

User tried to delete the BNS name onto an existing account
User received pop up dialogue that it has been submitted however,user does not see the name revoked in web wallt
In explorer the name revoke has seem confirmed in anchor block
However useris yet able to view the bns name of the account
https://explorer.stacks.co/txid/0xe6ee0aae5f23eae018f083c1fa2af0374747e08d15223db0e801ae33cb681bad?chain=testnet

<img width="647" alt="Screen Shot 2021-10-20 at 10 27 27 AM" src="https://user-images.githubusercontent.com/38872890/138112712-577eebee-b26e-428e-9f34-ee059939d6d9.png">

**Comment by markmhendrickson** [comment]
This seems possibly related to https://github.com/blockstack/stacks-wallet-web/issues/1703#issuecomment-953017756 

cc @fbwoolf

**Comment by fbwoolf** [comment]
> This seems possibly related to [#1703 (comment)](https://github.com/blockstack/stacks-wallet-web/issues/1703#issuecomment-953017756)
> 
> cc @fbwoolf

Seems like it could definitely be related.

**Comment by markmhendrickson** [comment]
@timstackblock to retest this and see whether it's a caching issue by checking the account in a separate browser post-revoke. Otherwise it might be an issue related to the wallet-sdk package.

**Comment by Eshwari007** [comment]
https://btc-website.tintashlabs.com/get/testhiro.btc is having some issues( the site isnt responding)
I will touch base with btc team on it and will retest the issue above

**Comment by Eshwari007** [comment]
Update:BTC Testnet SSL has expired, BTC team is working on it

**Comment by timstackblock** [comment]
This still seems to be happening, the revoke transaction is confirmed but it doesnt seem to be working as expected even with the new wallet.


<img width="1492" alt="Screen Shot 2022-05-05 at 1 31 24 PM" src="https://user-images.githubusercontent.com/49165468/166985675-ff455717-3a12-4e7e-ad79-81041a78415f.png">
<img width="1491" alt="Screen Shot 2022-05-05 at 1 31 46 PM" src="https://user-images.githubusercontent.com/49165468/166985676-5cb33892-fac6-4675-bec7-5c2f7cbd4af8.png">
<img width="1460" alt="Screen Shot 2022-05-05 at 1 31 56 PM" src="https://user-images.githubusercontent.com/49165468/166985678-5a913b1e-6341-421c-a96c-d67f7a5ee8aa.png">
<img width="1425" alt="Screen Shot 2022-05-05 at 2 05 00 PM" src="https://user-images.githubusercontent.com/49165468/166985680-c8f7960d-0b50-4815-b923-b9e73543d4c2.png">
<img width="1352" alt="Screen Shot 2022-05-05 at 2 04 36 PM" src="https://user-images.githubusercontent.com/49165468/166985679-5de714a3-adc9-44d7-9299-b6d6664cdf77.png">

**Comment by Eshwari007** [comment]
@timstackblock Shall I put the ticket back into the backlog since you were able to reproduce it?
cc @markmhx

**Comment by timstackblock** [comment]
Yes please do
