### ISSUE TITLE
Duplicate toast when replacing by fee

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-app#1854]
I wanted to add more stx to the fee for a given transaction, and it seems there are two toast that get fired:

<img width="428" alt="Screen Shot 2021-10-21 at 11 34 39 AM" src="https://user-images.githubusercontent.com/11803153/138320070-077e7c95-a15d-4b06-a90a-8183d31ae44c.png">

I correctly replace-by-fee'ed, and feel like this toast was fired by mistake.

**Comment by markmhendrickson** [comment]
It seems that both of these toasts are incorrect, in that we should have just one that says "✅ Fee increased!" or something similar?

**Comment by pete-watters** [comment]
Closing this off as its outdated
