### ISSUE TITLE
Tx status icon incorrect in activity tab

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#1859]
I performed a swap on Arkadiko and when the tx was in a mircoblock the tx status in the activity tab did not show the microblock icon. See images...

<img width="477" alt="Screen Shot 2021-10-24 at 12 26 23 PM" src="https://user-images.githubusercontent.com/6493321/138605736-390f01d3-6a3d-4a6f-b33c-bad5a2f5330c.png">

<img width="437" alt="Screen Shot 2021-10-24 at 12 26 39 PM" src="https://user-images.githubusercontent.com/6493321/138605739-7c61f166-bd9d-41ef-b712-3bf3a8211a9c.png">

<img width="783" alt="Screen Shot 2021-10-24 at 12 26 55 PM" src="https://user-images.githubusercontent.com/6493321/138605742-fb9d90e3-86f2-4180-a2c9-9ea9abb19500.png">

**Comment by markmhendrickson** [comment]
Closing as stale
