### ISSUE TITLE
Issue with Hiro Wallet

### ISSUE THREAD

**Issue by anthonyfiore** [blockstack/blockstack-app#1865]
My Hiro Wallet says v.2.19.4 at the top.

Again, when I try to generate a new account it wont allow me to do that and when I choose an account to connect to btc.usa from which I purchased a domain name, it will not allow me to do so.

**Comment by anthonyfiore** [comment]
That id=s when I try to connect to the account, it keeps on spooling.

**Comment by anthonyfiore** [comment]
I do have the latest version of the hiro wallet.

**Comment by anthonyfiore** [comment]
Please advise!!

**Comment by anthonyfiore** [comment]
Please note --the "Choose the Account to connect to the Hiro Wallet separate accounts do show the individual domain names that I purchased but again it won't make me enter the specific account that I choose. Again it keeps spooling.

**Comment by andresgalante** [comment]
Hi @anthonyfiore I can't follow. Would you be able to explain the steps to reproduce this issue, and maybe add some screen shots please?

**Comment by anthonyfiore** [comment]
It is very easy

**Comment by anthonyfiore** [comment]
I cant open an account when I try to get into the btc.us domain name that was previously created.

**Comment by anthonyfiore** [comment]
I first go into the btc.us page THEN press sign in THEN when I try to go into an individual domain name that was previously created and paid for, it wont allow me. Instead it keeps spooling.

**Comment by anthonyfiore** [comment]
I have close to 285 separated and distinct accounts, all of which I can not enter into when I try. Again in each account that I try to enter it keeps spooling instead of allowing me to enter the specific account.

**Comment by anthonyfiore** [comment]
Moreover, I can not generate another account.  This also spools when I press generate account.

**Comment by andresgalante** [comment]
Ok, thanks for the info. I am trying to figure out if this is an issue with the wallet or btc.us

**Comment by anthonyfiore** [comment]
ok ty

**Comment by Eshwari007** [comment]
@anthonyfiore 
Two ways of creating new account were tested:

1) Via login into Web wallet v2.20.0 and creating new account
2) Via the account 'Sign in' on btc.us where the popup appears and user is allowed to generate a new account

I randomly picked a BNS name and tried to connect to both of them (the first account had some STX on it via ww ) while the second account did not created via account generation in btc .us)

The test passed,sometimes it takes a minute or two to wait and you will get it all worked.
Attaching the screenshots below 
<img width="558" alt="Screen Shot 2021-10-26 at 9 19 00 AM" src="https://user-images.githubusercontent.com/38872890/138888178-8c52b72b-a80a-4f60-b7b0-57a9a8e77194.png">
<img width="539" alt="Screen Shot 2021-10-26 at 9 19 13 AM" src="https://user-images.githubusercontent.com/38872890/138888179-045f2e3f-cb0b-4656-9385-d284e3e9f9be.png">
<img width="1329" alt="Screen Shot 2021-10-26 at 9 20 03 AM" src="https://user-images.githubusercontent.com/38872890/138888180-6f9e02e0-1f90-44c1-8dbf-12dac702532d.png">
<img width="1361" alt="Screen Shot 2021-10-26 at 9 20 20 AM" src="https://user-images.githubusercontent.com/38872890/138888185-f2a19c75-fdfb-4aca-ba5e-1f4638a5c3ef.png">


I also tried using an existing account which has BNS name on it to be tested in btc.us,that was also able to be connected
Do try to use the latest Hiro Wallet release and see if the issues are reproducible

cc @andresgalante

**Comment by anthonyfiore** [comment]
Can you send me the link of the lastest version.

**Comment by anthonyfiore** [comment]
my problem though is that I can not enter an BSN

**Comment by anthonyfiore** [comment]
My problem though is that I can not enter an BNS that I previously have a domain name attached to it; Again it keeps spooling. Maybe it is not the lasted version of the wallet.

**Comment by anthonyfiore** [comment]
Both of the above function that you say you can easily do is not available to me under the version that I have.

**Comment by markmhendrickson** [comment]
@anthonyfiore Please reach out to the .BTC app support email at btcus@app.co if this is still an outstanding problem.
