### ISSUE TITLE
Reduce dependence on Gaia hub

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#1877]
In investigating #1732, I noticed that the wallet breaks if it cannot connect to its Gaia hub.

https://github.com/blockstack/stacks-wallet-web/pull/1870 fixes the most immediate problem: Handling the error cases, by failing silently, ensuring the wallet still works when Gaia is unavailable.

We can, and probably should, further reduce the reliance the wallet has on Gaia.

To explain further: "Creating an account" is simply generating another key. If the resulting address has no balance, nor activity, there is no way to "know" its was ever generated. So, if you were to create 10 accounts, delete, then restore your wallet, we can't know this ever happened. _Unless_ we persist somewhere. This is where Gaia is used. It's updated every time you create a new account.

Currently, we request the "generated account info" / `wallet-config.json` from Gaia on every wallet unlock. Which:
1. Slows down every wallet sign in
2. Adds a reliance on a separate web service

If I understand correctly, the only information we need is the index of the latest account generated. If so, a more resilient implementation might request Gaia on account restoration, but following that, manage this integer locally.

cc/ @hstove @aulneau is there more to the relationship wallet-sdk has to Gaia, in context of account generation?

---------------------------

Edit 2021-12-04: per some of the issues on slow wallet unlock times, I did 5 tests in either scenario:

```
Stable release:
5564ms

Stable release, Fast 3g network throttling:
9446ms

Without gaia dependence
4560ms
```

**Comment by beguene** [comment]
@timstackblock @Eshwari007 
This is ready for testing . PR #2080 

Area impacted:
- Login (new wallet, existing wallet)
- Unlocking

Below a few important test cases.

Test case 1:
1. Create New wallet.
2. create account => 2 accounts are present
3. Lock wallet
4. Unlock wallet

Expected: 2 accounts shall be present

Test case 2:

1. Import an existing wallet with many accounts
2. Lock the wallet
3. Unlock

Expected: All the accounts shall be present

Test case 3:
Same as above but switch between testnet and mainnet
