### ISSUE TITLE
Ensure cache updates for BNS usernames displayed per account

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#1880]
Issues are being reported where newly purchased .btc names are not showing up in the wallet unless reinstalled. We should look at how we are caching account names.

Related issues:
https://github.com/blockstack/stacks-wallet-web/issues/1703
https://github.com/blockstack/stacks-wallet-web/issues/1850

**Comment by getify** [comment]
This is still happening. I purchased my .btc name, and confirmed the API shows I have it: https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SPFBP27YQAR2DRNXNTC7X4MQV9EZXG0RQGXGNNFR

But my wallet didn't update. I signed out and back in and it showed up. So it seems like the wallet needs some sort of "refresh" button to re-request the name.
