### ISSUE TITLE
Sign out checkbox has no feedback

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-app#1886]
hi :~)

When trying to sign out, checking the box does nothing:
![Screen Shot 2021-10-30 at 10 51 15 AM](https://user-images.githubusercontent.com/11803153/139540216-a3703242-5b0c-4358-87f2-a390104c49f0.png)

but the button can work if you pay attention to when you click on the check box (even though it provides no feedback)

**Comment by fbwoolf** [comment]
I experienced this too but no one else seemed to report it. I also have the same experience with the input fields in the popup. When I type nothing happens, but when I click into another field what I typed appears.

**Comment by markmhendrickson** [comment]
This works for me in Chrome fwiw:

<img width="410" alt="Screen Shot 2021-10-31 at 12 31 51" src="https://user-images.githubusercontent.com/28991/139581477-a6da5902-8ebf-4c1b-8893-62135c98b4d7.png">

**Comment by fbwoolf** [comment]
It is really unclear to me what makes this not work sometimes, it is working for me right now in Chrome too.

**Comment by kyranjamie** [comment]
I've seen reports of this before, but has never happened to me. Can you consistently recreate issue @aulneau?

**Comment by GinaAbrams** [comment]
happening for me now and have experienced this relatively consistently in the past 
![Screen Shot 2021-11-11 at 9 49 19 AM](https://user-images.githubusercontent.com/30627583/141318137-8c2df59e-cff8-4eac-aace-9c0d01e79ca5.png)

**Comment by Eshwari007** [comment]
@GinaAbrams Am in Chrome with v2.20.2 and its working fine
<img width="743" alt="Screen Shot 2021-11-11 at 9 58 48 AM" src="https://user-images.githubusercontent.com/38872890/141320125-ccdce9e8-4cd5-4851-af1b-4f15716883c5.png">
<img width="422" alt="Screen Shot 2021-11-11 at 9 59 17 AM" src="https://user-images.githubusercontent.com/38872890/141320126-553d9a04-5785-4a92-91a0-2a5118ce1fb0.png">

**Comment by GinaAbrams** [comment]
I thought the wallet automatically updated but looks like Im in an older version. Ill try the new one.

**Comment by markmhendrickson** [comment]
@GinaAbrams I'm closing this out, but if it's still happening for you, please comment and I'll reopen. 🙏
