### ISSUE TITLE
Unhandled Rejection (Error): Hiro Wallet not installed.

### ISSUE THREAD

**Issue by unclemantis** [blockstack/blockstack-app#1887]
`import React, { useEffect } from "react";
import { Box } from '@blockstack/ui';
import {
    AppConfig,
    openContractCall,
    UserSession,
  } from "@stacks/connect";
import { AnchorMode } from "@stacks/transactions";
import { StacksTestnet } from "@stacks/network";

const userSession = new UserSession();
const network = new StacksTestnet();

export const Deposit = () => {
    useEffect(() => {
        async function mintFT() {
            openContractCall({
                contractAddress: "ST2R33XYMQNZSXXGCBQM7NHQ3YVZ07SQZDTXJZ0QJ",
                contractName: "token3",
                functionName: "mint",
                functionArgs: [],
                anchorMode: AnchorMode.Any,
                userSession,
                network,
              })
        }
        mintFT();
    });

    return (
        <Box width="100%" textAlign="center">
            <Box maxWidth="400px" mx="auto" mt={[6, '100px']}>
                <img src="/logo512.png" alt="WholeCoin"/>
            </Box>
        </Box>
    );
 }
`

**Comment by unclemantis** [comment]
`(define-fungible-token mantis)

(define-public (mint)
    (let (
            (amount u1000000)
            (client tx-sender)
            (contract (as-contract tx-sender))
        )
        (match (stx-transfer? amount client contract)
            success (ft-mint? mantis amount client)
            error   (err u1)
        )
    )
)`

**Comment by markmhendrickson** [comment]
Was this encountered when trying to deploy the contract in your last comment here?

**Comment by unclemantis** [comment]
No. And sometimes it works. I will keep trying

**Comment by timstackblock** [comment]
Could you give me a bit more information about this issue? The title says Hiro wallet not installed could you elaborate on this. Is this a download and installation issue with the Web wallet?
