### ISSUE TITLE
Segment User Agent for chrome reads Mozilla/5.0

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#1893]
Below is the User agent we see when using the wallet with chrome.

"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"

**Comment by beguene** [comment]
This is normal and a legacy thing. It just means that Chrome is Mozilla compatible.
