### ISSUE TITLE
Segment Selected network is coming in NULL

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#1894]
Selected network should read one of the following  (string: mainnet, testnet, devnet or other)
But it is coming up empty

{
  "anonymousId": "380269d7-30b1-43b3-a303-432ddb0db52a",
  "context": {
    "ip": "0***.0***.0***.0***",
    "library": {
      "name": "analytics.js",
      "version": "next-undefined"
    },
    "locale": "en-US",
    "page": {
      "path": "/extension.html",
      "referrer": "",
      "search": "",
      "title": "Hiro Wallet",
      "url": "chrome-extension://khkloghggohkpegfkabdkpknpmkcoehk/extension.html"
    },
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
  },
  "event": "change_network",
  "integrations": {},
  "messageId": "ajs-next-c9b6756957a8707cefa68f3c856f31fe",
  "originalTimestamp": "2021-11-02T17:01:45.890Z",
  "properties": {
    **"network": {**
      "chainId": 1,
      "name": "M***",
      "url": "https://stacks-node-api.stacks.co"
    },
    "route": "/",
    "version": "2.20.1-dev.9.407"
  },
  "receivedAt": "2021-11-02T17:01:46.039Z",
  "sentAt": "2021-11-02T17:01:45.890Z",
  "timestamp": "2021-11-02T17:01:46.039Z",
  "type": "track",
  "userId": null

**Comment by beguene** [comment]
@timstackblock For me it is correctly displayed. I just checked the staging env in segment (Hiro Wallet (web, staging), here is the value:
analytics.page('view', '/', {
  category: 'view',
  name: '/',
  network: {
    chainId: 1,
    name: 'Mainnet',
    url: 'https://stacks-node-api.stacks.co'
  },
  path: '/extension.html',
  referrer: '',
  route: '/',
  search: '',
  title: 'Hiro Wallet',
  url: 'chrome-extension://kmnkahpchooedoclgegoaanmjigpadgb/extension.html',
  version: '2.20.1-dev.9.407'
});

Can you check again ?

**Comment by Eshwari007** [comment]
@beguene Believe this was the bug which @timstackblock indicated in his original post `network: {` is displaying empty.Should this be the case as I see it empty in your value example as well

**Comment by beguene** [comment]
@Eshwari007 Can you see the 'name' attribute in network ?
here it's name: 'Mainnet', which is correct (or Testnet if you use Testnet)

**Comment by Eshwari007** [comment]
I was testing few events and network was populated accurately:
analytics.page('view', '/transaction', {
  category: 'view',
  name: '/transaction',
  **network: 'mainnet',**
  path: '/popup.html',
  referrer: '',
  route: '/transaction',

Moving the issue as done
