### ISSUE TITLE
Fix infinite "view" event triggers upon network change error

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#1896]
To verify this we can change the endpoint to regetest which currently throws 500 error for that api.

We get an infinite spinner in the web wallet app which is expected

But Segment keeps throwing view/ events this will pretty much fill up our logs with tons of events so we want to fix this asap.

<img width="1137" alt="Screen Shot 2021-11-02 at 1 37 19 PM" src="https://user-images.githubusercontent.com/49165468/139917013-6d6f2361-5214-4c30-98d7-8749de382aca.png">
<img width="1270" alt="Screen Shot 2021-11-02 at 1 37 09 PM" src="https://user-images.githubusercontent.com/49165468/139917016-8dd6c85d-3e37-46f7-9279-bf92ce4e1ec0.png">

**Comment by beguene** [comment]
Actually it is not firing infinitely and is not caused by the absent regtest endpoint. The analytics is firing 4 events whenever user changes the route. I will fix it.
