### ISSUE TITLE
Segment events not firing

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#1897]
The following 12 events are not firing

- Authenticate application: When user authenticates application (attributes: app_domain => string)
- Copy address to clipboard: When user selects option to copy address to clipboard
- Submit invalid password: When user submits a valid password for sign up or in
- Enter amount for send: When user enters any value into amount input for send form
- Select maximum amount for send: When user selects maximum value for send form
- Enter recipient for send: When user enters any value into recipient input for send form
- Enter memo for send: When user enters any value into memo input for send form
- Choose to change network: When user chooses to change network from app menu
- Change network: When user selects network
- Transaction state change: When outbound or inbound transaction is recognized with new state (attributes: type => inbound|outbound, state => pending|microblock|anchor|failed, time_since_last_state => time in milliseconds)
- Toggle transaction signing inputs: When user opens or closed view of transaction signing inputs (attributes: action => open|close)
- View API error (attributes: code => number, message => string)

**Comment by markmhendrickson** [comment]
@beguene which if any of these have been implemented already?

**Comment by beguene** [comment]
The list of implemented events are here
https://github.com/hirosystems/stacks-wallet-web/pull/1784#issue-1020182705

**Comment by beguene** [comment]
@timstackblock @Eshwari007 

Authenticate application: When user authenticates application (attributes: app_domain => string)
=> Phase 2 (issue already created)

Copy address to clipboard: When user selects option to copy address to clipboard
=> Already there

Submit invalid password: When user submits a valid password for sign up or in
=> Done

Enter amount for send: When user enters any value into amount input for send form
=> for Phase2

Select maximum amount for send: When user selects maximum value for send form
=> Done

Enter recipient for send: When user enters any value into recipient input for send form
=> for Phase2

Enter memo for send: When user enters any value into memo input for send form
=> for Phase2

Choose to change network: When user chooses to change network from app menu
=> Already there

Change network: When user selects network
=> Already there

Transaction state change: When outbound or inbound transaction is recognized with new state (attributes: type => inbound|outbound, state => pending|microblock|anchor|failed, time_since_last_state => time in milliseconds)
=> Done

Toggle transaction signing inputs: When user opens or closed view of transaction signing inputs (attributes: action => open|close)
=> Phase 2

View API error (attributes: code => number, message => string)
=> Phase 2
