### ISSUE TITLE
Loading switch account takes forever: some issue loading BNS name details?

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#1898]
1. Prior to 2.20.x the bns names would load gradually (or not at all if you did not wait for it) and it would not influence loading of the page after clicking "switch account" now depending on the number of accounts on a keychain it can become almost impossible to select the account until all BNS names have been loaded. Meanwhile the application is hardly responding to clicks, it also crashes if the "extension window with the switch account screen" closes and you start it again (Brave) by clicking the extension icon. 

2. If you do manage to click the account you want to enter into... it shows the loading icon for a long time before actually showing the account details (balance/activity etc).

**Comment by anthonyfiore** [comment]
Again, the WEB WALLET and NOT THE HIRO WALLET is giving me the problem in that it will not allow me to enter, instead, it keeps spooling even if I wait for a long time, the account will not open.

**Comment by 314159265359879** [comment]
> Again, the WEB WALLET and NOT THE HIRO WALLET is giving me the problem in that it will not allow me to enter, instead, it keeps spooling even if I wait for a long time, the account will not open.

With the _Hiro wallet_, you mean the desktop wallet that Hiro makes? I think the Web wallet is also referred to as the _Hiro Wallet for web_ so I think we are talking about the same thing.

**Comment by anthonyfiore** [comment]
I guess!! Its the wallet that you use to buy btc domain names and not the wallet that you initial transfer stx token in order to buy the domain mames.

**Comment by markmhendrickson** [comment]
I'm labeling this as a P2 bug since it appears that the long wait times do sometimes impede account selection completely, not just slow it down?

**Comment by 314159265359879** [comment]
> I'm labeling this as a P2 bug since it appears that the long wait times do sometimes impede account selection completely, not just slow it down?

That is correct. I think it becomes progressively worse the more BNS names you have registered on a private key. 50 is fine, hundreds isn't.

**Comment by andresgalante** [comment]
@kyranjamie I moved this one to QA to make sure that the issue is gone and we have no side effects

**Comment by kyranjamie** [comment]
Sure, you can test build in the PR here https://github.com/hirosystems/stacks-wallet-web/pull/2083

**Comment by Eshwari007** [comment]
The issue is no longer reproducible though I tested with only couple BNS names in Mainnet but I tested a bunch of BNS names over testnet as well.

**Comment by anthonyfiore** [comment]
The problem is still occurring. I have in excess of 240 separate and distinct domain names. Maybe we can have a screen share session??

**Comment by 314159265359879** [comment]
> Sure, you can test build in the PR here #2083

I just tested the Chromium build in that 2083 PR on Brave and it works perfectly, completely solves the issue for me. I look forward to seeing this fix in production. 

@Eshwari007 With the current wallet 2.23.2 I can reproduce the issue, it might be that you do not have enough BNS names registered, a keychain with about 50 names will be workable and does not crash the wallet. Combined with the API issues we had in the last week the keychains with 200+ names were practically inaccessible though.
