### ISSUE TITLE
Ensure app icon display when selecting account for auth

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1903]
I've seen the icon missing here for Megapont during app auth recently, as well as received this report from a user that it's missing for other apps:

<img width="586" alt="Screen Shot 2021-11-05 at 09 40 38" src="https://user-images.githubusercontent.com/28991/140488387-88ebf77f-10a0-4e1d-920f-8b23d0298bcb.png">

**Comment by friedger** [comment]
Something related to the CSP
`Content Security Policy: The page's settings blocked the loading of a resource at <img url> ("default-src").`

**Comment by kyranjamie** [comment]
Fixed above, pending release
