### ISSUE TITLE
Improve unlock performance / prevent from pending for long periods of time

### ISSUE THREAD

**Issue by LCBradley3k** [blockstack/blockstack-app#1907]
I entered my passphrase into the Web wallet on Microsoft Edge Dev Internal browser. It gets stuck infinitely with the loading circle. To isolate the issue, I set up the same wallet on Mozilla Firefox. I added the wallet via my seed phrase. The extension then asked me to create a passphrase. At this step, after adding the passphrase it was also infinitely loading. Thus, the wallet could not even be set up on Mozilla Firefox.

I also set up the desktop version of the app with my seed phrase. I know that does not support a passphrase. The wallet was able to get set up properly on there.

**Comment by markmhendrickson** [comment]
I wonder if you may have encountered this issue as I did recently: https://github.com/hirosystems/stacks-wallet-web/issues/1902

Can you check the extension's background page console for the same error as reported on that issue?

**Comment by markmhendrickson** [comment]
@LCBradley3k I'm going to close this out for lack of activity, but please comment if the above #1902 issue wasn't the culprit and we'll reopen.
