### ISSUE TITLE
Cannot restore wallet on latest Brave nightly build

### ISSUE THREAD

**Issue by lgwillmore** [blockstack/blockstack-app#1912]
I am using Brave nightly, and I currently cannot restore my hiro extension wallet.

Description:

1) Provide seed phrase
2) Enter password
2) Stuck on spinner forever

Current brave nightly version

![image](https://user-images.githubusercontent.com/1360645/141120326-7ba94188-f58d-4826-bea3-d3d2c2986aef.png)

**Comment by markmhendrickson** [comment]
I suspect you may have run into this issue affecting beta builds: https://github.com/hirosystems/stacks-wallet-web/issues/1902

**Comment by lgwillmore** [comment]
@markmhx yup - that looks like it

**Comment by lgwillmore** [comment]
@markmhx there is a brave bat tip waiting for your github account if you verify :wink:

**Comment by markmhendrickson** [comment]
Cool! I don't even know what that is but sounds fun 😆

**Comment by markmhendrickson** [comment]
Ooooh _BAT_ not 🦇 

![image](https://user-images.githubusercontent.com/28991/141122380-b2f6aaad-8e4e-4adf-b51e-039dfb20bc50.png)

I'll look into this 🙏

**Comment by lgwillmore** [comment]
Sorry for cluttering an issue with this chat, but ya,  hirosystems can get verified, but I sent your personal git profile the tip for connecting the dots on the issue :smile:

**Comment by Eshwari007** [comment]
Closing the issue as it has been resolved
cc @markmhx
