### ISSUE TITLE
SIP010 token transfer gets stuck and doesnt post

### ISSUE THREAD

**Issue by bitfari** [blockstack/blockstack-app#1915]
- Click send
- Select a sip010 token
- Set an amount
- Provide a recipient
- Provide a memo (optional)
- Click preview
- The screen will simply disappear and the transaction will not post

**Comment by JakeBlockchain** [comment]
Can confirm i'm having this issue as well trying to transfer MiamiCoin out to an exchange.
Running chrome on Windows has the issue currently.
Moving to Firefox worked fine.

Specifically, I can do everything up until I click "Preview", Then the dialogue box minimizes to a 1x1 empty white box hovering just below the Hiro Wallet icon in the task bar.

**Comment by bitfari** [comment]
After reversal to a previous version, this error is gone. We're on Mac OS X Monterey.

**Comment by fbwoolf** [comment]
> After reversal to a previous version, this error is gone. We're on Mac OS X Monterey.

Can you provide information on what version is working for you?

**Comment by bitfari** [comment]
I reverted to v2.16.0.330 using this guide: https://www.hiro.so/wallet/install-web-source

**Comment by fbwoolf** [comment]
@kyranjamie or @beguene I ran into with moving fees to the send form. Error logs this and is tracked to here:

https://github.com/hirosystems/stacks-wallet-web/blob/82db83a0797eacca86563743d1350eb1491fc075/src/common/utils.ts#L172

![Screen Shot 2021-11-10 at 8 22 26 PM](https://user-images.githubusercontent.com/6493321/141226073-edc68fe0-33be-4d8b-917d-c948e0002ddf.png)

I added this line before L172 locally and fixed it but not totally sure if it's the right solution or what broke it:

`if (hexWithMaybePrefix !== 'string') return hexWithMaybePrefix;`

**Comment by beguene** [comment]
Thanks @fbwoolf 
@kyranjamie I will fix it.
