### ISSUE TITLE
Won't Send Mia

### ISSUE THREAD

**Issue by cubancrypto** [blockstack/blockstack-app#1916]
I fill everything out correctly and when I hit preview the wallet shrinks to a tiny white cube and then nothing happens. 
<img width="56" alt="Screen Shot 2021-11-10 at 7 46 12 PM" src="https://user-images.githubusercontent.com/84804958/141216868-261c1833-c925-411c-86c1-fcf583441074.png">
s

**Comment by kyranjamie** [comment]
We're fixing it, hang tight.

**Comment by kyranjamie** [comment]
Fixed in `v2.20.2`

**Comment by cubancrypto** [comment]
Unfortunately its still doing the same thing

**Comment by kyranjamie** [comment]
@cubancrypto has your extension upgraded to `2.20.2`?

**Comment by cubancrypto** [comment]
Yes but I had to go back to the old version to send the transaction. Will get the new version and try again in a bit
