### ISSUE TITLE
Remove dependence on regtest in our unit tests

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#1920]
Some of our unit tests rely on our API, regtest specifically. As regtest is being deprecated, we should change this to use testnet.

Reenable:
- `src/store/transactions/fungible-token-transfer.spec.ts`
- `src/pages/transaction-signing/hooks/use-submit-stx-transaction.spec.ts`

**Comment by fbwoolf** [comment]
We also have a regtest contract call we should remove from the test-app.

**Comment by markmhendrickson** [comment]
@kyranjamie mind t-shirting this with one of the new labels?

**Comment by markmhendrickson** [comment]
Which unit test(s) in particular are currently impacted by this dependence?

**Comment by andresgalante** [comment]
This should be done soon because there are 2 important tests not running at the moment to release with confidence

**Comment by markmhendrickson** [comment]
This has been hanging out in the backlog for a _loooong_ time. Still important?

**Comment by fbwoolf** [comment]
Neither of the files listed in the description exist any longer but the heystack mocks all use regtest so it does still need to be addressed.

**Comment by andresgalante** [comment]
Why do we keep heystack alive? our docs are not using it anymore.

@markmhx can we just archive it?

**Comment by markmhendrickson** [comment]
Yep go for it
