### ISSUE TITLE
Red text briefly flashed on transaction approval

### ISSUE THREAD

**Issue by obycode** [blockstack/blockstack-app#1922]
I made a transaction, and after I approved it in the popup window, I saw some red text pop up at the bottom of that window just before it closed. It closed too quickly to see what it was. The transaction still appeared to be submitted correctly, as it showed as pending in the explorer.

I attempted to increase the fee in the web wallet, and first the transaction showed as pending, then it went away, then it came back and I clicked the button to increase the fee, set it to 2x, and then when I submitted that, it showed "Your transaction went through. No need to speed it up." After that, it still switches between showing in the list as pending, or not showing up at all.

https://explorer.stacks.co/txid/0xab4a8a194b27398f28d1cb7416bacae91ee9d4aa4ab4cb2c8b234980fba6d505?chain=mainnet

**Comment by obycode** [comment]
Something definitely seems strange with this transaction... I tried again to increase the fee, and it seems to crash the wallet, resulting in this little white box showing instead of the normal wallet view.
<img width="110" alt="image" src="https://user-images.githubusercontent.com/1473715/141319928-f85802c4-6170-4e25-8ce9-6cc5ba68a7a2.png">

**Comment by Eshwari007** [comment]
Hiro wallet:v2.20.2

Few findings I notice while trying to reproduce the issue,will update on the ticket as well,the date of receiving account seems off to Oct but the sending account is accurate.Yes the increase fee in senders account tx vanishes upon selecting  but the second time reopening the window seemed to work with the increase fee dialogue button.I get this square icon near the extension when the increase fee dialogue vanishes
<img width="132" alt="Screen Shot 2021-11-11 at 1 54 53 PM" src="https://user-images.githubusercontent.com/38872890/141353226-52afb202-ba0c-4619-b1ee-6b0209bd3f65.png">

**Comment by Eshwari007** [comment]
Irony is that its not consistent,second and fifth try seems to work fine.
<img width="425" alt="Screen Shot 2021-11-11 at 1 55 53 PM" src="https://user-images.githubusercontent.com/38872890/141353388-3c4f6c04-242c-4626-9447-4a714f748b48.png">
