### ISSUE TITLE
Wallet goes Blank during loading of confirm button

### ISSUE THREAD

**Issue by funkyjames** [blockstack/blockstack-app#1924]
Hi,

I've been trying to send/transfer Funky Donut's from STXNFT to those that have entered our Giveway and have been experiencing an issue where the Hiro Wallet goes blank as it's trying to load the confirm button. The confirm button is pale blue while it's loading (to be able to clicked) and then within 3-4 secs the wallet/screen goes blank.

This has happened to me several times now as it's now happening repeatedly so I'm unable to send the NFT's to the recipients. It was fine for maybe the first 8 transfers and then it started going blank and has ground me to a halt.

I'm using Brave Browser. Hiro wallet v2.20.2

James.

![hiro-wallet-screenshot](https://user-images.githubusercontent.com/94128426/141330792-534cbad6-3174-4385-8806-a8a7901fef4e.png)

**Comment by Eshwari007** [comment]
@funkyjames Chrome seems to have no issue with the steps above.Testing with Brave now

**Comment by kyranjamie** [comment]
We believe this was caused by lack of error handling of the `/mempool` endpoint. @funkyjames, can you try and replicate the issue with `v2.20.3`?

**Comment by markmhendrickson** [comment]
I'm taking this off our board until we can get confirmation from @funkyjames that it's still a problem.

**Comment by funkyjames** [comment]
> I'm taking this off our board until we can get confirmation from @funkyjames that it's still a problem.

Apologies Mark, I've been away for a few days. This seems to no longer be an issue 🙂 Thank you!
