### ISSUE TITLE
Stuck transaction - disappears & reappears from explorer

### ISSUE THREAD

**Issue by BowTiedBustard** [blockstack/blockstack-app#1931]
I've had a transaction (0x0a5a6b0bd810fdd819e989f28797524bbdf506d1feefcc628770851189c51359) pending for >24 hours. 

When viewed in explorer, it shows as pending but sometimes disappears altogether (with the 'pending' page being replaced by a notice saying 'This page is missing' or 'Nothing here yet'). It will then reappear some time later. I have attempted to increase the gas fee but this has no effect. On occasion, I have received a notice saying that 'there is no need to speed up the transaction as it has been processed', but it then still shows as pending.

I am using Hiro web wallet v2.20.3 on Brave.

**Comment by markmhendrickson** [comment]
I'm not seeing this transaction in the Explorer atm. Were you able to resolve your issue here?

If not, mind providing a new transaction ID for lookup?

**Comment by 314159265359879** [comment]
This has been resolved with some of the past improvements to the API. Closing this now. Let me know if it reappears.
