### ISSUE TITLE
Redesign tooltip used across app

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#1933]
After the fee estimations work, we need to circle back and redesign the tooltip used in the web wallet. We are currently using a shared `Tooltip` component from the UI library that either needs to be updated there or abandoned. It doesn't make sense just to redesign it in one place. Right now, the new design shown for fee estimations would be different from the tooltip seen in other parts of the app.

Current:
![Screen Shot 2021-11-12 at 12 48 42 PM](https://user-images.githubusercontent.com/6493321/141519332-45e0dbf8-e58f-42d5-a4f9-3a71dfdd77fa.png)

New design:
![Screen Shot 2021-11-12 at 12 46 26 PM](https://user-images.githubusercontent.com/6493321/141519256-1efd708b-88d3-473e-8515-47d20e176d60.png)

**Comment by pete-watters** [comment]
Closing this off as its outdated and we are using a shared tooltip from our UI package https://www.npmjs.com/package/@leather-wallet/ui
