### ISSUE TITLE
Failed transaction between Binance and Hiro wallet. STX stuck somewhere.

### ISSUE THREAD

**Issue by Weirdcoin** [blockstack/blockstack-app#1934]
Status of transaction is 'Failed'. Funds have not be returned to Binance. Or arrived in the destined Hiro wallet address.
48 hours have been passed by far (few more days).

https://explorer.stacks.co/txid/0xc68542c8ff668ee90f7cecf4957ae3a8de5509dac66291b482b8f52d24841564?chain=mainnet

A day after this transaction a new transaction has been send with newly sold STX. These STX did arrive. I'm still missing the STX reported here.

![image](https://user-images.githubusercontent.com/94184050/141538722-a84ab17c-35bf-404f-bd9b-1587da67568a.png)

**Comment by markmhendrickson** [comment]
If this is a failed transaction from Binance to your wallet and Binance hasn't debited your Binance account with the corresponding amount, you'll need to contact Binance support about the matter.

There isn't anything we can do from the Hiro Wallet side to help here unfortunately.
