### ISSUE TITLE
Integrate standardized UI for fiat onramp options

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#1940]

**Comment by andresgalante** [comment]
- [ ] @beguene to make this available so we can test it with a real card

**Comment by Eshwari007** [comment]
Testing use case(s)

Use Case 1
Expected: 
-Upon wallet installation
-User selects 'I'm new to Stacks'
-User selects I have saved my secret key option
-User signs in with password -User can view the "Buy" button on their account
Actual: **Test passed with the expected steps**

Use Case 2
Expected:
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if a new account is added
Actual:**Test passed with the expected steps**

Use Case 3
Expected:
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has 0 STX
Actual:**Test passed with the expected steps**

Use Case 4
-Upon wallet installation
-User selects 'I'm new to Stacks'
-User selects I have saved my secret key option
-User signs in with password -User can view the "Buy" button on their account
-User selects Transak option
-User selects the credit card option for EU
-User was allowed to purchase in EU for STX
-User received successful purchase dialogue box
**Note**:A link to explorer would be an enhancement of the tx will be created
Actual:**Test passed with the expected steps**


Use case 5
Upon wallet installation
-User selects 'I'm new to Stacks'
-User selects I have saved my secret key option
-User signs in with password -User can view the "Buy" button on their account
-User selects Transak option
-User selects the bank transfer option for EU
-User was allowed to purchase in EU for STX
-User received successful purchase dialogue box with order status and processing time
Actual:**Test passed with the expected steps**

Use Case 6.  
Upon wallet installation
-User selects 'I'm new to Stacks'
-User selects I have saved my secret key option
-User signs in with password -User can view the "Buy" button on their account
-User selects the 'Buy'option
-User selects Transak option
-User selects the credit card option for GBP
-User was allowed to purchase in GBP for STX
-User received successful purchase dialogue box
Actual:**Test passed with the expected steps**

Use Case 7
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has 0 STX
-User selects the 'Buy'option
-User selects Transak option
-User selects the credit card option for GBP
-User was allowed to purchase in GBP for STX
-User received successful purchase dialogue box
Actual:**Test passed with the expected steps**

Use Case 8
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has 0 STX
-User selects the 'Buy'option
-User selects Transak option
-User selects the bank transfer option for EU
-User was allowed to purchase in EU for STX
-User received successful purchase dialogue box with order status and processing time
Actual:**Test passed with the expected steps**

Use Case 9
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has positive STX balance
-User selects the 'Buy'option
-User selects Transak option
-User selects the bank transfer option for EU
-User was allowed to purchase in EU for STX
-User received successful purchase dialogue box with order status and processing time
Actual:**Test passed with the expected steps**

Use case 10
Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has positive STX balance
-User selects the 'Buy'option
-User selects Transak option
-User selects the credit card option for GBP
-User was allowed to purchase in GBP for STX
-User received successful purchase dialogue box
Actual:**Test passed with the expected steps**



**Note** :The above was an existing account with 0 STX in it 
The enhancement ticket for having a link to explorer:https://github.com/hirosystems/stacks-wallet-web/issues/2040

**Comment by Eshwari007** [comment]
List of potential known issues are listed :https://github.com/hirosystems/stacks-wallet-web/issues/2042
This may be helpful to assist support team
