### ISSUE TITLE
Implement Okcoin

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#1941]

**Comment by Eshwari007** [comment]
@beguene Upon selecting 'Buy on Okcoin' receiving the below:
<img width="1304" alt="Screen Shot 2021-12-01 at 1 41 03 PM" src="https://user-images.githubusercontent.com/38872890/144294910-907e65bb-ee25-4746-b78a-8d12af0789d5.png">

**Comment by Eshwari007** [comment]
cc @markmhx

**Comment by markmhendrickson** [comment]
I believe Okcoin has not intended to release their support here for the flow just yet. We'll have to wait until they do to test this end-to-end. However, once they do release it, we will need to test with a VPN.

**Comment by beguene** [comment]
@markmhx @Eshwari007 I will disable Okcoin before merging into dev.

**Comment by Eshwari007** [comment]
Sounds good-thank you

**Comment by Eshwari007** [comment]
> I believe Okcoin has not intended to release their support here for the flow just yet. We'll have to wait until they do to test this end-to-end. However, once they do release it, we will need to test with a VPN.

How will the VPN testing be?,a suggested one from Okcoin I believe.Just making sure the users doesn't feel its complicated or requiring additional steps may prevent their engagement time with our product

**Comment by markmhendrickson** [comment]
The VPN is only needed for our pre-release staged testing. I believe @beguene has the info to set you up if you need it.

**Comment by Eshwari007** [comment]
Moving this ticket to Ready for Merge as we are disabling Okcoin for the release
cc @markmhx @beguene

**Comment by andresgalante** [comment]
I'll move this and #1940 to Done and open a new one once OKcoin is ready to ship
