### ISSUE TITLE
Implement Transak

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#1942]

**Comment by Eshwari007** [comment]
@beguene 
Couple of initial findings or perhaps questions:
<img width="521" alt="Screen Shot 2021-12-01 at 1 22 37 PM" src="https://user-images.githubusercontent.com/38872890/144291696-261503db-8e7d-4d9f-93e1-59a0d38e559a.png">
Upon selecting Transak,am noticing ETH as default with USD
Only after selecting different currency such as GBP and EURO ,STX is populated
<img width="1413" alt="Screen Shot 2021-12-01 at 1 22 08 PM" src="https://user-images.githubusercontent.com/38872890/144291937-2157dd2c-ae1b-42b8-bfb2-ebd628e95719.png">
If I select USD again after selecting different currency ,receive the below:
<img width="524" alt="Screen Shot 2021-12-01 at 1 22 23 PM" src="https://user-images.githubusercontent.com/38872890/144292026-f8e9dfb5-6484-4464-b771-3824673e9f2e.png">
which I believe is correct behavior

Also noticed when I select INR
<img width="526" alt="Screen Shot 2021-12-01 at 1 21 51 PM" src="https://user-images.githubusercontent.com/38872890/144292111-98512a36-5f31-4b23-ab3e-adc872222eb3.png">
the error thrown is `INR is temp suspended` instead the default error for other currency which is `STX is temp suspended`

**Comment by Eshwari007** [comment]
Tested Okcoin and receiving the below upon selecting `<img width="1304" alt="Screen Shot 2021-12-01 at 1 41 03 PM" src="https://user-images.githubusercontent.com/38872890/144294297-04b3eb65-ea86-4fb7-993e-60a938c34bf2.png">`

**Comment by timstackblock** [comment]
STX rate is also incorrect 1 STX is 4667 GBP 🚀  we wont hit that price unil next year lol

<img width="624" alt="Screen Shot 2021-12-01 at 1 56 50 PM" src="https://user-images.githubusercontent.com/49165468/144296410-3e9cc8d7-2274-4224-ad76-6e68c4bcaec3.png">

**Comment by markmhendrickson** [comment]
I've asked the Transak team about the above issues

**Comment by beguene** [comment]
@Eshwari007 STX cannot be purchased with USD in transak.

**Comment by markmhendrickson** [comment]
We should have what we need now in the Transak dashboard to wire up the flow for production:

![image](https://user-images.githubusercontent.com/28991/144591435-18827654-f154-4ba5-99fb-33742a2a268f.png)

**Comment by beguene** [comment]
I will add the keys and update the PR.

**Comment by beguene** [comment]
@Eshwari007 @timstackblock I updated the PR https://github.com/hirosystems/stacks-wallet-web/pull/1981 to be in production mode for transak so you can test with a real CC.
I also deactivated okcoin since they are not ready yet.
@markmhx @andresgalante If all is good for QA, I will merge it to dev later today or on Monday so we can release next week.

**Comment by Eshwari007** [comment]
THank you @beguene ,will take a look at it and keep you posted

**Comment by Eshwari007** [comment]
> STX rate is also incorrect 1 STX is 4667 GBP 🚀 we wont hit that price unil next year lol
> 
> <img alt="Screen Shot 2021-12-01 at 1 56 50 PM" width="624" src="https://user-images.githubusercontent.com/49165468/144296410-3e9cc8d7-2274-4224-ad76-6e68c4bcaec3.png">

This issue seemed to be fixed now ,tested with few currency such as GDP and EURO.INR is not supported at the moment

**Comment by Eshwari007** [comment]
@markmhx I'll post this in Transak Telegram as well but little confusing as in GDP selection,indicated initially minimum 15 for the first time then switched to 60 when I entered 15
<img width="630" alt="Screen Shot 2021-12-03 at 10 05 01 AM" src="https://user-images.githubusercontent.com/38872890/144624987-93470ff3-f9a4-47da-8685-37492bc9c944.png">
<img width="688" alt="Screen Shot 2021-12-03 at 10 05 24 AM" src="https://user-images.githubusercontent.com/38872890/144625047-b73e0a6c-b18b-4f1a-9592-4fb093c426c7.png">

I suspect one validation is for the currency value and the other one is for number of STX to be purchased if my assumptions is accurate

**Comment by Eshwari007** [comment]
Just submitted my KYC,waiting for approval and will continue with purchase.Hoping it would let me buy in GBP.
cc @markmhx @beguene @timstackblock @andresgalante

**Comment by Eshwari007** [comment]
Test passed with @kyranjamie KYC .STX purchase was tested on Transak via Credit card purchase and Bank transfer.Attaching screenshot for reference.
<img width="807" alt="Screen Shot 2021-12-06 at 9 29 43 AM" src="https://user-images.githubusercontent.com/38872890/144864215-972bcf66-3d9d-46c9-acd2-4f1b8a55601f.png">
<img width="454" alt="Screen Shot 2021-12-06 at 9 30 04 AM" src="https://user-images.githubusercontent.com/38872890/144864216-d33894bf-097e-458b-8243-563e25e49329.png">

**Comment by Eshwari007** [comment]
A small enhancement in ensuring the link of the transaction in explorer :https://github.com/hirosystems/stacks-wallet-web/issues/2040
cc @markmhx @andresgalante @beguene

**Comment by Eshwari007** [comment]
Testing use case(s)

Use Case 1
Expected:
-Upon wallet installation
-User selects 'I'm new to Stacks'
-User selects I have saved my secret key option
-User signs in with password -User can view the "Buy" button on their account
Actual: Test passed with the expected steps

Use Case 2
Expected:
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if a new account is added
Actual:Test passed with the expected steps

Use Case 3
Expected:
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has 0 STX
Actual:Test passed with the expected steps

Use Case 4
-Upon wallet installation
-User selects 'I'm new to Stacks'
-User selects I have saved my secret key option
-User signs in with password -User can view the "Buy" button on their account
-User selects Transak option
-User selects the credit card option for EU
-User was allowed to purchase in EU for STX
-User received successful purchase dialogue box
Note:A link to explorer would be an enhancement of the tx will be created
Actual:Test passed with the expected steps

Use case 5
Upon wallet installation
-User selects 'I'm new to Stacks'
-User selects I have saved my secret key option
-User signs in with password -User can view the "Buy" button on their account
-User selects Transak option
-User selects the bank transfer option for EU
-User was allowed to purchase in EU for STX
-User received successful purchase dialogue box with order status and processing time
Actual:Test passed with the expected steps

Use Case 6.
Upon wallet installation
-User selects 'I'm new to Stacks'
-User selects I have saved my secret key option
-User signs in with password -User can view the "Buy" button on their account
-User selects the 'Buy'option
-User selects Transak option
-User selects the credit card option for GBP
-User was allowed to purchase in GBP for STX
-User received successful purchase dialogue box
Actual:Test passed with the expected steps

Use Case 7
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has 0 STX
-User selects the 'Buy'option
-User selects Transak option
-User selects the credit card option for GBP
-User was allowed to purchase in GBP for STX
-User received successful purchase dialogue box
Actual:Test passed with the expected steps

Use Case 8
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has 0 STX
-User selects the 'Buy'option
-User selects Transak option
-User selects the bank transfer option for EU
-User was allowed to purchase in EU for STX
-User received successful purchase dialogue box with order status and processing time
Actual:Test passed with the expected steps

Use Case 9
-Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has positive STX balance
-User selects the 'Buy'option
-User selects Transak option
-User selects the bank transfer option for EU
-User was allowed to purchase in EU for STX
-User received successful purchase dialogue box with order status and processing time
Actual:Test passed with the expected steps

Use case 10
Upon wallet installation
-User selects 'Existing user with password'
-User enters secret password
-User signs in with password -User can view the "Buy" button on their account if the account has positive STX balance
-User selects the 'Buy'option
-User selects Transak option
-User selects the credit card option for GBP
-User was allowed to purchase in GBP for STX
-User received successful purchase dialogue box
Actual:Test passed with the expected steps

Note :The above was an existing account with 0 STX in it
The enhancement ticket for having a link to explorer:#2040
