### ISSUE TITLE
Added network is lost after restarting Chrome

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#1943]
While testing ALEXGO we are using a custom testnet. Anyone interested in the community can help test the dapp as long as they go through some steps to get access tot the ALEXian network. 

The connection is however lost when restarting the browser. The web extension defaults to mainnet and you have to manually 'add a network' again. The confusion for the user is enlarged by the fact that the dapp does retain it's login to the right network and will show account details for the test network. It is only when they start sending transactions that they notice something is wrong (contracts/account balance can't be find).

I suggest storing this data, for a custom network, so it can be retained when restarting. 
![image](https://user-images.githubusercontent.com/33360391/141815016-687a0fac-eda0-418b-96c6-5ea56e4b5082.png)

**Comment by markmhendrickson** [comment]
Thanks for the report! We'll investigate.

**Comment by markmhendrickson** [comment]
@314159265359879 does this remain a problem?

**Comment by 314159265359879** [comment]
no this is not a problem anymore. 
The network is still lost on occasion though. I will investigate and make a new issue when I find out more.
