### ISSUE TITLE
Max button is not working 

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1945]
Thought I had found the issue in Fee Estimate PR, @fbwoolf had confirmed the issue was not related to the new feature.
Currently ,the UI is returning high value of fees in thousands hence believe this could have impacted the Max button on the UI.However the Max button is working fine for other tokens such as Hey Token and Stella.
This seems to be STX specific only.
Creating the ticket for tracking purposes and will re test the issue upon the fee estimate high return is fixed

cc @fbwoolf

**Comment by andresgalante** [comment]
I don't understand the issue, if it's a visual bug would it be ok to add a screenshot to understand it better, please?

**Comment by Eshwari007** [comment]
The issue has been fixed.The `Max`button was not working for STX hence it had to be reworked from API endpoint by Dev as the values for fees was returned high yesterday.The issue has been fixed .
**Chat transcript from discord from Dev ** : think we might want to change there and use the fee instead of the fee_rate from the endpoint to calculate the amount available bc if a user even goes and changes the fee with the custom input, the fee_rate from the endpoint is still being used and therefore the button doesn't work.

`Max`is working in both Testnet and Mainnet (tested various tokens as well)
cc @andresgalante @fbwoolf
