### ISSUE TITLE
Blank screen when Send button is selected

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1949]
This may not be related to the PR but as I am testing Fee estimate:https://github.com/hirosystems/stacks-wallet-web/issues/1728
Noticed that when user switches between accounts in mainnet and tries to select Send button,a blank screen is populated for few sec sometimes .Its always the very first time when user switches to a new account and tries the Send button.Attaching video for perusal

https://user-images.githubusercontent.com/38872890/142070084-163a875e-785f-4575-aecb-4ec7fa341687.mov

**Comment by markmhendrickson** [comment]
Thanks for this catch. I'm removing "P3 Bug" since generally visual bugs should be labeled without P1, etc. additionally (as they aren't _functional_ bugs that prevent users from doing things; they're more glitches than anything else).

**Comment by kyranjamie** [comment]
I've noticed this too, there's definitely some async work going on that's fallback back to nothing.

**Comment by Eshwari007** [comment]
> I've noticed this too, there's definitely some async work going on that's fallback back to nothing.

Yes,this happens both on the ext popup dialogue and on the full page screen as well of WW.

**Comment by markmhendrickson** [comment]
@kyranjamie: we can perhaps disable suspense with reactquery

**Comment by fbwoolf** [comment]
> @kyranjamie: we can perhaps disable suspense with reactquery

You have to enable suspense with react-query: https://react-query.tanstack.com/guides/suspense

**Comment by fbwoolf** [comment]
If I remove the suspense boundary around `<SendTokensForm />` in the routes it seems to fix this for me locally but not sure that is the right solution. Testing it.
