### ISSUE TITLE
Set fee to zero when using sponsored transactions

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-app#1954]
Hey everyone 😄 

I've been playing with sponsored transactions, and for the most part everything already works really well from a user experience standpoint. However, the API doesn't handle fees for sponsored transactions very well, and it can end up with users having a negative balance!

Discussed more here: https://github.com/hirosystems/stacks-blockchain-api/issues/857

For sponsored transactions, there are two "fees" - the regular spending condition, and the sponsor spending condition. They each have a "fee", but only the sponsor's spending condition is what has any effect.

Overall, I think it would be great if the wallet simply hard-coded the fee to zero for sponsored transactions. Right now I can't set a zero-fee by any means (i.e. in transaction request or by changing it in the UI), so I'd imagine this would lead to a lot of confusion for end users.

❤️

**Comment by markmhendrickson** [comment]
Thanks for the report! Mind attaching a screenshot so we can visualize the negative balance case? As well as how the regular fees are showing alongside (or in spite of) the sponsored transaction label?

**Comment by hstove** [comment]
Absolutely! Here's a [mainnet address](https://explorer.stacks.co/address/SPY3T5EAGZQYCG3294CYSQGZB6CADZX9V17C0XNB?chain=mainnet) showing negative balance on the explorer - it's the same in the wallet because the STX balances come from the same APIs.

In the transaction popup it shows the 'sponsored' item, which is perfect:

![image](https://user-images.githubusercontent.com/1109058/142207446-85b3270a-2a9f-4bf4-8ccb-25ad13743094.png)

When you go to 'settings', though, you can see that the fee is set by default (like non-sponsored transactions), even if I specify a custom fee from my app that triggered this tx. This mainly has the unfortunate downstream effects of showing a 'negative' balance, but that's only because of the API issue I linked above.

![image](https://user-images.githubusercontent.com/1109058/142207398-b08a6526-21e5-4981-a064-14b0fa076271.png)

If I try and change that fee (in settings) to zero, it has a validation error (amount must be positive)

**Comment by markmhendrickson** [comment]
@fbwoolf let's take a look at how sponsored transactions work here in light of your recent fee estimates work?

My sense is that we'll need simply to remove the fee adjustment options entirely when transactions are sponsored (with "Settings" here becoming "Edit nonce" in any case).

We don't seem to have an explicit mockup of sponsored transactions in [our design set](https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=3%3A12) these days. Assigning to @eugeniadigon as well so she can add one when she has a chance.

**Comment by markmhendrickson** [comment]
- Add option to demo app to test sponsored transactions
- Add to QA routine
- Add automated test

I'm putting this into design so @eugeniadigon can take a full look at sponsored transactions in general here and represent them in Figma clearly, even if the modifications compared to non-sponsored transactions are minimal.

**Comment by pseudozach** [comment]
Hi, is there any update on this?

For my use case (https://github.com/hirosystems/stacks-wallet-web/issues/2141) only requirement is that a user with 0 STX balance should be able to sign a sponsored transaction without broadcasting it.

And this is not for demo or localnet purposes but actual mainnet users being onboarded with no STX.

Maybe a quicker fix can be made while waiting for design work to be done involving other aspects.

**Comment by diwakergupta** [comment]
> Hi, is there any update on this?
> 
> For my use case (#2141) only requirement is that a user with 0 STX balance should be able to sign a sponsored transaction without broadcasting it.
> 
> And this is not for demo or localnet purposes but actual mainnet users being onboarded with no STX.
> 
> Maybe a quicker fix can be made while waiting for design work to be done involving other aspects.

Yes, see https://github.com/hirosystems/stacks-wallet-web/issues/2141#issuecomment-1017038007 -- we'll try to have this fixed in the next release, thanks!

**Comment by fbwoolf** [comment]
@eugeniadigon this was upgraded to a P2 bug, should I pull the design work out into another issue so we don't lose track of it?

**Comment by Eshwari007** [comment]
Noticed that the vercel app with the sponsored tx https://stacks-wallet-web-git-fix-sponsored-tx-error-blockstack.vercel.app/ is showing up blank as indicated by @CharlieC3  and @fbwoolf 
@kyranjamie Do you have any input to this which will help to test the sponsored tx?

**Comment by fbwoolf** [comment]
@Eshwari007 just so you aren't blocked in situations like this, you might just take some time to get the test-app running locally. It is very simple and will allow you test changes more easily.

**Comment by Eshwari007** [comment]
Going to test the test-app running locally using https://github.com/hirosystems/stacks-wallet-web#optional-run-test-app following the read me instruction. Will keep you posted

**Comment by Eshwari007** [comment]
@fbwoolf Testing the test app locally.
When I connect to a test account on testnet, receive a blank wallet. I test the test app (locally ) with another PR and it's working fine , just that the sponsored tx was not visible as it was diff build.
<img width="1183" alt="Screen Shot 2022-02-01 at 10 36 27 PM" src="https://user-images.githubusercontent.com/38872890/152175277-b6e82af5-6b7c-48d8-be89-f5684a5ab656.png">

**Comment by fbwoolf** [comment]
@Eshwari007 are you running the wallet locally at the same time? You likely need to run `yarn dev` in another terminal window and load the dist folder into your extensions?

**Comment by Eshwari007** [comment]
Tested the sponsored tx by running the test app locally
Test passed. Thanks @fbwoolf for the input
<img width="455" alt="Screen Shot 2022-02-02 at 3 45 39 PM" src="https://user-images.githubusercontent.com/38872890/152234663-94ccec51-cf93-4789-a547-1e5bf4e4bb92.png">
