### ISSUE TITLE
'Max' button selection returning error when non STX token is selected

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1959]
User was testing Fee Estimate PR
When an user selects non STX token such as Stella,Rocket and etc,the fee estimate points to Custom with 0.000 STX value.
Believe this is accurate as the API isnt returning any value hence the case
But when user selects 'Max' for the non STX token in the WW ,user is receiving 'Unable to calculate Max'
<img width="393" alt="Screen Shot 2021-11-17 at 2 17 52 PM" src="https://user-images.githubusercontent.com/38872890/142270967-aeb17536-8f28-422b-bd17-63ba90775e54.png">
<img width="382" alt="Screen Shot 2021-11-17 at 2 17 59 PM" src="https://user-images.githubusercontent.com/38872890/142270970-9d626576-11c9-4501-be2d-25f2cb570d6a.png">
<img width="389" alt="Screen Shot 2021-11-17 at 2 18 27 PM" src="https://user-images.githubusercontent.com/38872890/142270972-03b4f9ae-68c3-4d8f-9e2f-614959a4b6f6.png">
<img width="393" alt="Screen Shot 2021-11-17 at 2 19 32 PM" src="https://user-images.githubusercontent.com/38872890/142270973-350fa41d-0e8c-4183-8761-c42836886281.png">

@fbwoolf and myself had discussed abt this on Discord but would like @markmhx @eugeniadigon @kyranjamie thoughts on how handle the use case:
@fbwoolf comment:I had it filling in the total amount available as a default but that was problematic bc then entering the custom fee would be over and cause an error message.Currently, it fills in the total amount available
Myself:Maybe we need to provide some info for the users on why Max wont work for this non STX token as the fee estimation will not be returned for them.Your thoughts?
Or perhaps tweak how the Max functionality works for non STX token

**Comment by kyranjamie** [comment]
This is a bug. We only need to know the fee to calculate the max spend of STX, as the fee is also paid in STX.

The fee has no bearing on the max spend of other fungible tokens, so we should never see this toast error.
