### ISSUE TITLE
Set custom value for fees selection to zero by default

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1960]
It would be nice to have Custom value in Fee Estimate to populate 0.000000 and also a suggestion if that is doable.
Currently Custom value is cached to any previously selected value from the fee estimate dropdown list
<img width="378" alt="Screen Shot 2021-11-15 at 11 34 36 PM" src="https://user-images.githubusercontent.com/38872890/142271790-86b77f7a-ef1f-4a56-80b8-3d533a656a34.png">
<img width="421" alt="Screen Shot 2021-11-15 at 11 34 43 PM" src="https://user-images.githubusercontent.com/38872890/142271822-a303fc2d-963d-4ed6-8f30-d864ad7b24b6.png">

**Comment by fbwoolf** [comment]
@Eshwari007 I am going to implement this behavior on this PR: https://github.com/hirosystems/stacks-wallet-web/pull/1971

I'll change it so the default for custom input is just `0.000000`.
