### ISSUE TITLE
Increase Fee intermittent issues

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1961]
Testing :v2.21.0-dev.3
Increase fees works for certain accounts in Mainnet and doesnt for some ,I have seen similar patterns in Testnet as well.
Not quite sure what is triggering this issue as its very intermittent
<img width="387" alt="Screen Shot 2021-11-17 at 2 49 47 PM" src="https://user-images.githubusercontent.com/38872890/142273581-53b62c06-1a6f-4aed-a608-4e8d3c234f4b.png">
<img width="380" alt="Screen Shot 2021-11-17 at 2 50 32 PM" src="https://user-images.githubusercontent.com/38872890/142273582-80d84445-bd22-4de7-9d0f-e42c5e1a4e4f.png">
<img width="640" alt="Screen Shot 2021-11-17 at 2 59 02 PM" src="https://user-images.githubusercontent.com/38872890/142273584-66600103-e700-4437-9bc7-58c4cf0a4094.png">

**Comment by markmhendrickson** [comment]
Does it not work in the sense that the "Increase fee" option doesn't respond at all when clicked?

**Comment by markmhendrickson** [comment]
cc @Eshwari007 👆

**Comment by Eshwari007** [comment]
@markmhx This issue is outdated and no longer able to be reproduced.
