### ISSUE TITLE
High fee warning confirmation

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#1967]
Creating an issue to track the implementation of the high fee warning confirmation drawer:
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=1356%3A12852

**Testing:**
- Send a transaction
- Input a custom fee higher than 5 STX
- Notice the high fee confirmation
- `Edit fee` takes you back to send form
- `Yes, I'm sure` moves you forward to confirm tx

cc: @markmhx @eugeniadigon

**Comment by fbwoolf** [comment]
@markmhx @eugeniadigon what are you thinking triggers this drawer confirmation? Is it when the user clicks on `Preview` the drawer pops up for confirmation?

**Comment by markmhendrickson** [comment]
Yep that's what I had in mind for the trigger if it's a simple STX transfer. Although I suppose we could trigger it upon "Confirm" within the preview view as well.

Otherwise upon selection of "Confirm" if it's a contract execution or deploy. 

@eugeniadigon can (no pun intended) confirm

**Comment by ginny-d** [comment]
agree with @markmhx
