### ISSUE TITLE
Replace-by-fee tx on dev moves back into `Submitted`

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#1975]
I am seeing this behavior on dev so I wanted to create an issue for it. Hoping to confirm others are seeing it?

When I do a `replace-be-fee` the tx moves from the tx list back into the `Submitted` list and won't clear from local storage unless I do it manually.

cc @Eshwari007 

![Screen Shot 2021-11-22 at 8 32 52 AM](https://user-images.githubusercontent.com/6493321/142881652-37d59415-72ed-4bb8-92fb-3a067055a731.png)

**Comment by Eshwari007** [comment]
Yes, @fbwoolf I see it too but it goes away after the tx is confirmed.Thanks for bringing the topic as wasnt sure if it was bug

**Comment by fbwoolf** [comment]
@Eshwari007 mine doesn't seem to clear out even after the new tx is confirmed, yours does?

**Comment by fbwoolf** [comment]
And, I have a lot of transactions listed under `Today` which were not done today.

**Comment by markmhendrickson** [comment]
@kyranjamie can take a look since his refactor work may have caused this related to atoms

This is on dev so we need to resolve before releasing.
