### ISSUE TITLE
No guidence in what fee to set. Starts with a fee of 0?

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#1993]
2.21.1 has no guidance to set a custom fee, how would the user know what to do?
Environment: Windows 10, Firefox (latest), Hiro Wallet for web 2.21.1
 
![image](https://user-images.githubusercontent.com/33360391/143408481-daccc619-93dc-4016-8125-fc8cecb5a66b.png)

When I hover over the "i" I see this:
![image](https://user-images.githubusercontent.com/33360391/143408242-3a0f801f-88fc-48c2-a903-8af943906269.png)

And when I click the "i" see something I am suppose to see...
https://www.hiro.so/questions/how-do-transaction-fees-work-with-the-hiro-wallet

**Comment by 314159265359879** [comment]
So I am missing these options for low medium high
![image](https://user-images.githubusercontent.com/33360391/143408768-3e9db9ac-a5a9-47ed-90cb-efdcb3eec01e.png)

**Comment by 314159265359879** [comment]
On the a more commonly used contract call (PoX contract) "allow-contract-caller" I do get a prefilled fee. 
https://www.dropbox.com/s/m4fkn2h67mwhwwd/Screenshot%202021-11-25%2013.16.54.png?dl=0

**Comment by 314159265359879** [comment]
On a more commonly used contract call (pox) allow-contract-caller I do get a standard fee and the dropdown menu. No default filled I think is puzzling for a user. Perhaps start with the minimum fee required in that case? (there is a minimum to send it to the mempool such as 180 uSTX for a STX transfer)

![image](https://user-images.githubusercontent.com/33360391/143440995-3d9cf0e4-b6f3-4df0-92d2-a1a7d50841ff.png)

**Comment by paradigma-cl** [comment]
The values of Standard, Low and High are very high!  Just for a stx transfer.  It is 5.8 % of the amount to send in Low, and 6% in standard, and High nearly the value of the transfer.  Is it correct?  So I tried to set it with custom, to 0.02 STX.

**Comment by paradigma-cl** [comment]
in  Chrome.

**Comment by markmhendrickson** [comment]
@paradigma-cl What absolute values were you seeing here that seemed especially high?

**Comment by markmhendrickson** [comment]
@314159265359879 we've resolved your original report here of not seeing fee suggestions with: https://github.com/hirosystems/stacks-wallet-web/pull/1998

Please upgrade to the latest version in the stores and it should be working now.

(Closing but we can keep commenting here about @paradigma-cl's high fees report anyway)

**Comment by paradigma-cl** [comment]
> 

Yes, now values are more reasonable.  Thanks!  Well done

**Comment by 314159265359879** [comment]
@markmhx here is an example of specially high fees:
To stack-tokens in the NYC contract these are the options shown
Low 0.25 STX
Medium 18 STX (a minute before it was 1,7 STX)
High 86 STX (a minute before it was 75 STX)

Checking the fees payed yesterday at https://www.stxstats.co/
I see a total of 3059 STX was payed covering a total of 3893 transactions that day. That informs me somewhat about the average cost of transactions today: 3059/3893 = 0,79 STX per transaction (the day before it was 0,59 STX per transaction).

Some of the latest transactions that got mined (is it possible to see how long it was in the mempool?) (fee payed 0,606 STX
https://explorer.stacks.co/txid/0xf437334429e54f105143d445a20c87adc1559758090651c1bef3ee919b3c4136?chain=mainnet
Fee payed 1 STX
https://explorer.stacks.co/txid/0xa694b42f683fca4c2dd1d5d47fe00a91d002b8ffb38e31f6405864a0a51b80e6?chain=mainnet

These really high values for Medium and High do not look right. 

here is a more extreme example from Arkadiko (453 STX medium fee!):
![image](https://user-images.githubusercontent.com/33360391/143676400-18c99687-61b0-481e-93d2-c21729c0f0e7.png)

**Comment by markmhendrickson** [comment]
Thanks for this comprehensive data 🙏🏻 We've released v2.21.4 to Chrome that caps low, standard and high values at 5, 15 and 25 STX respectively. It'll be available in Firefox soon as well.

This should help while we analyze why higher amounts were getting displayed in the previous release.
