### ISSUE TITLE
Prevent negative fee values in input for transaction signing

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#1994]
Wallet version 2.21.1
![image](https://user-images.githubusercontent.com/33360391/143408887-b759260e-679f-4224-9cb7-979fb611e1c1.png)

**Comment by 314159265359879** [comment]
I saw this option in Firefox but not in Chrome on 2.21.0
.

**Comment by kyranjamie** [comment]
Likely needs a `min` html attribute on the input cc/ @fbwoolf

**Comment by Eshwari007** [comment]
Interesting,am receiving amount must be positive in both FF and Chrome-latest version

**Comment by Eshwari007** [comment]
<img width="408" alt="Screen Shot 2021-11-25 at 12 40 42 PM" src="https://user-images.githubusercontent.com/38872890/143484972-6744eab8-8ca0-4b34-96d0-4d1638880d27.png">
<img width="389" alt="Screen Shot 2021-11-25 at 12 47 21 PM" src="https://user-images.githubusercontent.com/38872890/143484973-326d2636-defe-4e1f-99d7-3f76b35b9d66.png">

**Comment by fbwoolf** [comment]
I would bet if the user clicks on `Preview` they would see the validation error. Just bc the input takes the value doesn't mean our form will accept it. The validation occurs on submit.

**Comment by Eshwari007** [comment]
Agree,upon selecting Preview the error message appears
