### ISSUE TITLE
Switch account popup is truncated

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2000]
Release version:v2.21.3

Noticed that when 'Switch account' is selected ,a small popup appears without the list of accounts.When user reselects the switch account,user is able to view the list of accounts
<img width="717" alt="Screen Shot 2021-11-26 at 3 12 14 PM" src="https://user-images.githubusercontent.com/38872890/143626389-3dc7f567-b04d-4425-9eb2-4b405039030b.png">
This happened both in Chrome and FF when its fresh install of a new version in web wallet.

**Comment by markmhendrickson** [comment]
I've encountered this as a loading state, in that the full modal with accounts appears after a delay of a few seconds at most.

**Comment by markmhendrickson** [comment]
@Eshwari007 have you seen this more than once as more than just a delay but needing to go back to select it again?

**Comment by andresgalante** [comment]
@kyranjamie Would you be able to take a look at this issue this week please?

**Comment by kyranjamie** [comment]
I can't replicate this issue. Investigating what might have caused it.

**Comment by kyranjamie** [comment]
If accounts is `undefined` we render nothing, so this may have happened here. Accounts should never be `undefined`, though. I've added a warning and analytics event, and used this opportunity to do some refactoring. 

If users often see this issue, we'll know about it and can investigate further.

**Comment by andresgalante** [comment]
Should we move this to QA?
