### ISSUE TITLE
Fix selection of account for authentication

### ISSUE THREAD

**Issue by anthonyfiore** [blockstack/blockstack-app#2006]
I am having a major problem with your web wallet. I had purchased approximately 250 domain names in separate accounts without any issues. Now when I try to enter a certain account which contains a separate domain name, I can not do so. The web wallet continues to spool in a circle without opening the respective account. I wanted to link an email with the respective account.
Anthony

**Comment by anthonyfiore** [comment]
This problem has been occurring for quite a long time. Are other people have purchased multiple distinct domain names experiencing the same problems?  I am willing to screen share to make it easier for the technician resolve this issue.  Kindly advise.

**Comment by 314159265359879** [comment]
Thank you for reporting. This is related to/like #1898

**Comment by markmhendrickson** [comment]
@anthonyfiore Please do share a screenshot of the network calls that are pending forever if you can

**Comment by anthonyfiore** [comment]
See the attached screenshot which shows the issue trying to open any of the separate and distinct accounts that represent the BTC domain names.


-----Original Message-----

**Comment by markmhendrickson** [comment]
@anthonyfiore it appears your screenshot wasn't included?

**Comment by anthonyfiore** [comment]
Yes it was attached. I checked my Sent folder and it's attached.  I am attaching it here again. It is a .PNG file.  Let me know, thanks.


-----Original Message-----

**Comment by markmhendrickson** [comment]
Sorry there must me an issue with GitHub attaching the image to this issue. Mind emailing me it directly to mark@hiro.so?

**Comment by markmhendrickson** [comment]
From @anthonyfiore: 

![image](https://user-images.githubusercontent.com/28991/144591556-92aae676-02f6-49ea-8984-e1c5c94e177b.png)

**Comment by markmhendrickson** [comment]
It appears this could be a duplicate of #1898 as @314159265359879 suggests.

**Comment by anthonyfiore** [comment]
I am still having this problem???? I have in excess of $3000.00 tied up here. What is the status????

**Comment by anthonyfiore** [comment]
I am still having an issue opening my respective btc domain names!! Can anyone contact me at agfiore@verizon.net to tell me the status of what the possible solutions is to this problem.

**Comment by anthonyfiore** [comment]
Has anything been done to resolve my issue?????

**Comment by andresgalante** [comment]
We did some updated to the account list on the latest release. Would you mind trying out installing `3.1` please?

**Comment by anthonyfiore** [comment]
Do you have a link and I will try it tomorrow morning thank you so much

**Comment by andresgalante** [comment]
Sure: https://www.hiro.so/wallet/install-web

**Comment by anthonyfiore** [comment]
I am still having the same problem. I cannot get into any of the 280 plus BTC domain names which are under individual distinct accounts. It just continues to spool no matter which domain name I choose. 
My phone number is 267 858-8759 should someone wish to discuss this issue. I am located in South Philadelphia but I am willing to travel should that be necessary to resolve this issue.

**Comment by andresgalante** [comment]
@timstackblock or @Eshwari007 can we reproduce this issue in the test wallet?

**Comment by fbwoolf** [comment]
> @timstackblock or @Eshwari007 can we reproduce this issue in the test wallet?

Our next release will add back @kyranjamie's work on the virtualized account list ...might fix this?

**Comment by anthonyfiore** [comment]
Thank you so much for all your help!!!!

**Comment by Eshwari007** [comment]
> > @timstackblock or @Eshwari007 can we reproduce this issue in the test wallet?
> 
> Our next release will add back @kyranjamie's work on the virtualized account list ...might fix this?



> Thank you so much for all your help!!!!
> […](#)
> Sent from my iPhone
> On Feb 9, 2022, at 8:50 PM, Fara Woolf ***@***.***> wrote: ﻿ @timstackblock or @Eshwari007 can we reproduce this issue in the test wallet? Our next release will add back @kyranjamie's work on the virtualized account list ...might fix this? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Do keep us posted upon the next release if the fix helped solving your issue.Thx

**Comment by anthonyfiore** [comment]
When will the next release be available???

**Comment by Eshwari007** [comment]
Tested the issue on v3.3.0 
Seems to be resolved.

@anthonyfiore Do kindly keep us posted if the issue has resolved your problem upon release.

**Comment by anthonyfiore** [comment]
Can you please send me the link to version 3.3 and I will check it out tomorrow or Friday Edit

**Comment by Eshwari007** [comment]
> Can you please send me the link to version 3.3 and I will check it out tomorrow or Friday Edit
> […](#)
> Sent from my iPhone
> On Mar 16, 2022, at 5:32 PM, Eshwari007 ***@***.***> wrote: ﻿ Tested the issue on v3.3.0 Seems to be resolved. @anthonyfiore Do kindly keep us posted if the issue has resolved your problem upon release. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

@anthonyfiore Here is the link : https://www.hiro.so/wallet/install-web

**Comment by anthonyfiore** [comment]
Still has not resolve my problem. It continues to spool.

**Comment by Eshwari007** [comment]
@anthonyfiore If my understanding is correct, all of you 250 accounts has bns names attached to it, am I correct?
I have abt 200 over accounts in one secret key but handful of the accounts attached to bns(not all).Am trying to mimic your exact scenario hence asking so to be precise.

**Comment by anthonyfiore** [comment]
About 285.

**Comment by anthonyfiore** [comment]
I feel like the screen share I would be more than willing to do so.

**Comment by Eshwari007** [comment]
> I feel like the screen share I would be more than willing to do so.
> […](#)
> Sent from my iPhone
> On Mar 22, 2022, at 3:43 PM, Anthony Fiore ***@***.***> wrote: ﻿About 285. Sent from my iPhone >> On Mar 22, 2022, at 3:39 PM, Eshwari007 ***@***.***> wrote: >> > ﻿ > @anthonyfiore If my understanding is correct, all of you 250 accounts has bns names attached to it, am I correct? > I have abt 200 over accounts in one secret key but handful of the accounts attached to bns(not all).Am trying to mimic your exact scenario hence asking so to be precise. > > — > Reply to this email directly, view it on GitHub, or unsubscribe. > You are receiving this because you were mentioned.

Ys, that would be ideal.Can we set up some time tomm to go thru the exact scenario
Will loop in @sjwhitely as well 
cc @timstackblock @markmhx @andresgalante

**Comment by anthonyfiore** [comment]
OK I will text you soon as I get in my office

**Comment by sjwhitely** [comment]
> Ys, that would be ideal.Can we set up some time tomm to go thru the exact scenario

Yep - absolutely. Are you @anthonyfiore free after 1pm today? If so, drop your email and I'll send an invite over so we can triage live!

**Comment by anthonyfiore** [comment]
I just sent the video to the hirosystems email

**Comment by sjwhitely** [comment]
@anthonyfiore I think that's an old email - please send to support@hiro.so

**Comment by anthonyfiore** [comment]
﻿



Sent from my iPhone

**Comment by sjwhitely** [comment]
@Eshwari007 I have screenshare - I'll send directly to you.

**Comment by Eshwari007** [comment]
@anthonyfiore The issue was tested on a test account which has more than 290 accounts but only abt 10-20 BNS names attached to the accounts.I am curious if to see what error is thrown in developer tools>console when the spooling occurs when you are trying to change the accounts.

Can you kindly take a screenshot of the error so that the developers can get a better understanding of the internal issue.
You can do so by if in Chrome:
I will attaching a screen recording for your perusal in order to grab the errors in console log

https://user-images.githubusercontent.com/38872890/160690275-b86ffb94-5423-4908-843a-81e94ca12ac9.mov

Let me know if you are using a different browser and I will attach the steps to grab the console error logs accordingly.

**Comment by anthonyfiore** [comment]
They are all in separate accounts.

**Comment by markmhendrickson** [comment]
@anthonyfiore Are you still experiencing the same issue as reported a year ago ("The web wallet continues to spool in a circle without opening the respective account")?

**Comment by anthonyfiore** [comment]
Thank you for asking!! I haven’t really looked at them for quite some time but the last time I checked everything was fine. I will let you know if I experience any problems in the future.
Thx again!!
