### ISSUE TITLE
Speed up loading of fee estimates for transaction signing

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2008]
Testing the release:v2.22.0
Notice similar issue in prior 2 releases before this as well and this is both on Chrome and FF
User notices that the fee estimate dialogue box takes few additional seconds to be populated while the Preview button seems enabled.
We may need to improvise the performance of the fee estimate pop up which will aid user interface

https://user-images.githubusercontent.com/38872890/143891636-3ae77e0d-a10b-42f5-881e-bfe81555b9ff.mov

**Comment by markmhendrickson** [comment]
@Eshwari007 Mind retesting this to see if it's still an issue?

**Comment by Eshwari007** [comment]
@markmhx The issue mentioned above is no longer reproducible. Will close the ticket.
