### ISSUE TITLE
Fee estimation not loading on custom regtest

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2010]
On ALEX a custom regtest/testnet is used. Currently no transactions can be confirmed because the fee is not prefilled/loaded it just halts at the loading screen. 
What could be causing this? Should this be resolved by Hiro or is there something at ALEX that can be done?

![image](https://user-images.githubusercontent.com/33360391/143928243-c4c528b3-c064-4bd3-b1e3-fef622468cf6.png)

**Comment by andresgalante** [comment]
What version of the wallet are you using?

**Comment by 314159265359879** [comment]
I was certain I was on wallet 2.22.0 however when I try the same transaction again, now, I do get fee estimations to load. 

Perhaps I was on 2.21.x after all.
I will double check with the other users reporting this on the ALEX testnet and report back here, when I learn more.

**Comment by andresgalante** [comment]
Thanks for looking into it 🙇 

Please close the issue if it's fixed on the lastest version of the wallet

**Comment by 314159265359879** [comment]
Okay on the second swap I try to make I do get the error again with the 2.22.0 wallet version
![image](https://user-images.githubusercontent.com/33360391/144051293-0f546e17-2105-4302-bf47-2e1ebadcc1f4.png)

**Comment by 314159265359879** [comment]
The other users on ALEX testnet are also still getting this error with the latest version.

**Comment by andresgalante** [comment]
Regtest has been decommissioned. We have an open issue to remove it from the selection list https://github.com/hirosystems/stacks-wallet-web/issues/1763

Are you using regtest or testnet?

**Comment by 314159265359879** [comment]
> Regtest has been decommissioned. We have an open issue to remove it from the selection list #1763
> 
> Are you using regtest or testnet?

ALEX uses a custom testnet (it is a lot like the old regtest with fast block times) All the testers add the network manually, like this:

![image](https://user-images.githubusercontent.com/33360391/144116029-75acf19a-5317-4bc1-bfd2-e75e6383727b.png)

That is why I am not sure if there is a fix ALEX can implement or it is something that can only be fixed in the web wallet itself.

**Comment by markmhendrickson** [comment]
Could this be the underlying problem on the API-side? https://github.com/hirosystems/stacks-blockchain-api/issues/865

**Comment by fiftyeightandeight** [comment]
We've upgraded our mocknet to `stacks-blockchain-api v0.71.2 (master:01cd4a1)`, which supports the APIs called by the latest Hiro wallet to estimate the cost.
So this can close. Thank you.
