### ISSUE TITLE
Broadcast error:Transaction rejected on Mainnet

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2011]
Testing v2.22.0
In Chrome

I was trying to deploy a contract from Sandbox for the following use case:
When user selects Custom and inputs 0.000772 on Testnet ,the tx was submitted successfully despite fee is low is thrown however similar error was throw in Mainnet but thc tx failed as Broadcast error was thrown
<img width="440" alt="Screen Shot 2021-11-29 at 3 24 53 PM" src="https://user-images.githubusercontent.com/38872890/143948706-c97697aa-46c4-42c3-891c-f8b611921c34.png">
<img width="877" alt="Screen Shot 2021-11-29 at 3 26 18 PM" src="https://user-images.githubusercontent.com/38872890/143948746-c56bd35a-777d-4d00-ad8f-37adebfca6c3.png">
The first image from Mainnet and second from Testnet

Logging the issue for investigation.

**Comment by markmhendrickson** [comment]
This seems to be expected behavior in that the "fee lower than suggested" warning is just that: a warning. And as such, we should allow the user to proceed to broadcast, even if the chances are low that the transaction will get confirmed.
