### ISSUE TITLE
Values of 'Low' suggested fees mismatched between WW and Explorer (Testnet)

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2012]
Testing :v2.22.0
User was testing contracts via Sandbox
User noticed that the default fee or 0.454945,0.75 and 2 STX for the values for contracts not recognized as our release with lower fee suggestion caps (thinking of 0.5, 0.75, and 2 STX for low, standard and high
This is in Testnet.

On Mainnet,it seems to be reflected as per the suggested values
<img width="451" alt="Screen Shot 2021-11-29 at 3 24 01 PM" src="https://user-images.githubusercontent.com/38872890/143949614-70506f42-6109-4696-bd93-dde3fd3319ad.png">
However in the explorer,its hown as 0.5 STX
<img width="877" alt="Screen Shot 2021-11-29 at 3 26 18 PM" src="https://user-images.githubusercontent.com/38872890/143949669-0d6e99ee-d562-4109-9d9b-e0a6326c5a60.png">

cc @fbwoolf

**Comment by andresgalante** [comment]
I am confused. The wallet shows a fee of `0.454945` but the explorer shows `0.5` for the same transaction?

**Comment by Eshwari007** [comment]
> I am confused. The wallet shows a fee of `0.454945` but the explorer shows `0.5` for the same transaction?

Yes,thats the issue.Diff numerical fee value between WW and Explorer when user selects 'Low' selection from fee estimate

**Comment by andresgalante** [comment]
Could you determine which one is the correct one? meaning is it a wallet or explorer bug?

**Comment by Eshwari007** [comment]
The fix that we have which came from Product suggestion caps ( 0.5, 0.75, and 2 STX for low, standard and high)
Hence 0.5 is correct one,this works fine in Mainnet,the issue seems to be on Testnet only.
Explorer is accurate but WW seems to display a wrong value for the low fee.

**Comment by fbwoolf** [comment]
I just went through the repro steps on this with a contract deploy and the explorer showed the lower value `0.425105 STX`, NOT 0.5.
https://explorer.stacks.co/txid/0xd68dbee8bf3519118e956c5eab87335918ea2a48f12e9347dc4b11cab264db8c?chain=testnet

I am wondering if you can try this again @Eshwari007. I just don't see in the code where this would happen so I'm wondering if it was a mix up just with opening the wrong transaction or something?

**Comment by Eshwari007** [comment]
@fbwoolf Retesting the use case but quick question,why is the low fee is showing different values opposed to suggested low of 0.5 STX,as I see in all of the contracts in sandbox,the standard and high is always 0.75 and 2 .But just the low fee has been up and down.
<img width="435" alt="Screen Shot 2021-11-30 at 4 42 13 PM" src="https://user-images.githubusercontent.com/38872890/144132880-e95474ab-af60-4d39-9755-9fed073661c5.png">
This is the value I see now for low fee in contract deploy via Sandbox.Wanted to get your thoughts in it
The explorer indicated same value as WW in this one:https://explorer.stacks.co/txid/0xc99f5be872a7f99ec5fc644d600ecec545a848f1e187c3520148ddae7f636759?chain=testnet

**Comment by Eshwari007** [comment]
Deployed another contract and low fee now is back to 0.5 STX,believe if the contract is not recognized,the defaults fees will be 0.5,0.75 and 2 as per Mark's input.I deployed another contract and now I am seeing 0.5 STX back as the suggested low fee
<img width="751" alt="Screen Shot 2021-11-30 at 4 45 52 PM" src="https://user-images.githubusercontent.com/38872890/144133220-c41a8eda-f754-4235-873c-1f59696c2244.png">

**Comment by Eshwari007** [comment]
The WW fee value seems to match with Explorer Fee value now.Am sure I saw this couple times bfr creating a ticket.Will monitor the fees going fwd but we can close the ticket as of now.Just wondering if  its an intermittent bugs just as how the fees fluctuates in suggested cap of 0.5 to 0.3xxxxx or 0.4xxxxx

**Comment by fbwoolf** [comment]
@Eshwari007 the code checks each value separately and caps it accordingly, so if the low value is below 0.5 it will be that but if it is above 0.5 you will see 0.5, does that makes sense. It is the same for the others.

**Comment by Eshwari007** [comment]
Values for` Standard` and `High ` have not changed or at least I have not seen prior hence my question on the values which changes for `Low`
Thanks and will close the ticket
