### ISSUE TITLE
Allow STX transfer to a domain name

### ISSUE THREAD

**Issue by pors** [blockstack/blockstack-app#2013]
<img width="374" alt="Screenshot 2021-11-30 at 11 37 22" src="https://user-images.githubusercontent.com/1078320/144022501-49f862e0-dcaa-4217-bd8d-29a66f1dbbfb.png">

Feature request: allow STX transfer to a .btc address. I'm a noob in the Stacks space, and as such it seems like a simple thing using a lookup call first https://hirosystems.github.io/stacks-blockchain-api/#operation/get_name_info. Or am I missing something?

Motivational tweet: https://twitter.com/APompliano/status/1465478030504210441:
> The faster we move away from random strings of letters and numbers as the default for wallet addresses, the faster we will reach true mass adoption.

**Comment by markmhendrickson** [comment]
Thanks for the submission! We're tracking this here already so let's move discussion there: https://github.com/hirosystems/stacks-wallet-web/issues/1840

cc @larrysalibra
