### ISSUE TITLE
Refactor: sign up flow to support wallets with no key

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2026]
This task involves going through the sign up flow, and ensuring the wallet works with only the values that can be taken from a Ledger device (publicKey).

Other differences include generating ahead-of-time a handful of different accounts. Unlike the current flow, where addresses can be generated at will, this can only be done while the device is connected.

- [x] #2038
- [x] #2055

**Comment by markmhendrickson** [comment]
Let's break this down since it's 1+ week dev?

**Comment by andresgalante** [comment]
@timstackblock I'll move this one to Close, please move it back if it isn't done
