### ISSUE TITLE
'BUY' option for accounts with positive STX balances 

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2032]
Fiat onramp feature:
It would be nice to have a 'Buy' option for current existing user/account that has positive STX value on the account
Currently we only have this option for an account with 0 STX Or for a new account only.

**Comment by andresgalante** [comment]
@beguene Would you be able to include this for all accounts before the release, please?

**Comment by beguene** [comment]
@andresgalante @Eshwari007 This is fixed in the same PR https://github.com/hirosystems/stacks-wallet-web/pull/1981
