### ISSUE TITLE
Trigger analytics event when assets received

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2034]
The event should be fired whenever an asset of any type is detected as received.

- Name: `receive_asset`
- Properties:
  - `type`: `stx`, `ft` or `nft` (required string)
  - `contract`: (optional string if type `ft` or `nft`)
  - `amount`: (required number) (`1` if type `nft`)

In the circumstance in which the asset was received since last open, the event should be fired upon subsequent open.

This will help us understand the efficacy of fiat onramp work in particular.

**Comment by beguene** [comment]
I spent some time with this, and the solution is complex and not reliable. I think we should do this analytics on the backend side like the solution I suggested before,  it will be reliable and simpler.
cc: @andresgalante

**Comment by markmhendrickson** [comment]
@beguene could you elaborate on the complexity to this solution? 

How would the backend solution work (and how would we ensure that the same anonymous user ID is used to trigger the event there as used on the frontend)?

**Comment by markmhendrickson** [comment]
I'm closing in favor of https://github.com/hirosystems/stacks-wallet-web/issues/2232
