### ISSUE TITLE
Trigger analytics events for fiat onramp activity

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2035]
- `view_buy_options`: When user selects "Buy" button from home screen
- `select_buy_option`: When user selects provider option and is sent to 3rd party site (with property `provider` containing name e.g. `transak`)

**Comment by kyranjamie** [comment]
Is there a difference between `view_buy_options` and a page view of going to the buy page?

**Comment by markmhendrickson** [comment]
I assumed we don't have page views in place already given the general routing issues, but if this standard transition does get tracked already, there's no need for this separate event.

**Comment by Eshwari007** [comment]
@beguene Only view buy is visible in sentry, view_buy_option,
<img width="1181" alt="Screen Shot 2022-01-24 at 12 38 18 PM" src="https://user-images.githubusercontent.com/38872890/150835484-c78325c6-4a22-4f92-9a0d-9fc04a3b8e3e.png">
 and select_buy_option is not visible on sentry

**Comment by Eshwari007** [comment]
@beguene Not sure if the naming convention has changed.

**Comment by beguene** [comment]
@Eshwari007 The view /buy is triggered after you click on the "Buy" button in the home page.
The view_buy_option is triggered when you click on one of the provider (transak for example). Have you tried that ?

**Comment by Eshwari007** [comment]
> @Eshwari007 The view /buy is triggered after you click on the "Buy" button in the home page. The view_buy_option is triggered when you click on one of the provider (transak for example). Have you tried that ?

Yes,I did try buying via transak though did not find okcoin in this PR but I did not get view_buy_option when I select Transak.
cc @beguene

**Comment by beguene** [comment]
Did you get the 'view_buy_option' in Segment after you clicked on Transak ?

**Comment by Eshwari007** [comment]
> Did you get the 'view_buy_option' in Segment after you clicked on Transak ?

No, @beguene .My last event was as below attached though I am on Transak page:
<img width="1181" alt="Screen Shot 2022-01-25 at 10 36 14 AM" src="https://user-images.githubusercontent.com/38872890/151008240-b9750e92-3b53-4723-a42d-6ddae4932780.png">

**Comment by beguene** [comment]
@Eshwari007 My bad, the event is just 'view /buy', we don't need 'view_buy_options'

**Comment by Eshwari007** [comment]
Thanks for checking my findings @beguene 
Moving the ticket to test done
