### ISSUE TITLE
Link to explorer should be provided for tx via Transak

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2040]
Actual scenario :
User is able to purchase STX (outside USA) via Transak both by credit card and also bank transfer
However user receives order status without a link to the explorer of the tx id.
This can be cumbersome for users as they would want to view a link which will aid them direct access to explorer via the order status dialogue box

Suggestion
either the user's mainnet add should be made as a link to explorer or the tx id.Depending on the preferences from PM's input

**Comment by andresgalante** [comment]
Is this a change on Transak's UI?

**Comment by andresgalante** [comment]
I'll close this issue since it's out of our scope
