### ISSUE TITLE
Add metrics to understand the  incidence rate of low, standard, and high fees

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#2041]

**Comment by Eshwari007** [comment]
@beguene To understand the metric accurately,despite selecting low,standard, high and custom received the same metric:

<img width="449" alt="Screen Shot 2021-12-08 at 6 03 40 PM" src="https://user-images.githubusercontent.com/38872890/145305217-e204d809-f81a-4837-a282-d65674deb88a.png">

Is this accurate?
analytics.track('use_fee_estimation_default_simulated', {
  estimations: [
    {
      fee: 224,
      fee_rate: 37.39330897956175
    },
    {
      fee: 1671,
      fee_rate: 278.65419292979175
    },
    {
      fee: 72159,
      fee_rate: 12026.585281780368
    }
  ],
  maxValues: [
    {
      fee: 224,
      fee_rate: 37.39330897956175
    },
    {
      fee: 1671,
      fee_rate: 278.65419292979175
    },
    {
      fee: 72159,
      fee_rate: 12026.585281780368
    }
  ],
  network: 'testnet',
  route: '/send',
  usingDefaultHiroApi: true,
  version: '2.23.1.672'
});

Noticed that the fees were 
<img width="335" alt="Screen Shot 2021-12-08 at 6 11 01 PM" src="https://user-images.githubusercontent.com/38872890/145305912-2e9ce338-974a-421e-b338-e51108180205.png">
 but its listed as   {
      fee: 72159,
      fee_rate: 12026.585281780368
    } 

in the segment without decimal,is this the way we want the display of the fees in segment?
Also believe we are not adding the metrics for custom hence will leave the criteria out

**Comment by Eshwari007** [comment]
If the above findings are accurate,we can move the ticket to merge.Thx

**Comment by beguene** [comment]
@Eshwari007 My bad, I changed the key name, can you please check again ?
The fee is in micro STX, this is what we use throughout (in our UX code, api, blockchain and documentation) and matches the fee_rate which is also in based on micro STX. I would prefer to stay consistent so we can communicate with the same units if there is an issue.
But if we really need it I can change it.

**Comment by andresgalante** [comment]
+1 for consistency!

**Comment by Eshwari007** [comment]
@beguene the key name is reflecting to the changes
<img width="299" alt="Screen Shot 2021-12-09 at 9 51 29 AM" src="https://user-images.githubusercontent.com/38872890/145418843-8959a401-64c9-4228-88d3-07fea78680d1.png">

I also cross checked the values are acccurate as being displayed within the ww and segment using the micro STX system.
Will move the ticket to Merge as testing completed
