### ISSUE TITLE
List of Transak integration known issues

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2042]
**Issue one**: Manual calculation of user input monetary values / value of per STX is not accurate as its missing few additional STX.
Suspected reason is that there is another network/exchange fee which disrupts the calculation

**Issue two**: Only GBP and EURO has bank transfer option as if user selects other international currency only credit card option is displayed

**Issue three**: The Max limit for credit card purchase  is around ~650 STX but if user selects bank transfers which is only available via  EURO and GBP currency selection,user can purchase up to max ~6200 STX

**Issue four**: Enhancement ticket for a link to explorer : #2040

**Issue five**: User will receive two validation error when user is inputting monetary value in " You Pay" input box,the first for a minimum buy and second for minimum buy in the selected currency value
Actual reason: There is 2 minimums,1 fiat minimum 15 GBP (if GBP is selected in currency exchange) and then 1 crypto minimum depending on Transak liquidity source( in this case the suggested 50 GDP)

**Issue six** : Need a 'Back' button from global transak page back to web wallet : #2048 

**Issue seven**: Removal of USD fiat currency which is defaulting to ETH for US based users : #2052 

cc @markmhx @andresgalante @beguene @timstackblock

**Comment by markmhendrickson** [comment]
I'm closing out in favor of reporting service-provider problems directly to the corresponding provider instead of tracking in our repo.
