### ISSUE TITLE
Need a back button to navigate from Transak back to Web Wallet

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2048]
User was testing the Transak integration when realized that there is no back button to go back if accidentally selected the Buy button from Web wallet.
We may need to have a back button to WW if user wants to return to WW rather than reselecting the wallet from the extension

https://user-images.githubusercontent.com/38872890/145055057-1a18d13a-5156-48c6-8fb2-80ec9151a8b9.mov

cc @eugeniadigon

**Comment by andresgalante** [comment]
I don't think this is a valid concern, but we can include it in https://github.com/hirosystems/stacks-wallet-web/issues/2042

**Comment by Eshwari007** [comment]
Brought the topic to @eugeniadigon and end results was to create an enhancement ticket for the issue.Thank you for linking it into #2042

**Comment by andresgalante** [comment]
this is out of our scope, I'll close this issue
