### ISSUE TITLE
Stop users from accessing buy button while on TESTNET

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#2049]
Users can attempt to send STX to a testnet address with Transak we should put a warning message up to let users know they are on testnet if they attempt to hit the buy button.

<img width="1093" alt="Screen Shot 2021-12-07 at 11 14 56 AM" src="https://user-images.githubusercontent.com/49165468/145068752-19306b58-19ac-4d8d-b504-79376cd3e81c.png">

**Comment by Eshwari007** [comment]
Buy option is not available on Testnet.Notice a small milisec delayness in Send button activate on Testnet but it was only the first time upon extension download.
Moving the ticket to merge and will create an issue on 'Send' button delay upon reproducing it

cc @beguene @fbwoolf
