### ISSUE TITLE
'Increase fee 'default value is inaccurate

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2050]
Testing :v2.23.1, similar results both on testnet and mainnet
Notice that when user tries to increase fee of a tx ,be it STX or etc token,the default value is shown as 0
<img width="434" alt="Screen Shot 2021-12-07 at 11 39 48 AM" src="https://user-images.githubusercontent.com/38872890/145070062-a6ff1fb8-d541-43d9-8330-05c3b1108b7c.png">

However when user selects '1x',user is able to view the fee value which was used for the tx bfr selecting '2x' or etc options
<img width="383" alt="after 1x" src="https://user-images.githubusercontent.com/38872890/145070783-b1794d10-d476-4698-9cee-8b7edad95ab9.png">

**Comment by fbwoolf** [comment]
Ok, this was minor. It was added after fee estimations to use `0` if there was no fee but it was just slow so the fee was showing up after the `0` was already used. Will put up a PR for the fix.

**Comment by fbwoolf** [comment]
@Eshwari007 I merged this into dev. When you test dev before our release this week, can you just make sure this is fixed for you and close the issue?

**Comment by Eshwari007** [comment]
The issue has been tested and verified in v2.24.0-beta.1

**Comment by fbwoolf** [comment]
Great, I am going to close the issue. Thx for testing it!
