### ISSUE TITLE
Change the copy of the onramp to Transak to read "Non-US residents" instead of "international"

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#2051]
<img width="325" alt="Screen Shot 2021-12-07 at 15 34 31" src="https://user-images.githubusercontent.com/1832037/145087284-f20a6f41-abe9-492b-a15c-320d7707b4b8.png">

**Comment by kyranjamie** [comment]
Many exchanges require users to explicitly agree they're not even US _citizens_, even if they're resident elsewhere.

**Comment by andresgalante** [comment]
Let's change it to:

> Non-US residents can purchase STX with a credit card, debit card, or bank deposit via Transak.
