### ISSUE TITLE
Remove USD as fiat option from Transak

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#2052]
USD is not accepted to buy STX from Transak. When a user tries to do it they get ETH as a crypto option.

This is something we can disable on an integration level, via query parameters and the Transak team can provide guidance if there is no documentation.

![unknown-4](https://user-images.githubusercontent.com/1832037/145108623-44a22aee-382f-4f89-a0fc-da325d57d3fc.png)

**Comment by Eshwari007** [comment]
Seems like its visible for users using from USA only

**Comment by beguene** [comment]
@andresgalante there is only this option [fiatCurrency](https://www.notion.so/Query-Parameters-9ec523df3b874ec58cef4fa3a906f238) but it can have only one fiat currency (ex: EUR). So all the other fiat currencies will be disabled which is not great I think.

**Comment by andresgalante** [comment]
This isn't something we can do from the wallet. I'll close this issue and we can think of a different solution if this became a common problem for users
