### ISSUE TITLE
Design inconsistencies with Buy screen

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-app#2058]
Hi all -- just noticed the new funding screen and saw it seemed to be misaligned. 

<img width="407" alt="Screen Shot 2021-12-08 at 3 44 21 PM" src="https://user-images.githubusercontent.com/11803153/145289440-2fcb3efb-830e-499e-bbbd-8a3f441fcc9d.png">

**Comment by fbwoolf** [comment]
@beguene were you following designs for this? Is it just left aligned in the popup? I merged in a `getViewMode()` you can use to center align full page if you need it.

**Comment by fbwoolf** [comment]
Nvm, I see the image is the popup so disregard my last comment! Haha

**Comment by beguene** [comment]
@fbwoolf Thanks for checking it anyway ! 👍
