### ISSUE TITLE
Disable tx Confirm button until fees are available

### ISSUE THREAD

**Issue by pors** [blockstack/blockstack-app#2065]
During a smart contract call that transfers some amount I got this message:

<img width="762" alt="Screenshot 2021-12-10 at 10 09 34" src="https://user-images.githubusercontent.com/1078320/145628968-ab8fc966-d2c4-4c64-a429-9e81ee810fd8.png">

The error doesn't make sense as the amount is set by the application, not through user input directly.
Also there is no input field to enter an amount anyway.

This error occurred on the [lnswap.org](https://lnswap.org) application.

I suspect that it can be reproduced as follows: 
- initiate a swap from BTC => STX
- add a STX amount that is above the maximum (enforced by a post-condition)
- follow the steps in the app.

**Comment by fbwoolf** [comment]
Trying to repro this but struggling to get a valid Lightning invoice to work in the app. What Lightning wallet are you using? I'm using Muun to generate an invoice.

**Comment by fbwoolf** [comment]
Ok, got the invoice to take. Photo didn't work but copy/paste did. However, I don't see this error.

**Comment by pors** [comment]
I'm using Muun as well, and yes sometimes it doesn't work perfectly (very much alpha yet).

Did you try to swap to an amount larger than 22.5 STX?

**Comment by fbwoolf** [comment]
I was just trying to swap the 2 STX min.

**Comment by fbwoolf** [comment]
I see the repro steps now say above the max but that doesn't make sense, why would you be able to swap above your max available STX? This seems like an issue with the app, not with our wallet?

**Comment by fbwoolf** [comment]
I just did 30 STX and did NOT see the error.

**Comment by pors** [comment]
Hmm, my theory about the cause is not correct then. I assumed it had to do with the post-condition.

I assume you were not able to complete the 30 STX transaction? Did you try to "claim"?

**Comment by pors** [comment]
> I see the repro steps now say above the max but that doesn't make sense, why would you be able to swap above your max available STX? This seems like an issue with the app, not with our wallet?

I don't think it is an issue with the app. Well, it is in part, because the app should not allow us to enter an amount above the post-condition limit. But since it does, the wallet should not show this error I think?

@pseudozach can you chime in?

**Comment by fbwoolf** [comment]
@pors are your refunds working? Can you educate me a bit on this app? The app told me the swap failed > explorer says the tx was successful > I request refund thru app > refund fails. STX are gone but no BTC in muun wallet. I am out 32 STX at this point.

**Comment by fbwoolf** [comment]
These were the 2 swaps I did but I had no ability to claim them? Now what?

https://explorer.stacks.co/txid/0xd03e40b7990d8f63742b83c1e103d16c2d09bf90023544096a2128953f12ec2b?chain=mainnet

https://explorer.stacks.co/txid/0x8f4133a10bd9efbe79f16f5481cc1d6f82456cbfa8881859af79f23e303faaf2?chain=mainnet

**Comment by pseudozach** [comment]
> ow say above the max but that doesn't make sens

right after our discord conversation I actually pushed a fix to increase post condition so it doesn't cause tx failure.

Main question was about that wallet error how/why it gets there. that's not clear to me.

**Comment by pseudozach** [comment]
> @pors are your refunds working? Can you educate me a bit on this app? The app told me the swap failed > explorer says the tx was successful > I request refund thru app > refund fails. STX are gone but no BTC in muun wallet. I am out 32 STX at this point.

well the swap is trustless and 2-step. You locked the funds which is step-1 and in order to claim the funds from the contract lnswap backend tried to pay your invoice but checking my logs I see it failed `Could not pay invoice of Swap yGdVYm because: no route` so the swap itself failed you need to manually refund your funds from the contract.

Please use the files provided to you to submit a refund transaction via the website after the swap expiry block-height. 
for the lock tx you linked, expiry block-heights are 41166 and 41172 which is already passed so you should be able to refund at https://lnswap.org/refund

**Comment by pors** [comment]
> right after our discord conversation I actually pushed a fix to increase post condition so it doesn't cause tx failure.
> 

Can I still try to reproduce the issue (the error message in the wallet)?
Maybe you can temporarily set the post-condition limit to a low amount?

> Main question was about that wallet error how/why it gets there. that's not clear to me.

Yes indeed. My assumption was that this error was triggered by requesting a higher amount than the post-condition limit. @fbwoolf could not reproduce that, but I'd like to try again.

**Comment by pors** [comment]
> I am out 32 STX at this point.

Did your first transaction also fail? Then maybe something else was going on (unrelated to post-condition).

Anyway, I'll try to test a couple of times more!

**Comment by pors** [comment]
I have it again, this time on a different site/app. So not related to lnswap.org or post-conditions....

I wanted to buy an NFT on https://stxnft.com/, when the wallet popped up there was a grey bar under the "Fees" part of the wallet. When clicking [confirm], I got the "Enter an amount of STX" message again (in place of the grey bar. A second try worked.

Comes from this line in the code: https://github.com/hirosystems/stacks-wallet-web/blob/ef4f0bbfdeb3658c02419b803831ad06501ab22d/src/common/validation/currency-schema.ts#L11

**Comment by fbwoolf** [comment]
@pors yes, that is a validation check we perform on the field. Can you provide screenshots? Not understanding why you would see a grey bar in place of the validation warning? A grey bar should be present as a loading placeholder for the fee row itself. I can't repro this and I haven't heard anyone else reporting this so a bit hard to debug. If it worked on the second try, I'm thinking it is just that you aren't waiting for the fee to load before trying to confirm the transaction?

**Comment by pors** [comment]
@fbwoolf yes could be. I can't reproduce it now, but will try a couple of times more.

**Comment by pors** [comment]
@fbwoolf yes you were right: if I click confirm before the fees are loaded I get this error. Probably best to disable the confirm button till the fees are loaded.

**Comment by fbwoolf** [comment]
> @fbwoolf yes you were right: if I click confirm before the fees are loaded I get this error. Probably best to disable the confirm button till the fees are loaded.

Ok, good to know, thanks for the feedback. It definitely seems like it should be disabled 👍 . I will change the name of this issue so it can be addressed. Thanks again for helping me debug this!

**Comment by markmhendrickson** [comment]
@fbwoolf mind adding a label here with the t-shirt estimate?

**Comment by fbwoolf** [comment]
> @fbwoolf mind adding a label here with the t-shirt estimate?

Yep, let me confirm this is even still an issue today.

**Comment by fbwoolf** [comment]
I don't see this as an issue. The button to confirm the tx is disabled for me until the fees are loaded. I am going to close this issue. @pors please reopen if you still experience this as an issue for you.

**Comment by pors** [comment]
@fbwoolf I don't have permission to reopen it, but I can still reproduce the problem:
- start making a transaction
- wallet pops up
- scroll down fast and click the [Confirm] button while the fee box is still loading
- result:

![Screenshot 2022-04-27 at 18 20 09](https://user-images.githubusercontent.com/1078320/165553477-b7d7ce61-6f76-4800-928d-61444dc5ae03.png)

The button was not disabled for me.

Wallet version v3.7.1

**Comment by fbwoolf** [comment]
> @fbwoolf I don't have permission to reopen it, but I can still reproduce the problem:
> 
Ok, np, I will reopen. My network must be too fast. I even throttled it in Chrome console to simulate a slower load time. Sorry I closed it!

**Comment by Eshwari007** [comment]
Test passed. The fee loads up quickly even before I select the Confirm button hence the issue was not able to be reproduced
