### ISSUE TITLE
Add MoonPay to the fiat onramp providers

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#2068]
MoonPay will have STX available in "early Q1". We can start the integration into their widget any time in preparation for it, so we can ship as soon as they are ready

**Comment by beguene** [comment]
@timstackblock @Eshwari007 This is ready for test.
PR: https://github.com/hirosystems/stacks-wallet-web/pull/2312

**Comment by timstackblock** [comment]
I do not see STX in the asset dropdown

<img width="1200" alt="Screen Shot 2022-03-21 at 9 49 39 AM" src="https://user-images.githubusercontent.com/49165468/159276678-736c5b42-7856-4c2b-aebd-bd205b1f1c90.png">

**Comment by markmhendrickson** [comment]
This needs to wait for Moonpay to release STX support, as well as some final visual integration details by @fbwoolf, before QA.

**Comment by timstackblock** [comment]
ok thanks @markmhx
