### ISSUE TITLE
Add test to verify routes replacing shared "state derived" routes

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2069]

**Comment by fbwoolf** [comment]
@kyranjamie this issue was generated from the list of items here which I believe you created? https://github.com/hirosystems/stacks-wallet-web/issues/1048 ...what are you thinking needs to be tested here?

**Comment by kyranjamie** [comment]
This one was to think of any integration test flows we might want to test, specifically to test those that touch the routes that were previously derived, wallet unlocked state, for example.

Is there any functionality that the routing changes touches, that isn't covered by our current tests?
