### ISSUE TITLE
Add test to enforce unique paths in `RouteUrls`

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2070]

**Comment by fbwoolf** [comment]
@kyranjamie same on this one, can you add more detail here?

**Comment by kyranjamie** [comment]
This is a really small one. It was really confusing that previously, we had different names for the same route path. What stops a developer introducing more duplicate paths? 

We could add a unit test that ensures all the `Object.values` of the enum are unique, failing if not.
