### ISSUE TITLE
Adding a new network using new API url isnt functioning in WW

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2071]
Testing WW version v2.23.2
- User was testing network using new API url on Web wallet
- User notices that despite successfully adding the new network with the API,selecting the new network isnt retained.The network switches to mainnet only even after selecting the new network.
- Attaching video for perusal

https://user-images.githubusercontent.com/38872890/145890866-a2b935fb-dec7-4420-b389-88833fe6f459.mov

**Comment by markmhendrickson** [comment]
@Eshwari007 Mind retesting this to see if it's still an issue?

**Comment by Eshwari007** [comment]
@markmhx The issue mentioned above is no longer reproducible. Will close the ticket.
