### ISSUE TITLE
Adding logo for xBTC to Stacks wallet

### ISSUE THREAD

**Issue by wbnns** [blockstack/blockstack-app#2079]
Hi friends! Wrapped bitcoin (xBTC) is launching this week on Stacks and one last minute item that came up yesterday is how we can get our logo to populate correctly in Stacks wallet?

Here's the contract:

SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin

And here's the logo:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/1130872/146171174-e5346d36-4274-4079-b009-7897a063bd56.png">

![PNG](https://user-images.githubusercontent.com/1130872/146171291-28e51277-73cf-4d8f-b54e-f35d27afc38e.png)

It's also available in [SVG format](https://drive.google.com/file/d/1tTv2ddfxiscZC9Zor5ZhKATRaMB8KNcE/view?usp=sharing) in case that's helpful.

Happy to open a PR, but not exactly sure the correct placement / procedure, so opening this issue. :)

**Comment by wbnns** [comment]
Related: https://github.com/hirosystems/stacks-wallet-web/issues/1800

**Comment by GAD2511** [comment]
About the logo, is it the final one or it is still modifiable?

**Comment by wbnns** [comment]
@GAD2511 

> About the logo, is it the final one or it is still modifiable?

Heya, it's the final one.

**Comment by andresgalante** [comment]
The wallet doesn't show FT images yet. On your side, you can leave this ready for us to show by adding the image as metadata https://github.com/stacksgov/sips/blob/hstove-feat/sip-10-ft/sips/sip-010/sip-010-fungible-token-standard.md#token-uri

If you'd like to help with the implementation of this featue in the wallet we can definitely assist with guidance and reviewing PRs

**Comment by aulneau** [comment]
@wbnns your token metadata needs to be updated, as @andresgalante stated. see what is returned here https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin/ft/metadata

**Comment by wbnns** [comment]
Thanks for the note on this, we will add that metadata. Cheers!

**Comment by Macxim** [comment]
🔥 Thanks @wbnns. Much appreciated. I'll update it on Arkadiko 🤩

**Comment by wbnns** [comment]
@Macxim Ah!! Thanks so much!!!

**Comment by wbnns** [comment]
@aulneau 

> @wbnns your token metadata needs to be updated, as @andresgalante stated. see what is returned here https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin/ft/metadata

Thanks again for mentioning this the other day. This has been updated. 👍

**Comment by markmhendrickson** [comment]
We'll tackle this with https://github.com/hirosystems/stacks-wallet-web/issues/1800
