### ISSUE TITLE
Fee estimation: low option should default to minimum instead of a fixed maximum

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2086]
For example when sending STX the transfer fee needs to be at least 0.000180 STX (180 uSTX). This is the minimum fee for a STX transfer, a lower fee will throw an error: "fee to low".

I think the default max values are a temporary fix (currently 0.5, 0.75 and 2 STX for low, medium and high transaction fees). The wallet seems to default to them when the fee estimates can not be loaded (on time)). I am not sure if this is still considered a temporary fix. 

In any case:
When the "Low" option is selected I think the user should get a reasonable estimate of the lowest possible fee a transaction can be processed at. Perhaps this should not even based on analysis of past "low fees" payed. At current network load the minimum fee looks to be just fine (it is getting my transactions processed within 1 or 2 blocks). Perhaps low can always default to the minimum based on amount of mempool transactions (i.e. when <300) or simply always because it leaves the most room for the user to increase the fee (RBF) when it does not get processed?

**Comment by markmhendrickson** [comment]
I'm closing this out since we've refined fee calculations since this issue was first reported. However, please comment if you're still running into similar problems and I'll reopen.
