### ISSUE TITLE
Create a Bitcoin/Lightning-centric version of the wallet

### ISSUE THREAD

**Issue by pors** [blockstack/blockstack-app#2093]
Create a Bitcoin-centric version of the wallet, so:

- has all functionality of the current wallet
- there is no need to own STX
- use on-chain bitcoin or a lightning transfer to receive
- all other wallet actions use STX under the hood, the user only sees BTC

This allows bitcoin-only owners to buy NFTs, .btc domain names etc. without first buying (or knowing about) STX.

Maybe using the same HD wallet as suggested here (if I understand it right?) https://github.com/hirosystems/stacks-wallet-web/issues/1483 is a good way to implement this.

**Comment by markmhendrickson** [comment]
This also came up when speaking with [Moonray](https://moonray.game/): "In general we’d like to move towards transactions in btc using Lightning, and STX is a true gas token."

**Comment by markmhendrickson** [comment]
@landitus this would be a more advanced enhancement on top of https://github.com/hirosystems/stacks-wallet-web/issues/1483 but worth starting to explore as well

**Comment by markmhendrickson** [comment]
We now have Bitcoin! Lightning is getting explored here most actively: https://github.com/leather-wallet/extension/issues/4558
