### ISSUE TITLE
Update 'Fund Account' (Buy) design and text

### ISSUE THREAD

**Issue by ginny-d** [blockstack/blockstack-app#2107]
Please update the Fund Account screen with the following changes:

- Secondary button style on Buy:
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=1856%3A12455

- Update illustration, text, add component to choose from more than one option, and add legal disclaimer:
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=1856%3A12439

Thank you!

**Comment by fbwoolf** [comment]
This is outdated, so closing the issue.
