### ISSUE TITLE
Fee dropdown must not overlay Confirm button

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2114]
[Reported on Discord](https://discord.com/channels/621759717756370964/745197302255321108/929883203668430888) by user _Francisc_.

A user may miss the select button target, and send the transaction erroneously.

![image](https://user-images.githubusercontent.com/1618764/148738183-da873899-b893-4b0e-9686-9e980b23db15.png)

**Comment by fbwoolf** [comment]
This was reported again by a user in discord as an issue they are encountering. @markmhx @landitus

**Comment by Dulb26** [comment]
![image](https://user-images.githubusercontent.com/21203121/158600587-1e931703-753a-4ada-897b-1ec21cb78651.png)
i'm so scared of pressing the custom button in times when the Fees is calculated very high like this one
A few times i clicked the confirm by mistake (luckely was when fee was low).... 

Would love if the buttons dont overlap! =D

**Comment by aulneau** [comment]
simple solution could be to disable the confirm button when the select menu is open

**Comment by landitus** [comment]
I think we should force the dropdown drawer to open from the top of the Select component so that it doesn't overlap with the Confirm button. Do we have the ability to customize the position of the drawer @fbwoolf @kyranjamie? 

[Here's an example of how Material UI does it](https://codesandbox.io/s/basic-select-material-v5-forked-v8tleq?file=/demo.js). Note that forcing the position will only take effect if there's space above the component. In our case, that should cover most of the use cases, since the Select is very close to the bottom.

**Comment by fbwoolf** [comment]
> I think we should force the dropdown drawer to open from the top of the Select component so that it doesn't overlap with the Confirm button. Do we have the ability to customize the position of the drawer @fbwoolf @kyranjamie?
> 
Yes, we have control over the positioning.

**Comment by landitus** [comment]
Let's try that out!

**Comment by markmhendrickson** [comment]
@Eshwari007 @timstackblock did you happen to see fees as high as 109 STX during your recent fee testing as shown in @Dulb26's [screenshot above](https://github.com/hirosystems/stacks-wallet-web/issues/2114#issuecomment-1069130837)? My expectation is that we should be seeing estimates that extreme anymore. cc @kantai @saralab

**Comment by kantai** [comment]
It would be possible as a high estimate still. However, the new estimates were only enabled on March 15, and I'm not sure when that screenshot was taken.

**Comment by Eshwari007** [comment]
@markmhx I have not seen the exorbitant fees lately as were testing fees past Tuesday as well for a release.
Am looking at the fees at Stacks on-chain as well:https://stacksonchain.com/dashboards/Fees/20 but didn't see the chart going above ~2.07 cc @timstackblock

**Comment by fbwoolf** [comment]
This was merged into dev and can be tested once a new release PR is created.
