### ISSUE TITLE
Low custom fee throws error(s) 

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2116]
PR:v2.24.0-beta.7

User is running a regression on the release version and notices that upon entering low custom fee and selecting Confirm(Deploying contract via Sandbox)

- An error is thrown in the popup box itself in red which vanishes in few seconds.
- Bunch of error is thrown in console logs as well
- Attaching the video for perusal.

https://user-images.githubusercontent.com/38872890/148834578-0fa50351-cfd2-4fd1-9964-8163dd8d07e8.mov

**Comment by markmhendrickson** [comment]
@Eshwari007 Mind retesting to see if it's still a problem?

**Comment by Eshwari007** [comment]
@markmhx The issue mentioned above is no longer reproducible. Will close the ticket.
