### ISSUE TITLE
can not unlock wallet after 2.24 update

### ISSUE THREAD

**Issue by pseudozach** [blockstack/blockstack-app#2124]
Wallet closed automatically after updating and when I try to unlock it, it says `wait a few secconds` and goes back to password entry.
video: https://wormhole.app/ZkOym#Wsl0g7-3uMPBVqTRpekAAg

**Comment by andresgalante** [comment]
Hi @pseudozach, thanks for the report, we are having a hard time reproducing this issue. What OS and browser are you using?

**Comment by pseudozach** [comment]
@andresgalante latest macos, latest chrome. can you put your wallet to some other network? I had 26 additional networks added and a non-existing API was selected before it updated.

**Comment by andresgalante** [comment]
The issue is with the localstorage walletConfig, if it isn't there, it fails.

To reproduce this issue:

1) create new wallet
2) sign in, wall works okay
3) delete walletConfig from localstorage
4) lock the wallet
5) unlock, the bug happens

We'll work on it

**Comment by andresgalante** [comment]
This issue has been resolved by a rollback and we'll add a test scenario to make sure it doesn't happen again

**Comment by andresgalante** [comment]
Sorry, it'll be closed by #2128

**Comment by Eshwari007** [comment]
Test passed in refs/pull/2128/merge.
