### ISSUE TITLE
insufficient balance error while signing a sponsored tx

### ISSUE THREAD

**Issue by pseudozach** [blockstack/blockstack-app#2141]
I have a new feature in lnswap.org where a user can initiate a Bitcoin transfer and the swap operator will lock funds in a contract and then sponsor the claim contract call so the user can receive the funds from the contract in a trustless way.

While testing with a wallet with 0 STX balance I get the below error. Why is this check performed? I just need the wallet to sign the tx and not broadcast it but pass it back to the application which will forward the rawTx to backend via API.

![image](https://user-images.githubusercontent.com/3731591/150000775-81662af6-bb1c-4d4b-82b9-1664e9b4016b.png)

Here's the frontend code where setSignedTx(swapResponse.id, serializedTx) passes the signed tx to sponsoring party.

```
  const txOptions = {
    contractAddress: contractAddress,
    contractName: contractName,
    functionName: 'claimStx',
    functionArgs: functionArgs,
    network: activeNetwork,
    postConditionMode: PostConditionMode.Deny,
    postConditions,
    sponsored: true,
    sponsorSpendingCondition: {},
    onFinish: data => {
      console.log('Stacks sign onFinish:', data);
      const serializedTx = data.stacksTransaction.serialize().toString('hex');
      setSignedTx(swapResponse.id, serializedTx);
    },
    onCancel: data => {
      console.log('Stacks sign onCancel:', data);
    },
```

Note that since this is a mocknet gitpod environment the contract call fee estimation is failing as well so it may or may not be related.

**Comment by fbwoolf** [comment]
I believe this might be related to another issue that we are aware of: https://github.com/hirosystems/stacks-wallet-web/issues/1954

**Comment by fbwoolf** [comment]
It seems like this should be easy enough to fix even if design work is being worked on for #1954. I can move it into our backlog and take a look at it.

**Comment by fbwoolf** [comment]
@kyranjamie working on this, but I don't think we are currently handling sponsored transactions in the app? Have you seen this while refactoring signing transactions?
~~https://github.com/stacks-network/stacks-transactions-js/blob/master/README.md#sponsoring-transactions~~

I don't see that we handle broadcasting a sponsored tx correctly?

**Comment by fbwoolf** [comment]
Updated doc link: https://github.com/hirosystems/stacks.js/tree/master/packages/transactions#sponsoring-transactions

**Comment by fbwoolf** [comment]
Nvm, I tracked this thru our code. I see where this is implemented now.

`if (isSponsored) return { txRaw };` ...and we don't broadcast it.

**Comment by fbwoolf** [comment]
@Eshwari007 this is the issue that needs to be tested. The PR is linked which shows the new button in the test-app you can use to test this.
