### ISSUE TITLE
Add integration test covering case of locked wallet interacting with dApp

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2143]
We've ran into this problem twice. Let's add a test case that:

1. Creates a wallet
2. Locks said wallet
3. Closes wallet tab
3. Opens test-app
4. Connects to it, and validates we land on unlock screen
5. Enters password and validates sign in lands us on _Choose account_ screen

**Comment by timstackblock** [comment]
Done in PR https://github.com/hirosystems/stacks-wallet-web/pull/2163/

**Comment by andresgalante** [comment]
Cool! Thanks @timstackblock . I'll close this issue and move it to Done.
