### ISSUE TITLE
Keep views in sync during wallet lock/unlock

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2146]
After the routing refactor, we need to address keeping the full page and popup views in sync when the wallet is locked and unlocked. It was previously handled with renders, but now we need to use proper messaging via the background script to keep the views in sync.

![image](https://user-images.githubusercontent.com/6493321/150202144-c6acdfef-514b-49ce-a03a-fe076ca12801.png)

**Comment by fbwoolf** [comment]
@Eshwari007 originally reported in #2142

**Comment by Eshwari007** [comment]
Similar behavior but when the popup wallet is unlocked the windows wallet is yet locked despite being refreshed.
Only upon inputting the password, the windows wallet was visible with all the accounts
Perhaps this is the intended behavior but we should ensure for the locking and unlocking process should be consistent amid the popup wallet and windows.

<img width="1348" alt="Screen Shot 2022-01-19 at 2 43 42 PM" src="https://user-images.githubusercontent.com/38872890/150203403-5b4ee63c-3107-4fe6-903c-dbce28f6d3a4.png">
