### ISSUE TITLE
Update 'Back up Secret Key' screen

### ISSUE THREAD

**Issue by ginny-d** [blockstack/blockstack-app#2152]
This screen needs to be updated with new design / illustrations:

https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=80%3A3287
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=80%3A3317

<img width="1352" alt="key" src="https://user-images.githubusercontent.com/78865845/150518732-f8a53c2d-4447-4f4b-93f7-77e89aeedc70.png">
<img width="492" alt="key-1" src="https://user-images.githubusercontent.com/78865845/150518743-e7b00f7c-6e6b-40e4-b064-b1e6f8bcf407.png">

This is just a proposal, but I think it'd be better if we'd give more air/clarity to each word:
<img width="1366" alt="key2" src="https://user-images.githubusercontent.com/78865845/150520461-bc69f636-e603-42a6-9536-e4372e87128b.png">

**Comment by kyranjamie** [comment]
+1 to boxing each word. Much easier to match order when writing down on paper.

**Comment by andresgalante** [comment]
oh this is much better! ❤️

**Comment by Eshwari007** [comment]
@fbwoolf The screen looks awesome, just curious that the  'back up later 'isn't visible on the screen. Attaching the actual implementation vs the Figma draft design below.
<img width="721" alt="Screen Shot 2022-02-01 at 10 03 44 AM" src="https://user-images.githubusercontent.com/38872890/151993783-58c79f86-f350-4096-8ccb-8dadc681b9a5.png">
<img width="361" alt="Screen Shot 2022-02-01 at 10 05 34 AM" src="https://user-images.githubusercontent.com/38872890/151993834-8de80434-fb0b-4a2a-ab65-48392252a9b8.png">

**Comment by fbwoolf** [comment]
@Eshwari007 we have decided to remove that option from the user for now bc the flow for `back it up later` was never completed.
