### ISSUE TITLE
Update Stores banners

### ISSUE THREAD

**Issue by ginny-d** [blockstack/blockstack-app#2153]
Please update the stores' banners with these new images:

<img width="1280" alt="Store Banner 1 1280x800" src="https://user-images.githubusercontent.com/78865845/150535819-42c1a8fb-8721-4a2d-adcf-65d9fc7c6913.png">

<img width="1280" alt="Store Banner 2 1280x800" src="https://user-images.githubusercontent.com/78865845/150535828-b8468a55-459a-47a0-8c2a-6bcf2ee2b785.png">

<img width="1280" alt="Store Banner 3 1280x800" src="https://user-images.githubusercontent.com/78865845/150535832-196da35c-9872-4eac-a461-46ab6074a789.png">

<img width="1280" alt="Store Banner 4 1280x800" src="https://user-images.githubusercontent.com/78865845/150535839-1385cfe5-16f7-43a7-851f-a377dfef404f.png">

**Comment by andresgalante** [comment]
Hi @eugeniadigon 

these images are larger than the max size for the screen shoots. This is what we need:

<img width="259" alt="Screen Shot 2022-01-26 at 09 39 04" src="https://user-images.githubusercontent.com/1832037/151164423-f8c71a20-f686-4df0-8cca-cba8e0b13fed.png">

Can you adjust them please?

**Comment by ginny-d** [comment]
Sorry about that, here they are in the correct size:

![Store Banner 1 1280x800](https://user-images.githubusercontent.com/78865845/151173554-e0a56dec-f56e-453d-a88a-4a46f8b4fd6e.png)
![Store Banner 2 1280x800](https://user-images.githubusercontent.com/78865845/151173578-f8d32bfc-8601-4914-aa7c-3e011582db30.png)
![Store Banner 3 1280x800](https://user-images.githubusercontent.com/78865845/151173582-f6da030c-dfc5-444b-914e-30d79bc4e356.png)
![Store Banner 4 1280x800](https://user-images.githubusercontent.com/78865845/151173584-47d7b694-6012-4226-bc7d-ad8cd2ddf443.png)

Since these are the "screenshots", do you also need all the other sizes? Or are they different sizing options for the same banners?

**Comment by andresgalante** [comment]
I'll upload them as screenshoots. If you'd like to add banners, let me know :)

**Comment by andresgalante** [comment]
Done, Thanks @eugeniadigon
