### ISSUE TITLE
"invalid amount" error message appears for certain assets when user tries a token transfer

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#2154]
On the testnet with the dev version of the wallet the user hits this message and cannot send the token. 

<img width="1312" alt="Screen Shot 2022-01-21 at 10 18 00 AM" src="https://user-images.githubusercontent.com/49165468/150555280-8b5dbf70-1ba7-48de-9fa5-68e82e910458.png">
<img width="379" alt="Screen Shot 2022-01-21 at 9 23 12 AM" src="https://user-images.githubusercontent.com/49165468/150555292-c26006ce-a0ac-4347-8ba4-273bb02f5df9.png">

**Comment by Eshwari007** [comment]
I had similar issue when I was testing non STX token transfer
<img width="398" alt="123" src="https://user-images.githubusercontent.com/38872890/150559191-e35db6e4-9638-4b44-ad15-5e7d664eeb19.png">


seems to work fine with Stella token though
<img width="395" alt="Screen Shot 2022-01-21 at 10 58 28 AM" src="https://user-images.githubusercontent.com/38872890/150558976-7eb0d158-5882-4792-8fd6-851bef654d38.png">

**Comment by kyranjamie** [comment]
I have a feeling this is related to my refactoring work. One area that wasn't entirely clear, based off the existing code, was how we determine "transferable assets".

It could be that RTO is a non-SIP-09 token that shouldn't be transferable, but is now considered as such.

**Comment by He1DAr** [comment]
Some tokens are missing metadata, it looks like they were being filtered out previously.
main:
![image](https://user-images.githubusercontent.com/97111756/150603598-3c9bbc6b-49df-427b-9735-6338f8a9dac9.png)
dev:
![image](https://user-images.githubusercontent.com/97111756/150603635-6c52b914-07f5-4ff6-90e6-26d271a4413a.png)
