### ISSUE TITLE
transactions are not appearing on the activity stream in the dev version of the wallet compared to prod

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#2155]
You can look a the transactions below there seems to be an issue with the refresh and page routing 
@fbwoolf has diagnosed the issue and is looking into it.

<img width="389" alt="Screen Shot 2022-01-20 at 12 20 08 PM" src="https://user-images.githubusercontent.com/49165468/150555690-d7e77f22-4037-42a2-92bd-38e3d6d11e7a.png">
<img width="387" alt="Screen Shot 2022-01-20 at 12 19 07 PM" src="https://user-images.githubusercontent.com/49165468/150555692-379e738a-eb1e-49cd-8264-0f90edd3c88c.png">

**Comment by kyranjamie** [comment]
I tested this this morning and it worked okay. Is the branch's build you're testing from up to date with `dev`?

**Comment by fbwoolf** [comment]
@timstackblock I have been testing this too and am not seeing the issue consistently. There is a forced refresh still when sending/redirecting. I believe at times the api is just slow to refresh the data? The forced refresh may happen too soon. There is a constant used: `const timeForApiToUpdate = 250;` which might need to increase? Using `useRefreshAllAccountData` is not ideal.

**Comment by timstackblock** [comment]
Ok sounds good, it's definitely happening but it isn't consistent. I know you mentioned you saw this as well on a fresh install @fbwoolf. If we can pinpoint the API slowness as the problem then we can close out this issue I just want to make sure we arent introducing anything new into Prod.

**Comment by fbwoolf** [comment]
@kyranjamie do you think we should increase `timeForApiToUpdate` to help when the api is slow or just close this issue?

**Comment by kyranjamie** [comment]
If it works, sure. Generally speaking, using an arbitrary number to try and guess time for the API to update is a bit of a hack. 

Though, with the fix to make sure the submitted transactions appear, is this necessary? This fix isn't on live yet afaik, but on dev it works right?

**Comment by fbwoolf** [comment]
Yeah, I am going to close this issue for now. We can reopen it if people see this happening consistently, but I haven't been running into it.
