### ISSUE TITLE
Change the text for Okcoin description

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2170]
Separating out the issue from parent ticket:https://github.com/hirosystems/stacks-wallet-web/issues/2105
https://github.com/hirosystems/stacks-wallet-web/issues/2105#issuecomment-1006061990

We may need to reword 'US users can purchase STX quickly with USD' under Okcoin to match up to Transak description
<img width="373" alt="okcoin" src="https://user-images.githubusercontent.com/38872890/151226475-838b11ca-4428-4cc6-baec-4ad2b6cbed38.png">

**Comment by andresgalante** [comment]
OKCoin does not support the US market.

@beguene can you please change the text so it's the same to Transak?

**Comment by beguene** [comment]
@andresgalante Sure I will update it today.

**Comment by Eshwari007** [comment]
Test passed .Moving it to Merge
<img width="615" alt="Screen Shot 2022-01-31 at 12 34 07 PM" src="https://user-images.githubusercontent.com/38872890/151843842-cf935076-5656-4c7a-903c-261a416638a4.png">
