### ISSUE TITLE
Max button does not work after encountering error

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#2175]
The max button told me I had insufficient funds even though I had enough to handle the transaction. When I returned to the balance screen and tried to do the transaction again the button is now disabled. Please see the image and video link below and let me know if you have any questions. 

This is with the current prod version of the web wallet on the chrome browser

2 bugs here 

1st the max button throws the insuficient funds message when it shouldn't 
.099935 STX + .000065 STX should allow me to send if I have a balance of 0.1 STX

2nd the button become unclickable when I leave and return to the send screen

VIDEO OF BUG 

https://somup.com/c3VuDOZglM

<img width="373" alt="Screen Shot 2022-01-28 at 10 55 45 AM" src="https://user-images.githubusercontent.com/49165468/151584244-8d2babe7-40de-4871-bef3-7f23644328c1.png">

https://somup.com/c3VuDOZglM

**Comment by andresgalante** [comment]
To replicate the issue:
1. Press max & add legit address
2. Choose low fee
3. Press preview
Bug: fee auto switches to standard

**Comment by kyranjamie** [comment]
Ready to QA, can pull build either from latest beta release (check changelog to make sure this commit is there) or from the PR
