### ISSUE TITLE
Fix selection of "Low" fee estimate instead of seeing "Fee is too low" message

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2176]
User testing stacks-node-api-875-876.stacks.co API via the network
User noticed when users send non stx and stx tokens and select the low custom fee.
Receiving an error that the fee is too low. 
Attaching the screen recording for perusal

https://user-images.githubusercontent.com/38872890/151585636-4ed70820-7c24-46b9-a871-89e80eb983df.mov

<img width="1411" alt="Screen Shot 2022-01-28 at 11 24 04 AM" src="https://user-images.githubusercontent.com/38872890/151585663-88b5fe33-6866-442d-98e4-480c415b0e0a.png">

**Comment by timstackblock** [comment]
<img width="394" alt="Screen Shot 2022-02-22 at 2 14 19 PM" src="https://user-images.githubusercontent.com/49165468/155203780-d6d5e57f-93ac-4497-be7d-8037a399ab54.png">

**Comment by timstackblock** [comment]
Still an issue @markmhx can you pull this into the sprint

VIDEO OF ISSUE  https://screencast-o-matic.com/watch/c3n3qbVbyG4

<img width="452" alt="Screen Shot 2022-02-22 at 2 25 04 PM" src="https://user-images.githubusercontent.com/49165468/155204540-eb7d8550-93f5-4694-a7aa-d342c2ea5dd3.png">

**Comment by Eshwari007** [comment]
Yes, @timstackblock Am finding the same issue when I select the `Standard` and also `Low `fee from the custom fee

https://user-images.githubusercontent.com/38872890/155204840-9d6b149a-9e9c-4aa4-a7b3-1c6d1268faff.mov

The Original issue was found during API testing as well and found the above while testing : https://stacks-node-api-pr-875.mainnet.stacks.co/extended/v1/status

**Comment by andresgalante** [comment]
@markmhx let's make sure to prioritize this issue

**Comment by markmhendrickson** [comment]
The wallet displays "Fee is too low" and fails to broadcast the transaction when the user has selected the "Low" fee suggestion?

**Comment by Eshwari007** [comment]
With PR :2259

Notice the issue was reproducible on mainnet when the user selects "Low" fee but when the user selects Standard it s working fine.
Seems to be intermittent with Standard but at least selecting low produces consistent` Fee is too low` message

**Comment by andresgalante** [comment]
@markmhx I could reproduce this issue in pro, try it out. The error shows before the transaction is executed, therefore there is no broadcast

**Comment by markmhendrickson** [comment]
@Eshwari007 @andresgalante @timstackblock have you seen this recently?

**Comment by Eshwari007** [comment]
> @Eshwari007 @andresgalante @timstackblock have you seen this recently?

@markmhx This issue has been fixed hence have not seen it reproduced lately.
I can close the issue and keep an eye in future (just in case if the bug reappears)
