### ISSUE TITLE
Add ability to remove network

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2177]
<img width="589" alt="Screen Shot 2022-01-28 at 11 40 56 AM" src="https://user-images.githubusercontent.com/38872890/151586614-dcea887f-24dd-4714-a137-6a3b82e06646.png">

User tried to delete the newly added network but noticed the delete(symbol) is missing from all of the network end

**Comment by markmhendrickson** [comment]
I'm changing to an enhancement since this is functionality we haven't added yet.

**Comment by markmhendrickson** [comment]
I'm closing this out as a duplicate of https://github.com/hirosystems/stacks-wallet-web/issues/1716
