### ISSUE TITLE
STX WALLET balance no longer appears on the contract call screen 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#2178]
Balance no longer appears in the top right corner on the contract call screen, it has been removed. 

![issue](https://user-images.githubusercontent.com/49165468/151589230-be84208c-b5d3-4f8f-8c30-31278c8acb28.png)

See the convo for details https://discord.com/channels/621759717756370964/745197302255321108/936662283839496293

**Comment by andresgalante** [comment]
Since the PR is approved, I've added this to QA to get into the next release

**Comment by fbwoolf** [comment]
Ok, I will merge the PR.
