### ISSUE TITLE
Address is for incorrect network WTF?

### ISSUE THREAD

**Issue by memoriess-art** [blockstack/blockstack-app#2179]
![image](https://user-images.githubusercontent.com/79898618/151673738-4697ca09-09ae-44cd-84f2-70bad06f1b0f.png)

**Comment by memoriess-art** [comment]
ADMENNNNNNN

**Comment by memoriess-art** [comment]
HELP

**Comment by fbwoolf** [comment]
The app is on testnet and you are trying to send to a mainnet address. If it start with `SP...` that is mainnet. Testnet addresses start with `ST...`.

**Comment by memoriess-art** [comment]
> The app is on testnet and you are trying to send to a mainnet address. If it start with `SP...` that is mainnet. Testnet addresses start with `ST...`.

And ? what should I do ?

**Comment by memoriess-art** [comment]
> 

where to find the address ST

**Comment by memoriess-art** [comment]
Help withdraw ((((((

**Comment by unclemantis** [comment]
Just switch network to MainNet to send to an address beginning with the letters SP

**Comment by memoriess-art** [comment]
> Just switch network to MainNet to send to an address beginning with the letters SP

MainNet balance 0

**Comment by fbwoolf** [comment]
> > Just switch network to MainNet to send to an address beginning with the letters SP
> 
> MainNet balance 0

This isn't an issue with the web wallet. You are using the desktop wallet which is a different repo. It seems like you need support help? Can you join discord and seek out help in our support channel and/or use our support email? https://discord.gg/p9u9s3D3
