### ISSUE TITLE
v2/fees/transaction  -  "SyntaxError: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by dartman10** [blockstack/blockstack-app#2180]
Trying to deploy contract via Hiro wallet but returns with 400 when fetching fee estimate.   However, the resulting JSON seems incorrect.   

Supposed to get a 'reason', according to  https://github.com/stacks-network/stacks-blockchain/pull/2872

![Screen Shot 2022-01-29 at 3 20 37 PM](https://user-images.githubusercontent.com/34408740/151676510-72ee80ee-4e83-4317-957f-aa9d8446ceba.png)

![Screen Shot 2022-01-29 at 1 17 26 PM](https://user-images.githubusercontent.com/34408740/151676516-73bc5874-8340-48cb-a322-ed3b4c77f32c.png)

Thank you!

**Comment by dartman10** [comment]
Closing for now.  Issue might have been resolved.

**Comment by dartman10** [comment]
See issue https://github.com/hirosystems/stacks-wallet-web/issues/2181

**Comment by unclemantis** [comment]
I am getting a 400 as well
