### ISSUE TITLE
Ledger: Analytics events

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2186]
Ensure events are fired throughout Ledger flows

Consider events such as:
- [x] On user select connect Ledger <-- has url
- [x] On Ledger device connected <-- has url
- [x] On user shown Ledger connection warning page <-- has url
- [x] On public key pulled from Ledger device
- [x] On transaction signed with Ledger

**Comment by kyranjamie** [comment]
I've built the Ledger flow in a way where each step has its own url, so many of these analytics are implicit by page views.

cc/ @markmhx for input on any others events we need to capture

**Comment by markmhendrickson** [comment]
@landitus minding listing out all the new UI interactions that are possible to instrument for event tracking with the Ledger integration then I'll review for naming and property design purposes?

**Comment by landitus** [comment]
Sure thing
