### ISSUE TITLE
Modify 'View your secret key' page to be in sync with new onboarding design

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2202]
<img width="644" alt="Screen Shot 2022-02-01 at 4 37 47 PM" src="https://user-images.githubusercontent.com/38872890/152058732-edb7dbbb-2761-462a-92b3-febb82f2d605.png">
<img width="647" alt="Screen Shot 2022-02-01 at 4 40 13 PM" src="https://user-images.githubusercontent.com/38872890/152058734-c2286c29-c765-4145-867b-ed134322160e.png">

For design consistency,we may need to box the secret key on the "View your secret key" page as hows its being displayed now in the new onboarding design

Input from @fbwoolf :Prob a good idea ...maybe we can just remove the Here's your Secret Key:... text from that page (first image) and just center what is on the right side of the new Back up you Secret Key page (which you are showing in the second image)?

cc @eugeniadigon

**Comment by andresgalante** [comment]
Well spot Esh. I like @fbwoolf's suggestion, if possible we should reuse the exact same component in both pages.

**Comment by ginny-d** [comment]
Here's the screen with the component updated:
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=2593%3A13125

I'm not sure for the text, it is different on the wallet currently vs. on the screenshot

**Comment by Eshwari007** [comment]
Tested the PR, `View your secret key` is matching up to the new account creation 'Secret key' view as on the onboarding steps.
I do have a quick question about the font size though on the full page view of the wallet, felt that the **' Your secret Key'** font size is a little too big but will leave the question to @eugeniadigon 
Since its purely cosmetic and feature functionality is fixed, am moving the issue to as Test is done.
We can always create an enhancement ticket for the font size upon design review.

cc @fbwoolf

**Comment by fbwoolf** [comment]
> I do have a quick question about the font size though on the full page view of the wallet, felt that the **' Your secret Key'** font size is a little too big but will leave the question to @eugeniadigon Since its purely cosmetic and feature functionality is fixed, am moving the issue to as Test is done. We can always create an enhancement ticket for the font size upon design review.
> 
Not sure on this as there is no comp to refer to but the onboarding pages do use the same font size (48px) for the full page title. I do think there are times it reduces to 40px (ex. unlock page), but that is only when the 48px wraps to the next line, which it doesn't in this case. Happy to change it if needed. Thx for the feedback.

**Comment by fbwoolf** [comment]
I did notice just doing a screen cap of this that I missed centering the title , so I'll need to fix that (maybe I can just sneak in the fix with the onboarding homepage changes bc minor). Here is a screenshot for @eugeniadigon ...do you think the title text is too big here?

![Screen Shot 2022-02-04 at 4 46 57 PM](https://user-images.githubusercontent.com/6493321/152613441-c6ebc845-826c-4360-8127-87c68f76ae32.png)

**Comment by ginny-d** [comment]
Usually the _full screen_ screens use farily big titles, so I was trying to follow the same logic. I did decrease this one though because I had the same thought. Let's keep it like that for now. Thank you for checking!
