### ISSUE TITLE
Tooltip on send form has broken styles

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2206]
![image](https://user-images.githubusercontent.com/1618764/152154957-eb728a57-29c0-46e9-9454-0a184d67b23f.png)

**Comment by fbwoolf** [comment]
Did we need all those tippy styles I removed in the global-styles? I'll check ...it appeared they were unused but I'll put them back if needed.

**Comment by kyranjamie** [comment]
That could well be the issue 😂
