### ISSUE TITLE
Unlock a wallet with secret key link allows unlocking of a different secret key

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#2213]
We now give users the ability to unlock the wallet with a secret key as well as their password
but we do not verify they are using the secret key of the currently locked wallet
so basically they can unlock a different wallet while logged into the previous wallet if it becomes locked 

Video of issue: https://screencast-o-matic.com/watch/c3neoMVDBPF

<img width="374" alt="Screen Shot 2022-02-03 at 12 38 10 PM" src="https://user-images.githubusercontent.com/49165468/152397824-c59ba519-3dea-42ec-8898-0a60b792a70d.png">

**Comment by fbwoolf** [comment]
After merging the unlock page redesign, the full page view was added to Figma here: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=3%3A7

As part of this issue, I am going to make sure the design is correct.

**Comment by timstackblock** [comment]
Ok thanks just let me know when i'm clear to retest.
