### ISSUE TITLE
Transaction id wrapped in txId

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-app#2216]
After a contract call, the tx result in onFinish is txid.txid
It is unclear why when this changed, but my app breaks now.

**Comment by fbwoolf** [comment]
I fixed this, so it will be included in our release this coming week.

**Comment by fbwoolf** [comment]
It was fixed in this PR and merged, but not release yet: https://github.com/hirosystems/stacks-wallet-web/pull/2159/files#r791218440

**Comment by friedger** [comment]
Is there a test for that? That this doesn't happen in the future again :-)

**Comment by fbwoolf** [comment]
@timstackblock was a test for this added by chance with your new integration tests? If not, I can make an issue to make sure we add one.

**Comment by timstackblock** [comment]
I do not believe we are specifically looking for txid.txid a test to verify that assertion is still needed.

**Comment by fbwoolf** [comment]
Added issue here: https://github.com/hirosystems/stacks-wallet-web/issues/2222
