### ISSUE TITLE
Wallet becomes irresponsive when scrolling the popup wallet via dragging the scrollbar 

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2217]
Branch:v3.1.0-beta.7

- User is testing using the test account with 185 accounts
- User notices that when the user is scrolling the scrollbar bottom and upwards several times , a square pops up near the extension
- User is then not able to select the extension as it becomes irresponsive
- Attaching the screen recording for perusal

https://user-images.githubusercontent.com/38872890/152815442-4f74d631-f12f-4a10-92cd-cb4ec2ccf263.mov

**Comment by Eshwari007** [comment]
Test passed on Dev- Hiro Wallet Preview
v3.2.0-beta.7

**Comment by andresgalante** [comment]
@Eshwari007 Did the test pass on dev o prod?

**Comment by Eshwari007** [comment]
> @Eshwari007 Did the test pass on dev o prod?

Test passed on Dev. @andresgalante
