### ISSUE TITLE
Chrome Web Store description has duplicated text

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2227]
The [Chrome Web Store description](https://chrome.google.com/webstore/detail/hiro-wallet/ldinpeekobnhjjdofggfgjlcehhmanlj) has duplicated text. This is because the Chrome Webstore combines the app's manifest `description` with the text coming from the Web Store dashboard. Seems the Webstore dashboard text is the more current and the one to keep, as it emphasizes "decentralized apps" vs plain "apps".

<img width="1255" alt="Chrome Web Store2" src="https://user-images.githubusercontent.com/239215/153074151-0a8ad08c-8b39-45fc-b525-9da019b83401.png">

**A proposed fix could be:**
- ~~Update the manifest file with the latest copy: "Hiro Wallet is a safe way to manage your STX, sign into decentralized apps, and protect your funds while interacting with Clarity smart contracts."~~ [Here's a similar issue on how to do that](https://github.com/hirosystems/stacks-wallet-web/pull/1681/files).
- Remove the first paragraph in the Webstore dashboard to avoid duplication.
- Change the first bullet point  in the Webstore dashboard to include "decentralized apps": Authenticate with **decentralized apps** that have integrated the Connect library from Stacks.js

**Comment by andresgalante** [comment]
@landitus do you want to take a stab at fixing this one yourself? (It's totally ok if you aren't comfortable doing it)

**Comment by landitus** [comment]
I'll make a try and let you know how this goes :)

**Comment by landitus** [comment]
Manifest v2 accepts only 132 characters for the description, and updating the text will make it longer. The best solution is to leave the manifest untouched, since it's exactly 132 characters now, and remove the duplicated text in the Chrome Web Store dashboard. I've updated the proposed solution above.

**Comment by andresgalante** [comment]
👍 Thanks @landitus 

I'll close this issue and we can reopen it when we move to manifest v3

**Comment by landitus** [comment]
We've just updated the Chrome Store dashboard and sent it for review. Will wait for it to be published before closing this issue.

**Comment by landitus** [comment]
The change was approved by Google and now looks good! cc/ @markmhx 

<img width="984" alt="Screenshot 2022-02-16 at 14 09 54" src="https://user-images.githubusercontent.com/239215/154271396-4019b476-508e-4df2-bb88-04905ac3c0b1.png">
