### ISSUE TITLE
Showing two scroll bars (even when nothing to scroll) on an Account in Firefox

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2228]
Tested on Windows 10, Firefox (latest) (this issue is not present in Chrome)
Two scroll bars

When there is nothing to scroll through:
![image](https://user-images.githubusercontent.com/33360391/153077617-ca65283e-011d-4d3c-9d48-f8b2178b2281.png)

When there is something to scroll through:
![image](https://user-images.githubusercontent.com/33360391/153077831-cf0c2151-4143-4b76-ba83-bbcdfcf7f056.png)

**Comment by fbwoolf** [comment]
We did change a few things with global styles and scrolling behavior in this release. I don't have a Windows machine to repro this, @kyranjamie do you?

**Comment by kyranjamie** [comment]
@fbwoolf this happens on MacOS firefox too.

**Comment by fbwoolf** [comment]
> @fbwoolf this happens on MacOS firefox too.

I didn't see it on MacOS 🤔 ...not sure why but thanks for fixing!

**Comment by andresgalante** [comment]
@fbwoolf you need to have scroll bars always visible, else they'd be hidden

**Comment by fbwoolf** [comment]
> @fbwoolf you need to have scroll bars always visible, else they'd be hidden

I don't understand what you mean? In FF settings?

**Comment by andresgalante** [comment]
Try this:

1. From the Apple menu, select System Preferences.
2. Click General. Once you click General the following menu will appear.
3. Set the Show Scroll Bars setting to Always.
4. Close System Preferences.

**Comment by kyranjamie** [comment]
> @fbwoolf you need to have scroll bars always visible, else they'd be hidden

@andresgalante I'll run you through the scrollbar changes we've made in our 1:1 tomorrow. You can object if you think they're abhorrent, though imo it works much nicer (and there's a precedent for omitting them)
