### ISSUE TITLE
Clicking on the logo redirects to a blank page

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2236]
During the onboarding, clicking on the Hiro Wallet logo in the header redirects from `chrome-extension://.../index.html#/onboarding` to `chrome-extension://.../index.html#/` which is a blank page, perhaps because the account is not yet authenticated.

https://user-images.githubusercontent.com/239215/153922749-aafd771e-4a25-4201-b535-2264737174d4.mp4

Should clicking on the logo redirect somewhere or we could just remove this interaction? I think it's safe to remove the click interaction in this particular place.

**Comment by fbwoolf** [comment]
Yep, good catch. Either way is easy to fix. It is routing to home but the account gate is returning null I bet. It might be that Kyran's work fixes this bc he made some changes to the account gate. We can check this on his branch but easy just to remove the interaction here if best?

**Comment by landitus** [comment]
Yes, my preference is to remove the click interaction altogether.

**Comment by fbwoolf** [comment]
Great, will do. Thx for the feedback!

**Comment by kyranjamie** [comment]
Remove _during onboarding_ maybe? But it's a pretty common UX pattern that the icon goes to home page. We shouldn't remove it completely, right?

**Comment by landitus** [comment]
It is a common pattern indeed. I wasn’t as clear, I meant removing it from
the initial splash page, shown in the video, that acts a home page for
un-authenticated accounts. So in this single spot, there’s no need to have
a click to home since this is the starting point.

But we can also keep the link if it links to this same page. That is
acceptable as well.

**Comment by timstackblock** [comment]
resolved
