### ISSUE TITLE
Adding a long network name truncates it on the popup wallet

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2248]
User added: the new API url for testing purpose
https://stacks-node-api-pr-875.mainnet.stacks.co/extended/v1/status

User notices that the url is truncated in the popup wallet 
We need to fix the issue with better way to handle long url on the popup wallet
<img width="348" alt="Screen Shot 2022-02-18 at 12 32 30 PM" src="https://user-images.githubusercontent.com/38872890/154733426-64bfe6c7-e789-4eae-b5bb-c4dab7fe42e9.png">

**Comment by pete-watters** [comment]
I'll close this as we have improved it but can make it even better in https://github.com/leather-io/extension/issues/5124 

Current UI:

![Screenshot 2024-06-28 at 11 28 00](https://github.com/leather-io/extension/assets/2938440/b350ab92-c6b0-4b77-8885-11b6297e6191)
