### ISSUE TITLE
Changing Network popup box truncated

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2255]
Users notice that when the dev tool is populated and settings are selected, only the change network popup box is truncated.We may need to size it as how other selections in setting work

https://user-images.githubusercontent.com/38872890/155259860-3f4ba070-3c4f-4c35-a945-5b0254541f37.mov

**Comment by markmhendrickson** [comment]
I'm closing this issue out in favor of the general viewport formatting work pursued here: https://github.com/hirosystems/stacks-wallet-web/issues/2256
