### ISSUE TITLE
Make new UI layout responsive 

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2256]
Tracking this here for us to go through and ensure all layouts are responsive (and we don't want this to slow us down merging the latest changes). The welcome screen & home page, for example, don't resize down when the viewport is narrowed.

We're mostly there, but some adjustments are needed to make them collapse gracefully. As the narrow viewport styles are needed for the popup, the fullscreen mode should adopt these when narrow. @fbwoolf If you'd find it helpful, let's work on this together.

<details>
<summary>Welcome</summary>

![image](https://user-images.githubusercontent.com/1618764/155304608-3676c3e3-f4c8-4023-91a8-c07539429dad.png)

</details>

<details>
<summary>Homepage</summary>

Missing padding/horizontal scroll

![image](https://user-images.githubusercontent.com/1618764/155304779-60ead167-0294-4b7e-8dc7-e8f9edf3abcb.png)

</details>

**Comment by markmhendrickson** [comment]
Does this require any additional design input from @landitus in Figma?

**Comment by kyranjamie** [comment]
I don't think so. Let's have a stab at it, and then have another review.

**Comment by markmhendrickson** [comment]
Note that we also have issues with _short_ viewports as reported here: https://github.com/hirosystems/stacks-wallet-web/issues/2255

**Comment by landitus** [comment]
Interesting! Would we consider going "responsive" to going from the Desktop size as the maximum to the Web wallet size as the minimum? I can take that into account in the design process and reviews as well.

**Comment by kyranjamie** [comment]
The web wallet in popup mode is close enough a smart phones viewport width. Imo we should design/implement the web wallet with the traditional web design approach to responsiveness (mobile first), supporting a wide range of screen widths.

**Comment by landitus** [comment]
Perfect, that sounds good to me! Let me know when you need a review.

**Comment by fbwoolf** [comment]
I can definitely take this on, I just wasn't aware it was a requirement bc it isn't shown in any design as full-page being responsive. We currently don't have any deigns for a md screen size? I noticed we have access to this hook in our UI library that might be helpful: https://chakra-ui.com/docs/hooks/use-media-query

**Comment by landitus** [comment]
~~Alright @fbwoolf, we've settled with option A (short and sweet 🍬 ).~~

EDIT: Moved to https://github.com/hirosystems/stacks-wallet-web/issues/1478

**Comment by fbwoolf** [comment]
I am going to break out finishing up the onboarding steps and home page as-is before the responsive changes into a separate issue.

**Comment by andresgalante** [comment]
@fbwoolf if I can help thinking through how to achieve this task, please let me know.

**Comment by Eshwari007** [comment]
@landitus Quick question: I see in https://github.com/hirosystems/stacks-wallet-web/issues/2249, the popup wallet shown as below:
<img width="500" alt="Screen Shot 2022-03-23 at 10 01 35 PM" src="https://user-images.githubusercontent.com/38872890/159827204-9025ed5c-53e1-4944-b024-7e5ba07ec936.png">

Current view of the UX:
<img width="415" alt="Screen Shot 2022-03-23 at 10 02 39 PM" src="https://user-images.githubusercontent.com/38872890/159827268-16a9a049-3b7a-4ec4-8240-c42c0b6262b7.png">

Should we have a description matching the full window mode to the popup wallet as well?

<img width="900" alt="Screen Shot 2022-03-23 at 10 05 22 PM" src="https://user-images.githubusercontent.com/38872890/159827555-bbadb38f-9511-492f-bbe5-4eaff0a6e25b.png">


The reason I ask if you look at current UX, upon 'Back up secret key ' action is performed, we have a black square with a checkmark on it
<img width="190" alt="Screen Shot 2022-03-23 at 10 06 08 PM" src="https://user-images.githubusercontent.com/38872890/159827876-ad66460d-3ee2-4d18-9258-ee3375afaf75.png">
<img width="975" alt="Screen Shot 2022-03-23 at 10 08 23 PM" src="https://user-images.githubusercontent.com/38872890/159827877-daa5ba3a-efb7-4bb3-8f61-5010ab26f68c.png">

**Comment by fbwoolf** [comment]
@Eshwari007 it was decided that the `Back up secret key` step would be completed during onboarding so the steps would load with that step as `Done` which is shown in the popup as the check mark icon.

**Comment by landitus** [comment]
> Should we have a description matching the full window mode to the popup wallet as well?

For this iteration, we'll ship it as it is. But we can definitely consider adding them as a later enhancement
