### ISSUE TITLE
Hiro wallet version overlaps with viewing "Your secret key"

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2262]
The user notices that Hiro wallet version overlaps with view Your secret key in the full window wallet page
Noticed this in PR : 2259 and also in Prod v3.2.0

<img width="622" alt="Screen Shot 2022-02-23 at 6 38 34 PM" src="https://user-images.githubusercontent.com/38872890/155429402-9cb8f4a9-5f64-407c-ba1c-3894c666cfef.png">

<img width="615" alt="Screen Shot 2022-02-23 at 6 43 36 PM" src="https://user-images.githubusercontent.com/38872890/155429497-ceecd625-4880-476f-a1e8-fd1d3c17602c.png">

**Comment by andresgalante** [comment]
To reproduce this the wallet needs to be open on a short viewport, less than ~510px

**Comment by fbwoolf** [comment]
Maybe I can address this along with: https://github.com/hirosystems/stacks-wallet-web/issues/2256

**Comment by andresgalante** [comment]
Great idea! responsive doesn't mean only width, but also the height of the viewport.

**Comment by Eshwari007** [comment]
Test passed in v3.3.0
