### ISSUE TITLE
Pending indicator seems to be overlapping for wrapped-nothing token

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2267]
The user was testing version v3.2.0 for comparison testing

User noticed that for STX and other tokens like Miamicon , the Pending icon doesn't overlap but for this particular token seems like over lapping. Attaching screenshot for perusal

<img width="387" alt="Screen Shot 2022-02-24 at 1 19 09 PM" src="https://user-images.githubusercontent.com/38872890/155584194-25a8688f-0904-4ba2-bb5b-3ea487ffee23.png">

**Comment by andresgalante** [comment]
This is a problem with long strings and line-height that wasn't tested properly when implementing the component.

Even though it's easy to fix, I suggest we tie this issue to the improvements of the activity list #1605, I'll add it to the milestone https://github.com/hirosystems/stacks-wallet-web/milestone/52
