### ISSUE TITLE
The Activity empty state is briefly shown even when there are transactions

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2269]
h/c @eugeniadigon 

The Activity tab empty state is briefly shown even when there are transactions in the account. It shows quickly before loading the actual content. The expected behavior of the empty state is to only show when the list is empty.

**How to reproduce (tested on the pop-up size)**
1. Have a wallet with transactions and ready to use
2. Navigate to the activity page
3. Close and re-open the popup with the browser extension icon

Video:
https://user-images.githubusercontent.com/239215/155749709-07e92565-82e8-4faf-8904-791830a96c6c.mp4

**Question:** Should we consider having a loading state here?

**Comment by markmhendrickson** [comment]
I would indeed suggest having a loading state here (and generally anywhere in the app where a delay in API-based data could theoretically become perceptible).

Though we don't have to necessarily show it until the API has taken more than a preset amount of time (e.g. 1 second) to respond. That way we avoid flashing the loading state very briefly, which makes for a bad effect.

A skeleton loader may be ideal in this case.

**Comment by landitus** [comment]
Yes, I agree having a skeleton loading would do the trick. Happy to take this on!

**Comment by landitus** [comment]
Added this related task https://github.com/hirosystems/stacks-wallet-web/issues/2276

**Comment by kyranjamie** [comment]
Dupe of https://github.com/hirosystems/stacks-wallet-web/issues/2276
