### ISSUE TITLE
Small delay is creating a new account

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2271]
Testing PR #1822 
While testing the PR, the user was creating a new account and noticed that it derive the accounts, and this is why there's a small delay with a blank screen loading spinner. Creating the ticket for future tracking purpose

https://user-images.githubusercontent.com/38872890/155775037-c1122ff9-1c4f-4299-a8bd-2ef55bef4262.mov

**Comment by andresgalante** [comment]
Does this block merging #2172 to dev?

**Comment by Eshwari007** [comment]
> Does this block merging #2172 to dev?

I wouldnt say its a blocker ,its a minor bug .#2172 can be merged but I will need to test the onboarding homepage features on it first if possible prior to merging it to Dev.Only Kyrans refactor part has been tested on #2172.

**Comment by pete-watters** [comment]
Closing this off as its outdated
