### ISSUE TITLE
Selecting Hiro wallet header on main page redirects to Backup your secret key page

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2279]
The user is testing v3.2.0

There are two issues here:

Issue 1:

- User selects the extension
- User views the main onboarding page
- User selects the Hiro wallet header
- User is directed to Backup your secret key page(user was using the account earlier before signing out)

This is a major bug as user had already signed out from the account and selecting the header should not direct user to the previous logged in account secret key

Issue 2:

- User tries to select the header several times to see if its reproducible
- User notices that extension turns to blank screen

Attaching screen recording and screenshot for perusal

https://user-images.githubusercontent.com/38872890/156219101-6136c8a5-e9a1-44a7-95f1-2aff8e06fc45.mov

<img width="440" alt="Screen Shot 2022-03-01 at 12 26 32 PM" src="https://user-images.githubusercontent.com/38872890/156219151-1fe5c58c-ca51-4ce0-811e-6e893239f35d.png">
<img width="1316" alt="Screen Shot 2022-03-01 at 12 27 39 PM" src="https://user-images.githubusercontent.com/38872890/156219153-47aa6662-9b6e-4542-94e9-21a86b7c874f.png">

**Comment by andresgalante** [comment]
@fbwoolf would this be something that the move to redux fixes somehow?

**Comment by fbwoolf** [comment]
> @fbwoolf would this be something that the move to redux fixes somehow?

I don't know what you mean? This is bc of a new `onboarding-gate` that was implemented on this branch for routing. I have actually fixed it in my PR so I can implement the change here.

**Comment by fbwoolf** [comment]
Fixing this issue is included my PR which was the original problem: https://github.com/hirosystems/stacks-wallet-web/issues/2236

**Comment by markmhendrickson** [comment]
Hm I'm unable to recreate this myself in production, but I agree we should patch even if intermittently occurring. 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/28991/156225642-e8d30a79-ed71-45be-b8db-482e2fc1bcec.png">

**Comment by fbwoolf** [comment]
This is the same issue as: https://github.com/hirosystems/stacks-wallet-web/issues/2236. It will be fixed in: https://github.com/hirosystems/stacks-wallet-web/pull/2277

**Comment by andresgalante** [comment]
I'll close it in favor of #2236
