### ISSUE TITLE
No Option for Setting New Password on Chrome Extension on PC

### ISSUE THREAD

**Issue by sjwhitely** [blockstack/blockstack-app#2280]
Met with PC user live - using latest version of Chrome and the Web Wallet - and he is unable to set a new password for his Web Wallet. User has done all the following steps:
1- Backed up Secret phrase 
2- Signed out
3- log in again with secret phrase
4- Deleted browser extension and re-installed
5- tried from Microsoft browser 

Attached is screenshot of Dev View from user's side when he arrives at the "enter password" page. 

He does not have this issue with Desktop wallet. 

_Hiro team members on Macbooks were unable to reproduce this issue._ 

<img width="1512" alt="Screen Shot 2022-03-02 at 10 05 18 AM" src="https://user-images.githubusercontent.com/98830038/156397570-0c2b4520-cb65-406c-81b0-9e579f45dc92.png">

**Comment by kyranjamie** [comment]
Usually you enter a password on the step after entering your seed phrase. 

What happens, exactly, after this step?

**Comment by sjwhitely** [comment]
After he logs out, re-enters his seed phrase, he gets prompted to enter his password instead of create a new one. He sees this:
<img width="287" alt="Screen Shot 2022-03-02 at 11 12 17 AM" src="https://user-images.githubusercontent.com/98830038/156401615-83283d6f-8b41-464d-a5b5-d6d3de73e787.png">

**Comment by sjwhitely** [comment]
When he should see this:
<img width="389" alt="Screen Shot 2022-03-02 at 11 13 44 AM" src="https://user-images.githubusercontent.com/98830038/156401745-e2bc6f6d-59e4-4ef3-95a7-45205a43a9bb.png">

**Comment by markmhendrickson** [comment]
I'm moving to QA so they can attempt to recreate on Windows.

**Comment by sjwhitely** [comment]
Another user reported same issue on PC this morning (just keeping track :) )

**Comment by andresgalante** [comment]
@Eshwari007 I am wondering if we can test both if we can reproduce it in prod and if it's solved on `dev`

@sjwhitely Do we know what version of Windows they are on?

**Comment by Eshwari007** [comment]
Tested the issue on Windows 
Wallet version: v 3.2.0
Edition: Windows 11 Home
Version:21H2
OS Build:22000.493

I was not able to reproduce the issue above. @sjwhitely Can you share users' Windows machine details? Much appreciated.

**Comment by sjwhitely** [comment]
@Eshwari007 awaiting user's response! getting you that information :)

**Comment by sjwhitely** [comment]
@Eshwari007 it is an hp spectre running windows 11

**Comment by andresgalante** [comment]
@timstackblock can you please try to reproduce it

**Comment by timstackblock** [comment]
This is working as expected in the current production wallet on chrome/windows with wallet version v3.3.0 

Please see the video here http://somup.com/c3er2wTdO2 and screenshots below and let me know if this is still an issue for the user.



![image](https://user-images.githubusercontent.com/49165468/159283240-e27995c4-d38a-437c-978e-a2fe2842e4e4.png)

**Comment by Eshwari007** [comment]
cc @sjwhitely The above along with recording from @timstackblock

**Comment by sjwhitely** [comment]
@Eshwari007 do you think it's at a place now where I can have the user re-try? Based on what you saw last week and testing today?

**Comment by Eshwari007** [comment]
> @Eshwari007 do you think it's at a place now where I can have the user re-try? Based on what you saw last week and testing today?

@sjwhitely Yes ,I think its safe to ask the user to retry and check if he has any etc extensions on his browser which may overlap with the issue that we saw last week.

**Comment by timstackblock** [comment]
Based off @kyranjamie feedback where he saw the magic recovery key screen during the screenshare video. I think that we can just ask the user if they are using a 24 word seed phrase or a magic recover code they received via email for an old blockstack browser user ID. If they are using a magic recover code they will never be able to set a new password and will always be prompted to enter the password associated with the old blockstack browser ID and the magic recover code. Then this would be expected behavior.

**Comment by Eshwari007** [comment]
cc @sjwhitely the above

**Comment by sjwhitely** [comment]
@timstackblock they are using a 24 word seed phrase and created the wallet in Feb 2022, so wouldn't be associated with a blockstack browser user ID.

**Comment by Eshwari007** [comment]
cc @timstackblock on the above

**Comment by kyranjamie** [comment]
Are they entering their seed phrase with some funny formatting? If entering as `word <space> word...` magic recovery step will not appear.

**Comment by Eshwari007** [comment]
> Are they entering their seed phrase with some funny formatting? If entering as `word <space> word...` magic recovery step will not appear.

cc @sjwhitely

**Comment by sjwhitely** [comment]
@kyranjamie YOU GET 1000000 BONUSLY POINTS!
