### ISSUE TITLE
Address changes to stacks.js packages

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2282]
https://discord.com/channels/621759717756370964/803293319328170024/948604001174323241

as of stacks.js >3.3.0 the bundling (main fields) is a bit different, for the same behavior as previously you will likely want to add a resolve.alias to the webpack config as seen here: https://github.com/janniks/stacks-wallet-web/blob/fea34ecfa667518ea9eecdf3b8161aa8e3fad1e3/webpack/webpack.config.base.js#L72-L82 (only for the relevant updated packages)

another diff for when upgrading all stacks.js packages to latest: https://github.com/hirosystems/stacks-wallet-web/compare/dev...janniks:add-esm-alias

**Comment by fbwoolf** [comment]
This needs to be addressed when we update to `3.3.0` stacks.js packages. We are currently using `3.0.0`.

**Comment by beguene** [comment]
For QA: Only regression tests are needed here.

**Comment by timstackblock** [comment]
.btc names still do not work with the latest version of the app https://sigle-git-feature-stacks-wallet-extension-sigle.vercel.app/

Ran a test with a regular ID it works fine.
Then ran a test with my .btc username and it wont allow you into the app

VIDEO of the issue
https://somup.com/c3evqbOVTC

**Comment by markmhendrickson** [comment]
@timstackblock is any error showing up in particular for the app in the developer console?

**Comment by markmhendrickson** [comment]
I was able to authenticate with my own `.btc` username.

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/28991/161267587-2d77b406-484e-4042-83b7-01dedc98071b.png">

**Comment by Eshwari007** [comment]
Will retest upon having https://github.com/hirosystems/stacks-wallet-web/issues/2283 issue fixed

**Comment by andresgalante** [comment]
Waiting for the test app to update stackjs to be QAed

**Comment by Eshwari007** [comment]
@janniks Kindly advise if the stack.js has been updated and its good to go for another round of testing.
Thx

**Comment by janniks** [comment]
I released stacks.js + connect, will now create a wallet-web PR that updates to the latest versions...

**Comment by pradel** [comment]
Thanks @janniks, for testing purposes, I updated the staging Sigle app https://sigle-git-feature-stacks-wallet-extension-sigle.vercel.app/ with the latest stacks.js + connect too.

**Comment by Eshwari007** [comment]
> I released stacks.js + connect, will now create a wallet-web PR that updates to the latest versions...

@janniks Do ping me when I can test the new stacks.js changes on web wallet extension.Thanks

**Comment by janniks** [comment]
https://github.com/hirosystems/stacks-wallet-web/pull/2333 updates to current stacks.js (4.0.0)

**Comment by Eshwari007** [comment]
> #2333 updates to current stacks.js (4.0.0)

@janniks Test passed with the web extension above ,singing in to https://sigle-git-feature-stacks-wallet-extension-sigle.vercel.app/

**Comment by Eshwari007** [comment]
Tested the fix with https://app.stackswap.org/swap as well, its working well!!
