### ISSUE TITLE
Upgrade to latest `@stacks/wallet-sdk`

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2283]
We need to upgrade the wallet-sdk to the version including @friedger's PR https://github.com/hirosystems/stacks.js/pull/1204

This will fix profile signing for new users

cc/ @markmhx @pradel

**Comment by pradel** [comment]
To add to the context, I saw that a commit with 3.4.0 release was created but I couldn't find the tag on npm so maybe something went wrong during the release process.

**Comment by fbwoolf** [comment]
Will need to address this when we do the update: https://github.com/hirosystems/stacks-wallet-web/issues/2282

**Comment by markmhendrickson** [comment]
@kyranjamie @pradel Can one of you spell out the exact problem that will or does occur already _without_ this upgrade, so that we capture clearly here the specific UX benefit to this upgrade?

**Comment by pradel** [comment]
This fix is for signing the profile.json with the right key, no UX changes are required.

**Comment by markmhendrickson** [comment]
I mean to ask, what UX problems will occur if we don't make this upgrade (aside from us needing to make any UX changes per se, since I agree those aren't required)?

In other words, what will go wrong exactly (e.g. with Sigle usage) if we don't upgrade how the profile.json is signed? I presume something akin to what we outlined [here](https://www.notion.so/hiropbc/Resolve-legacy-BNS-support-8b4780ed29654c83b8fb3b0e1b7e7d3a#78988215cab0459d99ab65c4193ce93d) in Notion, but would like to capture here on GitHub as well.

**Comment by pradel** [comment]
From the notion, the part not working is:

> - Accounts displayed all the same as before
> - Others attempting to view `sigle.io/mary.id.blockstack/mypost` can view her blog post
> - Others attempting to view sigle.io/mary1.btc/mypost cannot view her blog post

The profile.json is signed with the wrong key, so when we fetch the profile we can't verify that `mary1.btc` did sign it properly.

**Comment by timstackblock** [comment]
.btc names still do not work with the latest version of the app  https://sigle-git-feature-stacks-wallet-extension-sigle.vercel.app/


Ran a test with a regular ID it works fine.
Then ran a test with my .btc username and it wont allow you into the app

VIDEO of the issue
https://somup.com/c3evqbOVTC

cc @Eshwari007 @markmhx

**Comment by andresgalante** [comment]
@Eshwari007 can you please test this issue with a .btc name?

**Comment by Eshwari007** [comment]
Test findings

Tested the PR on https://sigle-git-feature-stacks-wallet-extension-sigle.vercel.app/login
Test failed, I was not able to login and notice errors in console log 
Attaching the screenshots for perusal

<img width="1405" alt="Screen Shot 2022-04-05 at 4 41 03 PM" src="https://user-images.githubusercontent.com/38872890/161845607-64c42547-9884-47c3-b97f-d5e1100f5fed.png">
<img width="373" alt="Screen Shot 2022-04-05 at 4 41 44 PM" src="https://user-images.githubusercontent.com/38872890/161845608-bc4f0790-88aa-4991-8000-8b19238844f9.png">
 

cc @andresgalante @markmhx @pradel

**Comment by andresgalante** [comment]
Thanks @Eshwari007 🙇 @pradel @beguene what are the next steps?

**Comment by beguene** [comment]
@andresgalante Not sure about the next steps. In this PR I fixed the unit tests errors but I did not touch the profile signing issue maybe @pradel Can give more details.

**Comment by pradel** [comment]
@beguene @andresgalante @Eshwari007 I will have to look next week what's going on.

But looks like I can't login anymore using an account with a .btc domain with the latest 3.7.0 version. I tried on Arkadiko, Alex and Frens. So the issue you faced might not be related to the changes?

<img width="493" alt="Screenshot 2022-04-07 at 15 41 35" src="https://user-images.githubusercontent.com/5749437/162213186-3e8d04cc-a8be-4577-8a6f-70535121981b.png">

**Comment by pradel** [comment]
Created a separate issue https://github.com/hirosystems/stacks-wallet-web/issues/2354

**Comment by markmhendrickson** [comment]
I believe we need to upgrade Stacks.js for the test app to include the changes made with https://github.com/hirosystems/stacks.js/pull/1230 then retest the related PR. 

@janniks can confirm if that's indeed the case here given the case encountered above during testing before.

**Comment by andresgalante** [comment]
Waiting for the test app to update stackjs to be QAed
