### ISSUE TITLE
Provide path for username migration in accounts list

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2284]
The goal is to ensure that all users with addresses and corresponding BNS usernames from Stacks 1.0 can access and use them with apps on Stacks 2.0.

In order to do that, we should provide a way for Wallet users to migrate their usernames from data-key addresses to wallet-key addresses.

**Web wallet experience**
1. Prompt the user to migrate their username per account
2. The user views a confirmation screen for the migration and confirms it
3. A migration request is submitted to the registrar and becomes pending
4. After a wait time, the accounts view is updated to confirm migration

**Comment by markmhendrickson** [comment]
I'm closing this since upon further discussion it appears more expeditious that we pursue this new UI via the CLI instead of the wallet: https://github.com/hirosystems/stacks.js/issues/1209
