### ISSUE TITLE
Display only usernames owned by wallet-key-derived addresses in accounts list

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2287]
Currently we display usernames in the accounts list regardless of whether they are registered with a given account's data key or wallet key.

We should instead only show usernames registered with the wallet key. However, along with this change, we should also provide guidance to users that they can [use the CLI to migrate their usernames](https://github.com/hirosystems/stacks.js/issues/1209) from the app-key-derived addresses to wallet key ones.

This guidance could be a simple message at the bottom of the accounts list that says `Learn more about accounts` that takes the user to an FAQ where we can explain the migration path.

[See context](https://www.notion.so/hiropbc/Resolve-legacy-BNS-support-8b4780ed29654c83b8fb3b0e1b7e7d3a)

**Comment by friedger** [comment]
Is this website enough for guidance? https://renewbns.com/

**Comment by landitus** [comment]
We'd like to mark accounts that need migration in the context of the wallet. After discussing with @markmhx we're going to work on designs for the following:

Both on the **Switch accounts** and the **Choose your account** pages:
- In the accounts lists, the items with app-key-derived address will be shown with their default name (Account X). They will have an inline note or tooltip with the following: `[account-name] is owned by the legacy address for this account`
- If there are one or more accounts affected, we'd show an inline alert at the top of the page: 
-- `You have [x] accounts owned by the legacy addresses. [What you need to do...] `
-- CTA: `Transfer username` [External link to FAQ about migrating with the CLI]

**Comment by landitus** [comment]
> Is this website enough for guidance? https://renewbns.com/

Does it support subdomains? I believe we need that to provide a successful migration. That's why we'd point to a CLI workflow.

**Comment by markmhendrickson** [comment]
The RenewBNS app above doesn't support subdomains, which makes me link we should link to a general FAQ about renewals then guide the user to either that app or the CLI based on their needs.

**Comment by markmhendrickson** [comment]
On further reflection, let's tackle these changes as part of this issue:

1. Show only usernames owned by wallet-key addresses

But let's _not_ do this for now:

2. Indicate per account whether there is a legacy name
3. Show alert at top of screen with indication of how many accounts are affected
4. Add link to "Learn more about accounts" (since already handled by https://github.com/hirosystems/stacks-wallet-web/issues/2293)

This should cut down on the work involved here in general.

If we discover that users demand enhancements 2 and 3 in particular, we can return to them for prioritization. In the meantime, the first two changes should be sufficient.

**Comment by markmhendrickson** [comment]
Kyran has mentioned that this work will also simplify the code and increase loading performance significantly. It should involve removing usernames from the wallet SDK. cc @janniks

**Comment by markmhendrickson** [comment]
@timstackblock to verify whether this change is already in production by testing for old usernames

**Comment by timstackblock** [comment]
This is not working for me in production, I do not see my legacy username.

Moving this to dev for review by a developer.



![Image](https://user-images.githubusercontent.com/49165468/169538148-f2956b3b-b1dc-4a6d-85a4-dda5ce1d8190.png)


To test this log in with a legacy username thisisit202020.id.blockstack by using the magic recovery key.

KDR6O8gKXGmstxj4d2oQqCi806M/Cmrbiatc6g7MkQQLVreRA95IoPtvrI3N230jTTGb2XWT5joRFKPfY/2YlmRz1brxoaDJCNS4z18Iw5Y=

When prompted enter the password
test202020

**Comment by markmhendrickson** [comment]
@pradel Mind indicating your experience with legacy usernames in the latest version of the wallet? It seems like they don't show up anymore (as desired), but we're not entirely sure given our test accounts.

**Comment by timstackblock** [comment]
This is correct the legacy name is not showing up if this is the desired result we are good to go
