### ISSUE TITLE
Firefox wallet does not display other accounts

### ISSUE THREAD

**Issue by beguene** [blockstack/blockstack-app#2291]
One user experienced an issue with Firefox.
"I have multiple accounts (two) in my Hiro wallet Chrome Extension
I also have the Hiro Extension installed in Firefox

When I log in to the Hiro wallet on Firefox extension I can only see account 1. I cannot 'switch accounts'."
version V3.2.0 in both
Both wallets used the same seed.

**Comment by markmhendrickson** [comment]
Do their other accounts not show up upon selecting "Create An Account"?

**Comment by markmhendrickson** [comment]
I'm closing this out with the presumption that it's the same as https://github.com/hirosystems/stacks-wallet-web/issues/1732
