### ISSUE TITLE
Warn aggressively if user is trying to send a TX where STX being sent + STX fee > STX wallet balance

### ISSUE THREAD

**Issue by cargocultscience** [blockstack/blockstack-app#2296]
We see this issue quite often especially with DEXs where users want to transfer all of their STX into a swap or LP token. What then happens is a user tries to send a transaction for their entire STX balance. They do not think about the fee portion and thus will soon have a stuck transaction.

Hiro wallet should go out of its way to warn the user that they are attempting to ship a transaction that does not have sufficient STX to be processed by miners. Yes, there are scenarios where you might want to send a transaction of this nature but they are exceedingly rare.

**Comment by markmhendrickson** [comment]
The wallet _should_ prevent the user from broadcasting such transactions already, but calculating only the available funds to send after the deduction of fees when the user selects "Send Max", and by throwing an error if the user manually enters an amount that exceeds the balance minus fees.

@cargocultscience have you seen multiple instances of the wallet letting users submit send values that exceed the balance minus fees?

**Comment by markmhendrickson** [comment]
If there's a bug here, we'll track its fix on https://github.com/hirosystems/stacks-wallet-web/issues/2311
