### ISSUE TITLE
Wrapped-nthng token tx failed with postcondition error

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2301]
User was performing the usual non STX token transfer as per regression testing
User is aware all the tokens will be successful
However, the token below failed after pending tx which stated `This transaction would have succeeded but was rolled back by a supplied post-condition.`. I did not notice any post condition on the tx details hence logging it for investigation.

Token:wrapped-nthng

https://explorer.stacks.co/txid/0x7fe20da9aaad6ae39c47e2e259ae06780f99d001da338a988ff033bcea3a6e19?chain=mainnet

**Comment by friedger** [comment]
Same for other FTs, like USDA
https://explorer.stacks.co/txid/0xcf07672c834a53aed84b43b8b203794c9f6eb982fb1f9a1e9887744e56ab1c98?chain=mainnet

Using version 3.3.0

Post-condition error is never an error of the contract, but of the client/wallet.

**Comment by andresgalante** [comment]
More info here https://github.com/hirosystems/explorer/issues/667

**Comment by andresgalante** [comment]
@kyranjamie I am assigning this issue for you to investigate.

**Comment by whoabuddy** [comment]
I can also confirm this is happening with MIA transfers from the web wallet.

**Comment by whoabuddy** [comment]
Looking back at the `miamicoin-token` and `newyorkcitycoin-token` contracts I found several examples of transfers without post-conditions popping up in the recent transactions.

MIA

https://explorer.stacks.co/txid/0x9996a78e23020082e60f43b4b1f7e48270bb327c27077dc95582a7f9804b05ee?chain=mainnet
https://explorer.stacks.co/txid/0x68c9d8886c7d4c8ca7cd4bce845e992f1ef41311fe30827c0c4cced215f30271?chain=mainnet
https://explorer.stacks.co/txid/0xa7928d7c6d13e311b20e41c84d52424b0621cf8383ba024a0ef83bdcce1424c4?chain=mainnet
https://explorer.stacks.co/txid/0xe453dcb73ccd8200641044b560f8ba8f8bac4e6088b39606d19d18c9e24bc115?chain=mainnet
https://explorer.stacks.co/txid/0x0d8a5700933606cd3e6f7fc10b0227f3c213ccaf071e27cb61e0707ee51c7558?chain=mainnet

NYC

https://explorer.stacks.co/txid/0x79a3c2115ebff2776dd57b7cec94dc2c857242a3cd83d9b43461e0c06b8814c8?chain=mainnet
https://explorer.stacks.co/txid/0x02d41f1d777556bd75391f46da3bf99e609158b4b3cb9ab25e585c79cd9ff2c9?chain=mainnet
https://explorer.stacks.co/txid/0x1a4d28875a31367382bde570c1d38618f3f031910af066bf94a80413070d543a?chain=mainnet
https://explorer.stacks.co/txid/0x80e11b1345b70edd98cd552dc14f73ef5123006f01dc4f89cde0accd2e0d63e9?chain=mainnet
https://explorer.stacks.co/txid/0x8909eeb44b9b71eadd97b28055ff9495efd86e8dafaa13742fd1d428f8cc59cf?chain=mainnet

**Comment by Eshwari007** [comment]
Tested the issue against the PR.
Moving it out of QA as its not reproducible
