### ISSUE TITLE
Design a generic illustration for error pages

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2305]
Let's have a generic illustration for any error pages. I think we could go for a classic (!) exclamation in a circle or in a triangle as a starting point with any other elements related to our brand language.

[Here's the Figma where we can work on this](https://www.figma.com/file/EpJiJrYfaVzFm5DP3XnANB/%232157---Redesign-error-message?node-id=10%3A1352)
Related issue: #2157

**Comment by ginny-d** [comment]
Figma file is updated now with illustration
