### ISSUE TITLE
Animate the Ledger illustrations

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2306]
We'd like to animate the Ledger illustrations to add more delight to the experience and also reinforce the physical interactions required to operate the device. This could be done after the feature release, but we'd like to get ahead with the design.

### Scope

We currently have 7 illustrations where we could add motion. It would be worth reviewing the illustrations to make them similar in proportions so it can be easy to transition from one to the other. We have plans to add transitions between each step, to add more fluidity and further enhance the experience.

1. Connect: plugging the Ledger into a computer
2. Connecting: Could be a subtle variation of the previous one (or we re-use 1)
4. Success: Green checkmark
5. Verify: focus on pressing both buttons and checkmark
6. Error: Generic failed ledger
7. Disconnected: Ledger unplugged from computer

![Ledger animations](https://user-images.githubusercontent.com/239215/158629500-de245f67-22f7-4c12-a179-a7c64fb9f824.png)

[Figma](https://www.figma.com/file/Di8iSLFICR2twUdjdduGig/%F0%9F%94%91-Ledger?node-id=356%3A12344)

---

### Approach

We are going to work with @eugeniadigon and a motion designer for this. I believe we haven't implemented these kinds of animations before in the Wallet, so wanted to check with @fbwoolf @kyranjamie if there are any requirements regarding the format of the animations. Is there anything you'd want to test first? I'm thinking we could do an early test to check performance and file size if needed.

---

### References
- **Sonos** mostly for the subtle transitions between steps and animations, which we could add at a later stage.
- **Ledger** has a very nice onboarding full of Ledgers (of course!)  

https://user-images.githubusercontent.com/239215/158643574-2b579b03-0506-4ed1-8c7e-576ed2dd256f.mov

https://user-images.githubusercontent.com/239215/158643813-f17b576f-5daf-42a4-9c13-5ca5acc78bbd.mp4

**Comment by landitus** [comment]
Added references! cc/ @eugeniadigon

**Comment by kyranjamie** [comment]
Love this. 

I don't think there's much to consider by way of constraints. We'd likely use a library like `react-motion` or `react-spring` if we have a vector-based animations, or just a plain animated SVG (if it's simple)

Assets will be bundled with the extension and loaded from disk, so file size is less of an issue than were this a website.

**Comment by landitus** [comment]
Would about the [Lottie](https://lottiefiles.com/) format? I think it's widely used for motion animation (specially coming from After effects and other GUI motion software)

**Comment by landitus** [comment]
@eugeniadigon found an additional one we could animate, the disconnected state. This one should probably not include the (!) as part of the illustration, as I'm still refining this screen. I'd consider the ledger only as part of the illustration/animation.


![Disconnect](https://user-images.githubusercontent.com/239215/158811854-a75e68b6-794b-4a0e-bbee-9c57751ca5da.png)

**Comment by fbwoolf** [comment]
How do I run the animations in the Figma link?

**Comment by ginny-d** [comment]
@markmhx @landitus @kyranjamie 

- [Here's the figma board](https://www.figma.com/file/H5CmFSFOIIJE6gciGxeq95/%232306---Ledger-animations?node-id=1%3A3444) with the storyboard/UI reference of each animation

- And I'm attaching two files, one with the mp4 preview animations, and another one with the JSON files

[Json-20220329T135128Z-001.zip](https://github.com/hirosystems/stacks-wallet-web/files/8372055/Json-20220329T135128Z-001.zip)
[Mp4-20220329T135125Z-001.zip](https://github.com/hirosystems/stacks-wallet-web/files/8372056/Mp4-20220329T135125Z-001.zip)

**Comment by landitus** [comment]
thanks @eugeniadigon ! These are looking awesome! As a first review, as we agreed, we can focus on the first animation for the Connect screen. This is actually the most complex to position in the widget, since it has taller proportions. As you can see in @kyranjamie first test, the ledger looks off-centered because of this, and my goal is to have the Ledger LCD screen be the focus and center of the animation at all times. Also note that in the mocks, the animation will be positioned with 40px margin to the sides of the window.

[I've mocked in Figma](https://www.figma.com/proto/H5CmFSFOIIJE6gciGxeq95/%232306---Ledger-animations?page-id=89%3A2593&node-id=89%3A5097&viewport=241%2C48%2C0.5&scaling=scale-down) how it looks when centered, and though some parts get cut off, I think it looks better overall. We can work with the animator to fade the elements off-screen, for example.

**Off-centered**
<img width="601" alt="Screenshot 2022-04-13 at 18 04 45" src="https://user-images.githubusercontent.com/239215/163222855-be555903-1fd5-4a60-9e80-218f8b8b5fb8.png">

**Centered**
<img width="1279" alt="Screenshot 2022-04-13 at 18 02 36" src="https://user-images.githubusercontent.com/239215/163222465-f5ea8f3c-544d-468e-9864-b68db21358bf.png">

Additionally, for the connect animation, I believe it will look better without the flashing green buttons. It takes the focus away from the LCD screen with the Stacks app logo. Actually, we could play with the logo and animate it like Ledger does when selecting apps in the menu. Here's a preview:

![20220412_152225_resized](https://user-images.githubusercontent.com/239215/163223323-166cf253-3cb3-43c3-a22b-2e7dd6f7be7d.jpg)
![20220412_152218_resized](https://user-images.githubusercontent.com/239215/163223338-49de00dd-a762-499b-b711-6d6cf70ecc5b.jpg)

**Comment by fbwoolf** [comment]
@kyranjamie should I be looking at helping you with this or you are doing?

**Comment by kyranjamie** [comment]
Until we have updated animations there isn't anything to do yet

**Comment by mica000** [comment]
@fabric-8 @mica000
