### ISSUE TITLE
Ensure wallet calculates max amount for sends accurately

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#2311]
There is a [report on Discord](https://discord.com/channels/621759717756370964/745197302255321108/953968695825301534) for wallet `v3.3` seeing an "Insufficient funds" message which might be a bug in the way the wallet auto-calculates max amount

![hiro-wallet-3 3 0](https://user-images.githubusercontent.com/1832037/158811331-159b17f5-77d3-4728-a15f-89c53b141ea9.png)

> I've just bought BNS name and I'm sending funds from that wallet to another address and I'm getting an 'Insufficient funds' message however there are no transactions that have gone out/in the process of going out of this wallet (I've double checked the address on Stacks Explorer too in case there was a lag).

They also mention this bug: https://github.com/hirosystems/stacks-wallet-web/issues/2176
> I also had a 'fee too low' message too on a few of the attempts, which was auto calculated - changed it to 'High' but no difference & unable to send the funds.

**Comment by markmhendrickson** [comment]
@andresgalante have you seen this issue recently?

**Comment by Eshwari007** [comment]
@markmhx I have not seen this issue recently personally from my end

**Comment by andresgalante** [comment]
I'll close it, thanks Mark
