### ISSUE TITLE
Review layouts and responsiveness in pages

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2314]
There are inconsistencies in the page layouts, regarding how the content is positioned and scrolled. This is specially noticeable in the large size, and not in the smaller widget. So far, I've noticed that **Fund account**, **Receive** and **Secret keys** pages have vertically centered contents. When the viewport is shorter, the elements collide with the header and get cut off the viewport. Unlike the **Send** page, which has normal scrolling and positioning and any viewport size.

## Scope
- [x] Review all pages responsiveness (narrower and shorter viewports)
- [ ] Propose a design spec for consistent page layouts going forward https://github.com/hirosystems/stacks-wallet-web/issues/2322
- [ ] Check other issues about pages https://github.com/hirosystems/stacks-wallet-web/issues/1947 

## Examples

<img width="1080" alt="Screenshot 2022-03-18 at 15 47 34" src="https://user-images.githubusercontent.com/239215/159029799-65f45a96-344f-4556-8ea4-1c6ef417876d.png">

**Comment by landitus** [comment]
As @fbwoolf has been improving the responsiveness of the app, the first step would be to review this PR https://github.com/hirosystems/stacks-wallet-web/pull/2277 and check if the visual bugs persist.

**Comment by landitus** [comment]
#2277 Will fix all centering and scrolling issues and will get us to a better place in terms of layout and responsiveness. Still, I found more inconsistencies in the headings and navigation. The next step is re-define the spec for the layout and navigation.

**Comment by pete-watters** [comment]
Closing this off as I believe it to be outdated and we have improved our responsiveness a lot in https://github.com/leather-io/extension/pull/5176
