### ISSUE TITLE
Add a "Low Cap" to avoid fees being too low

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#2315]
There is a [report on Discord](https://discord.com/channels/621759717756370964/745197302255321108/954391674166055013) of a transaction fail due to caps being too low after the new estimations were released.

We'd like to add caps to disallow fees being too low.

We'll need help from @saralab and @kantai to decide what those caps should be set up at

**Comment by kantai** [comment]
For a 100 KB transaction (this would be a unusually large transaction), the "minimum relay fee" is 1 microstack per byte,

```math
(1024 * 100 bytes) * (1 microstack / byte) / (1,000,000 microstacks per stack)
```

This would be ~0.1 STX for the transaction, which would be a reasonable lower limit.

**Comment by markmhendrickson** [comment]
Is it correct that we've only seen the estimates being "too low" for the "Low" suggested value in particular thus far? Or are the other two values known to be affected and effectively in need of this "low cap" / floor as well?

(I'm asking for incidence clarity even though whatever functionality we ship here should allow us to set floors for all three values regardless)

**Comment by fbwoolf** [comment]
@markmhx can you confirm what we want to set the three low fee caps to be?

**Comment by 314159265359879** [comment]
> @markmhx can you confirm what we want to set the three low fee caps to be?

When the wallet did not have an option to set the fee value yet it would always default to the minimum fee the network would accept for a given function call. I think that should be the minimum on all options.

**Comment by fbwoolf** [comment]
> 
> When the wallet did not have an option to set the fee value yet it would always default to the minimum fee the network would accept for a given function call. I think that should be the minimum on all options.

That was a calculation using the tx byte length and a fee rate of `400` (from what I remember). These caps are not calculated per tx (that will be implemented later). This is a quicker fix to hard code the fee caps on all txs.

**Comment by kantai** [comment]
Looking again at the historical transactions:

* 99% of transactions are < 2200 bytes, so would be fine with a lower cap of `0.0022`. 
* 99.9% of transactions are < 30000 bytes, so would be fine with a fee cap of `0.03`

A minimum fee cap of `0.0025` would work for the vast majority of cases (probably all transactions ever sent by the web wallet), and for the cases were the fee needed to be increased to get over the network minimum (probably only contract publish transactions), the user can just increase the fee manually.

**Comment by fbwoolf** [comment]
> 
> A minimum fee cap of `0.0025` would work for the vast majority of cases
>
Super helpful, thanks!

**Comment by Eshwari007** [comment]
Test results:

Tested several STX and non-STX token transfers and all the min fees were `0.0025`
Tested with third party apps such as STX NFT.com and Megapont in their market place for NFT purchase,the fees min were consistent at `0.0025`

I was not able to reproduce the annoying 'fee too low' bug as well which is a big plus during the testing 

cc @fbwoolf @timstackblock @andresgalante

**Comment by fbwoolf** [comment]
This was released and should be closed.
