### ISSUE TITLE
signing sponsored tx doesn't seem to increase nonce

### ISSUE THREAD

**Issue by pseudozach** [blockstack/blockstack-app#2316]
steps:
1- sign a sponsored tx with an account
2- broadcast it via a sponsor
3- sign another sponsored tx with the same account in step-1
4- broadcast it via sponsor -> fails with `badnonce`

Looks like signing sponsored tx doesn't increase nonce.

sending a tx with manual nonce fixes the issue temporarily.

**Comment by fbwoolf** [comment]
@kyranjamie or @beguene you have both worked with nonces. I just tried to reproduce this and the account nonce `288`:
https://stacks-node-api.testnet.stacks.co/v2/accounts/ST12SYBBE6B5P3KQR49WH448HT80JVV645ZP6Y6WY

is not the same as what is returned by the end point we are using to get the `possible_next_nonce` for the edit nonce form:
https://stacks-node-api.testnet.stacks.co/extended/v1/address/ST12SYBBE6B5P3KQR49WH448HT80JVV645ZP6Y6WY/nonces

What am I missing here? Shouldn't these match? The explorer shows `288` but our edit nonce form pulls in `287`.

**Comment by fbwoolf** [comment]
I did the test again ...same result, the `possible_next_nonce` isn't updating when doing a sponsored tx.

https://stacks-node-api.testnet.stacks.co/v2/accounts/ST2PSMKVPJ1CAJMNPE611PS6SFECW8GFQJRNRTTQ0

https://stacks-node-api.testnet.stacks.co/extended/v1/address/ST2PSMKVPJ1CAJMNPE611PS6SFECW8GFQJRNRTTQ0/nonces

This would be an api issue, correct?

**Comment by beguene** [comment]
@fbwoolf We use the api https://hirosystems.github.io/stacks-blockchain-api/#operation/get_account_nonces to get the possible next_nonce and in our wallet code we try to fill the missing nonces if there are any.
Given the 2 links you posted, it seems that the api is not updating the possible_next_nonce. You could check with the api team and see if there is a cache issue or else.

**Comment by fbwoolf** [comment]
> @fbwoolf We use the api https://hirosystems.github.io/stacks-blockchain-api/#operation/get_account_nonces to get the possible next_nonce and in our wallet code we try to fill the missing nonces if there are any. 
>
Yep, thanks for confirming, I got to the linked response from our nonce query. 👍 
>
Given the 2 links you posted, it seems that the api is not updating the possible_next_nonce. You could check with the api team and see if there is a cache issue or else.
>
cc @rafaelcr who would be best to look into this?

**Comment by fbwoolf** [comment]
@markmhx I am going to move this back into the backlog until the issue I created in the `stacks-blockchain-api` repo is addressed: https://github.com/hirosystems/stacks-blockchain-api/issues/1133

**Comment by rafaelcr** [comment]
API issue is now resolved and will be live in the next release https://github.com/hirosystems/stacks-blockchain-api/issues/1133

**Comment by fbwoolf** [comment]
> API issue is now resolved and will be live in the next release [hirosystems/stacks-blockchain-api#1133](https://github.com/hirosystems/stacks-blockchain-api/issues/1133)

Thx @rafaelcr!

**Comment by pseudozach** [comment]
@rafaelcr is there any timeline for when public hiro instances are updated to include this fix? or any official release date?

Users are having this issue which really degrades sponsored tx experience.
![image](https://user-images.githubusercontent.com/3731591/165432805-52d242f8-6514-448e-b815-3ff9918e1fb3.png)

**Comment by markmhendrickson** [comment]
@fbwoolf is this something you can begin to tackle now that API support is available?

**Comment by fbwoolf** [comment]
> @fbwoolf is this something you can begin to tackle now that API support is available?

I don't think this is actually live yet? I believe it was changed in a beta release? @rafaelcr can you confirm? Once it is released, I don't think there is anything we need to do in the wallet. This issue was an api issue. I would just need to retest to confirm it fixes it for sure.

**Comment by rafaelcr** [comment]
@pseudozach @fbwoolf we are in the process of deploying 4.0.0 to production. Right now we have a canary environment serving a percentage of traffic to make sure all is good. If tests are successful, we plan on rolling it out to 100% tomorrow.

I'll update this issue when that happens.

**Comment by Jamil** [comment]
Hey @rafaelcr! Appreciate the updates on this issue; is this rolled out now? 🙂

**Comment by rafaelcr** [comment]
sorry @Jamil not yet, we found a regression that affects BNS name resolution so we rolled back. We'll re-enable ASAP once the BNS fix is done https://github.com/hirosystems/stacks-blockchain-api/issues/1158

**Comment by markmhendrickson** [comment]
I'm closing this out since it's ultimately an API-borne issue.
