### ISSUE TITLE
Review the "Create Account" dialog UX

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2321]
The Create account flow UX could be improved by replacing drawers/dialogs with toast alerts. Today, they present the user with unnecessary information, such as a button with a loading state that is not interactive and not needed. Since the flow needs to provide the user with updates on the creation process, we should go for auto dismissible alerts, a.k.a toast notifications.

https://user-images.githubusercontent.com/239215/159345698-6f5dc748-9171-42d8-8aa0-ee6efe1d3c03.mp4

https://user-images.githubusercontent.com/239215/159345703-91179ae6-c637-49bb-a648-d0c53b8c3085.mp4

**Comment by fbwoolf** [comment]
As a first step, I am switching this to a toast now to get past some failing integration tests: https://github.com/hirosystems/stacks-wallet-web/issues/2370

**Comment by fbwoolf** [comment]
PR merged as first step switching to a toast: https://github.com/hirosystems/stacks-wallet-web/pull/2373

There seems to be inconsistency in seeing the success toast using `react-hot-toast` as is noted in the comments.
