### ISSUE TITLE
'Next steps for you ' UI is hidden when user has more than 1 wallet installed

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2325]
Users can only view the 'Welcome to Stacks 👋' -Next steps for your UI when no other wallets are installed in their extensions.
If for example Phantom and Metamask is installed, the user will only get to view :'Add your funds' UI

Attaching screenshots below
<img width="320" alt="Screen Shot 2022-03-23 at 10 55 12 AM" src="https://user-images.githubusercontent.com/38872890/159730870-512064ca-1508-4677-bd03-0f9746d35b68.png">
<img width="1299" alt="Screen Shot 2022-03-23 at 10 41 48 AM" src="https://user-images.githubusercontent.com/38872890/159730895-bc6ed74a-cc99-4f49-b1e2-99db96cef750.png">

without other wallets installed
<img width="1074" alt="Screen Shot 2022-03-23 at 10 59 48 AM" src="https://user-images.githubusercontent.com/38872890/159730956-17aa23e9-e9e8-4794-a59f-2d32da58ca5d.png">

**Comment by markmhendrickson** [comment]
I believe we concluded elsewhere that this doesn't have anything to do with the other extensions installed, but rather the caching used to hide the next steps from a previous session with the wallet extension had remained and prevented them from showing here?

**Comment by fbwoolf** [comment]
> I believe we concluded elsewhere that this doesn't have anything to do with the other extensions installed, but rather the caching used to hide the next steps from a previous session with the wallet extension had remained and prevented them from showing here?

That is correct, no other wallet installs can really impact the onboarding steps.
