### ISSUE TITLE
Resolve Okcoin error "Sorry, currently we're not allowed to provide service for you"

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2328]
The user was testing the new next steps on the homepage.
As part of the steps testing, the user wanted to add funds and then purchase an NFT to ensure all the checklists were checked under the next steps.

- User selects 'Add some funds'
- User was directed to Okcoin/Transak fiat page, user selects Okcoin and received the error below
- User also tried Transak to see upon selecting non USD is STX is being populated, user was not able to select the selection and even if user is able to,STX was not populated in the available token search

Attaching the screen recording for perusal:

https://user-images.githubusercontent.com/38872890/159826134-b7af78cf-2e5f-4e17-b19e-be5f7d42c56c.mov

https://user-images.githubusercontent.com/38872890/159826156-824877cf-651a-4926-b6b9-1ba1d00f5949.mov

cc @beguene @markmhx

**Comment by timstackblock** [comment]
Tested in Prod after the March 28th release "grey wolf"

**Transak still broken in prod, there is no STX in the dropdown**


<img width="1335" alt="Screen Shot 2022-03-28 at 10 22 55 AM" src="https://user-images.githubusercontent.com/49165468/160425850-55e3749a-ede6-4e26-8584-c3dd5495515d.png">
<img width="1029" alt="Screen Shot 2022-03-28 at 10 23 52 AM" src="https://user-images.githubusercontent.com/49165468/160425848-bba8ff4e-ae10-4822-9bde-8b3db32e1d18.png">


**Okcoin is broken as well users get this error when trying to use the service**


<img width="1440" alt="Screen Shot 2022-03-28 at 10 21 35 AM" src="https://user-images.githubusercontent.com/49165468/160425851-c51a610c-217b-4ace-bb5a-f6c2af456440.png">

**Comment by fbwoolf** [comment]
I am getting the same. @markmhx should this be a priority?

**Comment by andresgalante** [comment]
@beguene can you please take a look at this before anything else? if it is a problem in our side we should fix it ASAP

**Comment by beguene** [comment]
@andresgalante Sure I will check it out.

**Comment by beguene** [comment]
It's working fine from non-US countries, but you can't buy STX from US. This is expected behaviour from Transak.

**Comment by markmhendrickson** [comment]
I can confirm that Transak works here as expected outside of the US:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/28991/160590887-67511a11-1dbe-4da8-9c5e-26cc9d71397e.png">

However, I'm also encountering the same issue with Okcoin as reported initially above. @Eshwari007 @timstackblock have you notify Okcoin of this problem?

**Comment by Eshwari007** [comment]
Update:
@timstackblock tested the issue with VPN  that changes to a different county
Seems like Okcoin has started to have IP checks on the pages 
QA was also thrown a message that please use VPN with an EU license
This was not the case prior when both of us were able to purchase STX via Okcoin.

Findings:
Though the Okcoin checks of IP addresses have changed and facilitate non-US residents, it would be apt to have a better error message when a user signs in to Okcoin via US IP add.

We should perhaps relay this to the Okcoin team. Your thoughts around this are much appreciated. 
cc @markmhx @andresgalante @beguene @timstackblock
