### ISSUE TITLE
Fix intermittent unauthorized request error during transaction signing

### ISSUE THREAD

**Issue by sjwhitely** [blockstack/blockstack-app#2329]
Related to [https://github.com/hirosystems/stacks-wallet-web/issues/2157](https://github.com/hirosystems/stacks-wallet-web/issues/2157) but addresses what could be underlying issue as opposed to design flaw. This message appears across apps and cannot always be solved by logging out/logging back in. 

7 unique reports from users between 3/1/22-3/24/22

**Comment by fbwoolf** [comment]
@markmhx is this something I should take on as a priority bug? It looks like maybe I tried to fix it early on but didn't handle correctly? https://github.com/hirosystems/stacks-wallet-web/pull/2156

**Comment by markmhendrickson** [comment]
@fbwoolf Yes please 🙏 This seems like a P2 bug to me in that having to re-authenticate makes such an issue quite blocking, and transaction signing is obviously a critical path.

**Comment by markmhendrickson** [comment]
Note https://github.com/hirosystems/stacks-wallet-web/pull/2331 from @kyranjamie is intended to help track the incidence rate of these in production

**Comment by markmhendrickson** [comment]
cc @philipdesmedt since he mentioned encountering this over Discord. He may be able to provide more contextual input

**Comment by fbwoolf** [comment]
Yep, I'll get on this today. I think I'm pretty clear on what is happening and can fix.

**Comment by fbwoolf** [comment]
@philipdesmedt do you have exact repro steps on this? I actually can't reproduce this. When I encounter the error msg it is always when I expect to and if I reauth with the correct account it clears.

**Comment by fbwoolf** [comment]
> 



> and cannot always be solved by logging out/logging back in.
> 
Do you have repro steps? Are the users signing out of the wallet or the app to trouble shoot this? See last commet here, I can't seem to repro this so I'll need more info.

**Comment by philiphacks** [comment]
@fbwoolf I can't really TBH - it happens randomly. I switch often between networks so might have something to do with that?

**Comment by fbwoolf** [comment]
> 



> @fbwoolf I can't really TBH - it happens randomly. I switch often between networks so might have something to do with that?

Thx @philipdesmedt, I think I've identified the issue. 👍
