### ISSUE TITLE
Glitch: Welcome screen flashes before showing analytics consent page

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2330]
When landing on a clean wallet install, the welcome page appears (briefly) before insta-navigating to the analytics consent page.

This is because the implementation only checks whether consent has been given on the welcome page itself. This logic should be moved to the routing level, so that on clean install, a wallet always begin the routing flow on this page.

**Comment by pete-watters** [comment]
I think this may have been fixed already as part of this refactor:
https://github.com/hirosystems/wallet/commit/739b44d3f590c24acef56eae07a3a92596c739af#diff-406fe0c8db09c4d2483cbf8b7727e982ac8c8c157c838d500e9e3e5543ff2780

**Comment by kyranjamie** [comment]
Maybe yeah, though just checked and in bg script, on install, we navigate to onboarding page first rather than the diagnostics page. Think this can change

https://github.com/hirosystems/wallet/blob/a798bd1a40faf97c7420e8db463e31a21dd45cf4/src/background/background.ts#L25-L34
