### ISSUE TITLE
searching for token and selecting it, selects stx

### ISSUE THREAD

**Issue by alexrudloff** [blockstack/blockstack-app#2335]
Wallet v.3.5.1 - Chrome 99.0.4844.83 (Official Build) (arm64), MacOS 12.0.1

When trying to send MIA I noticed that when I type in MIA and miami coin comes up, after selecting it the form is filled out for Stacks instead of MIA. If I scroll down and select MIA instead of selecting it via search, it works.

**Comment by timstackblock** [comment]
cc @markmhx

**Comment by andresgalante** [comment]
@kyranjamie can this be related to the latest changes in the FT transfer screen?

**Comment by kyranjamie** [comment]
Unrelated, I think. In all honesty I've never once used the search functionality. This could well be a long-standing issue. Downgrading to P3, this isn't critical fuctionality.
