### ISSUE TITLE
Adjust sign out modal, has software wallet specific content

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2337]
The current sign out window is in appropriate for two reasons:

1) Has copy about software wallets
2) Requires checkbox confirmation (which is less important when using a Ledger)

![image](https://user-images.githubusercontent.com/1618764/160558778-af6b4c7c-0853-4105-9e69-13900102152b.png)

**Comment by kyranjamie** [comment]
For time being, I've removed the checkmark and adjusted copy 

![image](https://user-images.githubusercontent.com/1618764/160599057-433dd57e-83db-4033-beba-15c139bf4ef1.png)

**Comment by landitus** [comment]
Looks good @kyranjamie!
