### ISSUE TITLE
Description for Transak should be reworded as its Live for US resident

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2338]
Transak went Live for the US resident on 29th of March 2022
The current description on Transak upon user selects 'Buy; indicated the below:
Non-US residents can purchase STX with credit card, debit card, or bank transfer via Transak.

We may need to tweak it indicating both US and non-US residents can purchase STX with credit card, debit card, or bank transfer via Transak.

<img width="366" alt="Screen Shot 2022-03-29 at 10 38 23 AM" src="https://user-images.githubusercontent.com/38872890/160637063-d7c5efba-b3b2-42f5-a829-39d6d75b88a1.png">

**Comment by fbwoolf** [comment]
This was merged into dev and can be tested once a new release PR is created.

**Comment by Eshwari007** [comment]
Test passed for the Transak description

<img width="380" alt="Screen Shot 2022-03-29 at 4 08 46 PM" src="https://user-images.githubusercontent.com/38872890/160698200-76b27786-ef37-4d21-af20-72938b0502e8.png">
