### ISSUE TITLE
Remove `capsize` library

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2344]
[Capsize](https://seek-oss.github.io/capsize/) is a library that uses pseudo elements to add negative margins to text elements in order to set the line height equivalent to the cap size of the font.

The current implementation uses this feature inconsistently, plus our Figma designs do not follow the same pattern. The result of this is that wallet text spacing differs from the designs, as the actual lineheight isn't adhered to.

**Comment by markmhendrickson** [comment]
Is this resolved now that #2808 is merged?

**Comment by kyranjamie** [comment]
Yep
