### ISSUE TITLE
Test: Known decimal balance is displayed correctly

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2356]
https://github.com/hirosystems/stacks-blockchain-api/issues/1139 highlights one wallet behaviour that would be nice to catch. 

The balance list displays tokens as a decimal, based on the `decimal` value returned from the API. 

We should add a test that the formatting of these values is as expected. E.g. `10.01` not `1001`

**Comment by andresgalante** [comment]
@markmhx Tim will be back in 2 weeks, if this can wait till then let's assign it and add it to the backlog?

**Comment by markmhendrickson** [comment]
Yep sounds good

**Comment by markmhendrickson** [comment]
@timstackblock to t-shirt

**Comment by andresgalante** [comment]
Add a tests for ALEX, NYC
