### ISSUE TITLE
Ledger: add missing transaction detail items

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2360]
Per @landitus's comment here https://github.com/hirosystems/stacks-wallet-web/pull/2242#issuecomment-1091794509

We need to add the missing transaction details to the transaction signing screen

![](https://user-images.githubusercontent.com/239215/162214369-c25cf92a-417c-4879-9796-f94ab51c5137.png)

**Comment by fbwoolf** [comment]
Adding link to comment with more details about what I missed to add: https://github.com/hirosystems/stacks-wallet-web/pull/2242#issuecomment-1091763519
