### ISSUE TITLE
Ledger: temporary graceful error for app transaction flow

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2362]
While we solve the issue with authentication and private keys verification we'd like to show a graceful error or message for early Ledger testers that try to transact with applications

**The graceful error message should show up**
- While connecting the wallet to an app. For ex. for [Stackxnft](https://stxnft.com/) when after clicking "Connecting Wallet".
- Onboarding through the app flow? We should show ASAP.

**Comment by landitus** [comment]
@kyranjamie Here's the proposal for the temporary error message. Made use of the generic error page we've designed a few weeks ago.
@markmhx @sjwhitely would you mind taking a look at the copy?

[Figma](https://www.figma.com/file/VQPOPkkrfVcf0BEd9kz3HZ/%232275---Ledger%3A-Onboarding-%2B-Transaction-signing?node-id=1203%3A30097)

<img width="1440" alt="Feature not available" src="https://user-images.githubusercontent.com/239215/163243943-0c29050d-33ab-4f84-ba09-6a4571efaa53.png">

**Comment by sjwhitely** [comment]
My edits: 

Feature coming soon...
You are trying to authenticate with a Ledger device, but this feature is not yet available. 

In the meantime, you can authenticate using Hiro Wallet for Desktop
If issues persist, please reach out to support@hiro.so

**Comment by fbwoolf** [comment]
> 
> In the meantime, you can authenticate using Hiro Wallet for Desktop If issues persist, please reach out to

I don't think this change is correct? The user is trying to use a web app so they would need to use the Hiro Wallet extension not the desktop wallet (software not hardware wallet).

**Comment by kyranjamie** [comment]
Yep, authentication means proving to an app that you own key X. The desktop wallet doesn't interact with any websites. 

Will work on this now

**Comment by sjwhitely** [comment]
Oops - my b! Misunderstood what was meant by software wallet
