### ISSUE TITLE
Can not fund wallet with ok coin

### ISSUE THREAD

**Issue by sovereignalmida** [blockstack/blockstack-app#2367]
Aloha trying to buy a nft and need to fund my wallet. 
clicked buy with Ok Coin ( already have an account with them)  the bridge opens and then redirects after showing buy page with an error saying not allowed to provide service. I am a US customer currently sitting in Portugal.  Ok Coin says it is a problem with Hiro wallet not them . help?

**Comment by markmhendrickson** [comment]
My understanding has been that Okcoin disallows purchases from any user who has registered their account in the US even when they're subsequently traveling overseas in another country.

However, are you saying that Okcoin support has indicated that you as a US-registered user _should_ be able to purchase while overseas? 

If so, we can contact their team for clarification.

**Comment by sovereignalmida** [comment]
This is precisely what I assumed however the customer rep said it was not an issue on their end.
I tried both via VPN and without. However when I am on their site - no VPN - I can buy crypto fine when logged into my account. IF they are blocking only the wallet fund then that is inconsistent.

**Comment by markmhendrickson** [comment]
I think the distinction here is that you can indeed buy STX via Okcoin on their regular site as a US user (either inside or outside of the US), but this particularly purchase flow from the wallet into their "instant buy and deposit" flow is restricted to only non-US users (i.e. users who have KYC'ed with identities from other countries and are accessing the flow from other countries as well).

This would explain the differences you see as well, though it's not technically a wallet problem but rather a question of how the availability supported for this particular purchase flow at this time.

**Comment by kyranjamie** [comment]
Closing as exchange specific
