### ISSUE TITLE
Remove old NFT counts (which user does not own anymore) off the Balance display + thumbnails?

### ISSUE THREAD

**Issue by Hero-Gamer** [blockstack/blockstack-app#2369]
Level 1: 
Dear Hiro teams/Stacks devs! Once I've sold out my NFTs or moved them all to another wallet, how can they not show up in my wallet anymore. It makes me feel so dizzy when I look at it!
<img src="https://user-images.githubusercontent.com/92864860/163595747-7acf1366-e0ce-4017-b07a-66b869d42bed.png" width="280px" />

Level 2: 
Can the thumbnails display the collection & tokens' picture?
**NFT token thumbnails ref: like on STXNFT.com**
https://stxnft.com/collections
<img src="https://user-images.githubusercontent.com/92864860/163595856-f17851b6-e2b5-4fa6-a75f-327b75ac92fb.png" width="200px" />

**Fungible Tokens thumbnail ref:** 
https://app.alexlab.co/token-list
<img src="https://user-images.githubusercontent.com/92864860/163596210-8a427ac7-a56b-459f-84cf-38bcd6b1bd7e.png" width="200px" />

Thanks a lot.
Regards,

**Comment by Eshwari007** [comment]
Level 1 has been addressed and tested.
Level 2 Shall I separate it out as an enhancement ticket @markmhx ?

**Comment by markmhendrickson** [comment]
We have an issue here for Level 2 already: https://github.com/hirosystems/stacks-wallet-web/issues/1028

**Comment by Hero-Gamer** [comment]
Nice one thanks for Lvl 1
