### ISSUE TITLE
Refactor create account drawer to toast and simplify tests

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2370]
The create account flow is causing problems with our integration tests. There is already a design issue to review this drawer and design it as a toast. The UX is odd atm. So, to get past failing integration tests, I am going to change it to a toast matching the ones we use in the wallet now. It will make it easier to swap out for a new design when it is ready. Also, we have several tests for creating/switching accounts which are redundant so I'm going to consolidate into only what is needed.

Related design issue:
https://github.com/hirosystems/stacks-wallet-web/issues/2321

These failing tests are blocking my open PR to upgrade Connect pkgs and they seem to be failing on dev too:
https://github.com/hirosystems/stacks-wallet-web/pull/2363

**Comment by Eshwari007** [comment]
Tested the issue on Pink Panther.Test Passed
