### ISSUE TITLE
Add API to request addresses

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2371]
Similar to Ethereum's `eth_requestAccounts`, the Hiro Wallet should provide a way to share account details that doesn't do auth, requiring signing of a JWT.

Related https://github.com/MetaMask/metamask-extension/pull/4703

**Comment by markmhendrickson** [comment]
Related discussions: https://github.com/hirosystems/stacks-wallet-web/discussions/2352 https://github.com/hirosystems/stacks-wallet-web/issues/1051#issuecomment-1099924181

**Comment by markmhendrickson** [comment]
Note how the equivalent MetaMask UI appears to preselect just the currently / previously selected account in the user's session:

<img width="380" alt="Screen Shot 2022-04-19 at 13 35 05" src="https://user-images.githubusercontent.com/28991/163994855-0cfed0be-ae81-4b7b-abb2-d888d2a85eb9.png">

@landitus we'll need a similar modal for the wallet to support this issue's functionality

Note that they have a second screen here that clarifies permissions, though I imagine we won't need one in our case since we can fit whatever guidance we need into just one screen (in which the user selects the accounts to share):

<img width="372" alt="Screen Shot 2022-04-19 at 13 36 44" src="https://user-images.githubusercontent.com/28991/163995187-587ad95b-0972-4ffd-86db-77df23580114.png">

**Comment by landitus** [comment]
Thanks @markmhx. I'll include this scenario as I work on https://github.com/hirosystems/stacks-wallet-web/issues/2355

**Comment by landitus** [comment]
> Note how the equivalent MetaMask UI appears to preselect just the currently / previously selected account in the user's session:

- Would the multiple account selection functionality just be available when the dApp requests the account details (this issue) and also when using the authentication methods? 
- Is selecting multiple accounts selection functionality a hardware wallet-specific feature? Why?

Trying to understand how the **Connect wallet** UX would evolve with this new method and if they should be treated as different UX patterns.

**Comment by markmhendrickson** [comment]
> Would the multiple account selection functionality just be available when the dApp requests the account details (this issue) and also when using the authentication methods?

Just when the app requests accounts with the new API for `requestAccounts` or similar.

> Is selecting multiple accounts selection functionality a hardware wallet-specific feature? Why?

Nope, multiple accounts can be selected regardless of whether the user is using a software or hardware wallet.

> Trying to understand how the Connect wallet UX would evolve with this new method and if they should be treated as different UX patterns.

I suspect that the app will show the same sort of "Connect wallet" option to users, regardless of whether they decide to trigger the new `requestAccounts` method or the old (and soon deprecated) authentication method.

Both are ways to connect the wallet. They just differ in A) whether the account(s) are verified or not, and B) whether only a single account or multiple account values can be returned to the app as a result.

**Comment by svntax** [comment]
Having something like `eth_requestAccounts` for stacks wallets would be very helpful for web games made in game engines like Unity and Godot. In many cases, reading the list of NFTs that an account owns is enough for a game to use those NFTs. I'm personally interested in adding Stacks wallet support in Godot, so I'd love to see this implemented.

**Comment by markmhendrickson** [comment]
@kyranjamie @mica000 putting this back on the board as WIP

**Comment by markmhendrickson** [comment]
Now inclusive of taproot addresses: https://github.com/hirosystems/wallet/issues/3372

- Stacks
- Native SegWit
- Taproot

**Comment by markmhendrickson** [comment]
Now supported via https://github.com/hirosystems/wallet/pull/3421
