### ISSUE TITLE
Ledger: Stacks app version is out of date message

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2376]
As surfaced [here](https://github.com/hirosystems/stacks-wallet-web/pull/2242#issuecomment-1091685941), we want to warn the user if the version of the Ledger Stack app is not up to date since it will not allow them to perform actions not supported by that version. In order to do this we propose the following:

- At the moment of connecting with Ledger, if the feature is incompatible, we block the flow and prompt the user to update the Stacks app on Ledger. _Ex. If the user tries to sign an Arbitrary message, we should block the flow as it's not supported now._
- If the feature does not require it, such as the authentication flow, we should be doing some proactive messaging to alert users without blocking any action (This will be followed up in another issue)

[User flows for **Transaction signing**](https://www.figma.com/file/o0VSeFzhYI2GgnDcX0NPmU/User-lifecycle-flow?node-id=882%3A1754), highlighting the new logic

<img width="851" alt="Screenshot 2022-04-20 at 15 01 08" src="https://user-images.githubusercontent.com/239215/164236356-299cfce4-be8a-4e91-9052-c0669c94416d.png">

**Comment by landitus** [comment]
Here's the design proposal: we are re-using the inline alerts pattern as we can detect the Stacks app version upon connecting

[Figma prototype](https://www.figma.com/proto/VQPOPkkrfVcf0BEd9kz3HZ/%232275---Ledger%3A-Onboarding-%2B-Transaction-signing?page-id=890%3A24396&node-id=890%3A24736&viewport=241%2C48%2C0.5&scaling=scale-down&starting-point-node-id=890%3A24736&show-proto-sidebar=1)

![Connect ledger - Error_ Stacks app version is outdated](https://user-images.githubusercontent.com/239215/164237459-685fbdcb-87f0-4c69-af52-ede07557532b.png)

- @kyranjamie @markmhx  lmkwyt
- @Eshwari007 I've updated the flows with this error [here](https://www.figma.com/file/o0VSeFzhYI2GgnDcX0NPmU/User-lifecycle-flow?node-id=882%3A1754)
- @sjwhitely Note we are adding another error message with further reading on our website

**Comment by markmhendrickson** [comment]
LTGM though be sure to capitalize "Live" in "Ledger Live" since it's a brand name. And we can just say "Ledger Live" instead of "Ledger Live app" me thinks.

**Comment by landitus** [comment]
Good catch @markmhx. I've fixed it!

**Comment by landitus** [comment]
This is ready for development @kyranjamie

**Comment by markmhendrickson** [comment]
Let's close this out in favor of functionality-specific messaging for when users need to upgrade their Stacks app to proceed with Ledger.
