### ISSUE TITLE
Style: Transaction UI horizontal padding disappears at wider window size

### ISSUE THREAD

**Issue by mcintyre94** [blockstack/blockstack-app#2391]
Repros in both Chrome and Firefox

I open a transaction using `openContractCall` in Stacks JS, a transaction window appears from the wallet extension. If I make this window wider then the horizontal padding disappears and the content ends up right against the edges, which I don't think is desirable. 

Is this intended/expected?

https://user-images.githubusercontent.com/1711350/165582555-11b40242-7de9-4662-8492-7a341261f02e.mov

**Comment by andresgalante** [comment]
Thanks for the report.

Even though I couldn't find it on the source code, there a condition to unset inline padding on min-width: 30em:

<img width="268" alt="Screen Shot 2022-04-27 at 20 58 27" src="https://user-images.githubusercontent.com/1832037/165649993-1d1fb10b-defe-42d8-baeb-17977c0e20e2.png">

This should be a really easy fix.

**Comment by mcintyre94** [comment]
Ah cool found it, I'll PR a fix :)
