### ISSUE TITLE
Fresh wallet (Nonce 0) with nonce gaps, incorrect nonce suggestion

### ISSUE THREAD

**Issue by Hero-Gamer** [blockstack/blockstack-app#2395]
Hi team, 

![InkedCase 02-A01_LI](https://user-images.githubusercontent.com/92864860/166056049-20b09d81-ca4d-4ac8-a3a0-e92a18b135ee.jpg)

**Case**
* Came across a user the other day, where his wallet was **fresh wallet with 0 nonce**. 
* He had pending txs, of 3, 4, 5, none of which were correct
* When I was helping him, his wallet was suggesting nonce 6 (after 2 days even apparently), which is incorrect. 
* I have seen a few cases like this where, even a very new wallet was suggesting wrong nonce with nonce gaps. 

**The only only explanation I can think of how this had happened ..**
* around 23rd April the mempool was very high, which led to his Nonce 0 & 1 & 2 low fee txs pending over 256 blocks therefore dropped off. 
* Left him nonce 3, 4, 5 pending still, at which point I helped him to send a Nonce 0 tx to fix it. 

**Issues & solution ideas I see**
Issue 1: * Fee estimation too low during  intense spike mempool congestion, causing tx to pend for over long, causing jammed wallets
_Solution ideas:_ 
1. better LIVE fee estimation when we have such intense spike mempool level? cc: @pavitthrap @saralab 
2. when there is network congestion, altho you can manually increasing fee, user would have no idea what to increase it to to get the tx pushed through, can the Hiro wallet display the latest LIVE fee level that can with high probability help the low fee pending tx succeed?

Issue 2:* Wrong nonce suggestion after even after Nonce gaps created, e.g. in his case, his has pending tx nonce 3, 4, 5, with nonce gap 0, 1, 2
_Solution ideas:_  shouldn't when sending a new tx at that moment, his wallet automatically **detects if he has nonce gap (s)** , and if yes, the wallet suggests Nonce 0 rather than attempting to add + 1 to his latest pending tx nonce 5?

_User said his Hiro wallet was suggesting default Nonce as 6:_
See here: https://discord.com/channels/893027129602740264/893028152127914004/967824450500329492 

_You can see the full conversation starting from here:_
https://discord.com/channels/893027129602740264/893028152127914004/967819581181820988

_Confirmation he was using Hiro wallet:_ 
https://discord.com/channels/893027129602740264/893028152127914004/968245063828242533

Thanks Team. 
Regards,

**Comment by markmhendrickson** [comment]
@Hero-Gamer Any chance you could send us the address here so we can investigate?

**Comment by Hero-Gamer** [comment]
> @Hero-Gamer Any chance you could send us the address here so we can investigate?

Here is the tx:
https://explorer.stacks.co/address/SP3KXQWSKS5A2WSSD76AB4Z7TZCQZPE3PQFGFPBPJ?chain=mainnet

**Comment by markmhendrickson** [comment]
cc @beguene ☝️

**Comment by beguene** [comment]
Everything looks fine to me
There is only 1 transaction initiated by the wallet owner 
https://explorer.stacks.co/txid/0x065a96f858fc061eb82ab5287c9ca1978653a83d885f86a2460cd4de1efba4b5?chain=mainnet
with nonce = 0
The next nonce should be 1 as returned also by the api
https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP3KXQWSKS5A2WSSD76AB4Z7TZCQZPE3PQFGFPBPJ/nonces
@Hero-Gamer Do they still have the problem in the web wallet ? The wallet should show nonce = 1 now.

**Comment by markmhendrickson** [comment]
cc @Hero-Gamer is this still an outstanding issue?

**Comment by Hero-Gamer** [comment]
* I am not hearing anymore from the user about this issue still existing. 

* I think it's probably more of a question and decision for your team to see if it's an actual problem. I am only passing on the oddity I came across when supporting users. 

* Personally speaking I don't have issue if you wanna close it, from the perspective of it's an odd problem probably difficult to identify therefore solve. And, it is not a very common issue that I come across. Probably just some edge case.

**Comment by markmhendrickson** [comment]
Thanks for the update. I'll close for now and we'll reopen if we see the same behavior reappear.
