### ISSUE TITLE
Create FAQ for arbitrary message signing

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2400]
Per https://github.com/hirosystems/stacks-wallet-web/pull/2350#issuecomment-1117101143

**Comment by sjwhitely** [comment]
@markmhx sounds good! When do you need this?

**Comment by markmhendrickson** [comment]
By early next week e.g. Tuesday 🙏

**Comment by sjwhitely** [comment]
@beguene "FAQ may not be worth it right now, at least this is not a blocker for the release. We already have a blog post and a tutorial." Gonna close this for now and we can re-open if needed!

**Comment by markmhendrickson** [comment]
@beguene do we need to remove the "Learn more" from the UI?

**Comment by beguene** [comment]
@markmhx I think we should still keep the 'Learn more'. It's currently linking to https://docs.hiro.so/build-apps/message-signing. Shall we link to the [blog post](https://www.hiro.so/blog/how-arbitrary-message-signing-works-in-the-hiro-wallet) instead ?

**Comment by markmhendrickson** [comment]
If we're keeping it, we should preferably link to a user-serving FAQ instead of a developer-serving resource like the docs or this blog post, since we can presume that most users who click this link want to learn just what they're doing by signing, not how to integrate into apps.
