### ISSUE TITLE
Write generic instructions to buy and withdrawal STX

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2407]
[As we surface all the exchanges that offer STX](https://github.com/hirosystems/stacks-wallet-web/issues/2251), we want to provide instructions to our users on what are the required steps to buy and then withdraw STX to the wallet. The instructions will be generic, meaning they should fit any exchange. On the implementation, we'll change some basic words/variables to personalize the content a bit more (for ex. The icon, the name of the exchange, the accounts key and links to the exchange)

<img width="1103" alt="CleanShot 2022-05-03 at 16 44 03@2x" src="https://user-images.githubusercontent.com/239215/167427141-8aa7b81f-ce79-456e-b541-9e3d8579f6fe.png">

**Comment by sjwhitely** [comment]
@landitus draft here for you! Feel free to leave comments: [](https://docs.google.com/document/d/1UTvOCmXXpgm_niH83jZUZBgvLNpuqcQZHbaO8oCBXco/edit)

**Comment by sjwhitely** [comment]
@landitus [https://www.notion.so/hiropbc/Buying-STX-from-Exchange-cb51b96c4003452eb306dffc7bce16bd]

**Comment by sjwhitely** [comment]
https://www.notion.so/hiropbc/Buying-STX-from-Exchange-cb51b96c4003452eb306dffc7bce16bd

**Comment by andresgalante** [comment]
www.hiro.so/wallet-faq/how-do-i-buy-stx-from-an-exchange
