### ISSUE TITLE
Passing incorrect function arg in transaction fails silently

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-app#2409]
When you are constructing a transaction and you pass an incorrect function argument, the wallet will appear to have successfully broadcast the transaction, when in reality it fails because the function args are incorrect. This is very hard to debug, and it'd be better if the wallet provided some failure state.

This is the response from the api when the tx fails:
```ts
{
  error: 'transaction rejected',
  reason: 'BadFunctionArgument',
  reason_data: { message: 'TypeError(OptionalType(UIntType), UIntType)' },
  txid: 'd765af4f2db445798cc92d4f8048f0173614a4656c547a86cbb3342f271de127'
}
```

However it's never possible to see this in the wallet, or in the payload response from the tx request in the dapp that started this.

**Comment by kyranjamie** [comment]
Has the API response always been like this? Our code uses the presence of a `txid` to mean successful transaction, so I'm not surprised this happens, but how have we only just found out 🤷🏼 

https://github.com/hirosystems/stacks-wallet-web/blob/a77b821070dfd4f7f7103f1f9a4745190e20bdde/src/app/store/transactions/transaction.hooks.ts#L150-L157

See https://github.com/hirosystems/stacks-wallet-web/pull/2410, I'd imagine this should fix it, though haven't had time to set up failing test environment to try yet.

**Comment by markmhendrickson** [comment]
@aulneau mind providing an example of incorrect arguments that QA can use to test here? 🙏

**Comment by Eshwari007** [comment]
@aulneau provided input that the best (easy) way to test the issue would be by tweaking our test app with something that is like a uint clarity value to a string clarity value.

**Comment by timstackblock** [comment]
Once a fix to the code has been made the team has handled similar types of issues like this in the past by adding the contract to the test app similar to the screen shot below. This contract call will fail when the contract call is executed and we should be able to verify that there is an actual error and not a silent fail.




![Image](https://user-images.githubusercontent.com/49165468/169539672-951af222-7f08-4be2-ace9-8fc98d6fcb8a.png)




![Image](https://user-images.githubusercontent.com/49165468/169539203-a2a1883f-683e-4936-88fd-b83298af8406.png)
