### ISSUE TITLE
Revamp Buy page

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2422]
Based on the work to be done for https://github.com/hirosystems/stacks-wallet-web/issues/2251, we want to port this new design for displaying the buying options and replace the **Buy** page. The design is basically identical, but for the top header which reflects the Wallet navigation: top left has a back button and top right has the menu dropdown.

[Figma](https://www.figma.com/file/mpfjDNidnBwUUoCz8r1Wkx/%232251---Fund-account?node-id=310%3A62798)

<img width="1440" alt="Wallet - Buy" src="https://user-images.githubusercontent.com/239215/168815364-dc7d4405-3e89-4f04-ae32-0fc91ccccb1c.png">

<img width="1440" alt="Wallet - Fund account" src="https://user-images.githubusercontent.com/239215/168815391-207ced37-6dbb-40e3-b9bf-7a0155bff10a.png">

---

**Responsive**
Like the current **Buy** page, it can be displayed inside the extension widget. 
- Most of the design flows from the adapting the layout to a narrower size
- Additionally, there are special tweaks to adapt the content to the smaller form factor and remove unnecessary clutter: margins are reduced, illustration is removed and the heading text sizes and alignments change, the main header copy is abbreviated, the description text color changes to match the rest of the pages.

<img width="1440" alt="Wallet - Buy" src="https://user-images.githubusercontent.com/239215/168851433-1fecbca9-b095-45c7-bf72-ee892fba3e88.png">

<img width="1440" alt="Homepage (sm)" src="https://user-images.githubusercontent.com/239215/168815401-396324c4-b629-42c8-936a-a3a710d37242.png">

**Comment by fbwoolf** [comment]
@markmhx @landitus are you thinking the button that leads here is still `Buy` even though all options are not to buy? I am considering how we might want to change the route name (currently it is `/buy`). Do we want the route the same for both, `/fund-account`? Or, should these be two different routes rendering the same feature/components?

EDIT: Possibly `/get-stx`? After thinking about it, it should prob use one route bc there are multiple places currently routing to the buy page. `/fund-account` is likely best?

**Comment by markmhendrickson** [comment]
`/fund` is perhaps the most succinct and broad route name we could use going forward, and perhaps "Get STX" for the label of the home button?

I'd also suggest we update the icon since a plus symbol (+) isn't very illustrative. But that can be a separate enhancement:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/28991/169232673-c73b4c56-0fc5-4d9b-9b65-6f316bb5feb0.png">

**Comment by landitus** [comment]
> I'd also suggest we update the icon since a plus symbol (+) isn't very illustrative. But that can be a separate enhancement:

I'd like to try a few things too regarding button order, colors, and icons as you mention. We should do a separate issue, for sure.

**Comment by fbwoolf** [comment]
> 
> I'd like to try a few things too regarding button order, colors, and icons as you mention. We should do a separate issue, for sure.

Ok, I can make a separate enhancement issue for this today. Thanks for the feedback. 👍

**Comment by fbwoolf** [comment]
@landitus couple of questions on this:

1. Should we alphabetize the providers?
2. Should the layout always be constrained to 4 providers across?

EDIT: 3. The MoonPay icon seems to be the only one smaller than 24x24, can you add a box around it so it matches the others? Or, are you ok if it enlarges it slightly?

![Screen Shot 2022-05-21 at 3 48 47 PM](https://user-images.githubusercontent.com/6493321/169668499-c79d172d-e328-43ad-9219-801887263c72.png)

**Comment by markmhendrickson** [comment]
I'd suggest starting the provider list with the same set and custom order of those we currently show in the wallet (Moonpay, Transak then Okcoin), then show and alphabetize the rest from there.

**Comment by fbwoolf** [comment]
Note that Okcoin is always listed before Transak in the design comps ...might change just so QA doesn't flag it on the PR during testing ...and alphabetize.

**Comment by landitus** [comment]
> Should we alphabetize the providers?

I've updated the Figma with what we've decided in this thread

>  Should the layout always be constrained to 4 providers across?

No. I would adapt the rows to the screen width. In a medium breakpoint we could fit 3, and so on.

> EDIT: 3. The MoonPay icon seems to be the only one smaller than 24x24, can you add a box around it so it matches the others? Or, are you ok if it enlarges it slightly?

Gotcha. Made MoonPay larger so it fits with the rest. Thanks!

**Comment by fbwoolf** [comment]
Moving this to QA, but I will still need to do a bit of work after this is content is available next week: https://github.com/hirosystems/stacks-wallet-web/issues/2407 ...right now the links go to a page that doesn't exist.
