### ISSUE TITLE
Revamp Receive screen

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2423]
Based on the work to be done for https://github.com/hirosystems/stacks-wallet-web/issues/2251. The Receive screen is now actionable from multiple screens: from the onboarding funding step, the Buy page and the homescreen. In order to present it as a quick action, it makes sense to move it to a modal.

[**Figma**](https://www.figma.com/file/mpfjDNidnBwUUoCz8r1Wkx/%232251---Fund-account?node-id=310%3A57331)

**Modal component**
This modal should follow the existing modal component behavior for scrolling and design styles (background, shadow, etc). Only exception is the new title position, aligned with the close button.

<img width="1440" alt="Receive modal - 1" src="https://user-images.githubusercontent.com/239215/169090814-e37ecba2-c8f1-498c-a0be-4474b823346b.png">

<img width="1440" alt="Receive modal - 2 - example" src="https://user-images.githubusercontent.com/239215/169090396-58a08bf7-a5a0-4e31-82a3-69744dc82eaa.png">

![Image](https://user-images.githubusercontent.com/239215/169089728-c88b3b53-4712-4e47-9831-678bee5e6450.png)

**Responsive**
When presented on the widget, the modal is adapted to a screen. The headings and spacing should be matched to how pages are displayed on the widget. The QR is reduced in size to prevent internal scrolling.

![Image](https://user-images.githubusercontent.com/239215/169089782-781a5dd5-5cae-4776-a3fe-b09dabcfc844.png)

**Demo**
[Check the demo full size](https://www.figma.com/proto/mpfjDNidnBwUUoCz8r1Wkx/%232251---Fund-account?page-id=220%3A27927&node-id=310%3A61672&viewport=96%2C-3800%2C0.5&scaling=min-zoom&starting-point-node-id=310%3A57331)
[Check the demo on the widget](https://www.figma.com/proto/mpfjDNidnBwUUoCz8r1Wkx/%232251---Fund-account?page-id=220%3A27927&node-id=396%3A55534&viewport=96%2C-3800%2C0.5&scaling=min-zoom&starting-point-node-id=310%3A51033)

**Comment by fbwoolf** [comment]
@landitus the way our app is setup the modal popup in full page is seen as a drawer in the extension popup, is that ok for this?

**Comment by fbwoolf** [comment]
Another question on this, what do you want to have happen in the UI when the `Copy address` button is clicked?

**Comment by fbwoolf** [comment]
This is what it looks like in the ext drawer:

![Screen Shot 2022-05-25 at 3 18 08 PM](https://user-images.githubusercontent.com/6493321/170359988-d116ae4a-37e9-43c6-a8d6-725330bd16d2.png)

**Comment by landitus** [comment]
> @landitus the way our app is setup the modal popup in full page is seen as a drawer in the extension popup, is that ok for this?

Yes :)

**Comment by landitus** [comment]
> Another question on this, what do you want to have happen in the UI when the Copy address button is clicked?

I believe we could display a toast with the message: Address copied to clipboard

**Comment by landitus** [comment]
> > @landitus the way our app is setup the modal popup in full page is seen as a drawer in the extension popup, is that ok for this?
> 
> Yes :)

This doesn't change the **Receive** page behavior: that one will look like a regular page, right?

**Comment by fbwoolf** [comment]
> This doesn't change the **Receive** page behavior: that one will look like a regular page, right?

I am not sure I understand this question, the issue I'm working on is to refactor the current receive page into a modal, correct? It will be a popup modal in full page and a drawer in the extension, always. So, when you ask about `that one`, what are you referring to?

**Comment by landitus** [comment]
[My original idea](https://user-images.githubusercontent.com/239215/169089782-781a5dd5-5cae-4776-a3fe-b09dabcfc844.png) was to show it as a page in the extension, but I see your point that all modals get to be drawers in the extension. So it's fine by me! Let's do it and I'll review it

**Comment by fbwoolf** [comment]
@Eshwari007 this was merged into my branch refactoring the buy page into the new fund page, so it can be tested there, thx.
