### ISSUE TITLE
Adjust copy in Welcome screen

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2425]
Based on the work to be done for https://github.com/hirosystems/stacks-wallet-web/issues/2251. The usability tests showed some of the concepts and terminology can be confusing to users. The concept of "Stacks account" is never referred back again. So we opted to streamline and change it to "Wallet".

[**Figma**](https://www.figma.com/file/mpfjDNidnBwUUoCz8r1Wkx/%232251---Fund-account?node-id=310%3A52533)

<img width="1440" alt="5 - 1 - Splash screen" src="https://user-images.githubusercontent.com/239215/169094695-cba63a59-ef73-412b-adbd-168dfd9fac98.png">
<img width="1440" alt="5 - 2 - Splash screen example" src="https://user-images.githubusercontent.com/239215/169094705-92350dcc-9fc8-4af8-81ae-979c31249d65.png">

**Comment by fbwoolf** [comment]
@Eshwari007 this was merged into dev to fix an integration test there, so please test it on dev, thx.
