### ISSUE TITLE
Dim completed steps on the home screen

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2426]
Based on the work to be done for https://github.com/hirosystems/stacks-wallet-web/issues/2251. 

While reviewing the onboarding flow, we discussed the Next steps have a lot of visual weight on the home screen and they definitely don't have a very clear differentiation between completed and to-do steps. @eugeniadigon suggested we could dim the completed steps.

[**Figma**](https://www.figma.com/file/mpfjDNidnBwUUoCz8r1Wkx/%232251---Fund-account?node-id=310%3A62784)

**Changelog**

- The CTA for step 2 changes to “Add funds”
- The CTA for step 2 changes to “Get STX”
- For completed steps, the image is replaced with a dimmed version 
- For completed steps, the title color is lighter: text-subdued

<img width="1440" alt="Next steps - 1" src="https://user-images.githubusercontent.com/239215/169353507-e323c053-97d9-4d29-afc9-3a10595bae6f.png">

<img width="1440" alt="Next steps - 2" src="https://user-images.githubusercontent.com/239215/169353545-8df8e2fb-c703-4d9f-a70b-ec91f7434abc.png">

---

### Responsive
The screen has some adaptations, like simpler illustrations, that also are dimmed upon completion.

**Changelog**
- Completed steps no longer have a check replacing the image. Instead, the image is dimmed.

<img width="1440" alt="Next steps - 3" src="https://user-images.githubusercontent.com/239215/169353577-d951b5a3-7347-4a3c-8110-00e990313d6d.png">
<img width="1440" alt="Next steps - 4" src="https://user-images.githubusercontent.com/239215/169353600-ce0e21d1-c9a1-4e6f-998e-ff53d5b9a29a.png">

**Comment by fbwoolf** [comment]
~~@landitus working on this, the changelog list says to change step #2 twice ...which is correct? `Add funds` or `Get STX`?~~

**Comment by fbwoolf** [comment]
Nvm on ^ that, I see the diff now.

**Comment by Eshwari007** [comment]
Test passed.Moving it to merge
