### ISSUE TITLE
Support message signing with Ledger hardware wallets

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2433]
The message signing feature, just released, hasn't been implemented for Ledger yet. 

A message signing flow should be created, following steps similar to transaction signing

**Comment by markmhendrickson** [comment]
@landitus Will this require significant design changes to support, or is the flow similar to one we've already designed for Ledger?

**Comment by landitus** [comment]
Seems it will be straightforward as we can use the Tx signing flow as a blueprint. It's basically the same UI.

We could go straight to implementation without mocks if needed, but I would still take some time to add this new flow to the wallet flow maps and check if something tricky appears.

**Comment by landitus** [comment]
I've mocked the happy path, and indeed we are going to use the same UX/UI as the TX signing with ledger. 

- I assumed we need a confirmation screen where the user will confirm on Ledger (just as the TX signing)
- There are some CTA and Heading copy updates to adapt it to Ledger and that's mostly it!

**Links**
- [Figma](https://www.figma.com/file/izUQG45KFWOwMkwxxT6a3A/%232433---Ledger%3A-Message-Signing?node-id=1%3A4143)
- [Prototype](https://www.figma.com/proto/izUQG45KFWOwMkwxxT6a3A/%232433---Ledger%3A-Message-Signing?page-id=0%3A1&node-id=1%3A4143&viewport=-2804%2C327%2C0.5&scaling=scale-down&starting-point-node-id=1%3A4143&show-proto-sidebar=1)
- [Flows](https://www.figma.com/file/o0VSeFzhYI2GgnDcX0NPmU/User-lifecycle-flow?node-id=849%3A600)

https://user-images.githubusercontent.com/239215/175544832-a53b3ca5-ae93-4bfa-852c-e63f13160be7.mp4

![Image](https://user-images.githubusercontent.com/239215/175544999-1571395c-6d71-4f87-b181-99f4e4592739.png)

**Comment by kyranjamie** [comment]
@markmhx Note that the Ledger only supports text-based message signing. We will need to work with Zondax to implement the structured data signing feature.
