### ISSUE TITLE
Sign demo failed on verification

### ISSUE THREAD

**Issue by zhigang1992** [blockstack/blockstack-app#2435]
The code copied from 

https://www.hiro.so/blog/how-arbitrary-message-signing-works-in-the-hiro-wallet

```typescript

        const message = "Sign in to SSO";
        sign({
          message: message,
          onFinish: async (data) => {
            const isValid = verifyECDSA(
              hashMessage(message),
              data.publicKey,
              data.signature
            );
            console.log(isValid);
          }
        });

```

is returning false rather than true.

Here is a reproducible example

https://codesandbox.io/s/signature-verification-failed-4zx4zo

https://4zx4zo.csb.app/

**Comment by markmhendrickson** [comment]
@kyranjamie @Eshwari007 @timstackblock can one of you reproduce this issue to see if we have a bug that needs fixing here?

**Comment by kyranjamie** [comment]
Taking a look. Expect this is accurate.

I wonder if we jumped the gun changing the signature format. The documentation/blog post is, as a result, wrong. Further, I wonder how this impacts the Ledger message signing feature, this might need to change too. All of this feedback about signature type, byte order would've been great _prior_ to releasing the feature, ideally we should've done a developer preview of message signing too.

To reform the signature, we can do this, which could also be exposed as a method via stacks.js:

```ts
const { r, s } = parseRecoverableSignature(data.signature);
const sig = new secp.Signature(hexToBigInt(r), hexToBigInt(s));
console.log('Is signature valid', secp.verify(sig, hashMessage(message), data.publicKey));
```

I'm sure there's a cleaner way to do this with nobel, suggestions welcome.

cc/ @janniks @aulneau @pradel @MarvinJanssen

**Comment by kyranjamie** [comment]
We've updated the instructions on the blog post, thanks for flagging
