### ISSUE TITLE
Redesign action buttons on home page (buy button)

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2436]
As part of refactoring the buy page, we need to look at changing the action button and route that leads to the new fund page from the user home page.

Relevant comment on the original refactor issue:
https://github.com/hirosystems/stacks-wallet-web/issues/2422#issuecomment-1131315665

**Comment by markmhendrickson** [comment]
Is this resolved now?

**Comment by fbwoolf** [comment]
No, we still need to revisit if we want the button to say `Buy` or `Get STX`. I believe @landitus wanted to rethink the UX/UI with all three action buttons on the homepage.

**Comment by landitus** [comment]
Indeed. I should take this on and forward
