### ISSUE TITLE
Signing message screen does not respect line breaks

### ISSUE THREAD

**Issue by pradel** [blockstack/blockstack-app#2437]
When asking a user to sign a message with line breaks, the line breaks are not shown in the UI. This makes it really hard for users to understand long messages.
![Screenshot 2022-05-19 at 18 20 04](https://user-images.githubusercontent.com/5749437/169349917-476a41a9-bd12-4a34-a350-8dc2201bc69a.png)

You can see that in metamask the line breaks are respected which makes the message more readable.
![Screenshot 2022-05-19 at 18 23 13](https://user-images.githubusercontent.com/5749437/169350269-348d8784-7066-458b-b557-78ec807d4705.png)

**Comment by sjc5** [comment]
This is arguably a user safety issue. Any updates on this one?

**Comment by fbwoolf** [comment]
@beguene is this one you are fixing in your current work?

**Comment by beguene** [comment]
@fbwoolf No, this is not included in my PR.
