### ISSUE TITLE
Wallet doesn't respect currently auth'd account when requesting message signing

### ISSUE THREAD

**Issue by zhigang1992** [blockstack/blockstack-app#2438]
Given user have two or more account,

When connected to the site with second account,

But wallet extension is on first account.

Then the sign prompt with be on first account rather than second.

https://codesandbox.io/s/signature-verification-failed-forked-d8dgcg

https://d8dgcg.csb.app/

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1057756/169355681-c13483be-eff0-4a4f-be7a-ccf9ebbd7b79.png">

is this expected?

**Comment by kyranjamie** [comment]
Thanks for reporting. We should define what the exact behaviour is here. 

Right now, we don't pass an STX address argument, but we probably should cc/ @landitus @beguene

**Comment by markmhendrickson** [comment]
Perhaps the app can pass an optional address, and if not passed, the wallet displays an account picker before displaying the message for signing? Or we make the header address (top left) toggle-able to other accounts somehow?

**Comment by beguene** [comment]
I think letting the dApp pass the STX address as an argument makes for a better UX. The user can then just click to sign.
Ideally we should track in the wallet which account was last loggedIn for that dApp.

**Comment by kyranjamie** [comment]
@zhigang1992 can you confirm this is fixed? I just tested and it defaults to currently auth'd account, but allows signing from any if the `stxAddress` property is passed.

**Comment by zhigang1992** [comment]
Yeap, this is fixed now. thank you very much!
