### ISSUE TITLE
Public key returned with signed payload seems incorrect

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-app#2440]
When building out the messaging signing features in `micro-stacks`, i wanted to export some verification utils for folks to use, and I noticed that the public key recovered from the signature differs from the public key that is returned via the wallet. Here is a test case I made from the wallet:

https://github.com/fungible-systems/micro-stacks/blob/main/src/connect/message-signing/verify.test.ts

```ts
// from the wallet
const payload = {
  signature:
    '007db2f251643ff11493ae377db2581a55b5dcce11a9b79becc177dc97a2fb6932076bd197a8e3772eab317d95a1c78f60adfcbf8e1512357c3f95d6606ad7dd29',
  // seems wrong
  publicKey: '035b08fd4d14786187f51a3360864665fa437a9ad22bbdf7ae716d4599f26943a7',
};
```

and you can see here that I'm forced to use the public key from the signature: https://github.com/fungible-systems/micro-stacks/blob/main/src/connect/message-signing/verify.ts#L14

Curious if I've done something incorrect in my implementation, or if the wallet is returning something erroneous. It'd be cool if there were tests in `@stacks/connect` to compare against.

**Comment by aulneau** [comment]
I've added one more test to try and replicate how the wallet is signing the messages -> https://github.com/fungible-systems/micro-stacks/pull/96/files#diff-9e6ad0f1b082c7bb148fde26f13b9eedf6c899c60b84c6db319f903823807a26R71

**Comment by aulneau** [comment]
disregard :~) forgot to prefix my messages.

**Comment by kyranjamie** [comment]
I'm relieved to hear 😅  

@janniks, and I were wondering whether the wallet should even return a public key if it's included in the signature. Convenient, maybe, but also duplicate 🤔
