### ISSUE TITLE
improve the "Show hash" interactivity

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2441]
The _show hash_ toggle functionality could be improved. 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1618764/169475855-1d8c2b02-9711-473d-b463-9e255d65a2b8.png">

Some suggestions: 

- **Increase the click target**. Right now, only the 16x16px arrow box is clickable. The whole row should be clickable.
- **Make accessible**. It's a `div` and should be a `button`. It can't be accessed with keyboard navigation. 
- **Interactive states** Hover/focus states are missing.

cc/ @landitus @beguene

**Comment by markmhendrickson** [comment]
@kyranjamie can we close this as completed and released?

**Comment by kyranjamie** [comment]
These changes are in the unreleased PR
