### ISSUE TITLE
Add option to open wallet in a new tab

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2442]
Right now it's not obvious users can open the wallet the in a new tab as it's a right option click from the extension icon. We should add an option on the wallet UI

**Comment by DevRishiJain** [comment]
Can this be assigned to me?

**Comment by markmhendrickson** [comment]
This one has actually been resolved already with a new menu option:

<img width="402" alt="Screenshot 2023-05-08 at 07 18 18" src="https://user-images.githubusercontent.com/28991/236810569-95609538-b865-456b-9df0-a859684353f0.png">
