### ISSUE TITLE
Hash displayed in wallet for signed message is incorrect

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-app#2443]
Was pulling my hair out trying to figure out why my hashes were different, yet was able to validate the signatures lol

https://github.com/hirosystems/stacks-wallet-web/blob/23d9d9ac388ecf54f570be93f0b909cc662f0b2e/src/app/pages/signature-request/components/message-box.tsx#L24-L27

this bit here is incorrect, should be using the shared hashMessage function.

cc @kyranjamie @beguene

**Comment by aulneau** [comment]
additionally, i think they payload the wallet sends back should send the hash to the client too. what do you think @kyranjamie?

**Comment by kyranjamie** [comment]
Returning the hash makes sense too
