### ISSUE TITLE
Ledger : Issue with 'Hiro wallet wants to connect 'pop up box

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2447]
User testing Ledger with web wallet on Windows 11 
PR:https://github.com/hirosystems/stacks-wallet-web/actions/runs/2353152234

The screenshot below shows an additional popup on the left-hand side with ledger flow when the user tests the ledger (Is this an expected design)
The reason is that the popup box looks very plain and isn't complying to the design stands of Hiro ledger onboarding screens
Issue 1:  The user is not provided with any instruction if they should select Nano S (or not) on the left popup dialogue box

Issue 2: The user can only move to the next screen upon selecting Nano S from the left popup box which will then only highlight the Connect box thus allowing the user to continue

![2022-05-22 (1)](https://user-images.githubusercontent.com/38872890/169845009-4ac09f9c-8960-4428-a519-44bc506609f1.png)
![2022-05-22](https://user-images.githubusercontent.com/38872890/169845155-c90d8541-8667-494b-a487-382168500747.png)

**Comment by markmhendrickson** [comment]
This is expected behavior since we can't customize the popup on the left. It's a native browser UI component.
