### ISSUE TITLE
Ledger: User cannot scroll down or see anything on the preview screen

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2453]
PR:refs/pull/2242/merge
The user is stuck at the screen below and cannot scroll to  see any of the data 

<img width="581" alt="bug1" src="https://user-images.githubusercontent.com/38872890/170326999-7c5e8b7e-badc-4d89-87f6-5414c6733429.png">

**Comment by timstackblock** [comment]
@kyranjamie I still see this issue present

**Comment by kyranjamie** [comment]
Unable to replicate. It opens in a new tab on the send page.

I did notice another issue, though, that when landing directly on the send page, there are no assets to pick from 0️⃣

**Comment by fbwoolf** [comment]
I can repro this even in the new tab ...I can't scroll. Also, same as assets (likely) the nonce isn't setting in the form so the button is disabled until you click on `Edit nonce`. I will take on fixing both of these so going to move this back into development.

![Screen Shot 2022-06-14 at 2 12 47 PM](https://user-images.githubusercontent.com/6493321/173674492-96ee1530-f122-46ba-8918-c3189053bcea.png)
