### ISSUE TITLE
Ledger:Multiple transaction on wallet causing nonce issue

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2454]
PR:refs/pull/2242/merge

Here is a video of the bug, the nonce issue happens at the end around the 8 min mark. Users have seen this happen 2 times but it doesn't happen every time.
<img width="789" alt="bug2" src="https://user-images.githubusercontent.com/38872890/170327719-193fa0c4-0a5a-4c45-ac0d-134fdd6647f2.png">
https://screencast-o-matic.com/watch/c3hT2cVrJPw

**Comment by markmhendrickson** [comment]
By "Users have seen this happen 2 times", do you mean you've seen it twice or you've seen others report this as well?

**Comment by Eshwari007** [comment]
@timstackblock mentioned that he has seen this issue repeated twice while testing ledger with web wallet

**Comment by Eshwari007** [comment]
I was able to reproduce the nonce conflict when I was trying to submit two tx back to back of non-STX tokens as well.
<img width="1354" alt="Screen Shot 2022-05-27 at 2 24 17 PM" src="https://user-images.githubusercontent.com/38872890/170769101-e21e531b-8040-441e-9fc9-f44d68289c0b.png">

**Comment by fbwoolf** [comment]
@Eshwari007 you for sure can't repro this in prod or on the dev branch? It is ledger branch specific?

**Comment by fbwoolf** [comment]
I ask bc I did make some changes to how tx form data is managed in state but it was only merged into the ledger branch.

**Comment by fbwoolf** [comment]
Also, is this only happening when you use ledger to do the tx or does it just happen on the branch in general with any tx?

**Comment by fbwoolf** [comment]
This doesn't appear to be happening with my software wallet.

**Comment by fbwoolf** [comment]
Scratch that, I do see this with my software wallet ~~but only when sending non STX tokens.~~ I'll take a look at this.

**Comment by fbwoolf** [comment]
Ok, this is interesting, I just reproduced this in our prod wallet but the tx just fails silently rather than showing the toast w/ nonce error. I can clearly see the nonce is not updating right away so `currentAccountNonceState` must not be working.
