### ISSUE TITLE
Ledger: Preview button is disabled when tx is transferred between two accounts

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2456]
PR:refs/pull/2242/merge
Windows machine

User switches Account  2 under ledger -web wallet and copies the address
User then goes to Account 1 to send STX to Account 2
User notices that the Preview button is disabled, despite having address, memo, and fee selection
User then edits the nonce and notices the Preview button is enabled in the background
User returns to the foreground of the web wallet and the Preview button is now enabled.

Preview button should be enabled without editing nonce

![2022-05-25 (5)](https://user-images.githubusercontent.com/38872890/170381527-ec81ccc1-1208-4515-bfcf-243bc6db3b25.png)
![2022-05-25 (4)](https://user-images.githubusercontent.com/38872890/170381546-aa0726cd-a7a8-4423-a1eb-62e6b0784033.png)
![2022-05-25 (6)](https://user-images.githubusercontent.com/38872890/170381557-4bbe682b-cfc1-4761-b667-5356c5c168e3.png)
![2022-05-25 (7)](https://user-images.githubusercontent.com/38872890/170381568-99a50ddf-fefe-4a76-b68e-4e074ffd0e49.png)

**Comment by markmhendrickson** [comment]
Is this only the case with Ledger or also software mode?

**Comment by Eshwari007** [comment]
> Is this only the case with Ledger or also software mode?

cc @timstackblock

**Comment by Eshwari007** [comment]
@markmhx Just with web wallet while testing it with ledger

**Comment by fbwoolf** [comment]
This is likely related to the nonce issue if it is `undefined` it will cause the Preview button to be disabled until it is defined. It seems like something is working with loading the nonce? I will look.

**Comment by fbwoolf** [comment]
This doesn't seem to be happening with a software wallet, so I'm going to test with a ledger now.
