### ISSUE TITLE
signStructuredData not in line with SIP018 specification

### ISSUE THREAD

**Issue by beguene** [blockstack/blockstack-app#2460]
See https://github.com/hirosystems/connect/issues/225#issue-1245926927

As part of this task, we need to make sure that all the signatures used during the signing flow are in RSV format.

References
https://github.com/stacksgov/sips/pull/57
https://github.com/hirosystems/stacks.js/pull/1269
https://github.com/hirosystems/connect/issues/225

**Comment by MarvinJanssen** [comment]
FYI: https://github.com/stacksgov/sips/pull/57#issuecomment-1140622966

The structured data prefix has been changed to make sure that SIP018 messages can absolutely never be valid transactions.
