### ISSUE TITLE
intermittent long login delays

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/blockstack-app#2466]
Using Firefox 100.0.2 64 bit on ubuntu-based Pop!_OS
With my wallet after a long time it logs out, then I have noticed I cannot log back in on **mainnet** with my saved password, and for extended periods of time.  The login spinner just turns for a very long time (minutes).
Then after failing/quitting, I tried logging into **testnet** and it suceeded very fast - less than 10 seconds. 
Then I was able to switch to mainnet.  This problem is very annoying as it happens quite often.  

**edit: I just locked the wallet and tried to log back in. I waited _in excess of 4 minutes and it failed to login_.
Then I switched to _testnet and it logged in in 6 seconds_, and then I was able to switch to mainnet.**

**Comment by fluidvoice** [comment]
Is there logging happening anywhere I can see what's going on during the login process?
How to debug this?  
Should there be a way to enable debug mode - say a UI button or env var that can be set to enable seeing logging?

**Comment by kyranjamie** [comment]
If you encounter this problem again, can you try restarting Firefox completely and seeing if this helps. 

I wonder if the mainnet/testnet switching has any impact at all, and the change in behaviour was simply coincidence. Afaict there's no sign in logic that changes based on network. We've had many reports of slow sign ins with Firefox. Out of curiosity, what are the specs of your machine?

There is no logging available for this unless you create a build and add it yourself.

**Comment by fluidvoice** [comment]
**EDIT: err It's not as reproducible as I thought. I just restarted the browser again and now it logged in within 14 seconds.**
I will test some more n see how it goes. This problem has been going on intermittently for quite some time... many weeks/months.


> If you encounter this problem again, can you try restarting Firefox completely and seeing if this helps.

no restarting doesn't help. 
New browser start with no other open tabs.

> I wonder if the mainnet/testnet switching has any impact at all, and the change in behaviour was simply coincidence. Afaict there's no sign in logic that changes based on network. We've had many reports of slow sign ins with Firefox. Out of curiosity, what are the specs of your machine?

it's repeatable. Not a coincidence.
My notebook is a Core i5 quad-core 8 threads with 20GB RAM (4gb used)

> 
> There is no logging available for this unless you create a build and add it yourself.

**Comment by fluidvoice** [comment]
well testing it a lot it's very random. Sometimes restarting the browser works sometimes not.
I wonder if there is some server-side resource with variable load that could be causing this?
more often than not, restarting the browser works, or logging into Testnet first then switching to Mainnet.
I wonder if it could be a timing or latency issue. I'm located in Brazil.

**Comment by kyranjamie** [comment]
> I wonder if there is some server-side resource with variable load that could be causing this?

You wonder correctly. The `@stacks/wallet-sdk` library interacts with Gaia, so it's possible that causes the issue (though, anecdotal reports also suggest it's predominantly a Firefox problem)

**Comment by kyranjamie** [comment]
We've recently made improvements that have hopefully fixed this issue. Please let us know if you encounter it again.
