### ISSUE TITLE
Wallet is not respecting anchor mode

### ISSUE THREAD

**Issue by mcintyre94** [blockstack/blockstack-app#2469]
I'm sending a Testnet transaction to the wallet with `anchorMode: 2`, ie off-chain transactions/using microblocks

When I request the transaction from the API, it has `anchorMode: any`

In practice this transaction does not get a result until it's in an anchor block, so the API seems to be reflecting the state it is being broadcast from the wallet in

It's a bit difficult to know exactly where in the ecosystem this is breaking, but my best guess is the wallet because I can see the `anchorMode` option being sent by stacks.js is correct, and I can see it's incorrect as soon as I make a request to the API, and I can see that the transaction does not appear in a microblock

---

I have a repro here on the public testnet: https://microblocks-test.vercel.app/

- Connect wallet

- Click the 'Mint Tokens' button

- At this point transaction options will be displayed, notice anchorMode: 2 is included:
```
{
  "contractAddress": "ST1RF441MG7VMFPN73DNHEH341DH7GDZW0MYD0GDY",
  ...
  "anchorMode": 2
}
```

- Confirm the transaction 

- At this point the transaction ID is shown, and a request is made to the `/extended/v1/tx/${transactionId}` route. The response of this is shown, and will include `anchorMode: any`: 
```
{
  "tx_id": "0x6e80847d6800a061a377a3a5a6e695e8293dce740bad971a5ec2f1299bee835e",
  ...,
  "anchor_mode": "any",
  "tx_status": "pending",
  ...
}
```

Source code is here: https://github.com/mcintyre94/microstacks-test/blob/main/src/pages/index.tsx

**Comment by mcintyre94** [comment]
I've found that using `anchorMode: 1` to force not to use microblocks is also ignored

I've updated my repro to add a toggle to set anchorMode to 1 or 2, to show that in both cases the transaction ends up submitted with `anchorMode: any`

**Comment by fbwoolf** [comment]
The fix for this has been merged into the new release branch so I'm going to close this issue and add it to the content list there.

PR: https://github.com/hirosystems/stacks-wallet-web/pull/2473
