### ISSUE TITLE
Fix Password strength indicator UX

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2474]
We don't show the password strength indicator by default, but when we do, I noticed it doesn't update in real time when you type. This makes it difficult to know when you've landed on a "secure enough password".

- [ ] Ensure password strength updates `onChange`
- [ ] Fix password not matching error text

<br /><br /><br />
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1618764/171468036-b4e784af-abc2-4194-ade1-26a0c37c000a.png">

**Comment by bit2world** [comment]
@kyranjamie can you assign me this?
