### ISSUE TITLE
onboarding links do not take users to the new exchanges

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#2475]
Onboarding links do not work for the new exchanges they all get a error page
video of the issue https://somup.com/c31nIUtTHd

binance
crypto.com
coinbase
kucoin
bybit
blockchain
OKX

<img width="1496" alt="Screen Shot 2022-06-02 at 9 25 38 AM" src="https://user-images.githubusercontent.com/49165468/171639844-a530e24c-c9c8-41ab-8eaf-5397ff65d1bd.png">

**Comment by fbwoolf** [comment]
This was fixed and merged into the release branch so I'm going to close this issue.
