### ISSUE TITLE
Fix blank auth screen with @stacks/connect upgrade

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-app#2495]
Uncaught (in promise) TypeError: "list" argument must be an Array of Buffers
    at Function.concat (index.js?9e97:399:1)
    at base58Encode (keys.js?de0d:36:1)
    at base58CheckEncode (keys.js?de0d:39:1)
    at publicKeyToAddress (keys.js?de0d:44:1)
    at Module.makeAuthRequest (messages.js?86ba:44:1)
    at UserSession.makeAuthRequest (userSession.js?4954:57:1)
    at _callee$ (auth.esm.js?6bbc:66:1)
    at tryCatch (runtime.js?ad1f:63:1)
    at Generator.invoke [as _invoke] (runtime.js?ad1f:294:1)
    at Generator.eval [as next] (runtime.js?ad1f:119:1)

Using Hiro Web Wallet 3.10.0
"@stacks/connect": "^6.6.0",
"@stacks/auth": "^4.3.0",

found on
Chromium: Version 102.0.5005.115 (Official Build) snap (64-bit)
Firefox: 100.0.1 (64-bit)
OS: Ubuntu Linux 22.04

**Comment by markmhendrickson** [comment]
Mind providing the code snippet and context in which you're seeing this?

**Comment by philiphacks** [comment]
Getting the same error when trying to upgrade @stacks/connect. No auth code has changed, PR here https://github.com/arkadiko-dao/arkadiko/pull/508/files

We're still doing `const { doOpenAuth } = useConnect();` and then just calling `doOpenAuth()` when clicking the connect wallet button.

**Comment by philiphacks** [comment]
Btw I isolated this to just upgrading @stacks/connect in that PR and I get the same error. I'm not sure if this is a bug or some dependency conflict

**Comment by philiphacks** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/577420/177279324-d4fcdcde-f35a-4d4e-87f1-e6d8df1a6894.png">

**Comment by markmhendrickson** [comment]
@philipdesmedt Any updates on your end as you've worked on troubleshooting, or are you still facing the same as reported above?

**Comment by philiphacks** [comment]
@markmhx still the same.. I've been working with @kyranjamie to find a solution but nothign so far.. seems like public key is an UInt8Array and should be a buffer

**Comment by kyranjamie** [comment]
Yeah one bizarre part of this is that there is a check to make sure it's a Buffer, but it still returns a Uint8Array anyway
![image](https://user-images.githubusercontent.com/1618764/178278298-0ec300e5-3d1b-4139-9c3f-add77f2da338.png)

**Comment by janniks** [comment]
I believe this is fixed in Stacks.js v`4.3.2`. I tested here: https://github.com/janniks/arkadiko/commit/603f73d6c4f707083bd032a56675b9282cc35cfa and the connect popup appears correctly. _(Will update the connect packages with latest Stacks.js soon)_

**Comment by philiphacks** [comment]
@janniks @kyranjamie @markmhx 

just upgraded to v4.3.2 for both auth and encryption packages and I can confirm the popup now appears!

thanks to all of you for spending time on this and getting it fixed! 🎉
