### ISSUE TITLE
Display images for NFT collections

### ISSUE THREAD

**Issue by Hero-Gamer** [blockstack/blockstack-app#2497]
Hi team, 

Thanks for getting the FT thumbnail display in. Looking much better!

I was wondering if it's possible to get the **NFT Collection thumbnail** in as well? 

**NFT Collection thumbnails like on: gamma.io**
https://gamma.io/collections
<img src="https://user-images.githubusercontent.com/92864860/163595856-f17851b6-e2b5-4fa6-a75f-327b75ac92fb.png" width="200px" />

To clarify:
* This is just one thumbnail for the WHOLE NFT collection. I'm **NOT** referring to displaying thumbnail for individual NFT you own in that collection. 
* e.g. if I have 14 crashpunks, on the BALANCE tab in hiro wallet where I see all of the NFT counts, the square thumbnail will only show **1** generic Crashpunk thumbnail (everybody who uses Hiro wallet who owns a Crashpunk, will see the **SAME** Crashpunk thumbnail)
* Obviously I do not understand the work involved to make it happen, but it seems like it could be a job leveraging what exists already, I feel like this could be a **quick win**, that can make every user's wallet & UX look & feel much sleeker. 

Thanks sir.

**Comment by markmhendrickson** [comment]
Tracking here now: https://github.com/leather-wallet/extension/issues/3613
