### ISSUE TITLE
Improve subheader copy for purchase options

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2499]
Options that are available:

- Only outside of the US should say "Available only outside of the US", not "Available outside of the US and other countries"

- Only inside of the US should say "Available only inside of the US"

- Inside and outside of the US should say "Available both inside and outside of the US".

![Image](https://user-images.githubusercontent.com/28991/175024311-5ae9f659-e2c6-456d-b437-3cc998347a94.png)

**Comment by fbwoolf** [comment]
Do we know of any that are only available in the United States? The code currently only makes the distinction b/w whether support is or isn't available in the United States.

**Comment by fbwoolf** [comment]
I checked all our providers and I don't see one that is just available in the United States, so I'll just implement as-is using the two other description changes.

**Comment by markmhendrickson** [comment]
That's true, there may not be any that satisfy the condition "Only inside of the US" so it can be omitted for now.
