### ISSUE TITLE
Add Coinbase Pay support

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2500]
Test App ID: `ca72edbc-0a08-468c-952d-6cde50b1dce6`

https://docs.cloud.coinbase.com/pay-sdk/docs

cc @jonastgerber

**Comment by fbwoolf** [comment]
@markmhx starting this today, Stacks isn't listed in the array of accepted blockchains here ...how did we know this was ready?

![Screen Shot 2022-07-11 at 12 49 56 PM](https://user-images.githubusercontent.com/6493321/178326606-d4c48e89-1ca1-4782-8059-8c134de627ae.png)

**Comment by fbwoolf** [comment]
Got this far but Stacks isn't listed and get an `invalid address` (expected) if I select anything else...

![Screen Shot 2022-07-11 at 3 27 04 PM](https://user-images.githubusercontent.com/6493321/178352314-514a1b4d-3750-41bf-bfb8-ae99ae60251d.png)

**Comment by markmhendrickson** [comment]
Coinbase indicated that Stacks should be listed already, so I'm not sure why it's not showing. I've CC'ed you on an email to them to learn more.

**Comment by cfluke-cb** [comment]
@fbwoolf try adding the item as an asset as STX

**Comment by fbwoolf** [comment]
Thx @cfluke-cb, that worked. 👍

**Comment by fbwoolf** [comment]
@markmhx success...

https://explorer.stacks.co/txid/0x3fec963a3757b58b991475ea6280ca46193c22cd7db5738a5448c0da8f3e8b27?chain=mainnet

![Screen Shot 2022-07-13 at 12 47 13 PM](https://user-images.githubusercontent.com/6493321/178797876-fab616d2-338a-45de-b274-482cb48f15ff.png)
