### ISSUE TITLE
Support Gaia for Ledger users

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2503]
The first version of Ledger support does _not_ include support for Gaia. We should enhance this to allow for such support.

**Comment by diwakergupta** [comment]
Can you clarify what "support for Gaia" means exactly?

**Comment by markmhendrickson** [comment]
@kyranjamie can provide more technical details once back, but essentially apps that authenticate users with Ledger using the Ledger-enabled wallet build (i.e. one we're planning to release soon into general availability) are unable to save or retrieve data with Gaia on behalf of those users as they can when users authenticate in "software" mode with a Secret Key.

**Comment by kyranjamie** [comment]
@diwakergupta Gaia uses the "appPrivateKey" that's deterministic from the data private key (`m/888'/...`). The Ledger app doesn't let us export/access this key, and Ledger wouldn't let us add it if we wanted to (according to Zondax). 

See the discussion https://github.com/hirosystems/stacks-wallet-web/discussions/2352

**Comment by kyranjamie** [comment]
We'll not be doing this as we're removing Gaia support entirely
