### ISSUE TITLE
Fix pending nonce not updating with tx requests

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2509]
This was fixed in the send form, but while testing the release build I found that for tx requests the atoms used for both pending and confirmed txs are not being set. So, if there is a pending tx, the nonce does not increment.

Related fix in the send form:
https://github.com/hirosystems/stacks-wallet-web/pull/2492

**Comment by wickles** [comment]
FWIW I did not have too many issues with this before 3.11, but now when there are pending transactions I have to manually edit the nonce every time.

**Comment by markmhendrickson** [comment]
Does this affect all transactions attempted while another is still pending? Or just a subset of those cases?

**Comment by fbwoolf** [comment]
> Does this affect all transactions attempted while another is still pending? Or just a subset of those cases?

This is for all txs from an app (not txs sent from the wallet send form). Sorry about this @wickles, it is fixed in this PR and hoping to merge/release it soon. https://github.com/hirosystems/stacks-wallet-web/pull/2511

**Comment by fbwoolf** [comment]
Did a quick fix for this that will be included with the ledger release today.
