### ISSUE TITLE
Possible bug: options.nonce in sponsored tx is overwritten regardless of value

### ISSUE THREAD

**Issue by unclemantis** [blockstack/blockstack-app#2513]
Please look at these two references containing `nonce: Number(values.nonce) || options.nonce`

[useSoftwareWalletTransactionBroadcast](https://github.com/hirosystems/stacks-wallet-web/blob/92e1047240326d4582f49e99f68426f5fac3aa38/src/app/store/transactions/transaction.hooks.ts#L123-L127)

and

[useGenerateUnsignedStacksTransaction](https://github.com/hirosystems/stacks-wallet-web/blob/92e1047240326d4582f49e99f68426f5fac3aa38/src/app/store/transactions/transaction.hooks.ts#L192-L196)

In my opinion the line should be

`nonce: options.nonce || Number(values.nonce)`

_Originally posted by @unclemantis in https://github.com/hirosystems/stacks-wallet-web/issues/2512#issuecomment-1168183329_

**Comment by kyranjamie** [comment]
To investigate this, we should check if `values.nonce` is ever `undefined`, or if the form is prepopulated with a default, preventing `options.nonce` from ever being used. 

If not, I don't think this is a bug, as the user should have the ultimate choice of what the nonce is.

**Comment by unclemantis** [comment]
> To investigate this, we should check if `values.nonce` is ever `undefined`, or if the form is prepopulated with a default, preventing `options.nonce` from ever being used. 
> 
> If not, I don't think this is a bug, as the user should have the ultimate choice of what the nonce is.

I discovered using testnet that explorer says next nonce for an account but the api nonces are different.  the wallet uses the api but the final say is from the miners.  I am currently stuck with a nonce mismatch and currently only editing nonce to match the one displayed in explorer works, otherwise I get a badrequest using the wallet suggested nonce which is retrieved from the api.  freaking weird if you ask me.  I broke my wallet. lol. 

The address in question.

ST17EV8YSY8MJ9J0ZDHVHXG5YKKX53Q2KKJQ305S1

I was using sponsored txs and apparently something broke.

**Comment by fbwoolf** [comment]
Options here are coming from `unsignedStacksTransactionBaseState`. Values is first bc if a user edits the nonce that has to be used. This is not a bug that I know of so going to close this. I am working on a bigger refactor of nonce state here which will hopefully fix some possible nonce issues: https://github.com/hirosystems/stacks-wallet-web/pull/2511
