### ISSUE TITLE
Wallet remains blank when loading many accounts (~200+)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2525]
Wallet version 3.11.0
Chrome browser

This is a copy of a user reporting this issue on the ALEX discord. I was hoping Hiro could help resolve this. 

![image](https://user-images.githubusercontent.com/33360391/177197345-6a8bc3e0-5dd0-4345-9157-d6247007e4e1.png)

![image](https://user-images.githubusercontent.com/33360391/177197372-ec1f0488-92d1-411f-9c2a-3582ad5a6f77.png)

![image](https://user-images.githubusercontent.com/33360391/177197399-53228bca-d5f4-4cef-8870-a6fe47159523.png)

I will keep an eye out if I see more users reporting this issue and checking if I can get a copy of whatever the console is reporting.

**Comment by 314159265359879** [comment]
The issue has something to do with the amount of accounts on a keychain. The user says this occurred when it tried to load more then 200 accounts. 

I tried to reproduce this issue on a key with enough accounts and found the same issue. For me it loaded fine for me at first but then after some scrolling (and loading more accounts) eventually it went blank. 

Here are shots from the console:
![image](https://user-images.githubusercontent.com/33360391/177206799-ca3b0216-de22-46e3-8336-f1c9fc547e40.png)

![image](https://user-images.githubusercontent.com/33360391/177206808-29e2bc5a-eeae-4475-8cf7-e3fe6a715117.png)

![image](https://user-images.githubusercontent.com/33360391/177206818-8af85026-2d1f-4005-9440-cf8e7af2492f.png)

![image](https://user-images.githubusercontent.com/33360391/177206827-4d30fb0e-5a9c-4573-9f95-1fdb2a69a1b7.png)

![image](https://user-images.githubusercontent.com/33360391/177206844-e67bd1ba-1287-4c9d-a933-95ef8b9f21b1.png)


For anyone seeing this who can't access they're accounts. If you use Xverse (iOS/Android app) you won't see this issue. Work around for now.

**Comment by fbwoolf** [comment]
@markmhx @kyranjamie I think we are seeing this bc of changing the onboarding steps to check every account balance and nft holdings on the home page. This is prob high priority to fix.
