### ISSUE TITLE
Apply hiro-web-extension header only for requests initiated by extension

### ISSUE THREAD

**Issue by janniks** [blockstack/blockstack-app#2533]
The wallet currently adds the `hiro-web-extension` header logic to every request (to the Hiro API), also those not initiated by the extension.

[This check](https://github.com/hirosystems/stacks-wallet-web/blob/e341f519e4de15efeacbea15f482f6a57a7faf7a/src/shared/add-referer-header.ts#L10) is no longer in the live version. I believe, something similar needs to be added again.

CC @CharlieC3 @kyranjamie

**Comment by markmhendrickson** [comment]
What kind of requests are being made by the wallet but not initiated by it? And why don't we want to track these? 🤔

**Comment by kyranjamie** [comment]
I understand that, if a web page makes a request to the API _and_ has the wallet installed, the extension will modify the header of the webpage's request. 

I removed the line in question as this prevented modified requests on all non-Chrome browsers, not considering this impact. 

Likely we need to use the extension's ID only to check initiator.
