### ISSUE TITLE
[Ledger] Tx signing flow returns to welcome page

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-app#2534]
When trying to sign a tx the flow ends on the welcome page instead of going through the tx signing flow.

I think
``` 
{ledgerTxSigningRoutes} 
```
should be in the transaction route

**Comment by markmhendrickson** [comment]
This is happening even if you're signed into the wallet already? And the wallet pops up directly to the welcome screen instead of the transaction signing screen?
