### ISSUE TITLE
Support updating the public profile

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-app#2544]
Users have a public profile (sometimes registered via the zonefile) that contains public information like where users store their data for certain apps. Currently, the profile contains a schema definition for `Person`. However, there is no way for the user to add or change the personal details.

This feature request is a first step to support updating the public profile. It is limited to properties of the Person schema. 

Application can request to update the users profile, then the user has to confirm the change via UI like this:

![Screenshot from 2022-07-07 13-19-43](https://user-images.githubusercontent.com/1449049/177761754-1e9ee700-2536-491f-a58f-8948fd8f1cf5.png)

This feature requires:
* handling a new type of request (update profile) from apps
* adding UI flow to confirm profile updates
* re-useing existing functions to upload the updated and signed profile

In connect (see https://github.com/hirosystems/connect/issues/246):
* adding new type of request (doUpdateProfile)

//cc @markmhx @yknl

**Comment by friedger** [comment]
If approved, I am happy to send a pull request

**Comment by aulneau** [comment]
I'm happy to help out here too

**Comment by Hero-Gamer** [comment]
I LIKE THIS FEATURE!

**Comment by markmhendrickson** [comment]
This generally approach looks great to me. We'd love to review a PR with this addition.

**Comment by kyranjamie** [comment]
Rather than a specific profile updater feature, could this be implemented as a more generic gaia data updater?

**Comment by friedger** [comment]
@kyranjamie The underlying logic could handle that. The app should then send mime-type, filename and file content, optional encryption key. 

This issue is about limited editing feature of the profile because the public profile contains app data that users might not want to mess with in general. Therefore, the flow for this issue would accept only
```
mime-type = application/json
filename = profile.json
encryption key = undefined
file content follows strictly Person schema
```

**Comment by aulneau** [comment]
While I think it makes sense to potentially have a Gaia generic function, the profile related stuff does warrant its own methods in my opinion. The profile is a core element of stacks auth and wallet usage, and we should start giving it more focus.

I vote for a specific profile related function before a generic Gaia method.

**Comment by friedger** [comment]
Here is first proposal for a request token: https://github.com/hirosystems/stacks-wallet-web/pull/2632/files#diff-013e7cf4ed0371a2b480849aa230bf83e4314ff2c959d79818953a93fc460688R30

**Comment by markmhendrickson** [comment]
@kyranjamie is going to prepare for release
