### ISSUE TITLE
Can't edit nonce for sponsored transactions

### ISSUE THREAD

**Issue by anilasdev** [blockstack/blockstack-app#2553]
While I'm making a transaction, it is sending the wrong nonce. So when I make edit the nonce, I'm not able to type any values in the nonce field.

**Comment by kyranjamie** [comment]
I'm not able to replicate this. Any more details you can share on how to reproduce this? Do you mean the send form, or a contract call from an app?

A screencast would be very helpful, if you know how to make one.

**Comment by anilasdev** [comment]
<img width="867" alt="Screenshot 2022-07-11 at 14 09 42" src="https://user-images.githubusercontent.com/20225408/178224180-328632c1-828f-4b66-99c6-6d72370f3c80.png">

Here I can not type anything. Also, this issue is before calling a function and getting the wrong nonce error. Also, this is a part of the sponsored transaction and I'm sending the serialized transaction to the API where I make the API call. This is the error Im getting.

{
  actual: 62,
  expected: 66,
  is_origin: true,
  principal: 'ST1N8RXPB8M771MEM9N1EJZRN125983CXPXYC2AX1'
}

**Comment by anilasdev** [comment]
I'm using chrome wallet v3.11.2

**Comment by unclemantis** [comment]
I too am having issues with sponsoredtx.  following.

**Comment by kyranjamie** [comment]
Thanks, I can only replicate with sponsored txs. It looks like there's some extremely heavy js operation happening blocking the main thread.

**Comment by anilasdev** [comment]
@kyranjamie Is this fixed? I'm still having this issue

**Comment by markmhendrickson** [comment]
@anilkumar1994 Can you confirm the version number of your wallet installation is at `3.12.0` or greater now?

**Comment by fbwoolf** [comment]
This is fixed for me on `v3.12.0`, however now I'm seeing a fee load in which is odd. I didn't see this when testing.

<img width="463" alt="Screen Shot 2022-07-13 at 9 13 10 AM" src="https://user-images.githubusercontent.com/6493321/178755191-cae2abe0-d40c-4b9d-8156-caac9943d8b4.png">

**Comment by fbwoolf** [comment]
Not seeing ^ now, so maybe it was an edge case, but I will look at it bc might load the fee with a slow network.

**Comment by anilasdev** [comment]
> @anilkumar1994 Can you confirm the version number of your wallet installation is at `3.12.0` or greater now?

I have updated the chrome extension, and it worked. thanks
