### ISSUE TITLE
[Ledger] Auth fails with account 2 and higher

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-app#2572]
Using chrome extension 3.12.1, I can't authenticate with accounts other than account 1 on alex, arkadiko, pool.friedger.de/members, etc.

The call to `doSignaturesMatchPublicKeys` fails when verifying the auth response.

![Screenshot from 2022-07-18 12-53-44](https://user-images.githubusercontent.com/1449049/179500036-fc6ad3c1-0142-4055-beca-40a584ad6ea3.png)

**Comment by the-artilleryman** [comment]
I tried this and also ran into problems, if e.g. the extension is set to account 1, but I attempt to auth account 2 - it doesn't log in.

Corrected it by switching the account first, to the account I wanted to auth with.

Replicated it in reverse. Account 1 didn't auth while account 2 was active in the extension.

**Comment by kyranjamie** [comment]
Thanks for the report @friedger. Bug here was using the data key of the active account, not the account of the index you selected. Shipping a fix very shortly.
