### ISSUE TITLE
Revisit error message when trying to finalize auth/tx/message

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2584]
A few reports in Discord from users not understanding this error message...

![image](https://user-images.githubusercontent.com/6493321/180246179-76702d70-6160-4cd6-8f80-20891d1ce03e.png)

This error message should also be better shared:
https://github.com/hirosystems/stacks-wallet-web/blob/3a890d665a70241a9593859ea889c2c0c897290d/src/app/common/actions/finalize-auth-response.ts#L59
https://github.com/hirosystems/stacks-wallet-web/blob/3a890d665a70241a9593859ea889c2c0c897290d/src/app/common/actions/finalize-tx-signature.ts#L29
https://github.com/hirosystems/stacks-wallet-web/blob/3a890d665a70241a9593859ea889c2c0c897290d/src/app/common/actions/finalize-message-signature.ts#L24

**Comment by kyranjamie** [comment]
I'm hoping this will work a lot better when we follow the request account pattern, where each request has a uuid.

I wonder if this happens when there are > 1 auth/signing window open at a given time.

**Comment by fbwoolf** [comment]
> I wonder if this happens when there are > 1 auth/signing window open at a given time.
>
I'll try to test this today.

**Comment by kyranjamie** [comment]
This was refactored, and we improved the flow where we now detect a requesting app close, and showing an error accordingly
