### ISSUE TITLE
Making contract calls with Ledger doesn't broadcast transactions after they're signed

### ISSUE THREAD

**Issue by 2snEM6** [blockstack/blockstack-app#2585]
### How to reproduce

Call `openContractCall`. Example:

```javascript
openContractCall({
        contractAddress,
        contractName,
        functionName: 'delegate-stx',
        functionArgs: [...args],
        onFinish: () => {
          console.log('onFinish')
        },
      });
```

Sign the transaction with Ledger, wallet will say it's approved, but nothing will happen afterwards and onFinish will not be called.

**Comment by fbwoolf** [comment]
I believe we determined this was a broadcast error not being displayed in the wallet. `BadFunctionArgument` which is going to be added in this work here: https://github.com/hirosystems/stacks-wallet-web/pull/2582 ...so, I am going to close this issue.

![image](https://user-images.githubusercontent.com/6493321/180289649-e511837c-d51a-4ee5-ad5a-29cfa672fb85.png)

**Comment by fbwoolf** [comment]
Also, this issue was created in Connect: https://github.com/hirosystems/connect/issues/261

**Comment by 2snEM6** [comment]
Agree, will follow #2582, thanks @fbwoolf
