### ISSUE TITLE
Something went wrong?

### ISSUE THREAD

**Issue by Macxim** [blockstack/blockstack-app#2586]
Hello. I came across this: 
<img width="443" alt="Screen Shot 2022-07-24 at 1 30 38 PM" src="https://user-images.githubusercontent.com/1909957/180647143-fb4853c6-f934-4b01-8cb0-2adc8cce3f1e.png">

Something definitely went wrong with that error message 😂 See https://github.com/hirosystems/stacks-wallet-web/blob/92e1047240326d4582f49e99f68426f5fac3aa38/src/app/pages/transaction-request/components/minimal-error-message.tsx#L32

**Comment by fbwoolf** [comment]
This is fixed in my current open PR refactoring the submitted transactions so I'll link it there.
