### ISSUE TITLE
Sponsored tx nonce suggestion error (1 more than it should)

### ISSUE THREAD

**Issue by Hero-Gamer** [blockstack/blockstack-app#2590]
if you try minting a free (sponsored tx, user pays nothing) NFT from this page: https://byzantion.xyz/mints/airdropticket
the default nonce suggestion seems to suggest 1 more than it should. 

To repro: 
- click mint page, connect wallet, click mint button, confirm tx. 
then you can check in your Explorer history that sponsored tx suggested 1 more nonce than it should, creating nonce gap. 

Just to bring to you guys' attention.

**Comment by fbwoolf** [comment]
Closing this bc it is an explorer issue here: https://github.com/hirosystems/explorer/issues/793
