### ISSUE TITLE
Password checker (when creating new account/wallet) - non-critical 

### ISSUE THREAD

**Issue by Hero-Gamer** [blockstack/blockstack-app#2593]
Hi team,

Currently the process when creating new account/wallet, it asks you to create a password, and only type ONCE.

However it doesn't check what you wrote is what you think you wrote, i.e. someone mis-typed what he thinks the password vs what he actually thinks the password is, he could be logged out in the future and not able to enter, yes he can still log back in with 24 seed phrases and reset a new password. 

But it can be simply avoided if you asked the user to type password again with a checker. Ideally it would also check for password strength as well (which I think it currently does already right?)

<img src="https://user-images.githubusercontent.com/92864860/181755834-e7fd2ab9-ec24-4d43-8dbf-8acb3ee7a468.png" width="400px" />

**Comment by fbwoolf** [comment]
We just removed the confirm password field after doing UX/UI research on what is preferred. We have provided the show/hide eye icon so a user can see the password they are submitting. You can see the discussion that happened to make this decision here: https://github.com/hirosystems/stacks-wallet-web/pull/2488#issuecomment-1163483173

**Comment by Hero-Gamer** [comment]
I see, cool to see the research. Thanks!
