### ISSUE TITLE
Text-wrapping in Sign message 

### ISSUE THREAD

**Issue by dleiberman** [blockstack/blockstack-app#2594]
![Screen Shot 2022-07-28 at 11 00 15 AM](https://user-images.githubusercontent.com/5739796/181770621-9cb205b9-a33c-458c-a1d3-5670ef3ae2ef.png)

**Comment by fiftyeightandeight** [comment]
We also have a similar issue. It not only makes reading harder but also aesthetically not pleasing. Can we please improve on this?

<img width="444" alt="Screenshot 2022-08-01 at 2 45 09 PM" src="https://user-images.githubusercontent.com/443225/182093511-b67370d4-fdda-494e-bb58-79c61807aa04.png">

**Comment by markmhendrickson** [comment]
@kyranjamie can we close this as completed and released?
