### ISSUE TITLE
Wrong nonce is getting sent on sponsored transactions.

### ISSUE THREAD

**Issue by ImTheCodeFarmer** [blockstack/blockstack-app#2605]
[This address](https://explorer.stacks.co/address/STZTTWJ2DFJTQWV2THMY55W2ZVD7T7G9CE4ESMT6?chain=testnet) shows the last executed tx nonce as two. When the wallet window appears, it fills the nonce with the assumed value of 3. However, this address has many executed transactions (of which most were sponsored). So instead, it is expecting a higher nonce.

I have put together a video of this in our app [here](http://p8screenshots.s3.amazonaws.com/screencast_2022-08-08_09-29-05.mp4).

I am not 100%, but it seems that one API is counting the sponsored transactions towards the required nonce, and another isn't. I found these two endpoints returning two different nonces:

https://stacks-node-api.testnet.stacks.co/v2/accounts/STZTTWJ2DFJTQWV2THMY55W2ZVD7T7G9CE4ESMT6

https://stacks-node-api.testnet.stacks.co/extended/v1/address/STZTTWJ2DFJTQWV2THMY55W2ZVD7T7G9CE4ESMT6/nonces

**Comment by fbwoolf** [comment]
The wallet (and the explorer) uses the second api endpoint linked and some additional validation checking client-side to determine the nonce. If this is an issue, it appears to be an api issue and should be moved to that repo? @rafaelcr wasn't this fixed in the api recently?

**Comment by rafaelcr** [comment]
It was @fbwoolf , I believe the issue is that the testnet API is running version 3 instead of the most recent version 4 cc @deantchi @CharlieC3

**Comment by deantchi** [comment]
yes, confirmed `testnet` is on `v3.0.3`

**Comment by ImTheCodeFarmer** [comment]
Ohhh, interesting. Is that upgrade something that is planned? Not sure how the release cycles work. Thanks, everyone :).

**Comment by markmhendrickson** [comment]
I'm closing this wallet issue seeing that it appears to be an API side problem for which a fix needs deployment.

@deantchi and @CharlieC3 can still follow up here with an indication of the expectations for that release.

**Comment by ImTheCodeFarmer** [comment]
Thanks! Is there a place to check deployment status to testnet @deantchi / @CharlieC3 ?

**Comment by CharlieC3** [comment]
@jhammond2012 Try again, it should be at version 4 now (thanks @deantchi !)
https://stacks-node-api.testnet.stacks.co/extended/v1/status
