### ISSUE TITLE
Replace Coinbase Pay logo

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2606]
With the following asset:

![Coinbase_Coin_Primary](https://user-images.githubusercontent.com/28991/183631176-cc372cf2-d6d4-4c81-8ad2-be18047873a9.svg)

**Comment by fbwoolf** [comment]
I guess if only available in the US we need to change the tile copy as well? Should it now say, `Available only inside of the US`?

**Comment by markmhendrickson** [comment]
Let's hold off on the US vs non-US copy change for now since I've inquired with marketing whether we ought to wait for non-US coverage to announce. 🙏
