### ISSUE TITLE
Sponsored TXNs are having some issues

### ISSUE THREAD

**Issue by ImTheCodeFarmer** [blockstack/blockstack-app#2640]
When trying to call a sponsored TXN we are getting a disabled confirm button. Upon inspecting the console, I can see the following errors:

![The Error](http://p8screenshots.s3.amazonaws.com/DevTools_-_chrome-extensionldinpeekobnhjjdofggfgjlcehhmanljpopup-center.html_2022-09-01_08-57-43.png)

It seems the address is not getting passed into the request for some reason.

**Comment by ImTheCodeFarmer** [comment]
I also wanted to mention (maybe this is related or should be it's own issue) that we are calling a mainnet function but getting back a testnet error:

```
const options = {
    contractAddress: process.env.REACT_APP_CLAIM_CONTRACT_ADDRESS,
    contractName: process.env.REACT_APP_CLAIM_CONTRACT_NAME,
    functionName: "claim-link",
    functionArgs,
    postConditions,
    network:
      process.env.REACT_APP_STACK_NETWORK === "mainnet"
        ? new StacksMainnet()
        : new StacksTestnet(),
    appDetails: {
      name: "Claim",
      icon: "https://assets.website-files.com/618b0aafa4afde65f2fe38fe/618b0aafa4afde2ae1fe3a1f_icon-isotipo.svg",
    },
    onFinish,
    sponsored: Boolean(isSponsored),
  }; 
  ```

**Comment by markmhendrickson** [comment]
Thanks for this report. I suspect these are two separate issues, so it'd be great if you could create a new issue for the latter.

@fbwoolf @kyranjamie might the 404 response issue with missing address value in the URL be a quick fix?

**Comment by kyranjamie** [comment]
Not sure if this is directly related to the missing url. One of us will have to investigate.

**Comment by fbwoolf** [comment]
I can check if the sponsored tx is broken in the test-app this morning, but last I checked it was working.

**Comment by ImTheCodeFarmer** [comment]
Just wanted to follow up on this one. Thanks! :)

**Comment by fbwoolf** [comment]
> Just wanted to follow up on this one. Thanks! :)

Sorry, I haven't had a chance to try and repro. I will do today!

**Comment by fbwoolf** [comment]
Ok, I repro'd the `Confirm` button not becoming active bc we were checking for a fee value here to enable it. I will put up a PR today to fix it and include it in the next release.

**Comment by ImTheCodeFarmer** [comment]
Thanks so much!!
