### ISSUE TITLE
Unable to send wrapped-bitcoin (testnet)

### ISSUE THREAD

**Issue by jeremyallencpa** [blockstack/blockstack-app#2642]
I am unable to select wrapped-bitcoin from my Hiro Wallet.

When I attempt to send wrapped-bitcoin it doesn't show up under 'Choose an asset' despite the fact that the wallet contains wrapped-bitcoin.

I don't have this issue with the STX and Wrapped USD in my wallet.

For reference the contracts for wrapped-bitcoin and Wrapped USD are:

Wrapped Bitcoin  ST287GF5M9WEJ6BXEN7NPN1WGA95YWXWBE0ZRK6X.Wrapped-Bitcoin
Wrapped USD ST2TZK01NKDC89J6TA56SA47SDF7RTHYEQ42CGN7F.Wrapped-USD

**Comment by markmhx** [comment]
I'm not able to find those addresses on the explorer. Mind posting explorer links to these contracts directly? 🙏

**Comment by markmhendrickson** [comment]
I suspect this may be due to the contracts not conforming entirely to the fungible token spec. Can you double check all the attributes? 

https://github.com/stacksgov/sips/blob/main/sips/sip-010/sip-010-fungible-token-standard.md

**Comment by jeremyallencpa** [comment]
The attributes all appear to be appropriate (though perhaps I have missed something): [https://explorer.stacks.co/txid/0x7aea62300830452b7aefca6855d3e48f53d41569b185821f2d68bf87a0724b8f?chain=testnet](url). 

From the command line, we are able to mint, burn, and transfer tokens. Additionally, I have transferred tokens using my testnet Hiro wallet up until about a month ago. Any other thoughts on what could be happening here?

**Comment by markmhendrickson** [comment]
@fbwoolf @kyranjamie any ideas here?

**Comment by kyranjamie** [comment]
The API was having trouble with metadata a while back. Please reopen if issue persists.
