### ISSUE TITLE
Open contract call and web wallet not aligned on network

### ISSUE THREAD

**Issue by mijoco-btc** [blockstack/blockstack-app#2645]
Versions:
"micro-stacks": "^1.1.1",
"@micro-stacks/svelte": "^1.0.3",

Configure the network to be 'testnet' with the hiro web wallet connected to mainnet.

    const config = {
      appName: 'Ecosystem DAO',
      appIconUrl: origin + '/img/logo.png',
      network: 'testnet'
    };
    mountClient(config)
On openContractCall, the wallet opens connected to 'testnet' but looks up the contract on mainnet.

## Steps to Reproduce

Pre-Conditions
1. Ensure Web Wallet connected to mainnet

Main Flow
1. Goto: https://testnet.stx.eco/about
2. Click Connect Wallet
     i. Click account 1 (note that the accounts shown are mainnet accounts)
     ii. Note the logged in address is your testnet address
3. Click the `DAO` link on the header bar
4. Click the `Proposals` link on the sub header bar
5. Click `support-sip-013` link in the list
6. Scroll down to a button that says `Conclude this Vote`
7. Click button and `wait 10 - 20 seconds` - should see the screenshot below
8. Manually switch the web wallet network to `testnet`
9. The `contract not found` error goes away.

See screenshot: 
<img width="927" alt="Screenshot 2022-09-07 at 10 47 44" src="https://user-images.githubusercontent.com/4384929/188848146-43972d60-b65d-410f-b1ae-531547e42688.png">

**Comment by kyranjamie** [comment]
Thanks for reporting @radicleart, can confirm this issue, appears the wallet is requesting from mainnet (though, at some point it corrects again, later loading back from testnet).
