### ISSUE TITLE
Multiple pending transactions

### ISSUE THREAD

**Issue by chipicookie** [blockstack/blockstack-app#2663]
Hello,

For address SP1M4CCT7BYKZKYQGX7F0BV490TPXCNMSSP28ET90, I had one pending transaction that lastest forever:

0x522e7738cc8e7168b4dfbe922ad18b37d299a9a7bfc58cd65557415692bd6c78

A user told me to create another transaction with none 8 so that this pending transaction would be cancelled. 

The new transaction went through: 

0xe3dbde3fc30844238a802b080693fda970eb3e80a33c62e056c5ab700247345d

But the initial pending one is still pending. And from then, all the new transactions I did are pending as well: 

![image](https://user-images.githubusercontent.com/113673869/190598744-e3dcfdfd-c1d6-43fd-b5ce-957c075210fc.png)

Could you please try to help me cancelling these transaction so I can actually move my stx? 

Thanks a lot for your help ;)

**Comment by kyranjamie** [comment]
Not sure what's going wrong here. 

https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP1M4CCT7BYKZKYQGX7F0BV490TPXCNMSSP28ET90/transactions

If last executed nonce was 8, then the transactions you have pending are legit and should be picked up. I'm not sure why they're not being mined. It looks like the wallet has selected the correct nonces.

cc/ @zone117x @rafaelcr wonder if you have any input on this

This account's first tx in above API resp is `2418`, not sure if this is related, but how could this ever be?

**Comment by rafaelcr** [comment]
@kyranjamie 

> This account's first tx in above API resp is 2418, not sure if this is related, but how could this ever be?

This was a tx that the address in question received, so the nonce belongs to the sender (SP1FNEJ21BMJCJYEJM2F73QT6WD2MN9MB2J92FZBN in that case).

The address nonce reported by nodes is still 8: https://stacks-node-api.mainnet.stacks.co/v2/accounts/SP1M4CCT7BYKZKYQGX7F0BV490TPXCNMSSP28ET90

If the other txs still appear it could mean the API did not receive the `dropped-replace-by-fee` message for it. In any case, the pending txs will be automatically garbage collected within 256 blocks.

**Comment by kyranjamie** [comment]
Thanks @rafaelcr. Missed that it was a receiving tx.

Node and API are returning correct next nonce value so think we can close this issue.
