### ISSUE TITLE
Ensure that fee ceiling is applied upon first load of transaction signing screen

### ISSUE THREAD

**Issue by wickles** [blockstack/blockstack-app#2667]
I've noticed that the default recommended Standard gas fee is (incorrectly?) much higher now on every transaction since version 3.17.0, around 0.2-0.5 STX or so typically. But if I open the Fees menu and press Standard again it goes back to the previous usual recommended fee of 0.003 STX. 

Is this an intended change or a bug?

**Comment by markmhendrickson** [comment]
It appears as though the fee "ceiling" (in which the wallet enforces a manual upper limit to the transaction fee) isn't getting consistently applied upon first load but sometimes only after the user manually toggles the fee selection. This appears to be a UI bug.

**Comment by markmhendrickson** [comment]
This has been reported by @ nat🍏#0129 on Discord as well
