### ISSUE TITLE
STX transfers pending forever (14+ hours)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2668]
Helping a user on Telegram, usually in this case (forever pending STX transfer) the nonce is wrong or the balance is insufficient but this transaction has been pending for 14 hours and I do not understand why. Nonce is correct, and balance is sufficient. 

![image](https://user-images.githubusercontent.com/33360391/192132537-1e443adb-6a18-44f3-b402-053e1662d023.png)

https://explorer.stacks.co/address/SP39WQ90WHTTN6BTTW8GST8FJXPZVVX8R2JESYT44?chain=mainnet

The only weird thing about this list of transactions is the ones below with nonce 12-15 they appear to be pending but when you go into the transactions it directs me to transactions that are mined yet failed: https://github.com/hirosystems/explorer/issues/864

Why are miners not picking this up?

**Comment by 314159265359879** [comment]
After the user increased the fee (2x) it did get picked up right away. https://explorer.stacks.co/txid/0x3b44d950da24dcbd7f0dca14b3764ce7064528e015594288d77933f2e205e970?chain=mainnet

The fee was already above average prior to the increase though, still strange it was not picked up before especially over such a long time. 

Average fee lately has been around 0.063 according to: https://stacksonchain.com/dashboards/Transactions-per-Day/14

**Comment by fbwoolf** [comment]
Can this be closed?
