### ISSUE TITLE
Error Farming

### ISSUE THREAD

**Issue by asnigglewiggle** [blockstack/blockstack-app#2670]
Getting this error with trying to Farm "Your Ledger device has rejected the payload stating it is invalid"

**Comment by 314159265359879** [comment]
For context this error is shown when using the ALEX dapp, not just farming apparently, we thought this was fixed. I think this is related: https://github.com/hirosystems/stacks-wallet-web/issues/2567

**Comment by markmhendrickson** [comment]
Please see: https://github.com/hirosystems/stacks-wallet-web/issues/2567#issuecomment-1259375186
