### ISSUE TITLE
 Wallet does not properly reflect the decimals of FT in the post conditions correctly

### ISSUE THREAD

**Issue by cryptocracy** [blockstack/blockstack-app#2678]
So in our app [https://mia.derupt.io](https://mia.derupt.io) 
Users can interact with the Derupt smart contract.
When doing so they are supposed to be transferring exactly `100` MIA per action. 
(when creating a New Chime, Liking an existing Chime, or Disliking an existing Chime.)

When clicking a button to invoke the action and thus present the Hiro Web Wallet popup window, it will show `100` MIA to be transferred as expected. However when viewing the transaction on the explorer it shows only the `0.0001` MIA is the post condition amount.

No matter what,  we can't seem to get the Hiro Web Wallet popup window and the actual amount per the explorer to both be indicative of 100 MIA.

In our source code we set my amount with `new BigNum(100000000);` 
The transaction per the Explorer settles correctly, eg `100` MIA is transferred as intended.
HOWEVER during this instance the Hiro window says the user is its going to xfer `100000000` MIA instead.
Which most def will create cause for pause as a user.

The best we can tell is that the Hiro Web Wallet does not properly reflect the decimals of FT in the post conditions correctly during the confirmation popup window.

**Comment by cryptocracy** [comment]
Trying to educate users about decimal precision errors outside of our control does make for a good UX, ...can't just be like "trust me bro..."

**Comment by cryptocracy** [comment]
The UX Impact

**Situation A)** 
code: 
    `const postConditionAmount = 100;` 
or `const postConditionAmount = 100n;` 
or `const postConditionAmount = new BigNum(100);`
yields: Hiro Window will show 100 MIA (giving the user **assurance** about what they expect to be sent) 
Explorer: shows the post condition amount as 0.0001, **resulting in tx failure to meet the condition** required by the smart contract.
ux impact summary: completely unusable due to tx failures

**or**

**Situation B)**  
code: `const postConditionAmount = new BigNum(100000000);`
yields: Hiro Window will show 100000000 MIA (giving the user **concerns** about what they expect to be sent) 
Explorer: shows the post condition amount as 100 MIA, **resulting in tx successfully meeting the condition** required by the smart contract.
ux impact summary: technically tx will confirm as intended, however users will not want to confirm the transaction because the Hiro Window will mislead the user into thinking they are about to send 100,000,000 MIA instead of just 100.

Additionally I've verified this is only happening with the Hiro web wallet, it does not seem to appear to be an issue whilst testing with Xverse wallet.

**Comment by cryptocracy** [comment]
Hmmm seems to be resolved now, not sure what changed, but i was literally watching a Hiro window as it fixed it self.
I'll go ahead and close this for the time being.

**Comment by markmhendrickson** [comment]
Thanks for this report, even if it it did seem to automatically resolve itself. Is it possible that the relevant contract had been very recently deployed and the API that the wallet uses to load standardized contract data may not have loaded the decimals data in time for your initial testing? Or had the contract been deployed for awhile already?

**Comment by cryptocracy** [comment]
> Thanks for this report, even if it it did seem to automatically resolve itself. Is it possible that the relevant contract had been very recently deployed and the API that the wallet uses to load standardized contract data may not have loaded the decimals data in time for your initial testing? Or had the contract been deployed for awhile already?

The contract in question that I was calling is our derupt alpha version 11 contract.
`SP3T3JC6V4S94PPB7WFEK17863HPG3EYP6CJ65E7M.derupt-mia-alpha-v11`
which was deployed over 4months ago.
