### ISSUE TITLE
[Bitcoin] Multi-currency receive picker

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2688]

**Comment by markmhendrickson** [comment]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=259%3A44722&t=9z5AbdmYRLvpuwr3-1



![Image](https://user-images.githubusercontent.com/28991/214093049-64d15058-e2b2-497a-aa58-51c442b41209.png)

**Comment by markmhendrickson** [comment]
Is this issue resolved so we can close?
