### ISSUE TITLE
[Bitcoin] Bitcoin send form

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2691]
- [x] #2817
- [x] #2818
- [x] #2819
- [x] #2853
- [x] #2873
- [x] Create action component
- [x] #2936
- [x] #2937
- [x] Create STX validation
- [x] #2813

**Comment by kyranjamie** [comment]
Observations of the current send form's implementation:

- **Slow loading**. The click handler to navigate to the page takes almost 1s.
- **Render blocking**. Heavy operations take place on user input to the fields, blocking the main thread.
- **Poor handling of global state change**. Change network or account while on the current send form does not work well.
- **Unclear structure**. The difference in responsibility between `send-tokens.tsx` and `send-tokens-inner.tsx` isn't well defined.
- **STX specific**. Requires refactor to build in support for multiple chains.

**Comment by fbwoolf** [comment]
Designs: https://www.figma.com/file/uWutVORXsNUqdrHS0F07jG/%F0%9F%93%A4-Send?node-id=5%3A5223

**Comment by markmhendrickson** [comment]
Assigning @mica000 to review the designs and provide modifications where helpful.

**Comment by fbwoolf** [comment]
This was linked to my last PR by you @markmhx so it closed when merged. I am going to move it to released column bc it was just keeping track of several issues which are complete. I think another design issue can be created once the form is ready for design review?

**Comment by markmhendrickson** [comment]
Sounds good! My bad on the linking 🙏
