### ISSUE TITLE
Prevent brief display of "poor" password indicator upon paste of strong password

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2697]
It currently provides for a slightly disconcerting experiencing in which the user might doubt if things are working properly:

https://user-images.githubusercontent.com/28991/193783392-4c19c959-62f5-4710-a059-8e04a828453d.mov

**Comment by kyranjamie** [comment]
I've noticed this too when pasting in my demo password. Perhaps we need to either reduce debounce time, or use a throttle instead.
