### ISSUE TITLE
Unable to determine chainID from node. [critical issue in 3.18.0]

### ISSUE THREAD

**Issue by caoer** [blockstack/blockstack-app#2703]
<img width="392" alt="screenshot-2022-10-05-15 58 15@2x" src="https://user-images.githubusercontent.com/225856/194009968-f6d19775-4a03-4261-85d6-c57d777c9170.png">

it works in 3.17.2 but failed to work in 3.18.0. Please see above screenshot. 
This affects all our test users. our API end point is: 
[https://stacks-node-api.testnet.alexlab.co](https://stacks-node-api.testnet.alexlab.co)
By using 3.17.2 downloaded from github release, the network can be added fine with same content.

**Comment by markmhendrickson** [comment]
@fbwoolf thoughts on whether / how the recent network refactor may have affected this?

**Comment by fbwoolf** [comment]
> @fbwoolf thoughts on whether / how the recent network refactor may have affected this?

Yep, most likely from those changes. I did test this before releasing, so let me look at it today.

**Comment by fbwoolf** [comment]
Ended up not being my changes but a double `//` path:

![Screen Shot 2022-10-05 at 8 26 13 AM](https://user-images.githubusercontent.com/6493321/194086220-1b395c23-cf8c-4cbd-8bec-828ef5262ca5.png)

Fix will be in the new wallet release today.

**Comment by fiftyeightandeight** [comment]
Hi @markmhx @fbwoolf thank you for releasing this fix as part of 3.18.1. 
I see that Chrome web store still carries 3.18.0. Would you know when this will be updated to 3.18.1?

**Comment by markmhendrickson** [comment]
It's hard to say exactly how long it'll take for Google to approve for the Chrome Web Store, but we've submitted and usually it's quite fast (within 24 hours).

**Comment by goodsanai** [comment]
I see it's now updated to 3.18.1. Thank you!

**Comment by fiftyeightandeight** [comment]
I see it's now updated to 3.18.1. Thank you!
