### ISSUE TITLE
[Bitcoin] Look up used accounts by balance, btc name

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2710]
Per https://github.com/hirosystems/stacks-wallet-web/issues/1732#issuecomment-1266658917

Using Gaia as an external dependency has presented a handful problems:
- The wallet breaking when Gaia is down
- Corrupt/broken wallet profiles returning nothing, and scaring users their accounts are gone
- Slowing down sign in times as it fetches the profile

Most crypto wallets have some mechanism that recurses through accounts until _n_ with no balances. We can do the same, considering balances, activity, and bns names. We should have this mechanism for both Stacks and Bitcoin balances.

**Comment by markmhendrickson** [comment]
Is this issue resolved so we can close?
