### ISSUE TITLE
Pending Transaction

### ISSUE THREAD

**Issue by Nabeel-javed** [blockstack/blockstack-app#2713]
hey, my transaction is pending for more then 12 hours and its getting frustrated now. I didn't sent more STX then i had but still its pending

Here is my Tx Id

https://explorer.stacks.co/txid/0x335e43b0e020b92c17c534e973f37c9db7ca9bf0c0eb3555fb05688a296bc5a9?chain=mainnet

**Comment by kyranjamie** [comment]
This transaction hasn't been mined yet, and is sitting in the mempool. There's nothing the wallet can do about this.
