### ISSUE TITLE
Resolve issue with nonce set 1 too high

### ISSUE THREAD

**Issue by Nabeel-javed** [blockstack/blockstack-app#2716]
Its been more then 48 hours since my transaction is stuck in mempool even tho i used high gas, idk why is this happening, but whatever reason is its very frustrating. I know you guys can't do anything but pls let me know how to cancel it and what's the approximate time that it will be cancelled. And what can i do next time so that my transaction won't be stuck like this

Please don't close the issue

**Comment by markmhendrickson** [comment]
Can you provide the transaction ID so we can take a look?

There's no method yet for canceling transactions, though we're looking into adding it soon: https://github.com/hirosystems/stacks-wallet-web/issues/1834

**Comment by Nabeel-javed** [comment]
> Can you provide the transaction ID so we can take a look?
> 
> There's no method yet for canceling transactions, though we're looking into adding it soon: #1834

https://explorer.stacks.co/txid/0x8ce91aaea056b220d4de22707d469a1a04769f31b5e5425ff855c08df2a3fa56?chain=mainnet
https://explorer.stacks.co/txid/0xbff543ead1aa0903e825cdad0a83e8836af5dce0fc13d834db23194c880af514?chain=mainnet

here are both TXNs


sorry I mistakenly closed it ig, but i would be good if u can still answer

**Comment by markmhendrickson** [comment]
It appears both of these transactions are using the wrong nonce (3 when they should be using 2).

@fbwoolf @rafaelcr any idea whether the work on https://github.com/hirosystems/stacks-blockchain-api/issues/1342 might have helped prevent this?

@Nabeel-javaid You should be able to resolve your issue here by resending both of this transactions, but before submitting, select "Edit nonce" at the bottom of the wallet screen and change the value to 2.

**Comment by markmhendrickson** [comment]
<img width="1352" alt="Screen Shot 2022-10-13 at 10 50 40" src="https://user-images.githubusercontent.com/28991/195549880-b9741622-b319-46c6-a9c7-67e0d0e03e0a.png">

<img width="1364" alt="Screen Shot 2022-10-13 at 10 50 46" src="https://user-images.githubusercontent.com/28991/195549847-387bf7e4-d455-48d7-85cb-45f4f9e0469d.png">

**Comment by rafaelcr** [comment]
> @fbwoolf @rafaelcr any idea whether the work on https://github.com/hirosystems/stacks-blockchain-api/issues/1342 might have helped prevent this?

I think so. The wallet could've detected the gap between the last mempool nonce and the last executed nonce to suggest the solution (RBF with nonce = 2)

**Comment by fbwoolf** [comment]
The logic in the wallet is not that simple. It can be reviewed here: https://github.com/hirosystems/stacks-wallet-web/blob/dev/src/app/query/stacks/nonce/account-nonces.utils.ts

@markmhx there is also a Notion doc that outlines the wallet logic as it was implemented. There are several edge cases it has had to address. We can scrap it if you want and start over.
