### ISSUE TITLE
When adding account it switches to another (older one)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2720]
When I add an account, I now switch to a seemingly random older account. I used to switch to the account that was just created. This looks like an issue that may only happen with a large number of keys on the account. Tested with over 100 keys.

**Comment by 314159265359879** [comment]
tested on both Firefox and Brave

**Comment by markmhendrickson** [comment]
Thanks for the report. By over 100 keys, do you mean accounts within the same wallet?

Any chance you could attach a video recording your screen when this happens for us to see the exact behavior?

**Comment by kyranjamie** [comment]
Can confirm, I noticed this earlier

**Comment by 314159265359879** [comment]
I have not been able to consistently reproduce but I have seen it very often by now. I think especially when I have not used the extension for some time. Or after an update. The first login will have this issue. Once logged in, locking and logging in again is usually no issue. For example now I have restarted the browser several times to login again and no issue. 

It happens on this screen after verify password, it will cycle through the additional message(s) "a bit more time" and the circle on the button will keep turning forever. 
![image](https://user-images.githubusercontent.com/33360391/195806261-effe34cb-0a9f-424a-89d6-8cbc10a16f1d.png)

**Comment by markmhendrickson** [comment]
@314159265359879 @kyranjamie have either of you seen this recently?

**Comment by 314159265359879** [comment]
I have not seen this since the report.

**Comment by pete-watters** [comment]
I retested this now and I cannot reproduce so closing this off. When I create a new account the wallet correctly renders that account.
