### ISSUE TITLE
Use decoded BNS punycode names for account labels

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2724]
Folks from in the BNS trading community [have been requesting in Discord](https://discord.com/channels/621759717756370964/621759718192447502/1030119884895555694) that the wallet display the emojis that are represented by any punycode values registered as BNS account names.

The idea here is that something like `🦋.btc` would show up at the top of the wallet for an account instead of (or perhaps better, in addition to) the raw punycode value for such an emoji (`xn--bt9h.btc` in this case). [See converter](https://www.punycoder.com/)

This would help make these registration types more useful and fun. We could later add support for other punycode representations such as non-latin language scripts.

<img width="777" alt="image" src="https://user-images.githubusercontent.com/28991/195833484-81cf6698-26a1-4fe3-b0e3-f05fed4e8075.png">

**Comment by ilzamy** [comment]
Emoji will be fun if implemented in .bns🚀

**Comment by GAD2511** [comment]
And also symbols like π, $... will be good too

**Comment by jeky138** [comment]
This feature is highly recommended because bns is supposed to be fun!

**Comment by solo88dolo** [comment]
Punycode is much better than Unicode for many reasons and should be supported. It's a pity this should be even discussed!

**Comment by dytsui** [comment]
Punycode safer .

**Comment by unter69** [comment]
yes

**Comment by mil7x0** [comment]
100% should be implemented. What's the point of building on Bitcoin if these centralized vc funded orgs don't want to do what the community wants? might as well go build on ethereum!

**Comment by dytsui** [comment]
https://coinyuppie.com/making-ens-farther-from-becoming-a-web-3-0-infrastructure/

**Comment by sevensato** [comment]
A must continue! This is the starting point for BNS to make it more unique, creative, and better than the others. Apply all emojis and also non latin language scripts to support punycode to hiro wallet. I completely agree on this!

**Comment by Stephens38** [comment]
Many of the community have already spent a very significant amount of time and money minting using Punycode. Punycode has proven to be safer than Unicode and it’s really what the community want and need. It’s going to really hurt the community unless it’s fully implemented. Please make it happen.

**Comment by seeyoooo** [comment]
hope the official can support the emoticon domain name earlier, and the emoticon will diversify the domain name.

**Comment by southguy** [comment]
wen snapshot and fork bns? first we need BNS DAO asap!

**Comment by JS-BadInfluence** [comment]
I completely agree with the sentiment here that we would all be grateful if you could please listen to the community and integrate punnycode. Thank you very much

**Comment by dltc258** [comment]
I completely agree ,, guys we been waiting for Emoji.btc  4 ever. Punycode is great and easy way. People smashing it with mint, There is just one step to make us happy. Thank you guys your work is great, and with this, we gonna smash web3 at all

**Comment by geraldohmygod** [comment]
Would definitely love punycodes to be implemented. Prefer to work around what's on the initial BNS contract and keep the originality

**Comment by concresha** [comment]
Please add puny . This is something that we the community want and would appreciate. Please hear our voices and let us have a say in this matter. Decentralization to moon 🚀

**Comment by yefan012** [comment]
just do it

**Comment by friedger** [comment]
The UI should indicate that it is a punny decoded name to reduce homoglyph attacks

**Comment by unter69** [comment]
Not only to increase expressions, but also to increase Chinese

**Comment by unter69** [comment]
Can it support Chinese and emoji?

**Comment by yefan012** [comment]
It is recommended to support Chinese and emoticons

**Comment by concresha** [comment]
We would like punycode because it’s more secure . Many ppl already hold
Chinese and Arabic domains via punycode. I won’t get scammed with a puny
emoji because I can check the punycode, not just look at the emoji.

**Comment by markmhendrickson** [comment]
We have a draft version of this enhancement here for everyone's review: https://github.com/hirosystems/stacks-wallet-web/pull/2744

Please take a look and let us know what you think!
