### ISSUE TITLE
Display Arabic number symbols also represented by Punycode for BNS accounts

### ISSUE THREAD

**Issue by Stephens38** [blockstack/blockstack-app#2726]
People from the Bns trading community would also like to get the Arabic number symbol to be displayed which are represented by punycode values. 

For example the symbol for 100 in Arabic is ۱۰۰ 
This converts to punycode xn--dmbab. 

Ens have an Arabic 999 club and everyone in Bns also wants an Arabic 999 club but we need the symbols showing in the Hiro wallet please.

**Comment by Stephens38** [comment]
![AD6784B4-761D-4631-8BFC-69B4AA162881](https://user-images.githubusercontent.com/115911320/196019520-15588276-511d-43fc-8797-4a8954438a14.png)

**Comment by edu-stx** [comment]
Hi @Stephens38, punycode support is in progress in #2744. All punycode transformations, including for Arabic characters, should be supported once the work is finished. Will close this issue in favor of #2724 where general punycode support is being tracked and discussed.

**Comment by Stephens38** [comment]
Thank you
