### ISSUE TITLE
Resolve error "Something went wrong" while broadcasting

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2733]
Reported by Stephens.btc#7717 on Discord. We plan to leverage https://github.com/hirosystems/stacks-wallet-web/issues/2727 to diagnose the underlying cause

<img width="615" alt="Screen Shot 2022-10-19 at 16 36 27" src="https://user-images.githubusercontent.com/28991/196722278-e43a1f98-4a50-4df8-b2b3-03f055596a44.png">

**Comment by markmhendrickson** [comment]
@314159265359879 mind working with Stephens on Discord to confirm whether this issue has been resolved? 

@kyranjamie can provide guidance on how to use the new diagnostic logging information (Kyran, perhaps worth writing these instructions up in a Notion doc we can then share publicly?).

**Comment by kyranjamie** [comment]
As this happened in the past, it wouldn't have been saved. 

To debug future issues, the user can hold <kbd>alt</kbd> while on the settings menu dropdown, copying the logs, and inspecting details for _Transaction broadcast_. The UX should be improved here, as failures shouldn't only be communicated in a vanishing toast.

**Comment by 314159265359879** [comment]
> @314159265359879 mind working with Stephens on Discord to confirm whether this issue has been resolved?
> 
> @kyranjamie can provide guidance on how to use the new diagnostic logging information (Kyran, perhaps worth writing these instructions up in a Notion doc we can then share publicly?).

Sure thing I will contact them.

**Comment by markmhendrickson** [comment]
This user has confirmed the issue is now resolved for them.
