### ISSUE TITLE
Provide a stronger message when signing out

### ISSUE THREAD

**Issue by edu-stx** [blockstack/blockstack-app#2748]
Some users coming from web 2 apps may not fully understand that signing out of the wallet without having a copy of their Secret Key will lead to a loss of their funds. Despite the wallet having a popup message warning users to save a copy of their Secret Key before signing out, as per [this user report](https://discord.com/channels/621759717756370964/745197302255321108/1032255793644458035), it seems this message may not be strong enough.

Small changes to the popup's design may help getting the message across. For example,

- making the text "Secret Key" bold 
- adding "loss of funds" (or similar) wording 
- adding a warning color background (yellow/orange) to the popup

may help better communicate the implications of signing out of the wallet.

**Comment by edu-stx** [comment]
Possibly something like this?
![sign-out-modal-lose-funds](https://user-images.githubusercontent.com/116000646/197360185-1363adeb-259e-4490-8c10-771eeb934477.png)

**Comment by markmhendrickson** [comment]
This modal could perhaps benefit from an illustration as well, one that conveys "warning".

**Comment by kyranjamie** [comment]
I would omit "Only sign out if you've backed up your Secret Key", if we add this warning text.

**Comment by edu-stx** [comment]
@markmhx aimed for an emoji at the beginning of the message, but as is rendered on my machine, got a less than ideal result. Can touch base with a designer if worth while.

![image](https://user-images.githubusercontent.com/116000646/197536967-5325abc0-a4a7-4a49-8126-c935e6747b75.png)


@kyranjamie Was looking to have a net increase in the overall message's strength, seems that adding a new sentence and removing the checkbox leaves it with a somewhat similar strength. If it gets in the way we'll probably get user feedback we can use to take further action, what do you think?
