### ISSUE TITLE
White sign screen, impossible to sign

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2750]
I have seen four of these reports from Alexians using the testnet at https://orderbook.alexlab.co I have not been able to reproduce this myself. I have seen it in the past using other dapps though. 

If there is something wrong with the dapp, which causes this, I think it will be great for devs to know what is causing this (could the wallet show a message instead of blinking/blanking). Some users have had success just restarting Chrome and it resolved this. For others that did not help. 

Any ideas, I have asked users to share console details, will add here later if I get any. 

Examples:
![image](https://user-images.githubusercontent.com/33360391/197289377-794a37b8-a8d3-4eb4-a948-ea23ab16f7f7.png)

![image](https://user-images.githubusercontent.com/33360391/197289810-2b5f729c-667a-4140-b914-27f22191c4c5.png)

![image](https://user-images.githubusercontent.com/33360391/197289895-bd781437-2c45-43f6-ba71-2d6da1b53f8a.png)

![image](https://user-images.githubusercontent.com/33360391/197290234-cdb33775-08ec-4266-9fb6-7269c97e2d16.png)

**Comment by 314159265359879** [comment]
A dapp developer once solved this issue for his dapp by "changing a wrong parameter" although later he did not recall exactly what it was. Maybe that will help a dev in the future or if someone else does recall they can add it here.

**Comment by 314159265359879** [comment]
One of the users reporting the white screen send these console errors:
![image](https://user-images.githubusercontent.com/33360391/197355837-6a9a2b06-df3e-4e88-b9c7-5f84e939f643.png)

`api.coingecko.com/api/v3/simple/price?ids=blockstack&vs_currencies=usd:1          Failed to load resource: the server responded with a status of 403 ()
api.coingecko.com/api/v3/simple/price?ids=blockstack&vs_currencies=usd:1          Failed to load resource: the server responded with a status of 403 ()
api.coingecko.com/api/v3/simple/price?ids=blockstack&vs_currencies=usd:1          Failed to load resource: the server responded with a status of 403 ()
api.coingecko.com/api/v3/simple/price?ids=blockstack&vs_currencies=usd:1          Failed to load resource: the server responded with a status of 403 ()
2instrument.js:109 SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at parse (<anonymous>)
(anonymous) @ instrument.js:109
scheduler.production.min.js:12 Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at parse (<anonymous>)
o204651.ingest.sentry.io/api/5963881/store/?sentry_key=1df7b7e43c4a4b80bdd8fa70e44f6cee&sentry_version=7:1          Failed to load resource: the server responded with a status of 403 ()
DevTools failed to load source map: Could not load content for chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/decryption-worker.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
utils.js:84          POST https://o204651.ingest.sentry.io/api/5963881/envelope/?sentry_key=1df7b7e43c4a4b80bdd8fa70e44f6cee&sentry_version=7 403`

**Comment by edu-stx** [comment]
Seems that the recently released 3.20.0 fixes white screen issues. Are you experiencing any issues with this version?

**Comment by markmhendrickson** [comment]
We suspect that https://github.com/hirosystems/stacks-wallet-web/pull/2743 will resolve this issue.

**Comment by kyranjamie** [comment]
This was likely fixed in a recent release. Reopen if the issue persists.
