### ISSUE TITLE
Hiro stacking reward problem

### ISSUE THREAD

**Issue by sharp1907** [blockstack/blockstack-app#2766]
Hello,

I run a stacking from cycle from #41 to #46, for cycle, I did not receive the reward yet.

My Hiro wallet address is SP15ZEDV9HKJ33E0QZNCHCXMJD0KAQHDZ633V1JVY
and reward BTC address is 1H6MJWJkDaATHuyLUJGKV2TTF4o2CZYCik (Binance exchange)

I run a stacking in Hiro Wallet for Desktop version.

I need to know what happened for rewarding process in #44 cycle.

Can you check this matter in your earliest convenience?

And, please send me the result to my e-mail address, lgdf4088@hanmail.net.

If you need any other information, please let me know.
![198189186-a19ef45b-04df-4dc5-a555-aae99955f498](https://user-images.githubusercontent.com/107832270/198199314-9a1da529-a05f-49a2-b924-ccffec9fca7d.png)

Thanks and best regards.

**Comment by markmhendrickson** [comment]
Rewards are not guaranteed for any given cycle even if you have a reward slot, though chances are higher the more reward slots you have. Given that you had 1 reward slot this particular cycle, it's not altogether surprising to have missed receiving BTC vs. a scenario in which you had more slots.
