### ISSUE TITLE
Audit request failing error handling

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2775]
- [x] #2776
- [x] #2777
- [ ] #2778

Purpose of this issue is to proactively diagnose possible issues where failing requests are handled with poor UX, or break the wallet. Currently, error handling is bad or non-existent in many parts of the app.

In investigating these issue, report findings, and propose solutions to problems found.

**Comment by markmhendrickson** [comment]
I've created a project ("Handle API issues gracefully") for this initiative since it's relatively broad in scope: https://hirowallet.notion.site/Handle-API-issues-gracefully-8d2f1ccaa0ee466db9cf5d19a887f5fd
