### ISSUE TITLE
Support partial data loading for balances and activity

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2776]

**Comment by edu-stx** [comment]
Reminder for when I come back to this later,
* App fails when networks are down. If main/test/dev-net are down, the app crashes and shows blank screen

**Comment by edu-stx** [comment]
Observation from balances list, `src/app/features/balances-list/balances-list.tsx`,

- Up to 2 network requests: 1) for btc, 2) for stx, stx ft, stx nft. The page shows any data available, or empty state in case of error no data, or loading.
- we may want to revisit later as ux isn't optimal: what to display at any given time and for the different combinations of loading/error/success across the two requests? Currently no spinners are shown when loading.

Similar observations as above for the activity list, `src/app/features/activity-list/activity-list.tsx`, and additionally,

- The spinner will show up multiple times on subsequent retries when the first request fails. The `isInitialLoading` variable being used resets when the first request fails.

If a better way of handling the spinner is suggested or comes to mind, I'll implement it. In any case, cautious that it seems that it is good enough for now and we'd probably want to tackle it as a broader UI/UX error handling effort across the app.

On my [comment above](https://github.com/hirosystems/stacks-wallet-web/issues/2776#issuecomment-1300692411), wasn't able to reproduce, seems it's fixed now.

**Comment by markmhendrickson** [comment]
This requires some UI explorations on how best to handle the various combinations / cases

**Comment by kyranjamie** [comment]
Closing in favour of #4787
