### ISSUE TITLE
UI improvments - esp for power users

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/blockstack-app#2795]
Suggested UI improvements:

- **clickable components should be obvious**
When opening the app the round icon to the left of the account name/heading - I didn't realize it was a clickable button you could use to switch accounts so I was always doing it using the (...) menu which requires 3 clicks versus 2.  
I think it and maybe **all UI components** that are clickable have graphics that indicates as such, for example a small upward-pointing-hand icon overlaid on the clickable item.  So, on the _Balances_ tab the assets are not clickable so have no overlay but on the _activities_ tab the clickable events have the overlay.

- **mouse-over context sensitive help** 
Wherever it makes sense, when you mouse over a UI component you should see some helpful text of what that does. 
Or if it's text you get extra text helpful info that otherwise would not fit in the space available to the UI.

- **Multiple accounts sort order** (better for advanced users)
When selecting (to change) the list is sorted chronologically by date created, oldest to newest.
A better sort order is by order of **transaction events in the accounts**, most recent first.  This helps a user to find out what has transpired **in all of their accounts** since the last time the app was used.  If not, it can be time consuming for users with many accounts.  Also this ordering would match how things are displayed in the account-activity tab.
  
- **Use colors for event icons** to make status more obvious
the icon overlays that are small circles with a up or down tx arrows or (f) for smart contract calls are not easy to distinguish at a glance when looking at a list of events.  Using icon colors could help this.  For example:
 received-down-arrow circle - blue
 sent-up-arrow circle - green
 in progress transaction - orange
 failed transaction - red

- **xBTC no arrow icon overlay.**  It should have had a down-arrow in my case of having received it. It might not sound like a big deal but it's no fun to open you wallet and see what could be outgoing events that you didn't initiate... "did I just get hacked (panic)?" 

-  **STX and Wrapped-STX token icons should be different**
In the _activities_ tab both STX and wSTX show the same icon. Ideally these should look different.

**Comment by fluidvoice** [comment]
regarding the first item above - **clickable components should be obvious**
I was talking to Dan Trevino yesterday and it was news to him too - he didn't know that icon was a functional button.

**Comment by fluidvoice** [comment]
Btw, I think the block explorer should adopt the same colored icons with up/down arrows... green for incoming and red or orange/yellow for outgoing.

**Comment by markmhendrickson** [comment]
Thanks @fluidvoice! Mind breaking these up into individual issues so we can categorize and track them better?

Also, for any explorer-specific enhancements, it'd be best to file them here: https://github.com/hirosystems/explorer/issues

**Comment by 314159265359879** [comment]
Closing in favor of individual issues. Thanks for the initial writeup Brad!

Find individual items here (in order as above):
https://github.com/hirosystems/stacks-wallet-web/issues/2877
https://github.com/hirosystems/stacks-wallet-web/issues/2878
https://github.com/hirosystems/stacks-wallet-web/issues/2879
https://github.com/hirosystems/stacks-wallet-web/issues/2880
https://github.com/hirosystems/stacks-wallet-web/issues/2881
https://github.com/hirosystems/stacks-wallet-web/issues/2882

**Comment by fluidvoice** [comment]
oh, thanks for doing this.
