### ISSUE TITLE
wrong USD account value displayed

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/blockstack-app#2797]
When attempting to switch accounts the list shows one account with 25000 STX in it has a value of only $79.28
Using Chrome Version 107.0.5304.87 (Official Build) unknown (64-bit) on Linux
and Hiro v3.22.0 wallet.

**Comment by markmhendrickson** [comment]
I believe this should be fixed in v3.22.1 per https://github.com/hirosystems/stacks-wallet-web/releases/tag/v3.22.1 given the work done on https://github.com/hirosystems/stacks-wallet-web/pull/2792

Mind checking to see if it works on that particular version?

**Comment by fluidvoice** [comment]
ah yeah. I'm using v3.22.1 and I just saw (after new login) that it's being displayed correctly.
I don't know if it was just a matter of a new logout/login?  But OK, you can close this issue.

**Comment by markmhendrickson** [comment]
Glad to hear it!
