### ISSUE TITLE
Logout while locked

### ISSUE THREAD

**Issue by obycode** [blockstack/blockstack-app#2801]
I used to be able to log out of an account while the current account is locked, i.e. without first putting in the password for the current account. Now, I can only log out after unlocking the current account. This is a minor issue, but the old way makes sense and is better for users.

v3.22.1 on Chrome

**Comment by fbwoolf** [comment]
@edu-stx could removing this be the problem here?
https://github.com/hirosystems/stacks-wallet-web/pull/2786/commits/ce7ad3caa814abe7639030ebce44b3fbd90f74cb

**Comment by fbwoolf** [comment]
It appears the sign out drawer is not popping up ...instead the password field becomes focused.

**Comment by fbwoolf** [comment]
I actually think this PR on dev already fixed the issue: https://github.com/hirosystems/stacks-wallet-web/pull/2785

**Comment by fbwoolf** [comment]
I am going to close this and link to the merged PR that fixed it. It should be in the next release, thx @obycode for reporting.
