### ISSUE TITLE
Trim whitespace from address values in send form

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/blockstack-app#2806]
a couple of minor things I just noticed with v3.22.1

Sending with an address with a leading or trailing space is not accepted "invalid address" error.
This could confuse some users, so why not strip (commonly pasted) leading and trailing white-space before validating an address?

When I sent a Tx I got a "Nonce conflict" error. But the tx went through and according to the Explorer the nonce was 4 and the prior tx was 3 so it looked fine n not sure why the error msg.

**Comment by markmhendrickson** [comment]
Thanks @fluidvoice 

@fbwoolf thoughts on why the nonce error may have shown briefly even though the nonce was okay?

I'll rename this issue so it focuses on the address value trimming enhancement in particular.

**Comment by fbwoolf** [comment]
> @fbwoolf thoughts on why the nonce error may have shown briefly even though the nonce was okay?
> 
I don't, nothing changed with nonces in the last release. That would be more specific to showing a broadcast error I think rather than a nonce issue.

**Comment by markmhendrickson** [comment]
cc @314159265359879 so he can keep an eye out for other reports of incorrect flickering error messages and file an issue if this seems recurring

**Comment by fluidvoice** [comment]
yesterday and the day before the nonce error happened again to me using **v3.23.0.** 
**Both times the tx did not go through**, then did on second attempt.  Yeah, could be a broadcast issue. Or, if this is happening **only to me**, maybe my ISP is creating some kinda tx broadcast latency that's exposing this? How do I help debug this?  btw, I'm using wifi-to-fiber router connection.

**Comment by 314159265359879** [comment]
Fluidvoice I pinged you in the other thread, I decided to make a separate issue which makes it easier to track.

**Comment by kyranjamie** [comment]
<img width="418" alt="image" src="https://github.com/hirosystems/wallet/assets/1618764/dc224978-43d1-4caa-9676-d0e33475b3ce">

Address not valid because of space at end
