### ISSUE TITLE
Add app-wide option for getting support

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2823]
Users currently have no way to find support from within the wallet itself. We should add an app-wide way to find it, even if later we add more specific contextual prompts based on particular flows or errors.

For example, we could add it in the app menu or header:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/28991/200565070-dd0b0ae3-58f1-4572-9b85-68aaee4167d2.png">

It could link to our support FAQ, where we intend to add more content (e.g. where to submit a support ticket): https://wallet.hiro.so/wallet-faq/where-can-i-find-support-for-the-stacks-wallet

cc @314159265359879

**Comment by markmhendrickson** [comment]
"Get support"

**Comment by edu-stx** [comment]
Would this work?
![image](https://user-images.githubusercontent.com/116000646/203110816-3f062060-f3a7-4825-92d2-04f04d174c47.png)

**Comment by markmhendrickson** [comment]
cc @314159265359879 wdyt?

**Comment by edu-stx** [comment]
@314159265359879 have you had a chance to take a look at it? If you haven't seen it yet, there's a build you can try out in #2883
