### ISSUE TITLE
Support app requests to sign BTC transactions

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2824]
As raised on https://github.com/hirosystems/connect/issues/283 and previewed with https://twitter.com/markymark/status/1582379165168254977

SIP needed: https://github.com/stacksgov/sips/issues/105

![image](https://user-images.githubusercontent.com/28991/200569931-17e024ab-7cde-461c-907b-7d6bc6b96c36.png)

**Comment by markmhendrickson** [comment]
@mica000 I believe the main thing missing from this early mockup is the ability to set fees, which we could drop in above the send button:



![Image](https://user-images.githubusercontent.com/28991/218311099-6adaf014-e835-4c6d-999a-d3a55110f1ee.png)

**Comment by markmhendrickson** [comment]
Relevant to this work in anticipation of extended functionality: [BIP-0322](https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki) and [BIP-0174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki)

**Comment by mica000** [comment]
Choosing a BTC fee has been updated on a separate user flow:
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1110%3A54471&t=Shl5eSB4xRFAbQkH-4

**Comment by markmhendrickson** [comment]
Makes sense! Mind updating this initial screen e.g. removing fees and total since that'll come later? I imagine you have ideas for how to spruce it up in general, too.

**Comment by markmhendrickson** [comment]
Makes sense! Mind updating this initial screen e.g. removing fees and total since that'll come later? I imagine you have ideas for how to spruce it up in general, too.

**Comment by markmhendrickson** [comment]
I've modified this issue to include both fully and partially signed transactions, either broadcasted by the wallet or simply returned to the app.

**Comment by markmhendrickson** [comment]
Speaking with @mica000 about this, it's like the new confirmation screen found [here](https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1065%3A58518&t=qUFkvvCsjBsMXk1D-1) but will a standardized app request header unit:



![Image](https://user-images.githubusercontent.com/28991/224320366-5d400b4d-deb2-4de8-9c0f-7325a11f811f.png)

**Comment by igorsyl** [comment]
@radicleart would use this immediately for sBTC bridge bitcoin transactions.

**Comment by mica000** [comment]
First draft...

Would something like this work?

<img width="1205" alt="Screenshot 2023-03-13 at 22 53 22" src="https://user-images.githubusercontent.com/119523541/224840606-e135ee26-30ec-4e61-ae36-58ca9d0b6394.png">

**Comment by markmhendrickson** [comment]
Looks generally good! Though we should move the fee setting to a subsequent modal just like we want it for regular BTC sends in the wallet, yea?

**Comment by markmhendrickson** [comment]
Also header should be more like "Send Bitcoin" than "buy-in-ustx"

And note how we'll have the app's domain (and favicon) here but not its name per se.

**Comment by mica000** [comment]
Updated design: https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=2348-92231&t=CDUjNDev3ezZG5Su-4

**Comment by mica000** [comment]
> First draft...
> 
> Would something like this work?
> 
> <img alt="Screenshot 2023-03-13 at 22 53 22" width="1205" src="https://user-images.githubusercontent.com/119523541/224840606-e135ee26-30ec-4e61-ae36-58ca9d0b6394.png">

@markmhx @fbwoolf are these design still relevant?

**Comment by markmhendrickson** [comment]
@mica000 hmm relevant how so? I'd say replace with whatever design you want implemented these days. I don't believe @fbwoolf has started on this UI work yet iirc

**Comment by fbwoolf** [comment]
> @mica000 hmm relevant how so? I'd say replace with whatever design you want implemented these days. I don't believe @fbwoolf has started on this UI work yet iirc

Nope, I haven't started this yet.

**Comment by crypticmeta** [comment]
would this enable us to do a tx with both segwit and taproot address?

example: 

payment with btc
receive ordinal with taproot 

I tried implementing this using PSBT, but failed miserably.

**Comment by markmhendrickson** [comment]
@crypticmeta Yep! We intend for it to work with both types.
