### ISSUE TITLE
Support structured data message signing with Ledger devices

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2827]
Zondax have released a [new version of the ledger app supporting structured message signing](https://github.com/Zondax/ledger-stacks/releases/tag/npm_v1.0.3).

This needs to be tested against apps known apps using structured message signing.

**Comment by markmhendrickson** [comment]
@MarvinJanssen have some ideas of what apps we should test here?

**Comment by markmhendrickson** [comment]
@kyranjamie to set up new tests in test app with @edu-stx

**Comment by markmhendrickson** [comment]
Related: https://github.com/Zondax/ledger-stacks/releases/tag/npm_v1.0.3 https://github.com/LedgerHQ/app-blockstack/pull/20
