### ISSUE TITLE
Incorrect decimals of balance in send form

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-app#2828]
The balance is shown using 6 decimals even though the token uses 8 decimals.

E.g. for xbtc. It would be nice if Friedger Pool would be that rich :-)

![image](https://user-images.githubusercontent.com/1449049/200824454-0f3cb0f9-2b80-448a-a683-fb51e56f81e1.png)

**Comment by 314159265359879** [comment]
Thanks for reporting Friedger, we'll want the balance field to take into account the decimals defined in the contract just as the field under amount does (or in the balances section of the wallet). 
![image](https://user-images.githubusercontent.com/33360391/201037447-27070cdd-4435-4f95-9405-f221e903d296.png)
