### ISSUE TITLE
Inserting js code into textarea while editing wordpress page with elementor

### ISSUE THREAD

**Issue by studiowena** [blockstack/blockstack-app#2830]
Hi,

Your extension on Mozilla Firefox inserts jscripts code into textarea while editing wordpress page with elementor. It inserts
`<script id=\"stacks-wallet-provider\" src=\"moz-extension:\/\/\/inpage.js\"><\/script>`

**Comment by markmhendrickson** [comment]
Thanks for the report. We're tracking this issue here for resolution already: https://github.com/hirosystems/stacks-wallet-web/issues/2604
