### ISSUE TITLE
Users accidentally click "create new account" and do not realize it

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2843]
I have had two cases this week, perhaps this happens more often. 

The users that do not realize what happened, see 0 STX, miss their other tokens and fear they have lost all their funds. Anything we can do UX wise?

**Comment by markmhendrickson** [comment]
A quick option could be to simply remove it from the app nav and leave it for selection here at the bottom of the accounts selection modal:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/28991/202188323-116c4c15-2fcf-4e0d-aacd-168c23c956f3.png">

**Comment by kyranjamie** [comment]
+1 to removing from settings dropdown. Account management should be in the same modal.
