### ISSUE TITLE
[Bitcoin] Derivation path and address type

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2845]
A couple of questions from the community. 

1. Has it been decided which derivation path the Hiro Wallet will use when Bitcoin support is added?
2. Which options are being considered, or what has the decision landed on?
3. What Bitcoin address format will be used? 

Jason mentioned Xverse uses a wrapped segwit address and Algorithm.btc mentioned that he would like to see compatibility with the xverse wallet. 

relevant Stacks forum discussion here: https://forum.stacks.org/t/rfc-standardizing-on-bitcoin-derivation-paths/13394

**Comment by 314159265359879** [comment]
Here is a copy of Mark's answer to 3.
![image](https://user-images.githubusercontent.com/33360391/201727760-0ef7bbc7-458a-4243-8c1d-2ceb368bc993.png)

**Comment by markmhendrickson** [comment]
cc @fbwoolf @kyranjamie who can provide input on questions 1 and 2

**Comment by kyranjamie** [comment]
The working assumptions are that:

- We will use standard bitcoin derivation paths
- We will use Native SegWit addresses `bc...`

These are not set in stone, but interoperability with another Stacks wallet shouldn't necessarily be our top priority imo (it'd also means less interoperability with btc wallets). Consider that the constraints faced by Xverse, when they opted to use Wrapped SegWit, are not necessarily the same as when we will make a decision
