### ISSUE TITLE
[Bitcoin] Account restoration

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2887]
- As part of this feature, we should remove the dependence on Gaia
- When restoring wallets, check the first 10 STX and BTC addresses
    - Consider BNS names
- After 10 empty addresses are not found, stop checking
- Aids users reusing seed phrases

**Comment by kyranjamie** [comment]
First part of this task is removing dependency on Gaia, which requires refactoring to query BNS names, and not depend on `restoreWalletAccounts` from WalletSDK.

**Comment by markmhendrickson** [comment]
Is this issue resolved so we can close?
