### ISSUE TITLE
Add Ledger support for Bitcoin and Ordinals

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2893]
[Spec from @markmhx:]

Users want the ability to connect their Ledger devices to the wallet for the purposes of managing BTC and Ordinals holdings with them in addition to the existing ability to connect such devices for Stacks-related holdings.

Here are the use cases involved in this enhancement:

1. New users can select "Connect with Ledger" from the "Get started" page then indicate that they wish to connect the "Bitcoin app" on their device (alongside a new explicit option to connect the "Stacks app"), in contrast to the current default flow in which users who select "Connect with Ledger" are defaulted into connecting just their Stacks app.
2. Existing Ledger users who have already authenticated to the wallet with the Stacks app can indicate they wish to connect with the Bitcoin app on their device, resulting in connections for both the Stacks and Bitcoin apps.
3. Existing Ledger users who have already authenticated to the wallet with the Bitcoin app can indicate they wish to connect with the Stacks app on their device, resulting in connections for both the Stacks and Bitcoin apps (this is the inverse need of case 2 above)

With case 1 above, users will be able to use all Bitcoin-related features in the wallet but not Stacks ones (e.g. users can view Bitcoin and Ordinals receive addresses upon selecting "Receive" but not Stacks-related addresses).

With cases 2 and 3 above, users will be able to use both Bitcoin and Stacks-related features in the wallet at the same time (akin to how software wallets provide access to both sets of features, e.g. they'll see receive addresses for both Bitcoin and Stacks-related deposits).

Here are use cases that are *not* involved in this enhancement:

4. Existing software users can connect either the Bitcoin or Stacks app on their Ledger device without having to sign out first / to view their software wallet alongside their Ledger wallet.  We are **not** looking to do this as part of this enhancement because it would create too much complexity at this time to support software and Ledger wallets in the same session. This can be handled as a separate effort with https://github.com/hirosystems/wallet/issues/2570
5. New users can select "Connect with Ledger" from the "Get started" page then indicate that they wish to connect both the Bitcoin app and Stacks app at the same time. There are technical reasons why we can't make this a one-click connection process for both apps on the Ledger device, and while we may want to enhance the onboarding UX later so that users can sequentially connect both apps during onboarding, we will have already covered the need to connect both apps with cases 2 and 3 above. Therefore, I suggest we keep things simple for this particular enhancement and onboard users with just one Ledger app at a time then let them connect the other post-onboarding.

**Comment by markmhendrickson** [comment]
@kyranjamie @mica000 I've added a specification with use cases to this issue's description above. Please take a look and let me know if it makes sense and resonates with the way you're thinking about this effort.
