### ISSUE TITLE
Resolve delay in recognizing confirmed transactions

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2898]
Here transaction in microblock
![image](https://user-images.githubusercontent.com/33360391/203271913-f45bc6f7-5d53-43a5-84be-e28b17fb5834.png)

Yet on wallet shown as available

trying to sign a transaction will fail because the balance isn't actually available:
![image](https://user-images.githubusercontent.com/33360391/203272579-8eaafcdb-8ea0-4530-8940-6eadd70de36f.png)

This is happening on mainnet too:
https://discord.com/channels/621759717756370964/745197302255321108/1044462352642363412

Additionally when the transaction was confirmed in an anchorblock. I tried to send the transaction again from the btc.us testenvironment. And it would still show "insufficient" balance error on the confirm screen. I was only able to resolve this after logging out from the dapp and then logging in again, then the confirm screen still blinked "insufficient balance" for a split second before showing the expected:
![image](https://user-images.githubusercontent.com/33360391/203275262-8ea33827-9a3f-498a-b53c-89f10525f485.png)

**Comment by 314159265359879** [comment]
Steps to reproduce on testnet:
1. create new account
2. get funds from faucet via explorer sandbox
3. login on https://btc-website.tintashlabs.com/ (when faucet transaction is in microblock, before confirmed in anchor)
4. Try to register a domain
5. --> try to sign first transaction
6. see error

**Comment by 314159265359879** [comment]
I would expect the balance not to show as available as long as the transaction is only in a microblock and not anchored yet. This is adding to the confusion. 

After being anchored I would expect not to see any "insufficient balance" errors. I am not sure why I need to relog on the dapp.

**Comment by markmhendrickson** [comment]
> I would expect the balance not to show as available as long as the transaction is only in a microblock and not anchored yet. This is adding to the confusion.

I agree. It's unexpected and incorrect to include microblock amounts in the app nav balance here. We should update to show just anchored amounts.

> After being anchored I would expect not to see any "insufficient balance" errors. I am not sure why I need to relog on the dapp.

To be clear here, you had to sign out of the dapp itself and re-authenticate entirely? Not just close the transaction signing window and reopen it with the app-based action?

I can't imagine why re-authenticating the app should affect the behavior here, so I suspect it may have been simply a question of timing in that the wallet hadn't yet recognized the anchor block.

Mind trying to recreate this problem but waiting 1 minute after the transaction is included in an anchor block to see if the wallet recognizes it?

> then the confirm screen still blinked "insufficient balance" for a split second before showing the expected:

This sounds like a visual bug of sorts we should also iron out, if this error is showing incorrectly during load for accounts that do have sufficient balances.

**Comment by 314159265359879** [comment]
> To be clear here, you had to sign out of the dapp itself and re-authenticate entirely? Not just close the transaction signing window and reopen it with the app-based action?
> 
That is correct, re-authenticating. 

> I can't imagine why re-authenticating the app should affect the behavior here, so I suspect it may have been simply a question of timing in that the wallet hadn't yet recognized the anchor block.
> 
> Mind trying to recreate this problem but waiting 1 minute after the transaction is included in an anchor block to see if the wallet recognizes it?

Yes I can recheck that. Also waiting to hear back from another user.

**Comment by 314159265359879** [comment]
@markmhx 
This is two minutes after the anchor block confirmation
(after 6 minutes it is fine without re-authenticating, see further down but wallet balance updating so slowly is a problem)
![image](https://user-images.githubusercontent.com/33360391/203290340-17e5d36c-5c9e-4cfe-8ec1-66babd2a964b.png)

![image](https://user-images.githubusercontent.com/33360391/203290572-00c98720-de2a-43e2-bb3d-47f4b2162b7d.png)

oddly the wallet shows:
![image](https://user-images.githubusercontent.com/33360391/203290903-dafb122f-0503-4fda-a1e4-3c4d69c6f81d.png)

with this in the activities tab (upto 5 minutes after the anchor block):
![image](https://user-images.githubusercontent.com/33360391/203290968-24f83aab-ad32-43a5-8585-f25cce3465c3.png)

This is what Bruffstar was reporting earlier in the wallet channel on Discord.


This is 6 minutes after the anchor block... all good (no re-authentication needed)
![image](https://user-images.githubusercontent.com/33360391/203291698-d3c5870a-bfb6-4925-ab58-0b425b61af3d.png)

(6 minutes is not normal, different issue most likely something with API service?)

**Comment by markmhendrickson** [comment]
Are you checking the explorer specifically for confirmation and it does show as confirmed there _before_ the wallet? If so, that might suggest it's a wallet-specific problem because the explorer and wallet are using the same API.

However, it's also possible they're using different endpoints with different behaviors here.

I'm going to relabel this as P2 at least until we get reports that these delays are widespread. Mind splitting the problem with displaying microblock effects in the app nav balance into a separate issue for tracking there as a P2?
