### ISSUE TITLE
Track app domain as event property within app-initiated flows

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2904]
Whenever an app initiates a wallet flow for the user, we should include a new property for all events triggered within that flow that contains the domain of the initiating app.

For example:

- App initiates user authentication
- App initiates transaction signing

The property should be included from the point of initiation until the closing of the relevant wallet window, and it should be included only for events that are triggered within that specific flow (and not, for example, for events triggered simultaneously in a separate window open for the wallet).

It could be named something like `referringAppDomain` and should include the complete base URL of the referring app (e.g. `https://example.org` not `example.org/path/to/page`).

This will enable us to measure the amount and types of wallet usage driven by particular apps.

**Comment by markmhendrickson** [comment]
I'm reopening since I'm unable to see the `flowInitiatorURL` come through in production, and my sense is that we need to modify this to `flowInitiatorDomain` for it to be most useful in report generation.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/28991/207051988-cafd3ddf-3660-454a-96d1-6aedcf94522a.png">

**Comment by edu-stx** [comment]
Ended up using the `referringAppDomain` property, and didn't update the screenshot. Is `referringAppDomain` available in the dashboard?

We can set whatever name is most convenient.

I'll update the comment on the PR to match the code.

**Comment by markmhendrickson** [comment]
Note that we ended up using property `origin` instead of `referringAppDomain` or `flowInitiatorDomain` and the value appears to be reported accurately in production.
