### ISSUE TITLE
Ledger sends transaction with active account on wallet extension rather than account logged into

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2906]
Steps to reproduce
1. Switch extension to display **account X** balances
2. Login to explorer sandbox with **account Y**: https://explorer.stacks.co/sandbox/deploy?chain=mainnet
3. Go to pox contract
4. pick a contract call for example revoke-delegate-stx 
5. And call function
6. See error on confirm/ledger screen: asks to confirm transaction send from **account X**. 

I would expect the wallet to only ever send transactions with the account I am logged in with regardless of what the extension is displaying.

In software wallet mode this issue does not exist.

**Comment by 314159265359879** [comment]
2. also reproduceable with https://stacks-pool-registry.pages.dev/pools/1 which is a dapp to delegate stacking.

**Comment by kyranjamie** [comment]
Seems that the `stxAddress` isn't sent in the payload to the wallet when in Ledger mode. As it isn't found, the wallet defaults to the active account.

**Comment by kyranjamie** [comment]
See PR opened in connect https://github.com/hirosystems/connect/pull/289
