### ISSUE TITLE
Fix error boundary to correctly handle and log errors

### ISSUE THREAD

**Issue by edu-stx** [blockstack/blockstack-app#2921]
The app's error boundary isn't set up to properly handle errors, they are just re-thrown and no usefull message is shown to users.

handler declared here,
https://github.com/hirosystems/stacks-wallet-web/blob/8788e010b9504f1cfa5c8f2c619af19da240dbc8/src/app/features/errors/error-boundary.tsx#L154-L159
passed as arg here (TS accepts the different fn signature)
https://github.com/hirosystems/stacks-wallet-web/blob/8788e010b9504f1cfa5c8f2c619af19da240dbc8/src/app/features/errors/app-error-boundary.tsx#L52-L65
called here,
https://github.com/hirosystems/stacks-wallet-web/blob/8788e010b9504f1cfa5c8f2c619af19da240dbc8/src/app/features/errors/error-boundary.tsx#L94-L96

**Comment by pete-watters** [comment]
Closing this in favour of #3986
