### ISSUE TITLE
Prevent FT symbol from injection in amount field upon selection of "Max" in send form

### ISSUE THREAD

**Issue by ghost** [blockstack/blockstack-app#2922]
<img width="401" alt="스크린샷 2022-12-06 오후 6 17 21" src="https://user-images.githubusercontent.com/35640822/205871081-a0bc309e-a6a8-44d8-aa45-d01f69cfb912.png">

When clicking the Max button, not only the number but also the asset symbol is entered.

**Comment by markmhendrickson** [comment]
I've confirmed this incurs a validation error:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/28991/205916820-04705bc2-0457-49c3-bade-253b7fcd34af.png">
