### ISSUE TITLE
Fix onboarding flash of fund page

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2926]
During onboarding, if a user has STX in their wallet, there is now a flash that shows the fund page before routing a user to the home page. Something must have changed recently to expose this and we should handle it better so the user doesn't see the flash.

**Comment by kyranjamie** [comment]
To avoid this in future, recommend this fix moves the conditionality of the routing to the place where the `navigate` is called (rather than routing to the page, and checking there)

**Comment by markmhendrickson** [comment]
@fbwoolf I have a faint recollection that you may have resolved this? I also haven't noticed the behavior recently myself.

**Comment by fbwoolf** [comment]
I added a loading spinner to hopefully resolve the flash, but addressing the concern Kyran mentioned above is a bit more tricky bc the navigate happens on the set password step where the balances aren't available yet to check if they need STX. We could just always route to the `Fund` page and let the user skip it even if they have STX?

**Comment by markmhendrickson** [comment]
> We could just always route to the Fund page and let the user skip it even if they have STX?

Yea might be easiest

**Comment by pete-watters** [comment]
@fbwoolf : I was checking this and it seems like this has been resolved. Are you happy to close it off?

**Comment by fbwoolf** [comment]
Yep, will close.
