### ISSUE TITLE
Blank screen - Resolution of currency  is unknown, must be described

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-app#2931]
When unlocking the extension I see a blank screen. 

The console log shows
```
Resolution of currency  is unknown, must be described
```

Testnet 
Version 3.27.0

**Comment by kyranjamie** [comment]
When does this happen? Any more details?

**Comment by friedger** [comment]
I even removed the extension, then signed in, switched from mainnet to testnet and saw the message.

**Comment by markmhendrickson** [comment]
@friedger is the behavior you're seeing different than on https://github.com/hirosystems/stacks-wallet-web/issues/2935?

**Comment by friedger** [comment]
@markmhx Yes, the same

**Comment by markmhendrickson** [comment]
Thanks, closing as dupe then
