### ISSUE TITLE
Pending incoming transaction results in wrong nonce selection for new transactions

### ISSUE THREAD

**Issue by badonyx** [blockstack/blockstack-app#2933]
I submitted a TX with my account's nonce X, then received an incoming transfer with other account's nonce Y << X, and then while that was pending I tried to submit another TX from my account which was assigned nonce Y+1. This obviously doesn't work so the wallet then gives me the error that the TX could not be submitted due to incorrect nonce. I can edit it to the correct nonce X+1 but this is obviously faulty behavior.

**Comment by 314159265359879** [comment]
Thanks for reporting @0xBabo! that should not happen indeed. Would you mind sharing some more details, what version of the wallet were you using and what dapp?

**Comment by kyranjamie** [comment]
@fbwoolf could it be we're not filtering inbound txs from the pending txs passed in here?

https://github.com/hirosystems/stacks-wallet-web/blob/90f786d7ec992aeff483dc3ebe07b749d535192c/src/app/query/stacks/nonce/account-nonces.utils.ts#L66-L71

**Comment by fbwoolf** [comment]
@kyranjamie we do filter it here:

https://github.com/hirosystems/stacks-wallet-web/blob/281736d45b9bd7099b2da4c6d1508ca7aad5a1dd/src/app/query/stacks/nonce/account-nonces.utils.ts#L90

**Comment by fbwoolf** [comment]
I see the issue here with ^ that code so I can fix.
