### ISSUE TITLE
Wallet extension windows turns tiny/blank when connected to stacks.co testnet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2935]
Reported by Tycho who shared this video: https://www.loom.com/share/a91993a994624b2fb21ae4cb8e9a14be

![image](https://user-images.githubusercontent.com/33360391/206931708-025c7e95-4fe8-45ad-bfbf-6fce0329bdeb.png)

I believe this may have been introduced with 3.27.0, although it may be related to the testnet connection itself because when I use the alextest network details, this does not happen: 
![image](https://user-images.githubusercontent.com/33360391/206931770-d9f92770-f7e9-4f3b-b6d1-06f368ca0a8c.png)

Switch to stacks.co testnet and it is again an issue. 

Latest Chrome, windows and mac.
Alextest details:
![image](https://user-images.githubusercontent.com/33360391/206931843-14d15b3a-b1e0-4634-8a0b-7ddb8d958a27.png)

**Comment by tycho1212** [comment]
Hi @kyranjamie and @314159265359879 this issue persists unfortunately

**Comment by 314159265359879** [comment]
> Hi @kyranjamie and @314159265359879 this issue persists unfortunately

Did you check out one of the dev builds? Which one? I saw it resolved in this one: https://github.com/hirosystems/stacks-wallet-web/actions/runs/3674758120

Note: not yet released on chrome/firefox

**Comment by tycho1212** [comment]
Ah thanks! I mistakenly thought this was marked as completed
