### ISSUE TITLE
[Bitcoin] Create confirmation page

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2937]

**Comment by markmhendrickson** [comment]
Need design input on this from @mica000? Let's get the design linked here and reviewed in any case.

**Comment by mica000** [comment]
Sure! Is this user flow still up to date? @markmhx @fbwoolf 
https://www.figma.com/file/o0VSeFzhYI2GgnDcX0NPmU/User-lifecycle-flow?node-id=849%3A599&t=4Lb8KTFDpIF7S4Hy-4

**Comment by markmhendrickson** [comment]
That user flow looks generally right to me at first glance.

**Comment by fbwoolf** [comment]
> Need design input on this from @mica000? Let's get the design linked here and reviewed in any case.

Design is here: https://www.figma.com/file/uWutVORXsNUqdrHS0F07jG/%F0%9F%93%A4-Send?node-id=2%3A7&t=jJTKd5ibBx3FoBF4-0

I will link working PR to this issue.
