### ISSUE TITLE
Fix display of microblock icon for transactions in activity

### ISSUE THREAD

**Issue by JackNapolitano** [blockstack/blockstack-app#2944]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/6842529/208128728-5c4c2d85-05c5-4192-92f3-079e46292797.png">

**Comment by kyranjamie** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/1618764/208134310-a9fcd939-dd53-4f9c-a1b2-e40b0cd5c3ad.png">

Just tested this and see the microblock icon 🤔

**Comment by JackNapolitano** [comment]
which version are you on and which API are you pointing at?

I am on v3.28.0 and pointing at the stacks-node-api.stacks.co API

**Comment by markmhendrickson** [comment]
@314159265359879 mind trying to confirm?

Although I suspect the underlying problem here might be https://github.com/hirosystems/explorer/issues/885

**Comment by markmhendrickson** [comment]
I'm not seeing the right icon myself today while testing:

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/28991/208432065-8fd41322-32d1-4178-bce8-a1b40f0ab1e9.png">

Could this be given a difference between simple transfers and contract executions?

**Comment by 314159265359879** [comment]
> @314159265359879 mind trying to confirm?
> 
> Although I suspect the underlying problem here might be [hirosystems/explorer#885](https://github.com/hirosystems/explorer/issues/885)

I don't believe this is related to [#885](https://github.com/hirosystems/explorer/issues/885). I believe the icon is only shown on normal STX transfers and not on contract calls in microblocks. Contract calls in a microblock or anchor block are not shown differently in the activities tab, they look anchored in both cases. 

It looks like this can be improved. Perhaps in conjunction with the suggestion here? https://github.com/hirosystems/stacks-wallet-web/issues/2880 using different colors for the type of confirmation or transactions or:

If the finality of microblocks is still limited (chance for reorg is still big) why not display it more like pending:
![image](https://user-images.githubusercontent.com/33360391/212551009-a37f1f85-795b-4041-a82e-e248f242c126.png)


On the explorer even a STX transfer looks a bit strange when it is split between "transfer call" and the "amount being transferred", this looks like the upper part is anchored (no icon), and the lower part is confirmed in a lightning block (lightning icon):
![image](https://user-images.githubusercontent.com/33360391/212551527-33e787a0-9877-46d1-a475-73bc887883d9.png)

I would still like the nested approach [#1918](https://github.com/hirosystems/stacks-wallet-web/issues/1918) to make it more clear what transfers belong to which contract call. 

For example this is a single transaction (routed swap STX --> ALEX, ALEX --> SLM):
![image](https://user-images.githubusercontent.com/33360391/212551807-54c1f954-b302-4962-97af-1b110178be1e.png)

Preferred view (on the explorer and in the activities tab of the wallet):
![image](https://user-images.githubusercontent.com/33360391/212553529-8e370965-baf1-441d-812f-e119887d73b2.png)

- Then would you add a lightning icon (if any) on the top one only or on all five parts? just on the STX transfer part, doesn't make sense to me. 
- And would you color code the mini-icons to indicate where the funds are moving? as suggested in #2880

**Comment by 314159265359879** [comment]
Some more community feedback, adding it here for visibility:
![image](https://user-images.githubusercontent.com/33360391/213803710-6adc0de6-78a8-4f0b-a0ea-fdb754d49a33.png)

Looks like 1 is in favor showing something more limited with microblocks, for example:
![image](https://user-images.githubusercontent.com/33360391/216010955-3e22c0f8-5a28-4f8e-8f1d-241a23927725.png)

And 2, yes to keep the activities tab more clean, lets show a single transaction (top level in the above case "swap-helper" and have an option to collapse to show the parts of the transaction (STX transfer, SLM transfer, alex transfer etc in the example above).

**Comment by 314159265359879** [comment]
Lets fix displaying transactions as confirmed in a microblock. Could we add the "in microblock" text as a simple fix for now? I believe it will be clearer, and perhaps easier to do, than a lightning icon. 
I don't think we have to show all the parts of the microblock confirmed transaction, but I understand we may feel different about that with the upcoming changes. For now it could be displayed more as a pending transaction as the image above shows. 


For the discussion and resolution about nested view of activity see: https://github.com/hirosystems/stacks-wallet-web/issues/1918

**Comment by markmhendrickson** [comment]
Yep agreed we could include "In microblock" as part of the fix for clarification.
