### ISSUE TITLE
Users are getting logged out from the wallet after a recent update

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2953]
I have seen three reports since update 3.28.0 of users reporting that they have gotten logged out from the wallet after an update. 

The expected behavior of the wallet is that the user gets their wallet locked after an update. 

Has any change been made that could have resulted in this? 
Can this be rolled back? Users do not appreciate it.

When testing this myself I find the wallet only ever locks me out. I have not been able to test more then a single update forward. from 3.27.0 -> 3.28.0 and from 3.28.0 -> 3.29.0
Perhaps the issue occurs when the upgrade is done from a much older wallet to todays version.

**Comment by 314159265359879** [comment]
I have confirmation that one user was on Chrome and another one was on Firefox. Third user unknown.

**Comment by kyranjamie** [comment]
Hmm, not sure how to debug this one. There is only one place in the code where we clear `chrome.storage`, when the user signs out

https://github.com/hirosystems/stacks-wallet-web/blob/6a9298d7e62b233b3dd2adb561cebd12149c9e8d/src/app/common/hooks/use-key-actions.ts#L48-L54

Perhaps we can simulate an upgrade through multiple versions to test this

**Comment by 314159265359879** [comment]
I will check with users if I can get more details.

**Comment by southguy** [comment]
> I will check with users if I can get more details.

let me know sir , how can i help !

**Comment by 314159265359879** [comment]
> > I will check with users if I can get more details.
> 
> let me know sir , how can i help !

When you found out the wallets were logged out. 
(if you recall) When did you use the wallet last before that update/logout, when was it still okay?

**Comment by 314159265359879** [comment]
**(chrome) User 1**

Timeline:
**dec. 5th build 3.27.0 ready according to github** 

Chrome user 1 reported using the wallet up to the time of the issue, I am assuming it was already on 3.27.0 (or the automatic update would have failed for the previous 5-6 days). Not sure if it is relevant but the user was using multiple chrome profiles with different wallet accounts, all logged out at this point. 
**dec. 11 4PM GMT, automatic logout issue**

**dec. 13th build 3.28.0 ready according to github** 

So now I am not so sure it is actually caused by a wallet update. There was no wallet update on dec. 11th.

**Comment by 314159265359879** [comment]
> Hmm, not sure how to debug this one. There is only one place in the code where we clear `chrome.storage`, when the user signs out
> 
> https://github.com/hirosystems/stacks-wallet-web/blob/6a9298d7e62b233b3dd2adb561cebd12149c9e8d/src/app/common/hooks/use-key-actions.ts#L48-L54
> 
> Perhaps we can simulate an upgrade through multiple versions to test this

I am not sure if 'chrome.storage' is being cleared with this bug. I haven't been able to verify because the users likely already altered chrome.storage by re-enter the seed (or another seed) after the logout and before contacting us. 

3.27.0 has this fix
close other frames when wallet locks ([8788e01](https://github.com/hirosystems/stacks-wallet-web/commit/8788e010b9504f1cfa5c8f2c619af19da240dbc8))

Any chance that introduced a bug that could cause this?

**Comment by kyranjamie** [comment]
> Any chance that introduced a bug that could cause this? 

I wouldn't have thought so, as it only closes the window. I wonder if it's a routing issue, and somehow they're just viewing the welcome screen (appearing as though it's signed out), but it isn't really 🤔

**Comment by markmhendrickson** [comment]
@314159265359879 is your impression that we've resolved this by now?

**Comment by 314159265359879** [comment]
user 1, couldn't have been the update, maybe something with the use of multiple profiles (on Chrome) but I have not been able to reproduce this as of yet. 
user 2, turned out to have unknowingly/mistakenly click _log out_ instead of _lock_. 
user 3, unknown
user 4, similar to user 2

So perhaps user 2 and user 4 form a pattern. I have this issue https://github.com/hirosystems/stacks-wallet-web/issues/3037 for a small addition to the log out warning.

**Comment by southguy** [comment]
Thanks for the update anyhave .

Am already left stacks , almost months.

Don't care much.
