### ISSUE TITLE
Firefox extension popup window is displayed with full screen layout

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2960]
A user, suspecting a Firefox browser configuration error, has the visual of the wallet looking like this:
![image](https://user-images.githubusercontent.com/33360391/209451540-db4f77b3-b83d-41d7-b95c-5496709ff1de.png)

Left normal, right "full screen" centered layout you would expect when opening the wallet on a new tab:
![image](https://user-images.githubusercontent.com/33360391/209451534-ed8e01c4-f523-4abf-8cf9-15e8dc3fff04.png)

I would expect the centered image, large title and small explainer "enter the password you set..." on the full screen tab:
![image](https://user-images.githubusercontent.com/33360391/209451553-0989101d-d31b-41fe-8992-953e4fca618d.png)

Is there anything we can do to prevent this from happening?

**Comment by markmhendrickson** [comment]
I suspect this is a question of just which viewport width cut-off we have for the two formatting types, and we might want to make it wider for the narrower formatting.

However, when testing in Firefox, the narrower formatting does appear for me: 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/28991/210352181-953fba3f-ec87-4775-a561-ddafa0415b4b.png">

So this user's popup seems to be wider than normal for some reason?

**Comment by 314159265359879** [comment]
> I suspect this is a question of just which viewport width cut-off we have for the two formatting types, and we might want to make it wider for the narrower formatting.
> 
> However, when testing in Firefox, the narrower formatting does appear for me:
> 
> <img alt="image" width="432" src="https://user-images.githubusercontent.com/28991/210352181-953fba3f-ec87-4775-a561-ddafa0415b4b.png">
Yes this is also what I see when using Firefox. A normal width popup. Actually it doesn't matter how small or big I make the Firefox window the popup always appears to have a fixed width. 

> 
> So this user's popup seems to be wider than normal for some reason?

I checked the full screenshot again and the width of the popup for this user does look different. On the 1920x1080 screenshot he send me the wallet is approximately 760 pixels wide. When I resize the browser to HD resolution the wallet is always about a little less then 500 pixels wide on my computer. 

The user was experiencing scaling issues (Windows or Firefox related, they weren't sure) so that may have caused such a difference?

If the wallet dictates the width of the popup normally (I assume that because it is always the same for me) why doesn't the wallet do that in this case? should it?

If we can fix this by changing the viewport width cut-off that sounds good to me.

**Comment by pete-watters** [comment]
Closing this off as it's outdated and we aren't supporting Firefox now anyway. 

When I tested it is also working correctly with the latest design anyway: 

![Screenshot 2024-06-28 at 11 14 57](https://github.com/leather-io/extension/assets/2938440/6a7b4325-dd76-41dc-a38e-0e6882e3f0e2)
