### ISSUE TITLE
Long BNS names: show shortened BNS-name instead

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2961]
![image](https://user-images.githubusercontent.com/33360391/209713343-9c7499fc-23b6-43bb-8c27-350b80b56916.png)

g9.btc reported that 48 digit long BNS names are displayed strangly. Scroll bars all over. 

Is this working as intended or do we want to handle this case differently?

-scaling the font size for example?

**Comment by DevRishiJain** [comment]
Can this be assigned to me?

**Comment by 314159265359879** [comment]
Users no longer see scroll bars, but it looks a little odd anyway:

![image](https://github.com/leather-wallet/extension/assets/33360391/0f604f39-cdaa-4c04-967e-83bb00acb23e)

![image](https://github.com/leather-wallet/extension/assets/33360391/714d3783-a0e4-4952-8d73-de6e537b1806)


Some possible solutions
A. cut off and make it appear to go under
![image](https://github.com/leather-wallet/extension/assets/33360391/b64a8c3a-785a-4902-82ed-5de1430fdb69)

B. show beginning and end and use ... as in short addresses
![image](https://github.com/leather-wallet/extension/assets/33360391/db0a4368-caf3-4043-a40e-1d2afce24074)

C. or resize text
![image](https://github.com/leather-wallet/extension/assets/33360391/4fa3f28a-45be-4194-9700-eab82d22c859)


Among these options, I would recommend B. This solution retains a view on the namespace (.stx) unlike A, and it remains readable unlike C. Additionally, it is the least invasive option to resolve this (rare) issue.

**Comment by Aman-zishan** [comment]
@314159265359879 can this be assigned to me?

**Comment by Aman-zishan** [comment]
PR fix for this issue -> #5483

**Comment by pete-watters** [comment]
Closing this off as the PR was merged
