### ISSUE TITLE
Devtools warnings: "failed to load source map", "ERR_BLOCKED_BY_CLIENT"

### ISSUE THREAD

**Issue by getify** [blockstack/blockstack-app#2964]
With the chrome extension installed (Chrome 108 on Windows 10), on any page load of any site, I see these warnings from the extension in the devtools console:

<img width="938" alt="wallet-errors" src="https://user-images.githubusercontent.com/150330/209839248-aea3f9ee-ddbb-41ff-9999-3aced47f727d.png">

Typically, the "ERR_BLOCKED_BY_CLIENT" error comes from like an ad-blocker or something like that. But these errors happen on pages even when I have my ad-blocker (Privacy Badger) disabled, so I'm pretty sure it's not the cause.

I think something is happening from the wallet extension itself... either not having correct permissions to load the .map files, or them being missing, or something like that.

**Comment by getify** [comment]
Any update on this?

**Comment by markmhendrickson** [comment]
@kyranjamie any idea what might be generating these?
