### ISSUE TITLE
Fix extension tooltip name in browser chrome

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2967]
For some reason it comes up as "Stacks" instead of "Hiro Wallet" across both Chrome and Firefox:

<img width="168" alt="image" src="https://user-images.githubusercontent.com/28991/210355345-894709d5-35c3-4b65-b75a-3eaee379066a.png">

<img width="104" alt="Screen Shot 2023-01-03 at 12 51 01" src="https://user-images.githubusercontent.com/28991/210355364-9560771c-40b9-494d-a74f-3c4c7cc48a61.png">

**Comment by Pavan-Nambi** [comment]
hey , not sure why i am getting this error can anyone help me with this?
![image](https://user-images.githubusercontent.com/92514129/210371674-29b09bda-41f2-493e-af8c-bcf47d025480.png)

**Comment by adwitiyaM1** [comment]
Hey, I would like to work on this issue, is it available?

**Comment by markmhendrickson** [comment]
Yep it is if you want to submit a PR!

**Comment by adwitiyaM1** [comment]
I am new to this field, can you please guide me on this?
