### ISSUE TITLE
When downloading a wallet via hiro.so info/data to verify the download is excluded

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2973]
A users asked
_Why there isn't a hash or code crc256 to check if application is genuine to thwart supply chain attacks?_

We do have signed releases on github. Is there something else we should do here. Or are we assuming that a user who wants to run such a check to be able to find our github repository?
I do _not_ think adding the data to the download (a seperate file with the hashes?) would solve the issue because if hiro.so got compromised both could be replaced by the hacker providing false security. 

Should we perhaps provide the **option** to (a) direct to Github for a user to pick the appropriate version for themselves and/or (b) provide the option to verify authenticity?

**Comment by kyranjamie** [comment]
You can't download the web wallet from hiro.so. Are they referring to the desktop wallet?

**Comment by 314159265359879** [comment]
Sorry I will close this here and open it on the desktop repo.

**Comment by 314159265359879** [comment]
see here https://github.com/hirosystems/stacks-wallet/issues/1146
