### ISSUE TITLE
Transactions in same block not ordered correctly

### ISSUE THREAD

**Issue by badonyx** [blockstack/blockstack-app#2990]
Same issue in the Hiro web wallet as described here. 

https://github.com/hirosystems/explorer/issues/953

**Comment by 314159265359879** [comment]
Hi @0xbabo, thanks for reporting. 

@markmhx if "Transactions should be ordered by: `block_height` then `microblock_sequence` then `tx_index`." does that require changes to the API service we use or can we implement such a change with the current API's?

**Comment by markmhendrickson** [comment]
Hm good question, probably best for @fbwoolf or @kyranjamie to answer though

**Comment by kyranjamie** [comment]
Currently we list them in the order the API gives them to us

**Comment by badonyx** [comment]
> Currently we list them in the order the API gives them to us

Have just checked the `/extended/v1/address/{principal}/transactions` endpoint and it is ordered correctly there.

**Comment by badonyx** [comment]
This might only apply to transactions in microblocks but not yet anchored, please see https://github.com/hirosystems/explorer/issues/953#issuecomment-1452859231.

**Comment by markmhendrickson** [comment]
@alter-eggo might your work on https://github.com/hirosystems/stacks-wallet-web/pull/3340 also resolve this issue?

**Comment by alter-eggo** [comment]
@markmhx not sure that pr will help, there txs are sorted by tx time

**Comment by markmhendrickson** [comment]
@alter-eggo Makes sense. Would it be easy enough to extend that PR so they're ordered by time then block_height then microblock_sequence then tx_index?

Or best to tackle in a separate PR?

**Comment by alter-eggo** [comment]
@markmhx I'd like to do it in separate pr

**Comment by badonyx** [comment]
@alter-eggo I'm not seeing a code change that would fix this? Txs in the same block have the same block time.

**Comment by alter-eggo** [comment]
@0xbabo ah, sorry. issue was closed automatically as it was linked to that pr. I will fix this in separate pr

**Comment by alter-eggo** [comment]
@0xbabo could you please check if this works as expected
