### ISSUE TITLE
Prevent access to `/get-started` route when an account exists

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2997]
Reported on H1 is a scenario where, when navigating directly to `/get-started` from the lock screen, you're able to generate a new account. Viewing secret key, then displays the phrase of the previous account. Accessing this page, and generating a new account should not be possible.

**Comment by markmhendrickson** [comment]
Also reported with https://github.com/hirosystems/stacks-wallet-web/issues/2278
