### ISSUE TITLE
Wallet hangs on signing login message on sigle.io (MACos/Chrome)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2999]
On Mac, Chrome, and (software) wallet, signing in on sigle.io fails it hangs here:

![image](https://user-images.githubusercontent.com/33360391/212436508-3f5f7aba-f579-4635-bfb9-d7fe352b0ff7.png)

Trying to reproduce this myself on Windows and Chrome, but I have no issue. I am going through some steps with the user to exclude caching issues. And I am trying to get the wallet diagnostics. 

The user has already tried logging out on the wallet and re-entering the pass phrase. That didn't fix the problem.

**Comment by 314159265359879** [comment]
A copy of the users diagnostics:

[
  [
    "2023-01-14T00:13:41.060Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-13T18:39:02.092Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-13T18:38:11.255Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-13T18:35:31.462Z",
    "info",
    "Analytics event: request_signature_cannot_sign_message_no_account",
    null
  ],
  [
    "2023-01-13T18:35:31.460Z",
    "error",
    "Cannot sign message, no account in state"
  ],
  [
    "2023-01-13T18:35:31.458Z",
    "info",
    "Analytics event: request_signature_sign",
    {
      "type": "software"
    }
  ],
  [
    "2023-01-13T18:35:29.865Z",
    "info",
    "Analytics page view: /signature",
    null
  ],
  [
    "2023-01-13T18:35:18.985Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-13T18:35:11.927Z",
    "info",
    "Analytics page view: /fund",
    null
  ],
  [
    "2023-01-13T18:35:11.908Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-13T18:35:11.901Z",
    "info",
    "Analytics page view: /set-password",
    null
  ],
  [
    "2023-01-13T18:35:05.356Z",
    "info",
    "Analytics event: submit_valid_password",
    null
  ],
  [
    "2023-01-13T18:34:56.056Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:55.017Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:54.543Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:53.954Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:51.157Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:49.920Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:49.464Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:48.521Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:47.195Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:45.944Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:34:45.718Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-13T18:33:57.978Z",
    "info",
    "Analytics page view: /set-password",
    null
  ],
  [
    "2023-01-13T18:33:57.953Z",
    "info",
    "Analytics page view: /set-password",
    null
  ],
  [
    "2023-01-13T18:33:57.942Z",
    "info",
    "Analytics event: submit_valid_secret_key",
    null
  ],
  [
    "2023-01-13T18:32:14.862Z",
    "info",
    "Analytics page view: /sign-in",
    null
  ],
  [
    "2023-01-13T18:32:09.432Z",
    "info",
    "Analytics page view: /get-started",
    null
  ],
  [
    "2023-01-13T18:32:09.412Z",
    "info",
    "Analytics event: respond_diagnostics_consent",
    {
      "areDiagnosticsAllowed": true
    }
  ],
  [
    "2023-01-13T18:32:07.009Z",
    "info",
    "Analytics event: sign_out",
    null
  ],
  [
    "2023-01-13T18:32:06.962Z",
    "info",
    "Analytics page view: /request-diagnostics",
    null
  ],
  [
    "2023-01-13T18:32:06.946Z",
    "info",
    "Analytics page view: /get-started",
    null
  ],
  [
    "2023-01-13T18:31:56.166Z",
    "info",
    "Analytics page view: /sign-out",
    null
  ],
  [
    "2023-01-13T18:31:45.601Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-13T18:31:35.684Z",
    "info",
    "Analytics event: request_signature_cancel",
    null
  ],
  [
    "2023-01-13T18:30:22.022Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-12T23:22:35.133Z",
    "info",
    "Analytics event: request_signature_cannot_sign_message_no_account",
    null
  ],
  [
    "2023-01-12T23:22:35.130Z",
    "error",
    "Cannot sign message, no account in state"
  ],
  [
    "2023-01-12T23:22:35.128Z",
    "info",
    "Analytics event: request_signature_sign",
    {
      "type": "software"
    }
  ],
  [
    "2023-01-12T23:22:31.296Z",
    "info",
    "Analytics page view: /signature",
    null
  ],
  [
    "2023-01-12T23:22:31.247Z",
    "info",
    "Analytics event: complete_unlock",
    {
      "durationMs": 4972
    }
  ],
  [
    "2023-01-12T23:22:26.276Z",
    "info",
    "Analytics event: start_unlock",
    null
  ],
  [
    "2023-01-12T23:21:23.985Z",
    "info",
    "Analytics page view: /unlock",
    null
  ],
  [
    "2023-01-12T23:21:23.815Z",
    "info",
    "Analytics page view: /signature",
    null
  ],
  [
    "2023-01-10T22:15:53.459Z",
    "info",
    "Analytics event: request_signature_cancel",
    null
  ],
  [
    "2023-01-10T22:15:22.996Z",
    "info",
    "Analytics event: request_signature_cannot_sign_message_no_account",
    null
  ],
  [
    "2023-01-10T22:15:22.988Z",
    "error",
    "Cannot sign message, no account in state"
  ],
  [
    "2023-01-10T22:15:22.985Z",
    "info",
    "Analytics event: request_signature_sign",
    {
      "type": "software"
    }
  ],
  [
    "2023-01-10T22:15:15.878Z",
    "info",
    "Analytics page view: /signature",
    null
  ],
  [
    "2023-01-10T22:15:07.542Z",
    "info",
    "Analytics event: request_signature_cancel",
    null
  ],
  [
    "2023-01-09T23:22:23.967Z",
    "info",
    "Analytics event: request_signature_cannot_sign_message_no_account",
    null
  ],
  [
    "2023-01-09T23:22:23.959Z",
    "error",
    "Cannot sign message, no account in state"
  ],
  [
    "2023-01-09T23:22:23.956Z",
    "info",
    "Analytics event: request_signature_sign",
    {
      "type": "software"
    }
  ],
  [
    "2023-01-09T23:22:20.762Z",
    "info",
    "Analytics page view: /signature",
    null
  ],
  [
    "2023-01-09T23:22:02.620Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-09T23:21:11.720Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-09T23:21:06.952Z",
    "info",
    "Analytics page view: /sign-out",
    null
  ],
  [
    "2023-01-08T22:57:28.048Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-08T22:57:27.907Z",
    "info",
    "Analytics page view: /get-started",
    null
  ],
  [
    "2023-01-08T22:57:27.887Z",
    "info",
    "Analytics page view: /choose-network/change-theme",
    null
  ],
  [
    "2023-01-08T22:57:27.841Z",
    "info",
    "Analytics event: change_theme_menu_item",
    null
  ],
  [
    "2023-01-08T22:57:22.788Z",
    "info",
    "Analytics page view: /choose-network",
    null
  ],
  [
    "2023-01-08T22:57:22.746Z",
    "info",
    "Analytics event: choose_to_change_network",
    null
  ],
  [
    "2023-01-08T22:57:14.518Z",
    "info",
    "Analytics event: click_get_support_menu_item",
    null
  ],
  [
    "2023-01-08T22:57:10.367Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-08T22:45:39.210Z",
    "info",
    "Analytics page view: /sign-out",
    null
  ],
  [
    "2023-01-08T22:43:47.759Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-08T22:43:29.248Z",
    "info",
    "Analytics page view: /fund",
    null
  ],
  [
    "2023-01-08T22:43:29.236Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2023-01-08T22:43:29.226Z",
    "info",
    "Analytics page view: /set-password",
    null
  ],
  [
    "2023-01-08T22:43:23.043Z",
    "info",
    "Analytics event: submit_valid_password",
    null
  ],
  [
    "2023-01-08T22:43:13.439Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:43:13.030Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:43:11.267Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:43:10.621Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:43:09.374Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:43:07.631Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:43:06.848Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:43:05.525Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:43:03.452Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:42:59.904Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:42:57.880Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:42:57.578Z",
    "info",
    "Analytics event: submit_invalid_password",
    null
  ],
  [
    "2023-01-08T22:42:26.603Z",
    "info",
    "Analytics page view: /set-password",
    null
  ],
  [
    "2023-01-08T22:42:26.600Z",
    "info",
    "Analytics page view: /set-password",
    null
  ],
  [
    "2023-01-08T22:39:31.962Z",
    "info",
    "Analytics page view: /back-up-secret-key",
    null
  ],
  [
    "2023-01-08T22:39:31.919Z",
    "info",
    "Analytics event: generate_new_secret_key",
    null
  ],
  [
    "2023-01-08T22:39:28.034Z",
    "info",
    "Analytics page view: /get-started",
    null
  ],
  [
    "2023-01-08T22:39:27.820Z",
    "info",
    "Analytics page view: /signature",
    null
  ],
  [
    "2022-11-30T19:56:28.095Z",
    "info",
    "Analytics page view: /back-up-secret-key",
    null
  ],
  [
    "2022-11-30T19:56:28.064Z",
    "info",
    "Analytics event: generate_new_secret_key",
    null
  ],
  [
    "2022-11-30T19:56:26.479Z",
    "info",
    "Analytics page view: /get-started",
    null
  ],
  [
    "2022-11-30T19:56:26.430Z",
    "info",
    "Analytics event: respond_diagnostics_consent",
    {
      "areDiagnosticsAllowed": true
    }
  ],
  [
    "2022-11-30T19:56:21.924Z",
    "info",
    "Analytics event: sign_out",
    null
  ],
  [
    "2022-11-30T19:56:21.741Z",
    "info",
    "Analytics page view: /request-diagnostics",
    null
  ],
  [
    "2022-11-30T19:56:21.688Z",
    "info",
    "Analytics page view: /get-started",
    null
  ],
  [
    "2022-11-30T19:56:11.514Z",
    "info",
    "Analytics page view: /unlock/sign-out",
    null
  ],
  [
    "2022-11-30T19:54:56.462Z",
    "info",
    "Analytics event: complete_unlock",
    {
      "durationMs": 5029.900000095367
    }
  ],
  [
    "2022-11-30T19:54:51.433Z",
    "info",
    "Analytics event: start_unlock",
    null
  ],
  [
    "2022-11-30T19:53:55.188Z",
    "info",
    "Analytics page view: /unlock",
    null
  ],
  [
    "2022-11-30T19:53:54.928Z",
    "info",
    "Analytics page view: /signature",
    null
  ],
  [
    "2022-11-24T20:09:59.248Z",
    "info",
    "Analytics event: complete_unlock",
    {
      "durationMs": 4970.899999976158
    }
  ],
  [
    "2022-11-24T20:09:54.277Z",
    "info",
    "Analytics event: start_unlock",
    null
  ],
  [
    "2022-11-24T20:09:27.360Z",
    "info",
    "Analytics page view: /unlock",
    null
  ],
  [
    "2022-11-24T20:07:15.222Z",
    "info",
    "Analytics page view: /unlock/sign-out",
    null
  ],
  [
    "2022-11-24T20:05:27.304Z",
    "info",
    "Analytics event: complete_unlock",
    {
      "durationMs": 4943.899999976158
    }
  ],
  [
    "2022-11-24T20:05:22.361Z",
    "info",
    "Analytics event: start_unlock",
    null
  ],
  [
    "2022-11-24T20:04:51.127Z",
    "info",
    "Analytics event: complete_unlock",
    {
      "durationMs": 4966
    }
  ],
  [
    "2022-11-24T20:04:46.162Z",
    "info",
    "Analytics event: start_unlock",
    null
  ],
  [
    "2022-11-24T20:03:55.509Z",
    "info",
    "Analytics event: complete_unlock",
    {
      "durationMs": 4973.200000047684
    }
  ],
  [
    "2022-11-24T20:03:50.536Z",
    "info",
    "Analytics event: start_unlock",
    null
  ],
  [
    "2022-11-24T20:02:30.897Z",
    "info",
    "Analytics page view: /unlock",
    null
  ],
  [
    "2022-11-24T20:02:30.743Z",
    "info",
    "Analytics page view: /signature",
    null
  ],
  [
    "2022-11-22T14:36:31.745Z",
    "info",
    "Analytics event: request_signature_cannot_sign_message_no_account",
    null
  ],
  [
    "2022-11-22T14:36:31.741Z",
    "error",
    "Cannot sign message, no account in state"
  ],
  [
    "2022-11-22T14:36:31.738Z",
    "info",
    "Analytics event: request_signature_sign",
    null
  ],
  [
    "2022-11-22T14:36:26.383Z",
    "info",
    "Analytics page view: /signature",
    null
  ],
  [
    "2022-11-22T14:36:08.942Z",
    "info",
    "Analytics event: dismiss_suggested_first_steps",
    null
  ],
  [
    "2022-11-22T14:12:17.358Z",
    "info",
    "Analytics page view: /",
    null
  ],
  [
    "2022-11-22T14:12:17.348Z",
    "info",
    "Analytics page view: /back-up-secret-key",
    null
  ],
  [
    "2022-11-22T14:12:17.335Z",
    "info",
    "Analytics event: generate_new_secret_key",
    null
  ],
  [
    "2022-11-22T14:12:03.168Z",
    "info",
    "Analytics page view: /get-started",
    null
  ],
  [
    "2022-11-22T14:12:03.131Z",
    "info",
    "Analytics event: respond_diagnostics_consent",
    {
      "areDiagnosticsAllowed": true
    }
  ],
  [
    "2022-11-22T14:12:00.871Z",
    "info",
    "Analytics page view: /request-diagnostics",
    null
  ]
]

**Comment by 314159265359879** [comment]
It looks to me like the dapp isn't actually connected to the account properly:

`**"Analytics event: request_signature_cannot_sign_message_no_account",
null
],
[
"2022-11-22T14:36:31.741Z",
"error",
"Cannot sign message, no account in state"**`

**Comment by markmhendrickson** [comment]
Has the user tried to log out of Sigle and back into it to ensure that they're authenticated (via selecting their account anew)?

**Comment by alter-eggo** [comment]
@314159265359879 @markmhx tested on mac/chrome, and it worked ok for me, is this actual?

**Comment by markmhendrickson** [comment]
Given that it was just one report from over a month ago, let's close and see if anyone else reports it before reopening. 🙏
