### ISSUE TITLE
Loading accounts 2 and up on a private key not working (after update 3.31.0 and/or restart)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3020]
I noticed this in Opera after restart/upgrade to 3.31.0

Only showing a single account where there should be several more:
![image](https://user-images.githubusercontent.com/33360391/214523535-141504df-376e-419c-90fb-8f47a8324ae2.png)

And when opening the wallet via the icon or in a tab it doesn't load:
![image](https://user-images.githubusercontent.com/33360391/214523506-78a42f34-cdbc-4762-a727-e0627bb10bd5.png)

Menu incomplete:
![image](https://user-images.githubusercontent.com/33360391/214525306-43b5ce14-33b9-4537-b7b3-9ca7470021d9.png)

Kyran expects this is happening because GAIA is down and the fallback is not working as expected. Investigating further.

**Comment by markmhendrickson** [comment]
@314159265359879 Was this fully resolved by https://github.com/hirosystems/stacks-wallet-web/pull/3021 ?

**Comment by 314159265359879** [comment]
> @314159265359879 Was this fully resolved by #3021 ?

Yes, in 3.31.1
I had one exception while testing but did not reproduce that again so I assume it was also fixed. Probably caused by the initial failure to connect with GAIA or the fallback solution.

**Comment by 314159265359879** [comment]
I had one user report today, similar to what I experienced once. 
If you went online with the wallet at the time GAIA was down and the fallback wasn't working. You would still only see a single account, even after a reset today with a wallet updated to 3.31.1. 

The fix was simple though, click "create an account" (in this case a couple times) which revealed the prior accounts again.
