### ISSUE TITLE
Fix redirect upon changing theme from page other than home

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3025]
For some reason, if I choose "Change theme" on a page other than home (e.g. Buy page), it simply redirects me to home rather than showing me the theme options:

https://user-images.githubusercontent.com/28991/214576834-d61aad66-b0c3-48dd-a05c-81f7982dee55.mov

**Comment by kyranjamie** [comment]
This specific case is easy to fix, we can add the settings routes as children of the fund page. Afaik there's no way to set a wild card route like `*/change-theme`.

**Comment by alter-eggo** [comment]
@markmhx seems it is fixed already
