### ISSUE TITLE
Caching issue? causes wallet to load forever on Chrome, unresponsive to clicks on top right menu.

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3032]
The loading screen and console looked like this:
![image](https://user-images.githubusercontent.com/33360391/215429600-86c36759-0e0c-4b89-8859-2977c094a5f8.png)

Clicking change theme or log out would result in an error like this, the loading screen would remain:
![image](https://user-images.githubusercontent.com/33360391/215428921-ecae415a-c7d1-4449-a3d9-4ac1731dca47.png)

Workaround: Installing the Hiro Wallet on Firefox solved this issue. Additionally uninstalling the extension and reinstalling it resolved the issue on Chrome. 

The user experiencing this today mentioned having experienced this issue for about a week before contacting support.

**Comment by markmhendrickson** [comment]
This may be hard to resolve without steps to recreate

**Comment by markmhendrickson** [comment]
@kyranjamie do we expect this is resolved by v3.32.3?

**Comment by kyranjamie** [comment]
> @kyranjamie do we expect this is resolved by v3.32.3? 

I can't say for sure. I'd hope that by removing one component (gaia) from the sign in process, there's one less thing to break and causes issues like this.

**Comment by markmhendrickson** [comment]
@314159265359879 have you seen more instances of this reported recently? I'm going to close and we can reopen if so.
