### ISSUE TITLE
Show testnet badge in app nav while signing transaction

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3034]
It doesn't appear while signing:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/28991/215495600-8b9accb0-4cf8-4843-b540-feb35df9234d.png">

Though it does while on the home screen:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/28991/215495735-e785ec9c-a54d-4716-9e02-f15ff51d91c1.png">

**Comment by pete-watters** [comment]
Closing this as it's stale and has been confirmed as working in https://github.com/leather-io/issues/issues/157
