### ISSUE TITLE
Drop support for API overrides

### ISSUE THREAD

**Issue by badonyx** [blockstack/blockstack-app#3077]
The Stacks API is now being overridden by a third-party API due to 8c573f25b6e3c657cd4a4f8f5d0a0258809f7560. 

The reference Stacks wallet, Hiro, should not override the reference Stacks API, especially not for an already fragile system like BNS. 

I have written more about this in [the stacks forum thread about BNSX](https://forum.stacks.org/t/how-to-resolve-bns-x-names/14223/13).

**Comment by markmhendrickson** [comment]
Thanks @0xbabo, I've provided some thoughts here for discussion: https://forum.stacks.org/t/how-to-resolve-bns-x-names/14223/14?u=markmhendrickson

**Comment by kyranjamie** [comment]
While we evaluate the risks of this further, and how we can mitigate any potentially dangerous situations for users, we'll remove this functionality

**Comment by fbwoolf** [comment]
Track revert PR here: https://github.com/hirosystems/stacks-wallet-web/pull/3081
