### ISSUE TITLE
Display Ordinal inscriptions alongside Stacks NFTs

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3090]
To complement the release of https://github.com/hirosystems/stacks-wallet-web/issues/1028

**Comment by markmhendrickson** [comment]
@mica000 copying your designs guidance here since this issue is Ordinals-specific: https://github.com/hirosystems/stacks-wallet-web/issues/1028#issuecomment-1433796449

**Comment by markmhendrickson** [comment]
I'm reopening because the API endpoint on which we're depending here (https://ordapi.xyz/address/${address}) seems very non-performant and I can't get my inscriptions to load. Thankfully these (or similar) in combination should work for us:

1. We query a generic blockchain API (mempool or blockstream in our case?) in a similar manner to how they're hitting up https://api.blockcypher.com/v1/btc/main/addrs/bc1ptxztnn7yuv2c2hz5p6lxwyccv8z3yzw8ntzv6afpjqqn5qp920ms5vscmv?unspentOnly=true&limit=50 to get unspent transactions for the address and cherrypick the first to appear
2. Then we pass that tx_hash to https://ordapi.xyz/output/ca84578e541353673a66608d7d95608e48a7cdce7830f638efd0214f538e6842:0 to get the inscription ID
3. Then we use the inscription ID to query https://ordapi.xyz/inscription/9f165f481c23ba6eab848618bfebed149a43950d96ca053ae53ae7a54d3d3b70i0 for the inscription metadata and https://ordinals.com/content/9f165f481c23ba6eab848618bfebed149a43950d96ca053ae53ae7a54d3d3b70i0 for its content

**Comment by diwakergupta** [comment]
FYI @rafaelcr
