### ISSUE TITLE
Display fresh taproot address for depositing inscriptions with proper guidance

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3091]
For inscribing or depositing Ordinals. E.g. under "Collectibles" as an "Add inscription" option with the following type of content displayed upon selection:

![Screenshot 2023-02-17 at 02 38 40](https://user-images.githubusercontent.com/28991/219621530-e7a51d31-9d79-471a-897c-1c60a05a414f.png)

[See related Figma](https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1182%3A63497&t=Shl5eSB4xRFAbQkH-4)

**Comment by kyranjamie** [comment]
Why not only expose TR addresses via apps that request them? 

If we add this, users will send funds there, and we have no plans yet to provide them a way to spend them.

**Comment by mica000** [comment]
@markmhx @kyranjamie Is this step still relevant given that the new user flow starts from the collections section?

**Comment by mica000** [comment]
https://user-images.githubusercontent.com/119523541/219715387-35d7a38e-07ad-49d7-a5c6-f03c0805aa4b.mov

<img width="621" alt="Screenshot 2023-02-17 at 15 17 29" src="https://user-images.githubusercontent.com/119523541/219682147-331986fe-df9d-4208-b40f-aea920825b63.png">


[Component](https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1203%3A63087&t=0OeOFKmcaHOATyvZ-4)

[Prototype 
](https://www.figma.com/proto/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?page-id=1065%3A45572&node-id=1182%3A64633&viewport=1565%2C1441%2C0.17&scaling=min-zoom&starting-point-node-id=1182%3A64633&show-proto-sidebar=1)

**Comment by markmhendrickson** [comment]
The plus icon in the current integration (per https://github.com/hirosystems/stacks-wallet-web/pull/3164) seems a bit smaller than the designs. Should we boost it up even more in the designs and integrated that larger size, so the user sees the icon prominently?

The width of the image itself is variable given viewport width, so perhaps this icon should be proportional to the width.

## Design



![Image](https://user-images.githubusercontent.com/28991/219873111-988fbe2c-15fa-43eb-a5c9-e249f5ac159a.png)



## Integration



![Image](https://user-images.githubusercontent.com/28991/219873087-354c63dd-435f-44cf-871f-835f4fcf6bf8.png)

**Comment by mica000** [comment]
@markmhx maybe better if the fix on the ghost button happens on this ticket https://github.com/hirosystems/stacks-wallet-web/pull/3164#event-8551130232?

**Comment by markmhendrickson** [comment]
Hm yea unsure since that PR is merged / closed now, so we'll need another one.

**Comment by fbwoolf** [comment]
I can change here if you tell me how big? https://github.com/hirosystems/stacks-wallet-web/pull/3190

It is currently `14px`

**Comment by markmhendrickson** [comment]
Assigning @edu-stx to wire up the actual taproot address.
