### ISSUE TITLE
Return Bitcoin address to app during auth

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3092]
This requires opening a SIP and issue in Connect for standardization

**Comment by planbetterHQ** [comment]
This is highly interesting for our pool to adopt the new Native Segwit addresses.

**Comment by aulneau** [comment]
for something quick and dirty between now and a SIP, you can always append data to the addresses key:

https://github.com/fungible-systems/micro-stacks/blob/main/packages/core/src/connect/auth/types.ts#L69

```ts
  addresses: {
    testnet: string;
    mainnet: string;
    bitcoin: ... // maybe by mainnet/taproot, etc etc
  ```
