### ISSUE TITLE
Update manifest description

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3093]
From:

> Hiro Wallet is a safe way to manage your STX, sign into apps, and protect your funds while interacting with Clarity smart contracts.

To:

> Hiro Wallet is the #1 wallet for Web3 on Bitcoin. Connect to apps and manage your assets secured by Bitcoin with the most popular wallet for the Stacks blockchain

**Comment by kyranjamie** [comment]
> A plain text string (no HTML or other formatting; no more than 132 characters) that describes the extension. The description should be suitable for both the browser's extension management UI and the [Chrome Web Store](https://chrome.google.com/webstore). You can specify locale-specific strings for this field; see [Internationalization](https://developer.chrome.com/docs/extensions/i18n/) for details.

Needs shortening.

**Comment by markmhendrickson** [comment]
> The most popular and trusted wallet for apps built on Bitcoin
