### ISSUE TITLE
Create in-app Bitcoin announcement banner or similar

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3094]

**Comment by mica000** [comment]
@markmhx Trying to understand where this would take place. Should we show it to all new and existing users?

**Comment by markmhendrickson** [comment]
I'm thinking we could squeeze in banner right below the "Next steps" section (if not hidden already) and above the rest of the home screen for all users, new and existing, that says something like:

> Hiro Wallet now supports Ordinal inscriptions and Bitcoin transactions! [Create your first inscription](#) or [Learn about Bitcoin features](#)

It could have some light visual treatment that connotes both Bitcoin and Ordinals, and the link could go to a new FAQ that highlights how to use Gamma for inscribing with the wallet. cc @314159265359879

**Comment by kyranjamie** [comment]
An _Enable Bitcoin_ button with https://confettijs.org 🤔

**Comment by markmhendrickson** [comment]
https://confettijs.org/ could be nice for the moment of transaction broadcasting as well, either alongside implementation of the new "post submission" transaction screen or ahead of it as well as we take the user to the activity area so they have a sense that it was accomplished

**Comment by mica000** [comment]
Component
<img width="1790" alt="Screenshot 2023-02-20 at 12 38 54" src="https://user-images.githubusercontent.com/119523541/220096114-74fac357-b624-4847-9b0a-43437080cf3b.png">

File
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1266%3A66268&t=EXKw9FjLtTgJvDeF-4


SVG
![#BTC launch banner icon - 118x46](https://user-images.githubusercontent.com/119523541/220095942-0fea3cad-f38b-49ff-aa00-17217a17d2cc.svg)

--------------------------

We have 4 users cases to keep in mind so some logic is needed
<img width="881" alt="Screenshot 2023-02-19 at 15 35 44" src="https://user-images.githubusercontent.com/119523541/219954920-af2f3820-1822-4438-95bb-fcb95e46e607.png">
