### ISSUE TITLE
Support app request for taproot address(es)

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3095]
So apps that need to inscribe Ordinals can retrieve the address for delivery

**Comment by aulneau** [comment]
@kyranjamie @markmhx lmk what you're thinking for request format so I can update micro-stacks :)

**Comment by markmhendrickson** [comment]
Wanted by Gamma and Ordswap

**Comment by markmhendrickson** [comment]
@alter-eggo I'd recommend syncing with @kyranjamie about how to go about this one. 

The wallet essentially needs to support a way for an app to request an array of the first 10 taproot addresses for the currently authenticated account.

**Comment by markmhendrickson** [comment]
Now tracking this here: https://github.com/hirosystems/wallet/issues/3372
