### ISSUE TITLE
[Bitcoin] Warning when fees exceed certain dollar amount

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3099]
Add a warning to the UI when fees exceed a certain value

**Comment by fbwoolf** [comment]
What is the max value we want to set here?

**Comment by fbwoolf** [comment]
@markmhx our current high fee warning for STX has a url link to https://hiro.so/questions/fee-estimates ...what do we want for btc?

**Comment by fbwoolf** [comment]
https://bitcoinfees.earn.com/

???

**Comment by markmhendrickson** [comment]
Hmm maybe we should link to the same FAQ for both BTC and STX but rework the content so its appropriate for both? cc @314159265359879
