### ISSUE TITLE
[Bitcoin] Select asset view too narrow

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3105]
At at certain widths, the view is narrower than it should be. 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/1618764/218527503-bacbcf73-6b9f-483e-9a1b-5ba82edffda6.png">

**Comment by fbwoolf** [comment]
Going to close this bc and make a new issue to refactor the send form into a modal instead.
