### ISSUE TITLE
Increasing fees doesn't check account balance/pending fees/pending STX transfers

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3109]
We are seeing an increased number of forever pending transactions such as this (screenshot):

I think a scenario such as the following plays out:
_New users sends three transactions. A pre-order for a domain. A transfer of STX and something else. After waiting two minutes, they believe it is taking to long so they increase the fee on the first transaction to something like 2 STX. Now there is not enough left to cover the fee and transfer of STX (second transaction). The users sends more transaction and they all remain pending for hours... and hours eventually they ask for help._

I am wondering if we can do more to check balance and include the current fees needed to cover pending transactions as well as STX to cover pending transfers out of the wallet so we can error "not enough STX balance to increase the fee to that value" or similar. Instead of getting wallets stuck like this. 

![image](https://user-images.githubusercontent.com/33360391/218552388-8d939937-49e6-418f-a4b3-b22dd6fec9d0.png)

I think this is a P2 because it especially happens to new users. More experienced Stackers will know transaction times on Stacks are (currently) longer than on Ethereum. Although in case of real congestion this can affect experienced users too.

**Comment by 314159265359879** [comment]
Scenario checked
![image](https://user-images.githubusercontent.com/33360391/218995057-ed0aa2eb-c1f0-4f35-852c-6ea9022daa6e.png)
I have transaction in microblocks that reduce the wallet balance to less then 1.0 STX. 
I was still able to send a new transaction with a fee of 1 STX. I believe this should also fail. 

The max button doesn't take into account pending transfers, I believe it should at least take into account pending transfers out (reduced actually available balance) as well as fees pending:
![image](https://user-images.githubusercontent.com/33360391/218995835-5114297b-efdf-417e-828c-ecb5c20b2c54.png)

**Comment by 314159265359879** [comment]
Currently there are a lot of transactions for BNS names. We may even want to consider taking into account the most common 2 STX needed for a pre-order of a BNS domain in the .btc namespace. I am not sure if it is viable to cover all namespaces or pending transactions more generally, perhaps if we go off the post-conditions of these pending transactions?
![image](https://user-images.githubusercontent.com/33360391/218998655-4577150d-544e-4edb-ae7b-772e41b46b18.png)

![image](https://user-images.githubusercontent.com/33360391/218999145-f2190dc9-37b4-409a-9690-76e90ddeddbb.png)

Or would this set us up for other issues?

**Comment by Hero-Gamer** [comment]
Still happening: https://github.com/hirosystems/wallet/issues/3338#issuecomment-1485561431
please fix this..

**Comment by harrybasra95** [comment]
Hi @314159265359879, I did some research on the issue.

We are using a hook called `useCalculateMaxBitcoinSpend` in the file [use-calculate-max-spend](https://github.com/hirosystems/wallet/blob/dev/src/app/pages/send/send-crypto-asset-form/family/bitcoin/hooks/use-calculate-max-spend.ts) to get the max spending amount and we are not subtracting the pending amount from that.

There is another hook called `useBitcoinPendingTransactionsBalance` [transactions-by-address](https://github.com/hirosystems/wallet/blob/dev/src/app/query/bitcoin/address/transactions-by-address.hooks.ts) which we can use to get the balance of the pending transactions and then subtract it.

One more thing I would like to add, we also have a list of submitted transactions, I think their balance should also be taken into account while calculating the max amount.

**Comment by markmhendrickson** [comment]
Assigning @alter-eggo to take a look since I believe he's worked on related code recently

**Comment by harrybasra95** [comment]
@harrybasra95  Sure

**Comment by alter-eggo** [comment]
@314159265359879 wonder if this is still relevant. seems like previous work on available balances fixed this

**Comment by 314159265359879** [comment]
@alter-eggo, yes #3525 (pending outgoing STX's transfers) and another fix to subtract pending fees, prevent a lot of cases already. 

There is still one issue open that should be addressed to catch all of the most common cases (subtract STX transfers due to contract calls based on exact post-conditions):
https://github.com/hirosystems/wallet/issues/3568

Lets proceed there?

**Comment by alter-eggo** [comment]
yeah, let's proceed there
