### ISSUE TITLE
Clarify microblocks state for transactions to distinguish from pending

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3110]
With the recent influx of new users I see a lot of questions like this:
![image](https://user-images.githubusercontent.com/33360391/218556049-39883ee7-a89f-47ff-9a9e-2e7d530b5d5f.png)

Users do not understand this. They think they should have STX and think they can spend it but they can't. It is not yet anchored.

1. Should the user get the answer in the wallet? add some info "confirmed in microblock, will become spendable after an anchorblock". 
2. Or if it is causing more confusion rather then helping should this be removed? That would go well with the suggestion here https://github.com/hirosystems/stacks-wallet-web/issues/2944#issuecomment-1411816492 to display microblock confirmations as an advanced stage of pending rather than confirmation.

**Comment by Hero-Gamer** [comment]
For example in metamask, balance is only reduced once tx is fully confirmed. Sometimes after 20 seconds, and during those 20 seconds, no balance is showing as "pending being taken out". 
Our tx is longer, sure if you wanna separate out, you could have like using the above case
Available balance: 0
pending spend -> 10.924

**Comment by 314159265359879** [comment]
This is closed because microblocks are no longer used in the upcoming Nakamoto release. This functionality was removed in preparation for that.
