### ISSUE TITLE
Update addresses under home account header (BTC and STX)

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3115]
Should say "Copy Stacks address" and should we add the Bitcoin address here as well (Native SegWit) alongside it to the left?

<img width="316" alt="image" src="https://user-images.githubusercontent.com/28991/218661129-44597261-b00c-41e6-b4c4-f5654ca01b87.png">

**Comment by tycho1212** [comment]
I think there are other ways to allow users to copy the BTC address too. I'm an experienced user so will recognise which address is BTC and which address is Stacks, but newer users might not
