### ISSUE TITLE
[Bitcoin] Persist send form values between route transitions

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3118]
When going from the send form confirmation, back to the send form, the user should see the values they input.

This'll be implicitly fixed if we make the preview a modal

**Comment by markmhendrickson** [comment]
Is this resolved now that we have the preview?

**Comment by kyranjamie** [comment]
Yes, though the fix has nothing to do with the preview per se. We look for route state that's defined, and use that to set form values. So, on preview screen, when navigating back, we set that state.
