### ISSUE TITLE
Restore "Choose account" for recipient field in new send form

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3123]
It appears we've lost it during the transition to the new form design, now on testnet. 

@fbwoolf I imagine you might already be tracking this. 

![Image](https://user-images.githubusercontent.com/28991/218742183-5b6444bc-a0b9-4c84-8d80-58be0a9ffd0f.png)

**Comment by kyranjamie** [comment]
I removed it purposefully as it didn't work with BTC yet

**Comment by fbwoolf** [comment]
Should I fix this today? I think it was just selecting the Stacks address in the bitcoin send form by mistake?

**Comment by markmhendrickson** [comment]
@fbwoolf please do!
