### ISSUE TITLE
Show fiat value for combined balances in account header

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3124]
We show in the accounts picker:

![Image](https://user-images.githubusercontent.com/28991/218744638-cf36110d-6df5-4dd6-aff1-cd6865a49356.png)

But not in the account header:

![Image](https://user-images.githubusercontent.com/28991/218744681-56d47d36-1ad6-4160-87d9-6aca4c596cca.png)

**Comment by mica000** [comment]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=259%3A59330&t=issirqQ7YBDFryGY-4
<img width="881" alt="Screenshot 2023-02-14 at 16 28 50" src="https://user-images.githubusercontent.com/119523541/218785284-7305649b-6695-4a20-9793-fdbde0f7fa42.png">

**Comment by markmhendrickson** [comment]
Thanks! Though I think we want to preserve the two options to copy BTC and STX addresses per https://github.com/hirosystems/stacks-wallet-web/issues/3115 ?

**Comment by mica000** [comment]
This ticket seems to be the same or conflicting [#3132](https://github.com/hirosystems/stacks-wallet-web/issues/3132#event-8537184953) (Solution on the ticket)
