### ISSUE TITLE
[Bitcoin] Add a warning/error when user tried to send too small amount

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3126]
Users shouldn't be able to send 1 satoshi. This would almost certainly be a mistake, as fees are like 15-20k sats.

![image](https://user-images.githubusercontent.com/1618764/218763400-ff4e7398-397f-44a2-9c62-9e654fb808f0.png)

**Comment by markmhendrickson** [comment]
This is resolved with https://github.com/hirosystems/stacks-wallet-web/pull/3179
