### ISSUE TITLE
[Bitcoin] Refactor full page send form design (add outline)

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#3128]
Designs: https://www.figma.com/proto/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?page-id=207%3A38522&node-id=1067%3A61964&viewport=-381%2C-701%2C0.32&scaling=min-zoom&starting-point-node-id=1067%3A61964&show-proto-sidebar=1

cc @markmhx @mica000

**Comment by kyranjamie** [comment]
We'll need conditional routing here, where we route to modal in full screen mode, but a separate page in popup mode.

**Comment by fbwoolf** [comment]
Edited the issue title and description here to be a refactor of the send form full page view. I will add the outline for now as a critical path for mainnet.
