### ISSUE TITLE
[Bitcoin] Send all toggle mode

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3136]
Currently, the _send all_ functionality works in a way where it simply sets the input amount to a given sum.

Due to complexities with fees, and calculating the transaction size, it must instead be a toggle. Send all is either on or off. Consider how Sparrow wallet does this. _Send max_ is enabled, until the user either 1) disables it, or 2) changes the set amount manually. To understand the need for this, one must first [understand the UTXO model](https://river.com/learn/bitcoins-utxo-model) bitcoin uses. 

![CleanShot 2023-02-15 at 10 35 32@2x](https://user-images.githubusercontent.com/1618764/218990183-eca5c8eb-4715-4541-bc25-c3e0c0150385.png)

## Problem

We are unable to calculate fees, or do correct coin selection, without knowing whether or not a user wishes to send their entire balance. We need to know this to determine whether to use a change address.

## Impact

- Unwanted insufficient balances validation
  - This error would only appear when sending max, if their entire balance isn't enough to cover fee
- Left over "dust" amounts of BTC in wallet
  - Current scenario: 
    - User wants to send all. They click send all. They go to fee selection page. Choose _Low_ fee. There's a remainder left over that is returned to their change address. End result: user has a little bit left over.
  - Ideal scenario: 
    - Fee selection page "knows" user wants to send all (because they've selected it). Coin selection adapts to this, and ensures all UTXOs are spent.

## Suggested solution

The send max button is toggleable. That is, it can only be on or off, a binary value that behaves like a checkbox. 

Currently, it's a action that just updates the input. This doesn't leave a sufficient way to determine that the user wants to spend all.

While the _send max_ is enabled, the form is not editable, or if it is edited, then the send max toggle is disabled/set to off.

The user must be taught that, when selecting send max, the amount received depends on fee selected.

**Comment by mica000** [comment]
@kyranjamie I don't understand the need for a toggle on this. Would a solution like this work?

<img src="https://user-images.githubusercontent.com/119523541/219367827-dff1f5e5-b674-4f63-ae4d-595534576071.png" width="354" />

**Comment by markmhendrickson** [comment]
This appears handled by https://github.com/hirosystems/stacks-wallet-web/issues/3141 as part of the general improvements there.

**Comment by mica000** [comment]
Copy udapte to "Send max {#}"

<img width="354" alt="Screenshot 2023-02-17 at 17 41 59" src="https://user-images.githubusercontent.com/119523541/219713113-88fe8b8f-8ecc-4005-a487-f086551ed933.png">

**Comment by kyranjamie** [comment]
Sorry for not replying to this msg Michelly.

This issue isn't complete, it requires more than just a copy change. I'll update the main issue body with a more explicit explanation.

**Comment by mica000** [comment]
Figma: https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=4655-97133&t=Vm6jIBs9X1VIuzNv-4

**Comment by mica000** [comment]
Reviewing this build: https://github.com/hirosystems/wallet/actions/runs/4980318506

Here are the things I spotted that were missing:

**SENDING MAX CTA**
- When sending max, cta should be in a pressed state. 
- When hovered, send max should show a tooltip: "This amount is affected by the fee you choose"
![Image](https://github.com/hirosystems/wallet/assets/119523541/68caa41d-5823-46a5-aec8-2db85abd0e34)

-----


**CHOOSE FEE (New ticket maybe?)**
- Include sats/vb
![Image](https://github.com/hirosystems/wallet/assets/119523541/47c70cac-1684-4c4c-a084-d7943d1e99a5)

-----

**SENDING ANY AMOUNT**
When sending an specific amount, the sending amount will also change to cover the fee. cc @kyranjamie as he know more about this use case.
- I was unable to test this as it depends of having really high fees
![Image](https://github.com/hirosystems/wallet/assets/119523541/28b5e351-0cbd-4a2b-a9f5-1c05cebd4d32)

**Comment by mica000** [comment]
@markmhx Should showing the available balance be added to this release or be solved in a separate ticket?

![Screenshot 2023-06-05 at 18 18 39](https://github.com/hirosystems/wallet/assets/119523541/c8a75418-0b35-42a4-bd88-fd95ee270998)

**Comment by mica000** [comment]
Copy improvement

Button copy while on default: Send max
Button copy while on pressed: Sending max


![Image](https://github.com/hirosystems/wallet/assets/119523541/74206786-4825-427d-9520-61161a2ca7ee)

**Comment by mica000** [comment]
When sending max is enabled, it's hard to know how to undo the step. Was initially thinking that by clicking in the value input field, we should disable the sending max and return the value to zero so it becomes editable again. WDYT?

![Image](https://github.com/hirosystems/wallet/assets/119523541/0bf1623b-d7f5-4c2b-9a2d-be398c4f928f)

**Comment by mica000** [comment]
@kyranjamie @markmhx @314159265359879 what do you think about removing the btc value in order to simplify the information we are showing?

![Image](https://github.com/hirosystems/wallet/assets/119523541/57a21e00-5485-4b3c-82fb-c56fe1b0c622)

**Comment by mica000** [comment]
Logic seems to be working fine tho! 

cc @kyranjamie would be valuable to have your knowledge around the edge cases for sending max to make sure we are covering all of the ones we discussed

**Comment by markmhendrickson** [comment]
> what do you think about removing the btc value in order to simplify the information we are showing?

Hmm it seems pretty important the user knows exact how much in BTC they'll be spending on fees

**Comment by markmhendrickson** [comment]
> Was initially thinking that by clicking in the value input field, we should disable the sending max and return the value to zero so it becomes editable again. WDYT?

Yea that could work

**Comment by markmhendrickson** [comment]
> Should showing the available balance be added to this release or be solved in a separate ticket?

Let's solve in this issue

**Comment by markmhendrickson** [comment]
@alter-eggo assigning to you to help integrate this design QA feedback next after your current WIP.

Note that this issue's PR has already been merged into dev. Can we revert that before making these changes, so we don't block other releases in the meantime?

cc @kyranjamie

**Comment by fbwoolf** [comment]
> Yea that could work
>
I really thought this was more confusing when I implemented it. 🤔 

EDIT: I think when I did it I didn't clear it to zero though, so that prob makes more sense. 👍

**Comment by fbwoolf** [comment]
> Let's solve in this issue
>
Pretty sure I added this in the custom fees draft PR?

**Comment by fbwoolf** [comment]
~~I feel like the copy fix on the button could be done and this could be released? Why revert this?~~ Nvm, if the UX behavior change is needed.

**Comment by kyranjamie** [comment]
> @alter-eggo assigning to you to help integrate this design QA feedback next after your current WIP.
> 
> Note that this issue's PR has already been merged into dev. Can we revert that before making these changes, so we don't block other releases in the meantime?
> 
> cc @kyranjamie

These all seem like fairly quick/minor improvements, so let's just fix rather than reverting

**Comment by markmhendrickson** [comment]
@314159265359879 FYI this is indeed live now with https://github.com/hirosystems/wallet/releases/tag/v4.29.0
