### ISSUE TITLE
Add option to "replace/delete" transaction

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3137]
Technically we can't "delete" a transaction we can only replace it by fee. This is changing a transaction by creating a new one with the same nonce but a higher fee than the initial transaction. Sometimes called RBF-ing. 

The delete button would do the following in effect:
A. Create a STX transfer of 0.000001 STX to the genesis address, add some common memo "~~deleted~~" same nonce as the transaction selected for deletion and a minimum fee that is 1 uSTX higher than current: for example 0.003001 STX if the default fee was used initially. 
The memo, the transfer amount and receiving address could be used to filter these transactions as a `deletedTX` so the wallet shows them as "deleted transaction" rather than (or in addition to) a 1uSTX transfer. If there is already a transaction with the nonce of the deleted transaction it could be ignored completely by the wallet (not show it on the activities tab for example). 

I don't believe a replace transaction option is a viable option. Because often a dapp is needed to construct the new transaction. A delete option like this would simply allow the user to move on. 
If Xverse can uses the same method (transfer amount to genesis and memo) we could even detect "deleted" transactions across wallets.

**Comment by markmhendrickson** [comment]
Thanks for this additional report, though closing as a dupe of https://github.com/hirosystems/stacks-wallet-web/issues/1834 where it will remain linked for context
