### ISSUE TITLE
[Bitcoin] Represent only confirmed amounts in BTC balance

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3140]
I saw this once. 

Tested at least four more transfers afterwards but didn't see this again.

**Comment by markmhendrickson** [comment]
Is this the sort of scenario you've seen?

1. You have 3 BTC and balance indicates 3 BTC
2. You send 1 BTC and the transaction is pending
3. Balance continues to indicate 3 BTC (whereas 1 BTC is expected?)

**Comment by 314159265359879** [comment]
I have ~10 mBTC incoming, it shows available on the balance tab whereas on activity tab it still shows pending. See video I opened the block explorer to check what that is saying: Unconfirmed. 

https://user-images.githubusercontent.com/33360391/219152660-620c213e-e4e0-4e22-a5dc-29c9dc19e0ca.mp4

**Comment by markmhendrickson** [comment]
It does seem that we're handling inbound BTC and STX differently:

- With Bitcoin, inbound pending amounts _are_ captured by the balance in addition to confirmed ones
- With STX, inbound pending amounts _are not_ captured by the balance, microblock ones are displayed in a sub-balance, and anchored / confirmed ones show up in the main balance

We should alter the Bitcoin behavior so that pending amounts _are not_ captured so it's consistent.

**Comment by markmhendrickson** [comment]
<img width="931" alt="Screenshot 2023-02-16 at 08 18 11" src="https://user-images.githubusercontent.com/28991/219307908-1c981ab7-b641-4b8f-b66e-56bb1f0a4960.png">
<img width="984" alt="Screenshot 2023-02-16 at 08 18 08" src="https://user-images.githubusercontent.com/28991/219307911-1018f9ef-63fd-4729-865f-99bb1d95097b.png">

**Comment by markmhendrickson** [comment]
Note that in addition to showing the pending amount in the balance, it also shows up in the send form, affecting the maximum amount that users are able to send (whether successfully or not).

**Comment by markmhendrickson** [comment]
In my most recent testing with v4.1.0, I'm not seeing this anymore but I also don't see what recent PR could have resolved it 🤔

**Comment by 314159265359879** [comment]
I saw this pop up again (unconfirmed btc showing as available). Couldn't create screenshots on time. because about an hour after this was posted this transaction got confirmed (4 days in the mempool). 

![image](https://user-images.githubusercontent.com/33360391/222925117-6559322a-26ba-4092-aaeb-359a9dce4fe0.png)


I will keep this closed until I am sure what status is causing this.
