### ISSUE TITLE
Display available balance in send form

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3143]
We should display how much of the token in available balance the user has to send when viewing the send form.

As the user enters an amount to send, we could also indicate something like "Estimated subsequent balance: ~0.132 BTC" or something (though we wouldn't know the fees until the next screen, so perhaps it's best to show this "post" balance on the final review screen instead?).

**Comment by mica000** [comment]
Designs for showing the available balance before sending:
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1101%3A56132&t=Shl5eSB4xRFAbQkH-4

<img width="511" alt="Screenshot 2023-02-16 at 12 48 31" src="https://user-images.githubusercontent.com/119523541/219362814-9a7db5d4-2861-4a88-b921-6e58b4ffa592.png">

-----------

For the post balance, I'm not 100% sure the information should be displayed at the end of the flow,  
I feel like this should be available to the user when returning to the wallet main page (ofc this should be updated as well and we should display the states clearer as the current arrow isn't explicit enough)

However, until we don't fix the arrow and the balance, displaying on the review and sent steps could make sense at least for the short term.
<img width="778" alt="Screenshot 2023-02-16 at 13 33 27" src="https://user-images.githubusercontent.com/119523541/219366112-06d384c0-14dc-422b-99e9-9c79967702e5.png">

Designs available here 
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1101%3A56854&t=Shl5eSB4xRFAbQkH-4

**Comment by mica000** [comment]
Designs above have been updated: 
<img width="1018" alt="Screenshot 2023-02-17 at 16 07 23" src="https://user-images.githubusercontent.com/119523541/219692428-2a741383-a27c-43c7-954c-16195d4b2873.png">
