### ISSUE TITLE
[Bitcoin] Copy bitcoin address button doesn't work under account name

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3151]
![image](https://user-images.githubusercontent.com/33360391/219155897-9098f371-68d9-4a12-8f2d-d4e97b88d3ed.png)

This copies the stacks address instead of the (t)BTC address, the other two copy buttons work as intended.

**Comment by markmhendrickson** [comment]
This appears resolved in the latest build
