### ISSUE TITLE
[Bitcoin] Select account list

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3157]
With one item it's not displaying correct 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/1618764/219302292-d19ba1c6-f81b-4470-bc5d-3cfda5734717.png">

**Comment by markmhendrickson** [comment]
@alter-eggo might be a good one to check out 🙏

**Comment by alter-eggo** [comment]
seems it is already fixed in some other pr
