### ISSUE TITLE
Add up and down arrows for BTC transactions to indicate outbound vs. inbound

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3160]
Note how we currently have these for STX transfers, and the color changes between orange (for pending) and blue (for confirmed):

![Image](https://user-images.githubusercontent.com/28991/219317728-5257cd5f-ab9e-474c-a060-5a5c3e53c2b7.png)

![Image](https://user-images.githubusercontent.com/28991/219318514-d41bb669-cf23-4d49-aeaf-d993c4a90bb5.png)

cc @mica000

**Comment by mica000** [comment]
@markmhx Got it! Seems good to me!
