### ISSUE TITLE
[Bitcoin] Add dust detection

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3163]
UTXOs that cost more to send than their value should be filtered out from utxo selection and balances.

**Comment by markmhendrickson** [comment]
This is to prevent unnecessarily high fees, yea?

**Comment by kyranjamie** [comment]
Kinda. Would phrase as preventing economically illogical transactions. If I have 10 dust utxos, the fee wouldn't be crazy high in absolute terms to spend, but doesn't make sense either.
