### ISSUE TITLE
[Bitcoin] Content can escape bounds of containing box

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3166]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/1618764/219423397-e7cfe6d9-30f0-4367-a96a-70ff768fee7c.png">

**Comment by fbwoolf** [comment]
Sorry, did too fast. Will look.

**Comment by fbwoolf** [comment]
Not seeing this so maybe I fixed on my current branch with some other UI things? It grows for me, where did you see this?  I'll link this issue to my PR when I put it up so you can check it again.

![Screen Shot 2023-02-16 at 2 46 28 PM](https://user-images.githubusercontent.com/6493321/219483284-ba2f223e-2af7-409f-833b-06041736230f.png)

**Comment by fbwoolf** [comment]
Also fixing on my branch the width to match new designs and losing the outline on narrowing the full page view... cc @mica000 

![Screen Shot 2023-02-16 at 3 01 19 PM](https://user-images.githubusercontent.com/6493321/219485953-7dc9a3ae-a74b-45ff-852e-3354855a10c0.png)

![Screen Shot 2023-02-16 at 3 01 32 PM](https://user-images.githubusercontent.com/6493321/219485990-7437709c-1790-4e5e-8534-da1d551c9d59.png)
