### ISSUE TITLE
Improve high fee warning UI

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3178]
Include way to test with overriding fees provided by API

**Comment by mica000** [comment]
<img width="1191" alt="Screenshot 2023-02-17 at 20 38 34" src="https://user-images.githubusercontent.com/119523541/219772805-86afeb77-f1a1-42a5-85db-a798361ea963.png">

https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1110%3A59159&t=0OeOFKmcaHOATyvZ-4

<img width="1307" alt="Screenshot 2023-02-17 at 20 41 27" src="https://user-images.githubusercontent.com/119523541/219773969-2350dced-2613-478e-9436-fcf0d6ffe235.png">

<img width="1306" alt="Screenshot 2023-02-17 at 20 41 08" src="https://user-images.githubusercontent.com/119523541/219773977-ba56b93a-54c0-41b1-bed0-bfb2206fd378.png">

**Comment by markmhendrickson** [comment]
These two warning variants are captured [here](https://www.notion.so/trustmachines/Fee-is-unusually-high-add170c8724f4833a53fc8278b224ed1?pvs=4) and [here](https://www.notion.so/trustmachines/Fee-requires-adjustment-of-principal-24028514bd41488d9fcb9ea3ea3fed36?pvs=4) for the new approval UX.
