### ISSUE TITLE
Support inscription sends

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3184]
The simplest way to design this to start may be to have an option for each displayed inscription under "Collectibles" for "Send" that when selected, reveals a simple form with one input for entering the recipient taproot address (with no other types accepted).

This approach would **not** include supporting inscriptions in the regular "Send" form for tokens but rather keep it separated here with the listed inscription to avoid the complexity of modifying the generic send form's token type picker, validation, fields, etc. to support them there.

**Comment by markmhendrickson** [comment]
Emblem Vault has expressed interest in this for moving inscriptions into vaults

**Comment by mica000** [comment]
COMPONENT: COLLECTIBLES + SEND CTA
![Image](https://user-images.githubusercontent.com/119523541/221895298-9d4dd696-7686-46e1-999f-7218ad49e3fd.png)
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1182%3A76377&t=EXEsEfYWsFzGfR35-4

SVG
![Image](https://user-images.githubusercontent.com/119523541/221896103-de29c39a-8643-44c4-9a01-5f9b059ec36c.svg)
![Image](https://user-images.githubusercontent.com/119523541/221896101-a01a2cde-1cdb-4b48-bb4b-09d3c6e05471.svg)
![Image](https://user-images.githubusercontent.com/119523541/221896100-d70a51c9-a8ae-44c5-8b1b-ada5e71fc135.svg)


-----

COMPONENT: ORDINAL ON THE MODAL
![Image](https://user-images.githubusercontent.com/119523541/221895280-e9453dac-5e19-4444-909c-86785483c81f.png)
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1540%3A72559&t=EXEsEfYWsFzGfR35-4

-----

USER FLOWS
![Image](https://user-images.githubusercontent.com/119523541/221895255-3de87837-b9d2-4e15-b154-75bf2ecb60f7.png)
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1540%3A72547&t=EXEsEfYWsFzGfR35-4

-------
