### ISSUE TITLE
Add transaction confirmation screen for sends

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3186]
For displaying a summary of a submitted transaction post-send instead of taking the user directly to the activity tab.

@mica000 can you add the designs you have here in a comment?

**Comment by mica000** [comment]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1110%3A56076&t=WDO37BU3n4AjE9xz-4
<img width="339" alt="Screenshot 2023-02-18 at 17 48 35" src="https://user-images.githubusercontent.com/119523541/219877880-099f6ade-1721-4ac6-b1c1-95e0cb6b6af5.png">

**Comment by markmhendrickson** [comment]
Note we'll need to add this confirmation screen not only for regular token sends but also inscriptions per https://github.com/hirosystems/stacks-wallet-web/issues/3332#issuecomment-1451752021
