### ISSUE TITLE
Enhance fiat onramp options to support BTC purchases

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3188]
In addition to STX for direct deposit into wallet

cc @jonastgerber

**Comment by markmhendrickson** [comment]
See relevant Wert docs here in case we want to add them alongside other providers: https://docs.wert.io/docs/introduction

**Comment by markmhendrickson** [comment]
@fbwoolf Curious if the tokens selector component as built for the swaps modal could be reused for this feature by prompting the user with "Choose asset to buy" upon selecting "Buy" from the home screen and before taking them to the buy screen itself, with the token value populated in the page (e.g. `Choose an exchange to fund your account with Bitcoin (BTC)` instead of STX etc.)

<img width="402" alt="Screenshot 2023-11-14 at 11 41 44" src="https://github.com/leather-wallet/extension/assets/28991/fc0ab6ed-3a4f-4fe9-ae6f-ba64613e0f81">

And @fabric-8 @mica000 if this approach strikes you as the easiest / best path to supporting BTC (and, in the future, other tokens for purchase as well)

**Comment by fbwoolf** [comment]
> @fbwoolf Curious if the tokens selector component as built for the swaps modal could be reused for this feature by prompting the user with "Choose asset to buy" upon selecting "Buy" from the home screen and before taking them to the buy screen itself, with the token value populated in the page (e.g. `Choose an exchange to fund your account with Bitcoin (BTC)` instead of STX etc.)
> 
Yeah, I think this could likely be refactored and shared ...we also have a 'choose asset' list on the send form. We should prob just have one choose asset dropdown. I think the intention here long term was to have it be a dropdown not a popup.

**Comment by mica000** [comment]
This list component was refactored to become a dropdown if Im not mistaken? If we want to trigger a list from the home screen, then I am afraid a dropdown like the one developed for swaps, that uses radix as a base, wont work. 

I believe we might need to refactor this list component also on the design side.
