### ISSUE TITLE
Display fiat value below crypto amount in send form

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3191]
We should show the fiat conversion value below the amount entered in STX or BTC here:

![image](https://user-images.githubusercontent.com/28991/219900976-bed40d7f-e0e6-404d-a958-64d1bb5cf131.png)

It currently looks like this:

![Screenshot 2023-02-18 at 13 46 43](https://user-images.githubusercontent.com/28991/219900979-f4f4eb6f-bc84-4083-9ca9-5a35ee2617d6.png)

Note that https://github.com/hirosystems/stacks-wallet-web/issues/3189 is for adding the option to swap whereas this issue is specifically for displaying the fiat value only (and not being able to swap the values). So this issue should come first.

**Comment by alter-eggo** [comment]
add autofocus also on amount field
