### ISSUE TITLE
Show non-image inscriptions with placeholder image

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3193]
Currently we don't display non-image inscriptions but should with a placeholder image.

@mica000 mind providing a design for this placeholder?

**Comment by markmhendrickson** [comment]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1182%3A76377&t=jI0fdMbNfm3xMWXc-1



![Image](https://user-images.githubusercontent.com/28991/219952160-8c6cb367-6058-4044-a40b-258907ee361d.png)

**Comment by mica000** [comment]
SVG
![Image](https://user-images.githubusercontent.com/119523541/219964111-8d1d55c7-a7ff-4f61-9ba6-85bae0a6c6b6.svg)
