### ISSUE TITLE
Update styles for "Add new" option in collectibles area

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3199]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1182%3A76377&t=H4pGkYXsGMLRHOAN-1

![Screenshot 2023-02-19 at 05 42 30](https://user-images.githubusercontent.com/28991/219952046-1e6ce347-e893-4e0f-83f7-4ecc49160de9.png)

**Comment by kyranjamie** [comment]
Needs a focus state 🔎 ♿

**Comment by mica000** [comment]
![Image](https://user-images.githubusercontent.com/119523541/219957729-3371a961-74f0-41f4-9cfe-4f2449b9b604.png)

Icon size: 24px 
Bouncing box: 40px


SVG:
![Image](https://user-images.githubusercontent.com/119523541/219957885-e1f04fba-1ffb-40a9-a48c-5afebea38035.svg)
