### ISSUE TITLE
Convert Bitcoin feature flag into remote config

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3201]
Currently the user can toggle Bitcoin functionality in the console with `debug.setBitcoinFeature(true)`

We should convert this user-facing option into a remote configuration for us to turn off and on for users as a team, in preparation for roll-out.

Note that the "Add now" option for inscriptions under "Collectibles" shows even when Bitcoin is turned off, so it should be brought into the coverage of the feature flag as well so it doesn't appear unless flipped on.

![Image](https://user-images.githubusercontent.com/28991/219954496-631eb13b-048e-4307-88ca-d3b68d7596e8.png)

And we should take care not to show the collectibles area in general if Bitcoin is turned off and there are no Stacks NFTs to show there per https://github.com/hirosystems/stacks-wallet-web/issues/3200

**Comment by fbwoolf** [comment]
Going to close this bc PR was merged into dev. Will use flag to show/hide the ordinals collectibles in another PR.
