### ISSUE TITLE
Enhance inscription deposit prompt with apps

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3202]

**Comment by mica000** [comment]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1203%3A61905&t=EXKw9FjLtTgJvDeF-4
<img width="507" alt="Screenshot 2023-02-19 at 16 10 30" src="https://user-images.githubusercontent.com/119523541/219957208-20896da6-c9df-4594-ab2f-e93ad44753f6.png">

URL: https://gamma.io/ordinals / https://ordinalsbot.com/

**Comment by markmhendrickson** [comment]
Looking good! Now that we have the "Use your wallet to create..." part, I'm thinking we can simplify the header to "Deposit Ordinal inscription". Wdyt?
