### ISSUE TITLE
Improve empty state for home screen so users can deposit inscriptions without balance

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3206]
To ensure that users can see zero balances for both Bitcoin and Stacks, as well as an empty Collectibles area with the "Add new" option, even if they don't have any of these assets already.

Current empty state, which doesn't show any indication of Bitcoin balance or Collectibles:

![Image](https://user-images.githubusercontent.com/28991/219972145-b6e23e4c-fb5e-4485-ad61-d3e927540c2a.png)

**Comment by mica000** [comment]
[Figma file with all the flows here.](https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1255%3A61994&t=vlaQI2yuSVhSCe5M-4) 👋

--------
<img width="1497" alt="Screenshot 2023-02-20 at 11 53 08" src="https://user-images.githubusercontent.com/119523541/220085724-dc740262-0087-4078-8f70-602118872200.png">

SVG
<img width="55" alt="add-funds-light-sm" src="https://user-images.githubusercontent.com/119523541/220085628-7d748a28-6bee-4817-9185-c3c9a7857ed1.png">
<img width="132" alt="add-funds-light" src="https://user-images.githubusercontent.com/119523541/220085631-407fe509-0b3e-4887-952d-a5d421eeab93.png">
<img width="55" alt="explore-apps-light-sm" src="https://user-images.githubusercontent.com/119523541/220085633-ae8ba047-a51b-4e9f-9206-98d519e7afaf.png">
<img width="132" alt="explore-apps-light" src="https://user-images.githubusercontent.com/119523541/220085637-6fc78bd0-b738-4e6c-b4fb-d8b907937d01.png">

---------------

<img width="1489" alt="Screenshot 2023-02-20 at 11 53 01" src="https://user-images.githubusercontent.com/119523541/220085731-59963aee-4948-4b0c-b895-9b2a110afab8.png">

---------------

<img width="2351" alt="Screenshot 2023-02-20 at 11 52 48" src="https://user-images.githubusercontent.com/119523541/220085738-8b23207e-18d5-4485-956b-1b14b8cbd702.png">

---------------

<img width="2205" alt="Screenshot 2023-02-20 at 11 52 35" src="https://user-images.githubusercontent.com/119523541/220085740-9015fe87-9491-4a99-a00d-b6e20e796e35.png">
