### ISSUE TITLE
Add event tracking to "Add new" collectible flow

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3210]
Trigger `select_add_new_collectible` when the user selects the "Add new" unit from under "Collectibles" and then `select_type_to_add_new_collectible` when user selects either displayed option, with property `type` set to "inscription" or "nft" depending on selection.

If user proceeds to view subsequent inscription modal and selects "Proceed to copy address", trigger `copy_address_to_add_new_inscription`.

**Comment by edu-stx** [comment]
Closed in https://github.com/hirosystems/stacks-wallet-web/pull/3198
