### ISSUE TITLE
Revisit send form tests

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3215]
I added some prohibited `waitForTimeout` uses as a quick fix. Further, let's figure out how to [manage page objects](https://playwright.dev/docs/pom) and avoid too much repetition of selector look ups.

**Comment by fbwoolf** [comment]
I did use here: https://github.com/hirosystems/stacks-wallet-web/blob/b1faab126720ad17426731622e309c3b42a49cd9/tests/page-object-models/home.page.ts#L10

I noticed you put in the spec file, is that preferred?

**Comment by kyranjamie** [comment]
Nope, let's move to a SendForm page object. Just did it that way to avoid some of the repetition/readability

**Comment by fbwoolf** [comment]
I am going to tackle this bc I started them. We can add to them later but want to get the ones we have refactored and working.

**Comment by fbwoolf** [comment]
If there are important ones to add, let's add a list to this issue? The btc form needs field validation tests.
