### ISSUE TITLE
[Bitcoin] Transaction sort order 

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3223]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/1618764/220160590-4f8a9d45-2fe6-4da5-a2ce-a61288d1d224.png">

should be the other way around

**Comment by markmhendrickson** [comment]
Related reports: https://github.com/hirosystems/stacks-wallet-web/issues/3121 https://github.com/hirosystems/stacks-wallet-web/issues/2990

**Comment by kyranjamie** [comment]
closed as dupe
