### ISSUE TITLE
Ordinal inscription addresses should be taproot addresses

### ISSUE THREAD

**Issue by badonyx** [blockstack/blockstack-app#3228]
The UI for testnet and the images from recent work being done (like PR https://github.com/hirosystems/stacks-wallet-web/pull/3198) all show `bc1q` or `tb1q` addresses which are native segwit and not taproot addresses. 

![](https://user-images.githubusercontent.com/6493321/219885116-7d51bc67-4dce-4a09-93c8-e80ac55c1230.png)

**Comment by 314159265359879** [comment]
Yes this was fixed in a later version of PR3198, thanks for being sharp. Looks good in current production version. 
![image](https://user-images.githubusercontent.com/33360391/220203737-119e9c2b-1cae-4279-b417-edc092fbdafb.png)
