### ISSUE TITLE
Restoring from seed: change copy to convey support for existing BTC accounts/secret keys

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3236]
A user pointed out not being sure if they could use their sparrowwallet key on Hiro. Editing the copy may help clear that up. Here are a couple suggestions, feel free to improve further. 

Firstly
"Already have a Stacks or Bitcoin account?"

Secondly
"Enter your 12 or 24-word Secret key to sign in to Stacks Wallet with an existing Stacks or Bitcoin account."

![image](https://user-images.githubusercontent.com/33360391/220345362-a7693fb7-d5e6-4f02-992c-b71003853ada.png)

![image](https://user-images.githubusercontent.com/33360391/220344768-ffcc0cf3-5bc8-48a6-ad46-e29f5092640b.png)

**Comment by markmhendrickson** [comment]
I'll consolidate with https://github.com/hirosystems/stacks-wallet-web/issues/3158
