### ISSUE TITLE
One address for ordinals

### ISSUE THREAD

**Issue by badonyx** [blockstack/blockstack-app#3243]
In #3091 it was said about ordinals that "you can store them in your wallet but only one Ordinal per taproot address," so it seems that Hiro's taproot and ordinal support was designed around this principle. 

However this is a faulty assumption based on general advice given to end users of other software due to lack of proper support for the necessary type of coin control. As far as I'm aware, there is no technical reason that Hiro could not handle receiving and sending multiple ordinal inscriptions and non-inscribed UTXO all on one single address, given implementation of appropriate coin control. 

For reference see https://docs.ordinals.com/guides/collecting/sparrow-wallet.html#sending-inscriptions-with-sparrow-wallet

**Comment by 314159265359879** [comment]
Hi @0xbabo, thanks for commenting! you are right we added this comment while under the assumption that it may be easier to get a transfer function out faster, easier. We have since learned it is not to difficult with ordinals on the same address. 
That is why we support both ordinals on the same address as well as on different addresses. 

The copy on the current version has already been adjusted 4.0.2.

**Comment by badonyx** [comment]
> The copy on the current version has already been adjusted 4.0.2.

I don't know what that means. Are you saying this is already implemented in 4.0.2? I can receive and send multiple ordinals from one address, and the proper coin control has been implemented so I won't unintentionally lose ordinals?

**Comment by markmhendrickson** [comment]
Yep that's correct. From v4.0.0 onwards, users could receive multiple ordinals to the same address. And when we add sending (not yet available but coming soon), we'll make sure to implement it in a way that's "smart" so you won't lose any. I imagine the UX will be something akin to a "picker" so you can select which one to send. And if we ever let you sent bitcoin out of it like normal, we'll have coin control there as well.

v4.0.2 was simply a copy adjustment so the UI wouldn't confuse users into thinking they had to use separate addresses, which was not the case anyway.
