### ISSUE TITLE
Display loading indicator for inscriptions in collectibles

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3244]
So user doesn't just see blank area while waiting and wondering if it's broken

**Comment by mica000** [comment]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1203%3A62712&t=7DhxNnIW77vRWj5q-4
https://user-images.githubusercontent.com/119523541/220953312-ade96354-b2e6-495e-99a8-6bf360cbdec9.mov

cc @edu-stx
