### ISSUE TITLE
Auth broken when Gaia is down

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3246]
There's no error handling for the Gaia operations when performing an auth request.

On auth, we do a handful of operations to update the Gaia profile of the user. If Gaia is down, auth breaks entirely as we don't handle the errors.

https://user-images.githubusercontent.com/1618764/220574040-4c0d3f62-9b00-45b8-a8cb-cf887a25ada5.mp4

<br /> 
I set the stopwatch for added drama.

**Comment by markmhendrickson** [comment]
Let's future-proof with https://github.com/hirosystems/wallet/issues/3564
