### ISSUE TITLE
Pending transactions in one account showing in the activities tab on another (temporarily)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3248]
Copied from Discord: 
Hey Hiro crew, I was switching through my accounts and pushing some small amounts around, I noticed that in the activity tab the pending information of a transaction in 1 account was showing in all the other accounts, it was temporary, i just had to click out and click back in and it showed the moves in each account correctly and in micro block i guess.  I was just wondering if this is a pre micro block feature, or something buggy.  Had noticed before once upon a time.

**Comment by pete-watters** [comment]
I've tested this and am unable to reproduce. I performed a transfer and can only see the pending transaction in the account I transferred it from.
