### ISSUE TITLE
Sending multiple transactions one after another I got this ERROR

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#3251]
I sent 2 transactions back to back to the same address and got this ERROR message using v4.0.1

<img width="1187" alt="Screen Shot 2023-02-22 at 11 08 58 AM" src="https://user-images.githubusercontent.com/49165468/220686052-7d45d319-96bb-49e8-a49b-78f7863ed41a.png">

**Comment by markmhendrickson** [comment]
Hmm @kyranjamie thoughts here on how this might happen?

**Comment by markmhendrickson** [comment]
@timstackblock if you try again now to send the 2nd transaction from the same wallet, does it work? Wondering if the issue was time-dependent.

**Comment by kyranjamie** [comment]
What's the balance on the account, @timstackblock ? can you share address

**Comment by timstackblock** [comment]
Its just a random burner wallet I created for testing so you can log in and play around

tb1qw2hun5eea97nuuqjq02v5434audlecylcxf3u6
ST1ZS69KNYN1K7RS8V4CWPT16Q8HGDD5C5CX84405


"notice couch eye model burst extend marriage fragile whale furnace also ancient spice sea industry erode habit reject three pink salon rail roast fabric"



Let me double check I think the issue was it let me send max amount twice back to back without stopping me. I was allowed to send max twice because it was reading a pending balance. If you already fixed the pending balance issue that may stop this from happening. Let me see if I can get a video.

**Comment by markmhendrickson** [comment]
@timstackblock the pending balance issues seems fixed for me in v4.1.0, does it for you too?

**Comment by timstackblock** [comment]
let me take a look

**Comment by timstackblock** [comment]
Looks good I wasn't able to reproduce
