### ISSUE TITLE
account balance has 0.01698908 BTC but popup on send page has balance is 0

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#3252]
Account balance on balance page  has 0.01698908 BTC
But popup on send page that shows balance has balance = 0

<img width="1112" alt="Screen Shot 2023-02-22 at 11 15 01 AM" src="https://user-images.githubusercontent.com/49165468/220687488-2b530eec-b306-4ecb-9e91-aab85a93e8d9.png">
<img width="993" alt="Screen Shot 2023-02-22 at 11 14 15 AM" src="https://user-images.githubusercontent.com/49165468/220687494-4d458ab8-6a4c-40e1-ace7-c775d9042d55.png">

**Comment by markmhendrickson** [comment]
Might of you had pending inbound BTC? We're resolving an issue with showing those pending amounts in the balance here: https://github.com/hirosystems/stacks-wallet-web/issues/3140

**Comment by fbwoolf** [comment]
This $ amount is the STX balance, isn't it?

EDIT: The BTC balance shown in the lower left of the send form is correct.

**Comment by fbwoolf** [comment]
I do think how we are showing $ amounts is confusing when showing both addresses.

**Comment by timstackblock** [comment]
Yeah this is definitely not a show stopper just something to make it a bit easier for users. I think you guys did a great job with the bitcoin wallet you get this in an app on a mobile phone and everyone will use it.
