### ISSUE TITLE
User building extension from source experiences several errors

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3263]
Extension install in Brave throws an error: "Unrecognized manifest key 'browser_specific_settings'."

More specifically the code string throwing the error :
`
"browser_specific_settings": {
    "gecko": {
      "id": "{e22ae397-03d7-4622-bd8f-ecaca8c9b277}"
    }
  },
`

![image](https://user-images.githubusercontent.com/33360391/220777362-6c5c6204-5875-4deb-8903-8d058a865071.png)

Additionally

![image](https://user-images.githubusercontent.com/33360391/220777261-009ba743-9090-482e-b140-3fa9c22d9e0c.png)

![image](https://user-images.githubusercontent.com/33360391/220777824-10069bed-d6d2-4a9b-8bba-81d12e418263.png)

**Comment by wileyj** [comment]
From the reporter:
```
1. I clicked the purple button to DL source.
2. Saved zip folder to DL folder
3. Unzipped to User->Appdata->local
4. Opened Brave Extensions (my Dev mode is always on)
5 Clicked "Load Unpacked"
6. Selected the unzipped hiro folder from dir
7. In Brave tab the auto opened, initiated new wallet setup.
8. Recorded Seed
9. Created/confirmed password
10. Clicked "receive Bitcoin"
11. Sent in some sats from external self custody wallet
12. Once tx confirmed, attempted to connect and swap on Inswap
13. Clicked connect at app.LNswap.org
14. Selected BTC->STX
15. Clicked Start
```
![2023-02-22 15 18 04](https://user-images.githubusercontent.com/2847772/220785642-88cec7b0-0817-4ce4-8b4b-8ce137658f26.jpg)


@pseudozach

**Comment by wileyj** [comment]
seems like step 14 is the key

**Comment by 314159265359879** [comment]
Indeed sponsored transaction is only supported with LNBTC <--> STX
You will get an additional lightning invoice to pay the fee with Lightning. The dapp will pay the actual mining fee in STX for you "sponsored transaction". 

I am closing this issue, I assume the errors we saw are unrelated and are likely unrelated build errors. Like the code identified for Firefox and related errors can be ignored when building for Brave.
