### ISSUE TITLE
Reevaluate send form structure

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3268]
Now that we've rebuilt the send form, and pushed some changes quite quickly, it'd be a nice exercise to go through how we can improve the current structure. Assigned to you and I @fbwoolf, but @edu-stx @alter-eggo you're welcome to participate too.

As it is, there's quite some repetition of logic between forms. All of them, but especially stx/sip10. Now that they've been built, it'll be easy to identify what's duplicated and can be abstracted out & shared. Also, going through stx/sip10 and asking exactly differs between them (a few things, but too much), and creating abstractions there too.

**Comment by fbwoolf** [comment]
Yeah, noticing a lot of refactoring happened that occurred just in the btc send form but wasn't replicated in others (ex. form validation changes). Would be good to have these all consistent.

**Comment by markmhendrickson** [comment]
@alter-eggo to tackle this as part of his work on the SIP 10 confirmation screen but waiting until https://github.com/hirosystems/wallet/issues/3366 is merged first

@fbwoolf and @kyranjamie on hand to help with guidance
