### ISSUE TITLE
Amount field symbol UI bug

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#3278]
How should we handle symbols that are really long in the new amount field?

Also should handle in asset list.

![Screen Shot 2023-02-23 at 12 43 55 PM](https://user-images.githubusercontent.com/6493321/221009263-84b61a30-0408-4809-9ee3-0832575fb5cd.png)

![Screen Shot 2023-02-23 at 12 03 33 PM](https://user-images.githubusercontent.com/6493321/221009228-fa58fd7b-e710-45a3-a713-cd09721f28e6.png)

**Comment by markmhendrickson** [comment]
`ARK...SDA`?

**Comment by fbwoolf** [comment]
@markmhx looking into this today to fix, it appears @alter-eggo added a line in the code to catch this and forces a smaller font size (22px)...

https://github.com/hirosystems/wallet/blob/badce0794005276c338959c160e8a375c0e62442/src/app/pages/send/send-crypto-asset-form/components/amount-field.tsx#L60

![Screen Shot 2023-04-21 at 2 09 52 PM](https://user-images.githubusercontent.com/6493321/233716469-11abfc74-20b5-4d4e-a858-dfcaecd1e6c1.png)

Is this ok, or do we want to change to the ellipses?

**Comment by markmhendrickson** [comment]
Yep this looks ok to me!
