### ISSUE TITLE
Create Stacks assets for Ledger Stax

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3287]
We need these for the new Ledger device

<img width="966" alt="image" src="https://user-images.githubusercontent.com/1618764/221191408-597d8645-d254-4ca9-8cb0-dabb459acb39.png">

**Comment by mica000** [comment]
@kyranjamie this was already sent to them in Slack or am I missing smt?

https://trustmachines.slack.com/archives/C01FSJYT64S/p1677249641058139

**Comment by kyranjamie** [comment]
Just noticed it wasn't assigned to you/marked as done. If they confirmed the assets are good, let's close
