### ISSUE TITLE
[Ordinals] seed from sparrow wallet generating different taproot addresses, not showing ordinals

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3298]
Cyberdemon, coming from sparrow wallet is having trouble seeing their ordinal inscriptions. Seeded Hiro with the sparrow wallet key. They shared a lot of details from their other wallet that can perhaps help us track down why this is. They are seeing different taproot addresses and ordinals are not loading. They have about 5 inscriptions over 5 addresses. 

Here is a screenshot of the account addresses and the addresses in sparrow with the ordinals and they dont line up
![image](https://user-images.githubusercontent.com/33360391/221426089-68544808-1177-4fea-afa7-86093b72f953.png)
OIC, yes but they all show this basically
![image](https://user-images.githubusercontent.com/33360391/221432646-0e068ff0-39c3-498e-8fcd-1ce0f394289c.png)
and if I expand the address they don't line up either.

![image](https://user-images.githubusercontent.com/33360391/221426065-5975a6ab-0f10-4aa2-b79a-fd3beac740ea.png)

![image](https://user-images.githubusercontent.com/33360391/221426081-26a8cf59-1632-469e-bbf8-34f3649e999d.png)

**Comment by markmhendrickson** [comment]
@kyranjamie does the derivation path line up here?

**Comment by kyranjamie** [comment]
This is expected. In the switch account list, you're looking at native segwit, not taproot addresses.

If you copy an address from the receive ordinals flow, you should see an address that matches your sparrow wallet

**Comment by 314159265359879** [comment]
The taproot addresses didn't match either according to the user when using the ordinals flow.

The real issue though is that the ordinals are not loading. 

If the ordinals are in the first taproot of the the account (but not loading), they would show the next empty taproot address when "+Add new" is clicked? Hence the difference?

**Comment by kyranjamie** [comment]
Just tested and the taproot address matches sparrow, as it should.

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/1618764/221533742-3d763fad-67db-4336-927b-56cf1c5cff69.png">

Suggest closing this @314159265359879 as we have another issue for inscriptions now showing

**Comment by markmhendrickson** [comment]
@kyranjamie mind linking that other issue "we have another issue for inscriptions now showing")? I'm having trouble finding it (and assume it's cache busting specific?) 🙏

**Comment by kyranjamie** [comment]
this one https://github.com/hirosystems/stacks-wallet-web/issues/3297 ? @markmhx
