### ISSUE TITLE
Pixel art is upscaled with an inappropriate algorithm

### ISSUE THREAD

**Issue by badonyx** [blockstack/blockstack-app#3308]
![image](https://user-images.githubusercontent.com/110633279/221684861-2a1c324b-e143-4e42-8cb7-181156698d64.png)

Saw this posted somewhere. It looks like Hiro is upscaling with some basic algorithm that doesn't work well for pixel art. 

The one on the left is not pixel art, it is a higher res image, while the one on the right is 64x64 pixel art. Here is an example. 

![image](https://user-images.githubusercontent.com/110633279/221685868-964206cd-aa5e-4d68-9afc-c3d1338231ad.png)

For inspiration, refer to: https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms

**Comment by kyranjamie** [comment]
We can use https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering but in non-pixel art cases, this will look worse

**Comment by markmhendrickson** [comment]
Might `image-rendering: pixelated;` work best if we assume most small image inscriptions are pixel art?

**Comment by kyranjamie** [comment]
I've added this already for images < 40px
