### ISSUE TITLE
Prevent wallet from setting BTC lower than minimum allowed for send

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3309]
I have only seen this once so far. If it starts happening more often we could check the current logic or add the option for users to set low, medium or high fee instead. 

![image](https://user-images.githubusercontent.com/33360391/221695304-55686f3f-9723-46fb-8ca4-566fbbecba60.png)
![image](https://user-images.githubusercontent.com/33360391/221695325-7a8c1fbf-7b3d-4032-8bcb-f39743748877.png)
![image](https://user-images.githubusercontent.com/33360391/221695349-b47d4ec5-93ce-4b29-aa74-598c6905e59a.png)
![image](https://user-images.githubusercontent.com/33360391/221695362-5952c4cd-90c7-434a-b0d6-e37f7d7b9bba.png)

**Comment by 314159265359879** [comment]
@markmhx  The user reporting this had no pending bitcoin transactions.

**Comment by markmhendrickson** [comment]
@314159265359879 have you seen any more of these reports recently?

**Comment by 314159265359879** [comment]
I have not seen more. I think it is safe to close and open if it does pop up again.

With the option to set a custom fee, now available, it would now also be easy to work around this if it does pop up again.
