### ISSUE TITLE
Improve dark theme handling

### ISSUE THREAD

**Issue by hugoclrd** [blockstack/blockstack-app#3314]
Recent updates are really neat! But I noticed a couple of issues with the dark theme:

- There a theme transition on load when the dark theme is used (with "system" and "dark" preference). I think the default theme is "light". It's then switched to "dark" on load with needed, but because there's a [css transition](https://github.com/hirosystems/stacks-wallet-web/blob/420592cd1f4d4daca92c33d071304b49cb22c55e/src/app/components/global-styles/global-styles.tsx#L19), we first see the light theme, then transitioned to dark
- Just like [`img`](https://github.com/hirosystems/stacks-wallet-web/blob/420592cd1f4d4daca92c33d071304b49cb22c55e/src/app/components/global-styles/global-styles.tsx#L22-L24),  `svg` should have an invert filter so that coin logos are displayed with the right color

**Comment by kyranjamie** [comment]
Thanks for the feedback @hugocaillard. I've noticed these too, it can definitely be improved

**Comment by pete-watters** [comment]
@kyranjamie I think we can close this issue off now that https://github.com/leather-io/extension/issues/3361 was fixed.

Is that correct? Or is there still more work to do here

**Comment by kyranjamie** [comment]
Think this is fixed now
