### ISSUE TITLE
Add event to inscription send

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3334]
Trigger `send_inscription` when transaction to send inscription is submitted successfully.

**Comment by markmhendrickson** [comment]
@edu-stx I think you mentioned this was already released but just wanted to confirm?

**Comment by edu-stx** [comment]
Yes, it had already been added. The name was set to `broadcast_ordinal_transaction`, I understood that this name would work? Have PR here in case we want to change, your call.

https://github.com/hirosystems/wallet/pull/3436

**Comment by markmhendrickson** [comment]
That works! I see it in mixpanel now 🙏
