### ISSUE TITLE
Improve transaction colors for income and outcome activity

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#3339]
Improve they way we show income and outcome so there is more contrast between activities

![222404910-048d4d35-adce-4ed0-b2bb-d6cf6e133f22](https://user-images.githubusercontent.com/119523541/222516553-ecf2e6b1-5dc3-41c9-a99b-a4aa436d2441.png)

**Comment by Hero-Gamer** [comment]
what's the gameplan here? :)

**Comment by markmhendrickson** [comment]
Closing this as a duplicate in favor of https://github.com/hirosystems/stacks-wallet-web/issues/3213
