### ISSUE TITLE
Unmatching taproot addresses between sparrow and hiro

### ISSUE THREAD

**Issue by hozzjss** [blockstack/blockstack-app#3341]
## Bug report
The user C҉Y҉B҉E҉R҉ D҉E҉M҉O҉N҉ 6.6.69 has been trying to import his 12 word seed phrase into hiro but the generated taproot addresses don't match what they see in sparrow for some reason they provided these details and that the same happened in xverse as well

I copied the xpub key from the screen shots here hope this helps in any way
```
xpub6Bi5rtkW36GeL1RPeGxZGEgP1HpjfeUqbuA58JHbENftwV5NpcbjvBfw325NUHxLnmmHGNagxZ1VvSDgD45u9aAyRbTSnK7txsP3eLeUJyR
```

![image](https://user-images.githubusercontent.com/13457698/222541114-aa4ff88c-5672-4fc2-8658-3db822c7cf34.png)
Here are the addresses in the Addresses tab that they are on

![image](https://user-images.githubusercontent.com/13457698/222541244-12f23d31-33b4-495a-a64d-6de0a069b2e9.png)

Here are my wallets settings, and where I click to view the seed to import into Hiro

![image](https://user-images.githubusercontent.com/13457698/222541264-1e6799b6-c215-463b-bb03-defe1d3715bf.png)
I then import the 12 word seed phrase into Hiro
But none of the accounts line up with the addresses from Sparrow and it shows no BTC balance or inscriptions in any of them 
I can even "View Secret Key" and confirm that it is the exact same seed phrase from Sparrow

I made more accounts in Hiro to see if any inscriptions would show up but they dont.  And the addresses it generates do not match my sparrow addresses containing inscriptions.  The addresses Hiro generates are as follows: 
bc1pu5dy2zr0csmvk20p0n0hlxtdgmdgra0fh2v7xstl03s5w2lrp35qjv2y2n
bc1pw9ylsux5n8dgyjxm5yx7055zdv4zhnu2nu4zm072s86q8l68t9gql3l7kx
bc1pxkla9lv2qpvq569tcau5jp2xr9nl69wx2ppqwjxskmazlv7p2klqldk89f
bc1puhekm4zg4yctgr36vqcj07e64xhfjdkxuugxxrscvc2aqljg7c7svztseu
bc1pdx2w248wsr8dhe0sdtamt3v2qmyscuzpjzzrutwr0pxnqgar2jyqk04r9v
And those are the ordinals receiving addresses (not the regular BTC addresses).  Copied from here: 

![image](https://user-images.githubusercontent.com/13457698/222541611-d3cb2406-5446-4877-96a3-267a15db1b71.png)

But neither the accounts' ordinals addresses nor regular BTC addresses line up with what's in sparrow 
I hope that is enough info to start troubleshooting
And here are the addresses from my Sparrow wallet that contain inscriptions, which dont appear in Hiro (in case you need to copy/paste them):
bc1p9gjlk7h0j9235crals0k85mgavjup2xfu4ng6tc7kwdrrdwm24nquueasj
bc1pvcn5j22x38hsv9w5kvx9rc0cswdlge4hylz0dkz3664rhyju8djqsmd5zy
bc1p7jy0vvzknzu7enhquuj4w72ygeyzslvhj26h80jsjeds0y7t2hdsx4xhwl
bc1pt98fkm9zqfcqjrrydzx8ha78y7qw0trhkqlmpvhzgtr9xgx6xpksuq6rys
bc1pra9dj2lqmpx8dpu5sdhpahhrujfauh2a4hjhdeqzm2dd7usndwjq434mjj

**Comment by kyranjamie** [comment]
I tested now with a 12 word 
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/1618764/222684162-f4ea110b-d29b-49d4-8019-2118ccd82174.png">

I think it's quite likely the user entered a passphrase, which will yield different keys: 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/1618764/222684307-acf40a0f-cfda-44be-be4d-238b44f82189.png">

Closing as not a wallet bug

**Comment by markmhendrickson** [comment]
Confirmed on Discord this user indeed had a passphrase
