### ISSUE TITLE
Improve error message when user's UTXO doesn't have enough sats to pay fees

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3342]
A user has reported they're unable to send this inscription:

https://ordinals.com/inscription/35d5530afafc02f7c0ec8e0a4c7bd5a300f9d8c1229566f5e806c7c85452b8f7i0

However, it seems pretty normal in that:

1. Offset is 0
2. Doesn't share UTXO with other inscriptions
3. UTXO has 2821 sats, over minimum of 1500

What could be causing this error to appear?

![Image](https://user-images.githubusercontent.com/28991/222602112-f40e1d49-8c06-4da7-8d35-603c20eb4a69.png)

**Comment by markmhendrickson** [comment]
It turns out the case here was that the user didn't have enough sats in the relevant UTXO to pay fees. We should update the error message so it indicates this specifically for easier debugging.

![image](https://user-images.githubusercontent.com/28991/222636713-eed29bd7-3c40-4064-af68-7f61c36fa3ab.png)

**Comment by kyranjamie** [comment]
> UTXO has 2821 sats, over minimum of 1500 

1500 isn't a absolute minimum. It's 1500 + fee, so this quite likely could've hit that error.
