### ISSUE TITLE
Design a consistent way to display address on the send  flow

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#3354]
<img width="426" alt="Screenshot 2023-03-03 at 15 32 49" src="https://user-images.githubusercontent.com/119523541/222747166-5b120f6f-4e3d-4db9-9ebc-b2a03c232fa4.png">
<img width="479" alt="Screenshot 2023-03-03 at 15 32 24" src="https://user-images.githubusercontent.com/119523541/222747170-ace75f1a-a802-4d92-b518-ee9fa5fad6ea.png">

**Comment by markmhendrickson** [comment]
@mica000 is this ready for integration?

**Comment by mica000** [comment]
yes, @alter-eggo is currently working on it


https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1101-56854&t=aN1XBe9LZW9tw8mp-4

![Image](https://user-images.githubusercontent.com/119523541/224029161-e2c2fef2-d99b-4d51-ba41-1c5479ceed4f.png)
