### ISSUE TITLE
Ordinals not showing after logging back into the wallet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3358]
**User 1 dewan**
208694468e41112375626e29247ca8657d980840dba79b6af0d16438469eec23
https://www.blockchain.com/explorer/transactions/btc/208694468e41112375626e29247ca8657d980840dba79b6af0d16438469eec23   
Chrome/PC
Reloaded many times, reset react cache, didn't help. 

Confirmed NFT showing in sparrow wallet.

**User 2 heezyMD**
_Hello, I logged back onto my wallet and now the ordinal I previously created disappeared and my ordinal address has changed. It showed up in the wallet before. Is there a way to restore the previous ordinal address or link it back?_

**User 3**
Two accounts with ordinals not being loaded, not seeing any helpful messages in the console.
I do see that the taproot address generated to receive the next ordinal inscription is a fresh one. Different from the ones that have already received ordinals.

**Comment by 314159265359879** [comment]
**User 4 camilocuadros**
Migrated inscription from native segwit address to ordinals address but it is not showing after 67 confirmations. 

Restored the wallet from seed to exclude caching issues.

**Comment by markmhendrickson** [comment]
For those also using Sparrow, can we confirm that the Taproot address provided by Hiro Wallet is also showing up in their Sparrow list of addresses?

**Comment by 314159265359879** [comment]
I will confirm. I know user 3 is only using their seed with Hiro Wallet.

**Comment by 314159265359879** [comment]
User 4 is only using their seed with Hiro wallet, another inscription is showing up normally. 
This is the inscription not showing up:
https://mempool.space/tx/e7011ffc97e239e52e030c1cd98d4b8f1747ef63fe5f59edcf879cdee720dc86
ordinal https://ordinals.com/inscription/c9d48c469d832ff1dc558444e2beb202f7f7bf6e6e58a1010dfceb9a6cb8ef20i0

**Comment by 314159265359879** [comment]
User 5 Lucynator,  is only using their seed with Hiro wallet, 15 confirmations so far. Not yet showing up. 
b1df3a71a61e4f2dc7e8349a9b81de215ec6d69e750c140e9955206443ea8228
https://www.blockchain.com/explorer/transactions/btc/b1df3a71a61e4f2dc7e8349a9b81de215ec6d69e750c140e9955206443ea8228

**Comment by 314159265359879** [comment]
User 6 Ivan, saw ordinals earlier, but are now not displayed anymore.

**Comment by NikiTotit** [comment]
yeah, everyone having the same issue.  Collectibles are not visible.   Hopefully back soon.  All this ordinals volume have systems crashing all around us, feels like the bull again.  Funny how many Eth maxis we have that refuse to acknowledge the god chain.  Buy or cry.

**Comment by 314159265359879** [comment]
User 7: 20470 created inscriptions with gamma and send them from the ordinals wallet to the HIro wallet, about 20 were send to the same Taproot address. 

They restored the wallet from seed which yielded no change. 
Address receiving the 20 inscriptions: bc1pyas6v800xrkqavy3cle2uw9vs8hjdfgltnw7fykqq7v29ad0sesqvv84sk

**Comment by crypstronomer** [comment]
Yeah just same as everyone reporting my end. Sent ordinal an md received in Hiro generated ordinal address about an hr ago can't display I'm using the chrome extension 

https://blockchair.com/bitcoin/address/bc1psv5yjn7exqv6w8y3pjhrve0mgk5vamedwcv255mnm9yyh2kexa0ql4xgmn

Was a Hiro seed generated account, imported into xverse app, sub account created in Xverse fir bns and then also added and married up into Hiro chrome extension. 

Sent BTC fine to BTC address yesterday, still shows bns associated with the address, however the collectable refresh is forever scrolling and i think that's the issue also, previously it stopped scrolling and had option to refresh.

The address shown in Xverse to recieve ordinal is different to one showing in Hiro chrome, I was told yesterday that would be the case just adding it in for reference

**Comment by crypstronomer** [comment]
Also just noticed this under manage extensions in chrome, says a lot of errors

**Comment by crypstronomer** [comment]
![Uploading Screenshot (96).png…]()

**Comment by aviwol** [comment]
I saw parts of the code rely on ordapi.xyz, the key structure has changed (keys with " " spaces were replaced with "_") on the return of ordinals from all endpoints including `ordapi.xyz/inscription/:inscription` might be because of that?

**Comment by markmhendrickson** [comment]
Thanks everyone for the input here, especially @aviwol for spotting the issue. We've rolled out a client-side fix and have also requested a temporary roll-back to the semantic change from OrdAPI so that viewing functionality is restored faster.
