### ISSUE TITLE
Sending STX to typed/pasted address is replaced by senderAddress: Can't send STX

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3367]
This is a high priority bug we are working to fix it as soon as possible. 

**Workaround 1:** Sending to address using the "choose account" option is unaffected. 
![image](https://user-images.githubusercontent.com/33360391/223074381-90e7aef9-2c2a-4855-8146-757af8efcb0d.png)

**Workaround 2:** Install the previous version of the wallet, using load unpacked in developer mode for extensions. 
chrome://extensions
![image](https://user-images.githubusercontent.com/33360391/223075139-8a9a4645-4aec-4bed-b2fc-c72581c2e3e9.png)

https://github.com/hirosystems/stacks-wallet-web/releases/tag/v4.4.0
![image](https://user-images.githubusercontent.com/33360391/223075439-0839e185-92bb-4f3d-ae23-843eb3d9d247.png)

**Comment by kyranjamie** [comment]
Should be fixed in https://github.com/hirosystems/stacks-wallet-web/releases/tag/v4.6.0
