### ISSUE TITLE
Add API for fresh taproot address

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3372]
Allow wallet to request new addresses.

**use case**
App want to send an inscription to user. It needs address to do so. It calls method that opens up pop up for the user to accept/reject.

**Comment by markmhendrickson** [comment]
Two new APIs:

1. Next fresh taproot address
2. N taproot addresses from index 0 onwards, regardless of freshness

**Comment by markmhendrickson** [comment]
WIP includes new request method for extensibility

**Comment by mica000** [comment]
Designs: 


![Image](https://user-images.githubusercontent.com/119523541/225402842-35424b10-5771-44fd-adc8-e0dc68b6b179.png)

https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=2214%3A77180&t=Pt37FNqtzaiXfYvG-4
