### ISSUE TITLE
Sending BTC, dust error, can be improved or prevented.

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3374]
Users get this error when they do not leave BTC for the fee. If they use the full amount can we take the fee from that? I see some other wallets doing that too. 

And quick fix, can we change the error to be more specific. Tell users why it is failing and how to resolve?

![image](https://user-images.githubusercontent.com/33360391/223398991-91698ca1-90c2-440d-b186-22be122a5f1a.png)

![image](https://user-images.githubusercontent.com/33360391/223399036-06f8d63b-1971-467e-970e-dd97c9c2926b.png)

**Comment by markmhendrickson** [comment]
I believe this should be handled by https://github.com/hirosystems/stacks-wallet-web/issues/3178, specifically the case there in which the principal needs reduction?

**Comment by 314159265359879** [comment]
I am seeing an increased number of reports, users seeing this "dust" error.

**Comment by kyranjamie** [comment]
This should be handled by #3163

**Comment by fbwoolf** [comment]
So, @kyranjamie I am supposed to assign/start https://github.com/hirosystems/wallet/issues/3163 to fix this?

**Comment by kyranjamie** [comment]
@fbwoolf yes, really we just need to do some more advanced utxo filtering.
