### ISSUE TITLE
Use new Hiro API URLs

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3383]
They host their APIs on 

- https://api.testnet.hiro.so/
- https://api.hiro.so/

cc @rafaelcr

**Comment by markmhendrickson** [comment]
@rafaelcr Are the old URLs getting phased out on any given date?

**Comment by rafaelcr** [comment]
@markmhx no set date yet but we will definitely phase them out, probably by the next major release

**Comment by markmhendrickson** [comment]
https://www.hiro.so/blog/domain-migrations-for-hiro-hosted-services

**Comment by saralab** [comment]
@markmhx  @kyranjamie  We have migrated to hiro.so.

Mainnet: https://stacks-node-api.stacks.co/ (/extended & /rosetta)] to https://api.hiro.so/

Testnet: https://stacks-node-api.testnet.stacks.co/ (/extended & /rosetta) to https://api.testnet.hiro.so/

We will have auto redirects in place for stacks.co → hiro.so from now - Apr 30, after this, you will no longer be able to access stacks.co after Apr 30 and this will result in a 404.
