### ISSUE TITLE
Fix FT Metadata API for testnet

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3384]
The current metadata API is broke on testnet, and apparently there's a new one on:

https://api.testnet.hiro.so/metadata/ft/ST2TZK01NKDC89J6TA56SA47SDF7RTHYEQ42CGN7F.Wrapped-USD

Let's migrate to this URL when we query metadata

**Comment by fbwoolf** [comment]
This was quickly addressed here: https://github.com/hirosystems/wallet/pull/3439 ...but our types seem off now and there might be potential errors surfacing with `undefined` metadata. I am going to close this issue bc it was merged, but open a new one for coordinating type changes.
