### ISSUE TITLE
Support arbitrary message signing for Bitcoin

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3386]
https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki

**Comment by skyrover7** [comment]
Would be awesome to be able to verify a user holds a particular ordinal(s)

**Comment by captain-munch** [comment]
Another +1 from our side. We have an inscription gating feature that leverages BIP-322, we'd love to deeplink the signing action into your wallet. Count us in for beta testing 🙌🏻

**Comment by markmhendrickson** [comment]
![Image](https://user-images.githubusercontent.com/28991/227985957-33f2ba22-b3d6-4be7-ae5b-440f372cbdde.png)

**Comment by vnprc** [comment]
We are looking into an ordinal gated solution, but we need wallet support to justify building this feature. This would be an excellent feature.

**Comment by diegoxter** [comment]
> Would be awesome to be able to verify a user holds a particular ordinal(s)

Technically you already can. I'm not a BTC dev, my experience is mainly on EVM but if you mess around with ordinals api (like the one in ordapi or the one hiro provides) you can get the holder of a specific ordinal, provided you know the ID/sat location. I have an app that already does that.

As for the content of this issue, how would this provide any solution to the ownership problem? I'm trying to wrap my head around it but cant find the actual use for it, maybe because EVM works in a different way. Would the user sign a message declaring he/she owns said ordinal?

**Comment by pxr64** [comment]
Hey guy, is there any ETA on this?

**Comment by ward-dc** [comment]
@kyranjamie I’m adding support for the signing feature to the dev build of BitCheck. If I’m correct when requesting a user’s addresses it just returns all of the addresses. A user is not able to select via the wallet which address they wish to connect and sign with. Is this intended or subject to change?

**Comment by kyranjamie** [comment]
@brinzi It's WIP, see demo build here https://github.com/hirosystems/wallet/pull/3490 

@ward-dc as the wallet only really supports address reuse, we're only signing with the 0 address index right now, but perhaps that'll change later. What's the use case for letting a user pic a specific address index? Imagine when users have funds over many addresses, we might want to sign from multiple address indexes?

**Comment by ward-dc** [comment]
@kyranjamie in most cases, online platforms only allow users to associate one address with their account. Most wallets offer the ability to choose an address to connect with. This allows the websites to avoid implementing an additional feature to select the address for signing messages.

**Comment by captain-munch** [comment]
yeah in our case, a user would like to be able to associate all the inscriptions they hold within Hiro with us. it isnt possible for them to pick one right now.

**Comment by ward-dc** [comment]
@kyranjamie To verify ownership of the ordinals in a Hiro wallet, it will be necessary to sign using the ordinals address.

**Comment by 314159265359879** [comment]
> kyranjamie in most cases, online platforms only allow users to associate one address with their account. Most wallets offer the ability to choose an address to connect with. This allows the websites to avoid implementing an additional feature to select the address for signing messages.

Hi @ward-dc , just to clarify we only return all the taproot addresses within an account m/86'/0'/`<account>`/0/0,1,2,3

The 1,2,3 are currently a legacy thing for Hiro wallet users, right now for account 1 the m/86'/0'/0'/0/0 taproot would be the primary/normal taproot address (mostly used), but if they Inscriptions are on m/86'/0'/0'/0/1 or m/86'/0'/0'/0/2 it is still Account 1 ( m/86'/0'/0 ) signing.

Taproot addresses for Account 2 (m/86'/0'/1'... ) on Hiro would not be returned when a user is logged in with Account 1, they do have that option. Perhaps that was already clear just wanted to make sure. 

> kyranjamie To verify ownership of the ordinals in a Hiro wallet, it will be necessary to sign using the ordinals address.

Users could send an ordinal to their primary Taproot address, as a workaround, if that is needed for verification via BitCheck?

**Comment by skyrover7** [comment]
hi folks, just wanted to circle back on some of the earlier comments regarding allowing a user to check if a specific ordinal (or one of a collection of ordinals) is available in a user's wallet. Is that something that this feature supports? @fbwoolf @kyranjamie 

thanks!

**Comment by markmhendrickson** [comment]
@skyrover7 yep that should be possible.  Want to give it a try and let us know if you run into any issues?
