### ISSUE TITLE
Include Taproot address(es) in userData during authentication

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3387]
To complement the return of the Native SegWit address in the same object per https://github.com/hirosystems/stacks-wallet-web/pull/3247

Perhaps as:

```
{
  btcAddress: {
    p2tr: {
      mainnet: "bc1p8rwmsmm782e7vfae2l2ssplwemqrfa7e3qz56yhfw59tknjx75cs8vlxt2",
      testnet: "tb1pfsm8ku24w9u2aewve23dn3lk4hanc25p7dh8zhcqpfutr5ms38es3653g4"
    }
  }
}
```

**Comment by kyranjamie** [comment]
This is an alternate of https://github.com/hirosystems/stacks-wallet-web/issues/3372

**Comment by markmhendrickson** [comment]
@kyranjamie does the above schema in the description look appropriate to mirror the one for Native SegWit?
