### ISSUE TITLE
failed to broadcast transaction: unexpected token '<', "<!doctype "... is not valid json

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3388]
Users are getting this error after clicking confirm/sign transaction. Then when they try again it usually does get confirmed without issue. 

![image](https://user-images.githubusercontent.com/33360391/223846633-88fcf777-5111-401d-92a0-4b14dc67080c.png)

Console
_Failed to load resource: the server responded with a status of 502 ()_
![image](https://user-images.githubusercontent.com/33360391/223846797-9df2288c-729a-4918-b39d-e7e935e39f64.png)

**Comment by markmhendrickson** [comment]
Is this for contract executions, and have you seen this recently?

**Comment by 314159265359879** [comment]
This was not seen recently, I can reopen it if I do see it pop up again. 

I am not sure if this was only showing for contract calls or also for STX transfers.
