### ISSUE TITLE
Prevent inscription sends from Native SegWit address

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3391]
When users sent BTC from their Native SegWit address, we need to freeze / filter out UTXOs with inscriptions to prevent their delivery or payment as fees.

This is because users are inevitably depositing them there (e.g. by accident).

**Comment by markmhendrickson** [comment]
@kyranjamie this is resolved yea?

**Comment by kyranjamie** [comment]
There is logic to ensure inscriptions aren't in Native Segwit UTXOs

https://github.com/leather-wallet/extension/blob/bd6dc1a6d946727859f5b4f1b89b7d7b0b199f99/src/app/query/bitcoin/address/utxos-by-address.hooks.ts#L79-L94
