### ISSUE TITLE
Support fees payment with additional UTXOs for inscription sends

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3399]
Right now we use the "postage" of a given inscription to power its sending from Taproot addresses.

This postage is essentially the sum of all sats on the given UTXO where the inscription lives. Most UTXOs with inscriptions have a decent number of stats (e.g. 10000) but if they get sent a few times and those sats get spent, they can get reduced to a point where an insufficient number of sats remain to keep sending.

To permit more sending, we need to incorporate sats from other UTXOs (on the same address or others), though taking care not to grab sats that are themselves inscribed via ordinals.

**Comment by markmhendrickson** [comment]
To look at using UTXOs from Native SegWit address

**Comment by 314159265359879** [comment]
There is a lot of demand from our users for this. Some of our users have expressed we should only send inscriptions using UTXO's from the native segwit address. 

It would solve this issue for users.
![image](https://user-images.githubusercontent.com/33360391/227702938-d46f0ed4-8974-490d-8beb-293f4190c603.png)

**Comment by 314159265359879** [comment]
Would this enhancement also make sending inscriptions with non-zero offset reliable/possible?

**Comment by markmhendrickson** [comment]
We'll tackle non-zero offset sends with https://github.com/hirosystems/wallet/issues/3483

**Comment by Floordinals** [comment]
Hello hardworking folks! I'm seeing this error on any inscription I attempt to send:

<img width="391" alt="CleanShot 2023-04-17 at 11 27 15@2x" src="https://user-images.githubusercontent.com/131031271/232578157-08b1472a-28f5-4fde-8d2a-d3d92c50b7b1.png">

I was told that this issue (#3399) was going to resolve it, but I just want to verify because the error message is different than the one posted above ([3 weeks back](https://github.com/hirosystems/wallet/issues/3399#issuecomment-1483750037)). And if it's a different issue I'd be happy to open a new one.

Thanks!

**Comment by 314159265359879** [comment]
@Floordinals Thanks for adding it here. I believe you are right this is a little different. It looks related to https://github.com/hirosystems/wallet/issues/3484

You also mentioned that after a while the error was not displayed and you were able to send the inscription anyway. I am not quite sure how that could be explained.

**Comment by Floordinals** [comment]
> You also mentioned that after a while the error was not displayed and you were able to send the inscription anyway. I am not quite sure how that could be explained.

That's correct @314159265359879, I did literally nothing different as far as I can tell... was just attempting to import my seed into other wallets. When I gave up I simply tried one more time in Hiro and the error had disappeared.

**Comment by markmhendrickson** [comment]
@Floordinals I've seen this myself whenever the URL we try to access for verifying the UTXO details isn't available for some reason. ~Mind confirming the version of your wallet and can you inspect the network panel under the developer console by chance to see if any API throws an error in particular upon seeing this message appear?~

I see now it self-resolved. That makes sense if the URL was temporarily inaccessible.
