### ISSUE TITLE
Display Ordinals of mimetype html with icon or similar

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3411]
https://ordinals.com/inscription/2e4d40a691488f6a0d8911f8b17049362931efa2ef5c1b3a63d65eff07d744cbi0

![Image](https://user-images.githubusercontent.com/28991/224565591-77708036-8120-46c7-a8fa-5b2534cbe3e5.png)

**Comment by mica000** [comment]
Something like this?

Not sure html is the best copy in here

<img width="445" alt="Screenshot 2023-03-14 at 18 43 35" src="https://user-images.githubusercontent.com/119523541/225092429-5db45e79-5eba-4485-8291-2ff536f971a3.png">

**Comment by markmhendrickson** [comment]
Perhaps we should display the mimetype (e.g. "text/html") here instead of "Html".

And in general, when we don't show a preview (for other content types like PDFs), we could also display that value (e.g. "application/pdf")? That way the user at least gets the benefit of seeing what types of content are in their wallet, if not a preview of the actual content.

The icon could remain generic for all these, or we could try implementing an icon mapping scheme like this one with FontAwesome: https://gist.github.com/colemanw/9c9a12aae16a4bfe2678de86b661d922

See list of common types: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

**Comment by null-ish** [comment]
It would be proper to have a preview icon for every common mimetype that cannot be previewed? If you want I can use the template @mica000 provided above to create some and upload them here.

Am I correct to assume that an HTML iframe cannot be rendered in an extension? If so, can sandbox=true provide safety for previewing inscriptions within a chrome extension?

**Comment by edu-stx** [comment]
It would help to define the extent to which we support each mimetype. We could go with the following,

* Natively supported (rendered in browser): `image/*`, `text/plain`
* Placeholder icon from FontAwesome or similar: long list from one of links above
* Generic icon: all remaining

**Comment by markmhendrickson** [comment]
> If you want I can use the template @mica000 provided above to create some and upload them here.

You're able to provide come custom icons here? Could be interesting! @mica000 wdyt?

**Comment by mica000** [comment]
@null-ish Would you like to give a try with this template? https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=2198-76546&t=nSBzAatfmm6MyutK-4

Im wondering tho about the cases on which FontAwesome doesn't have an icon to support. Can we identify such cases?

**Comment by markmhendrickson** [comment]
It seems like FontAwesome provides icons for all mimetypes that are listed here: https://gist.github.com/colemanw/9c9a12aae16a4bfe2678de86b661d922

And we can default to another icon for any cases not included in that list.

**Comment by mica000** [comment]
@markmhx I think this is ready to be implemented?

**Comment by markmhendrickson** [comment]
This will be addressed by https://github.com/leather-wallet/extension/issues/4077
