### ISSUE TITLE
Add option to "Increase fees" for BTC transactions

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3416]
Support Replace-by-Fee for BTC transactions in addition to STX ones so users with long pending transactions can increase their fees and get them confirmed faster

https://twitter.com/axopoa/status/1632723523515953157

**Comment by nattaja** [comment]
replace/correct nonce in pending tx needed too (it was for stx)

**Comment by abs014000** [comment]
Please add the RBF to Hiro Wallet.  I sent an inscription out 3 days ago and it's still Unconfirmed.

**Comment by markmhendrickson** [comment]
@314159265359879 any differences you see in how we should approach RBF for BTC vs. what we already have for STX? @mica000 is going to update the designs where needed for this implementation, using the Stacks-based "Increase fee" UX as the base

**Comment by markmhendrickson** [comment]
Screenshot of current STX RBF for reference:

<img width="406" alt="Screenshot 2023-05-31 at 15 57 47" src="https://github.com/hirosystems/wallet/assets/28991/cc932a88-e630-4621-8045-64d48b102e5f">

**Comment by 314159265359879** [comment]
> @314159265359879 any differences you see in how we should approach RBF for BTC vs. what we already have for STX? @mica000 is going to update the designs where needed for this implementation, using the Stacks-based "Increase fee" UX as the base

I especially like to see a rate in sats/vByte instead of an absolute number as we see on STX. 

other than that I think we can keep them a lot alike. 

I see "balance" in the reference design that should be "available balance" right?

**Comment by mica000** [comment]
Thanks @314159265359879!

@markmhx then I think we dont need designs. We can use the same component and just replace STX to sats/vB int the Front End?
