### ISSUE TITLE
Fix vertical scroll overflow for PSBTs

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3427]
![Image](https://user-images.githubusercontent.com/28991/224945886-506eddf6-3220-4e92-8460-049b7805d987.png)

https://openordex.org/inscription?number=a51db697e257b0c6775f3a57f13cbf5b00dae2840b05be95bd201ca35f54f926i0

**Comment by mica000** [comment]
@markmhx Isn't this message the same as the one we have on the yellow notification at the top?  
<img width="514" alt="Screenshot 2023-04-06 at 14 53 02" src="https://user-images.githubusercontent.com/119523541/230384248-51f2e78a-34a6-42e5-872b-e2f1904e3b8b.png">
