### ISSUE TITLE
Improve PSBT UX

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3440]
Cleanly list inputs vs. outputs in a way similar to post conditions for Stacks transactions

**Comment by fbwoolf** [comment]
@mica000 @markmhx dropping a link here directly to code so you can see the data structure we are dealing with:
https://github.com/paulmillr/scure-btc-signer/blob/e8763d96d131008164e57be6ad9bd82ee2f2c32c/index.ts#L474

You will see a comment that the lib takes directly from the BIP tables:
https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki

**Comment by fbwoolf** [comment]
Posting images of UniSat display which is extremely minimal...

![Screen Shot 2023-03-15 at 4 01 41 PM](https://user-images.githubusercontent.com/6493321/225442227-ac0978be-9337-4731-8ae9-80c3b2dfe9ce.png)

![Screen Shot 2023-03-15 at 4 01 50 PM](https://user-images.githubusercontent.com/6493321/225442193-c3e706aa-acfb-468f-82f7-79be31a24841.png)

![Screen Shot 2023-03-15 at 4 02 56 PM](https://user-images.githubusercontent.com/6493321/225442264-78da2827-92e0-4ddc-862d-8e770d70f91e.png)

**Comment by mica000** [comment]
Designs: https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=2319-81011&t=MCTdBArIknBJlAoO-4

**Comment by markmhendrickson** [comment]
To resolve in case still an issue during the redesign: https://github.com/hirosystems/wallet/issues/3427

**Comment by mica000** [comment]
Designs were updated: https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=2348-92231&t=m6JebigCB2ZBARrZ-4


Sneak peek of what is in the link (More states have been covered in Figma)
![Image](https://user-images.githubusercontent.com/119523541/230385078-1f888ac6-667d-4ad1-bd19-ed4631b51f83.png)
