### ISSUE TITLE
New ft metadata api types broken

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#3444]
After merging: https://github.com/hirosystems/wallet/pull/3439 we need to make sure types are coordinated with the change bc some props appear to come in `undefined`.

cc @rafaelcr is this expected?

**Comment by rafaelcr** [comment]
We respond with undefined for values that we're not returned by the contract, but we could set some defaults. Can you give me some examples @fbwoolf ?

**Comment by fbwoolf** [comment]
> We respond with undefined for values that we're not returned by the contract, but we could set some defaults. Can you give me some examples @fbwoolf ?

We use the `FungibleTokenMetadata` type so our code expects `symbol` to be defined but it is coming in `undefined` and breaking in some places. Should we move away from using that imported type?

**Comment by fbwoolf** [comment]
I see what is happening I think, token metadata is coming in as not found...

![Screen Shot 2023-03-15 at 1 57 58 PM](https://user-images.githubusercontent.com/6493321/225414904-50f5bd64-2a36-4f2b-890d-06f5538e2be9.png)

**Comment by rafaelcr** [comment]
Oh ok yeah I still need to generate types for this API, opened https://github.com/hirosystems/token-metadata-api/issues/132

> I see what is happening I think, token metadata is coming in as not found...

Some tokens might have failed during metadata fetch. In that case, you'll get a `422` response with that error message

**Comment by fbwoolf** [comment]
> 
> Some tokens might have failed during metadata fetch. In that case, you'll get a `422` response with that error message

Thanks for feedback, I'll put up a patch to fix it until you have types ready. 👍

**Comment by fbwoolf** [comment]
https://github.com/hirosystems/token-metadata-api/pull/134

**Comment by rafaelcr** [comment]
@fbwoolf client library is ready to use https://www.npmjs.com/package/@hirosystems/token-metadata-api-client

**Comment by fbwoolf** [comment]
> @fbwoolf client library is ready to use https://www.npmjs.com/package/@hirosystems/token-metadata-api-client

Thanks for the quick turnaround again! Super helpful. ❤️

**Comment by fbwoolf** [comment]
@rafaelcr any thoughts on these build errors after installing the pkg? Is this on my end? I killed my env and restarted webpack, but no luck...

<img width="1049" alt="Screen Shot 2023-03-16 at 6 39 04 PM" src="https://user-images.githubusercontent.com/6493321/225778667-20dd0fb9-c524-4a58-aa88-28e14c8bb622.png">

**Comment by rafaelcr** [comment]
Sorry about that @fbwoolf I just noticed the package I published did not include several files... could you try again with version `1.0.2`?

**Comment by fbwoolf** [comment]
> Sorry about that @fbwoolf I just noticed the package I published did not include several files... could you try again with version `1.0.2`?

Yep, that worked, thanks!

**Comment by fbwoolf** [comment]
@rafaelcr should we be using `unanchored=true` on these queries?

**Comment by rafaelcr** [comment]
@fbwoolf No need, that scope does not apply for metadata

**Comment by fbwoolf** [comment]
@rafaelcr should this be working for nft metadata too? Using `getNftMetadata` ...does the client need anything besides the `basePath` in the config?

![Screen Shot 2023-03-17 at 11 36 44 AM](https://user-images.githubusercontent.com/6493321/225970219-de97fb18-a92f-481d-a4ae-16fe59e367d3.png)

**Comment by fbwoolf** [comment]
Do we still need to include the `fetchApi` with headers, etc? I don't see that in the `ConfigurationParameters`?

**Comment by rafaelcr** [comment]
@fbwoolf there's an issue with that specific contract which I'm currently fixing... see: https://api.hiro.so/metadata/v1/nft/SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.megapont-robot-component-nft/48346

**Comment by fbwoolf** [comment]
@rafaelcr not sure if best to still comm here, but the `tokenUri` on the response type is coming in `token_uri`...

![Screen Shot 2023-03-17 at 12 46 41 PM](https://user-images.githubusercontent.com/6493321/225980276-1827948d-0b0e-44d6-8fb9-adaf1236668a.png)

![Screen Shot 2023-03-17 at 12 45 33 PM](https://user-images.githubusercontent.com/6493321/225980309-9660890c-1959-4e78-a942-1560f8d19d0e.png)

**Comment by rafaelcr** [comment]
ah, sorry about that... could you open an issue in the Metadata API repo? we can continue there (while I fix this) @fbwoolf

**Comment by rafaelcr** [comment]
fixed in v1.0.3 @fbwoolf

**Comment by fbwoolf** [comment]
> fixed in v1.0.3 @fbwoolf

Thank you!
