### ISSUE TITLE
Inconsistent behaviour when switching between two local networks (subnet)

### ISSUE THREAD

**Issue by hugoclrd** [blockstack/blockstack-app#3448]
## Context

Working on an example app to interact with a subnet contract.
Users will be able to transfer STX and NFTs between a L1 (in my case, the local devnet) and a L2 (the local subnet).

<img width="409" alt="Screenshot 2023-03-16 at 14 07 55" src="https://user-images.githubusercontent.com/911307/225626349-5861cadc-d4da-48d4-951b-62a7a7c918ff.png">

### Extension Network selection

In the wallet main page, when switching between the L1 and L2 networks, the wallet inconsistently displays my L1 or L2 balance, regardless of the selected network.

**Flow**
1. from L1 (local devnet) I can see my L1  balance ✅
2. switch to L2 (local subnet)
3. still see L1 balance ✅
4. refresh, refresh, refresh, sill seeing L1 balance ❌, until eventually...
5. see L2 balance ✅ 
6. switch back to L1
7.  refresh, refresh, refresh, sill seeing L2 balance ❌, until eventually...
8. see L1 balance ✅

Note: no issue to report when switching between mainnet/testnet/devnet 👍
Note2: reproduced in Firefox and Chrome

---

### In transaction pop up

When performing a transaction, and passing the following network to `openContractCall` `const l2Network = new StacksMocknet({ url: L2_URL });`

The popup page will inconsistently show L1, L2 (and sometime I believe testnet) balances.
And show contradictory data like showing the L1 balance) with 140STX bet saying insufficient founds to transfer 1 STX. Or the transaction preview looks good but it fails to transfer (while it should, because I already transferred 10STX to the L2 and the API does return 10STX as a balance.

<img width="554" alt="Screenshot 2023-03-16 at 14 02 26" src="https://user-images.githubusercontent.com/911307/225630555-28404356-2ba6-4f0f-95be-2aa756f328f4.png">
Here it shows the tow issues: 
- displaying L1 balance in the top
- not performing the transaction because of "insufficient balance" (while L2 has 10STX)

---

I know it may be hard to debug or reproduce because it's about seeing inconsistent data (at least it's consistently inconsistent). I'm available for a call if needed

--- 

https://user-images.githubusercontent.com/911307/225629216-6087e17d-f2ee-46ef-a88b-dcc4c7d515cf.mov

## How to reproduce
Here are the step to boot a local mocknet and subnet APIs with clarinet (version 1.5 or higher - `clarinet --version`).

Create an empty project with `clarinet new proj`
In `settings/Devnet.toml`, un-comment or add: 
```toml
enable_subnet_node = true
disable_subnet_api = false
```

Start project with `clarinet integrate`
In the top right "service" section, should appear:
```
stacks-api           http://localhost:3999/doc
subnet-api           http://localhost:13999/doc
```

Then the subnet can be added to the wallet
<img width="366" alt="Screenshot 2023-03-16 at 13 58 23" src="https://user-images.githubusercontent.com/911307/225625486-07b524be-34b2-4ce2-ae61-07169edecd1b.png">

From there, the behavior described above should be reproducible (even though you can't really deposit found on the subnet)

**Comment by alter-eggo** [comment]
seems this issue was closed in this pr https://github.com/hirosystems/wallet/pull/3470

@hugocaillard could you check please using dev branch?

**Comment by hugoclrd** [comment]
Hey @alter-eggo 
Things seem way more stable in the wallet view. The balances are accurate!
In the transaction popup on the other hand, I still see calls to the testnet api

Here, I call `callContract` with `const l1Network = new StacksMocknet({ url: "http://localhost:3999" });` ✅

<img width="1487" alt="Screenshot 2023-03-21 at 18 13 23" src="https://user-images.githubusercontent.com/911307/226689758-15d22dff-e3ae-4577-b1a3-eaf9c7cae034.png">

Here, I call  `callContract` with `const 21Network = new StacksMocknet({ url: "http://localhost:13999" });` ❌

<img width="1190" alt="Screenshot 2023-03-21 at 18 15 03" src="https://user-images.githubusercontent.com/911307/226689765-6b692829-841b-4db5-8713-4b033ad9409e.png">

**Comment by hugoclrd** [comment]
Thanks @alter-eggo for your help.
- first problem regarding network selection is fully resolved on the dev branch
- the second part is my bad, it was fixed by adding, I thought the `key` was optional and how to do with network protection or smth like that, but it seems like it's actually mandatory, everything works well we a key.

👉 Maybe the `key` field could be mandatory, and we shouldn't be able to add a network without it?

<img width="397" alt="Screenshot 2023-03-23 at 20 34 36" src="https://user-images.githubusercontent.com/911307/227330378-72a72269-61b8-49b2-9f9a-ab7829afcec8.png">
