### ISSUE TITLE
Add new token metadata client/types for ft/nfts

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#3452]
In support of: https://github.com/hirosystems/wallet/issues/3444

**Comment by 314159265359879** [comment]
Where are we showing SFT's by the way? (SIP013 semi-fungible tokens)?
Or should that be specified in the metadata for SFT's somehow? 

For example ALEX tokens from the lend/borrow protocol are probably appropriately displayed in the FT section. 

Whereas SFT's for a _trading card game_ are more appropriately displayed in the collectables section?

**Comment by fbwoolf** [comment]
Good question, we are not doing a query of this new api for SFT's, @markmhx how should those be handled?
