### ISSUE TITLE
Add Collectible: Ordinal Inscription does not show (option to copy )an address

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3454]
![image](https://user-images.githubusercontent.com/33360391/226047001-25ec29c4-6eff-4b36-a823-37ac5fb806cb.png)

I saw this once before for a user who had hundreds of ordinals in a single address. Thought it had to do with a loading issue. 

https://media.discordapp.net/attachments/1075920122314756166/1086394437489414295/image.png?width=680&height=870

Tested with Wallet version 4.10.2 on Mozilla and Chrome.

**Comment by markmhendrickson** [comment]
Has this been reported since March? I'm suspecting it's stale by now

**Comment by 314159265359879** [comment]
I have not seen reports since, closing it now.
