### ISSUE TITLE
Hard coded mainnet NFT url

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3467]
Slack conversation
https://hiropbc.slack.com/archives/C041G5UV41Y/p1679342287367839
The bug is here:
https://github.com/hirosystems/wallet/blob/ab7eb4770cb114f5079306e6f7fcb855eeb5239e/src/app/query/stacks/non-fungible-tokens/non-fungible-token-metadata.query.ts#L27

**Comment by fbwoolf** [comment]
This has been fixed in my open PR here: https://github.com/hirosystems/wallet/pull/3466
