### ISSUE TITLE
Refactor: asset queries using new data models

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3472]
Right now there's a pattern where we create a big type that has balance and metadata in the same object. As they come from different sources, we set "default" values and later update them. 

See `addQueriedMetadataToInitializedStacksFungibleTokenAssetBalance`

This means we have an inaccurate data type for a period of time. We should refactor this so that data models are only ever created when the correct data is available.

**E.g. to adjust. Filter out incomplete data from API, rather than initialising it with defaults**

https://github.com/hirosystems/wallet/blob/b10ad30c9ec0c4d7e369bf7d6b56fbf5ccdc4242/src/app/query/stacks/balance/stacks-ft-balances.utils.ts#L111-L119

**Comment by fbwoolf** [comment]
@kyranjamie starting work on this, so let me know any other thots/prefs you have here atm. In adding other tokens, we've been using the data structure of:

```ts
const queriedTokenData = { ...originalBalanceInfo, ...tokenMetaDataInfo }

interface nameOfToken {
  balance: Money,
  marketData: MarketData,
  tokenData: queriedTokenData
}
```

It seems to have been pretty effective with the other tokens, but let me know your thoughts so we can get this right across all token data models. This is going to be a pretty hefty refactor I think. 🤣

**Comment by fbwoolf** [comment]
I suppose to adhere to clean code, using `tokenData` isn't great. But, then you typ get `token.token...` later, so prob going back to `asset` is better here? 🤔

**Comment by fbwoolf** [comment]
Maybe it isn't nec to combine them? I know we discussed at first whether or not to combine them into one data model ...thinking maybe we should separate them as `Balance` and `Token` models?

EDIT: Going to put up a PR refactoring following the other token implementations, then we can discuss.

**Comment by kyranjamie** [comment]
Would explore the thinking behind not combining them. Consider that, maybe in another place, we only need balance and token data, yet because the type says we need it, we have to get that data as well (or worse, mock it will dummy values).

How could a system work such that, whenever we need that data, we just look it up? If we had a helper fn/hook that returns all the data in the type you show above, that's fine, but that's different than actually making the type always conform to this structure.

Happy to chat through this further if this isn't clear.
