### ISSUE TITLE
Resolve errors from blockstream when loading hundreds of inscriptions

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3481]
Taking the issue described here and putting it in this ticket as it is still relevant:
https://github.com/hirosystems/wallet/issues/3401#issuecomment-1465316871

Some screenshots of the console:
![image](https://user-images.githubusercontent.com/33360391/227345260-4122cec5-f4a4-4662-b8b7-2eb2be852517.png)

many more 400 errors blockstream.info
![image](https://user-images.githubusercontent.com/33360391/227346061-410583be-cb07-4bd7-b7f8-a85327afaedc.png)

**Comment by 314159265359879** [comment]
Another user reporting this issue. they have 1400 ordinals in their wallet
![image](https://user-images.githubusercontent.com/33360391/230193752-f95b2a49-d6e7-467c-8bea-3df0cad41ef5.png)

**Comment by 314159265359879** [comment]
Another wallet that looks affected: https://ordinalswallet.com/address/bc1puf40tt7tdwqwgl9g6cgxvmkdr9swzhtpduqzx76m2wem5avvhdsqj7k2e3

Update 526 ordinals in the wallet, created with gamma.io, unisat and looksordinal

User mentioned not seeing any errors in the console. 
Signing out and restoring from seed did yield a different result.

**Comment by kyranjamie** [comment]
The API responds with `Too many history entries`, it seems. The same goes for mempool.space

See known issue here: https://github.com/Blockstream/esplora/issues/282

**Comment by markmhendrickson** [comment]
@kyranjamie are you looking to resolve this with client-side rate limiting or some other approach?

**Comment by kyranjamie** [comment]
I haven't gotten any further than figuring out why this happens. It isn't rate limiting; the API just simply doesn't return utxos if there are too many.

We'll need to investigate other APIs, or host our own node, to see if we can get data no matter the number of utxos.

**Comment by markmhendrickson** [comment]
Resolve display with Hiro's Ordinal API https://github.com/hirosystems/wallet/issues/3417? And split out related "Retrieve BTC" impact into its own issue.

**Comment by 314159265359879** [comment]
It looks like users who mint ordinals in bulk, BRC20 mints for example are hitting the limit. https://mempool.space/address/bc1p2ye8rd2x5x7z8dljc00ew8gs5jmaywdv2szyjrdgz6xpaqp8ulpsxzpytk

As a workaround they may want to split up mints between wallets, create an additional account for every 150 or so mints for example.

**Comment by 314159265359879** [comment]
Update from Mark:
_We discussed this one and intend to resolve with the implementation of Hiro's Ordinals API, which will resolve the dependency on blockstream entirely for displaying inscriptions. It looks like their API is near ready now._

**Comment by 314159265359879** [comment]
@markmhx could you link the relevant _Hiro Ordinal API enhancement_ here for users keeping track of this issue? They would like to get an idea of when this fix could go live.

**Comment by markmhendrickson** [comment]
https://github.com/hirosystems/wallet/issues/3417 which is now WIP with https://github.com/hirosystems/wallet/pull/3654

**Comment by alter-eggo** [comment]
prob we can close this one in favour of https://github.com/hirosystems/wallet/issues/3694?

**Comment by kyranjamie** [comment]
> prob we can close this one in favour of #3694?

This is a problem even though the inscription side of it is fixed. 

Just found that it _does_ work from BTC.com's API, though it's paginated 50 at a time: 
e.g. https://chain.api.btc.com/v3/address/bc1puf40tt7tdwqwgl9g6cgxvmkdr9swzhtpduqzx76m2wem5avvhdsqj7k2e3/unspent?pagesize=50

**Comment by kyranjamie** [comment]
@alter-eggo's latest work should've fixed this. @314159265359879 can you confirm?

**Comment by 314159265359879** [comment]
Confirmed fixed, heard from several users with hundreds of inscriptions that they are all loading now. Closing it as completed with https://github.com/hirosystems/wallet/pull/3695
