### ISSUE TITLE
Nonce issue caused by gap due to dropped and invisible transaction (in explorer/wallet), yet in the mempool

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3482]
This is the second confirmed case I have seen. Perhaps related to this https://github.com/hirosystems/explorer/issues/1003

We do not see a transaction in this list, of pending tx, with nonce 1236 (the next nonce that can be processed for this address). Yet when the user tries to send a transaction with that nonce they get the error "nonce conflict" error in the wallet. Which indicates there is a transaction with the nonce already (with a higher fee). 
This hypothesis is confirmed when the user sends a transaction with nonce 1236 and a fee of 2.00001 STX: Then the transaction is accepted by the mempool. 

I believe the transaction with nonce 1236 was not visible because it was unprocessable (because fee was higher than account balance for example). Who can retrieve the original transaction hash, it has since been RBF'ed. 

![image](https://user-images.githubusercontent.com/33360391/227483258-4672f0a9-b9eb-414b-9c76-2db9126fb633.png)

![image](https://user-images.githubusercontent.com/33360391/227493206-0786f82b-e907-4967-b3e1-b6018239745d.png)

![image](https://user-images.githubusercontent.com/33360391/227493162-fa166e8d-8ef5-4f06-8e61-d410559d022e.png)

**Comment by 314159265359879** [comment]
In this case, two users were sending transactions from different wallets which explains a lot of the nonce gaps this is not a normal case. Only focus on the problem in the topic.

**Comment by markmhendrickson** [comment]
Should we update the title to reflect this is specific to using two separate wallets concurrently to broadcast transactions? What sort of thing can the wallet do here to handle this better?

**Comment by 314159265359879** [comment]
> 

No, that is a side note, not sure if it is relevant. The topic title is what is important here. The explorer is hiding certain  transactions which makes troubleshooting a lot harder!

**Comment by markmhendrickson** [comment]
I'm a bit confused here. If both the wallet and explorer are missing the "invisible" transaction, presumably it's because the API isn't recognizing it on its end? And so the most effective fix would be on the API side for both client apps?

However, the related Explorer display issue (https://github.com/hirosystems/explorer/issues/1003) _has_ been resolved which suggests the API is providing these transactions... or is that issue actually unrelated?

**Comment by 314159265359879** [comment]
I have only confirmed this case once. Although it was after the 1003 API fix, I believe it may have been caused by a API server that was not yet fully updated. Closing this for now. 
This could help troubleshoot in case of dropped transactions: https://github.com/hirosystems/explorer/issues/1173
