### ISSUE TITLE
Customize scroll bar 

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#3488]
Let's create our own to avoid looking like this

![image](https://user-images.githubusercontent.com/119523541/227981490-c1edfc04-2083-4cb0-8aec-1b86c15eaed7.png)
![image](https://user-images.githubusercontent.com/119523541/227981524-0cb9ead7-ec12-4bf9-a630-2574127bc8e7.png)
<img width="407" alt="Screenshot 2023-03-23 at 14 57 37" src="https://user-images.githubusercontent.com/119523541/227981565-cd8f646f-82ae-43d2-a4c6-6eff9bcd076f.png">
<img width="493" alt="Screenshot 2023-03-23 at 14 57 28" src="https://user-images.githubusercontent.com/119523541/227981568-2898ad11-301d-41c7-8687-b8b961b8db23.png">

**Comment by Chakravarthy7102** [comment]
Hey Hi @markmhx  can I take this issue!, Would love to contribute!

**Comment by mica000** [comment]
@Chakravarthy7102 Do you need some design guidance?

**Comment by Chakravarthy7102** [comment]
> @Chakravarthy7102 Do you need some design guidance?

Yes! , can I customize the scroll bar according to the above design in above screenshots?

**Comment by mica000** [comment]
Oh please no :) the above screenshot is what we want to change. This is the default scroll state in the browser.


Here are the designs:
https://www.figma.com/file/9QCiWd0ft0EZTeDsP4NvDB/Scrollbar?node-id=0%3A1&t=Q72z35t5LUVVJYlA-1
<img width="1367" alt="Screenshot 2023-04-11 at 15 51 33" src="https://user-images.githubusercontent.com/119523541/231184601-b347d870-6ba6-4381-84e8-e59ab5e6f50e.png">

**Comment by mica000** [comment]
@kyranjamie 
Do you know if there is any library that you recommend for this?

**Comment by Chakravarthy7102** [comment]
> @kyranjamie Do you know if there is any library that you recommend for this?

Nope I think we don't need to use any external Lib for this we can do this in with plain CSS. :)

**Comment by kyranjamie** [comment]
@Chakravarthy7102 I would maybe break this into two tasks:

First, fixing the scrollbar on the account selection page, by making sure the scrollbars are not padded. This will likely need to be done whatever approach we take next.

<img src="https://user-images.githubusercontent.com/119523541/227981524-0cb9ead7-ec12-4bf9-a630-2574127bc8e7.png" width=259 />

Then, second, exploring options for custom scrollbars, whether it be with a library, or a custom CSS implementation. 

@mica000 maybe you can provide some guidance about how we can change the layout/remove content at narrow viewports, such that no horizontal scroll exists in the first place.

**Comment by Chakravarthy7102** [comment]
> @Chakravarthy7102 I would maybe break this into two tasks:
> 
> First, fixing the scrollbar on the account selection page, by making sure the scrollbars are not padded. This will likely need to be done whatever approach we take next.
> 
> <img alt="" width="259" src="https://user-images.githubusercontent.com/119523541/227981524-0cb9ead7-ec12-4bf9-a630-2574127bc8e7.png">
> 
> Then, second, exploring options for custom scrollbars, whether it be with a library, or a custom CSS implementation.
> 
> @mica000 maybe you can provide some guidance about how we can change the layout/remove content at narrow viewports, such that no horizontal scroll exists in the first place.

Got it!, Yup we should consider going forward without the horizontal scroll

**Comment by mica000** [comment]
I believe the scroll bar only happens on this screen because the container on which "my account" is built doesn't seem to use the full width of the drawer. 

@kyranjamie Do you know why this is built like this? I only see this happening here

**Comment by markmhendrickson** [comment]
Thanks @Chakravarthy7102 for volunteering here! 🙏

**Comment by kyranjamie** [comment]
> @kyranjamie Do you know why this is built like this? I only see this happening here

No reason. It's a bug/interface error, the scroll bars should be at the edges. Just a problem that needs being fixed.

**Comment by mica000** [comment]
@kyranjamie Should the bug be fixed in this ticket as well? Is it something simple to be fixed?

**Comment by kyranjamie** [comment]
@mica000 Yeah, it should. I suggested above that first we fix the bug, then later we investigate custom scroll bars which is a more involved task.

**Comment by pete-watters** [comment]
This issue is a duplicate of https://github.com/leather-wallet/extension/issues/4477 and https://github.com/leather-wallet/extension/issues/4549 and will be solved by https://github.com/leather-wallet/extension/issues/4371
