### ISSUE TITLE
Google Docs throws error when web wallet extension enabled

### ISSUE THREAD

**Issue by mijoco-btc** [blockstack/blockstack-app#3502]
Hiro Web Wallet v4.14.0

Chrome 111.0.5563.146 (Official Build) (x86_64)

Noticed today (30th Mar) that a google docs error toggles with the Hiro web wallet extension being enabled/disabled. 

Reproduced same behaviour in Firefox.

<img width="1342" alt="Screenshot 2023-03-30 at 19 17 39" src="https://user-images.githubusercontent.com/4384929/228928522-05e29dfd-b6e0-4e8c-af23-9b55bff8d8e4.png">

**Comment by 314159265359879** [comment]
Thanks for reporting Mike! I wonder if it has anything to do with https://explorer.stacks.co/txid/0xea659970cc61d142f2a63fc039098a84f1f51733512f760adbd98280d307ce9c?chain=mainnet

**Comment by kyranjamie** [comment]
Wonder if this was temporary? Can anyone else replicate?

<img width="975" alt="image" src="https://user-images.githubusercontent.com/1618764/229528407-c43e7e33-dc2a-451c-bb5b-8f4a9d94fbda.png">

**Comment by mijoco-btc** [comment]
I just checked and I no longer see this error in google docs in either chrome or firefox with the extension enabled.

**Comment by 314159265359879** [comment]
I see James also noticed this issue and resolved it by reinstalling the wallet. 
![image](https://user-images.githubusercontent.com/33360391/229731239-0c2514fa-f0da-47d8-8a2a-b93b836327a2.png)

**Comment by 314159265359879** [comment]
One more report, I have asked them to try the above workaround (reinstalling Hiro). 
![image](https://user-images.githubusercontent.com/33360391/229916000-42eb1777-1aab-42ef-a606-cdf606d047df.png)

**Comment by markmhendrickson** [comment]
I'm seeing some behavior that I'm not 100% sure is related to the extension but seems likely.

I tried loading a test document a bunch of times with the extension installed but disabled and it seemed to load fine all of those times:

<img width="1370" alt="Screenshot 2023-04-05 at 09 18 10" src="https://user-images.githubusercontent.com/28991/230010057-fc78fefe-4959-46aa-b3b6-a04a24cf8e13.png">

I then re-enabled the extension _and_ clicked on its icon to view the home screen once, then tried reloading the same test document a bunch more times. And a high percentage of those times I noticed that the Google Docs toolbar area was disabled / greyed out and there was a GA-related error in the console:

<img width="1363" alt="Screenshot 2023-04-05 at 09 19 09" src="https://user-images.githubusercontent.com/28991/230010313-9489e055-5d4d-46ed-94b1-d3d173129e8e.png">
<img width="1367" alt="Screenshot 2023-04-05 at 09 20 27" src="https://user-images.githubusercontent.com/28991/230010320-0b3aa195-ae86-43fb-b212-383bd05faf46.png">
    
Note that if I disabled then re-enabled the extension but *didn't* click the icon to view the home screen before reloading the Google Docs tab, I _wasn't_ able to recreate this issue. It only happened (maybe 60% of the time?) when reloading the page having viewed the home screen at least once.

Note as well that this behavior is different than the original "Unable to load file" report in this issue, so it's unclear whether I've uncovered the same issue with a different manifestation or a separate one.

**Comment by igorsyl** [comment]
I'm experiencing this too. Let me know how I can help.

**Comment by markmhendrickson** [comment]
@igorsyl any errors in particular showing up in your dev console?

**Comment by igorsyl** [comment]
[console-export-2023-4-5_15-1-36-wallet-disabled.txt](https://github.com/hirosystems/wallet/files/11162627/console-export-2023-4-5_15-1-36-wallet-disabled.txt)
[console-export-2023-4-5_15-1-36-wallet-enabled.txt](https://github.com/hirosystems/wallet/files/11162628/console-export-2023-4-5_15-1-36-wallet-enabled.txt)

Will re-install, as suggested.
