### ISSUE TITLE
Resolve insufficient low BTC fee setting for transactions as intermittent issue

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3508]
Fixed 25-30 sats per vB as floor? for default / medium level

**Comment by kyranjamie** [comment]
Because the API is unreliable and returns too low fees?

**Comment by markmhendrickson** [comment]
@hozzjss can provide more context, but it seems we currently set a low rate at times (eg 3 / vb) causing transactions to pend forever

**Comment by hozzjss** [comment]
Sorry for the late response but yes the fees are not really on a spectrum, the fees are either too high or too low, basically they become super low after a block has been confirmed and over the period before the next block is confirmed fees become super high basically pushing back the transactions with the median fee, which was 3.5 sat/vByte at the time, and that makes sense if the fees didn't fluctuate that often, the suggestion was to have a minimum fee rate @kyranjamie

**Comment by 314159265359879** [comment]
Here is an example This transaction was send with Hiro 4 hours ago at the time the average fee paid was 14-25 sats/vB. The fee set in this case was 6.74 sat/B

Perhaps based on block 784794?
![image](https://user-images.githubusercontent.com/33360391/230992429-d2d92b37-ef1d-4293-922c-1ba521f31a91.png)

These are other blocks from about 4 hours ago.
![image](https://user-images.githubusercontent.com/33360391/230992294-30f94440-db7f-470d-9a6f-ef68f223cd98.png)

Now it looks like it will be a while before it gets picked up
![image](https://user-images.githubusercontent.com/33360391/230992655-46747698-9bbe-4803-ad66-074dc09acb87.png)

A minimum fee rate could help prevent cases like this. We could consider different ones for low/medium/high even.

**Comment by 314159265359879** [comment]
One more example:
![image](https://user-images.githubusercontent.com/33360391/231090628-b8bf8221-ba57-4cbd-8cd4-bb92be992cdd.png)

https://mempool.space/tx/264e81ca740846c9b550cbc4a9523f708d401d4cf2c0f7b466a08cb3d3791fe1

**Comment by markmhendrickson** [comment]
Talking through this with @314159265359879, it seems that if the fee estimator isn't properly averaging out fees from the past few blocks and weighing current mempool conditions, then we need to figure out a fix for that directly.

If instead or addition to that issue users are getting caught by sudden spikes in competitiveness (ie others start bidding a lot more in a way not captured by the estimator), then we need to rely on providing RBF as an option for them to correct their bid.

**Comment by 314159265359879** [comment]
A user mentioned:
![image](https://user-images.githubusercontent.com/33360391/233293287-08311399-ea8e-41bb-a9be-7c0e4e48cbb4.png)

Perhaps setting the 25-30 sats/vByte minimum for "high" would be okay. For medium and low this could be 10 times the average fee and hence could be frowned upon. When a user is choosing _high_ such a minimum is likely more acceptable. and even expected, considering the comment above.

**Comment by fbwoolf** [comment]
We could switch back to using the Blockstream api for fees if mempool.spaces isn't reliable?

**Comment by markmhendrickson** [comment]
Perhaps we can try both of these and see how they perform (add a minimum for high fee option and switch to Blockstream)

**Comment by fbwoolf** [comment]
@kyranjamie you might be able to provide more insight here, I can't remem why you switched to mempool.spaces for fees over Blockstream? I know I had originally used Blockstream.

**Comment by kyranjamie** [comment]
Discussion on the call suggested that we take an average from two separate fee endpoints https://bitcoinfees.earn.com/api
