### ISSUE TITLE
Ordinal inscriptions showing twice or more and revealing (false uninscribed BTC)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3517]
Perhaps this is caused by an API issue. 

The users sees this: 
![image](https://user-images.githubusercontent.com/33360391/229938457-7830ff2e-d1c0-415d-8988-99a2df0ff89b.png)

One output shows an ordinal
https://ordinals-explorer.generative.xyz/output/870a65f88ad97abda08861122f1f4d6aa81703659edc098806cb52324e2fa086:2
The other output shows no ordinal
https://ordinals-explorer.generative.xyz/output/870a65f88ad97abda08861122f1f4d6aa81703659edc098806cb52324e2fa086:3

After unlisting some ordinals, more uninscribed UTXO's are displayed
![image](https://user-images.githubusercontent.com/33360391/229938434-8e960e18-6ed5-4297-9d21-3b0f0f3db4dc.png)

Some of the inscriptions are showing three times. 
![image](https://user-images.githubusercontent.com/33360391/229938527-a4e89496-5e76-429d-8d1e-23b62ccbc581.png)

While on another explorer this is shown for the same address: bc1pxtet4fqgm3mlw3f87322eqslmkwjkmujpsl2fps7j08gue6kd4lsyw6vjn
![image](https://user-images.githubusercontent.com/33360391/229938575-b0010a6f-f1ee-4682-a31e-fb41264d875d.png)

**Comment by 314159265359879** [comment]
Restoring the wallet from seed (and clearing cache in the process) did change what is displayed in the wallet but it is still showing a specific inscription multiple times:
![image](https://user-images.githubusercontent.com/33360391/230015719-22bb5ad3-c362-46cb-baeb-c69a6f20a23a.png)

**Comment by hozzjss** [comment]
My own wallet suffers the same issue here's my address 

bc1p3qyrwnkd2hh7u33p95ct698vqy79erznv309dr0vwgd6a7xjkllq9gda6a

What happened was that all of these ordinals were mixed in one transaction and then jammed into one utxo which i then separated manually by splitting the utxo into multiple utxos using sparrow, since then it's fine in gamma but I can't for example do anything except list them, I can't change the price for some reason, nor unlist them

**Comment by kyranjamie** [comment]
Investigating. @314159265359879 what do you mean by unlisted?

**Comment by 314159265359879** [comment]
I think the user meant invalidating prior PSBT's. 

Although with hz' input I am not so sure that had anything to do with it. These two transactions seem to have been misinterpreted (showing uninscribed sats on both outputs while :2 in both cases held/holds an inscription). 


![Image](https://user-images.githubusercontent.com/33360391/230172876-97ce7756-4e37-4d53-b27a-e69b09d413c9.png)

https://mempool.space/address/bc1pxtet4fqgm3mlw3f87322eqslmkwjkmujpsl2fps7j08gue6kd4lsyw6vjn

The user believes: _that was probably the "mint", or sale, of the inscription on https://www.twelvefrog.com/_

**Comment by 314159265359879** [comment]
To get the uninscribed sats out of the wallet the user used the following workaround:

Using sparrow wallet to freeze all the utxos that have ordinal inscriptions in them and then sending the rest out.

**Comment by kyranjamie** [comment]
@314159265359879 can you QA the changes in https://github.com/hirosystems/wallet/pull/3519 ? 

I think this might address the duplicate displaying of inscriptions (and them moving around in order), but I'm not 100% sure on the inaccurate check for non-inscribed TR utxos. While the initial check may be wrong (best guess is temp api glitch), it's built with an additional double check of all UTXOs against a HTML explorer.

https://github.com/hirosystems/wallet/blob/089001662a120fd9b03c43a86000fccf9e688bef/src/app/features/retrieve-taproot-to-native-segwit/use-generate-retrieve-taproot-funds-tx.tsx#L51-L58

So it's likely users would've been stopped from actually being able to broadcast the tx.

**Comment by kyranjamie** [comment]
Closing this for now as I believe it was an API glitch. Please reopen if you hear reports of this again @314159265359879
