### ISSUE TITLE
Ensure inscriptions of mimetype JSON have line breaks

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3533]
![image](https://user-images.githubusercontent.com/33360391/230931283-1e315caf-f88c-416a-9c58-cba9ed54fd1d.png)

Is this because there are no spaces in the json?

**Comment by 314159265359879** [comment]
Nat mentions preferring display like this:
![image](https://user-images.githubusercontent.com/33360391/230931729-5bb04551-d3a3-4a9e-b4f9-5d7d08301ffc.png)

**Comment by markmhendrickson** [comment]
I suppose if the mimetype is JSON for an inscription, we could run it through a formatter to get both line breaks and indentation?

**Comment by kyranjamie** [comment]
Can be formatted with `JSON.stringify(payload, null, 2)`
