### ISSUE TITLE
Ordinals with json/txt, showing with white background in dark mode

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3534]
Is there anything that can be done in this specific case?
![image](https://user-images.githubusercontent.com/33360391/230990708-6baeb222-6d5c-4dae-8e08-b7bd176c79c1.png)

**Comment by markmhendrickson** [comment]
Is the issue the white background in dark mode? Or the text overflow wherein much of the content isn't visible?

**Comment by 314159265359879** [comment]
> Is the issue the white background in dark mode? Or the text overflow wherein much of the content isn't visible?

The overflow issue is covered here: https://github.com/hirosystems/wallet/issues/3533

This is just about the white background in dark mode.

**Comment by markmhendrickson** [comment]
This appears resolved now

<img width="511" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/4e9a87a3-e4a9-4d81-a101-f3096fabe6fa">
