### ISSUE TITLE
Ledger enabled wallet shows password dialogue erroneously, routing problem?

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3536]
The Ledger enabled Wallet Extension doesn't have a password or lock function like the software keyed wallet does. 
This dialogue should never show up. 

To reproduce
1. Click send
2. Choose any SIP010 token 
3. Click back
4. See password page: /index.html#/unlock

https://user-images.githubusercontent.com/33360391/231156342-2082a34d-ddfc-43b0-87c0-552b9869b299.mp4

A user reported that clicking a token without metadata (2-->4) would return the password page right away see screenshot
![image](https://user-images.githubusercontent.com/33360391/231156685-90126ffb-d7e5-4168-b293-c60619b2af65.png)

**Comment by markmhendrickson** [comment]
@kyranjamie is this issue also resolved with https://github.com/hirosystems/wallet/pull/3633 ?

**Comment by kyranjamie** [comment]
I haven't tested this, but I suspect not.

**Comment by 314159265359879** [comment]
This was resolved with https://github.com/hirosystems/wallet/pull/3540

I am closing this.
