### ISSUE TITLE
Integrate DLC signing into Hiro Wallet

### ISSUE THREAD

**Issue by sosaucily** [blockstack/blockstack-app#3541]
---
### Integrate DLC signing into Hiro Wallet
In order to use DLCs, Bitcoin wallets need to import a library which can sign and manage DLC contracts.

---

A DLC primarily consists of two Bitcoin transactions, a _funding tx_ and a _Contract Execution Transaction (CET)_. The DLC library from DLC.Link provides JS interface for building and managing the DLC contracts, and doing the signatures required. See below for more information about how DLCs function and why unique code is needed for them.

#### Tasks
* Add the dlc library, and instantiate the DLC manager object with wallet internal pieces (blockchain access, btc keys, etc)
* Build DLC signing flow into the architecture. Main actions: Sign / Accept DLC, navigate to DLCs page button, view existing DLCs.
* Build UX/UI components / pages matching the existing style. Main pages: Sign DLC, DLC details, etc.

#### Additional Reading
* Additional reading about dlc-lib - https://docs.google.com/document/d/1v5E17KxZaL5rXTvbyJkm5osR5-cNhYGlVcKdSCuK4j0
* Additional reading about DLC.Link: https://www.dlc.link/blog
* Additional reading about DLCs: https://github.com/discreetlogcontracts/dlcspecs

**Comment by sosaucily** [comment]
https://xd.adobe.com/view/5e12acc7-73f0-459b-994c-daffa9cf5e7d-0b41/

<img width="1334" alt="Screenshot 2023-04-14 at 13 04 44" src="https://user-images.githubusercontent.com/365420/232027942-f9a08dde-6152-48a8-b326-dcbae0b45130.png">

**Comment by markmhendrickson** [comment]
@mica000 assigning to you for capturing the top-level guidance and reference materials we just discussed on a call and posting here 🙏

**Comment by mica000** [comment]
Here is the Figma link:
https://www.figma.com/file/BTmEMXE0YzyZCvUzaku99f/Hiro-Wallet-%2B-DLC.Link?node-id=0%3A1&t=dvxEBbw7QasR7A03-1

**Comment by Polybius93** [comment]
Hey everyone! 

Here’s the weekly update from DLC.Link on the status of the DLC into Hiro Integration. Normally this should come out every Friday, including this coming Friday.

https://github.com/hirosystems/wallet/issues/3541

Here's what’s been accomplished so far:

- Thorough Hiro Wallet code review and familiarization
- Had a productive meeting with Kyran to discuss the main parts of the repository and how the listener should work. His guidance has been valuable in understanding the requirements.
- Successfully implemented the necessary interfaces and hooks.
- Initial integration into the Redux store by extending it with a DLC-related slice, which will help manage and update DLC data.
- BTC API function updates to include a new feature that retrieves the required transaction hex.
- Beginning step of the DLC flow (accepting offer) is tested and working.

Next week we will continue to finish the DLC steps (sign, broadcast) and begin implementing the UX / UI components.

One concern from Kyran came up on the topic of handing keys to the DLC library, and whether there was another option. We will take the existing approach as a starting point and discuss it again in the next meeting.


Thanks!
Dani

**Comment by Polybius93** [comment]
Hey everyone!

Here’s the weekly update from DLC.Link on the status of the DLC into Hiro Integration. 

Here's what’s been accomplished so far:

- With the necessary interfaces, hooks, and Bitcoin address information, the whole BTC locking flow is working. The wallet is now capable of locking BTC on the blockchain. 
- A case for the BTC lock request has been added to the RPC message handler and is functioning properly.
- Created the request page UI and the BTC locking success page.

Currently, the team is working on the following tasks:
- Finalizing the Rust WebAssembly (WASM) implementation to simplify the BTC locking flow.
- Completing the UI development to ensure a polished and user-friendly experience.
- Implementing the locked BTC contracts list page to provide users with an overview of their locked BTC contracts.


Thank you for your continued support, and stay tuned for more updates!

Best regards,
Dani

**Comment by Polybius93** [comment]
Hey everyone!

Here’s the weekly update from DLC.Link on the status of the DLC into Hiro Integration. 

Here's what’s been accomplished so far:

- Continued the implementation of the Rust WebAssembly (WASM) package to simplify the BTC locking flow.
- Encountered some complications with the WASM package and spent time working on resolving them.
- Conducted a major refactoring of the codebase to take advantage of the new WASM package and simplify the overall flow.

For this week:

- Identify and resolve any remaining bugs in the Rust WebAssembly (WASM) package and conduct thorough testing to ensure its stability and reliability.
- Design and implement the DLCs list page, which will provide users with an overview of their locked BTC contracts.
- Develop the necessary functionalities for the DLCs list page, such as retrieving and displaying contract details, status, and relevant information for each contract.
- Conduct comprehensive testing of the DLCs list page to ensure its functionality and usability.

Thanks!
Dani

**Comment by Polybius93** [comment]
Greetings, everyone!

It's time for the weekly update on the DLC.Link integration progress. Let's dive into what we accomplished last week and what we have planned for the upcoming week:

Last week's achievements:

- Successfully completed the implementation of the Rust WebAssembly (WASM) package, addressing all known bugs and errors.
- Streamlined the BTC locking flow, ensuring a smooth and efficient process.
- Devoted time and effort to working on the DLC list page, making significant progress in its development.

Additionally, we would like to mention that we had some out-of-the-office time last week. We attended the Bitcoin Prague conference, which provided valuable insights and networking opportunities. Consequently, our available working hours were slightly reduced, but we managed to make notable progress nonetheless.

Looking ahead, here's what we aim to achieve this week:

- Focus on completing the DLC list page, ensuring it meets the required functionality and user interface standards.
- In light of the recent surges in gas fees, we are proactively investigating strategies to minimize the impact on dlc transactions.

We appreciate your continued support! As we progress in our efforts, we are excited to share that upon reaching significant milestones, we will be reaching out to the Development and Product teams for review meetings.

Thank you!
Dani

**Comment by Polybius93** [comment]
Hello everyone,

Here's a brief update on the DLC.Link integration progress:

Last week's achievements:

- Completed thorough testing and resolved known bugs and errors for DLC transactions.
- Enhanced success and error pages in the DLC flow to provide clearer and more informative messages for users.

Planned features for the coming weeks:

- Focus on completing the DLC list page.
- Set up cloud storage infrastructure for secure storage and retrieval of DLC-related data.
- Create and implement comprehensive test cases to ensure functionality and stability of the DLC.Link integration.
- We have attached screenshots and recorded the DLC flow to visually represent our progress and improve the user experience. Review meetings with the Development and Product teams are scheduled to gather feedback and enhance the integration.

UI slides:
https://docs.google.com/presentation/d/1yAdGGGVFVsIy8mDHxb7pwnc_WLzq3NcK3rxEPDugsEw/edit?usp=sharing

PR:
https://github.com/hirosystems/wallet/pull/3893

Thank you,
Dani
