### ISSUE TITLE
Add fees selection to Ordinal inscription send flow

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3544]
Following support for regular btc sends https://github.com/hirosystems/wallet/issues/3141

Contingent on https://github.com/hirosystems/wallet/issues/3399

**Comment by fbwoolf** [comment]
@markmhx @mica000 any designs to ref on these changes? Encountering some things I can try to resolve with error messages needing to be relocated/changed/handled differently?

We used to review the fees here and throw an error under the input...
<img width="499" alt="Screen Shot 2023-05-09 at 2 24 31 PM" src="https://github.com/hirosystems/wallet/assets/6493321/e15da48d-f625-4997-aa66-10d87e0f6b76">

But, now we move to the choose fee screen and see this when the user doesn't have enough funds...
![Screen Shot 2023-05-09 at 2 22 31 PM](https://github.com/hirosystems/wallet/assets/6493321/46e555a5-3eec-4aa5-94dc-6559e56acd0c)

Should I show the same error but move it to the choose fee modal?

**Comment by fbwoolf** [comment]
Nvm, I can just move some code around and still show in the same place before getting here ...but let me know if prefer to change.

**Comment by fbwoolf** [comment]
Extending this issue to add an integration test flow for sending inscriptions.
