### ISSUE TITLE
Place "edit nonce" option in the same place on the interface on the confirm screen and Send form

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3547]
Confirm screen
![image](https://user-images.githubusercontent.com/33360391/231989598-7263c908-49f0-4865-a441-b1ca533637e7.png)

Send form
![image](https://user-images.githubusercontent.com/33360391/231989752-c82c2806-78d7-4386-b813-830dc6e1d0ee.png)

**Comment by markmhendrickson** [comment]
Assigning @mica000 to confirm which version is correct

**Comment by mica000** [comment]
Second image, on the right above the preview button.

> Assigning @mica000 to confirm which version is correct
