### ISSUE TITLE
Add swap interface

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3553]
For users to swap between:

- BTC <-> x/sBTC
- STX <-> Stacks FTs
- Stacks FTs <-> Stacks FTs
- Lightning BTC <-> STX

Early mockup:

![image](https://user-images.githubusercontent.com/28991/234336269-b0470f67-8c75-43e8-8abe-d7338d14f1f6.png)

**Comment by markmhendrickson** [comment]
For reference re: swapping UX:

https://app.alexlab.co/
https://www.lnswap.org/
https://testnet.magic.fun/

**Comment by markmhendrickson** [comment]
SDK for integration of ALEX contracts https://github.com/alexgo-io/alex-sdk

**Comment by markmhendrickson** [comment]
@mica000 want to link the full design set here?

**Comment by mica000** [comment]
Here is link, please check the Swap UX - Option B:
On the left you have the prototype and on the right how each step should be build
https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=4706-41283&t=1TVSrWMDeEMhTqn0-4
<img width="1636" alt="Screenshot 2023-05-31 at 18 15 41" src="https://github.com/hirosystems/wallet/assets/119523541/7a7b601b-c3f7-42a4-8609-55b066dc0e3c">


https://github.com/hirosystems/wallet/assets/119523541/3358ee5c-3292-4776-b618-0149acf2f675

**Comment by markmhendrickson** [comment]
@mica000 is currently working on producing a Magic-specific version of designs with a preview of the transaction series pre-submission

**Comment by mica000** [comment]
Collaborating in this notion docs to uncover the stages for BTC -> xBTC
https://www.notion.so/trustmachines/Add-BTC-xBTC-swaps-5b8c4fddefd2484797fa95ed6d4adefc

**Comment by markmhendrickson** [comment]
Needed input to finalize designs:

- Edge cases
- Recovery cases
- Exact transactions and their attributes for listing as steps (for Magic, and preferably for sBTC as well)

**Comment by markmhendrickson** [comment]
@mica000 Mind linking the latest designs here for reference as @fbwoolf dives in to help with the base UI? 🙏

**Comment by mica000** [comment]
Yup!

[North star designs](https://www.figma.com/file/nY5UTVUoJdLQ30sk7YGQ3Y/Swap?type=design&node-id=201-17001&mode=design)

[MVP 0](https://www.figma.com/file/nY5UTVUoJdLQ30sk7YGQ3Y/Swap?type=design&node-id=759-26610&mode=design)

@fbwoolf initially we were discussing about breaking it down in two parts, hence the scope above. Nonetheless, would be good to know from your perspective the best way to implement it

**Comment by ldiego08** [comment]
@markmhx just a heads up, I'm working on the token selector shown below in a separate branch. Just to have in mind while scoping UI work. The idea was to work in smaller PRs, so this one with the base page would get merged first. LMK if you'd like to handle it differently. 🙏🏽 

<img width="295" alt="Screenshot 2023-08-04 at 07 35 52" src="https://github.com/hirosystems/wallet/assets/271803/db14ed2c-f6e4-4653-8800-44f35d06592c">

**Comment by fbwoolf** [comment]
> @markmhx just a heads up, I'm working on the token selector shown below in a separate branch. Just to have in mind while scoping UI work. The idea was to work in smaller PRs, so this one with the base page would get merged first. LMK if you'd like to handle it differently. 🙏🏽
> 
@ldiego08 do you have this work pushed up on a branch I can use? Or, better for me to start from scratch on this?

**Comment by shivaenigma** [comment]
Currently leather wallet is not supporting BTC to STX swap. This would be a very useful and popular feature :1st_place_medal: Is this being planned to implement ?

**Comment by markmhendrickson** [comment]
@shivaenigma It is indeed being planned!
