### ISSUE TITLE
Mask Secret Key display during onboarding by default

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3560]
Providing an option to reveal the value if desired, to protect from onlookers / cameras in public places

**Comment by Safvan-tsy** [comment]
Hi @markmhx @kyranjamie 
I'm interested in working on this issue. Kindly assign it to me and let me know of any additional details to be aware of. 

Thank you.
Safvan

**Comment by markmhendrickson** [comment]
Thanks @Safvan-tsy!

@mica000 are you aware of any designs in Figma that capture this functional enhancement? I seem to remember there was a design at some point in time that had an 👁️ icon in the field that would toggle masking on and off.

**Comment by Safvan-tsy** [comment]
[Screencast from 26-04-23 06:20:09 PM IST.webm](https://user-images.githubusercontent.com/90437519/234580480-af1e76b3-56bb-4e60-8486-c213c5ab9fc6.webm)

**Comment by Safvan-tsy** [comment]
Is there are any suggestions on this? @markmhx

**Comment by markmhendrickson** [comment]
Looking good! @mica000 wdyt?

**Comment by markmhendrickson** [comment]
Want to add masking here as well while you're at it?

<img width="670" alt="Screenshot 2023-04-26 at 16 59 40" src="https://user-images.githubusercontent.com/28991/234617209-c663103a-f8b6-477d-bf6d-cf569a85aa29.png">

**Comment by Safvan-tsy** [comment]
[Screencast from 27-04-23 08:22:33 AM IST.webm](https://user-images.githubusercontent.com/90437519/234747835-1c7197c3-41e1-4918-be5e-99398d70fdd8.webm)

**Comment by Safvan-tsy** [comment]
@markmhx It appears that the input values are not being properly handled. Is the user expected to either type in the entire key or paste the entire key?

**Comment by markmhendrickson** [comment]
It looks as though you may have uncovered a validation bug in which if you paste a partial value into the textarea, the form doesn't recognize it until you unfocus the textarea?

We should indeed support either typing or pasting the full or partial values, however the user wants to enter them.

**Comment by mica000** [comment]
@Safvan-tsy Fantastic job! Design wise it's all looking great Thank you for your contribution! 

And indeed, I can reproduce this bug as well. Agreeing we should support both ways

**Comment by Safvan-tsy** [comment]
Thank you for your feedback . I'm happy to contribute to the project.
