### ISSUE TITLE
New SIP010 token not selectable in send form yet displayed under balances

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3565]
Quote from Chan at ALEX:
_Hi Mark and @kyranjamie we recently deployed sUSDT (the wrapped USDT) on mainnet, but at the moment I am unable to select from the Hiro wallet to send (it does not appear on the "Choose asset", while I can see it under "Balances"). 
Would you please take a look?
The deployment address is https://explorer.alexlab.co/txid/SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.token-susdt?chain=mainnet

Also, it's not picking up sUSDT's metadata (https://cdn.alexlab.co/metadata/token-susdt.json)_

@aalksnv#6998 recently added a fix so tokens of which metadata is not loaded would still be selectable. https://github.com/hirosystems/wallet/pull/3540

The token contract was deployed two days ago, seems ample time for it to get picked up by the new indexing service https://github.com/hirosystems/token-metadata-api

Is a _metadata update notification_ required before the service picks it up?

**Comment by markmhendrickson** [comment]
@rafaelcr thoughts on whether this might be an API-related issue?

**Comment by rafaelcr** [comment]
@314159265359879 @markmhx the orphan blocks are affecting our ability to pick up new contracts (we might miss some of them), so I'm going to be refreshing this contract manually ASAP. Will let you know when it's updated.

**Comment by rafaelcr** [comment]
Actually, I checked the logs and the API did detect the contract but the metadata JSON was unreachable at the time. I've refreshed it and it works now: https://api.hiro.so/metadata/ft/SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.token-susdt

Closing this issue
