### ISSUE TITLE
showConnect from '@stacks/connect' broken with new Hiro Extension Update?

### ISSUE THREAD

**Issue by himmelhargott** [blockstack/blockstack-app#3566]
Hi, 
I am currently developing a app with backend clarinet, frontend: parcel.
At the app start, there is a button, which makes on click a walletConnect (showConnect()) and on finish moves on to the next page.
Yesterday everything was working fine, today it is possible to unlock the extension, but as I choose an account, there seems to be an infinite loop (circling sign on the right side of the account) and the window does not close anymore. no on finish? (thats for Devnet)
When I try to unlock to Main- or Testnet there is a pop-up whether i want to add a new network. That was not so before. 

Since I am no pro, there could be that its something on my side, yet walletConnect (showConnect()) is nothing i changed, nor would i want to. Yet there it gets stuck (as far as i can see).

Would really much appreciate if someone could check and give me a feedback or workaround. 

Many thanks in advance! 
Stefan

Btw: I implemented walletConnect (showConnect()) as described here https://github.com/hirosystems/connect/tree/main/packages/connect

**Comment by himmelhargott** [comment]
Works again. Dont know why. If anyone fixed anything, thanks a lot! =)

**Comment by markmhendrickson** [comment]
Probably related to this: https://github.com/hirosystems/wallet/issues/3564#issuecomment-1513251124
