### ISSUE TITLE
Improve balances UX

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3569]
With this enhancement https://github.com/hirosystems/wallet/pull/3525

Users can see the error in the image below (insufficient balance...):
When they have 350 STX in their wallet, and a pending transaction that will use 150 STX (100 STX transfer and 50 STX fee). There is only 200 STX available. 

Showing two different values will lead to questions. Lets answer the likely question (A) or prevent the questions (B)?
A. By explaining the difference between available balance (shown on error) and the balance shown in the lower right corner.
I.e "Available balance takes into account pending transfers of STX and pending fees"
B. Or by showing available balance instead?
(...and other transactions with postconditions that suggest outgoing STX - https://github.com/hirosystems/wallet/issues/3568).

![image](https://user-images.githubusercontent.com/33360391/233029722-75ee7570-6954-4f89-bc3f-36e18295ab63.png)

Because of a pending transaction like this (100 STX going out, and 50 STX fee)
![image](https://user-images.githubusercontent.com/33360391/233027324-a5dc97fc-2c3c-4889-a587-2fba3f0d6076.png)

**Comment by markmhendrickson** [comment]
@mica000 It seems most intuitive we just show available balance throughout the wallet?

**Comment by markmhendrickson** [comment]
We've started a document to better define the various balance types here: https://www.notion.so/Balances-UX-905c93b633b84e05a1428c1a9087ab82

Related design exploration: https://www.figma.com/file/aIhESuca3xWkJ7efpaivbV/Balances?node-id=0-1&t=hPcsHgJuzC0wTsea-0
