### ISSUE TITLE
Use fixed overlay only when content needs to be fixed

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3570]
Using the send form in full screen mode, I have scroll bars, which aren't necessary because the content fits in the page. 

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1618764/233039018-5b9b97a9-080f-4806-8098-8c8bfa9d6f9e.png">

Our implementation should only use the fixed bar & scroll when it's needed (or at least likely needed), such as when it's in popup mode

cc/ @fbwoolf @mica000

**Comment by fbwoolf** [comment]
~~@kyranjamie this one here too appears to be included in a commit being released?~~ Nvm, doesn't look like your commit.

**Comment by fbwoolf** [comment]
Closing bc appears to be in a commit fix.
