### ISSUE TITLE
Fix link to BTC activities on mainnet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3573]
From a user:
_When I click on a Bitcoin transaction in my wallet's activity tab, it takes me to a [mempool.space](http://mempool.space/) page that doesn't load but redirects to the home page. For example,

https://mempool.space/**mainnettx**/01fd3e86c628d9d550fbada064b42cdd385bc7f43cf4e8391ec649b730c943c6
redirects to
https://mempool.space/

Perhaps the transaction should parse differently to the URL https://mempool.space/tx/01fd3e86c628d9d550fbada064b42cdd385bc7f43cf4e8391ec649b730c943c6_

Wallet in testnet mode does direct correctly to this for example:
https://mempool.space/testnet/tx/8ded6bf454d7aa72b8e578a1eb7b5230e91607df8969a0653829a395be1dce38

**Comment by kyranjamie** [comment]
Think this is fixed in the latest release already

**Comment by 314159265359879** [comment]
Confirmed fixed in 4.17.0, closing this.
