### ISSUE TITLE
Retrieve button from Taproot address broken

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3575]
A user reported:
![image](https://user-images.githubusercontent.com/33360391/233188934-ad77a602-b3ae-414f-a0a2-4c45df58713e.png)

I tested on Firefox and see the same issue. When I click the button I see the following error in the console:
![image](https://user-images.githubusercontent.com/33360391/233189012-7bd4868e-ab66-4c43-a709-9be1eead904a.png)

I am certain this UTXO doesn't have an inscription. 
https://ordinals-explorer.generative.xyz/output/5fd0e7af789e33a010e8687ec56a5a5c443609c7f12e975f2cbf526fe8c09e30:0

**Comment by 314159265359879** [comment]
Two more users reporting this today.

**Comment by markmhendrickson** [comment]
Verify that the UTXO checker upon submit is returning true positives only, and add simple alert or similar with error if reached so user sees info
