### ISSUE TITLE
Display sat/vB on choose fee screen

### ISSUE THREAD

**Issue by BTCAlchemist** [blockstack/blockstack-app#3576]
When I send BTC, the 'standard' and 'high' transaction fees are the same (screenshot below), even though mempool.space shows them as different (second screenshot below). Two times today when I submitted a transaction at a standard rate, it was slower than I anticipated.

It would also be helpful to see the fee rate in sat/vB on the 'Choose fee' screen.

Could these be updated accordingly?

<img width="424" alt="image" src="https://user-images.githubusercontent.com/56145569/233231396-7f0e013a-2868-45e5-8509-45c678185245.png">

<img width="505" alt="image" src="https://user-images.githubusercontent.com/56145569/233231438-6d1b97ba-8e30-4c28-b34e-d9ce7efd5ea7.png">

**Comment by markmhendrickson** [comment]
@BTCAlchemist Thanks for the report. Are you seeing this issue consistently whenever you send or only occasionally?

And where's the mempool.space screenshot from exactly? The transaction's page post-broadcast or elsewhere?

**Comment by BTCAlchemist** [comment]
@markmhx Thanks for the reply. I just tried again but the issue did not reproduce. I could reply if it happens again. The mempool.space screenshot was from the home page that displays live fee rates, https://mempool.space/.

Would it be possible to display the fee rate in sat/vB on the 'Choose fee' screen?

**Comment by markmhendrickson** [comment]
> Would it be possible to display the fee rate in sat/vB on the 'Choose fee' screen?

Good idea! I'll modify this issue to address this enhancement specifically

**Comment by BTCAlchemist** [comment]
@markmhx The issue reproduced. Here are two screenshots:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/56145569/235331285-fc667912-1496-4bf1-8232-5d76fe36e33a.png">


<img width="1511" alt="image" src="https://user-images.githubusercontent.com/56145569/235331279-c4e34994-9dfc-4cd0-bcc9-40d10a07dbca.png">

**Comment by markmhendrickson** [comment]
@BTCAlchemist Thanks for the follow-up. We're going to start averaging the fee values recommended by two separate APIs to help even out issues with any particular provider (e.g. the high and medium values being the same): https://github.com/hirosystems/wallet/pull/3610

**Comment by markmhendrickson** [comment]
@fbwoolf let's improvise a v1 design here while @mica000 is out by placing the rate by the time estimate for each option? eg `~30 min • 13 sat/vb`

**Comment by fbwoolf** [comment]
> @fbwoolf let's improvise a v1 design here while @mica000 is out by placing the rate by the time estimate for each option? eg `~30 min • 13 sat/vb`

I can add this change to the send max changes I'm working on now with fees.

**Comment by mica000** [comment]
@markmhx @fbwoolf 
Designs for these feature can be found here: 
https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=4655-106139&t=uUQ9MklaRSHARuta-4
