### ISSUE TITLE
Binance sending transactions with all kinds of nonces

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3584]
I am not sure what tooling/wallet they are using. Hoping to get in contact. A user send this transactions which has been pending for 18 hours. This transaction with nonce 23118:
0x412410fd1d1d61ba07f58d214c4c06d0b3492340020780668ec98cb696f929e8

I see there is a nonce gap (23117) which explains why it is not getting processed. What I do not understand is why there are many more of these gaps. In addition some nonces are way off in the hundreds range instead of 23k range. Gaps (in green in the screenshot) commonly occur when transactions get dropped after maturity (256 blocks) that is not the case here. I do not know of the wallet simply skipping nonces. It does not make sense. 

Is this the problem (hidden transactions): https://github.com/hirosystems/wallet/issues/3482
Who can analyse the mempool and see if there are indeed transactions pending but not showing on the explorer?
https://explorer.hiro.so/address/SP34EBMKMRR6SXX65GRKJ1FHEXV7AGHJ2D8ASQ5M3?chain=mainnet

Much lower nonces could be caused by some confusion about which account to check the nonce for. Disconnect between active account and signing account? Something like this: https://github.com/hirosystems/wallet/issues/3390 

![image](https://user-images.githubusercontent.com/33360391/233622630-7519258b-03a6-462d-9f94-996fc62f3405.png)

**Comment by markmhendrickson** [comment]
@cuevasm mentioned he believes Binance is using their own wallet, not Hiro Wallet?

**Comment by kyranjamie** [comment]
+1, I'd be very surprised if they're using our wallet. Their systems are automated.

**Comment by kyranjamie** [comment]
Not an issue, closing
