### ISSUE TITLE
Add custom fee rate option for BTC and inscription sends

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3597]
So users can set their own custom sat/vbyte rate in addition to selecting from the 3 options of high, medium and low

**Comment by 314159265359879** [comment]
The interface could look something like this?
Show total fee in real time based on the position of the slider and sat/vByte value selected?

![image](https://user-images.githubusercontent.com/33360391/236065453-59646526-5ecd-4af2-8224-e791b53cdb14.png)

**Comment by markmhendrickson** [comment]
@fbwoolf  This is quite urgent and @mica000 has designed this already for the most part for the swapping flow, which I imagine we can safely adapt to the regular BTC and inscription send forms, taking the same two-tabbed approach: https://www.figma.com/file/3wsB9MwbKAI4CBL8Dt3x8V/Max-fee?type=design&node-id=49%3A7259&t=lvnzhX73J4qneRKW-1

**Comment by fbwoolf** [comment]
Ok, yep, still trying to work on some of the refactors requested for the send max flow with fees > then was going to do this next. I wasn't able to make as much progress on the send max changes last week as I wanted bc of issues hit branched off the V3 changes. I do have a branch in-progress thou to finish up this week I hope.

cc @markmhx

**Comment by mica000** [comment]
Indeed!

Latest designs can be found in the design system file already: https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=4655-110518&t=uUQ9MklaRSHARuta-4

**Comment by fbwoolf** [comment]
@mica000 @markmhx have this in-progress, I left some design questions in Figma when you get a chance...

![Screen Shot 2023-06-01 at 2 11 04 PM](https://github.com/hirosystems/wallet/assets/6493321/01f8d326-deb4-48dc-8281-f7b49eb5d979)

**Comment by 314159265359879** [comment]
Want to give users an idea of what will get processed slowly or fast here or do we expect users to switch back to standard to get an idea?

We are using the mempool.space api right? can we show the average fee in sats/vByte for the last five blocks for example? It can help users set good targets here. 

![image](https://github.com/hirosystems/wallet/assets/33360391/50c1d0af-875a-4c64-9207-45ff4a13c968)

**Comment by markmhendrickson** [comment]
@alter-eggo It'd be great if you could take over this work while Fara is out for the week. Want to take a look at the code and see if it's clear how you'd pick it up?

**Comment by alter-eggo** [comment]
@markmhx yeah, I'll take a look

**Comment by markmhendrickson** [comment]
@alter-eggo to determine whether to release with BTC and inscriptions simultaneously or split into two issues
