### ISSUE TITLE
Include walletProvider property to UserSession object

### ISSUE THREAD

**Issue by bilalanees98** [blockstack/blockstack-app#3603]
I am unable to find a way to identify which wallet the user is currently signed in with by looking at the `UserSession` object stored in local storage of the browser. 

Is there a way to figure out if Hiro wallet was used to to sign in? Or can an additional piece of metadata be placed in the `UserSession` object for this differentiation.
I know of the `window.HiroWalletProvider` but that is only an indication of whether the extension is installed with the browser or not.

Context: 
- Using the `@stacks/connect` library's `showConnect()` function to log in to whatever wallet the user has installed.
- `UserSession` object is created by the `@stacks/connect` library.

**Comment by markmhendrickson** [comment]
cc @kyranjamie

**Comment by kyranjamie** [comment]
Maybe we can add some metadata to the payload response? `hiroWallet: true` or `walletProvider: 'hiro-wallet'`?

**Comment by markmhendrickson** [comment]
`walletProvider` seems like an extensible solution that wallets can include optionally. I'll change this issue's title to reflect it
