### ISSUE TITLE
Can't delete inactive networks

### ISSUE THREAD

**Issue by hugoclrd** [blockstack/blockstack-app#3608]
Thanks for adding the delete button in the networks list.

It doesn't work for inactive networks, like a local networks not running or any networks that would have stopped after it was added
<img width="391" alt="Screenshot 2023-04-27 at 15 09 44" src="https://user-images.githubusercontent.com/911307/234871728-3f542d30-66b0-4741-8203-d7011f9c0369.png">

**Comment by alter-eggo** [comment]
@hugocaillard I wonder if it's actual. I created network and managed to delete it inactive  🤔

**Comment by hugoclrd** [comment]
@alter-eggo Not working on my end.
No error in the console. The button simply does nothing

Wallet v4.22.0  - Firefox 113.0 (64-bit)
