### ISSUE TITLE
Ordinals activity - make icon more distinct between "regular bitcoin" transaction and "ordinal inscription"

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3617]
![image](https://user-images.githubusercontent.com/33360391/235327073-4d2827ab-def5-4f6d-807e-8dbfc156db50.png)

I am not sure if this is possible, but something like this perhaps?

![image](https://user-images.githubusercontent.com/33360391/235327382-8fd20ff9-3c38-4bd0-af30-330afb0e4cad.png)

**Comment by markmhendrickson** [comment]
Currently we don't show Ordinal transfers from Taproot addresses in the activity, though intend to add them here: https://github.com/hirosystems/wallet/issues/3249

So I'm not sure what kind of special treatment we'd be applying here in lieu of showing them (and their particular asset) with the above issue?

**Comment by 314159265359879** [comment]
> Currently we don't show Ordinal transfers from Taproot addresses in the activity, though intend to add them here: #3249
> 
> So I'm not sure what kind of special treatment we'd be applying here in lieu of showing them (and their particular asset) with the above issue?

@markmhx Ah I see this is the type of (Ordinal) transaction that is being shown. An ordinal transfer using native segwit balance for the transfer fee. I mistook it for 3249 merged. It is using two script types but I think the user would see this as "ordinal related". 
https://mempool.space/tx/a99b805c2e0dcacbd36ce64b93ea5180958b40cc219dc9059db8ab0b2f1c7d77
