### ISSUE TITLE
UTXO with multiple inscriptions error shows when only one inscribed sat is present - API issue?

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3618]
This error is expected when an output has multiple inscriptions https://github.com/hirosystems/wallet/issues/3484. In this case users are getting the error when that is not the case and it prevents sending. Four users reported this today and I see it myself on an UTXO that I know to have only one inscribed sat. 

I do not see signs of an inaccessible API in the console although that does look like it could be the cause. 

![image](https://user-images.githubusercontent.com/33360391/235371923-41d3f0f9-5deb-4202-88e5-bb1819a07a3d.png)

**Comment by buxor** [comment]
Having the same issue. There is certainly enough bitcoin in the wallet. Also each inscription was sent separately to hiro so they all cannot be on the same UTXO.
![asdf](https://user-images.githubusercontent.com/127578991/235389453-2b80228d-0821-4e13-a143-b70ece2a2d3f.png)

**Comment by ghost** [comment]
Same issue. It worked the first time we inscribed + sent an ordinal. But then it failed the next 10 times.

**Comment by ghost** [comment]
We did a hacky fix like this.

Before:
`if (numInscriptionsOnUtxo !== 1) {
     setShowError('Sending inscription from utxo with multiple inscriptions is unsupported');
     return;
 }`

After
`if (numInscriptionsOnUtxo > 1) {
     setShowError('Sending inscription from utxo with multiple inscriptions is unsupported');
     return;
 }`

**Comment by markmhendrickson** [comment]
https://github.com/hirosystems/wallet/pull/3621#issuecomment-1529568053
