### ISSUE TITLE
Errors of unknown function argument while arguments look good

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3620]
Copy from Discord https://discord.com/channels/621759717756370964/745197302255321108/1102412500076601376

_Hey guys, this is Sidney from ALEX team. 
We are currently facing error while our swap and seems like bug is coming from the wallet, saying Bad Function Argument. 

from https://api.hiro.so/v2/transactions, which is set in hiro wallet

Detailed error log is as below;

"TypeError(TraitReferenceType(TraitIdentifier { name: ClarityName("sip-010-trait"), contract_identifier: QualifiedContractIdentifier { issuer: StandardPrincipalData(SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9), name: ContractName("trait-sip-010") } }), PrincipalType)"

{"error":"transaction rejected","reason":"BadFunctionArgument","reason_data":{"message":"TypeError(TraitReferenceType(TraitIdentifier { name: ClarityName("sip-010-trait"), contract_identifier: QualifiedContractIdentifier { issuer: StandardPrincipalData(SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9), name: ContractName("trait-sip-010") } }), PrincipalType)"},"txid":"9996c622756de3a0302c42c895cf5def9a106c841536ab199dc1ac8a722cf2a1"}

Do you guys mind checking please?_

![image](https://user-images.githubusercontent.com/33360391/235427521-de2c71db-8b38-4616-a615-92b5760ff7ef.png)

Similar reports from Gamma.io users https://discord.com/channels/621759717756370964/625538774230892545/1102283947183976468
![image](https://user-images.githubusercontent.com/33360391/235427630-429c6847-361e-4e1b-9bee-8a1917e2f75e.png)

**Comment by 314159265359879** [comment]
Friedger's comment:
_When submitting the tx to the node (post to api.hiro.so/transaction), the node rejects the tx_

A user sharing the wallet confirm screen and arguments:
![image](https://user-images.githubusercontent.com/33360391/235427868-a50e1495-e381-44ba-a8df-55f8c8cff4dc.png)

**Comment by markmhendrickson** [comment]
This seems like a node issue as reported here https://github.com/stacks-network/stacks-blockchain/issues/3690
