### ISSUE TITLE
Display BRC-20 balances in collectibles

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3629]
In addition to customizing the display of BRC-20 inscriptions in collectibles with https://github.com/hirosystems/wallet/issues/3628, we could add a new unit type under the collectibles area that summarizes the user's "Balance" of a particular token while keeping them out of the regular FTs balances area since they're highly experimental.

We would need an API that provides us with such a balance given a particular address and ticker pair. We'd also want to show the sub-balance that's transferrable due to transfer inscriptions.

The unit's design could show special "BRC-20" and "Balance" labels, emphasizing the ticker and amount held by the account.

https://domo-2.gitbook.io/brc-20-experiment/

**Comment by fbwoolf** [comment]
Api called here: https://github.com/unisat-wallet/extension/blob/abf8d32fa8adf346e363c66680a786b681d8dfe8/src/background/controller/wallet.ts#L984

 Method called: https://github.com/unisat-wallet/extension/blob/ae2df6d929c843092b5a8679ac3c270839b96351/src/background/service/openapi.ts#L245

Api url paths: https://github.com/unisat-wallet/extension/blob/20a055f7ee3d8834c7333f10f0d6e6535174b03d/src/shared/constant/index.ts#L230

Test results: https://unisat.io/api/v3/brc20/tokens?address=bc1p0wygrrqhpxutra758s34567am965gc3wwdlzhuxcwwm6t8xkvgrsgrax2w&cursor=1&size=1

**Comment by mica000** [comment]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=3032-154284&t=6y4r2pxg0BDTAn8o-4

![Image](https://user-images.githubusercontent.com/119523541/236269048-32a8b6dd-c250-4e70-85c1-ce19aac2d84f.png)
