### ISSUE TITLE
Apply highest of two fee estimates, not average, for BTC transfers

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3639]
The average fees have gone from 60 to 150 sats/vByte in half a day which can require about 20k sats for a normal BTC transfer. 

It is not clear what the reserve is based on at which point the "insufficient funds" error appears currently I assumed the current minimum fee but it looks higher, perhaps it is rounded up? It looks like this is causing more of an issue now with the current network fees, because the amount is significant. 

![image](https://user-images.githubusercontent.com/33360391/235775433-c76155c2-3178-4db9-9671-d7569e11727b.png)

In the example transfer I tested I have a balance of 0.0008 BTC sending more then 0.0006 will give the insufficient balance error. While the fees displayed low/high/medium are like this:
![image](https://user-images.githubusercontent.com/33360391/235780089-ef0c67d2-c1bf-401d-bb43-9772529d9baf.png)

And result in leaving over 10k sats in the wallet and sending with 62 sats per vByte. rather than >131 which was the required minimum for the next block. 
![image](https://user-images.githubusercontent.com/33360391/235780272-0973c080-18ba-4c47-a337-4dfe8b26477e.png)

![image](https://user-images.githubusercontent.com/33360391/235781491-0ee8991e-d72d-432c-a641-d809c6a151c6.png)

**Comment by 314159265359879** [comment]
We introduced averaging fees from two API's recently https://github.com/hirosystems/wallet/pull/3626

Perhaps for the high fee instead of averaging using the high estimate, we pick the highest of the estimates instead then add some percentage on top even?

Prioritizing this enhancement could alleviate issues with suddenly increasing network fees https://github.com/hirosystems/wallet/issues/3416

Fara's analysis:
_It does look like in both places (at max send and at select fee) we use const fee = Math.ceil(sizeInfo.txVBytes * feeRate); and the feeRate is fastestFee_
![image](https://user-images.githubusercontent.com/33360391/235792217-4234e5b8-25d8-489f-a04a-4b737dae7c75.png)

**Comment by markmhendrickson** [comment]
> Perhaps for the high fee instead of averaging using the high estimate, we pick the highest of the estimates instead then add some percentage on top even?

Yep good idea
