### ISSUE TITLE
Add custom fee rate option for Ordinal inscription sends

### ISSUE THREAD

**Issue by BTCAlchemist** [blockstack/blockstack-app#3655]
When the user sends an ordinal from Hiro wallet to another address, the fee displayed is static and cannot be changed, with an estimated confirmation time of 1 hour+. The user cannot specify the fee rate, so the transfer would likely get stuck in the mempool (especially with recent high fee rates). This happens in both the extension drop-down view and in the full tab expanded view. I am concerned about attempting any ordinal sends this since I don't want the transactions to get stuck. Could you add a way to specify the fee rate for sending ordinals?
![image](https://user-images.githubusercontent.com/56145569/236401208-6198dd35-d96c-43f3-8f97-ccf4de394c48.png)

**Comment by markmhendrickson** [comment]
Related: https://github.com/hirosystems/wallet/issues/3597 and https://github.com/hirosystems/wallet/issues/3544

**Comment by Valuebai** [comment]
+1, please fix this

**Comment by markmhendrickson** [comment]
@mica000 I'd presume the same UX solution for https://github.com/hirosystems/wallet/issues/3597 could be applied here as well, assuming the custom fee rate option is an addition to the standardized fees screen for both BTC and inscription send flows

**Comment by markmhendrickson** [comment]
I've consolidated into https://github.com/hirosystems/wallet/issues/3597

cc @alter-eggo @mica000
