### ISSUE TITLE
BTC fee rate set lower then expected - caching issue?

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3657]
This happens sometimes for both BTC transfers and Ordinal sends and played a role in what was described here: https://github.com/hirosystems/wallet/issues/3639 the [fix](https://github.com/hirosystems/wallet/pull/3642) for that does not solve this issue. 

Fee selection options are lower than one would expect based on current activities. In the case of Ordinals sends no fee-options are available (yet) but a similar issue can occur. 
In a recent case fees were set to ~15 sat/vB while the fees at the time were nowhere near that: closer to 100 sats/vByte. 

I noticed this once myself after having signed out and signed in again, there was no difference but reinstalling the wallet resulted in the fee selection page showing the correct fee options (based on mempool averages of that moment). Could this be a caching issue? I thought we cleared that on sign out already. 

Fara already did some digging and found:
![image](https://user-images.githubusercontent.com/33360391/236681210-4157bd7c-99e2-4439-badd-0cd8a45609a8.png)

![image](https://user-images.githubusercontent.com/33360391/236681232-d41b8d84-9b99-451a-a6e3-5fa1c8573f44.png)

This does not always occur, and I have not been able to reliably reproduce. If the cause/solution can't be pinpointed perhaps these enhancements can get priority instead to make it easier for users to deal with a situation like this: 
- Increase fee (RBF): https://github.com/hirosystems/wallet/issues/3416
- Set custom fee: https://github.com/hirosystems/wallet/issues/3597  (especially helpful when RBF-ing) 
- Set custom fee when sending Ordinals: https://github.com/hirosystems/wallet/issues/3655

**Comment by fbwoolf** [comment]
@314159265359879 are you still seeing this reported. The issue seems quite old. We've done work on fees recently, and are about to release custom fees. The query options are set to:

```ts
staleTime: 1000 * 60,
refetchOnWindowFocus: false,
refetchOnMount: false,
```

@kyranjamie I know you've made some changes to fees recently, do you think this issue might be outdated?

**Comment by 314159265359879** [comment]
@fbwoolf I saw a case last week when there was a sudden (~day long) spike in bitcoin activity. I was unable to determine what version of the wallet they were using but assume a recent one. It is possible we have seen less cases because it is mostly fixed by the changes or because the fee market has been less erratic/volatile. 

I think it is safe to close this when RBF is live because then there is a clear/accepted workaround anyway.

**Comment by markmhendrickson** [comment]
Let's place this in the backlog for now then and return to it for prioritization post-RBF if it's still relevant.

https://github.com/hirosystems/wallet/issues/3416

**Comment by kyranjamie** [comment]
Let's see if it's fixed in above PR, potentially we weren't fetching often enough
