### ISSUE TITLE
Bitcoin wallet shows "insufficient balance" even when enough is left to cover fees

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3661]
![image](https://user-images.githubusercontent.com/33360391/236776766-670aece1-639e-4826-a705-636519ec86f0.png)

This is preventing users sending BTC transactions.

**Comment by 314159265359879** [comment]
Comment from a user that noticed the insufficient funds issue became more of an issue with the update that added BRC20. I am not sure if that is relevant but I thought I should add it. Not even allowing small amounts when there is sufficient balance. 

![image](https://github.com/hirosystems/wallet/assets/33360391/604f4a05-85da-4b1a-80d7-f381906f3dad)

Additionally I see reports from users with insufficient balance (users surprised by the high fees on bitcoin); I think it has more to do with the ultra high gas fees we've seen on Bitcoin since that update went live. 200-500 sats/vByte. At this moment They are between 66-215 sats (last 5 blocks) Finally coming down a bit.

**Comment by 314159265359879** [comment]
This issue is still popping up. I know we are redesigning this logic with the new fee selection modal. 

![image](https://github.com/hirosystems/wallet/assets/33360391/06e19d74-8871-4652-82d2-8223410ff38c)

This user has been reporting an insufficient balance issue since the BRC-20 upgrade was rolled out. They also had a success shortly after 24.2.0 launched and then the same issue appeared again. The only thing that strikes me about this wallet is that it has a lot of history.  I wonder if the constructed transactions are more expensive because of that. Perhaps there many small UTXO's?

bc1q0wmx06n9ffg9xnauv55glr9wyycj3vnjgtt5w9

**Comment by fbwoolf** [comment]
@314159265359879 what are you proposing we do here when you reopen it? We are using the lowest fee now to determine whether we should show this error. It is hard to understand just with a screenshot if the user can really afford the amount they are trying to send plus the lowest fee being calculated at the time. Besides implementing custom fees, what do you propose here?

**Comment by 314159265359879** [comment]
@fbwoolf thanks for the question and added detail. First of all I wanted to make sure the user knows we are still working on a long-term solution for this. It may not prevent this from happening but is likely to make the reason more apparent. Lets link to the relevant enhancements you and Michelly are working on, I believe these are (feel free to add additions in the comments below): https://github.com/hirosystems/wallet/issues/3136, #3655 #3597 https://github.com/hirosystems/wallet/issues/3576. 

Secondly I wanted to check what could be causing this. My assumption is that the amount of inputs could play a role even if the average total fees on the network is low. Specific transactions with a lot of inputs can be rather expensive, right?

When I opened this issue I was not sure how general these reports would be but it looks contained to addresses with less then 10 m BTC available usually 1-3 mBTC (0.001-0.003 BTC). Or perhaps when they lack one big UTXO to pay with. 

The suggested workaround for now will be to add additional funds to the address to avoid hitting this limit.
