### ISSUE TITLE
Sending 0 BTC should result in "enter an amount of BTC" instead of "insufficient balance"

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3662]
If you type 0 BTC to send, this is shown:
![image](https://user-images.githubusercontent.com/33360391/236787603-536c9d6e-06f4-4532-a0bb-0c1fd70eb519.png)

Rather show the same message as when nothing has been entered yet:
![image](https://user-images.githubusercontent.com/33360391/236787722-b3d620ed-863c-492d-b7ee-c01925557456.png)

**Comment by souravghosh01** [comment]
@314159265359879 are you working on this issue?

**Comment by KalebArmbrust** [comment]
@314159265359879 Hello, is this open source? And if so, could I give it a go?

**Comment by markmhendrickson** [comment]
@KalebArmbrust It is, and please do!

**Comment by KalebArmbrust** [comment]
@markmhx It looks like this issue was resolved is that true?

**Comment by markmhendrickson** [comment]
@KalebArmbrust it's resolved now and is now awaiting release, which should be imminent

**Comment by fbwoolf** [comment]
This was released earlier today: https://github.com/hirosystems/wallet/pull/3679
