### ISSUE TITLE
Support all address types for inscription send recipients

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3670]
Currently the user gets an error when sending an ordinal to a legacy bitcoin address. See below. This is good to have because it is safer for users to send to Taproot addresses which are commonly used for inscriptions (although not exclusively). 

1. We could allow users to send transfer inscriptions for BRC formatted like this `{ "p": "brc-20", "op": "transfer", "tick": "ordi", "amt": "500" }`
to any bitcoin address, to support future exchanges adapting such a scheme. 
2. We could offer a flow to send BRC20 tokens (further integration) inscribing a transfer inscription for the token and amount and then transferring that to any type of Bitcoin address (legacy, wrapped segwit, native segwit or taproot).

![image](https://user-images.githubusercontent.com/33360391/236904843-f233dfff-ac4e-4068-b282-f6c52b79ecae.png)

**Comment by Valuebai** [comment]
urgency, please dev this feat as soon as posible

**Comment by Valuebai** [comment]
come on baby, you can do it

**Comment by markmhendrickson** [comment]
@alter-eggo is this a quick validation change by chance?
