### ISSUE TITLE
Additional accounts created using @stacks/wallet-sdk not appearing in Hiro Wallet

### ISSUE THREAD

**Issue by minahil-imtiaz** [blockstack/blockstack-app#3671]
**Description:**

I am using the [@stacks/wallet-sdk](https://www.npmjs.com/package/@stacks/wallet-sdk) package to create a wallet and add multiple accounts to it. However, when I try logging into Hiro Wallet, I only see the primary/default account and not the additional accounts that I created using the wallet sdk package.

**Steps to reproduce:**

- Generate seed phrase using `generateSecretKey` from `@stacks/wallet-sdk`package
- Create a wallet using the `generateWallet` from `@stacks/wallet-sdk` package
- Add multiple accounts to the wallet using the `generateNewAccount`
- Log into Hiro Wallet using the same seed phrase and see that only the primary/default account is visible

**Expected behavior:**
All the accounts added using the `@stacks/wallet-sdk` package should be visible in Hiro Wallet.

**Actual behavior:**
Only the primary/default account is visible in Hiro Wallet.

**Code snippet:**

```
import {
  generateNewAccount,
  generateSecretKey,
  generateWallet,
} from "@stacks/wallet-sdk";

const password = "password";
const secretKey = generateSecretKey();

let wallet = await generateWallet({
  secretKey,
  password,
});

for (let i = 0; i < 5; i++) {
  wallet = generateNewAccount(wallet);
}
```

**Additional information:**
- Version of `@stacks/wallet-sdk` package used: v6.5.2
- Operating system: macOS Big Sur version 11.6.4
- Hiro Wallet version: v4.21.0

**Comment by kyranjamie** [comment]
We're moving away from using Gaia as it adds a great deal of complexity to the wallet, with only minor user experience improvements.

[Like Metamask](https://support.metamask.io/hc/en-us/articles/360015489271-How-to-add-missing-accounts-after-restoring-with-Secret-Recovery-Phrase) and other wallets, we check for accounts with activity, and display existing non-zero, non-bns-holding accounts.
