### ISSUE TITLE
Inscriptions not loading in the wallet - ordinals api not updated with latest data?

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3673]
case 1. Wizard bought with 90bae63470a365c7a6b4a0895f426eae0a1e8adf61cee5cfd83e5809d0ebf288i0
Checking the address with this API ordinal 140600 is showing but it was not loading in the Hiro wallet. 
https://ordapi.xyz/address/bc1puw77m5wzr0eqny83q9hkhajv6smgdf7smnqgsawkfd2l8qhju33q7sn3q4

case 2. transfer inscription for BRC-20
Created this one: https://ordiscan.com/inscription/4997627
2a948f20f7c32bddb4f27d742304b06bb7bdb00340d003b90297198eaf0ca7a4

case 3. transfer inscription for BRC-20
Created this one: https://ordiscan.com/inscription/4750483
Confirmed 15 blocks ago: https://mempool.space/tx/2a948f20f7c32bddb4f27d742304b06bb7bdb00340d003b90297198eaf0ca7a4
But it is not showing up in the Hiro Wallet the user has tried reloading, restarting etc. 

case 4. mint inscription for BRC-20
Coins are showing up in the wallet, but the inscription is not. Despite 8 confirmations already: 
![image](https://user-images.githubusercontent.com/33360391/237061611-7db4ac02-e1f8-48f9-b756-c7d7c2a6808f.png)
![image](https://user-images.githubusercontent.com/33360391/237061967-995b3bc0-c76e-43bb-b3fa-0650bc284470.png)

![image](https://user-images.githubusercontent.com/33360391/237062182-d063f4f1-53b7-46d1-ba18-7ca27f815ed8.png)

**Comment by markmhendrickson** [comment]
@314159265359879 let's break these into distinct issues? I suspect they may have separate causes, and breaking out may help with diagnosis and resolution of each 🙏

**Comment by fbwoolf** [comment]
I think this is an issue loading utxos again from Blockstream ...not the ordinal api info after we have the utxos.

**Comment by 314159265359879** [comment]
> I think this is an issue loading utxos again from Blockstream ...not the ordinal api info after we have the utxos.

I do not see any blockstream errors in my logs yet this mint inscription is not showing up. Users are also reporting that their recent transfer inscriptions are not showing in the wallet.
https://ordinals-explorer.generative.xyz/output/1a8139aa47080bd052283adb5988d6ca4b37ab70721347d5731f044560f562e7:0

I tested this hiro API integrated built https://github.com/hirosystems/wallet/actions/runs/4894627346 but the result is the same. Should this work? @alter-eggo 

it shows as uninscribed:
![image](https://github.com/hirosystems/wallet/assets/33360391/68a17780-4d07-4ac6-84a3-8b28d1dd9bc9)

**Comment by alter-eggo** [comment]
@314159265359879 in this pr hiro api is used only for fetching certain inscription details. I discussed with @kyranjamie the problem of all inscriptions fetching from hiro api (we need utxo information in the api response as well). here is more info: https://github.com/hirosystems/bitcoin-indexer/issues/500

**Comment by kyranjamie** [comment]
I've tested these in the wallet and can see these details (thanks to @alter-eggo's work to migrate to Hiro API). Closing for now, but feel free to reopen if we have further reports of this @314159265359879
