### ISSUE TITLE
Add BRC-20 as token option in receive modals

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3674]
Should we add
BRC20 to this list? under tokens? with the taproot address?

![image](https://github.com/hirosystems/wallet/assets/33360391/bc0faf78-8416-4319-a67d-8f91de9b9f99)

**Comment by mica000** [comment]
Wasn't this already done by @fbwoolf?

@markmhx I dont think we need to pass this through design? It seems to be just a matter of duplicating the row in the front end plus the icon for BRC020

**Comment by markmhendrickson** [comment]
I believe she added an option for Stamps but not BRC-20 yet

**Comment by 314159265359879** [comment]
Or do we want to adapt the line "Ordinal inscriptions" to "Ordinals and BRC-20" instead? Just like Xverse does. 

![image](https://github.com/hirosystems/wallet/assets/33360391/eeea2094-7efe-4ae5-a218-38ccacaba9f1)

**Comment by 314159265359879** [comment]
We need this @markmhx users are sending BRC-20 to the "Token" address bc1q... now

**Comment by markmhendrickson** [comment]
@alter-eggo let's add a row below "Bitcoin" under "Tokens" for "BRC-20 tokens" that displays the same Taproot address as the Ordinals option, and presents both the "Copy to clipboard" option and "QR code" one

**Comment by mica000** [comment]
@markmhx @314159265359879 @alter-eggo 

Design proposal for receiving asset:
https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=4655-30582&t=uUQ9MklaRSHARuta-4

Design proposal for receiving collectible:
https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=4655-53732&t=uUQ9MklaRSHARuta-4

**Comment by markmhendrickson** [comment]
Even better here would be to list all known BRC-20 tokens by popularity so the user can receive a particular one vs. seeing a generic "BRC-20" deposit option

**Comment by 314159265359879** [comment]
> Even better here would be to list all known BRC-20 tokens by popularity so the user can receive a particular one vs. seeing a generic "BRC-20" deposit option

What users expect based on Ethereum wallets is that they have to permit a token to show. I believe we'll have to move to a similar model. 
- With BRC-20 we could let the user add the ticker of a token they want to see, we can even show it with 0 balance in that case until they receive the token.
- In the case of Stacks tokens we could show known/trusted ones. Or let users add the token contract themselves... 

I am not sure if you want to cover that all with this enhancement. might be better to have a separate enhancement to cover permissions to show tokens.

**Comment by markmhendrickson** [comment]
Resolved

![Image](https://github.com/user-attachments/assets/74193e7a-7e35-4a6b-bf5e-daf8de7cfe9f)
