### ISSUE TITLE
BRC-20 ordinals (transfer) not showing in the collectables area

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3677]
Especially BRC-20 transfers are not showing up in the collectables area: https://github.com/hirosystems/wallet/issues/3673

But they do show on a marketplace like Magic Eden. 
![image](https://github.com/hirosystems/wallet/assets/33360391/e54d5d2d-905f-4996-a17d-38357f5c7cb3)

**Comment by 314159265359879** [comment]
Similar case a user does not get inscription #5036015 to load in the wallet

![image](https://github.com/hirosystems/wallet/assets/33360391/281e7f55-6e7f-4aa5-99cd-57e6f142a930)

![image](https://github.com/hirosystems/wallet/assets/33360391/6d3e41f4-2200-4f90-bb24-2f39498cbd27)

![image](https://github.com/hirosystems/wallet/assets/33360391/abd90406-7276-4372-8134-2551f7ffa65f)

The front has 184 requests!!! and the loading icon in the wallet is never hidden!
![image](https://github.com/hirosystems/wallet/assets/33360391/7791356a-ee5f-4c5e-9b18-d60ce48f4d35)

**Comment by Valuebai** [comment]
please fix this bug ASAP!

**Comment by kyranjamie** [comment]
![Image](https://github.com/hirosystems/wallet/assets/1618764/402657d4-95c2-42e6-940d-197a7b581278)


Confirmed that wallet now shows BRC-20 balances correctly
