### ISSUE TITLE
Update URLs for default Gaia hub and subdomain registar

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#3678]
We are updating the sub domain registar links and we are also updating the Gaia hub links. 

The new URLs for subdomain registar can be found here

dev: https://registrar.dev.hiro.so/
stg: https://registrar.stg.hiro.so/
prd: https://registrar.hiro.so/

And for testnet

dev: https://registrar.testnet.dev.hiro.so/
stg: https://registrar.testnet.stg.hiro.so/
prd: https://registrar.testnet.hiro.so/

We are also updating the Gaia hub links. 

The prod hub URL is https://hub.hiro.so/hub_info and the real URL prefix for this hub is https://gaia.hiro.so/hub/

Our game plan was to work with @pradel and the sigle app to test these links but he informed us that he gets the links from the wallet. So we are looping in the wallet team in to get your opinion on how the wallet uses these links and the best way to test the redirect for the new url to make sure it doesn't break any functionality.

**Comment by timstackblock** [comment]
@zone117x I had a conversation with @friedger and he informed me that the zonefiles contain a link to the old gaia URLs, and the hash of the zonefile is written to the blockchain. To change the url in the zonefile all users have to do is an update.

What are your thoughts @zone117x

**Comment by zone117x** [comment]
Yes, if the old URLs are not preserved with a transparent DNS redirect, then all zonefiles pointing to those URLs would no longer resolve. They would all need to be updated. 

The developers and users of zonefiles could speak to the impact of trying to rebroadcast zonefile update txs for all zonefiles -- my personal take is that it's a big ask and not very feasible. I'm assuming many of the zonefiles are controlled by users rather than centralized entities, and that it wouldn't be possible to even get in contact with all users in order to broadcast zonefile updates.

**Comment by friedger** [comment]
Best way forward is to enable users to manage their storage better. Eventually, this could enabled paid storage services and better support y app projects.

**Comment by markmhendrickson** [comment]
> The developers and users of zonefiles could speak to the impact of trying to rebroadcast zonefile update txs for all zonefiles -- my personal take is that it's a big ask and not very feasible

Agreed on this. Even if we did a ton of messaging and provided an tool for easy zonefile updating, there's a lot of users who simply won't update and presumably it's undesirable for their Gaia hub usage to stop working as a result.

I'd recommend permanent, transparent redirects for these existing users, and we can push a new wallet build that updates the relevant URL values for users going forward.

e.g.

https://github.com/hirosystems/wallet/blob/45c090fa3ce584bebb8c321eb787ae9d06346385/src/shared/constants.ts#L6

**Comment by timstackblock** [comment]
That sounds like the best plan @markmhx when do you think we can get that wallet build to do a valid test?

**Comment by CharlieC3** [comment]
Yup, we can implement a redirect, but testing it beforehand will be difficult. I believe we would need to set up a dummy URL, like `hubredirect.blockstack.org`, to test out clients hitting that URL and being redirected to the new `https://gaia.hiro.so` URL.

**Comment by timstackblock** [comment]
@markmhx any estimate on when we would be able to get a new wallet build that uses the updated URLs for testing?

**Comment by markmhendrickson** [comment]
I've assigned to @alter-eggo so he can take a look. I imagine we could have it ready over the coming days since it's quite a small change on our end.

**Comment by timstackblock** [comment]
Thanks Mark

**Comment by CharlieC3** [comment]
I see this was closed, but only the Gaia Hub URL was changed in the dev branch when this issue is requesting both the Gaia hub and subdomain registrar URLs are updated for testing.
Does the wallet use the subdomain registrar URLs too somewhere? If it does, I think this may need to be reopened.

**Comment by timstackblock** [comment]
@alter-eggo @pradel 

Using this release and the Sigle app I get the URL https://gaia.blockstack.org/hub/1NrHHDeDzyrygU97L9Jyd3Dpg9qvuYJChs/stories.json. 

I was expecting to see this URL https://gaia.hiro.so/hub/ being called by the wallet is there any particular reason why this isn't happening as expected?

@markmhx you think we could jump on a quick call sometime and talk through this change with @CharlieC3 

<img width="1590" alt="Screen Shot 2023-05-25 at 11 19 25 AM" src="https://github.com/hirosystems/wallet/assets/49165468/6307d508-3ace-4dfb-a277-14c69d12a642">
<img width="1592" alt="Screen Shot 2023-05-25 at 11 18 55 AM" src="https://github.com/hirosystems/wallet/assets/49165468/13287abc-9e98-498f-9684-3ecdfc594161">

**Comment by CharlieC3** [comment]
Was this intended to go into a release? I may be mistaken, but I believe @timstackblock [was waiting on a development build with this change for him to test before it's included in a release](https://github.com/hirosystems/wallet/issues/3678#issuecomment-1549652472).
Additionally, the URLs may be functioning, but we're not expecting production-level load right now. Is there some sort of feature-flag safe-guarding this from going live?

To clarify, enabling the use of the new URLs in the description as a default will require a a high level communication between our teams and thorough testing beforehand.

If the latest release enables the above URLs, can this be rolled back from the production release?
cc @markmhx @saralab

**Comment by markmhendrickson** [comment]
@CharlieC3 Sorry we seem to have gotten our wires crossed. @alter-eggo has merged a reversion

@alter-eggo let's get the subdomain URLs updated as well but keep under review without merging until the @timstackblock can confirm testing is complete? 🙏

**Comment by alter-eggo** [comment]
yeah, sorry guys, seems there was some misunderstanding, reversion will go in the nearest release

**Comment by CharlieC3** [comment]
All good, thanks everyone for the rollback! On the upside we were able to see lots of successful responses coming from the new Gaia Hub, and Tim was able to conduct some testing too 😆
We'll know more after we complete some tests with the subdomain URL changed in a dev build.

**Comment by timstackblock** [comment]
Testing now will keep you updated.

**Comment by markmhendrickson** [comment]
@CharlieC3 @timstackblock it looks like the register URL isn't set wallet-side but in the API repo? https://github.com/hirosystems/stacks-blockchain-api/blob/214829157c45d4c0ce6556422e74bbd48db40039/src/tests-bns/api.ts#L350 🤔

**Comment by CharlieC3** [comment]
I believe we're going to need a development build from a PR with the URL change(s) in the API client. Though I'm not sure if that's something that can be tested separately or should be part of this test (or both) - @timstackblock 
cc @zone117x @rafaelcr

**Comment by timstackblock** [comment]
We should test them together if possible. We have a wallet build currently, now all we need is the updated API client build and we should be good to go.

**Comment by zone117x** [comment]
Note that the API does not set any gaia hub or registrar urls. Any of these URLs _returned_ by the API come from immutable transactions/zonefiles that were constructed by clients/services.

**Comment by markmhendrickson** [comment]
Hm yea it seems neither the API nor wallet codebase is currently determining the use of https://registrar.blockstack.org specifically 🤔

**Comment by timstackblock** [comment]
We spoke about this last week in a meeting @CharlieC3 please chime in if I am missing anything below. 

1) Complete testing with the test version of the wallet https://github.com/hirosystems/wallet/pull/3726.  DONE

2) Draft a communication release to notify clients/services they should update their zone files to the new URL by a certain date. IN PROGRESS

3) Execute a test with the test version of the wallet and an app that has updated the zone file. TBD

4) Release the updated version of the wallet live TBD

**Comment by timstackblock** [comment]
@markmhx related to this convo here https://github.com/hirosystems/devops/issues/1226#issuecomment-1582550007

I noticed the wallet doesn't write to the zone file this ok as long as it doesn't store/use data in Gaia. If it does please let us know. The main reason for this is because we want to make sure that if the zonefile data is deleted apps can write to the zone file when the app is used and create a new line under the apps section. If we do not see an app doing this we want to make sure that the app doesn't need to use Gaia or the zone file to work properly because it is a chance it will break if the data is deleted. You can view the convo in the link above for more information.

**Comment by markmhendrickson** [comment]
@kyranjamie are we storing data in Gaia anymore now that we've migrated at least partially away from Gaia for accounts persistence, per @timstackblock's inquiry above?

**Comment by kyranjamie** [comment]
I think the only place we still write to gaia is during auth, via the `@stacks/wallet-sdk` library.

https://github.com/hirosystems/wallet/blob/a4ad9c0b24d46b420b3b5156a62bc1b41596f873/src/app/common/authentication/use-finish-auth-request.ts#L63-L108

I'm fairly sure few apps rely on this, and that we could remove it entirely.

**Comment by markmhendrickson** [comment]
What's the intended effect per se of this auth-based write to Gaia? I.e. what do we or apps lose if we remove it?

**Comment by kyranjamie** [comment]
I'm honestly not sure how this is used. Some information about the app, and permissions given to it, are persisted. None of it seems critical: why do we save the app name and icon url? 🤷🏼‍♂️

**Comment by markmhendrickson** [comment]
@friedger do you recall how this is used by chance?

**Comment by timstackblock** [comment]
@markmhx the Gaia URL update was done yesterday so it is safe to push #3726 feat: change gaia URL live. Please let @CharlieC3 and myself know if you have any questions or concerns.
