### ISSUE TITLE
Dollar value in "Choose an account" is stacks value not Bitcoin value + Stacks value

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3680]
Expected is the same value as in the Account (or in Switch Account).

![image](https://github.com/hirosystems/wallet/assets/33360391/480808e4-0c45-4469-a561-fae629a47c10)

**Comment by markmhendrickson** [comment]
Hm my sense is that @alter-eggo fixed this recently?

**Comment by alter-eggo** [comment]
hm, I fixed only for account switching, not 'choosing'. they are different components. I'll refactor this part of code

**Comment by alter-eggo** [comment]
seems is fixed here  https://github.com/hirosystems/wallet/pull/4009 @markmhx
