### ISSUE TITLE
Deduct outbound pending BTC amounts from balance

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3685]
I wasn't following some of the balance work happening so closely, perhaps this is related.

I've funded a Native Segwit wallet, and transferred straight to TR (as the exchange I used doesn't withdraw to TR).

**Observations**

Activity screen shows pending both in and outbound.

<img width="1153" alt="image" src="https://github.com/hirosystems/wallet/assets/1618764/e3fe0a5a-418f-4d59-893b-3998d2edd8aa">

Even with outbound tx, balance remains unchanged

<img width="985" alt="image" src="https://github.com/hirosystems/wallet/assets/1618764/ce6be54c-d640-4664-951f-b1c3a180e108">

**Comment by markmhendrickson** [comment]
We essentially need to deduct pending outbound BTC amounts from the balance, correct? Similar to what we do now for STX pending transactions
