### ISSUE TITLE
Mask Secret Key entry during sign in by default

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3689]
Providing an option to reveal the value if desired, to protect from onlookers / cameras in public places.

Similar to https://github.com/hirosystems/wallet/issues/3560

**Comment by lakshdhamija** [comment]
Hey @markmhx, can I pick this issue?

**Comment by markmhendrickson** [comment]
@lakshdhamija Yep! Much thanks for the PR. We'll review shortly

**Comment by fbwoolf** [comment]
Not sure if this is a priority, but there is more work to do on this PR bc the proposed solution is broken. I worked on it for a bit before going OOO last week, but not sure if it is a priority for me to work on atm? It seems to be a bit tricky to toggle password visibility with an Input component `as="textarea"`. It should toggle based on type, but it isn't working and the proposed solution only works when pasting a secret key not typing a new one. @markmhx

**Comment by markmhendrickson** [comment]
@lakshdhamija Can you take a look at the changes needed to get this fully working re: @fbwoolf's comments here? 🙏

**Comment by lakshdhamija** [comment]
Hey @markmhx, I've fixed the mentioned issue with a commit. Additionally, I've added the ability to copy the unmasked key even when it's in a masked state.
