### ISSUE TITLE
On Magic Eden users with enough funds in their wallet are told they do not have enough funds

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3700]
Is this related to #3661 how does Magic Eden come up with these numbers?
Wallet balance: 0.00215186
Price on market (excluding fee): 0.001224
left to cover fees: 0.00092786

Current network fees on Bitcoin ~50 sats/vB

![image](https://github.com/hirosystems/wallet/assets/33360391/ae5febb2-f381-4e2f-a6cd-ab0ace7ab0d6)

Does this imply that Magic Eden is reserving a fee of 0.00305702 - 0.001224 = 0.00183302 (that looks excessive to me)

![image](https://github.com/hirosystems/wallet/assets/33360391/36e80f32-aebd-43cb-9687-0c42e422779a)

![image](https://github.com/hirosystems/wallet/assets/33360391/b60e4ca8-7f50-4f4a-904e-85586be157d2)

**Comment by 314159265359879** [comment]
Discussed with dev the expectation is that this is a Magic Eden bug, not a wallet bug. @markmhx can you ping them?

**Comment by 314159265359879** [comment]
Magic Eden has introduced a separate button to select the fees to send the transaction with. Low, medium and high option. Since these charges are not included in the total (A), this could help prevent cases described here that surprise users with less profits than expected or a higher cost than expected. 

![image](https://github.com/hirosystems/wallet/assets/33360391/578e5ced-9f7e-452c-9133-ee9da66c70ac)

Additionally, In the Hiro wallet we are working on improving the display of signing PSBT (partial bitcoin transactions), so users are better aware of the risks and can see what is expected to go in and out of the wallet. https://github.com/hirosystems/wallet/issues/3805

**Comment by fbwoolf** [comment]
Should this issue be closed if there are other issues linked to address it in the wallet, but it was ultimately a ME bug? Not sure why it has the label of `P2 Bug`?

**Comment by markmhendrickson** [comment]
I'd suggest we close as well unless we suspect it could be wallet-borne, though I noticed @314159265359879 had added some context here so I'm not sure if he's using this issue for support comms somehow?

I downgraded to P2 from P1 since this doesn't seem to be a widespread problem, whether on the ME or wallet side.

**Comment by 314159265359879** [comment]
Yes it is okay to close now, Magic Eden can improve their interface by showing the total including all fees. The error messages have been improved on their side already though. 

![image](https://github.com/hirosystems/wallet/assets/33360391/3f9ce24c-7133-4ae6-8d3d-623c575329e6)

Closing this.
