### ISSUE TITLE
Minted src-20 tokens but can't see them in wallet

### ISSUE THREAD

**Issue by Ironb4lls** [blockstack/blockstack-app#3703]
Hi, I minted STAMP tokens the other day, but I'm not able to view them in my wallet to know if it worked or not. 

Here's the transaction number:
135cf75cb9c30674e22b11f0fe468f3bff9d33e453b38519040bf7bde2569d42

**Comment by markmhendrickson** [comment]
Is this still the case or are they showing by now?

**Comment by Ironb4lls** [comment]
Nope. I upgraded to v4.24.1 hoping that would fix it, but I still can't see
them. I know they're there, because I checked the balance on stampchain.io,
but nada when I open the wallet either in the extension or a full tab.
Here's what it looks like.

**Comment by 314159265359879** [comment]
Please add Asset ID's and links to the asset on stampchain.io if you experience this issue with specific Stamps and they are not showing up. We expect SRC-20 stamps to show but not yet the balance #3696

**Comment by 314159265359879** [comment]
From a user experiencing Stamps not showing up:

Hey, thanks for the reply. ill try not to panic as i see them on the blockchain and will just wait. i dont have a github account but if easier im happy to create and post?
**the address the SRC-20 stamps are on is: **

bc1q6rqjely3v5p7tw60rl293k7xv4khrle9cjvq92

**SRC-20 Assets:**
A11026069395071628245
A14697346736704152557
A15227652783983860807
A15702138440036075915
A16802794062757647122

**wallet showing no SRC-20 stamps included**

![image](https://github.com/hirosystems/wallet/assets/33360391/d957e0ae-12a5-4a1f-ad83-33a85b09adb5)

This is what is showing ono stampchain.io for this address:
https://stampchain.io/index.html?creator=bc1q6rqjely3v5p7tw60rl293k7xv4khrle9cjvq92
![image](https://github.com/hirosystems/wallet/assets/33360391/5a37299b-bbde-43b0-b819-2b7c4fcc16ec)

**Comment by tlake412** [comment]
Also for me, It doesn't Show up. Wallet address bc1qnas3ryhx8us6adhe7puwtm23gh55plasxeyrd2

Assets: 

A6598071545959832409
A639476900754396742

**Comment by jvdged** [comment]
Having the same issue here. 

Address: bc1q75t73sgd9akf7r2lfxnvqns4mtydtmguyldhtw

Assets:

A15544368248697724268
A9432096614409284163

**Comment by 314159265359879** [comment]
Stampchain.io website will show users a list of Stamps, whereas the wallet API returns an empty array: 
https://stampchain.io/api/stamps?wallet_address=bc1q6rqjely3v5p7tw60rl293k7xv4khrle9cjvq92

Same here
https://stampchain.io/api/stamps?wallet_address=bc1qnas3ryhx8us6adhe7puwtm23gh55plasxeyrd2

And here
https://stampchain.io/api/stamps?wallet_address=bc1q75t73sgd9akf7r2lfxnvqns4mtydtmguyldhtw

This is being looked into by stampchain devs. The Hiro wallet relies on their API to show the Stamps.

**Comment by Ironb4lls** [comment]
> Please add Asset ID's and links to the asset on stampchain.io if you experience this issue with specific Stamps and they are not showing up. We expect SRC-20 stamps to show but not yet the balance #3696

Here's my Asset ID: A18359677048586562970
And the link: https://stampchain.io/asset.html?stampNumber=29446

**Comment by 314159265359879** [comment]
Another case
Displays on stampchain.io for this address.
https://stampchain.io/index.html?creator=bc1qy44w8ez9s9q5ent7ge3qfqrfjrql6pallwrj2s
![image](https://github.com/hirosystems/wallet/assets/33360391/a555b0d5-3fe5-4c3a-b2cc-89845fea05f1)


API returns nothing, which is why the wallet does not display them. 
https://stampchain.io/api/stamps?wallet_address=bc1qy44w8ez9s9q5ent7ge3qfqrfjrql6pallwrj2s

**Comment by Ironb4lls** [comment]
> Another case Displays on stampchain.io for this address. https://stampchain.io/index.html?creator=bc1qy44w8ez9s9q5ent7ge3qfqrfjrql6pallwrj2s ![image](https://user-images.githubusercontent.com/33360391/240028468-a555b0d5-3fe5-4c3a-b2cc-89845fea05f1.png)
> 
> API returns nothing, which is why the wallet does not display them. https://stampchain.io/api/stamps?wallet_address=bc1qy44w8ez9s9q5ent7ge3qfqrfjrql6pallwrj2s

So it sounds like the problem is something on stampchain's end. Should we bring this issue to them?

**Comment by 314159265359879** [comment]
It looks like SRC do require a different method compared to Stamps. This API can help
https://stampchain.io/api/stamps?creator=bc1qy44w8ez9s9q5ent7ge3qfqrfjrql6pallwrj2s def. gives a filled array. 
(_creator_ rather then _wallet_address_) This Will show all created stamps if you want src-20 then filter by _locked_ and _supply 0_

instead of https://stampchain.io/api/stamps?wallet_address=bc1qy44w8ez9s9q5ent7ge3qfqrfjrql6pallwrj2s which will not return the SRC's.

I think it makes this an enhancement rather than a bug?

**Comment by markmhendrickson** [comment]
This seems like a dupe of https://github.com/hirosystems/wallet/issues/3696?

**Comment by markmhendrickson** [comment]
> I think it makes this an enhancement rather than a bug?

Perhaps technically, though my expectation would also be that these types of stamps show up given our current implementation. So de facto it seems buggy

**Comment by 314159265359879** [comment]
> This seems like a dupe of #3696?

Yes it is, at the time I was not sure if it was just related to a specific token mentioned there (Kevin).

**Comment by Awais78666** [comment]
can some one help me please I am really worried I have mined Kitty SRC20 in may 2023 but still not received in wallet they dont show my wallet address is bc1qfasv3dr8d4u6jt6uz4wgnqyzq32vtzrac3ump2

**Comment by 314159265359879** [comment]
@Awais78666 SRC20 is not yet displayed in Leather. Sign in with your wallet on openstamp.io or stampscan.xyz and view your profile/address assets, those dapps will display your SRC20 holdings. If you need further support please get in touch with us via email on support at leather.io
