### ISSUE TITLE
Issue with Stacks NFT collection not loading properly in Hiro wallet

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#3712]
NFTs in the Stacks NFT collection are not loading properly in the Hiro wallet vs Gamma.io site displays. Users are experiencing slow loading times or NFTs not loading at all. 
related (https://github.com/hirosystems/wallet/issues/3290)

Comparison screenshots:

Hiro Wallet
![hiro1](https://github.com/hirosystems/wallet/assets/132958967/4cd3dcbc-9efb-44ca-a005-fff6385c722b)

Gamma.io
![gamma1](https://github.com/hirosystems/wallet/assets/132958967/70532e66-f217-485a-a279-a6908c8ce383)

**Comment by markmhendrickson** [comment]
I suspect this may be an API-born issue. Mind opening a related issue in the metadata API repo and linking to this wallet one from there so that team can take a look? https://github.com/hirosystems/token-metadata-api

**Comment by DeeList** [comment]
Done <https://github.com/hirosystems/token-metadata-api/issues/158>
