### ISSUE TITLE
Minted but not received token

### ISSUE THREAD

**Issue by Abinesh76** [blockstack/blockstack-app#3729]
Today I had minted the SRC-20 the token name is "Kevin"-10000
Transaction I'd : fc587a2a89f8e3817049c3ecd657a4c72515da2c4b0eaf0dbb1ebcf1cf707479

Inputs & Outputs
bc1q55dmgz6lfh8sy52kgrnwj6ltqc8kjj
ur2k3plx
bc1qqt7euu7q7ww5mzqq29a46zc6a7jm8h
7x7kwezd

They minted it with this transaction on stampsrc dot github dot io
https://mempool.space/tx/fc587a2a89f8e3817049c3ecd657a4c72515da2c4b0eaf0dbb1ebcf1cf707479

**Comment by 314159265359879** [comment]
See details here, closing as a copy of 
https://github.com/hirosystems/wallet/issues/3696#issuecomment-1556150178
