### ISSUE TITLE
Improve UTXO filtering when building Bitcoin transactions to avoid errors

### ISSUE THREAD

**Issue by BTCAlchemist** [blockstack/blockstack-app#3732]
I tried to send two BTC transactions in a row but the second one threw this error:
`sendrawtransaction RPC error: {"code":-26,"message":"insufficient fee, rejecting replacement f3afc7318e054aa12883b34f475293621277041fc95f3a957f81ba843588210e; new feerate 0.00067262 BTC/kvB <= old feerate 0.00067262 BTC/kvB"}`
![image](https://github.com/hirosystems/wallet/assets/56145569/c8a101ce-589d-4ade-98df-bbb4fd5a9629)

The first one did not confirm yet, so I suspect an unconfirmed tx might cause this error in submitting a second one, is it?

**Comment by BTCAlchemist** [comment]
Just tried two in a row again and got this error
![image](https://github.com/hirosystems/wallet/assets/56145569/d1a5df3f-3636-4309-8878-df15dadfcbc0)

**Comment by BTCAlchemist** [comment]
Got this error again when trying to send two txs in a row. This is a problem because it is a time-sensitive tx, and now I have to wait for the first one to confirm before the second one will work.
![image](https://github.com/hirosystems/wallet/assets/56145569/00b7afd2-8531-4b49-ad1e-7092b5e4166d)

**Comment by 314159265359879** [comment]
Hi @BTCAlchemist you are trying to send regular BTC? not inscriptions, right?

**Comment by BTCAlchemist** [comment]
@314159265359879 Yes, that's right, I was sending regular BTC.

**Comment by fbwoolf** [comment]
@kyranjamie any thoughts on how to handle this with coin selection? It appears this happens when we are tying to spend the same input but the tx fee is the same, so it thinks the user is trying to do an RBF.

**Comment by kyranjamie** [comment]
We need to find a way to get more up-to-date UTXO information for subsequent broadcasts.

Maybe it'd be sufficient to manually refetch the UTXO query when a wallet's sent a transaction/about to spend another, but then we're still relying on the API to be current. Or querying the mempool directly for our transactions, and use that to filter UTXOs.

If neither of those approaches work, we might need to consider persisting spent transaction data, and filtering based on that.

**Comment by fbwoolf** [comment]
Any work we do here might be included with changes we make to how we handle utxos in the send form, which we discussed yesterday? @markmhx is there an issue for that yet?

**Comment by markmhendrickson** [comment]
Hmm I don't think I created one for UTXO handling. Mind doing so since I don't recall the details personally? 🙏

**Comment by fbwoolf** [comment]
Discussed in eng sync today, going to start here by making a change to filter out utxos with a pending status...
https://github.com/Blockstream/esplora/blob/master/API.md#get-addressaddressutxo

**Comment by fbwoolf** [comment]
Realizing here the status ^ is of the funding tx, so I'm creating a new query to utilize the spent status of the utxo...
https://github.com/Blockstream/esplora/blob/master/API.md#get-txtxidoutspendvout

Hoping this will work > in-progress.
