### ISSUE TITLE
Support for Cursed Inscriptions

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#3748]
Cursed inscriptions are ordinal inscriptions that never received an inscription number due to a bug in the protocol.

These inscriptions have negative numbers counting backward, and are currently not protected from spending in the same way that standard inscriptions are.

Eventually, this bug will be fixed (https://github.com/casey/ord/issues/2045) and no new negative-numbered inscriptions will be able to be created. Still, there should likely be protection in place for these existing inscriptions.

More info: https://twitter.com/billyrestey/status/1661406587511271424

**Comment by markmhendrickson** [comment]
This API-side change should ensure that cursed inscriptions show up under collectibles: https://github.com/hirosystems/ordinals-api/issues/83

> are currently not protected from spending in the same way that standard inscriptions are.

Mind explaining this a bit more?

cc @kyranjamie given his work on inscription send protections

**Comment by brandonmarshall-tm** [comment]
> Mind explaining this a bit more?

Like how there is protection for UTXOs that contain inscriptions being spent, are there similar protections in place for these cursed inscriptions?

**Comment by kyranjamie** [comment]
If the Hiro Ord API says there's no inscription, and it's on a Native Segwit address, then we would assume it's spendable. Are there any other reliable way to check for cursed inscriptions?

**Comment by brandonmarshall-tm** [comment]
https://cursedordinals.com/ was a resource, but doesn't seem to be working anymore

**Comment by brandonmarshall-tm** [comment]
Ordinals Protocol received an update yesterday which will account for these cursed inscriptions, so Hiro Wallet will need to support them!

https://github.com/ordinals/ord/releases/tag/0.6.0

**Comment by brandonmarshall-tm** [comment]
Hiro's API will be supporting these soon, which I believe will then allow them to work on the Wallet side without much (if any) changes needed.

#https://github.com/hirosystems/ordinals-api/issues/99

**Comment by markmhendrickson** [comment]
That's correct. No additional changes to the wallet will be needed once the API re-indexes in support of this type of inscriptions. My impression re: https://github.com/hirosystems/ordinals-api/issues/99 is that reindexing is imminent, if not complete by now already.
