### ISSUE TITLE
Display SRC-20 token balances

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#3751]
Show SRC-20 token balances.

This would allow users SRC-20 token name and balance to display.

https://github.com/hydren-crypto/stampchain/blob/main/docs/src20.md

**Comment by markmhx** [comment]
Looks like this is actually a dupe of https://github.com/hirosystems/wallet/issues/3696

**Comment by fbwoolf** [comment]
@markmhx I'm not seeing an api to get SRC-20 balances? The link here is just for the token data itself. For BRC-20, we query: 

`https://brc20api.bestinslot.xyz/v1/get_brc20_balance/${address}` ...which appears to have been changed by @alter-eggo after my initial implementation using Unisat api.

EDIT: Not sure from what I see that this should be a priority? 🤔

**Comment by markmhendrickson** [comment]
Steve from [Stamp Wallet](https://www.thestampwallet.com/) has provided this endpoint, which is currently using in that wallet as well: https://pkizh327c7.execute-api.us-west-2.amazonaws.com/prod/src20/balanceByAddressV1?address=bc1qzat8m5ufnpwcng3j9ytd6a04k6uj7mc335m2v3

**Comment by markmhendrickson** [comment]
[The Stampchain API](https://www.notion.so/trustmachines/Stampchain-API-9f875379cf6c4cf2a531725732bf9ae1) now supports SRC-20 balances.

**Comment by fbwoolf** [comment]
@markmhendrickson made some progress here, but the api schema documented is not what is returned in the query ...so a bit hesitant to feel like this is stable? Who is our contact for Stamps at this point?

Schema documented: https://stampchain.io/docs#/default/get_api_v2_src20_balance__address_
My SRC-20 balances: https://stampchain.io/api/v2/src20/balance/bc1qqwl3fwlarjt4rhhvtyekzd9mxf6jhw5q8fw3v0

What I see is the schema in the Stamps query we already use that returns an array of `src20` here:
https://stampchain.io/docs#/default/get_api_v2_balance__address_

Or, do you know something I'm missing? ~~Also, I'm not seeing the Stamp I purchased in my collectibles, is that a known issue I'm forgetting I should address here? ...I'll look to see if there is an open issue.~~ 👀 Nvm, I see it now.

**Comment by fbwoolf** [comment]
@DeeList are you with stampchain.io to answer my question above ^?

**Comment by markmhendrickson** [comment]
I believe the API owner should be in the "Leather & Bitcoin Stamps" group in TG. I've inquired there and CC'ed you @fbwoolf

**Comment by fbwoolf** [comment]
Was merged in https://github.com/leather-wallet/extension/issues/3751 ...I linked to the wrong issue so it didn't close automatically.
