### ISSUE TITLE
Ordinals not loading for some users on regenerated addresses

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3752]
Possibly it is related to ordinals being on regenerated address from before March 20th such as this case:

used 4.26.0 and 4.24.2 console doesn't show relevant errors. 
![image](https://github.com/hirosystems/wallet/assets/33360391/db9dc846-8ba9-4f24-aee5-5e36e9e51e4f)

https://discord.com/channels/1075856098269089834/1075920122314756166/1111377159261528165
![image](https://github.com/hirosystems/wallet/assets/33360391/e3be110d-4288-4d5d-99bd-a776fa26aa8f)

The user thought this may have been relevant but I do not think so because the addresses were generated by Hiro https://github.com/hirosystems/wallet/issues/3297

**Comment by 314159265359879** [comment]
It turns out I misunderstood and the issue is related to https://github.com/hirosystems/wallet/issues/3297 after all, originally created with Ords wallet.

**Comment by 314159265359879** [comment]
Two more users have reported some NFT's on regenerated addresses not loading. And I was unable to establish the issues are similar to the issue above where perhaps the algorithm to check addresses with activity is failing to find all the regenerated addresses with ordinals. 

https://ordinalswallet.com/address/bc1px3sgt0y9hk8cl4f6qj43qg308h5gjz63qcjeavryt33sh2ancrsqw60929
Only the NFT"s on this wallet address are not loading. Other addresses seem unaffected. 
Wallet 4.27.1, clearing cache and reinstalling the wallet made no difference. The user has 100+ Ordinals in Hiro and regenerated addresses are expected to have between 11-99. according to this user. 

@kyranjamie Are there any recent changes that could have caused this loading from regenerated addresses issue?

I have checked some of my wallets with ordinals in regenerated addresses and they do load, so it doesn't seem to be an issue in all cases.

**Comment by markmhendrickson** [comment]
@314159265359879 is this latest case not one originating from Ord in which their regenerated addresses are too spread out for our current scanning?

**Comment by 314159265359879** [comment]
> @314159265359879 is this latest case not one originating from Ord in which their regenerated addresses are too spread out for our current scanning?

This latest case is not originated from Ord. They used Hiro prior to March 20th when it was still regenerating fresh addresses.

**Comment by markmhendrickson** [comment]
This bug seems to have been introduced with [v4.25.0](https://github.com/hirosystems/wallet/releases/tag/v4.25.0). I tested the immediate previous version with an affected user and their inscriptions showed up.

We inspected the network calls to study activity related to a missing inscription. In the version where it didn't show up, we saw just a blockstream API call for the relevant owner address whereas in the version where it _did_ show up, we saw that blockstream call _plus_ a relevant Hiro Ordinals API call (for the inscription's metadata). So it seems that we're effectively querying the owner address but something is happening before the inscription data specifically is getting queried.

**Comment by kyranjamie** [comment]
What's the latest on this issue? Can you share the address information of said affected user?

To try and replicate this, we could try mocking some API calls locally with scattered inscriptions. @alter-eggo maybe write some fake Promise responses where say there's an inscription on the 20th, 40th, and 60th address index, and see if it displays correctly.

I wonder if it's possible to write a query that doesn't rely on the data outside of the query & next page logic, such as the `useRef`. That might be a cause of the problem/complexity too.

**Comment by 314159265359879** [comment]
@kyranjamie 
bc1pz6t7a9ytmpq63wms3agmwgmtlw8n96de09lmsuqnc53prhj0q8lqwknkzn
and
other user: bc1px3sgt0y9hk8cl4f6qj43qg308h5gjz63qcjeavryt33sh2ancrsqw60929

**Comment by 314159265359879** [comment]
Another case
The megapunks on this address are not showing up in the Hiro wallet: bc1p05nj660caphzyms4njetdv3fzuz3xdfz4fqjcl5f75xy9tvauu2slkc56p

The users's primary taproot address .../0'/0'/0/0 = bc1pp5ur0maw2m3gfjvvdj0d27kxlj3lpl78xykqjajer6vqq9ar03eqy0hkcz

**Comment by markmhendrickson** [comment]
I'm reopening to QA further and confirm the fix

**Comment by markmhendrickson** [comment]
The affected user who's QA'ed this build says it doesn't resolve the issue for him. Want to schedule time with him to debug live?

**Comment by alter-eggo** [comment]
@markmhx yeah, it would be great

**Comment by markmhendrickson** [comment]
@314159265359879 is coordinating this call now 🙏
