### ISSUE TITLE
Resolve or clarify error "Unable to calculate fees" when sending ordinals

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3760]
A user tried to send an inscription from their account and got this error: "unable to calculate fees". 

Wallet version 4.27.1 and 4.27.0

I am not sure if it is relevant but the inscription was on a secondary taproot account (from before March 20th when we still regenerated fresh taproot addresses when old ones were used), not the primary one (as displayed in receive). 

We tried in Chrome and Firefox, the console would not display any errors.

![image](https://github.com/hirosystems/wallet/assets/33360391/3fdc12b1-33ac-427f-8cf8-151c958e5df9)

**Comment by 314159265359879** [comment]
I got several other reports in the past hours. Looks like more recent addresses without regenerated addresses.

**Comment by fbwoolf** [comment]
@markmhx we probably just need a better error to display here? This will show if now `feesLIst` is passed to that component, which can happen for several reasons. Could this have been an api failure? We can't guess on fees if we don't fetch utxos or if our query for fee rates fails.

**Comment by markmhendrickson** [comment]
@314159265359879 any idea if these users later find that sending works for the same inscriptions (which might indicate API side issues that later clear up by themselves)?

If you can check with the users again, it could be worth looking at the "Network" tab of the dev tools in addition to the console, to see if the API is indeed erroring somewhere.

**Comment by fbwoolf** [comment]
Temporarily made changes here https://github.com/hirosystems/wallet/pull/3782 to address the error, but will further fix when I implement custom fees https://github.com/hirosystems/wallet/issues/3597: 



![Image](https://github.com/hirosystems/wallet/assets/6493321/1e9fd0e4-19f3-44a0-90e6-f23b58cc58b0)
