### ISSUE TITLE
Don't subtract fee from balance for incoming Stacks transactions

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3761]
To reproduce:
1. Send STX transaction with 0.0025 STX fee to a fresh address
2. Look at the balance when activity is pending:

![image](https://github.com/hirosystems/wallet/assets/33360391/6e5c9592-783f-4e9c-a28f-800506be2f58)

**Comment by markmhendrickson** [comment]
@alter-eggo might some of your recent work on balances have resolved this already?

**Comment by alter-eggo** [comment]
@markmhx don't think so, I haven't touched stx balances

**Comment by 314159265359879** [comment]
Users are still experiencing this. Incoming transfer with 0.01 fee will result in: 
![image](https://github.com/hirosystems/wallet/assets/33360391/b949867b-fa8e-45d2-9f6e-ffe1755588a8)

Especially popping up again now with all the testnet faucet use at the moment.
