### ISSUE TITLE
Show total BRC-20 balance, not just "available"

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3763]
It seems that if I have a transfer inscription that I haven't sent anywhere yet (still on my own address), the BRC-20 balance shows my total minus the amount of that inscription. However, it should still show the total amount.

Note how the same wallet in UniSat shows 5 for the total balance here and 1 for "available" balance, which is the value we seem to be showing as our "total". However, we need to add the "transferable" to get the total (or otherwise pull a different total value from the API, if available):

<img width="942" alt="Screenshot 2023-05-28 at 11 43 13" src="https://github.com/hirosystems/wallet/assets/28991/4a2c43d8-ed61-45f2-bb11-91073f9031c8">

<img width="1349" alt="Screenshot 2023-05-28 at 11 43 21" src="https://github.com/hirosystems/wallet/assets/28991/f729d2e6-d9d9-4fd3-a167-2860f9a89a1d">

<img width="330" alt="Screenshot 2023-05-28 at 11 48 38" src="https://github.com/hirosystems/wallet/assets/28991/3f984d35-a7b5-465e-86ba-ad171e8e8d24">

**Comment by markmhendrickson** [comment]
@314159265359879 curious if you've seen reports or user confusion about this?

**Comment by markmhendrickson** [comment]
@fbwoolf I'm curious what kinds of tests we have in place for balances in general these days that we could expand to cover stuff like this. Perhaps worth discussing live as a team as a broader topic

**Comment by 314159265359879** [comment]
> @314159265359879 curious if you've seen reports or user confusion about this?

Yes there is confusion about this. Some users report tokens lost after inscribing a transfer inscription because the token balance changes before they send the inscription out.

**Comment by markmhendrickson** [comment]
Are those tokens actually lost, or is that just the perception? I presume the latter?

**Comment by fbwoolf** [comment]
> @fbwoolf I'm curious what kinds of tests we have in place for balances in general these days that we could expand to cover stuff like this. Perhaps worth discussing live as a team as a broader topic

No tests atm. This was fixed here, correct? https://github.com/hirosystems/wallet/pull/3774

**Comment by 314159265359879** [comment]
> Are those tokens actually lost, or is that just the perception? I presume the latter?

Just perception indeed.
