### ISSUE TITLE
Prevent inadvertent display of send form validation errors

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3766]
It seems that if the user focuses then blurs the amount or recipient fields in the BTC send form, their validation errors appear instantly even without having entered a value.

We shouldn't show these errors unless the user blurs with a non-empty value that's invalid.

Notice how it affects selecting one's own account for recipient having already focused the field.

https://github.com/hirosystems/wallet/assets/28991/d4b0e093-2edc-4c6e-a128-8f479ab4dd8e

https://github.com/hirosystems/wallet/assets/28991/72b6e283-93e3-49f8-8d48-0cbe8d6b8861

**Comment by markmhendrickson** [comment]
A similar behavior occurs if the user focuses a field, then changes tabs to copy a value, then comes back and pastes the value:


https://github.com/hirosystems/wallet/assets/28991/b0c2af43-6185-42a6-ba4e-96297ce7aaa6

**Comment by kyranjamie** [comment]
Please record full screen @markmhx makes it easier to follow. Is it specifically related to changing tabs, or just that the perceived value is wrong when pasted in?

Note the earlier issues you've reported in this issue are fixed. We don't show errors if the form isn't dirty (touched and different than initial value)

**Comment by markmhendrickson** [comment]
Will do re: full screen going forward 🙏  

Note in this video, I'm simply selecting the field, clicking on another tab, copying the value I'd pasted in its address bar (for convenience), toggling back to the tab with the wallet, and pasting.

So, the value isn't wrong but for some reason the validation gets wonky having moved between tabs in the middle of the process. If I don't change tabs but rather select the field and paste the same value directly (having already copied it previously to my clipboard), I don't get this validation error.

**Comment by pete-watters** [comment]
I've been investigating this and it looks like an issue occurs with the validation incorrectly firing after focusing on a field then un focusing again. 

https://github.com/hirosystems/wallet/assets/2938440/13242e80-9255-4b4f-ba36-1bbf77c2c589

**Comment by pete-watters** [comment]
This was fixed in https://github.com/leather-wallet/extension/pull/4032 but not closed properly
