### ISSUE TITLE
Upscale amount field size in send form once shorter value entered

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3767]
It seems that once we downscale the amount field in the send form, we don't then upscale it again if the user changes the entered value to a shorter value than the longer one that caused the downscaling in the first place. Ideally we rescale up and down as necessary based on values.

https://github.com/hirosystems/wallet/assets/28991/8dab3988-5280-485b-b4eb-dae8cec974f3

**Comment by ddanielcruzz** [comment]
Hey @markmhx I got a PR open to fix this https://github.com/hirosystems/wallet/pull/4012 😀

I would appreciate a review

Thanks!

**Comment by markmhendrickson** [comment]
Much thanks, @ddanielcruzz!
