### ISSUE TITLE
Uppercase start of invalid recipient message

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3769]
"Recipient is invalid"

(bonus: audit other validation messages in the wallet for the same formatting tweak)

<img width="387" alt="Screenshot 2023-05-28 at 18 43 44" src="https://github.com/hirosystems/wallet/assets/28991/398f20f8-5dfc-4edd-8f35-099bd58033db">

**Comment by pete-watters** [comment]
I tested this and its no longer causing a problem. Now we say `Address` and its cased correctly 

![Screenshot 2024-06-28 at 11 48 42](https://github.com/leather-io/extension/assets/2938440/780f836b-3eed-4c9f-bae1-5cd4b7e2936b)
