### ISSUE TITLE
Add account parameter for signMessage and sendTransfer APIs

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3770]
Currently it seems like users can only sign BTC transactions and PSBTs with the account they have currently active in the wallet and not with the one they used to connect to the app (via auth or requestAddresses), in the case that the user has switched to a different active account post-connection.

Perhaps we need a way for the app to pass an optional account index or address parameter to indicate the account of choice?

**Comment by fbwoolf** [comment]
@kyranjamie didn't you address this last week in your refactoring?

**Comment by kyranjamie** [comment]
In https://github.com/hirosystems/wallet/pull/3727 I didn't make any changes to the PSBT signing logic. 

It looks like the implementation has always used the user's current account to sign the PSBT.

https://github.com/hirosystems/wallet/blob/551d55c91fa5f75df74a5635c9f0a71ae3c81c69/src/app/pages/psbt-request/hooks/use-psbt-request.tsx#L25-L26

Perhaps clients can pass some metadata, such as they account they want to sign with?

**Comment by fbwoolf** [comment]
> 
> Perhaps clients can pass some metadata, such as they account they want to sign with?
>
Ok, yeah, what they sign with has to match what we pass in auth response. You did change that, correct?

**Comment by kyranjamie** [comment]
It fixed #3725, which changes the public key returned from the app, but doesn't touch the signing logic, if that's what you meant?

**Comment by ericatallah** [comment]
It would be great if a client can specify the address they want to sign the inputs with.  This way if there are any signing errors, they can be propagated up to the client.
Currently, it's a little unclear what happens when a PSBT is signed, and there are no indications or error messages if the signatures fail.  I'm assuming it loops through all the inputs passed in, and tries to sign each with the segwit address, and if unable, it will try the tr address?

**Comment by markmhendrickson** [comment]
@fbwoolf might we need to add error handling coverage for the PSBT API in particular? If so, it's perhaps worth creating a separate issue to track its addition

**Comment by fbwoolf** [comment]
> @fbwoolf might we need to add error handling coverage for the PSBT API in particular? If so, it's perhaps worth creating a separate issue to track its addition

Yep we can, typically the errors come from the btc-signer lib and are seen pretty clearly in the console for devs to troubleshoot but I'm not sure users would know how to report. As for passing the address(es), I think it is a good idea but will require changes to the api. We could have them pass an array that tells us an address and which input indexes to sign using that address. @kyranjamie this should prob be done for message signing too? I did confirm it is just using the current account for signing.

**Comment by kyranjamie** [comment]
For this feature, we should make it clear in the UI when a user is signing from an account that isn't the active one.

**Comment by markmhendrickson** [comment]
Perhaps for this related edge case in which the user switches keys (not just account of same key), we can display a standardized error a la "Your connected account does not pertain to your active wallet."? https://github.com/hirosystems/wallet/issues/3837

**Comment by markmhendrickson** [comment]
Pending for signMessage and sendTransfer, and also need to update relevant docs for converting derivationPath values to account values for usage as parameters

**Comment by fbwoolf** [comment]
~~Sent an invite to @kyranjamie for tom morning to talk abt the PSBT api changes, bc I think might be confusing to apps? Our docs aren't very clear about the changes, and I'm a bit confused abt how to implement the account here. I am thinking, as part of this issue, I should update btckit too? @markmhx feel free to join if want.~~

EDIT: Ignore me. 🙃

**Comment by fbwoolf** [comment]
@kyranjamie nvm here if you want to ignore mtg request, every time I post something I immediately see the answer to my question! Haha. I didn't see in your merged PR the warning was removed to indicate it was the wrong account, so I thought I was missing something abt the implementation. ...the current account is just set to the custom account if one is provided ...got it.
