### ISSUE TITLE
Add public keys to `getAddresses` response

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3778]
Currently only address and type are returned

**Comment by markmhendrickson** [comment]
Super important addition – is this a quick one we can release this week?

**Comment by 0xVikasRushi** [comment]
Hey! I would like to contribute to this issue

**Comment by markmhendrickson** [comment]
Please do! 🙏

**Comment by 0xVikasRushi** [comment]
Current Response of **getAddresses**? 

![Screenshot 2023-05-30 at 9 31 41 PM](https://github.com/hirosystems/wallet/assets/88543171/2db652ee-d464-48d1-bf09-4548141ab71a)

im not able find a method to get publicKey from address. can you give a bit more infomation about which public keys to be returned?

**Comment by friedger** [comment]
Public keys can't be derived from addresses, because addresses are hashes. You need to use the private key. @0xVikasRushi 

Should users been informed about exporting public keys vs addresses only? @markmhx

**Comment by markmhendrickson** [comment]
@0xVikasRushi I might suggest checking out how the authentication endpoint returns public keys and using that method, though @kyranjamie can confirm whether there's a better approach: https://hirowallet.gitbook.io/developers/bitcoin/connect-users/authenticate-users

@friedger what kinds of info do you have in mind?

**Comment by friedger** [comment]
@markmhx In the popup of authentication show what is exported from the wallet so that we don't get disappointments like ledger did.
