### ISSUE TITLE
BTC transfer transaction with returning BTC in mempool can cause 0 balance

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3785]
Total balance is input. Most is returned and a small amount is send elsewhere or spend as fee. Users can get a scare because it can look like their whole balance is gone. 

![image](https://github.com/hirosystems/wallet/assets/33360391/502f0e8b-aa15-4a75-9a67-c647cd9b6a9b)

![image](https://github.com/hirosystems/wallet/assets/33360391/0a0d7bb3-d66d-477b-b47b-b841df286646)

![image](https://github.com/hirosystems/wallet/assets/33360391/a3643c2c-6c51-4ee4-823e-0112eb8a7b45)

After one confirmation the balance did show again as normal for the user.

**Comment by markmhendrickson** [comment]
By "returning BTC" what do you mean exactly? Are these PSBTs?

**Comment by 314159265359879** [comment]
> By "returning BTC" what do you mean exactly? Are these PSBTs?

I mean this output (138k sats) which is returning to the "input address". 
![image](https://github.com/hirosystems/wallet/assets/33360391/32eb86cb-e8f8-4653-bea2-5ab9d2492ee7)

**Comment by alter-eggo** [comment]
@314159265359879 could you check if this issue is still relevant here please: https://github.com/hirosystems/wallet/pull/3927

**Comment by 314159265359879** [comment]
@alter-eggo I have not seen it pop up testing with the latest build lets close this, for now, I will reopen if it does pop up again. It is a bit tricky to test because the issue didn't materialize in every situation.
