### ISSUE TITLE
Insufficient balance error on max button

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3796]
User reports:
when i try to send btc out it does not allowing me to. and when i press on max withdraw it only show something like this ˜1.24$ when i have over $10 in btc

**Comment by 314159265359879** [comment]
Another user experiencing issue with sending max. Only 1/4th is allowed from this 18$ balance worth of BTC (current fees 60-80 sats/vByte average expected fee about 2-3$ worth of BTC 10k sats for a normal send). 
![image](https://github.com/hirosystems/wallet/assets/33360391/6eadbfe1-b8bf-4209-866d-cb490473552e)

Involved wallet
bc1qqjzymy6k685rfq07287q326gq2d877meeu88am
https://mempool.space/address/bc1qqjzymy6k685rfq07287q326gq2d877meeu88am

I think sending everything in case of a small amount like this requires this enhancement: https://github.com/hirosystems/wallet/issues/3136

**Comment by markmhendrickson** [comment]
Presumably this PR, which is undergoing QA and should be released this week, will resolve this issue? https://github.com/hirosystems/wallet/pull/3782

**Comment by markmhendrickson** [comment]
@314159265359879 I'm closing this out on the presumption that #3782 resolved it but please reopen if you see it reported further
