### ISSUE TITLE
Insufficient balance error when sending small amount

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3797]
When I was trying to send 0.0009 BTC to another address my wallet prompted "insufficient funds". Actually, I had 0.015 BTC in my wallet.

![image](https://github.com/hirosystems/wallet/assets/33360391/c23cd746-9bd8-4def-b19d-64f8e8605823)

Possibly related to: https://github.com/hirosystems/wallet/issues/3661 and #3796 

Working to get more details on this case and other cases. I will add it here as I get it. 

This case address: https://mempool.space/address/bc1q6rd60efuphvffll4yhxs45w6dkppyxqhc3a8hu
User using Chrome browser/extension

Address has 57 transactions, and several look like Stamp mints. Does the issue have something to do with that?

![image](https://github.com/hirosystems/wallet/assets/33360391/388cb9be-6aa3-4eb9-bc39-c0adc162cb23)

**Comment by 314159265359879** [comment]
Another case like this user with 150$ worth of bitcoin in the wallet. unable to send about a fifth of the amount. 

I see transactions in the history of this wallet that look like Stamp mints again. 

![image](https://github.com/hirosystems/wallet/assets/33360391/e5387396-c7b5-449e-84a5-19620ff36589)
![image](https://github.com/hirosystems/wallet/assets/33360391/f61039af-31da-4e4f-b3c7-10a85983b315)

**Comment by 314159265359879** [comment]
please see [#3814](https://github.com/hirosystems/wallet/issues/3814) possibly related and examples of affected addresses in there.

**Comment by alter-eggo** [comment]
@314159265359879 is this still relevant? couldn't reproduce

**Comment by 314159265359879** [comment]
I am checking with some of the users who were affected by this, I will update here as I get more info.

**Comment by markmhendrickson** [comment]
@314159265359879 Were you able to confirm this is still an issue or should we perhaps close out for now?

**Comment by 314159265359879** [comment]
> @314159265359879 Were you able to confirm this is still an issue or should we perhaps close out for now?

@markmhx I have not been able to confirm with users who were affected by this in the past. I do believe it is safe to close I have not been able to recreate this either and haven't seen new reports for over a month now. 

We should consider also closing #3814 as those cases have likely also been resolved with this.
