### ISSUE TITLE
Add PSBT error handling

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3804]
Users are reporting silent failures with PSBT signing, where the modal just closes. Let's test this with some PSBTs that don't work, and make sure that some useful form of error message is returned to developers

<details>
<summary>Example PSBT</summary>

```
70736274ff01007d0200000001006f2dff5c6bbd9e908a127fc0838f63ac6df2b1f55f30b3b57d34b8e09b96b50c00000000ffffffff021027000000000000160014ca5000b93abcaab28c76e305c3224a1db5634e9e00000000000000002251206a0b4d305bdcf228da5d55f5f19aa082638c72d1d2c2df7001ec9549551dd20c000000000001012b10980200000000002251206a0b4d305bdcf228da5d55f5f19aa082638c72d1d2c2df7001ec9549551dd20c0117206ac12fe706263361d1a26e7a927cbace6485e1d66e8dcfb2f14fa4f6f0e7e1c1000000
```

</details>

**Comment by nftgeek** [comment]
This is very annoying, spent whole day debugging. The modal returns the same psbt given as input, which is unexpected.  Proper error handling is needed. @markmhx

**Comment by markmhendrickson** [comment]
Sorry for the frustration, @nftgeek! We'll dig into this soon since it's in high demand for developers generally atm.

**Comment by fbwoolf** [comment]
@kyranjamie should this be reopened and tied to this PR? https://github.com/hirosystems/wallet/pull/3917

**Comment by fbwoolf** [comment]
Adding a proper error flow with the work here: https://github.com/hirosystems/wallet/issues/3849
