### ISSUE TITLE
Insufficient Balance

### ISSUE THREAD

**Issue by atulkaushalmd** [blockstack/blockstack-app#3814]
Good afternoon!  I have 0.0065182 BTC in my HIRO wallet.  Trying to make a purchase of 0.004008 BTC and keep getting an 'insufficient balance' error.  I have no pending transactions.  Last transaction was several hours ago and has settled earlier today.  Please advise.  Hate to keep sending BTC to the wallet to cover transactions that should be OK.
Much appreciated!  Have been hitting this error quite a bit over the last few days on various txns.

**Comment by atulkaushalmd** [comment]
As an added detail, Hiro is telling me the MAX withdrawal is 0.00197147....but I clearly have 0.0065182 with no pending txns.

**Comment by atulkaushalmd** [comment]
![image](https://github.com/hirosystems/desktop-wallet/assets/135667245/36bc5104-e3bc-4257-85be-a5d5525bced5)

**Comment by atulkaushalmd** [comment]
My BTC address in HIRO wallet:  bc1qag0nazlqlp2tzurht7c7f9rj802e9wnzgz994x

**Comment by markmhendrickson** [comment]
Thanks for reporting @atulkaushalmd, and my apologies for this trouble.

@314159265359879 can you confirm here whether this PR is expected to resolve this particular user's report? https://github.com/hirosystems/wallet/pull/3782

**Comment by 314159265359879** [comment]
@markmhx I don't think 3782 resolves this because the user does not want to send max but a very specific amount (lower than max). 

This issue looks like https://github.com/hirosystems/wallet/issues/3797
If the 0.00651582 consists of many small amounts it could require higher fees, we expect the wallet to reserve for that, it seems that reserving ~200k sats for fees is quite a lot still (fees were between 15-90 sats per vByte around the time this issue was posted). 
I also see some transactions in this wallet that look like they minted stamps. Those sats do not look like they have been subtracted yet (from total balance 0.00651582), we do not want to send those, about 50 times 546 sats = 27,300 sats

**Comment by atulkaushalmd** [comment]
Thanks for clarifying the issue so it can be examined.  Is it simply due to the extra sats that don't get transferred right away?  Is there any way to account for that in the TOTAL, so that we're not looking at inflated account balances?

**Comment by 314159265359879** [comment]
In case the devs need this: Another wallet affected by this. A user trying to send an ordinal from their Ordinals address (BRC transfer). using their 10$'s worth of BTC in the native segwit address. 

Average fees on the network look low enough 15-50 sats/vByte to cover the transfer with this amount. Expected fee rate in dollars would be about 2$ worth. 

Funding: bc1qnyn990z6696m3ytt0dh5d6mnrzt9lq2745x8u9
BRC Address: bc1punyujs7kkqn2jq4v8mxvsc6wcptssfq5ynyhd8tzv77zll5jq9nqjatwca

**Comment by 314159265359879** [comment]
> Thanks for clarifying the issue so it can be examined. Is it simply due to the extra sats that don't get transferred right away? Is there any way to account for that in the TOTAL, so that we're not looking at inflated account balances?

Stamp mints and protecting stamps do not require protecting the UTXO's like Ordinals do. I just learned I was wrong to think that. We are protecting UTXO's from (accidental) ordinals that end up in the BTC address. But those are subtracted from the total as expected.

**Comment by atulkaushalmd** [comment]
Actually funny you mentioned it.  I accidentally sent an ordinal to my BTC segwit address in Hiro.  Could that be creating this problem?  And more importantly, can I get it out and move it to the Ordinals address?

**Comment by 314159265359879** [comment]
> Actually funny you mentioned it. I accidentally sent an ordinal to my BTC segwit address in Hiro. Could that be creating this problem? And more importantly, can I get it out and move it to the Ordinals address?

Yes actually you can move it out, and it is def. interesting to know if that resolves the prior issue. 
To move the ordinal does require a third-party wallet (for now). We have a tutorial covering the steps here: https://hiropbc.notion.site/Ordinal-migration-instructions-for-Hiro-Wallet-5f3b7787a3394b278436500d43b5a82d

**Comment by atulkaushalmd** [comment]
Thanks!  WHen I get a break from work, I'll give it a shot and report back here.  Much appreciated!

**Comment by markmhendrickson** [comment]
Closing as likely resolved per https://github.com/hirosystems/wallet/issues/3797#issuecomment-1638770022
