### ISSUE TITLE
User copies address to clipboard gets other address compared to short preview

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3826]
They see this screen in the wallet. And when they copy the address in Receive they get the following address. 
Even more oddly when they switch accounts (Account 2) they see a different (short) address when they click receive but after copy the same address is pasted: [SP1TDT0D3GFZ9VRKTG24F2DR24ZNNF6QPCVK9JM82](https://explorer.hiro.so/address/SP1TDT0D3GFZ9VRKTG24F2DR24ZNNF6QPCVK9JM82?chain=mainnet)

![image](https://github.com/hirosystems/wallet/assets/33360391/b488a27a-49b6-49d0-9d8c-fda5ffc84887)

Reinstalling the wallet from wallet.hiro.so, trying on Chrome, Firefox and even Xverse all had the same result. They are using a 24 word key generated with the wallet. This makes absolutely no sense to me and I am unable to reproduce this myself. 

Note: The user says: while using another Secret Key the process is as expected. When they copy the address then it will copy the address that relates to the short address shown in receive.

**Comment by markmhendrickson** [comment]
This has been reported only once, correct? Very strange indeed.

**Comment by 314159265359879** [comment]
Yes only once
