### ISSUE TITLE
Remove stamp UTXO amounts from BTC balances

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3827]
The Hiro wallet is protecting Stamps from accidental sends. Should that mean they are not shown as balance? Consider this wallet

This wallet with stamps, 
![image](https://github.com/hirosystems/wallet/assets/33360391/77952e18-b53e-4f48-a0ac-3c348fe2bd12)

on chain shows the same amount. 
![image](https://github.com/hirosystems/wallet/assets/33360391/94800733-1e08-4ab1-b577-4f2b71612af2)

Should the values from the stamps 6x 546 sats ~3300 sats be subtracted?

Should we show 0.00110550 BTC (3000 sats locked)?
Similarly with protected UTXO's from ordinals on the native segwit address?

Just subtracting the UTXO's is confusing because the balance will not reflect the total on an BTC explorer. It is better to display a locked amount separately.

**Comment by markmhendrickson** [comment]
It looks like @kyranjamie added send protection for stamps here but we haven't enhanced by reducing the balance by their amount yet, so we can frame this issue as that enhancement

https://github.com/hirosystems/wallet/pull/3571

**Comment by kyranjamie** [comment]
@314159265359879 please share the address so I can debug.

We use the "spendable utxos" to calculate balances, so this shouldn't be the case.

**Comment by 314159265359879** [comment]
@kyranjamie for this case: bc1qjjndzkm28qwapam0473kk672wvv3udwncl70sn

Also seen on bc1qryw8wetee6tug3y8cwh39qqc9s04q2h0plutj3

**Comment by kyranjamie** [comment]
Reached out to the stamps people. The stamp `tx_hash`es don't match ay of the utxos

**Comment by mikeinspace** [comment]
Unlike Ordinals that are tied to specific UTXOs/Sats, you can't "send away" your stamps by sending the Bitcoin balance. In fact, if you completely depleted your Bitcoin balance to 0, all the Stamps would remain. This is because Counterparty acts a meta layer where address balances exist independent of the Bitcoin in the address. In this way Stamps are far less fragile than Ordinals. @kyranjamie

**Comment by kyranjamie** [comment]
This can be closed as stamps don't require filtering
