### ISSUE TITLE
Add BRC-20 transfer support for non-zero-index taproot addresses

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3830]

**Comment by markmhendrickson** [comment]
From @314159265359879:

> Careful with this functionality of showing coins on regenerated addresses. If they have 1000 ORDI on one and a 1000 ORDI on another address they would need to inscribe two transfers one to each address for a 1000 ordi. If the wallet shows 2000, will the user realize this, will the wallet handle that?

It seems we can address this case by generating two or more inscriptions as needed, if the user enters an amount that represents more than the balance available on a single address.

E.g. user has across three addresses:

1. Taproot address # 1: 591 ORDI
2. Taproot address # 1: 3 ORDI
3. Taproot address # 1: 9523 ORDI
4. Taproot address # 1: 10 ORDI

If they go to send 1000 ORDI, the wallet can use up all available on the lowest index address / first one, then use whatever it needs from subsequent ones in a sequential manner:

1. Transfer inscription created for 591 ORDI with Taproot address # 1
2. Transfer inscription created for 3 ORDI with Taproot address # 2
3. Transfer inscription created for 406 ORDI with Taproot address # 3
4. No transfer inscription created with Taproot address # 4

Another (more optimal) way could be to create these inscriptions by address in descending order by how much they have for balances, to decrease the number of inscriptions required to send the total amount.

**Comment by kyranjamie** [comment]
Just spoken with @alter-eggo about this. I'm wary of the approach that we try and wrap sending BRC-20 tokens spread across many addresses (as you may with Bitcoin txs), at least on a first pass of this feature.

There's a lot going on here, and to mask all the steps will drastically increase the complexity. It requires a significant rewrite of many parts of the transaction form:

- The confirmation page will need to reflect when many transactions have been made
- We'll need to write "coin selection" logic for BRC-20
- Currently the user would see all the separate pending requests in their _Pending BRC-20_ section
  - ...unless we write more logic to group/batch pending requests
- The user will still need to send all of these individually with what we have now 
  - ...unless extend the send inscription feature to work with batch transaction requests

It's going be a huge task to do according to your description @markmhx, and I think we should ask whether the value we'll get from this ux is worth the time & effort, versus a simpler solution of only allowing users to send the balance of one address at a time.

Does Unisat support a single tx ux for balances across addresses?

**Comment by markmhendrickson** [comment]
Makes sense re: the complexity here, thanks for the explanation.

> versus a simpler solution of only allowing users to send the balance of one address at a time.

Could we simply list a given BRC-20 token in the "Choose asset" screen / list multiple times, once per address, if it's indeed spread across several addresses (indicating the amount per address and letting the user proceed just from there for sending from one at a time)?

This would probably be just fine for the edge case here in which users have BRC-20 on non-zero indices, even if it's a bit strange.

> Does Unisat support a single tx ux for balances across addresses?

They don't support non-zero indices in general

**Comment by kyranjamie** [comment]
Yep, this would be much simpler to build. Not against a custom UI for this, that groups them at little better than just displaying the same BRC-20 token multiple times.

```
┌─────────────────────────────────────────────────────────┐
│ ┌────────┐                                              │
│ │  FARA  │                                      30 FARA │
│ └────────┘                                              │
│                        ┌───────────────────────────────┐│
│                        │   Address index #1 --- 10 FARA││
│                        └───────────────────────────────┘│
│                        ┌───────────────────────────────┐│
│                        │   Address index #2 --- 20 FARA││
│                        └───────────────────────────────┘│
└─────────────────────────────────────────────────────────┘
```

**Comment by alter-eggo** [comment]
@markmhx @kyranjamie  seems we need to specify somehow the address in the brc-20 list item? 
<img width="529" alt="Screenshot 2023-06-20 at 11 52 17" src="https://github.com/hirosystems/wallet/assets/46521087/cb738c4f-427b-4635-866f-d1ced0bf2ca5">
<img width="516" alt="Screenshot 2023-06-20 at 11 53 20" src="https://github.com/hirosystems/wallet/assets/46521087/a4507a7e-3999-44fc-9b16-fc8ea9803190">

**Comment by markmhendrickson** [comment]
Let's discuss design needs here with @mica000 during kick-off today

**Comment by markmhendrickson** [comment]
Instrument `analyitics.identify({ has_brc20_across_addresses })` for BRC-20 query and 🚢
