### ISSUE TITLE
Decrease significant numbers in fees (fee selection)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3836]
Lets round the sats/vB to whole numbers. I see upto four decimals now. 

![image](https://github.com/hirosystems/wallet/assets/33360391/a02f2e87-25ac-49b3-81cd-8ae1705516bf)

**Comment by kyranjamie** [comment]
To fix this we should adjust average fee calc logic so we floor/ceil round and avoid any decimals.
