### ISSUE TITLE
Make entire activity item area clickable

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3845]
When I hover an item in activity and try to click in the gray hover background area near the edges, it doesn't open up the corresponding link unless I move the cursor further inside the area:

https://github.com/hirosystems/wallet/assets/28991/615abd19-0c75-4c52-9ec8-c9e3cf311e06

The user should be able to click anywhere in the gray area to use the link.

**Comment by CVamsi27** [comment]
Hey, I would like to work on this

**Comment by CVamsi27** [comment]
@markmhx,
I did set up the extension but devnet isn't available for me: what should I use for testing?
![image](https://github.com/hirosystems/wallet/assets/55316723/7997415f-57cf-4ae5-a73a-d2beebc8a36f)

My local when I run <yarn dev>:
![image](https://github.com/hirosystems/wallet/assets/55316723/7efe594f-1ca3-4a65-8e2a-a91cbaff46c4)

How to get some sample transactions to test?

**Comment by markmhendrickson** [comment]
Please see these instructions for running devnet: https://docs.hiro.so/smart-contracts/devnet
