### ISSUE TITLE
Add optional OP_RETURN parameter for API to initiate BTC transaction

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3848]
For effectively supporting memos within BTC transactions. Requested by the ALEX team.

https://hirowallet.gitbook.io/developers/bitcoin/sign-transactions/fully-signed-bitcoin-transactions

**Comment by fbwoolf** [comment]
Not 100% sure on the implementation here, but it does look btc-signer lib handles opcodes. Prob wouldn't take long to figure out.

**Comment by markmhendrickson** [comment]
ALEX has subsequently indicated a preference for OP_RETURN over OP_DROP here

**Comment by fbwoolf** [comment]
I am not understanding here why we would have to choose the opcode to handle as the wallet? The opcode can be anything the app wants, right? We would simply use it for the tx output. @fiftyeightandeight are you hoping to pass us an encoded script, or what are you hoping to pass us? What exactly are you asking for here from the api?

**Comment by fiftyeightandeight** [comment]
> I am not understanding here why we would have to choose the opcode to handle as the wallet? The opcode can be anything the app wants, right? We would simply use it for the tx output. @fiftyeightandeight are you hoping to pass us an encoded script, or what are you hoping to pass us? What exactly are you asking for here from the api?

Hi @fbwoolf we are looking to encode arbitrary message in the tx output, like the below. We are aware that currently OKX Wallet supports this via `OP_RETURN`.
https://mempool.space/tx/8bae12b5f4c088d940733dcd1455efc6a3a69cf9340e17a981286d3778615684

**Comment by fbwoolf** [comment]
> Hi @fbwoolf we are looking to encode arbitrary message in the tx output, like the below. We are aware that currently OKX Wallet supports this via `OP_RETURN`.
> 
> https://mempool.space/tx/8bae12b5f4c088d940733dcd1455efc6a3a69cf9340e17a981286d3778615684
> 
> 

I understand that, but how do you want to pass the data to us? What data type?

**Comment by fbwoolf** [comment]
Also, curious here, if you want more control over the tx, why not use PSBTs?

**Comment by fbwoolf** [comment]
I am reluctant here to say, `We are going to handle OP_RETURN`, it doesn't make any sense. Apps should be able to pass us any opcode in a script to be applied to a tx output. I think you should pass us the encoded script, we shouldn't know what it is. @kyranjamie your thoughts here on the api change?

**Comment by fiftyeightandeight** [comment]
If you could add an optional string parameter (say, `opReturn`) in the `sendTransfer` tuple and apply that opcode to the tx output, that will work for us (https://hirowallet.gitbook.io/developers/bitcoin/sign-transactions/sending-bitcoin).

Below is an example of a Bitcoin wallet (imToken) on its handling of `OP_RETURN` from UI perspective.

![telegram-cloud-photo-size-5-6104845637154616606-y](https://github.com/hirosystems/wallet/assets/443225/5f6fed67-a663-4c45-94a2-eaf00174a810)
 
![telegram-cloud-photo-size-5-6104845637154616607-x](https://github.com/hirosystems/wallet/assets/443225/ebfa3697-f706-4a80-b2fa-db7ee3ab4357)

**Comment by fbwoolf** [comment]
Ok, got it, thanks for the feedback. 👍

**Comment by fbwoolf** [comment]
@markmhx @mica000 wondering about the UI here with `Advanced` again, how many users really know what an opcode is?

EDIT: Maybe we aren't displaying this for the user?

~~Wondering also if we should make it more flexible, where the app passes us a param, `opcode` and `opcodeData`?~~ Nvm here, prob not possible to handle all. We can expand later.

**Comment by kyranjamie** [comment]
My understand aligns with @fbwoolf's here 

> I am not understanding here why we would have to choose the opcode to handle as the wallet? 

`OP_RETURN`s are described in the transaction itself. This guide shows how to create a tx with an op return https://bitcoindev.network/guides/bitcoinjs-lib/embedding-data-with-op_return/

@fiftyeightandeight what stops you from following these steps, turning the tx into a PSBT, and asking the Hiro Wallet to sign it?

Imo `sendTransfer` should not have an op return flag. This is simple "send money" feature, and adding op return might confuse our intentionally simplified API. For complex use cases, we have the PSBT feature that intends to allow _any possible transaction_.

[See a demos an unspendable return here](https://github.com/paulmillr/scure-btc-signer/issues/26#issuecomment-1450887431).

**Comment by fiftyeightandeight** [comment]
Hi @kyranjamie yes, we can handle this as part of PSBT, but were also wondering if there could be an easier way (for the casual users) to include "memo" when sending a transaction.
I also see your point on `sendTranfer` staying as a simple "send money" feature, though being able to include memo in that simple feature would be nice.

**Comment by fbwoolf** [comment]
Closing this issue in favor of apps using PSBTs for this functionality.
