### ISSUE TITLE
Organize PSBT signing data into "You'll transfer" vs. "You'll receive"

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3849]
Right now we show "Inputs vs. Outputs" which are hard for users to understand and therefore sign without having to trust the initiating app.

Organizing the signing consequences into "You'll transfer" vs. "You'll receive" would be more intuitive for users and make it possible for them to understand easily just what they are permitting from and to their account.

[Related designs in Figma](https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?type=design&node-id=2160%3A76296&mode=design&t=SAbfAUFuhiuvzjUw-1)

**Comment by fbwoolf** [comment]
@markmhx @mica000  I don't think the link here to designs is current? I would stick with just trying to be in parity with other wallets, showing the BTC total to transfer/receive at the top? I prefer how the other wallets keep the inputs/outputs separated beneath the total.

**Comment by markmhendrickson** [comment]
I agree as well that we should keep a way to view the raw inputs/outputs. I believe a previous exploration in Figma had this as an "Advanced" option of sorts to reveal them. We could either bring that option back or simply list below the transfer/receive summary.

**Comment by fbwoolf** [comment]
@markmhx sorry, somehow I edited your comment by mistake (which seems odd for me to be able to do). I meant to, and think I was, replying to it.

**Comment by fbwoolf** [comment]
> I agree as well that we should keep a way to view the raw inputs/outputs. I believe a previous exploration in Figma had this as an "Advanced" option of sorts to reveal them. We could either bring that option back or simply list below the transfer/receive summary.

We still have an `Advanced` tab that shows the decoded PSBT. That has always stayed in production. It is the `Simple` view that has been in flux. Personally, I just disagree with simplifying it to completely remove the better UI of showing the inputs/outputs in that view.

**Comment by mica000** [comment]
Curious to know your thought on this proposal:

https://github.com/hirosystems/wallet/assets/119523541/d7f0f5d9-37b1-461c-9395-203be19a4e5f

**Comment by kyranjamie** [comment]
Personal preference, perhaps, but I don’t like the default toggle closed. If I’m interested in the details, it’s an extra action to click open, if I’m not interested, I just won’t scroll there.

**Comment by fbwoolf** [comment]
Can we just keep the inputs/outputs as-is with the `Advanced` view as a toggle (not dropdown)? Is there a reason it is changing back to a dropdown? 

Maybe that inputs/outputs section defaults to open, but we can add the ability to close it?

**Comment by pete-watters** [comment]
I like this way of not showing too much information at first to overwhelm users. 

We could even elaborate further in the future and setup user specific settings so that this area could be completely hidden / shown if users had an `Advanced` setting on.

For some experienced people the extra detail is useful but for newer users I think it's better to keep it clean and simple as it's less things to confuse them.

**Comment by markmhendrickson** [comment]
@mica000 Once we have a design candidate the internal team feels good about later this week, let's also send to marketplace teams (e.g. Gamma, Magic Eden, Ordinals Wallet, UniSat) to get their feedback as well?
