### ISSUE TITLE
Fix PSBT signing for SIGHASH_SINGLE + SIGHASH_ANYONECANPAY flag

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3859]
Needed by OnChainMonkey, NeoSwap and Ordinal Wallet

**Comment by fbwoolf** [comment]
There is no info here, what does this even mean? We accept a param for `allowedSighash` (an array), so what is being reported as broken?

**Comment by markmhendrickson** [comment]
We've gotten reports from these teams that signing doesn't work when using this flag. With OnChainMonkey, it came up over a call; with NeoSwap it was reported [here](https://trustmachines.slack.com/archives/C05B70BPC78/p1687362820855539); and with Ordinal Wallet [here](https://discord.com/channels/@me/1100114735732621322/1122041203861508156).

cc @kyranjamie since interacted with some of these teams already re: the possible issue

**Comment by fbwoolf** [comment]
That conversation points to a suggestion Kyran makes to the team to ref the btc-signer lib we use. The `sighashType` has to be included with the input passed to us, then it has to exist in the `allowedSighash` array. It defaults to `all`. I think this is an error on the app side of not including the `sighashType` on the input?

https://github.com/paulmillr/scure-btc-signer/blob/91b37a5e2d5bc372d079f399efa552f4eb132cb7/index.ts#L490

EDIT: Appears lib defaults to`ALL` except for taproot defaults to `DEFAULT`.

**Comment by fbwoolf** [comment]
Xverse implementation is not diff than ours, except they make it an array when passed to the signer method. They just accept one type as a param.

https://github.com/secretkeylabs/xverse-core/blob/1d4013e9ce3c895b7fc92b432053462bbf0c6704/transactions/psbt.ts#L108

**Comment by fbwoolf** [comment]
Checking myself... haha.

![Image](https://github.com/hirosystems/wallet/assets/6493321/2ef57757-2b14-4b78-9124-594e6740feee)

**Comment by fbwoolf** [comment]
I did do testing on this today, and it was working for me in our test-app as long as I built the inputs/outputs correctly with the PSBT passed to the wallet. Also, if I remember correctly, I think Gamma has been using the flag `SIGHASH_ANYONECANPAY`?

**Comment by fbwoolf** [comment]
`sighashType` provided should use this enum we provided:

```js
export enum SignatureHash {
  DEFAULT = 0,
  ALL = 1,
  NONE = 2,
  SINGLE = 3,
  ANYONECANPAY = 0x80,
}
```

**Comment by fbwoolf** [comment]
@markmhx can I start to close these in favor of better documentation for PSBTs? There are 3 issues assigned to me that I'm not sure how to close bc not really issues in the wallet to fix.

**Comment by markmhendrickson** [comment]
Yep go for it! I'll work on queuing up improvements to the docs separately.
