### ISSUE TITLE
OnChainM different pub keys returned for taproot wallet v4.25 and v4.26

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3868]
See also e-mail thread. user indicated it is likely not related to https://github.com/hirosystems/wallet/issues/3770 as first thought. 

Fara mentioned this may be related to the code changes here:
https://github.com/hirosystems/wallet/issues/3725
https://github.com/hirosystems/wallet/pull/3727

The user reported
_In all my test runs, my wallet did have many accounts in it, but I was sure that the active account matched the connected account in all cases. So it was odd there was still a discrepancy between the pub keys returned between v4.25 and v4.26. The original issue I had raised was fixable by ensuring the accounts matched (connected and active). But in v4.26 and beyond, I'm unable to get it to work at all. I also tested on Magic Eden (tried to list an inscription for sale), and it is broken there now as well. I'll try to do a test with a single account wallet, but may not be able to get to it today as we're swamped this week._

**Comment by 314159265359879** [comment]
The reproduction on Magic Eden was on mainnet and showed an error "Invalid signature - no finalScriptWitness" according to Eric as he tried to list on Magic Eden. 

I have reproduced this. It looks like it is caused when there is a difference between the wallet signed in on in Magic Eden and the active address in Hiro wallet. Magic Eden is trying to sign with the active wallet on Magic Eden rather than the wallet address that is signed in with. 

Example signed in with Account 1 on Magic Eden, wallet on Account 5 and the sign-popup also shows Account 5. 

![image](https://github.com/hirosystems/wallet/assets/33360391/c4417965-d538-467e-ac1b-556bbc6d4989)

Error shown:
Invalid signature - no finalScriptWitness
![image](https://github.com/hirosystems/wallet/assets/33360391/9b6bec65-83a6-452e-a29d-c6a79ff74bd7)

Workaround:
Switch to the account on the Hiro extension so they are the same on Magic Eden and the extension. Then try again. I will check with Eric if the workaround works in their case too. 

This does look related to: https://github.com/hirosystems/wallet/issues/3770 this wasn't fixed with #3725 because it didn't change the logic for PBST's. 

The same error would be shown if the wallet is signed into with a completely different Secret Key. One can compare the primary taproot address to confirm (the one when copying the address for Ordinal Inscriptions, should be the same as the (partially displayed) address in the upper right corner on Magic Eden.

**Comment by markmhendrickson** [comment]
@314159265359879 this should be resolved in the latest release. Can you confirm?
