### ISSUE TITLE
Allow users to choose any recommended fee or set any custom fee while sending max

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3871]
They expect to be able to change the fee (not just have low and/or medium options, although very literally the low amount does allow sending the maximum amount). Should the other options be grey? now high is clickable and it will show insufficient balance rather than adapt the mount. 

Users expect to set the fee (preferably including custom fee) and then the amount send is adapted based on that so that the wallet leaves a total of 0 BTC in the address. 

![image](https://github.com/hirosystems/wallet/assets/33360391/16e7ace9-434b-4edb-b0af-2078cad5a10c)

Is this working as intended or does this merit a change?

**Comment by markmhendrickson** [comment]
I noticed this myself this morning. I'd expected the "send max" mode to allow me to choose any recommended fee or set any custom rate, and that it would just adjust the "max amount" value accordingly and never show an error per se that I didn't have enough (unless the fees were so high compared to a very low balance in which I didn't even have enough in my balance to cover the fees plus minimal amount).

@fbwoolf does this need additional UX guidance from @mica000 or does that described approach sound straightforward enough?

**Comment by fbwoolf** [comment]
This is clear to me, maybe I misinterpreted the designs but not sure. Dropping a link to the designs here so I can ref them again: https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=4655-97133&t=0azeT52ChHcoF0WP-0

**Comment by mica000** [comment]
@fbwoolf Just small obs that the page you referred is before custom fees. 

**Allow users to choose any recommended fee:**
https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=4655-106139&t=si50CXDV4b8Da50R-4

**set any custom fee while sending max:**
https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=4655-100007&t=si50CXDV4b8Da50R-4

**Comment by fbwoolf** [comment]
@markmhx changed the estimate here, fyi.
