### ISSUE TITLE
Fix header indentation for Stacks transaction signing

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3881]
For some reason the header text is now bumped to the right instead of aligned to the left:

<img width="459" alt="Screenshot 2023-06-15 at 15 09 09" src="https://github.com/hirosystems/wallet/assets/28991/accd0140-cbf0-4848-ae50-4fc1fb363137">

I believe I've also since an instance where it's entirely center aligned, though I can't recall how to recreate atm.

**Comment by markmhendrickson** [comment]
I'm seeing this in v6.0.0, not sure if we had a regression?

![Screenshot 2023-07-26 at 11 22 10](https://github.com/hirosystems/wallet/assets/28991/d4d4b41e-7872-49bf-a49a-fcb44c229133)

**Comment by prasad5795** [comment]
@markmhx may i solve this?

**Comment by prasad5795** [comment]
![image](https://github.com/hirosystems/wallet/assets/49803589/71f00053-c350-4fc2-a4f8-bb58fed579ae)

**Comment by pete-watters** [comment]
Hi @prasad5795 ,

Thanks, I'll review your PR soon

**Comment by pete-watters** [comment]
Thanks for fixing this @prasad5795 👍 

@markmhx - I had been looking at a different section, the very top with the users BNS name & balances. I believe we can also improve that area so it aligns consistently
