### ISSUE TITLE
Add multisignature option for Stacks transactions

### ISSUE THREAD

**Issue by fess-v** [blockstack/blockstack-app#3889]
We're building the first native multi-sig wallet for Stacks, and for that, we really miss that functionality for signing multi-signature transactions
there're functions like
`openContractDeploy`
`openContractCall`
`openStxTokenTransfer`
But for now, it can't work with multisig transactions, which is essential if we want to connect with the Hiro wallet from our frontend UI
All existing libraries for Stacks wallet connection lack this feature - [`micro-stacks`](https://micro-stacks.dev/docs/overview) and [`stacks.js`](https://docs.hiro.so/stacks.js/overview)

Related issue https://github.com/hirosystems/wallet/issues/1454
Related SIP for the signing order problem https://github.com/stacksgov/sips/pull/139
Related code for multi-sig transaction flow using @stacks js library https://github.com/hirosystems/stacks.js/issues/1487
PR for stacks blockchain for the SIP above https://github.com/stacks-network/stacks-blockchain/pull/3710

Native multisig transactions still have a problem described in the proposal, but the overall flow can already be established, therefore we're trying to integrate our solution with Hiro

**Comment by kyranjamie** [comment]
Curious what sort of API you'd propose to interact with the wallet to sign multisig STX transactions? How might this look styled as an RPC request ?

**Comment by fess-v** [comment]
In terms of RPC calls to the blockchain, there's nothing to change in my opinion
About the wallet-browser API calls - there're two different ways
The first way will be to add parameters `numSignatures`, `publicKeys` , `nonce`, `fee` to `openContractDeploy`, `openContractCall`, `openStxTokenTransfer`
So it will work the same way as `makeUnsignedSTXTokenTransfer`  from `stacks.js` - check https://github.com/hirosystems/stacks.js/issues/1487
The only thing else is to count previous owners' signatures (!), it is really important, it won't be possible to implement multisig without it
In the issue above it is counted using the `TransactionSigner` class. Each signature makes a new hash, wrapping the previously signed information. It makes the new `curSigHash` in the StacksTransaction method, therefore we need to use it as well to make the next signature. For that, we need to add one more parameter - `curSigHash`. Of course, `nonce` and `fee` should be set only once and forwarded from the frontend application (not from the wallet itself).

```javascript
const { nextSig, nextSigHash } = nextSignature( // code from `stacks.js`, file transaction.ts, class StacksTransaction 
      curSigHash, // sent from the frontend
      authType, // multisig, this field is figured out automatically when `numSignatures` and `publicKeys` fields are set
      condition.fee, // sent from the frontend
      condition.nonce, // sent from the frontend
      privateKey // stored on the wallet side for each user
);
```
We can skip sending `curSigHash` and send only signatures and public keys array, while on the wallet side reconstruct the `curSigHash` field using signatures in their order.

```javascript
export interface TransactionAuthField {
  type: StacksMessageType.TransactionAuthField;
  pubKeyEncoding: PubKeyEncoding;
  contents: TransactionAuthFieldContents;
}

export type TransactionAuthFieldContents = StacksPublicKey | MessageSignature;
const fields: TransactionAuthField[];

// We're calling signBegin to get the initial tx hash to sign
let curSigHash = transaction.signBegin();

const publicKeys = [] // Sent from the frontend, owners public keys ordered array

fields.forEach((f, index) => {
  if (f.type === StacksMessageType.MessageSignature) {
    curSigHash = nextSignature(curSigHash, f.data, publicKeys[index], AuthType.Standard, fee, nonce)
}
});
```
Modified nextSignature method (especially for curSigHash restoring):
```javascript
export function nextSignature(
  curSigHash: string,
  signature: string, // NEW: sent from the frontend instead of signing with the private key
  publicKey: string, // NEW: sent from the frontend
  authType: AuthType,
  fee: IntegerType,
  nonce: IntegerType,
  // privateKey: StacksPrivateKey OLD: removed from this version
): {
  nextSig: MessageSignature;
  nextSigHash: string;
} {
  const sigHashPreSign = makeSigHashPreSign(curSigHash, authType, fee, nonce);

  // const signature = signWithKey(privateKey, sigHashPreSign); OLD: removed
  // const publicKey = getPublicKey(privateKey); OLD: removed
  const nextSigHash = makeSigHashPostSign(sigHashPreSign, publicKey, signature);

  return {
    nextSig: signature,
    nextSigHash,
  };
}
// We repeat this method until we get to the current wallet owner, for which we sign using a standard `nextSignature` method
```

The second way will be to add just a generic `sign transaction` method, which will allow to sign whatever transaction, while still parsing it for displaying the data from tx to users on the wallet side


```javascript
const transaction = await makeUnsignedSTXTokenTransfer({
    recipient,
    amount,
    network,
    fee,
    nonce,
    memo,
    numSignatures: 2,
    publicKeys: pubKeyStrings,
  });

  const signer = new TransactionSigner(transaction);
  signer.signOrigin(privKeys[2]); // use the same flow, but open the Hiro wallet confirmation modal to sign, returns a signed transaction
  ```

  Check the same link above
  I would go with the first approach since it seems easier and less work-demanding for the Hiro side, but anything works for apps that will utilize these APIs
  
 In the end, the transaction is not broadcasted but returned to the frontend part to receive subsequent signatures or further broadcasting  

That's a lot of text, let me know if it makes sense and if I need to clarify any part. Thanks again!

**Comment by fess-v** [comment]
Hiro should also display if it is a multisig transaction or a standard transaction IMO, but it's not that complicated to display on the frontend
Also if it's multisig - it should show the multisig address from which the transaction will be executed eventually

**Comment by fess-v** [comment]
After our discussion with @markmhx and @kyranjamie, we decided to go with something similar to signPSBT for Bitcoin

This approach works for both - multisig and standard transactions, therefore it is universal

```javascript
interface SignStacksTXRequestParams {
  stxAddress: string;
  serializedTransaction: string; // StacksTransaction().serialize(), then cast it to hex
  chainId?: ChainID; // Stacks network id - testnet or mainnet
}

const requestParams: SignStacksTXRequestParams = { ...params };

const result = await window.stacks.request('signStacksTX', requestParams);
```

On the wallet side, we need to show the confirmation modal with the parsed transaction

```javascript
const deserializedTx = deserializeTransaction(serializedTX) // can be also used to show tx details in the modal

const signer = new TransactionSigner(deserializedTx);
signer.signOrigin(privKey);

return transaction.serialize() // return the signed serialized transaction, but also need to cast it to hex
```

**Comment by kyranjamie** [comment]
Thanks for the proposal @fess-v, this API looks good to me.

- Suggest naming fully as `signStacksTransaction`
- Suggest using a string of `mainnet | testnet` rather than chain ids

**Comment by fess-v** [comment]
Thanks, @kyranjamie 
so the final version is:
```javascript
interface SignStacksTransactionRequestParams {
  stxAddress: string;
  serializedTransactionHex: string;
  network?: NetworkModes; // default is user's current network, same as for PSBT
}

const requestParams: SignStacksTransactionRequestParams = { ...params };

const result = await window.stacks.request('signStacksTransaction', requestParams);
```

Am I right? Also changed a few small things like network, serializedTransactionHex (added hex at the end for convenience)

**Comment by markmhendrickson** [comment]
@fess-v pardon my memory, but did you mention that this related Stacks.js library was a blocker for this wallet enhancement? https://github.com/hirosystems/stacks.js/issues/1487

**Comment by fess-v** [comment]
@markmhx Actually an RPC call will also make it work fine, but probably later it should be added to public libraries so other wallets can use multisig txs as well
So it's not a blocker, but just the next step

**Comment by markmhendrickson** [comment]
Sounds good! cc @janniks and @smcclellan for context
