### ISSUE TITLE
Add option to broadcast PSBTs upon finalization

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3895]
Instead of always returning to the app for broadcasting. I've heard a couple developers request this feature recently.

**Comment by mica000** [comment]
![Image](https://github.com/hirosystems/wallet/assets/119523541/f089c265-880c-4a1f-9ca7-3b00526b3c84)

Would this design work?

https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?type=design&node-id=3466-91572&mode=design&t=qBMTQLE84KCxHHM6-4
