### ISSUE TITLE
Updated dev API throws error when sending transactions https://api.dev.hiro.so

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#3909]
@markmhx   @CharlieC3

We have updated the CORS setting on the api in this environment https://api.dev.hiro.so and have been running test to confirm its working. Here is the background on the change https://github.com/hirosystems/stacks-rpc-proxy/pull/1#discussion_r1230231573. It seems to work well on the Explorer and web wallet. But when I submit a transaction with the desktop wallet I get this error, I am not able to view console to see the source could you give us some insight into the problem or would it be possible to get a debug build with console enabled I remember you had these previously when testing strange issues.

Change network to https://api.dev.hiro.so and send STX to get the error below.

<img width="1009" alt="Screen Shot 2023-06-21 at 12 38 07 PM" src="https://github.com/hirosystems/wallet/assets/49165468/a875b72c-bc5d-4da2-a678-f826b176fa1f">

**Comment by markmhendrickson** [comment]
IIRC you may need the testnet version of the wallet to configure devnet. @kyranjamie is that indeed the case, and do we have instructions available on how to download it?

**Comment by kyranjamie** [comment]
I understand this network is a dev version of a mainnet API? Commented on other thread.

**Comment by timstackblock** [comment]
Yes it is I was able to send a sucessful transaction in v4.10.0 but it errors consistently in the previous version v4.8.0 if anyone  logs a bug we can just tell them to update to the latest version. I will close the issue, just keep an eye out for complaints.
