### ISSUE TITLE
Show domain expiration date in Hiro

### ISSUE THREAD

**Issue by DeloonCasino** [blockstack/blockstack-app#3914]
Some BNS domains like .btc (5 years) or .id (every 1 year) need to be renewed.

Please make it possible in Hiro to quickly scan which domains need to be renewed at what date or preferrably in how many days. If that could be sortable by days remaining, it would be much appreciated. Otherwise users risk losing their domains and might not be able to receive funds anymore under that address.

**Comment by markmhendrickson** [comment]
Thanks for this requested! It's also reported with https://github.com/hirosystems/wallet/issues/1529 so let's continue tracking the conversation about it there 🙏
