### ISSUE TITLE
A user send ORDI and SATS (BRC-20) form unisat to Hiro and it does not show

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3928]
Just going off ordiscan.com for the address the tokens are being send from the balance is not there. I suspect an indexing issue or the user can't connect to the BRC-20 API. And I am not seeing any connections issues in the console. 

![image](https://github.com/hirosystems/wallet/assets/33360391/809d6fc0-f1ab-4dd2-b8d3-0e6f192b2eba)

![image](https://github.com/hirosystems/wallet/assets/33360391/c9ba74fc-d40e-4576-afc6-3b1e721ded8c)
https://ordiscan.com/inscription/13537171

But the address does have unprocessed inscriptions such as
https://ordiscan.com/inscription/13080929 for ordi and sats from transactions that have 500+ confirmations
![image](https://github.com/hirosystems/wallet/assets/33360391/b14d85db-c4ee-4661-ada4-1a0bfc674d90)

The BRC-20 tokens are not shown in the wallet
![image](https://github.com/hirosystems/wallet/assets/33360391/e4ab9cc8-17b3-41f5-8d09-b3b4dd30fa06)

I do not see any connection issues here:
![image](https://github.com/hirosystems/wallet/assets/33360391/9a0baa83-9cb9-4e61-ba88-511956ec8c5b)

The unisat wallet has this record of the BRC-20 tokens (received and send)
![image](https://github.com/hirosystems/wallet/assets/33360391/5717ecc8-dcea-4d57-aa69-b1239a1143f2)

**Comment by markmhendrickson** [comment]
Any idea if this has self-resolved for the user via the API side by now?

**Comment by 314159265359879** [comment]
This has not yet been resolved. I believe it is because this https://github.com/hirosystems/ordinals-api/issues/101 fix has been delayed. It looks like reindexing and API ingestion is taking more time than anticipated.

**Comment by markmhendrickson** [comment]
@314159265359879 Were you able to confirm this is still an issue or should we perhaps close out for now?

In any case, it appears as though it's an API-side issue so I'll take it off the wallet project board.

**Comment by 314159265359879** [comment]
This can be closed, the user already worked around the issue and I am not sure how to test if the reindex would have resolved it. Most other BRC-20 indexers now agree on where the balance should be at least.
