### ISSUE TITLE
Ordinals not loading on account with lots of Stacks NFT's

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3929]
Is it possible users are getting rate limited because of API use for Stacks NFT"s and that Ordinals API is not even attempted?
![image](https://github.com/hirosystems/wallet/assets/33360391/58d44ce3-9b97-4720-ab63-14c4805aa91e)

ordinal address bc1plpezxyklnvfc5jdfw7aa77uyym2sarag2v8st8djklx80v82xumqxr5crd
stacks nft address SP2RNHHQDTHGHPEVX83291K4AQZVGWEJ7WCQQDA9R

Second time someone is reporting this. 

![image](https://github.com/hirosystems/wallet/assets/33360391/eb12729e-5cb5-4186-8c0c-4a9fd485dc03)

**Comment by 314159265359879** [comment]
the user also noticed this and asked to add it here (I am not sure if it is relevant). 
![image](https://github.com/hirosystems/wallet/assets/33360391/4d8fedeb-aa89-453c-9113-53d933f78e56)

**Comment by markmhendrickson** [comment]
@314159265359879 I'm closing as stale. Please reopen if still relevant and needs investigation.
