### ISSUE TITLE
Bug with broadcast error in Ledger

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3934]
Steps to reproduce
1. Create a transaction to transfer some STX and edit the nonce to something already processed by the wallet
2. Try signing it with Ledger
3. See the error:

![image](https://github.com/hirosystems/wallet/assets/33360391/98274e35-9f8e-43fe-9978-daaea9064e8b)

The error is also displayed when a user tries to increase the fee on a transaction with a nonce that has already gotten processed. In that case for users it is not clear their transaction has a nonce issue. 

Expected behaviour as in the software wallet:
Show error "incorrect nonce"/ transaction rejected
![image](https://github.com/hirosystems/wallet/assets/33360391/d1916f27-7327-41a4-8fde-d113040c18e4)

**Comment by markmhendrickson** [comment]
@314159265359879 This seems like a P2 since Ledger users are blocked from emitting transactions with the nonces they want to edit?

**Comment by 314159265359879** [comment]
I did not see the issue earlier on a transaction with a processable nonce. But the problem of errors popping up in the Ledger wallet is more common. I am seeing more now too. Even when just clicking "the activities tab" I see this popping up:

![image](https://github.com/hirosystems/wallet/assets/33360391/7ec24a15-bc17-4ff2-a783-1e84e5eb3787)

**Comment by fbwoolf** [comment]
I don't understand the description here vs the error image? Editing a STX tx would not be an error in the Sip10 form?

EDIT: Nvm, reproduced it.

**Comment by fbwoolf** [comment]
> I did not see the issue earlier on a transaction with a processable nonce. But the problem of errors popping up in the Ledger wallet is more common. I am seeing more now too. Even when just clicking "the activities tab" I see this popping up:
> 

This is a diff error not related to the issue.

**Comment by fbwoolf** [comment]
@kyranjamie I tracked this to this line here in the Ledger routing:
https://github.com/hirosystems/wallet/blob/fa2a09729c104d8d7a6ee1cb54797ecc28d4acdd/src/app/features/ledger/flows/stacks-tx-signing/ledger-sign-tx-container.tsx#L137

Something strange is happening there when the broadcast errors with a `BadNonce`, I can't quite tell yet how to fix. For some reason, the `Sip10TokenSendForm` is rendering and then the error occurs here bc the balance is undefined:
https://github.com/hirosystems/wallet/blob/fa2a09729c104d8d7a6ee1cb54797ecc28d4acdd/src/app/pages/send/send-crypto-asset-form/form/stacks-sip10/use-sip10-send-form.tsx#L31
