### ISSUE TITLE
Seed Phrase Input Error: Firefox Browser Extension V4.34.0

### ISSUE THREAD

**Issue by GAD2511** [blockstack/blockstack-app#3954]
When inputting the Secret Recovery Key, it's not possible to jump back on a word to correct it in case a letter is missing or need to add a missing word at the beginning or in the middle with no particular position. The cursor can be placed successfully but whenever you start to edit the letter/word, It drops at the bottom of the last word inputted and the letter/word is added there.

**Comment by markmhendrickson** [comment]
Thanks for the heads up 🙏  We'll fix
