### ISSUE TITLE
Unexpected app error: scriptpubkey_address when trying to mint on Magic Eden

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3961]
A user reported this issue, popping up 1-2 weeks, but only from time to time. 

![image](https://github.com/hirosystems/wallet/assets/33360391/4476ed27-fca1-4db7-80a4-b3514eb82e99)

Based on the clipped image above Fara thought.
1. Something related to testnet/mainnet login/configuration
2. Or race condition, data isn't there yet and errors, needs further investigation to determine

![image](https://github.com/hirosystems/wallet/assets/33360391/f4475543-a66f-4901-b2e0-89f929e0cc69)

Full error would also help, I have asked the user for an unclipped version of the screenshot

**Comment by 314159265359879** [comment]
Two more users have reported seeing a similar error. I have not yet received an image of the error without clipping, but several users intend to create one when they see it again.

**Comment by fbwoolf** [comment]
@314159265359879 can you test this build? https://github.com/hirosystems/wallet/pull/4026

The code producing this error has been removed. I'm hoping this is fixed?

**Comment by fbwoolf** [comment]
This code has been removed, so I'm going to close this issue bc it is outdated. If users hit this error somewhere else in the code, pls reopen or open a new issue with more current info for repro.
