### ISSUE TITLE
Update listing price or cancel listing on Magic Eden fails with invalid signature

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3962]
![image](https://github.com/hirosystems/wallet/assets/33360391/38902e06-3ad0-4326-afc8-a9a1093f3a94)

related address bc1pxjyx7z3q5a8jl9547mxs5rv2smgpf6zgajchf92h6hpwd933u7kszrcq7w (single ordinal)

**Comment by 314159265359879** [comment]
@DeeList has tried to reproduce this error but it has not yet popped up for him.

**Comment by fbwoolf** [comment]
Is it possible here the user listed with a different account?

**Comment by DeeList** [comment]
Thank you Fara! that seems to be it...I was able to see the error when using a different account within the extension, even though I was signed in with a different account on the Magic Eden website.
@314159265359879 provided a detailed explanation addressing this user's issue:  <https://discord.com/channels/1075856098269089834/1075920122314756166/1125504560581070858> 

<img width="944" alt="error" src="https://github.com/hirosystems/wallet/assets/132958967/6a04a216-827c-4ad0-96f3-c77be8be6e4e">

**Comment by markmhendrickson** [comment]
@fbwoolf to resolve this will simply require devs like ME here to upgrade their implementation with the new account handling yea?

**Comment by 314159265359879** [comment]
> Is it possible here the user listed with a different account?

I did ask the user to make sure the active account was the same as the one in Magic Eden, I forgot to mention they need to relog. I think that is why it persisted for them. DeeList confirmed that the following workaround does resolve it:

- 1st make sure that the Wallet Extension is signed into the account you want to handle on Magic Eden. 
- Then Sign out on Magic Eden... then sign in again on Magic Eden with the account that is currently active on the Hiro Wallet Extension. You should not see the "invalid signature..." as you interact with the account.

I assume this pops up because the new [account handling ](https://github.com/hirosystems/wallet/issues/3770) hasn't been (fully) adopted by Magic Eden yet. Happy to let Fara be the judge of that assumption.

**Comment by fbwoolf** [comment]
> @fbwoolf to resolve this will simply require devs like ME here to upgrade their implementation with the new account handling yea?

Yep, def would solve this problem for users, how do we get them to update their implementation?

**Comment by DeeList** [comment]
Update on the displayed error message - 'User declined signature to ***'

<img width="452" alt="magiceden address mismatch error" src="https://github.com/hirosystems/wallet/assets/132958967/f48d2253-1294-45e5-8a60-56549064a049">
