### ISSUE TITLE
Fix max width on Stacks contract UI

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3966]
A max width is incorrectly applied on the inner container

![CleanShot 2023-07-03 at 17 19 40@2x](https://github.com/hirosystems/wallet/assets/1618764/dea04176-d9e9-4d12-b400-38d134dd93ae)

**Comment by pranjalbhatt1228** [comment]
Hey everyone, I am interested in fixing the issue. Can you please refer me to a guide to set up the project locally and get it ready for development?
I already tried the yarn commands given in the repo's readme but encountered some errors.

**Comment by markmhendrickson** [comment]
@thesixpathguy We'd be happy to help here. Mind sharing the errors you've encountered?

**Comment by pranjalbhatt1228** [comment]
Hey @markmhx, firstly I got the following warning while running `yarn install`:
Should I add these peer dependencies separately by installing each one through yarn?

![Screenshot 2023-07-10 180648](https://github.com/hirosystems/wallet/assets/68118568/f037ca50-2559-4cfc-ba3d-80b02c924bb3)

And ignoring the warnings and going ahead with `yarn dev`, I got some webpack loggings:

![Screenshot 2023-07-10 181139](https://github.com/hirosystems/wallet/assets/68118568/b106ee03-4292-4e08-b04b-5e1ca72e9b8e)

Are these warning intended or is there some problem in the way I am setting up the project?

**Comment by pranjalbhatt1228** [comment]
Also, can you please guide me on how to run the extension locally for development after setting up the project? Because I am not able to find any `/dist` directory after running `yarn dev`.

**Comment by pete-watters** [comment]
@thesixpathguy - I'm not sure what is happening on your machine. Those warnings are safe to ignore and I just setup a fresh installation of the application without any problems. 

https://github.com/hirosystems/wallet/assets/2938440/627997eb-1532-4e1a-9fc8-c02fee2c44b6


Once the APP is built successfully I can see the `/dist` folder. 

I see you are using a windows system so a suggestion could be to install the application in a folder without spaces in the name e.g. in `Development/wallet`. 

Hopefully that helps unblock you

**Comment by pranjalbhatt1228** [comment]
Hey, @pete-watters, tried exactly the same way as shown in the screen rec and in a folder name without spaces but still the same issue and no `/dist` folder. 

As well as tried in `wsl`, but there I got errors in the `yarn install` step itself. This is the error in `wsl` engine:

![Screenshot 2023-07-11 185325](https://github.com/hirosystems/wallet/assets/68118568/df31ff85-e693-4d8d-a26c-cff129c3fb9a)

**Comment by puriravindra412** [comment]
hey can you guide me and explain me the exact issue to solve and setup project locally

**Comment by pete-watters** [comment]
@thesixpathguy - thank you for reporting this problem. I have checked and there is indeed an issue running the app on Windows right now. It's a issue with the path definition in `package.json`. 

I have implemented a fix but in the meantime you can to launch the app by running the following in the route folder:
`node webpack/dev-server.js`

**Comment by pranjalbhatt1228** [comment]
Hi @pete-watters, thanks for the workaround. The app is running fine locally, and I think I am up for fixing the issue.
Can you please elaborate more on the issue and give the exact steps to reach the above mentioned UI screen.

**Comment by pete-watters** [comment]
Hi @thesixpathguy, 

The issue is that for this screen, the inner container doesn't go to the full width available:
![Screenshot 2023-07-20 at 14 04 09](https://github.com/hirosystems/wallet/assets/2938440/412c1b1a-b760-4d48-9ab5-ce6551bf385e)

We have a testing APP you can use to simulate this screen. Did you see that in the README?

You can start it by running: `yarn dev:test-app`. Then you can debug that screen as per the following:

https://github.com/hirosystems/wallet/assets/2938440/5feb30c7-2837-4b8c-95fc-cd6a2b1104da

Let me know if this helps you reproduce it or if you hit any issues along the way. I look forward to your solution

**Comment by markmhendrickson** [comment]
@thesixpathguy can you get to this sometime this week? If not, @pete-watters may need to take it on himself. 🙏

**Comment by prasad5795** [comment]
@markmhx Can I go ahead and try to fix this issue?

**Comment by pete-watters** [comment]
@prasad5795 yes please fix it if you can, thanks!

**Comment by prasad5795** [comment]
Hey @markmhx  , just want to confirm this, please see the attached screenshot, this is the expected output, right?

![image](https://github.com/hirosystems/wallet/assets/49803589/28ef8a65-5307-468f-9f4b-70ab3f16d0b5)

**Comment by pete-watters** [comment]
> hirosystems#3966

Hi, yes that's correct 👍

**Comment by pete-watters** [comment]
This was fixed by @prasad5795 , thank you!
