### ISSUE TITLE
Add option to receive modal for Stacks FTs

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3973]
Currently we don't provide an explicit option to deposit / receive Stacks-based FTs in addition to Stacks itself.

E.g. see confusion here https://www.reddit.com/r/stacks/comments/14rtuir/how_to_receive_mia_coin_in_hiro_wallet/

We should provide one somehow, though the tricky thing here may be that we don't know just what type they want to receive so can't show specific options e.g. MIA. Rather we need a generic way to label (and "Stacks FT" itself probably isn't an effective user-facing term).

cc @mica000

**Comment by mica000** [comment]
Maybe we could add a search field so they can type for the ones that are not showing by default?
<img width="1673" alt="Screenshot 2023-07-07 at 17 25 45" src="https://github.com/hirosystems/wallet/assets/119523541/fa25e0c3-0bf7-4fa0-92b8-ca01000e6228">
<img width="1315" alt="Screenshot 2023-07-07 at 17 25 21" src="https://github.com/hirosystems/wallet/assets/119523541/ae3618df-978d-4f4b-b1a7-0ff09695b439">
<img width="1652" alt="Screenshot 2023-07-07 at 17 25 04" src="https://github.com/hirosystems/wallet/assets/119523541/834ed73b-8657-44f9-bc0a-c2401d1241e7">

**Comment by markmhendrickson** [comment]
In this approach, the ones shown by default would be the ones that the user already has in their wallet presumably?

If so, we'd need a way to a query a registry or something for others that they don't already have. And the question becomes just which registry to use (our own or a 3rd party, and whether it's decentralized or not).

This approach may be most intuitive to users, though it may also risk adding a step they don't need to take in actuality (because it's the same STX address they need to use regardless of the Stacks FT in question). It's perhaps worth a discussion as a team.

**Comment by mica000** [comment]
@kyranjamie suggestion during design review a curated list of know tokens

What do we think of the list from ALEX?

<img width="289" alt="Screenshot 2023-07-12 at 16 33 19" src="https://github.com/hirosystems/wallet/assets/119523541/128f649e-bd5f-42a2-89c6-1e6da2e1b289">

**Comment by markmhendrickson** [comment]
Yep I like that approach, keeps it simpler than adding search. And ALEX's list is quite comprehensive. Should we perhaps show these at the bottom of the receive modal so they don't bump the other options far down outside of the viewport?

**Comment by markmhendrickson** [comment]
@pete-watters When you get to this issue, let's touch base with @mica000 on just how to display this extended list of Stacks FTs within the UI of the current receive modal (e.g. in terms of order).

My sense is that we could simply swap the order of the "Tokens" and "Collectibles" sections then append these Stacks FTs to the "Tokens" section (now in second place, so they extend off the bottom of the viewport with scrolling without bumping the "Collectibles" off screen):


![Image](https://github.com/hirosystems/wallet/assets/28991/84df04b1-8c5d-48bc-94f4-1c41a07e7a27)

**Comment by markmhendrickson** [comment]
A very quick, provisional solution here (in lieu of integrating a whole list of Stacks FTs, which we'd need from ALEX) would be to simply update the "Stacks" label under "Tokens" to "STX and Stacks tokens".

**Comment by fiftyeightandeight** [comment]
Hi @markmhx @kyranjamie we published an endpoint for the tokens listed on ALEX: https://token-list.alexlab.co/

**Comment by markmhendrickson** [comment]
Resolved


![Image](https://github.com/user-attachments/assets/9cbb346b-658e-40e9-84e0-7a381b34e202)
