### ISSUE TITLE
Add global app error screen

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3986]
eg https://github.com/hirosystems/wallet/issues/3897

**Comment by pete-watters** [comment]
@mica000 can you please help me to come up with a design for a nice error page? 

Currently we just dump the console to the page and there's no way for users to recover from the problem:

![Screenshot 2023-07-12 at 10 14 03](https://github.com/hirosystems/wallet/assets/2938440/0bed24de-f388-4284-9ccd-51084133b28c)

**Comment by mica000** [comment]
Designs in here: https://www.figma.com/file/Li7qK8ZIG9c5dKSNOPO4iCtv/%E2%9D%96-Design-System?type=design&node-id=5452-43698&mode=design&t=NZ4EwmI5zZnbylRG-4

**Comment by alter-eggo** [comment]
seems design is outdated, @mica000 could you redesign it please?

**Comment by mica000** [comment]
@alter-eggo @kyranjamie could you perhaps clarify the need of this redesign? Asking because in light of the approval UX, all errors are already being redesigned so I' assuming what you are asking is to redesign smt for the existing app? I'm confused because this is saying its part of the Establish UI library milestone.

**Comment by pete-watters** [comment]
@mica000  - we want to add an error screen so users don't just see white text like [here](https://github.com/leather-wallet/extension/issues/3986#issuecomment-1632146057). 

@alter-eggo did a good job of improving it but we just want to get design approval of what he did [here](https://github.com/leather-wallet/extension/pull/5003) or else feedback on what he can change.

It's part of the UI library milestone as we should have an error component in the library we can use

**Comment by alter-eggo** [comment]
@pete-watters thanks here, yeah, it is exactly what I need

**Comment by mica000** [comment]
@pete-watters @alter-eggo Sorry all the questions, but Im a bit in the dark with the urgency and context of this one given we are redesigning all errors on Approval UX right now, however is this currently blocking development and needs to be redesigned asap? 

Also in relation to this visual that was shared, will this be included in the containers work? And if so, can we use the new footer and header components on the designs?
![image](https://github.com/leather-wallet/extension/assets/119523541/9b657d5b-4e72-486b-944b-5a823252018c)

**Comment by pete-watters** [comment]
> @pete-watters @alter-eggo Sorry all the questions, but Im a bit in the dark with the urgency and context of this one given we are redesigning all errors on Approval UX right now, however is this currently blocking development and needs to be redesigned asap?
> 
> Also in relation to this visual that was shared, will this be included in the containers work? And if so, can we use the new footer and header components on the designs? ![image](https://private-user-images.githubusercontent.com/119523541/309307227-9b657d5b-4e72-486b-944b-5a823252018c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDk0NzUsIm5iZiI6MTcwOTMwOTE3NSwicGF0aCI6Ii8xMTk1MjM1NDEvMzA5MzA3MjI3LTliNjU3ZDViLTRlNzItNDg2Yi05NDRiLTVhODIzMjUyMDE4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxNjA2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzJjY2NjYjAzYzliNjZlMDUzMGNkODQyYzRhMjAxNzYyNGM2YzBkYWU4MzkyMGM4N2RmYTdmY2MxM2NhOTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.spsih37QmaC6GACtkyBNu9Db-2no6AjmPv2U5ye9tmA)

No problem at all.  This is something that @alter-eggo is adding seperately to containers. 

Right now if users hit any errors they see a page like this: 
https://github.com/leather-wallet/extension/assets/2938440/0963eae6-7d28-4179-b17e-8f5fad2b9beb

@alter-eggo just added a nicer page to show instead of this and we want to check it looks OK with you.  If you want to give a quick design with header / footer we can add that. 

So the options are:

1. We do nothing yet and fix this in Approval UX
2. If what @alter-eggo did looks OK as an interim improvement lets add that for now then improve  in Approval UX
3. If you want to give us a newer design with headers + footers we can do that instead

**Comment by pete-watters** [comment]
@mica000 @fabric-8 - do we have a new design for this somewhere in Approval UX now we can use? 

It would be great if we can just have some better handling of these pages. 

If we don't have a new design I think we should just merge what @alter-eggo did already as it's better than an empty screen and stack trace

**Comment by fabric-8** [comment]
@pete-watters In the context of approval UX, we have a general layout/design that covers errors (signing state) & failures (transaction state) [here](https://www.figma.com/file/FlmF7ropcijOb7iVSDqNn0/%F0%9F%9F%A7-Web-App-Explorations-2024-H1?type=design&node-id=2185%3A143847&mode=design&t=toYB7TkX7XwWe7Xh-1)

There's an [accompanying notion database](https://www.notion.so/trustmachines/View-error-8c677c88febf46668e64cffbf1afae56?pvs=4) outlining the copy for the various types of errors we are tracking so far.

Hope that's helpful, feel free to reach out / ping me if there are any questions or so!

**Comment by alter-eggo** [comment]
we have such new design https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=14262-121111&mode=design&t=6x2thsQaW0T2aNEr-0

I will try to implement it this week or early next

**Comment by pete-watters** [comment]
OK, sounds great 👏

**Comment by pete-watters** [comment]
Closing this off as we completed and released it
