### ISSUE TITLE
Legacy address in PSBT output gets converted?

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3993]
From Discord: https://discord.com/channels/1075856098269089834/1088095116746571786/1127176787676385331

its changing the address i pass in to addoutput. 
here i give the 1GEE.... address, but when it lands to hiro I see it got a 16PSJ.....vm4JD 
this does NOT occur at all if I use a bc1 or non legacy address, and I see the expected addresses in those cases 

I figured I could use address.toOutputScript (from bitcoinjs-lib) but it also just leads to same issue and the address changes by the time its an output on the transaction.

![image](https://github.com/hirosystems/wallet/assets/33360391/84b640aa-284e-4da5-8edf-4589f9cf87ff)

![image](https://github.com/hirosystems/wallet/assets/33360391/973b1c1a-ff14-4bf9-9bc4-8a59a186d82d)

**Comment by Iheff** [comment]
I get the same result wether I use this:

```
    txHiro.addOutput({script:bitcoin.address.toOutputScript(output.address), amount: BigInt(output.value)})
```
or this:
```
 txHiro.addOutputAddress(output.address, BigInt(output.value))
```

to create the outputs

**Comment by fbwoolf** [comment]
I don't understand how this would be an issue in the wallet, as opposed to an issue with the btc-signer lib, bc calling these methods are from: https://github.com/paulmillr/scure-btc-signer

🤔

**Comment by fbwoolf** [comment]
We don't do anything except sign the inputs and return the psbt to the app. We don't call anything that would modify the psbt. 🤔

**Comment by fbwoolf** [comment]
@314159265359879 I have been doing a bunch of tests on this today. I can't reproduce this, so maybe my most recent PSBT refactor fixed it? Can you test the most recent prod build too?

```ts
tx.addOutput({
    amount: BigInt(796),
    script: p2pkh.script,
  });
```

![Screen Shot 2023-07-27 at 3 16 32 PM](https://github.com/hirosystems/wallet/assets/6493321/f5a311eb-b528-4653-bd03-e864b422b760)

EDIT: Or, this was never a bug in our wallet and user error?

**Comment by markmhendrickson** [comment]
This report seems similar / the same: https://github.com/hirosystems/wallet/issues/4070

Though apparently resolved with this build: https://github.com/hirosystems/wallet/issues/3897#issuecomment-1651971570

**Comment by fbwoolf** [comment]
> This report seems similar / the same: #4070
> 
The images in these issues show an outdated UI, so I think they can be closed?
