### ISSUE TITLE
Transaction size on Hiro 5 times higher than on other wallet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4014]
A user sending out BTC from this address at bitcoin block height 798699 this was the balance:
![image](https://github.com/hirosystems/wallet/assets/33360391/4c162456-efe0-4e4f-a686-615a4c0fda5a)

https://mempool.space/address/bc1qzl5xt45gazvj2j4su2xdm5tftqkckgst5hhald

Strikingly there are many small UTXO's in this address. The user tries to send out 0.002 BTC, hiro wallet calculates a 27k sats fee whereas free wallet calculates a 5k sats fee. It looks like there is room for improvement in the Hiro Wallet. 

There are many small UTXO's in this wallet address, and my guess is that perhaps we do not order them from big to small when selecting which ones to send. Leading the Hiro wallet to create a transaction with many 800 sat inputs rather then leaving those and picking the big UTXO's to limit the number of inputs to keep the total transaction size smaller.  

Fee estimate in free wallet (high ~7-12 sats/vB)
![image](https://github.com/hirosystems/wallet/assets/33360391/dc1ed412-becc-4ba9-9637-b270e4a0fe28)

Fee estimate in Hiro wallet (high 8 sats/vB)
![image](https://github.com/hirosystems/wallet/assets/33360391/843a27fa-478c-4c79-9e60-9d45a12e1545)

Mempool.space around that time
![image](https://github.com/hirosystems/wallet/assets/33360391/4b397590-547a-4890-86e2-e3d9900ddbea)

**Comment by kyranjamie** [comment]
Our coin selection logic starts largest to smallest utxo value. Are we sure freewallet is the accurate one here? 

Transactions are paid for by size/amount of utxos, regardless of value of BTC. So if there are many small utxos, we expect it to have a high fee.

**Comment by markmhendrickson** [comment]
@314159265359879 I'm closing this as stale but please reopen if relevant.
