### ISSUE TITLE
Filter out URLs from token names

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4017]
To prevent scams like https://twitter.com/hirowallet/status/1678881745738018816

Related on desktop: https://github.com/hirosystems/desktop-wallet/issues/1192

**Comment by pete-watters** [comment]
@markmhx I took a look into this and it's unclear exactly what we need to do. In the desktop issue it seems like the choice is either:
- filter out urls
- do not show memo on inbound transactions

I send some transactions to start working on this but it seems like we don't show the memo in Hiro wallet right now. Is that a bigger issue we need to also resolve first?

Maybe I'm missing something though or a section of the UI they appear?

Here's a video of my wallet and some transactions I sent:
https://github.com/hirosystems/wallet/assets/2938440/26739a83-02f7-477e-b508-4de67a8385fa

**Comment by markmhendrickson** [comment]
Oops you're right. I forgot we don't even show memos in the extension wallet yet, just the desktop one 😬  

We have a separate issue here tracked for showing it: https://github.com/hirosystems/wallet/issues/2695

As such, for this specific issue, we can focus on the _token names_ specifically and not memos. These show up in the "Balances" area of the home screen whenever someone has [a SIP-010 token](https://github.com/stacksgov/sips/blob/main/sips/sip-010/sip-010-fungible-token-standard.md) in their wallet e.g. ALEX. 

You can get testnet SIP-010 tokens [here](https://app.testnet.alexlab.co/) from ALEX's testnet app once you've gotten testnet STX from the Explorer [here](https://explorer.hiro.so/sandbox/faucet?chain=testnet).

**Comment by pete-watters** [comment]
> #2695

OK great. I will take issue #2695 on my plate also then to see this through E2E.

**Comment by markmhendrickson** [comment]
@pete-watters Sounds good! Let's prioritize getting the token-name filtering out first then add support (and filtering) for memos, since we're seeing more reports of the former and it'd be good to ship a solution iteratively for it 🙏

**Comment by markmhendrickson** [comment]
`Unknown token`

**Comment by pete-watters** [comment]
@markmhx : I've added a fix for this here: https://github.com/hirosystems/wallet/pull/4113/ 

Right now I am catching URLs like:
-  www.fake
- https://www.fake
- http://www.fake
- ftp://fake.com
- https://fake.com
- http://fake.com
- fake.com
- https://www.fake.com 

I also check for the following words: 'won', 'win', 'click'

If any of those are detected the token name is replaced with `Unknown token` as per:

![Screenshot 2023-08-09 at 09 59 48](https://github.com/hirosystems/wallet/assets/2938440/e52d7bd0-490b-4f79-9113-4d5722d0640c)

I believe this should catch most current cases and we can build on it in the future. 

Unfortunately my current REGEX won't catch cases like this (url without .com): 
- https://fake
- http://fake

Let me know if you want me to prioritise trying to catch those now also

**Comment by markmhendrickson** [comment]
Nice work! 

> Unfortunately my current REGEX won't catch cases like this (url without .com):

Could we perhaps add a regex for any string that contains `http` in general?

**Comment by pete-watters** [comment]
> Nice work!
> 
> > Unfortunately my current REGEX won't catch cases like this (url without .com):
> 
> Could we perhaps add a regex for any string that contains `http` in general?

Good shout. I spent a bit longer on it and now we cover all cases including anything with a `http` / `https`

**Comment by markmhendrickson** [comment]
Reopening since messages appear to be getting through the new filter: https://github.com/hirosystems/wallet/pull/4113#issuecomment-1690628718

**Comment by pete-watters** [comment]
I got @brandonmarshall-tm  to send me a spam token and I managed to fix this pretty quickly. 

My original code was working but there was one more place to add spam filtering to that I didn't know about.
