### ISSUE TITLE
Programmatically add network

### ISSUE THREAD

**Issue by empeje** [blockstack/blockstack-app#4027]
Hey, do we have API to add new network e.g. subnet programmatically? I'd like to build similar app like https://chainlist.org/ but for Stacks-based network.

**Comment by markmhendrickson** [comment]
Thanks for the request. We're tracking this enhancement here: https://github.com/hirosystems/wallet/issues/2535

If you're interested in working on it, we'd love to review a PR that attempts to add such an API!

**Comment by empeje** [comment]
Hi @markmhx, I think that's an interesting issue to pick up. I'm not sure if I have bandwidth to do it, but will open a PR if I have.

**Comment by 314159265359879** [comment]
![Image](https://github.com/user-attachments/assets/cf8e5a4e-81e2-40a8-bb8a-fdd26011742f)

**Comment by markmhendrickson** [comment]
I'm closing in favor of https://github.com/leather-io/issues/issues/279#issuecomment-2357804473
