### ISSUE TITLE
Fix state change behavior upon selecting "Send" for inscription

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4028]
On the home screen, if I select an inscription for sending under "Collectibles, the active tab inadvertently switches to "Activity" in the background of the appearing modal then switches back to "Balances" once I close the modal, but the screen is now inadvertently scrolled to the very top so I lose my place on the screen:

https://github.com/hirosystems/wallet/assets/28991/08ef4402-e888-4c0a-adee-a6008a3a6aa5

**Comment by kyranjamie** [comment]
Assigning @pete-watters as this is related to the routing changes. Think there must be some router setting to not unmount the activity route when loading a modal?

**Comment by markmhendrickson** [comment]
@pete-watters are you working on `dev` directly here or a PR we can link to this issue?

**Comment by pete-watters** [comment]
> @pete-watters are you working on `dev` directly here or a PR we can link to this issue?

I have a PR open [here](https://github.com/hirosystems/wallet/pull/4062)
