### ISSUE TITLE
Signed PSBT be rejected by mempool.space

### ISSUE THREAD

**Issue by bolasblack** [blockstack/blockstack-app#4029]
Here is my case:

I'm trying to create a brc-20 transfer transaction. I've already inscribed a transfer inscription in my p2tr address, and the network fee will be sent from my p2wpkh address (they both belong to one Hiro account),  so I called `request('signPsbt', ...)` twice for one transaction. But after I posted this transaction, mempool.space said `non-mandatory-script-verify-flag (Witness program was passed an empty witness)`

Am I missing any steps? Could any help me to take a look?

Here is the PSBT hex:

```
70736274ff0100a602000000024f1c74b76f48f64c771c717d760409077ba881f03012ce409d7b3a9e7eb2a3ad0000000000fffffffff72f612a7c9c2977d1950babafbcbe2754dbb9f47cc9bbb64aa425d113b100080000000000ffffffff022202000000000000225120e8486d59a7b48fb5e610164b1aa6385daf319e44fc5c1ae42106bcbb3fc32af8da81010000000000160014eef61374297e242272dff5395b44ed785fb62331000000000001012b22020000000000002251204eb64b3838252e8f92ee6ef057f72688b065cf363be5b5ba42934a74f745b4060113409d228d3bd8b7b92e5a34d047987b8518dfe652644fae6bc5fe2a7cae9b0cc9607f7f31476bbb4d5e601f2df2bb363972e536c5a32029995b5595a0056d3bc0760117206cb0bc651dd4e0b303f4a006553f676d44c363716d279107a70ba6e6cfda5a610001011fa086010000000000160014eef61374297e242272dff5395b44ed785fb623312202036a0620a399171899ecce846ca740a857bad4d0c3924b3fe46e6610e3042a29eb4730440220611db1a01adc79b30d34ee051e4310ce7c232fd801ec70740c88ce52b41a4896022054284de5a437d1eecd41ae8eb801301ff4927a3cf87e87aab61ce621ac31d20301000000
```

Here is the code:

```typescript
const {
  ordinalsAddress,
  ordinalsAddressPublicKey,
  bitcoinAddress,
  bitcoinAddressPublicKey,
} = await getAddresses(window.btc)

// this is some mock code
const originPsbtHex = await createPsbt({
  inputs: [
    {
      txid: ordinalsUtxo.txid,
      index: ordinalsUtxo.index,
      witnessUtxo: {
        script: ordinalsUtxo.script,
        amount: ordinalsUtxo.amount,
      },
      tapInternalKey: getTapInternalKey(ordinalsAddressPublicKey),
    },
    {
      txid: bitcoinUtxo.txid,
      index: bitcoinUtxo.index,
      witnessUtxo: {
        script: bitcoinUtxo.script,
        amount: bitcoinUtxo.amount,
      },
    }
  ],
  outputs: [
    // ...
  ]
})

const { hex: ordinalAddressSignedPsbtHex } = handleRpcError<{ hex: string }>(
  await window.btc.request("signPsbt", {
    hex: originPsbtHex,
    publicKey: ordinalsAddressPublicKey,
    signAtIndex: ordinalWalletSignIndices,
  }),
)

const { hex: bitcoinAddressSignedPsbtHex } = handleRpcError<{ hex: string }>(
  await window.btc.request("signPsbt", {
    hex: ordinalAddressSignedPsbtHex,
    publicKey: bitcoinAddressPublicKey,
    signAtIndex: bitcoinWalletSignIndices,
  }),
)

return postTxToMempoolSpace(
  btc.Transaction.fromPSBT(bitcoinAddressSignedPsbtHex).hex
)

function getTapInternalKey(
  publicKey: Uint8Array,
): Uint8Array {
  return btc.p2tr(
    ecdsaPublicKeyToSchnorr(publicKey),
    undefined,
    btc.NETWORK,
  ).tapInternalKey

  function ecdsaPublicKeyToSchnorr(pubKey: Uint8Array): Uint8Array {
    const ecdsaPublicKeyLength = 33

    if (pubKey.byteLength !== ecdsaPublicKeyLength) {
      throw new Error("Invalid public key length")
    }

    return pubKey.slice(1)
  }
}
```

**Comment by bolasblack** [comment]
And I'm also quite hopeful that Hiro Wallet can drop the requirement for API callers to provide `tapInternalPubKey` (related to #4007) 😆

**Comment by fbwoolf** [comment]
@bolasblack would it be helpful if our api optionally had us finalize/broadcast the transaction? Where is that happening in your code? If you are using the rpc api, do you want to make sure to send us the account index to make sure the wallet is trying to sign with the right account, otherwise it will default to whatever is current in the wallet.

**Comment by bolasblack** [comment]
@fbwoolf Thanks for your reply!

> would it be helpful if our api optionally had us finalize/broadcast the transaction?

Yes it would be helpful in some other cases, but I will toggle it off in this case, as you can see, I called `signPsbt` twice in my code, cuz I need two addresses to sign this transaction.

So the most helpful thing for me currently is if the `signPsbt` can sign all my tx inputs in one call by default, it will also be quite helpful to improve our user experience (cuz currently it needs users to confirm twice) (and hopefully it will not need us to provide any other input data more than `txid`, `index`, `witnessUtxo.script`, `witnessUtxo.amount` if possible)

**Comment by fbwoolf** [comment]
> 
> So the most helpful thing for me currently is if the `signPsbt` can sign all my tx inputs in one call by default, it will also be quite helpful to improve our user experience (cuz currently it needs users to confirm twice) (and hopefully it will not need us to provide any other input data more than `txid`, `index`, `witnessUtxo.script`, `witnessUtxo.amount` if possible)
>
Is there another api you are working with that is more ideal? How can we change ours to be more helpful?

**Comment by fbwoolf** [comment]
Also, do you finalize the tx anywhere?

**Comment by bolasblack** [comment]
> Is there another api you are working with that is more ideal? How can we change ours to be more helpful?

Thanks so much for your asking! Yeah I hope Hiro Wallet can also provide an API like

```typescript
sendInscription(receiverAddress: string, inscriptionId: string): Promise<{ txId: string }>
```

And can still provide `signPsbt`, but with the function "`can sign all my tx inputs in one call by default`" (and other wish I mentioned above 😆 )

**Comment by fbwoolf** [comment]
We do sign all inputs if you don't provide the indexes array.

**Comment by bolasblack** [comment]
> We do sign all inputs if you don't provide the indexes array.

But I saw I have to provide one public key when signing, but what if I have two inputs from different addresses (both belonging to the same account)?

<img width="695" alt="image" src="https://github.com/hirosystems/wallet/assets/382011/e68bad1d-736a-4e58-bd82-f1ff3c32ac68">

**Comment by bolasblack** [comment]
> Also, do you finalize the tx anywhere?

😱it works, previously it was not working and threw me some errors, I checked the tx data and thought maybe Hiro Wallet finalized it for me automatically. Damn, it could be that I didn't pass the parameters correctly somewhere before.

Anyway, Thanks so much for your help!

**Comment by fbwoolf** [comment]
> > We do sign all inputs if you don't provide the indexes array.
> 
> But I saw I have to provide one public key when signing, but what if I have two inputs from different addresses (both belonging to the same account)?
> 
> <img alt="image" width="695" src="https://user-images.githubusercontent.com/382011/254596224-e68bad1d-736a-4e58-bd82-f1ff3c32ac68.png">

@kyranjamie what do you think about changing the api here to accept addresses rather than an account index? I noticed the Xverse api accepts an address to sign specific inputs so that the request here in question could be done  with one tx.

**Comment by bolasblack** [comment]
Yes, then as developers we can sign tx like this (and users will no longer have to confirm one transaction twice as well):

<img width="722" alt="image" src="https://github.com/hirosystems/wallet/assets/382011/c8b19824-cd7c-43ce-92d1-944a7f352669">
