### ISSUE TITLE
Selecting standard fee broken in send flow on Firefox when sending BRC-20

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4034]
Reproduction steps:
1. Click send
2. Select a BRC-20 token
3. Add the amount and click next
4. Then select the fee
5. And see this error:
https://github.com/hirosystems/wallet/assets/33360391/b7ac230f-1870-4835-b4b3-1f3f95d71edd

The console shows:
![image](https://github.com/hirosystems/wallet/assets/33360391/1fcf4147-d647-44b2-938b-c93fa945e47c)

Not sure if this is more general, I have not seen this on Chrome. Have not tested it yet with sending BTC or Ordinals.

**Comment by alter-eggo** [comment]
hm, tested on Firefox and it works ok for me. @314159265359879 can you send user btc address please?

**Comment by 314159265359879** [comment]
@alter-eggo the user is seeing it with these accounts, right now the user has to set a custom fee otherwise the balance is insufficient to cover the fee. After setting it low enough the "fee selection" screen shows again (and again if repeated) instead of going to review. 
bc1qpyn72nr75rjeh3a66cff40fagm34yeevdra9kq
bc1pxea22ukw37kuq5682shqwzvpkgn3aw0pw9jh36syktp08v2v2vnqxfe0zz

**Comment by markmhendrickson** [comment]
@314159265359879 any more reports of this, or best to close out for now?

**Comment by 314159265359879** [comment]
No other reports lately and I haven't seen it either, I believe this has been resolved. Closing.
