### ISSUE TITLE
White square popup before wallet extension window shows (software chromium wallet)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4046]
This was introduced with 5.0.0
This is when you are signed in and the wallet is unlocked, only on chromium based browsers in software mode. 

![image](https://github.com/hirosystems/wallet/assets/33360391/6b9f25de-1a89-494e-8712-24357b344d33)

https://github.com/hirosystems/wallet/assets/33360391/7e31039d-2864-4966-b27f-0718ed603074

**Comment by markmhendrickson** [comment]
@314159265359879 are you still seeing this by chance? I don't personally in the latest version

**Comment by 314159265359879** [comment]
@markmhendrickson this has indeed been resolved, I have not seen this for a while now.
