### ISSUE TITLE
Create issues in milestone for integrating monorepo into extension

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4050]
This task is to start work on the mono-repo. It will involve:
- planning we need
- researching options
- testing out and performing a SWOT analysis on options
- defining a roadmap and timelines for implementation

**Comment by pete-watters** [comment]
I have completed analysis of the options available and my recommendation. 

The next step is to discuss it with the team and come up with a plan and timelines around it

**Comment by markmhendrickson** [comment]
@pete-watters to create issues for milestone that map to entire integration of mono-repo into extension

**Comment by pete-watters** [comment]
I created a doc based on my research here: 
https://www.notion.so/trustmachines/Improve-code-sharing-monorepo-4e89155d2b3e4442bc010f71223efadb

**Comment by pete-watters** [comment]
I added 4 more steps to take this monorepo along. I think that's the most we can really plan ahead for now until we take those steps and decide how best to handle code sharing between platforms
