### ISSUE TITLE
Simplify suggested first steps feature

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4058]
I love the feature we have to help onboard users that shows when first creating a wallet. But, doing some other work that touches some of the related hooks, believe we tried to over-optimise and over-engineer a solution.

<img width="1797" alt="image" src="https://github.com/hirosystems/wallet/assets/1618764/b3b178de-f3a0-48a4-816f-b9f667613190">

There is _so much code_, simply to add the functionality that: 

_if the user's account has activity, don't display the suggested steps_

We have a whole system in place to check the first 5 accounts STX balance, check their NFTs etc.

The effort-to-value ratio doesn't make sense. Let's just show it every time, because 
1) Install/restoring a wallet isn't an every day action
2) We aren't at a place where we can spend developer-hours optimising for one fewer one-time-per-install clicks

**Comment by markmhendrickson** [comment]
Agreed let's keep this simple and just show upon installation each time, even if the user is restoring an actively used wallet.

Related re: overhauling this UX in general: https://github.com/hirosystems/wallet/issues/3839

**Comment by kyranjamie** [comment]
This will help with Ledger work, so let's prioritise for next week if we can
