### ISSUE TITLE
Enabling wallet extension doesn't register on website until refresh

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/blockstack-app#4064]
## Background

I use both the Hiro wallet and Xverse wallet extension in my browser. Both are set to only allow usage on a website when the extension is clicked on.

This occurred for me today on two Stacks websites that I use regularly, not sure if it's related to the latest version or if it's a downstream issue with Stacks.js/micro-stacks.

Figured I'd start here first since I am not seeing the same issue with Xverse wallet - it still works as expected.

## Expected flow

1. Click to login on website - receive error no wallet installed
2. Click to enable wallet extension
3. Click to login on website - successful pop-up
4. Continue per usual

## What happens now

1. Click to login on website - receive error no wallet installed
2. Click to enable wallet extension
3. Click to login on website - receive error no wallet installed
4. Refresh website
5. Click to login on website - successful pop-up
6. Continue per usual

**Comment by markmhendrickson** [comment]
Did this change in behavior happen about a week ago? We pushed live support for Manifest v3 which may have caused an underlying change in behavior here re: how the extension gets recognized upon activation.

Also note that work has been going on to resolve these collisions so you don't have to deactivate and reactivate:

https://github.com/hirosystems/connect/pull/326
https://github.com/secretkeylabs/sats-connect/pull/14

**Comment by whoabuddy** [comment]
Possibly, although I think I would've noticed it right away based on a few things I'm working on.

On my laptop I still had 5.0.0 (slow auto-update, or intermittent connection maybe?) and it worked as expected.

Working around it for now with a refresh but great to hear there's progress on the provider collisions!

I actually prefer to keep the extension on click to activate so I'm not turning it on unless I plan to use it.

**Comment by markmhendrickson** [comment]
It looks like @kyranjamie may have just resolved this issue here? https://github.com/hirosystems/wallet/pull/4068

**Comment by markmhendrickson** [comment]
Just to confirm, were you using Firefox or Chrome?

**Comment by whoabuddy** [comment]
Chrome/Brave

**Comment by whoabuddy** [comment]
I'm using 6.2.1 and the behavior is working as expected again! If I click to enable I no longer have to refresh.
