### ISSUE TITLE
Sending STX/SIP10 with Ledger fails with "sending bitcoin is temporary disabled" error

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4083]
![image](https://github.com/hirosystems/wallet/assets/33360391/820ab37f-4b0b-4864-8b69-e2bc5204d6cb)

This is affecting any Ledger user. A viable workaround seems to be to use https://sendstx.com to send STX. For other tokens I think Ledger users best wait for a fix unless they are familiar with calling the token contract directly using the Explorer sandbox. 

**Steps to reproduce**
1. Restore wallet with Ledger
2. Click Send
3. Choose asset: Click STX or a SIP010 token to send
4. See error (screenshot above).

**Comment by Lapy71** [comment]
Hello, I have initiated this topic on Discord due to an issue to send STX from my Hiro wallet and a guy werner.btc has launched this topic on Github. I tried again but I have always the same message, impossible to send STX. My version is 6.2.0 I have installed my extension chrome wallet + ledger with this link [chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.html#/get-started](url)
Many thanks for help

**Comment by Lapy71** [comment]
Sorry but I have only STX (see attached doc) that I try to send and that's not possible with error as described , thanks by advance for your help
<img width="1081" alt="Capture d’écran 2023-08-03 à 13 01 43" src="https://github.com/hirosystems/wallet/assets/92605171/17aab047-9730-447b-8ac9-877462610b23">

**Comment by 314159265359879** [comment]
@Lapy71 there is a fix for this in version 6.2.1 of the wallet. This has been released but is pending review by the extension store for Chrome. Once accepted your wallet is expected to update automatically within a couple hours or you can force it with a restart of the browser.

**Comment by Lapy71** [comment]
Thanks Werner
I will update the chrome wallet extension and check if the version is 6.2.1
Many thanks for your help
Have a nice weekend
Regards

**Comment by Lapy71** [comment]
Hey Werner, I have updated my chrome wallet.
I made a simulation with address and memo and and that's run Ok now, no error. 
Many many thanks for your great help and speed for acting best regards
