### ISSUE TITLE
Wallet always opens to Balances tab

### ISSUE THREAD

**Issue by badonyx** [blockstack/blockstack-app#4086]
Previously the wallet would open to whichever tab (Balances or Activity) you had used last. Now it only opens to the Balances tab every time. This is annoying because the Activity tab is generally more useful to check on the status of transactions.

**Comment by kyranjamie** [comment]
As a work around for now, you could make a bookmark pointing to the `/activity` page

**Comment by markmhendrickson** [comment]
Thanks for the report @babonyx, we'll get this resolved. Perhaps related work: https://github.com/hirosystems/wallet/issues/4028

**Comment by pete-watters** [comment]
Thanks @babonyx , I will be fixing this soon. 

This is indeed related to https://github.com/hirosystems/wallet/issues/4028
