### ISSUE TITLE
Investigate test reliability

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4089]
Our Playwright tests are often failing at the `Post run action/cache` step citing _This operation was cancelled_ (when it wasn't manually). Some reports say this might be memory related. 

<img width="1722" alt="image" src="https://github.com/hirosystems/wallet/assets/1618764/9a4c7058-c350-44a4-8fd2-3bd00a8d9fcb">

[_Example run →_](https://github.com/hirosystems/wallet/actions/runs/5737188117/job/15548315666?pr=4087)

This is problematic in that otherwise successful tests often fail, requiring developers to rerun failed tests. A huge productivity hit.

This issue to to investigate the problem, and try some alternative solutions to remedy the problem. Perhaps we can play with cache settings, have more or fewer job matrices etc

**Comment by pete-watters** [comment]
Closing this to merge with https://github.com/leather-wallet/extension/issues/3919
