### ISSUE TITLE
openPsbtRequestPopup throws unknown address type

### ISSUE THREAD

**Issue by mijoco-btc** [blockstack/blockstack-app#4109]
Hiro Web Wallet 6.2.1
Browser Chrome, Firefox

This PSBT uses segwit address for inputs and pays to the taproot sBTC Alpha wallet (tb1qrjgzx3w697f65cz9qdxrsxs0v35ypqk7mqmm9v) triggers the (Unknown address type) error below;

70736274ff0100a00200000001782ba5d65b8551a99228b8d77e4989cf6ef6a197827d13b6d1dc3e8ba3d8e77f0100000000ffffffff0300000000000000001a6a1858323c1a7010183fd1a76976e7b2bb67acdf57cdfe704882dd89000000000000225120b8c8b0652cb2851a52374c7acd47181eb031e8fa5c62883f636e0d4fe695d6caecd70c000000000016001409c7efcd51a08da9b4e38345645866c2a270eb39000000000001011fb7700d00000000001600141c902345da2f93aa6045034c381a0f64684082de00000000

But loads and allows signing with Electrum.
<img width="1217" alt="Screenshot 2023-08-08 at 13 49 24" src="https://github.com/hirosystems/wallet/assets/4384929/c3221522-03da-4ebe-8588-464a6bd2db2a">

Also tried with this PSBT using wallets cardinal address for inputs with. Throws same error in wallet but loads fine in Electrum

70736274ff0100a002000000017ab0408cd8a95eb821244c67f4924b00c44a4567ca9954cc97d08cddd3e84ef10000000000ffffffff0300000000000000001a6a1858323c1a7010183fd1a76976e7b2bb67acdf57cdfe704882dd89000000000000225120b8c8b0652cb2851a52374c7acd47181eb031e8fa5c62883f636e0d4fe695d6cac42b0f000000000016001409c7efcd51a08da9b4e38345645866c2a270eb39000000000001011f95c40f000000000016001409c7efcd51a08da9b4e38345645866c2a270eb3900000000

```
Unexpected Application Error!
Unknown address type=unknown
Error: Unknown address type=unknown
    at Object.encode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:194768:19)
    at getAddressFromOutScript (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:43693:93)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:20333:76
    at Array.map (<anonymous>)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:20328:42
    at Object.useMemo (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:142995:189)
    at exports.useMemo (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:147846:208)
    at useParsedOutputs (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:20328:27)
    at useParsedPsbt (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:20469:25)
    at PsbtRequestDetails (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:21266:7)
    at Xh (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:142978:137)
    at Wk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:143101:337)
    at Vk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:143091:389)
    at Uk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:143091:320)
    at Jk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:143091:180)
    at Ok (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:143082:88)
    at Fk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:143084:300)
    at jg (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:142938:105)
    at Xk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:143094:470)
    at Qk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:143092:398)
    at Hk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:143081:269)
    at J (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:155372:203)
    at MessagePort.R (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/997.js:155373:128)
```

**Comment by mijoco-btc** [comment]
Note I changed the taproot output address to a segwit v0 and get the same error.

Also checked to ensure the wallet and app are connected to the same account on same network.

**Comment by mijoco-btc** [comment]
Update.. I just tried signing a psbt from a different application and the error was not thrown - investigating this now..

**Comment by mijoco-btc** [comment]
Still seeing this in v6.3.1 .

**Comment by markmhendrickson** [comment]
Are you seeing the same error with the same PSBT in other wallets?

**Comment by mijoco-btc** [comment]
Xverse works with p2sh address.

Electrum is able to display the transaction given the psbt hex. 

I thought I saw it working after a wallet update a few days ago but get the same error now.

**Comment by markmhendrickson** [comment]
> Xverse works with p2sh address.

Is it able to sign the exact payload though?

**Comment by mijoco-btc** [comment]
Xverse  [signs and sends](https://mempool.space/testnet/tx/56ef6e5439e442dfb86558de93f274482bfca9cae98ab4ba1b742eda065e0add) on first attempt but fails on second - perhaps because I couldn't work out the right redeem script.

**Comment by mijoco-btc** [comment]
Tested with segwit address in Electrum and able to [sign and broadcast](https://mempool.space/testnet/tx/149655c1f82c19173e699f5dc1b1c323faac26cedb5a86adaf42fad7bb5c2743)

**Comment by mijoco-btc** [comment]
@markmhx is this an underlying bug in scure-btc-signer ?

**Comment by mijoco-btc** [comment]
Hi @fbwoolf, does this problem originate in scure-btc-signer ?

Can you raise an Issue for Paul if so please ? It's hard for us to do this without knowing the internals of the wallet interaction with Millers code and this is high priority right now as its effects the upcoming release of sBTC.

NB @kenrogers !

**Comment by fbwoolf** [comment]
> Hi @fbwoolf, does this problem originate in scure-btc-signer ?
> 
> Can you raise an Issue for Paul if so please ? It's hard for us to do this without knowing the internals of the wallet interaction with Millers code and this is high priority right now as its effects the upcoming release of sBTC.
> 
> NB @kenrogers !

Yes, this is hitting an error in the btc-signer lib. I have opened an issue before with this and it was closed by Paul. See the thread here: https://github.com/leather-wallet/extension/issues/3897

**Comment by fbwoolf** [comment]
It is hitting the error here: https://github.com/paulmillr/scure-btc-signer/blob/47f7ab9fdaba59166bc0ac7746681923e206eef8/index.ts#L1485

**Comment by mijoco-btc** [comment]
Thanks for the info - I'll read it through carefully.

**Comment by fbwoolf** [comment]
We basically just call this method to display the input and output addresses in the UI, and it errors on `btc.Address().encode()`.
https://github.com/leather-wallet/extension/blob/3b7bc460905e0a9a1d7ce30867e8470de2e0d453/src/shared/crypto/bitcoin/bitcoin.utils.ts#L64

**Comment by fbwoolf** [comment]
Xverse is basically doing the same thing, so not sure how would work there but not with our wallet?
https://github.com/secretkeylabs/xverse-core/blob/5cab1f1e24825e4e8114b0e5c41aef6aa23dd4f4/transactions/psbt.ts#L260

**Comment by fbwoolf** [comment]
@radicleart I loaded your hex into our test-app and hit your error. In my console I can see that one of your outputs has a script type as `unknown`, so that is why it hits that error trying to get the address form Paul's encode method...

<img width="458" alt="Screen Shot 2023-09-01 at 9 56 16 AM" src="https://github.com/leather-wallet/extension/assets/6493321/ad89b540-2c14-44c4-a811-47102ef29cc5">

<img width="897" alt="Screen Shot 2023-09-01 at 9 56 06 AM" src="https://github.com/leather-wallet/extension/assets/6493321/724025d1-d089-48d9-b5dd-c92630bd6144">

**Comment by mijoco-btc** [comment]
Yes was just discovering this as well. The first ouput is op_return as per the sBTC spec.

**Comment by radicleart** [comment]
Should this prevent signing ?

**Comment by mijoco-btc** [comment]
I'm also pretty sure this was working earlier in the project maybe back in May time?

**Comment by mijoco-btc** [comment]
yes so the error is in here - can't get an address for unknown type ?

```
	if (outputScript.type === 'unknown') {
	  return btc.Address(net).encode({
		type: outputScript.type,
		script,
	  });
	}
```

in /bitcoin.utils.ts ?

**Comment by fbwoolf** [comment]
We have to handle 'unknown' here or we get a type error, but it errors in btc-signer bc the type is unknown. It looks like in the code you can try to use an option `allowUnknowOutput` (which appears to be a misspelling?), but not sure here. You can ask in btc-signer lib repo for clarification.

**Comment by mijoco-btc** [comment]
Ah yes - looks like he deprecated `allowUnknownOutput` in favour of `allowUnknownOutputs` in recent update.

Will update everything and let you know - thanks !

**Comment by mijoco-btc** [comment]
@fbwoolf allowUnknow(n)Output(s) doesn't get transferred to the PSBT (see transaction.toPSBT()) so these flags are not passed to the wallet. Also Miller's Address encoder doesn't look at that field and assumes the script passed is an address;

```export function Address(network = NETWORK) {
  return {
    encode(from: P.UnwrapCoder<typeof OutScript>): string {
      const { type } = from;
      if (type === 'wpkh') return programToWitness(0, from.hash, network);
      else if (type === 'wsh') return programToWitness(0, from.hash, network);
      else if (type === 'tr') return programToWitness(1, from.pubkey, network);
      else if (type === 'pkh') return formatKey(from.hash, [network.pubKeyHash]);
      else if (type === 'sh') return formatKey(from.hash, [network.scriptHash]);
      throw new Error(`Unknown address type=${type}`);
    },
```

Is `bitcoin.utils.ts : getAddressFromOutScript` method is only used in `[use-parsed-outputs.tsx]` for display purposes so maybe it can return 'unknown' for op_return outputs ?

**Comment by fbwoolf** [comment]
@radicleart Thx for trying, it should run through `normalizeOutput` here and hit this: https://github.com/paulmillr/scure-btc-signer/blob/47f7ab9fdaba59166bc0ac7746681923e206eef8/index.ts#L2016

But, when I search for that option in his code, that is the only existence of `allowUnkownScript` so that seems odd. 🤔 I had originally read that as `allowUnknownOutput` and thought it would be handled.

I think we can prob do what you suggest, I can at least put up a PR so you can test the build and get feedback from our lead engineer on the change. cc @kyranjamie

EDIT: Though it is erroring on a UI display of the address, I wonder if it will error again in his lib when we try to sign it though. 🤔 ...will check his code.

**Comment by fbwoolf** [comment]
@radicleart I made a PR you can test with the change. I was able to get past the error with your hex posted above.
https://github.com/leather-wallet/extension/pull/4168

Link to build: https://github.com/leather-wallet/extension/actions/runs/6052120932

<img width="461" alt="Screen Shot 2023-09-01 at 12 03 47 PM" src="https://github.com/leather-wallet/extension/assets/6493321/b863fca9-1a0a-4da7-8535-d0ab79d6371c">

**Comment by mijoco-btc** [comment]
Awesome thank you - will test it over the weekend !

**Comment by mijoco-btc** [comment]
Looks good to me @fbwoolf. Thanks again !

**Comment by markmhendrickson** [comment]
@radicleart Mind providing more context on your use case here for @mica000 so she can verify whether the above UI approach is ideal for it, or whether any modifications might make sense for user clarity?

Also @btcopenstamp, I believe the above change will unblock your needs on https://github.com/leather-wallet/extension/issues/3897. Can you confirm if that's the case, and whether the above UI approach makes sense in your mind – or whether you'd expect the user to need a different sort of presentation while signing?

**Comment by mijoco-btc** [comment]
Hi Mark, yes the use case is deposit / withdrawal from sBTC protocol use op_return to store the payloads. Transaction generated by sBTC bridge are likely to have a mixture of outputs of type 'unkown' along with spendable outputs. The issue here was that yhe wallet tried to display an address for usability purposes for each output but unknown output have no address. 

I think Fara solution of labelling them unknown works but might be confusing for users. They could be labelled 'data' or 'unspendable' etc. Not my forte!

**Comment by fbwoolf** [comment]
Would it make sense at all just to hide those outputs completely bc they would still be available to see in the advanced view of the raw psbt?

**Comment by mica000** [comment]
Thanks for clarifying @radicleart! 

Would be possible to know what do you mean when you mention 'unspendable' or 'data'? 

In add, I also agree with @fbwoolf proposal, if they are not adding to the total, couldn't they only appear on the advance mode?

**Comment by mijoco-btc** [comment]
Hey @mica000 - Bitcoin allows unspendable outputs (signified with the OP_RETURN op code). They generally have a value of 0 and allow an 80 byte payload of data that is meaning full to some external protocol - sBTC in my case.

I also agree with @fbwoolf solution to hide these outputs. This makes sense as they don't move BTC around and the details are still available in the other tab.

**Comment by fbwoolf** [comment]
@markmhx are you ok with ^ solution? Just hiding those outputs in the details view?

**Comment by markmhendrickson** [comment]
Yep I'm okay with simply hiding if we don't expect the user to benefit from seeing it

**Comment by fbwoolf** [comment]
Updated in the PR and going to get it merged today, will be in next release. @radicleart, thx for the feedback on this!

<img width="450" alt="Screen Shot 2023-09-15 at 12 09 49 PM" src="https://github.com/leather-wallet/extension/assets/6493321/e3f1c538-783d-493a-86e2-8e1b41267b4b">

<img width="454" alt="Screen Shot 2023-09-15 at 12 10 03 PM" src="https://github.com/leather-wallet/extension/assets/6493321/b26958d3-38ae-4a88-920d-7371b593e5cd">
