### ISSUE TITLE
After clicking confirm with any PSBT on ME the window stays open yet sends the transaction

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4121]
One of the devs at Magic Eden reported this. 

![image](https://github.com/hirosystems/wallet/assets/33360391/8cb7f743-a43c-4dd0-b234-cf1810525b74)

**Comment by markmhendrickson** [comment]
This is just happening on signet?

**Comment by 314159265359879** [comment]
This is more common than we thought. I am able to reproduce the issue on mainnet too now. 

To reproduce
Visit magiceden.io
Go to Bitcoin assets
Buy any Ordinal inscription
When you click to confirm the window stays open but the transaction is send. 

See it here (video):
https://github.com/hirosystems/wallet/assets/33360391/4e576053-3d6c-4636-a94b-f60df322e1a5

**Comment by markmhendrickson** [comment]
@fbwoolf Might the recent broadcasting parameter work have inadvertently caused this for (some) cases in which the app does _not_ request broadcast?

**Comment by fbwoolf** [comment]
> @fbwoolf Might the recent broadcasting parameter work have inadvertently caused this for (some) cases in which the app does _not_ request broadcast?

The video shows a notification of theirs, not sure how that would be triggered on our end? The broadcast parameter isn't required and it is checked here for the broadcast to occur: https://github.com/hirosystems/wallet/blob/99539d9af0e4c162802fe5efd3f741fcd893422b/src/app/pages/rpc-sign-psbt/use-rpc-sign-psbt.tsx#L112

**Comment by fbwoolf** [comment]
Also, is ME using the rpc request? Bc this was only added to the rpc request.


EDIT: It seems odd to me no one else is reporting if on our end? When we broadcast it, we navigate to either the tx summary or an error page. 🤔

**Comment by fbwoolf** [comment]
Would be helpful here to know any errors in the console of either ME or the wallet popup.

**Comment by fbwoolf** [comment]
I understand now the bug is just the window staying open, not that we are broadcasting the tx.
