### ISSUE TITLE
Placeholder not displayed for ordinals that have been embedded by another site

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4123]
A user reported that this Ordinal (and ordinals like it) are not displayed in the Hiro Wallet:
https://ordinals.hiro.so/inscription/14effa0e0a947cc05cab869d50626cdaf2ad1cbc05f81dbc8d99cb763116f117i0

On ord.io it is displayed like this:
https://www.ord.io/bc1pd4fjc9cyg8wfgc3x7d3pcxc99tmn6vqw5gstp6hhmputm06rw2tqdqdtxd

If it isn't displayed for security reasons on ordinals.hiro.so, do we still expect a placeholder image to be displayed in the wallet? I was unable to verify that that is the case.

**Comment by 314159265359879** [comment]
![image](https://github.com/hirosystems/wallet/assets/33360391/0cfb3f26-e4aa-47bd-8858-eba5b1e89dc2)

**Comment by markmhendrickson** [comment]
Let's tackle this with https://github.com/hirosystems/wallet/issues/4077
