### ISSUE TITLE
Fix display of "Double spend" of inscription

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4126]
![CleanShot 2023-08-14 at 10 38 39@2x](https://github.com/hirosystems/wallet/assets/1618764/09f18d53-c79a-4c3a-add0-03010e727c9a)

Last Friday [I sent an inscription](https://ordinals.hiro.so/inscription/1b723236ad06cd5dc40a153af8db1d786d7f134e8f9d1a568f9ca89be1859e1fi0) from Account 1 → 2. 

I want to test sending it again, so I sent my full balance to account 1 → 2 to fund account. On broadcast of this tx, the UI showed that I sent the inscription again.

Note that after getting mined this tx looks as expected 

<details>
<summary>When mined</summary>

<img width="800" alt="image" src="https://github.com/hirosystems/wallet/assets/1618764/ac4d23f5-e5ff-4cd9-b5ca-7242e2849c67">

</details>

**Comment by markmhendrickson** [comment]
This is a display bug, not anything deeper, correct?

**Comment by kyranjamie** [comment]
Duplicate of #5079

Seems like a filtering issue cc/ @alter-eggo
