### ISSUE TITLE
Mac user unable to click confirm for Stacks transactions

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4128]
I expect this is caused by some local configuration option because we haven't seen more then one of these reports but it is persistent for the user. However the user switching back to her older MAC did have the same issue even though it worked prior on her old mac. 

Connecting the wallet with Bitcoin and signing to confirm account ownership (arbitrary message signing) worked without issue. Singing an arbitrary message on Stacks also worked without issue when connecting to gamma.io or alexlab.co

Clicking confirm here is impossible:

![image](https://github.com/hirosystems/wallet/assets/33360391/fd13ce25-d2ff-412c-a573-e9f471bb8264)

Trying to sign a transaction to list an NFT, or to swap tokens on alexlab.co has not worked for over a month now. 

On a call with the user we checked the console but there were no errors displayed. 

Current wallet version is 6.3.1, first reported with wallet version 4.35.0

**Comment by 314159265359879** [comment]
Mouse pointer is not changing to a hand when hovering over the button. Is that expected?

**Comment by 314159265359879** [comment]
Additional info the user also tried on different browsers (Chrome and Brave) with no other extensions active. 

Checked if there was an element over the confirm button, but it doesn't look like it:
![image](https://github.com/hirosystems/wallet/assets/33360391/1ba854b8-3cf2-4560-b85d-7dd25b49bf5c)

**Comment by markmhendrickson** [comment]
It's a bit unclear looking at this screenshot whether the elements inspection was able to confirm there was no overlapping element. Did you try right clicking on the confirm button and selecting "Inspect element", and was the confirm button's element indeed the one that showed up in the elements view on the left-hand side?

**Comment by 314159265359879** [comment]
I think we did that wrong, I am going to check it again taking those steps exactly.

**Comment by 314159265359879** [comment]
This is what it look like for the user after clicking inspect element:
![image](https://github.com/hirosystems/wallet/assets/33360391/92a1ac64-d295-4c00-8099-eadcd9c5339f)

**Comment by markmhendrickson** [comment]
@314159265359879 any more reports of this? I suspect it was an issue due to this particular user's system

**Comment by 314159265359879** [comment]
@markmhendrickson I have not seen any other reports like this since.
