### ISSUE TITLE
Add input validation to Secret Key entry per BIP 39

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4130]
https://www.blockplate.com/pages/bip-39-wordlist

**Comment by pete-watters** [comment]
I have a working prototype of this in review now @markmhx. Here's how its looking:

https://github.com/hirosystems/wallet/assets/2938440/c5e348dc-b801-4816-9265-15483ded9e51

It's generally OK but has some room for improvement:
- We need to decide on an error message, I just added `Not a valid BIP39 word` for now
- When there is an error
    - The gap between input rows is too big and looks weird
    - The error icon and text aren't aligned (this is an APP wide bug to solve) 
- When you paste a full mnemonic key, it works but it doesn't yet give the user the visual impression of filling in all of those input fields

I can play with the styling more but if we plan to re-design this section and we aren't in a rush we could improve it then. This concept is proven at least now and we should be able to build on this to add type-ahead suggestions also

**Comment by 314159265359879** [comment]
if a word fails (not valid) is it possible not to hide it?

any chance we can get suggested words while the user types? That makes it even easier to identify mistakes. And it helps users who only wrote the first four characters of their words (which is already unique and sometimes used on metal backups)

**Comment by pete-watters** [comment]
@markmhendrickson this is getting close now. I just need to fix some failing tests and iron out bugs in the typeahead. 

Here's a demo of how it's looking so far:
https://github.com/leather-wallet/extension/assets/2938440/771f2ddd-51e9-4372-8a7e-d5983822d5b9

I got basic typeahead working but it's not pretty and buggy so will fix that ASAP (clicking a button shows a filtered list of BIP words based on what you have entered):

https://github.com/leather-wallet/extension/assets/2938440/7d84cb0c-37fe-463d-a459-0e06c735ae8a

CC @fabric-8 @mica000

**Comment by fabric-8** [comment]
Very nice! 

Curious to see how/when type-ahead can be triggered and how it'll feel when typing in the key. 
Btw, are you aware of any products already doing this? Maybe that's a good proxy to get a better feel

**Comment by pete-watters** [comment]
> Very nice!
> 
> Curious to see how/when type-ahead can be triggered and how it'll feel when typing in the key. Btw, are you aware of any products already doing this? Maybe that's a good proxy to get a better feel

Thanks. 

I have the typeahead working on the input but I need to resolve issues between our form tool - `Formik` and either radix dropdown for typeahead / a custom solution. 

I just have the button there for now. If you have time can you please review the work so far here? https://github.com/leather-wallet/extension/pull/4243 

Just in case I missed something style wise. 

FYI, I made the `Your password` panel a bit wider here. I can add a margin around it if it's too big. I just wanted to stop the content jumping around as mentioned before

![Screenshot 2023-09-28 at 08 46 34](https://github.com/leather-wallet/extension/assets/2938440/ef64a391-63e3-4a7e-9871-10270f7b2a5c)

**Comment by pete-watters** [comment]
@fabric-8 - something to check is about the button text too. I'm not sure if we need to say `Copy to clipboard`. Maybe we can just say `Copy`?

Saying that as when in extension view the text is too long for the button: 
![Screenshot 2023-09-28 at 09 11 28](https://github.com/leather-wallet/extension/assets/2938440/0bdd21bf-faac-4953-a3b4-9867b408b6c1)

I can make the text change at smaller sizes but maybe just `Copy` is enough?

**Comment by pete-watters** [comment]
I also made this a bit wider, let me know if its OK. 

![Screenshot 2023-09-28 at 09 25 51](https://github.com/leather-wallet/extension/assets/2938440/621a1324-78a7-41f2-96bd-422a7014e3e8)

**Comment by 314159265359879** [comment]
> Very nice!
> 
> Curious to see how/when type-ahead can be triggered and how it'll feel when typing in the key. Btw, are you aware of any products already doing this? Maybe that's a good proxy to get a better feel

For some examples@fabric-8, two "apps" that use it:
Sparrow wallet (also open source)
![image](https://github.com/leather-wallet/extension/assets/33360391/9f4e5028-e43e-454b-aed5-b8e242c27ba1)

And I think the experience when restoring a seed on a Ledger is also a good example of how to help the user while typing part of the words (for example on a nano S).

**Comment by mica000** [comment]
@pete-watters @fabric-8 thanks for working in this! It's looking very nice!
Was wondering about the corner radius, should we already add the 0 radius corner to the inputs or do this is a separate PR where we tackle all the corners of the app?

**Comment by fabric-8** [comment]
@mica000 Guess we should handle this seperately as it's a global thing we need to apply?

**Comment by kyranjamie** [comment]
Agree, anything that changes things app-wide is best done separate from any feature work

**Comment by pete-watters** [comment]
I'll re-add the radius so it matches the rest of the app then I will remove it again with the brand audit work.

**Comment by pete-watters** [comment]
@fabric-8 @markmhendrickson @mica000: I've finalised work on this and updated the [PR here](https://github.com/leather-wallet/extension/pull/4243). 

I decided to leave out auto complete for now as it was a big job getting this far and I need to switch to other priorities. I can continue with that in the near future once I progress some other issues cc @314159265359879 .

**Comment by pete-watters** [comment]
I've just merged this so it's ready to release. @fabric-8 @markmhendrickson @mica000 - let me know if you spot anything else that needs tweaking
