### ISSUE TITLE
Keeps getting locked out

### ISSUE THREAD

**Issue by Hero-Gamer** [blockstack/blockstack-app#4134]
Hi, input password correctly, logged in fine. Then soon after some seconds or a minute, wallet is auto locked again asking for my password. 
V6.3.1 
Firefox.

**Comment by Hero-Gamer** [comment]
Seems after I updated the browser, fixed the problem. Thanks.

**Comment by Hero-Gamer** [comment]
I was wrong, the problem still persists! Help!

**Comment by 314159265359879** [comment]
@Hero-Gamer, you will like the next update, a fix for this [was built ](https://github.com/hirosystems/wallet/pull/4127)and is going out in the next release. (6.3.2+)
