### ISSUE TITLE
Scroll bar exceeds its own bounds, PSBT

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4140]
![image](https://github.com/hirosystems/wallet/assets/1618764/337f749d-613e-4b51-9366-f15610d28f6a)

![image](https://github.com/hirosystems/wallet/assets/1618764/1d92c363-fd10-4731-b80d-42e4d3e64873)

In PSBT signing screens, the scroll bar goes below the fixed area and is cut off. We should see the bottom of the bar.

**Comment by markmhendrickson** [comment]
@pete-watters I presume this is related to your current container work?

**Comment by pete-watters** [comment]
Yes it's another thing to fix there so I will take care of it

**Comment by pete-watters** [comment]
I have fixed this in #4370 . 

Here's a demo:
https://github.com/leather-wallet/extension/assets/2938440/cf865735-b78b-4709-82ee-72809585ed6f

Note - in the demo:
- the header is wrong
- I am forcing display of the scroll bar to show the issue is resolved, however we usually hide it
