### ISSUE TITLE
Not all ordinals on regenerated addresses loading

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4145]
This was first reported here: https://github.com/hirosystems/wallet/issues/3752 most of these cases have since been resolved. This one has not. 

I have been on a call with the user who isn't getting all their ordinals loaded past some of the ordinals on the other indexes (regenerated addresses from prior to March 20th). 

The user is particularly interested in getting the ones loaded on index m/86/0'/0'/0/5 and most specifically this is not loading (some of the others are):  #57431

m/86'/0'/0'/0/0
[bc1puvv9q3l02l90n882036cnv5rcg4hkts5vel99seasmf03pukhajq7kest8](https://ordinalswallet.com/address/bc1puvv9q3l02l90n882036cnv5rcg4hkts5vel99seasmf03pukhajq7kest8)

m/86'/0'/0'/0/1
bc1pkcq02uvqp40keft9p96wsgg3vhwsln4d2mhlsmjmw02lnztn4mwsnpva5f

m/86'/0'/0'/0/2
bc1pklhj9cqeguaxq0z5vxs3ngdsuqfj7vr39ynvsc0heu0d3w3puhkqkdu25x

m/86'/0'/0'/0/3
bc1p5x8y9fe5vzt9us0njmctlqsa9q6nx3v5xk90vplc5qmlm75ku7nspzfvm4

m/86'/0'/0'/0/4
bc1pnyejp94h09afcu8afqpw5pkcwqvdmm5rfvvh0tw4tdzq3936c2gqyaykkz

m/86'/0'/0'/0/5
https://ordinals.hiro.so/address/bc1pz6t7a9ytmpq63wms3agmwgmtlw8n96de09lmsuqnc53prhj0q8lqwknkzn
![image](https://github.com/hirosystems/wallet/assets/33360391/210439d8-69a2-4798-8b1d-434a2c4a825f)

m/86'/0'/0'/0/6
bc1psksdgmtkecckeq05s937j9qzh23n8mmkc3hf029em9lhqfmv6c9qaaue23

m/86'/0'/0'/0/7
bc1pllzarlxqdrsnyuzdymac8c4vnhje8pz7fk6dspextaea7lu47lgsaf0kgu

m/etc'

The one not showing up is: 
#57431 (also shown in the last screenshot here which is expected to show all the ordinals going from low to high ordinal number)
![image](https://github.com/hirosystems/wallet/assets/33360391/6d5bfe75-fa02-4963-9f8e-235985a2188a)

Additionally we see the wallet keeps showing the "loading" icon below the ordinals that do show, it loads for sec, stops then does that again: 
![image](https://github.com/hirosystems/wallet/assets/33360391/32b5337a-8652-4a4a-a7c3-a3c642710a8a)

We couldn't see errors in the console beyond this (these do not seem related, right?):
![image](https://github.com/hirosystems/wallet/assets/33360391/624cdae5-0bb5-4365-90d4-aeeb9d826bb9)

Workaround: Because this is in Account 1 in Hiro, we were able to load the seed in Xverse and go to the 6th account there to access this taproot address m/86'/0'/0'/0/5. There the specific ordinal (#57431) is loaded/shown.

**Comment by markmhendrickson** [comment]
@314159265359879 I'm closing as stale but please reopen if still relevant.
