### ISSUE TITLE
Using ordinalswallet: buy/mint an ordinal leads to "Unable to sign PSBT... sighHash=0, Allowed: 1" error

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4146]
![image](https://github.com/hirosystems/wallet/assets/33360391/edb0a9ae-c273-491d-94ca-9702a46dcaf1)

This looks like a similar issue Magic Eden had and resolved. 

I do not think they are aware yet that it is something only they can solve. Lets reach out?
![image](https://github.com/hirosystems/wallet/assets/33360391/fef2dd80-948d-41e3-bcee-7c4cd8f5579d)

**Comment by markmhendrickson** [comment]
@314159265359879 suggests we need docs to help devs avoid this issue on their end

**Comment by fbwoolf** [comment]
Related issue, this will fix: https://github.com/hirosystems/wallet/issues/4116
