### ISSUE TITLE
Replace final Ordapi.xyz dependency before October 1, 2023

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4163]
Ordapi API will be shut down on that date

https://github.com/leather-wallet/extension/blob/3b7bc460905e0a9a1d7ce30867e8470de2e0d453/src/app/query/bitcoin/ordinals/ordinals-aware-utxo.query.ts#L14

**Comment by fbwoolf** [comment]
@markmhendrickson this is not currently offered by the Hiro api: https://docs.hiro.so/ordinals/introduction

**Comment by 314159265359879** [comment]
Should we request the feature in the Hiro Ordinals api repo? it would be quite nice if the functionality was there to check outputs for ordinals, wouldn't mind the option to search by output too... for troubleshooting. 

Which API will we be using for this in the meantime?

perhaps an option?
https://ordinals-explorer.generative.xyz/output/2c4883f940a13cec19f6b3938fce1c13e1a797e399c9d6ffe5ca2ee610b7f568:0

**Comment by fbwoolf** [comment]
> Should we request the feature in the Hiro Ordinals api repo? it would be quite nice if the functionality was there to check outputs for ordinals, wouldn't mind the option to search by output too... for troubleshooting.
> 
> Which API will we be using for this in the meantime?
> 
It turns out, we are using the Hiro api. I am in the process of refactoring. Their inscription list ended up having the data we need in the response to filter utxos.
