### ISSUE TITLE
Design System - Add containers

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4165]
https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=5056-60851&mode=design&t=CbvgKq8c4jj6eRZE-0

<img width="1429" alt="Screenshot 2023-10-03 at 14 28 01" src="https://github.com/leather-wallet/extension/assets/119523541/c40a35d3-a825-42a1-b2a6-5483bbb90492">

<img width="745" alt="Screenshot 2023-10-03 at 14 27 33" src="https://github.com/leather-wallet/extension/assets/119523541/6d12ef9e-c89a-4d1a-b2de-6ed02c829209">

**Comment by pete-watters** [comment]
![Screenshot 2023-09-21 at 10 46 37](https://github.com/leather-wallet/extension/assets/2938440/bdcfbb71-b5d8-48be-9a3c-f85b9b60ab60)

**Comment by pete-watters** [comment]
We need to fix this so the button doesn't disappear at smaller heights

![Screenshot 2023-09-21 at 10 47 22](https://github.com/leather-wallet/extension/assets/2938440/d5b0ac2a-7aff-44a9-9342-aa518f481d9d)

![Screenshot 2023-09-21 at 10 42 09](https://github.com/leather-wallet/extension/assets/2938440/ae1f3051-afc4-4464-b9d6-8b207a965e79)

**Comment by pete-watters** [comment]
![Screenshot 2023-09-21 at 11 12 03](https://github.com/leather-wallet/extension/assets/2938440/ddb63c2f-2954-43e8-be82-1c7df77ffa29)

**Comment by pete-watters** [comment]
![Screenshot 2023-09-21 at 11 22 37](https://github.com/leather-wallet/extension/assets/2938440/70e26b30-079d-411e-b581-f5928551760e)

**Comment by pete-watters** [comment]
> We need to fix this so the button doesn't disappear at smaller heights
> 
> ![Screenshot 2023-09-21 at 10 47 22](https://user-images.githubusercontent.com/2938440/269569321-d5b0ac2a-7aff-44a9-9342-aa518f481d9d.png)
> 
> ![Screenshot 2023-09-21 at 10 42 09](https://user-images.githubusercontent.com/2938440/269577370-ae1f3051-afc4-4464-b9d6-8b207a965e79.png)

I made this look better in this PR: https://github.com/leather-wallet/extension/pull/4343 

I fixed the issue main issue with the button disappearing and adjusted it to reduce the gap, however it's still not perfect as you can see the top border radius and the dashed border of `New Collectible` below:
![Screenshot 2023-10-11 at 13 13 29](https://github.com/leather-wallet/extension/assets/2938440/45a737c2-4efd-4085-86e6-07db8a289c62)

I had to apply a similar fix to the `Receive` modal https://github.com/leather-wallet/extension/issues/4165#issuecomment-1729230925

I checked some other modals we have (theme, network) and we will need to fix them also or come up with a better solution for this. 
![Screenshot 2023-10-11 at 13 15 16](https://github.com/leather-wallet/extension/assets/2938440/34cd2a33-f1d8-4e25-8f7b-36eb943f6d33)
![Screenshot 2023-10-11 at 13 18 06](https://github.com/leather-wallet/extension/assets/2938440/a0c888aa-aefe-49a9-88cb-941e78c5bcd8)
![Screenshot 2023-10-11 at 13 18 20](https://github.com/leather-wallet/extension/assets/2938440/eeb57cc7-eb9e-4d19-9fd5-0a8b2ac4caac)

**Comment by pete-watters** [comment]
> ![Screenshot 2023-09-21 at 11 12 03](https://user-images.githubusercontent.com/2938440/269576317-ddb63c2f-2954-43e8-be82-1c7df77ffa29.png)

I fixed this issue in here: https://github.com/leather-wallet/extension/pull/4243

**Comment by pete-watters** [comment]
@markmhendrickson @mica000 @kyranjamie: Closing this issue as discussed yesterday. 

I may have made things unclear here adding in other bugs from the brand audit. I added those screens as in the brand audit file we have flagged a lot of things with incorrect spacing on extension view. In the new designs to correct it it is also changing things from being a modal to being a full page as you can see here:


![Image](https://github.com/leather-wallet/extension/assets/2938440/c8111c04-f489-4cf1-a892-be102057d931)

If we want to change things to be full page and use containers that's fine but it seems unclear thats exactly what we want to do.

**Comment by pete-watters** [comment]
Work for this issue will be done in #4370 and #4371
