### ISSUE TITLE
Ensure full token names show if space available

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4170]
This token is fraudulent so inadvertently it's good we cut it off, but in general we should show the entire token name if there's space (to the right) to show it on the home screen, such as here when in full tab mode:

![Image](https://user-images.githubusercontent.com/28991/265183859-9f9fe604-1fde-4291-82f4-632c267849ee.png)

**Comment by fbwoolf** [comment]
I actually did this bc mine were going to multiple lines and causing issues in the UI...

![Screen Shot 2023-05-31 at 4 28 07 PM](https://github.com/leather-wallet/extension/assets/6493321/8f4d4780-9245-4fea-9e85-d08755a2465c)

What else should we do here then?

**Comment by fbwoolf** [comment]
Pretty sure there was an issue at one point to address these long names?

**Comment by pete-watters** [comment]
I think here we need to use ellipsis to truncate if we are in the extension view, but then in full screen view if there is space allow the full width to be used. 

We increased the minimum page width so there may be more space to show them there. 

We could also possibly add a tooltip in extension mode so if the name gets cut off you can hover and see it. 

@mica000 do you have any ideas on improving this?

**Comment by aryzing** [comment]
Would something like this work in all views?

```css
.class {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

**Comment by mica000** [comment]
> I think here we need to use ellipsis to truncate if we are in the extension view, but then in full screen view if there is space allow the full width to be used.
> 
> We increased the minimum page width so there may be more space to show them there.
> 
> We could also possibly add a tooltip in extension mode so if the name gets cut off you can hover and see it.
> 
> @mica000 do you have any ideas on improving this?

Yes, this is the expected behavior 🙌

**Comment by mica000** [comment]
> I actually did this bc mine were going to multiple lines and causing issues in the UI...
> 
> ![Screen Shot 2023-05-31 at 4 28 07 PM](https://user-images.githubusercontent.com/6493321/265208536-8f4d4780-9245-4fea-9e85-d08755a2465c.png)
> 
> What else should we do here then?

For the row that is overlapping - this looks like a visual bug? Not sure exactly why this is happening. Any clarification possible to understand what's going on?

Ideally the container is set to wrap around the row content so no scroll needed if there is space to grow.

When there is no space to grow, then we show the scroll

**Comment by kyranjamie** [comment]
We'd need fluid width text truncation, guide here https://css-tricks.com/flexbox-truncated-text (some what tricky when not a fixed width).

Anyone that jumps on this, use _viewport width_ to establish whether to truncate (not `whenPageType()`).

**Comment by pete-watters** [comment]
Thanks Kyran, I can work on this to solve it

**Comment by pete-watters** [comment]
I have opened a [PR](https://github.com/leather-wallet/extension/pull/4359) for this. I chose to use a grid instead of fluid width text truncation as it seems cleaner and a better fit here.
