### ISSUE TITLE
Create Input recipe

### ISSUE THREAD

**Issue by alter-eggo** [blockstack/blockstack-app#4171]

**Comment by markmhendrickson** [comment]
@alter-eggo is this still WIP?

**Comment by alter-eggo** [comment]
no

**Comment by markmhendrickson** [comment]
Mind providing some context on this issue e.g. what it'll achieve?

**Comment by alter-eggo** [comment]
actually we will discuss it today on a call, radix components vs custom ones, this task is for creation of custom input component
