### ISSUE TITLE
Fix resizing on the buying step

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4188]
![Screenshot 2023-09-06 at 16 52 20](https://github.com/leather-wallet/extension/assets/119523541/d5745835-8a33-400c-ada7-a8b01bc798f5)
![Screenshot 2023-09-06 at 16 49 34](https://github.com/leather-wallet/extension/assets/119523541/165f0311-d90f-4d1c-bed5-2607c8a867ac)

-------------

**How it should look:**
Same as the old Hiro wallet before
![Screenshot 2023-09-06 at 16 52 42](https://github.com/leather-wallet/extension/assets/119523541/322bc3f2-1af0-4563-8f70-c6a053d87378)

**Comment by pete-watters** [comment]
@mica000 I have updated this screen and the PR is ready to check here: 
https://github.com/leather-wallet/extension/pull/4208

I'm not sure if we have a new design for this page? I couldn't see it. Let me know if anything looks off and I can fix it. Thanks!
