### ISSUE TITLE
Code view during contract deployment breaks display of transaction window

### ISSUE THREAD

**Issue by badonyx** [blockstack/blockstack-app#4192]
<img width="554" alt="Screenshot 2023-09-06 at 5 53 22 PM" src="https://github.com/leather-wallet/extension/assets/110633279/4ab3e4b5-c809-4aea-9cfa-fc722f979227">

**Comment by 314159265359879** [comment]
Thanks for sharing!

**Comment by pete-watters** [comment]
Closing this off as I believe it's stale and solved in https://github.com/leather-io/extension/issues/5248
