### ISSUE TITLE
Prevent Stacks logo from appearing in "Extensions" page

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4197]
Currently in Chrome:
![image](https://github.com/leather-wallet/desktop/assets/33360391/7d3d790c-450c-4e68-b242-1f0ed07df4c4)

**Comment by markmhendrickson** [comment]
The new Leather logo should show up instead of the Stacks one, for all users who have installed the extension post-rebrand or accepted the new brand from within existing installs.

@314159265359879 have you seen the STX logo upon installing a build from source? It seems we have a bug in which it sometimes shows again in that scenario

**Comment by 314159265359879** [comment]
@markmhendrickson I did install this one from the Chrome store. To check if the other wallet I had installed from source was causing the issue I uninstalled both Hiro/Leather wallets and then reinstalled Leather via the Chrome store. It looks like this is still popping up. 

Before
![image](https://github.com/leather-wallet/extension/assets/33360391/216c5244-6f84-412a-b4f6-ccc3f3dacfe1)

After
![image](https://github.com/leather-wallet/extension/assets/33360391/713292c5-22cc-4b61-a592-160b442b263c)
(retested with Chrome (fresh install), also seeing the STX logo on the extension management page in Brave after accepting new terms). 

----
By the way the icon in the top right of the browser does update right after I click "accept new terms". 
![image](https://github.com/leather-wallet/extension/assets/33360391/5fa72bc2-cb48-4bec-8abc-4e17f294e96b)
Screenshot from Chrome (and retested on Brave).

**Comment by kyranjamie** [comment]
I'm not sure there's anything we can do about this until we change the manifest-defined logo. Give it another one or two weeks, I reckon we should remove the icon swap for just leather

**Comment by 314159265359879** [comment]
I got a report that on a fresh computer/browser installing on Firefox will also show the stacks logo on the navigation bar in Firefox. I was able to reproduce this. I assume it is due to the same issue and will be resolved in about 2 weeks as per Kyran's message above.
