### ISSUE TITLE
Wallet sets to low bitcoin "standard fee" sometimes

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4198]
From the past week:

Wallets sets a fee of 4-6 sats/vB, we have seen about four cases this week. 

The transaction usually depletes the wallet and there is at most a small amount left in the wallet in the ~300 sats range. Insufficient to to significantly increase the fee with the existing input/inputs. 

Is there anything more we can do to prevent situations like this? (why is the wallet setting these fees, we haven't seen them confirmed this low for a month or more). 

Another solution would be to have options to increase the fee on such a transaction too. as described in https://github.com/leather-wallet/extension/issues/4176

Some screenshots of such a transaction
![image](https://github.com/leather-wallet/extension/assets/33360391/6288d1c0-258f-4d39-bfb6-92d21ca7f452)

https://mempool.space/address/bc1qcvag8add7errl0jlzv47u09dnz5u6wpphs2ayd
![image](https://github.com/leather-wallet/extension/assets/33360391/7cb62323-5b02-4c5c-a95b-32d6c1224b34)

**Comment by fbwoolf** [comment]
@314159265359879 this issue was opened quite awhile ago, is this still a problem and what do you propose as a solution? Not quite sure I know what you want me to do here?

**Comment by fbwoolf** [comment]
I feel like we can close this issue, we provide the custom fee option so that if situations like this come up with fee estimates a user can adjust the fee on their own? cc @markmhendrickson

**Comment by markmhendrickson** [comment]
I believe the concern is that our API-based calculation for the standard fee level is sometimes coming in lower than expected given average rates seen elsewhere. Users proceed without knowing / realizing that the fees are low, and then later have to go back and "Increase fee" (so they aren't aware of the problem upon sending initially and inclined to customize the fees until it's too late).

@314159265359879 perhaps has more details about the behavior and frequency of this problem that could help indicate why we might be estimating low at times.

**Comment by fbwoolf** [comment]
Yeah, but we tackled this before and now average three different apis to get our fee estimates, so what else can we do here?

**Comment by fbwoolf** [comment]
It looks like a `BtcSizeFeeEstimator` was created, but I don't have much context on it. cc @kyranjamie could this be the prob here?

**Comment by 314159265359879** [comment]
> I believe the concern is that our API-based calculation for the standard fee level is sometimes coming in lower than expected given average rates seen elsewhere. Users proceed without knowing / realizing that the fees are low, and then later have to go back and "Increase fee" (so they aren't aware of the problem upon sending initially and inclined to customize the fees until it's too late).
> 
> @314159265359879 perhaps has more details about the behavior and frequency of this problem that could help indicate why we might be estimating low at times.

This is a good description of the problem, users do not realize it indeed. There were two reports in the last month (mind you there is little traffic on Bitcoin at the moment). 

A third case that was narrowed down to CPFP chain and lowered effective fee rates as per: https://github.com/leather-wallet/extension/issues/4037

The other two cases looked like 
A. they had bad data from one of the three API endpoints which lowered the estimate to something that was way off compared to whatever average fees mempool.space was displaying for that moment. 
B. The wallet had outdated info (from days or weeks ago) which for some reason wasn't updated at the time the fee was calculated/estimated for the latest transaction. (what happens when the API endpoints are unreachable? are fees not updated, is there an error for the user in such a case?)
C. Perhaps there is another way to explain it...

**Comment by fbwoolf** [comment]
I wonder if it would help to show a low fee warning if we detect the fee estimations are low? Also, we are using these options in the query, which maybe we should leave as `true`.
```ts
refetchOnWindowFocus: false,
refetchOnMount: false,
```

It appears we are only using two apis now for the average. We are defaulting to fallback fees if we need to, so we could show a warning too if that happens?

**Comment by markmhendrickson** [comment]
> we are using these options in the query, which maybe we should leave as true.

Curious how this might be affecting the fee rate – could it be that the app is applying an old cached fee rate from a previous send, when rates were lower?

**Comment by kyranjamie** [comment]
How is the wallet able to determine whether or not the fee estimations are too low?

If there was another source of truth we could reference, we'd use that instead.

**Comment by 314159265359879** [comment]
> How is the wallet able to determine whether or not the fee estimations are too low?

The wallet may be able to do some statistical analysis on the inputs but with n=2 (two fee estimations) there is not much to go on? 

When one of the values is off, the average is off and hence the wallet can be sending transactions with a low fee. I am not sure if that is the case though.

Some thoughts if so...
1. Express the range of the values in a percentage of the average fee. A high percentage means low confidence: warn user to check the value. 
2. Add more fee estimates to increase n, a wrong value will have less impact on the average.

**Comment by fbwoolf** [comment]
Should this issue be to add a third api for the fee estimation averages? Trying to pinpoint what to do here bc I can't reproduce the issue atm.

**Comment by kyranjamie** [comment]
I doubt a third would help here. @314159265359879 is the problem that the APIs are suggesting too low of a fee, or that we calculate the weight of the tx wrong, and apply a too low fee for the tx size?

**Comment by 314159265359879** [comment]
@kyranjamie I am not sure, I haven't been able to determine what caused it exactly, I just have some thoughts here A, B,..
https://github.com/leather-wallet/extension/issues/4198#issuecomment-1779926571

Since it only affected some users and not everyone perhaps B should be investigated further first. 

What happens when the API endpoints are unreachable? are fees not updated, can there be an error/warning for the user in such a case?

Or wait until we have a specific case again. Most of the time though we get the report well after the fact and I am unable to reproduce it. A dev mocking some of the likely scenario's with unreachable fee estimate API's may shed as much light on possible improvements without such a case.
