### ISSUE TITLE
Update Firefox slug

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4201]
Firefox store hasn't updated, nor redirect from the original hiro-wallet url https://addons.mozilla.org/en-US/firefox/addon/hiro-wallet

@markmhx is this a setting we need to update in the admin panel?

**Comment by markmhendrickson** [comment]
Updated to https://addons.mozilla.org/en-US/firefox/addon/leather-wallet

Unfortunately they don't support redirects from the old path 😢
