### ISSUE TITLE
Add fees components for swaps

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4204]

**Comment by markmhendrickson** [comment]
@fbwoolf do we need design guidance here?

**Comment by fbwoolf** [comment]
> @fbwoolf do we need design guidance here?

Not specifically for the fee page bc we will reuse the designs from btc choose fee, but we do need a design flow for when fees are used. How are we handing when sponsored txs are disabled (when there is one pending)? How will the user be notified about this and decide to pay the fee themselves, etc? I don't understand at this point when this page is actually needed in the swap flow.
