### ISSUE TITLE
How to integrate Leather on our site?

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4222]
I got this question via email. 

_Thank you, I'm looking at the [Connect-Users/Get-Addresses](https://leather.gitbook.io/developers/bitcoin/connect-users/get-addresses) instructions but it's not clear what steps we have to do to get the Leather wallet setup on our site so that users can connect their wallets.

I see the example code but no instructions on how to implement it. Does the wallet "Example screenshot" get called from just that one line of code?_

I was wondering if the following could be added to the page, an example of a dapp with the integration that is both open source and live, so users with a similar question can check that out.

**Comment by markmhendrickson** [comment]
Tracking [here](https://app.asana.com/0/0/1206838329175629/f)
