### ISSUE TITLE
Update HiroWalletProvider to Leather

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#4244]
Refactor naming of our provider.

**Comment by fbwoolf** [comment]
@kyranjamie will this be a breaking change?

**Comment by kyranjamie** [comment]
Yes, we should add a new in in addition to, rather than renaming old one

And we already have
https://github.com/leather-wallet/extension/blob/615ebb1d458f1ee101a82b2fb47df908a65b84cf/src/inpage/inpage.ts#L255-L258
