### ISSUE TITLE
Improve handling when hitting API "Too many history entries" limit

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4248]
A user is experiencing this issue where no balance is shown in the wallet for bitcoin:
![image](https://github.com/leather-wallet/extension/assets/33360391/8cb2e354-bc6f-4449-b7bb-a05856cd7df6)
Other assets such as STX, Stacks NFT's are displayed normally. 

bc1qpyjutel6d4gj50dscphjrqcp29ljtfjel7ccap does have balance as seen on mempool.space explorer
![image](https://github.com/leather-wallet/extension/assets/33360391/676a43b9-21ca-4357-a63d-981af635b63f)

I have seen this issue before and often it is due to local restrictions, firewall, vpn etc. this time it looks like there is a different cause. 

Console displays a error 400 for the blockstream API
![image](https://github.com/leather-wallet/extension/assets/33360391/40147414-e4d5-403e-ab70-f715d99469f8)

The API checked manually shows this
https://blockstream.info/api/address/bc1qpyjutel6d4gj50dscphjrqcp29ljtfjel7ccap/utxo
![image](https://github.com/leather-wallet/extension/assets/33360391/f92401f2-4101-43ab-84ca-c6b3c3e001db)
"Too many history entries"

I think we need better error handling for this. Preferably also a way to display the balance anyway.

**Comment by kyranjamie** [comment]
Needs design input for how we visually display the error cc/ @mica000 @fabric-8

**Comment by 314159265359879** [comment]
Another wallet affected by this issue, 16,725 transactions
bc1qwafz80ygxpurl9fqmldp4x2z7z5g2p3ned68lf

https://mempool.space/address/bc1qwafz80ygxpurl9fqmldp4x2z7z5g2p3ned68lf

https://blockstream.info/api/address/bc1qwafz80ygxpurl9fqmldp4x2z7z5g2p3ned68lf/utxo
![image](https://github.com/leather-wallet/extension/assets/33360391/c9fc5e8b-d5db-47ef-af8e-f999df126aaf)

Will we work around this issue in the future. Would it require running a local node /API server for example?

**Comment by fabric-8** [comment]
Would be great to discuss constraints & possibilities here to better understand what's feasible from a design perspective cc @markmhendrickson

**Comment by 314159265359879** [comment]
I noticed this issue is similar: https://github.com/leather-wallet/extension/issues/3631#issuecomment-1941071023 Mark suggested a possible solution there. 

another wallet affected by this today:
![image](https://github.com/leather-wallet/extension/assets/33360391/e5e3e5a8-9705-4c3f-a626-2c4a10c950c9)
https://blockstream.info/api/address/bc1qke8cq9kkvpwvm74rrvd7lhxl3d0faw4qau8lzn/utxo

**Comment by markmhendrickson** [comment]
Can we use blockchain.info as a backup e.g. https://blockchain.info/balance?active=bc1qke8cq9kkvpwvm74rrvd7lhxl3d0faw4qau8lzn ?

**Comment by kyranjamie** [comment]
This might help us display the balance, but nothing else would work, sending txs, showing transactions etc

**Comment by kyranjamie** [comment]
Even with a node, [getting all the utxos of a given address](https://bitcoin.stackexchange.com/questions/93860/how-to-query-all-utxos-of-an-address-from-a-full-node) isn't supported well.

Solutions like Quicknode also don't have a the full suite of RPC commands, and misses the ones we'd need e.g. [`listunspent`](https://developer.bitcoin.org/reference/rpc/listunspent.html). It does however have [a paid add-on that supports querying utxos](https://marketplace.quicknode.com/add-on/blockbook-rpc-add-on), [Blockbook](https://github.com/trezor/blockbook).

If we take this approach, we'll need to investigate the [rate limiting tooling they also offer](https://guides.quicknode.com/docs/bitcoin/endpoint-armor), to avoid abuse of our key that would always be public.

**Comment by 314159265359879** [comment]
Another case like this 
https://blockstream.info/api/address/bc1qc4a54g4y7pyq5mcqys8xp4k4k7rkumv9zyt980/utxo
![image](https://github.com/leather-wallet/extension/assets/33360391/bce1b4f5-5bcb-4f0f-b147-f305ac341f07)

https://blockstream.info/api/address/bc1qc4a54g4y7pyq5mcqys8xp4k4k7rkumv9zyt980
[![image](https://github.com/leather-wallet/extension/assets/33360391/b53995ed-206b-459a-b1b4-c3a047bd3c90)](https://mempool.space/address/bc1qc4a54g4y7pyq5mcqys8xp4k4k7rkumv9zyt980)

**Comment by 314159265359879** [comment]
If we switch to BIS, would that resolve this issue?

Another address affected (for mocking/retesting): https://mempool.space/address/bc1qvvlpmskgaq0uulja7nj0wu7m6sk46vearwxwyf

**Comment by markmhendrickson** [comment]
> If we switch to BIS, would that resolve this issue?

This is unrelated to BIS since it involves Blockstream, not Hiro or Ordinals APIs generally

**Comment by 314159265359879** [comment]
@markmhendrickson do you have an estimate when a fix for this could be live?

**Comment by markmhendrickson** [comment]
Not yet, since it hasn't been prioritized

**Comment by brandonmarshall-tm** [comment]
Another report from one of our partners 
![telegram-cloud-photo-size-5-6231204167708426214-y](https://github.com/leather-wallet/extension/assets/122313287/85f82396-204c-4f12-89aa-775d2081b29c)

**Comment by markmhendrickson** [comment]
I'm moving to our dev backlog and assigning @alter-eggo to investigate solutions, presumably by implementing an alternative to Blockstream for the relevant query/ies

**Comment by markmhendrickson** [comment]
The build on https://github.com/leather-io/extension/pull/5690 resolves this issue for me.

**Comment by kyranjamie** [comment]
@markmhendrickson which wallet/address are you using that triggers this error?

**Comment by markmhendrickson** [comment]
https://github.com/leather-io/extension/issues/3631#issuecomment-2258312130

**Comment by kyranjamie** [comment]
Ah fantastic, I see it's fixed since  using paid Mempool space plan.
