### ISSUE TITLE
Prevent buttons cut-off for analytics prompt in modal viewport

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4250]
It seems the overlay with the analytics content simply needs to extend further to the bottom so there is even margins all around it

<img width="472" alt="Screenshot 2023-09-20 at 16 55 40" src="https://github.com/leather-wallet/extension/assets/28991/6b4d8ac5-cabb-49d3-b9ad-f3a48894844e">

**Comment by mica000** [comment]
@markmhendrickson I believe this should be fixed once we update the containers, which will improve headers and footers?

**Comment by pete-watters** [comment]
I checked this and it looks OK in extension mode:

![Screenshot 2023-10-11 at 14 43 00](https://github.com/leather-wallet/extension/assets/2938440/90da1d19-fc27-4038-b946-1784d92e5c79)

I think this specific issue relates to pop-up mode when we are authorising other apps but don't have a logged in wallet.

I tried to fix it quickly but it will take a bit of time to get it right as our standard breakpoint for extension mode doesn't work for modals so I need to investigate

**Comment by pete-watters** [comment]
I've fixed this in #4370 . Once merged it will look like this: 

<img width="412" alt="Screenshot 2024-02-01 at 15 38 34" src="https://github.com/leather-wallet/extension/assets/2938440/7c323470-9497-4bb4-ba0e-4ef7383a59a6">

Something I notice with our buttons is they have a blue border on focus which we will need to fix. 

<img width="403" alt="Radix_BG_Bug" src="https://github.com/leather-wallet/extension/assets/2938440/2ceea967-a79b-4e8d-ad4a-738475e77d78">

**Comment by fbwoolf** [comment]
> Something I notice with our buttons is they have a blue border on focus which we will need to fix.
> 
Focus border is in the designs.

![Screenshot 2024-02-01 at 11 18 18 AM](https://github.com/leather-wallet/extension/assets/6493321/397f5dd6-e398-4ad2-8880-2086a487d32b)

**Comment by fbwoolf** [comment]
Best to link issue to the PR?

**Comment by pete-watters** [comment]
Thanks Fara! I guess it's not a bug so 😄 

I linked it to the containers PR just now. I am cleaning up some of the fixes to put them in review to get a clear picture of whats fixed and not

**Comment by mica000** [comment]
Well, but curious to know, does this border appear on a default button? it should only be visible when on focus mode

**Comment by pete-watters** [comment]
> Well, but curious to know, does this border appear on a default button? it should only be visible when on focus mode

No it's only on `focus`. It looks good, now that I know it's intentional 😄
