### ISSUE TITLE
Make background of Ledger transparent for dark mode

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4251]
@fabric-8 assigning to you first in case you can prepare such an asset for integration given your other recent editing work on the animtaions

<img width="1358" alt="Screenshot 2023-09-20 at 16 59 09" src="https://github.com/leather-wallet/extension/assets/28991/e67e51f1-1d5c-4e21-a3bd-99e4a73a33b6">

**Comment by fabric-8** [comment]
Yes, will handle this together with @alter-eggo when exchanging the assets for themable SVGs
