### ISSUE TITLE
Fix padding on buy screen within modal

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4253]
We seem to have too much in a few places:

<img width="417" alt="Screenshot 2023-09-21 at 14 21 06" src="https://github.com/leather-wallet/extension/assets/28991/90fdb4fb-b527-4bed-b724-5180fe335ae7">
<img width="405" alt="Screenshot 2023-09-21 at 14 21 10" src="https://github.com/leather-wallet/extension/assets/28991/6fed9c3c-4776-46f1-9911-751560d58d94">

**Comment by pete-watters** [comment]
I can fix this and also this issue: https://github.com/leather-wallet/extension/issues/4423 

But we don't have visual designs for a lot of screens across all views so we have improvised here. It would be helpful to have pixel perfect designs for screens in at least full screen and extension view so we can set padding etc. correctly

**Comment by markmhendrickson** [comment]
@mica000 @fabric-8 either of you want to take on this design guidance?

**Comment by mica000** [comment]
Designs here: https://www.figma.com/file/mpfjDNidnBwUUoCz8r1Wkx/%232251---Fund-account?type=design&node-id=376-53889&mode=design&t=dxep2GBa6ZYT6OBm-4

settings of the wrapper around the cards
<img width="899" alt="Screenshot 2023-10-27 at 15 40 24" src="https://github.com/leather-wallet/extension/assets/119523541/69605e42-dffb-4dcd-bece-492d8f32364e">

**Comment by pete-watters** [comment]
~~I started looking at this but the `Buy` step is failing in the dev build. I'll investigate~~

=> I found a comment in the code saying the issue above is a known one so it can be ignored

![Screenshot 2023-11-01 at 08 56 12](https://github.com/leather-wallet/extension/assets/2938440/b42244fe-58b0-4d17-a5ee-7c96afd0bc20)

**Comment by pete-watters** [comment]
Thanks for linking this design @mica000 . I've made some changes:
- to improve the spacing
- reduce heading size in extension view

When resizing the browser, when I move from full tab the changes don't kick in until we are in a narrow screen. Let me know if you want me to further adjust heading size / padding along the way

https://github.com/leather-wallet/extension/assets/2938440/d492239d-f1f7-45de-8802-e1f1b61b5f37

**Comment by mica000** [comment]
@pete-watters Sorry, I see that you just closed the issue but didnt add the feedback yet. My bad!

Here is the issue I talked about:
<img width="574" alt="Screenshot 2023-11-01 at 18 49 11" src="https://github.com/leather-wallet/extension/assets/119523541/2a2b9ae9-8a99-4420-92ce-f6fc5fb29680">



**Wondering if we could:**
1. Change the header to heading 3 on the extension;
2. Add the background color to fix the issue with the white bg when resizing to small sizes;

<img width="257" alt="Screenshot 2023-11-01 at 18 48 33" src="https://github.com/leather-wallet/extension/assets/119523541/9e397aa2-c18e-4e16-a782-c474c332f3ff">

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=6421-55389&mode=design&t=LE3yc8UvRyVRPwK0-4

**Comment by pete-watters** [comment]
@mica000 not your bad at all, I closed it as I fixed the other problems. 

I can see the issue too and it looks bad in dark mode also:
https://github.com/leather-wallet/extension/assets/2938440/4b468843-289c-4190-9ce8-edc461eb288c

It seems:
- it doesn't behave the same on the `Fund` page as the `Home` in the breakpoint just before extension 
- in `dark` mode the header gets set to black but it should be the page BG colour
- the header has too much bottom padding so then the text heading doesn't get proper top padding

I'll fix it in the [containers](https://github.com/leather-wallet/extension/issues/4370) issue if that's OK? 

I will be working on that next week
