### ISSUE TITLE
Sandbox blank wallet appears after deploying contract with address mismatch

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#4258]
When attempting to deploy a contract on Sandbox, a blank wallet appears when users are not connected to the same address they logged in with.
The issue can be resolved by signing out of Sandbox and signing back in with the same address. Is it possible to add a notification in the box to alert users of the address mismatch?
Additionally, could the same notification also warn if they are connected to the mainnet but signed in to testnet, indicating an address mismatch?

![blank wallet](https://github.com/leather-wallet/extension/assets/132958967/f8f585bf-4414-4e60-b83b-2e1258754122)

**Comment by kyranjamie** [comment]
This is a problem relating to Firefox unexpectedly reverting us back to a 2-year-old version
