### ISSUE TITLE
Firefox Not Recognizing Leather Wallet

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#4259]
User reported on ALEX Discord that they encountered an issue with Firefox not recognizing Leather. After refreshing the browser page (F5) three times, it seemed to resolve the issue.

[ALEX Discord post](https://discord.com/channels/856358412303990794/856358412303990797/1154321765430997083)

**Comment by 314159265359879** [comment]
Did they install version 2.10.0 which is currently available on the Firefox store due to an unresolved issue? This version is 2 years old and not expected to work properly. If they have 6.5.0 or 6.5.1 this would be unexpected. 

A new version was uploaded to Firefox over a week ago but is still pending review.

**Comment by mijoco-btc** [comment]
Hi any news on this ? I have 6.5.1 in firefox and have an issue (see pic) that is fixed in chrome v 6.9.2 ?
<img width="1174" alt="Screenshot 2023-10-13 at 09 58 11" src="https://github.com/leather-wallet/extension/assets/4384929/0dbe00ab-0fd7-484e-b1f9-5addfbce849c">

**Comment by 314159265359879** [comment]
@radicleart the Firefox store has not yet accepted our latest build and is still serving 2.10.0 sadly. However, you can work around it by getting the .zip and installing it manually on Firefox instead. In that case grab the latest version for Firefox here [6.11.0 instead](https://github.com/leather-wallet/extension/releases).

**Comment by mijoco-btc** [comment]
Thanks - will give it a go  !

**Comment by markmhendrickson** [comment]
@radicleart did the new version work for you in the end?

**Comment by mijoco-btc** [comment]
Ah i got stuck with firefox extensions and dev mode.

I just retested (loading the wasm file) and everything looks to be working in FF with Leather version 6.16.

Thank you !
