### ISSUE TITLE
#1: Set up a package based monorepo and put in prettier config

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4268]
Create a leather-wallet `prettier-config` within the new monorepo, as a MVP package to test out the new monorepo.

**Comment by markmhendrickson** [comment]
@kyranjamie @pete-watters mind fleshing out this issue's description with the work involved?

**Comment by pete-watters** [comment]
Now that we have decided on a stack to use, the first step is to create a basic monorepo that we can use to share out prettier config. 

The steps involved here are:
- create  / clean up the demo monorepo and create a new `pnpm` workspaces monorepo
- extract the `.prettier` config from the `extenstion` and host it as a package here
- publish the package 
- consume the package in the `extension` and remove exisiting setup there
