### ISSUE TITLE
[Runes] Support runes protocol

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#4273]
Leather doesn't currently support Runes, but it feels like basic support could potentially be offered without a ton of work. Rune transactions are identified with an "R" in the OP_RETURN field. A basic implementation would be to protect any UTXOs containing this "R" designation so they aren't spent with other transactions.

Once the spec is more ironed out, they would be displayed in a similar manner to BRC-20 transactions in Balances.

Here's an example of a Rune transaction:
https://mempool.space/tx/ba8db28ec5aee2804b207c9a6bd95dd41e337fdc1508d977599862fc095b716b

**Comment by markmhendrickson** [comment]
Our initial support needs:

- [ ] Protection of UTXOs with Runes from missends or misspends during transaction signing generally (in addition to our existing protection for Ordinals and Stamps)
- [ ] Display of Runes balances (in addition to balances for other protocols like Stacks FTs, BRC-20, and SRC-20)

[See relevant API docs](https://docs.bestinslot.xyz/reference/api-reference/ordinals-and-brc-20-and-runes-and-bitmap-v3-api-mainnet+testnet/runes)

**Comment by fbwoolf** [comment]
@alter-eggo made an issue to track your progress here: https://github.com/leather-wallet/extension/issues/5207
Assigned myself to this issue: https://github.com/leather-wallet/extension/issues/5208

**Comment by fbwoolf** [comment]
First PR up here: https://github.com/leather-wallet/extension/pull/5209

**Comment by fbwoolf** [comment]
Going to close this bc we have open issues tracking the actual work here. Linked ^. Balances PR here: https://github.com/leather-wallet/extension/pull/5224
