### ISSUE TITLE
Publish to Microsoft Edge and Opera stores

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4277]
Ensure Leather can be found on Edge store https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

**Comment by pete-watters** [comment]
Do you think it's worth considering Opera and Safari extension support also? 

They are down the usage rankings but if we can support everything and most others only chrome it could give us an advantage. 

Opera for example is about 2% of browsers used worldwide but is the 2nd most used in Africa at about 12%. 

I think the wallet could be very popular in emerging markets where people need better choice of finance tools.

**Comment by kyranjamie** [comment]
Didn't realise Opera has it's own store, and I use it for my personal wallets, but yeah why not if we can.

<img width="1462" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/8e89b959-3644-4040-b1c5-b87c0b8ccc3b">

For Safari the extension requirements are a little bit different. We looked into it before and it was going to be quite a job to get it working. Though, maybe that's changed now we're MV3. Would definitely be a worthy addition.

**Comment by markmhendrickson** [comment]
Tracking [here](https://app.asana.com/0/1204692015959378/1206838329175632/f) now
