### ISSUE TITLE
Fix routing issues (edit nonce / sign out)

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#4285]
I have hit two routing issues in the past two days:

1. Using the STX send form edit nonce button > try to use back button after canceling > back button triggers the edit nonce form to popup again > caught in loop.
2. If on the Activity tab and you try to sign out > you are taken to the Assets tab

**Comment by pete-watters** [comment]
There's a few bugs we have with routing:
- https://github.com/leather-wallet/extension/issues/4028 
- https://github.com/leather-wallet/extension/issues/4086 

I can check this as part of those

**Comment by markmhendrickson** [comment]
@pete-watters has this been resolved as part of your containers work?

**Comment by pete-watters** [comment]
@markmhendrickson I checked and these are indeed fixed by https://github.com/leather-wallet/extension/pull/4655
