### ISSUE TITLE
Fix refresh icon alignment for collectibles

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4290]
![Image](https://github.com/leather-wallet/extension/assets/28991/9b6ffe09-b6b8-4a7b-83ad-86229e0d4b08)

**Comment by mica000** [comment]
this can be done in the Brand audit ticket pherhaps, since it will also update the font size?
 https://github.com/orgs/leather-wallet/projects/1/views/1?pane=issue&itemId=39370740

**Comment by pete-watters** [comment]
Yes I can fix that in issue #4249 . 

@mica000 I was changing the font there to be `label.01` but it still looks wrong compared to the design. 

In our system `label.01` is using `'Diatype'` but in the brand audit file it's `Inter`. 

Does it look OK here using `label.01` ? 

![Screenshot 2023-10-11 at 08 56 49](https://github.com/leather-wallet/extension/assets/2938440/3b8913e5-1230-4c70-80b2-57182f3c7bfc)
