### ISSUE TITLE
Refactor core code to use monorepo packages

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4297]
Once the concept is proven and tested here https://github.com/leather-wallet/extension/issues/4268 we can identify more things that would benefit from moving and being shared via packages. 

A rough list could be:
- TS config
- Core CSS theme 
- Panda configuration setup
- Design system - typography, colours etc.

**Comment by kyranjamie** [comment]
Eslint config, too. 

RE design tokens, how about the structure of `@leather/tokens` → `@leather/panda-config` ?

**Comment by markmhendrickson** [comment]
@kyranjamie to outline Bitcoin and Ordinals code to migrate for sharing

**Comment by pete-watters** [comment]
I've been working on this and have setup new monorepo packages for:
- `eslint`
- `tsconfig`

I've also implemented developer tools which:
- enforce conventional commits with `commitlint`
- use `husky` to run lint and commit checks on commit

Now I am working on setting up github actions to run checks and to auto-publish to `npm`. Once that's done we will be in a good spot to add the remaining packages

**Comment by pete-watters** [comment]
Another package to add here is `dependancy-cruiser`

**Comment by kyranjamie** [comment]
Here's a stab at how I reckon we should organise our packages. 

Please excuse this very basic, crude diagram but hope it can explain a few thoughts. For some reason I couldn't embed mermaid directly.

<img width="738" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/232e03d6-098a-4408-abdb-8dc3b90fa838">

**Package granularity**
The thinking here is really to highlight what level of granularity our packages should take. For example, do we have a general bitcoin package, break it down further into an ordinals package, a Native Segwit and Taproot package etc. I suggest the former, creating a chain-level abstraction (so not very granular).

**Isolating side effects/network requests**
Anything that involves side effects, e.g. network requests, we should isolate in separate packages. They should also allow some level of configurability. Consider the use case that we need to add a custom header to requests on each platform, how might we configure the internal http client?

**Dependency rules**
We'll likely need a core package for general utils and logic shared between the `@leather/{bitcoin,stacks}` packages. I think we can just have a single crypto package for this, but open to other ideas if anyone thinks we should abstract further. `@leather/crypto` must not depend on any chain-specific packages, and depcruiser should enforce this, and also prevent any circular deps.

**`@leather/crypto`**
Encapsulates common crypto logic shared between chains. Keychain derivation, extracting details from a derivation path, for example. Must not know of chain-specific details. Much of the logic in `src/shared/crypto` of extension. 

**`@leather/stacks`**
Lower priority for now as mobile won't support Stacks on first release, also much logic is already abstracted in `@stacks/*`

**`@leather/bitcoin`**
Highest priority package. Should depend on as few packages as possible, ideally only those of `@scure/*` and internal leather tooling. Stateless. Package should expose flat, pure functions. Should:
- Derive the correct bitcoin-specific keychains
- Contain logic to generate bitcoin payment types
- Sign transactions
- Message signing

**Questions**
- Should chain packages be allowed to contain React-specific implementations? Hooks etc?
- Should hardware wallet specific logic live alongside software in single package?
- To what extent can, or should, we extract state management stucture/logic?

Please share any other idea & feedback

**Comment by pete-watters** [comment]
This looks great to me @kyranjamie , thanks for the efforts on this. 

Regarding the questions:
- I think it's OK to keep React-specific implementations in chains but in an organised manner. It would be cleaner not to but in reality all of our APPs will use React for now at least so it's useful to also share that logic
- Similar to the above it could be easier to keep hardware + software specific logic alongside it's chain. I don't know much about the nuances of that though. If there are more generic things like setup / key creation it could be better to have in it's own package

Another thing for consideration on this path are to add more headless unit tests for packages to ensure core logic is well tested. 

Yesterday we discussed starting to move some of these items for sharing with mobile but I find that a tricky thing to do without a clear roadmap and defined feature list for mobile. That will help us prioritise what to move and when

**Comment by markmhendrickson** [comment]
@kyranjamie to decompose this issue into particular issues per package, for monorepo creation and extension integration respectively

**Comment by markmhendrickson** [comment]
@kyranjamie is this issue still relevant?

**Comment by kyranjamie** [comment]
Repurposing this issue for the refactor
