### ISSUE TITLE
Add dollar value of BTC being send for a BTC transaction created by a dapp

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4304]
Steps to reproduce
1. Go to unisat
2. Click inscribe
3. Pick any top level domain for example .ord
4. type a name (that is available)
5. click next
6. pick fee to send with and submit/pay invoice: pay with wallet
7. see
![image](https://github.com/leather-wallet/extension/assets/33360391/10a1e497-711f-4570-96db-4209e57e6852)

For PSBT users already are shown the dollar value like so:
![image](https://github.com/leather-wallet/extension/assets/33360391/9ed156c2-d730-4771-832f-d7dbd40c21e0)

And when sending BTC straight from the wallet we show this on the review modal:
![image](https://github.com/leather-wallet/extension/assets/33360391/f239efd1-23b7-4df4-86b8-75d9f0ba3d4e)

**Comment by markmhendrickson** [comment]
This is resolved in the new approval UX.
