### ISSUE TITLE
Utilise `@leather/prettier-config` in all packages

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4306]
Update repos with shared package
- [ ] Desktop
- [x] Extension
- [ ] Lockstacks

**Comment by pete-watters** [comment]
The extension is using the new config now. I opened a draft PR for desktop https://github.com/leather-wallet/desktop/pull/1247 

It seems to have some problems when installing it

**Comment by markmhendrickson** [comment]
I'm closing this issue since it's extension-specific.
