### ISSUE TITLE
Confirm modal "total spend" for BTC has to many decimals

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4307]
![image](https://github.com/leather-wallet/extension/assets/33360391/6ad04195-4759-40cb-a68d-79fbd9c633a2)

This should have 8 decimals. 

I would prefer if  "sending" amount was also displayed with 8 decimals at all times using padding decimals.

**Comment by edgarkhanzadian** [comment]
Unable to reproduce this issue on v6.20.0 on Chrome.

@314159265359879 does this only happen on Firefox? Can you, please, provide steps to reproduce this bug on v6.20.0? Are you able to reproduce this bug every time you get to this screen?

**Comment by markmhendrickson** [comment]
@314159265359879 can you recreate?

**Comment by 314159265359879** [comment]
I have been looking out for this. I believe it popped up while using ordinalsbot.com to mint some text inscriptions but I have not seen it pop up recently. I just created a couple testing transactions and do not see it via other platforms either. I will close this and if I do see it again log very specific reproduction steps.
