### ISSUE TITLE
Design System: Improve tabs

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4309]
Current tabs has the wrong color for the hover state

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=8651-166804&mode=dev
<img width="1418" alt="Screenshot 2023-10-03 at 13 33 47" src="https://github.com/leather-wallet/extension/assets/119523541/0b20b41d-2833-4083-9858-33cd2547b330">

**Comment by fbwoolf** [comment]
@markmhendrickson I think it is confusing to have two devs assigned to the same issue, what does this mean exactly?

**Comment by markmhendrickson** [comment]
My thought was that whichever of you gets to it first can take it. But happy to assign to just one if preferred for clarity.

**Comment by fbwoolf** [comment]
> My thought was that whichever of you gets to it first can take it. But happy to assign to just one if preferred for clarity.

O, I see, np. That works.

**Comment by markmhendrickson** [comment]
@mica000 do we currently use these tabs only on the home screen, or are there other instances you can list? 🙏

**Comment by fabric-8** [comment]
We're using the same tabs in the fee picker as well (currently implementation only showing this for BTC)

**Comment by kyranjamie** [comment]
@mica000 what are the dark mode colours?
