### ISSUE TITLE
Design System: Add toast

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4310]
![image](https://github.com/leather-wallet/extension/assets/119523541/880de914-9bfc-4ad6-a0a7-0d4789870edd)

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=12108-63748&mode=design&t=4atOHlKRSOr96Vb7-4

**Comment by kyranjamie** [comment]
And this a _callout_ per https://www.radix-ui.com/themes/docs/components/callout

**Comment by mica000** [comment]
@kyranjamie are you sure, this looks and behaves more like https://www.radix-ui.com/primitives/docs/components/toast

**Comment by kyranjamie** [comment]
Looks like, but doesn't behave like. A toast is a global element which often appears over other content in top-right/bottom-right of screen (not inline like displayed here).

**Comment by mica000** [comment]
Sorry this was lacking further description. The behavior or for this component is indeed to appear over the content and then disappear

**Comment by markmhendrickson** [comment]
@mica000 to provide standard positioning guidance, across modal and full width tab formats

**Comment by mica000** [comment]
@fabric-8 could you also take a look into this one? 
It's missing the visualisation of how toasters would work on different sizes

**Comment by fabric-8** [comment]
@mica000 I think the confusion here (toast vs. callout) partially stems from this looking quite like a callout - Mind if I suggest a slightly different design looking more like a toast floating on top?

**Comment by mica000** [comment]
> @mica000 I think the confusion here (toast vs. callout) partially stems from this looking quite like a callout - Mind if I suggest a slightly different design looking more like a toast floating on top?

Of course not :D All yours!

**Comment by fabric-8** [comment]
→ [Updated toast specs incl. guidance for animations and placement can be found here.](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=12108%3A63748&mode=design&t=ADetHVQQAzPbOe9G-1)



![Image](https://github.com/leather-wallet/extension/assets/4112698/3ad0e128-0294-4c4a-b480-71d9f68532d0)
