### ISSUE TITLE
Design System: Add callout

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4311]
https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=8651-167026&mode=design&t=GWkPk0GFV2vMVala-4

![Image](https://github.com/leather-wallet/extension/assets/119523541/c9992117-2e07-4c3c-8107-a44ad4dc79f9)

![Image](https://github.com/leather-wallet/extension/assets/119523541/b833caa4-afed-4ede-af18-879989e0c9ea)

**Comment by kyranjamie** [comment]
This is typically what I'd call a toast, re https://react-hot-toast.com/

**Comment by markmhendrickson** [comment]
I believe this issue is intended for inline notification messages whereas https://github.com/leather-wallet/extension/issues/4310 is for toasts

**Comment by mica000** [comment]
@kyranjamie and this one is more like a https://www.radix-ui.com/themes/docs/components/callout

**Comment by kyranjamie** [comment]
It's really more about how it behaves than how it looks. These are fairly simple UI elements and we can style them as we like. The behaviour isn't something we can easily change.

If this is to be placed in the corner, it's a toast. If it's inline with content how we choose, it's a callout

**Comment by markmhendrickson** [comment]
I presume once we add this callout component, we'll replace all instances such as here as part of this ticket – or should we create separate tickets for each instance where it'll need application?



![Image](https://github.com/leather-wallet/extension/assets/28991/d5d315c4-c2b5-4145-a94f-ca39d64fd8d7)

**Comment by fbwoolf** [comment]
I think for this it can be part of the same issue to replace?

**Comment by markmhendrickson** [comment]
I'm moving this to the product backlog to create an inventory of where we currently have callouts in the design, and determine whether it makes sense to update the current instances or wait on [redesigning core flows](https://www.notion.so/trustmachines/Redesign-core-flows-86f9fcad48184928bd9e5079290d1c6a?pvs=4).

**Comment by markmhendrickson** [comment]
@mica000 FYI I'm adding this to the approval UX milestone since I presume it's most immediately needed for that project

**Comment by mica000** [comment]
@markmhendrickson I see this more part of the "estab. ui" milestone since it's a dumb component several projects will use, similar to items, buttons, etc..

**Comment by fbwoolf** [comment]
@kyranjamie was there a branch you mentioned I was supposed to work from here when it was reassigned to me, or I should start something new?

**Comment by kyranjamie** [comment]
That was all I'd done basically, so no worries with the branch

```ts
import { css } from 'leather-styles/css';
import { Box, type BoxProps } from 'leather-styles/jsx';

const calloutStyles = css({
  color: 'ink.2',
  '&[data-variant="default"]': {
    backgroundColor: 'success.background',
  },
  '&[data-variant="success"]': {
    backgroundColor: 'success.background',
  },
  '&[data-variant="error"]': {
    backgroundColor: 'error.background',
  },
  '&[data-variant="warning"]': {
    backgroundColor: 'warning.label',
  },
  '&[data-variant="neutral"]': {
    backgroundColor: 'accent.non-interactive',
  },
});

interface CalloutProps extends BoxProps {
  variant?: 'info' | 'warning' | 'error' | 'success' | 'neutral' | 'default';
}
export function Callout(props: CalloutProps) {
  const { variant = 'default', ...rest } = props;
  return <Box data-variant={variant} className={calloutStyles} {...rest} />;
}
```

**Comment by fbwoolf** [comment]
It appears this issue is dependent on: https://github.com/leather-wallet/extension/issues/4831

Will do that one first.

**Comment by kyranjamie** [comment]
Replace `TestnetBtcMessage` component with callout when ready `src/app/pages/send/send-crypto-asset-form/family/bitcoin/components/testnet-btc-message.tsx`
