### ISSUE TITLE
Design System: dropdown-menu

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4312]
This ticket is about building the radix component [dropdown-menu](https://www.radix-ui.com/themes/docs/components/dropdown-menu)

Designs: https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=9344-35933&mode=design&t=hjqmbIyJGAvKngKO-4
![image](https://github.com/leather-wallet/extension/assets/119523541/dc2da02f-a2eb-4163-a86f-f9be6b46fb3f)
 

More resources
https://www.notion.so/trustmachines/Design-system-components-9e2d9e70b1a14e36bd9ed7c08515a5c1

**Comment by mica000** [comment]
@fbwoolf you mentioned that the button with token was something you were or had already tackled, correct?

**Comment by fbwoolf** [comment]
> @fbwoolf you mentioned that the button with token was something you were or had already tackled, correct?

I do have a version of this built in my current swaps PR.

**Comment by mica000** [comment]
@fbwoolf @kyranjamie how do we want to go about components that are build in between features? Should we separate them like we are doing with the selector?

**Comment by fbwoolf** [comment]
> @fbwoolf @kyranjamie how do we want to go about components that are build in between features? Should we separate them like we are doing with the selector?

Yeah, I think it is a good idea to separate, or at least make sure the code is put into a shared location while the feature is being developed. Typically, I would say best to tackled separately, but in this case it might be best for me to just separate the code in my PR since it is part of refactoring existing work not yet merged?

**Comment by mica000** [comment]
@fbwoolf Ticket for dropdown has been updated. Let me know if this works

**Comment by pete-watters** [comment]
@fbwoolf - just a heads up that for the work on the new headers, I need to [restrict the width](https://github.com/leather-wallet/extension/pull/4655/commits/ed62442ac1f496771ca7e7912b0bb22a95045269) of the `HomeHeader` to `882px`.

The current menu we have positions itself absolutely so this means on wide screens it goes far away from the trigger button:
![Screenshot 2023-12-22 at 11 19 24](https://github.com/leather-wallet/extension/assets/2938440/bf7b775a-049b-49d7-9a05-c8163339bb23)

I'm hopeful that the Radix dropdown will work better out of the box but thought I best let you know in case. You will be able to check easily enough by adding a max-width of `882px` to the `headers.tsx` base `Flex` 
![Screenshot 2023-12-22 at 11 22 10](https://github.com/leather-wallet/extension/assets/2938440/baa998be-566a-40c8-856e-044b314150a8)
