### ISSUE TITLE
Feature: Settings

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4313]
This feature uses the dropdown menu from this task https://github.com/leather-wallet/extension/issues/4312

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=10352-137977&mode=design&t=hjqmbIyJGAvKngKO-4

![image](https://github.com/leather-wallet/extension/assets/119523541/59207e34-e570-4293-aa13-0c178e79803f)

https://github.com/leather-wallet/extension/assets/119523541/da36ad7f-bf9b-4e5d-8839-825ec3bcba23

**Comment by pete-watters** [comment]
@markmhendrickson @mica000 - I'm just going to implement this now in #4370 , I hope thats OK? 

It makes sense to do as I need that new menu and it will help to fix https://github.com/leather-wallet/extension/issues/4826 and https://github.com/leather-wallet/extension/issues/4826 anyway.

**Comment by mica000** [comment]
@pete-watters Sounds great! Let me add the icons to this ticket as I forgot about this.

**Comment by markmhendrickson** [comment]
Works for me!

**Comment by mica000** [comment]
@pete-watters [Settings icons.zip](https://github.com/leather-wallet/extension/files/14210708/Settings.icons.zip)

Some of them are new, so they will need to be added to the Icons Package

**Comment by fbwoolf** [comment]
> 
> Some of them are new, so they will need to be added to the Icons Package

This process here isn't great bc I'm working on this!

**Comment by mica000** [comment]
Sorry! My bad! There is indeed an overlap between the tasks. In this case, since you are working on the Icons Package, guess they will be added there and then Pete will pull them to this feature, I assume?

**Comment by fbwoolf** [comment]
> Sorry! My bad! There is indeed an overlap between the tasks. In this case, since you are working on the Icons Package, guess they will be added there and then Pete will pull them to this feature, I assume?

Sounds good, can you add to the `Icon Export` list? Pete can keep using the `PlaceholderIcon` until I get mine merged.

**Comment by pete-watters** [comment]
@fbwoolf don't worry, I will use placeholders then consume the icons when ready 👍

Thanks!

**Comment by pete-watters** [comment]
I've implemented most of this, without the icons and using the menu items we have already. 

I am facing some weird UX issues with the sub-menu dropdown so I am deferring work on that for now and we may consider how we intend to use it. You can see in here: 

https://github.com/leather-wallet/extension/assets/2938440/51b74c29-aaab-4a5a-b9fa-659ff471242d

- we need the sub menu to open on the opposite side and it's against the natural flow
- to use the keyboard we need to use the right arrow but the menu is shown on the left
- we don't really have space to have a sub-menu in extension mode
- it's quite hard to hover and then click so it's unusable right now 

No doubt with some more work we can figure this out but for now I will just implement the basics

**Comment by mica000** [comment]
Thanks @pete-watters!
Should we provide feedback on it?
If so, could you share the link to the PR?

**Comment by pete-watters** [comment]
> Thanks @pete-watters! Should we provide feedback on it? If so, could you share the link to the PR?

Sure, share feedback if you want. I have more work to do fixing bugs but I will take it into consideration. 

It's the same PR as containers - https://github.com/leather-wallet/extension/pull/4655

**Comment by fbwoolf** [comment]
I changed the milestone for this issue bc I couldn't easily find it. It is being worked on with the container work.

**Comment by pete-watters** [comment]
Moved this into code review now as I made a final change to settings menu width so it should be complete now

**Comment by mica000** [comment]
Great work here! 👏👏👏👏👏
