### ISSUE TITLE
Design System: InteractiveItem

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4314]
As part of the effort to consolidate our components, we will need these elements to be added to our design system.

Once added, we should replace them on the following steps:

- [x] Assets list
- [x] Activity list
- [x] Send
- [x] Receive
- [x] Swap asset list
- [x] Accounts list

-----------
![image](https://github.com/leather-wallet/extension/assets/119523541/08846e5f-a626-43ec-8cde-f2ed8fda466f)
![image](https://github.com/leather-wallet/extension/assets/119523541/9d0672fe-d8ba-48d0-b6e7-9b2ef3922fe4)
![image](https://github.com/leather-wallet/extension/assets/119523541/de89f9ce-fbe2-4451-b0dd-5d37cc7a04ac)

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=2081-3746&mode=design

**Comment by markmhendrickson** [comment]
@mica000 to update so that name and content is more generic

**Comment by mica000** [comment]
@fbwoolf @markmhendrickson ticket has been updated, please review it and let me know

**Comment by kyranjamie** [comment]
To rename everywhere to content menu (we don't use context menu's anywhere in the app currently).

**Comment by kyranjamie** [comment]
From a development perspective, this is quite a broad task to tackle as it touches content from many different components.

I wonder if "_ActionItem_" might be a better name as it suggests interactivity. Suggesting waiting until Storybook is merged so these can be created and reviewed in the tool.

I'm not sure what "Section" means here. Is this content for within an input? If so, I don't think we need a component for this?

**Comment by mica000** [comment]
@kyranjamie thanks for the review.

Section is the equivalent of " <Select.Label>Vegetables</Select.Label>" in radix: https://www.radix-ui.com/themes/docs/components/select

**Comment by mica000** [comment]
@kyranjamie in relation to the naming, if we could keep the initial root the same for all would be helpful for Figma documentation.

**Comment by kyranjamie** [comment]
Can we follow the same naming as Radix, and call it `Select.Label`?

**Comment by fbwoolf** [comment]
I believe this touches the Dropdown Menu and Select components I've built already? I have built the basic list item here and the select label: https://github.com/leather-wallet/extension/pull/4765

EDIT: I was a bit unclear about the label naming too so can change from `...SectionLabel`.

**Comment by mica000** [comment]
Cool. let us know which names you will be using on the frontend so we can also update on Figma

**Comment by fabric-8** [comment]
@kyranjamie @fbwoolf Just checking in: Did you already settle on the names?

**Comment by fbwoolf** [comment]
> @kyranjamie @fbwoolf Just checking in: Did you already settle on the names?

We followed what @kyranjamie mentioned ^ `Select.Label` and `DropdownMenu.Label`.

**Comment by fbwoolf** [comment]
@mica000 is this ready to work on as a possible first step here? https://github.com/leather-wallet/extension/issues/4313

For context, Pete asked me to start with rebuilding the settings menu.

**Comment by pete-watters** [comment]
To give context here. I'll be happy if we can even just swap out the settings menu components without doing a big re-style now if they mostly look the same. 

I need to change the app `Header` and the settings menu is a part of that. At the moment, clicking to show the menu touches some logic in the state using jotai atoms (`useShowSettingsStore`).

That logic is a bit complex so I would like to put efforts into instead adding the new menu and then making things work

**Comment by mica000** [comment]
@fbwoolf how are we re-naming `item-interactive`, `item–buttons` and `item-address`?

**Comment by kyranjamie** [comment]
Would decompose issue as follows:

Notes from call
1. Create reusable styles for a kind of _InteractiveRow_ component, that can be shared between Radix and our own uses
2. Create reusable layout-only components to handle the repeating layout patterns
3. Create new buttons for the item buttons
