### ISSUE TITLE
Store swap asset info in routing

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4317]
Suggest we use a scheme of lowercase urls

```
/swap
/swap/base
/swap/base/quote
```

**Comment by fbwoolf** [comment]
Skipping this issues while https://github.com/leather-wallet/extension/pull/4425 is in flight so I don't mess up route changes.

**Comment by markmhendrickson** [comment]
I'm not entirely clear what states these paths are meant to represent?

E.g. when I use the token picker in the current swaps flow, I see `/swaps/choose-asset`



![Image](https://github.com/leather-wallet/extension/assets/28991/de0f7fbe-4bf1-4a53-ba66-eede860d3233)

**Comment by fbwoolf** [comment]
@kyranjamie is this issue still needed? Can you clarify why this is necessary? I can't say I totally understand what I'd be implementing here? So, as the user selects each token the route changes?

**Comment by kyranjamie** [comment]
> Can you clarify why this is necessary?

It's not absolutely necessary, but it's good application design. A core principal of the web is that locations have unique identifiers in the form of a URL. When building features, and even designing them, it's helpful to consider how they map to URLs, as this is easier than trying to retrofit functionality later.

> I can't say I totally understand what I'd be implementing here?

I'd suggest the implementation saves the state of which tokens are selected in the URL, rather than custom component/context state. [`useParams`](https://reactrouter.com/en/main/hooks/use-params) to get the state from router.

> So, as the user selects each token the route changes?

Yeah, that's how all exchanges work. The URL changes when you go to another trading pair.  Examples 👇🏼

<details>
<summary>Coinbase</summary>

![2024-03-20-000143@2x](https://github.com/leather-wallet/extension/assets/1618764/df57c734-55ec-4ceb-9be4-a143db180c9b)

</details>

<details>
<summary>Binance</summary>

![2024-03-20-000144@2x](https://github.com/leather-wallet/extension/assets/1618764/dc71c438-1fd7-4183-8f48-f06b58864bcf)

</details>

<details>
<summary>Kraken</summary>

![2024-03-20-000145@2x](https://github.com/leather-wallet/extension/assets/1618764/ed097c31-21aa-4de6-873d-6821cdb71340)

</details>

Benefits of building features with descriptive URLs:
- User can link directly to a trading pair
- User can bookmark trading pair
- Power user can directly modify the URL to get where they want (I do this on exchanges all the time)
- Developer can navigate directly to a specific trading pair
  - If we needed that feature, how would we build it now?
- Analytics are included out-the-box

**Comment by markmhendrickson** [comment]
I presume that this improved routing will also help with SEO once we move swaps to the web app.

**Comment by fbwoolf** [comment]
> 
> Yeah, that's how all exchanges work. The URL changes when you go to another trading pair. Examples 👇🏼
> 
> Coinbase
> Binance
> Kraken
> Benefits of building features with descriptive URLs:
> 
These are just centralized exchange pairs, I was looking for a defi swapping UI example. ALEX doesn't do it, but I do see that Jupiter does. 👍

**Comment by fbwoolf** [comment]
Just checked Uniswap does not. 🤔

**Comment by fbwoolf** [comment]
Interesting, but if I type in the pair, Jupiter does not recognize it...

![Image](https://github.com/leather-wallet/extension/assets/6493321/34de1669-2381-478c-a8d6-ea98c87d44dd)

EDIT: Must be a bug with WIF, haha, bc worked with USDC...

![Image](https://github.com/leather-wallet/extension/assets/6493321/e300feb6-a8ad-4499-ac24-6a7a758b6f1c)

**Comment by fbwoolf** [comment]
Kinda nuts Uniswap doesn't...


![Image](https://github.com/leather-wallet/extension/assets/6493321/e0c437cc-f939-4aaf-ac2c-3078433d72da)

**Comment by kyranjamie** [comment]
Don't see relevance of centralised or decentralised. Swaps and trades are effectively the same action to a user. There's an exchange of one asset for another, and the interfaces are identical. Unisat is not an example we want to follow 😅 

This isn't a discussion specific to swaps, though. It's a question of: Does it make senes for this information to go in the URL?

Examples asides, I'm curious to hear your take @fbwoolf. What is the argument against doing this?

**Comment by fbwoolf** [comment]
> 
> Examples asides, I'm curious to hear your take @fbwoolf. What is the argument against doing this?
>
I think you are mistaking my curiosity with 'arguing' against something. I think you are misreading my comments here. I don't have an argument against it. I def think it is better. I was just looking to play around with the experience of a swapping UI where the user (me) was seeing the route change based on the tokens I was selecting (or typing into the url). I just hadn't come across it before, or used. My comment on the centralized exchange was that the pairs are set up to choose from typically where I don't see that with decentralized exchanges ...but I might just be missing something there.

**Comment by kyranjamie** [comment]
All good. Sorry, I did indeed read your comments in a way thinking you were counter arguing—which is totally fine if you disagree. Gloves off 🥊

**Comment by fbwoolf** [comment]
I started on this work yest, but realized it is going to conflict quite a bit with changes in the container work with the `BaseDrawer` being removed and routing changes. I will keep this inflight, but I'm going to stall and start another issue today.
