### ISSUE TITLE
Post conditions warning text in dark mode not visible

### ISSUE THREAD

**Issue by Polybius93** [blockstack/blockstack-app#4328]
Noticed this yesterday, I use dark mode most of the time and I saw that the text color of the warning text matches the background, so it is not visible.

<img width="458" alt="Screenshot 2023-10-05 at 14 20 16" src="https://github.com/leather-wallet/extension/assets/99192647/6f98acfc-ef8e-4626-9ee1-6242ec05a761">

**Comment by fbwoolf** [comment]
It appears this has been fixed, so will close the issue...



![Image](https://github.com/leather-wallet/extension/assets/6493321/134394f7-ac1b-44c3-a2c2-764297ac67c8)
