### ISSUE TITLE
Change extension to use pnpm instead of yarn

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4329]
https://www.swarmion.dev/docs/how-to-guides/migration-guides/yarn-to-pnpm/

**Comment by pete-watters** [comment]
Closing this off as we changed the monorepo to use `npm` instead so it would work better with `expo`. 

We could potentially change the `extension` to also use `npm` but I don't think theres much to be gained from it

**Comment by kyranjamie** [comment]
Reopening now we're using pnpm again in mono.

**Comment by pete-watters** [comment]
Kyran did this in this PR https://github.com/leather-wallet/extension/pull/5075
