### ISSUE TITLE
Add sBTC specific default network config

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4330]
Easiest way to unblock sBTC devenv is to add a default network type that works with their environment.

Later we can improve the _Add Network_ functionality to cover more use cases. 

Blocked by https://github.com/leather-wallet/extension/issues/4223
Related https://github.com/stacks-network/sbtc/issues/196

**Comment by AshtonStephens** [comment]
https://github.com/stacks-network/sbtc/issues/196

Merged mempool ticket, so you should be able to connect to the api on the port 8083

**Comment by friedger** [comment]
It looks like, for devenv, the btc txs api calls are still using blockstream.info endpoint.

**Comment by friedger** [comment]
The extension btc api url is http://localhost:8999
The devenv btc api url is http://localhost:3002
