### ISSUE TITLE
Prevent send form from continuing automatically upon "Send max"

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4333]
It seems to occur both for software and Ledger wallets, in the Stacks send form specifically:

https://github.com/leather-wallet/extension/assets/28991/a53c785c-3714-4948-8e2c-9fb7a444f9ad

**Comment by kyranjamie** [comment]
I reckon we should put a default of `type=button` on LeatherButton to stop this from happening

**Comment by fbwoolf** [comment]
> I reckon we should put a default of `type=button` on LeatherButton to stop this from happening

Yeah, I noticed I had to add it with swaps so likely the prob here.
