### ISSUE TITLE
Display Ledger incompatibility message for unsupported browsers

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4334]
Currently we show the "Use Ledger" option in Firefox but upon click the page just refreshes. We should have a message that explains that it's not compatible. 

https://github.com/leather-wallet/extension/assets/28991/d568b75f-1233-444f-9c89-b77db7d5a936

**Comment by kyranjamie** [comment]
This is a regression, we used to have this.

**Comment by fabric-8** [comment]
I guess it doesn't make too much sense to have me assigned to this then? As we discussed yesterday, this just comes down to bringing a pre-existing modal back (for which the asset has already been updated)

**Comment by markmhendrickson** [comment]
@mica000 is the previous design in Figma somewhere for reference by chance?

**Comment by fabric-8** [comment]
I think it should be [this one](https://www.figma.com/file/VQPOPkkrfVcf0BEd9kz3HZ/%232275---Ledger%3A-Onboarding-%2B-Transaction-signing?type=design&node-id=2537%3A66711&mode=design&t=i2bbIqcZsgtH1XSP-1)
<img width="440" alt="Browser not supported" src="https://github.com/leather-wallet/extension/assets/4112698/dfbdfe94-e469-42b7-bd1b-868ce0d8a8ab">
