### ISSUE TITLE
Retrieval of funds wrongfully taken

### ISSUE THREAD

**Issue by anthonyfiore** [blockstack/blockstack-app#4337]
How can one retrieve assets that were unlawfully taken and which have been frozen b/c  the chain has been clog or flagged on mem pool.

 The breach started here:
![iZpMWcUB](https://github.com/leather-wallet/extension/assets/92958752/4245cfa6-8e15-4486-870a-c150ec28ded8).

The thief has connected me b/c he realizes that he can't get the wallet to transfer. 

On Stacks I believe there a “Frieger swap” that does it through smart contracts

**Comment by 314159265359879** [comment]
Hi Anthony, I understand you want to do everything you can to get your funds back. Options are however very limited once your Secret Key is compromised and funds are send out by the thief. I replied to your questions via email.  Filing a police report and contacting the local authorities will be important.

**Comment by anthonyfiore** [comment]
Ty!Sent from my iPhoneOn Oct 9, 2023, at 2:54 PM, Werner ***@***.***> wrote:﻿
Hi Anthony, I understand you want to do everything you can to get your funds back. Options are however very limited once your Secret Key is compromised and funds are send out by the thief. I replied to your questions via email.  Filing a police report and contacting the local authorities will be important.

**Comment by anthonyfiore** [comment]
Werner: I'd like to ask the Stacks Discord if anyone recognizes which exchanges use the wallets:SP22GF51PH2HRMWME1HJMDB54VFY5YMZXCMXKZ26V  or:SP2TA4FGB43WVAS8MVS6YCWTSN2BZNQ1ASGEAKSDD Reason;And then have the authorities contact the exchanges for details for those accounts and memo fields. Exchanges are where public on-chain info and private  individual accounts get mixed together. I'm by no means an expert so hopefully others who have been with Stacks longer can provide further insight.Sent from my iPhoneOn Oct 9, 2023, at 2:57 PM, Anthony Fiore ***@***.***> wrote:﻿Ty!Sent from my iPhoneOn Oct 9, 2023, at 2:54 PM, Werner ***@***.***> wrote:﻿
Hi Anthony, I understand you want to do everything you can to get your funds back. Options are however very limited once your Secret Key is compromised and funds are send out by the thief. I replied to your questions via email.  Filing a police report and contacting the local authorities will be important.
