### ISSUE TITLE
Brand audit: Fix colors in Send screen  empty 0 and Enter recipient address

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4345]
Follow up work from https://github.com/leather-wallet/extension/issues/4249 
![Screenshot 2023-10-11 at 15 00 38](https://github.com/leather-wallet/extension/assets/2938440/da3306a0-1a1a-479c-b107-4c63c931464c)

**Comment by pete-watters** [comment]
@mica000 @fabric-8 : this text is for input placeholders. Should I make a global change so that app wide all placeholder text is the same colour?

**Comment by pete-watters** [comment]
I also need to update the disabled colour of `TextInput`s as per https://github.com/leather-wallet/extension/pull/4343/files/1a0b49ac2407a25db031bb5a34f6c8c301b168e2#r1355342845

**Comment by mica000** [comment]
yes, this is the latest color scheme. 

Placeholders are called text-subdued
 
<img width="610" alt="Screenshot 2023-10-16 at 12 57 26" src="https://github.com/leather-wallet/extension/assets/119523541/9c99d15a-b619-4014-aff7-76bb37109076">

:root {
  /* Value */
  /* colors */
  --color-blue-dark-blue-100: #e6f2ff;
  --color-blue-dark-blue-300: #9bcaff;
  --color-blue-dark-blue-500: #3795ff;
  --color-blue-dark-blue-600: #057aff;
  --color-blue-light-blue-100: #e6f2ff;
  --color-blue-light-blue-300: #9bcaff;
  --color-blue-light-blue-500: #3795ff;
  --color-blue-light-blue-600: #057aff;
  --color-brown-dark-1: #12100f;
  --color-brown-dark-10: #ded6cd;
  --color-brown-dark-11: #ded6cd;
  --color-brown-dark-12: #f5f1ed;
  --color-brown-dark-2: #2c2a24;
  --color-brown-dark-3: #4a423b;
  --color-brown-dark-4: #34312a;
  --color-brown-dark-5: #12100f;
  --color-brown-dark-6: #716a60;
  --color-brown-dark-7: #8f887d;
  --color-brown-dark-8: #c6b9ad;
  --color-brown-dark-9: #f5f1ed;
  --color-brown-light-1: #ffffff;
  --color-brown-light-10: #64594d;
  --color-brown-light-11: #4a423b;
  --color-brown-light-12: #12100f;
  --color-brown-light-2: #f7f5f3;
  --color-brown-light-3: #f5f1ed;
  --color-brown-light-4: #eae5e0;
  --color-brown-light-5: #e4ddd6;
  --color-brown-light-6: #ded6cd;
  --color-brown-light-7: #d8cec4;
  --color-brown-light-8: #c6b9ad;
  --color-brown-light-9: #948677;
  --color-green-dark-green-100: #e6f5ed;
  --color-green-dark-green-300: #99d8b9;
  --color-green-dark-green-500: #33b172;
  --color-green-dark-green-600: #009e4f;
  --color-green-light-green-100: #e6f5ed;
  --color-green-light-green-300: #99d8b9;
  --color-green-light-green-500: #33b172;
  --color-green-light-green-600: #009e4f;
  --color-grey-dark-1: #ffffff;
  --color-grey-dark-10: #808080;
  --color-grey-dark-11: #646464;
  --color-grey-dark-12: #12100f;
  --color-grey-dark-2: #f9f9f9;
  --color-grey-dark-3: #f1f1f1;
  --color-grey-dark-4: #ebebeb;
  --color-grey-dark-5: #e4e4e4;
  --color-grey-dark-6: #dddddd;
  --color-grey-dark-7: #d4d4d4;
  --color-grey-dark-8: #bbbbbb;
  --color-grey-dark-9: #8d8d8d;
  --color-grey-light-1: #ffffff;
  --color-grey-light-10: #808080;
  --color-grey-light-11: #646464;
  --color-grey-light-12: #12100f;
  --color-grey-light-2: #f9f9f9;
  --color-grey-light-3: #f1f1f1;
  --color-grey-light-4: #ebebeb;
  --color-grey-light-5: #e4e4e4;
  --color-grey-light-6: #dddddd;
  --color-grey-light-7: #d4d4d4;
  --color-grey-light-8: #bbbbbb;
  --color-grey-light-9: #8d8d8d;
  --color-overlay-black-50: #12100f80;
  --color-red-dark-red-100: #fceeed;
  --color-red-dark-red-300: #ffabb1;
  --color-red-dark-red-500: #ff5863;
  --color-red-dark-red-600: #ff2e3c;
  --color-red-light-red-100: #fceeed;
  --color-red-light-red-300: #ffabb1;
  --color-red-light-red-500: #ff5863;
  --color-red-light-red-600: #ff2e3c;
  --color-yellow-dark-yellow-100: #fef9e6;
  --color-yellow-dark-yellow-300: #fbe699;
  --color-yellow-dark-yellow-500: #f7cd33;
  --color-yellow-dark-yellow-600: #f5c000;
  --color-yellow-light-yellow-100: #fef9e6;
  --color-yellow-light-yellow-300: #fbe699;
  --color-yellow-light-yellow-500: #f7cd33;
  --color-yellow-light-yellow-600: #f5c000;
}

**Comment by pete-watters** [comment]
The latest colours were added here https://github.com/leather-wallet/extension/pull/4964
