### ISSUE TITLE
Design System - Add containers

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4370]
This issue is a new version of 4165 but with a more specific scope. The task is to implement a re-usable set of containers for page `Header` and `Footer` as per:

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=5056-60851&mode=design&t=CbvgKq8c4jj6eRZE-0

<img width="745" alt="272258460-6d12ef9e-c89a-4d1a-b2de-6ed02c829209" src="https://github.com/leather-wallet/extension/assets/2938440/fb9e7f4f-ae9c-4d84-bc01-f662ca1b8b5d">
<img width="1429" alt="272258431-c40a35d3-a825-42a1-b2a6-5483bbb90492" src="https://github.com/leather-wallet/extension/assets/2938440/a499288c-f50b-46c1-886a-35926497035f">

The headers should be generic but will need to have some context provided as they will show different information in different views. e.g. in `extension` view, they need to show the network / account 

This task relates to #4371 and  builds upon #4165

**Comment by pete-watters** [comment]
@markmhendrickson : we had a call yesterday to clear up the scope of #4165 . We have split up the work into two issues #4370 and #4371 

CC @mica000 @kyranjamie @fabric-8

**Comment by markmhendrickson** [comment]
Thanks @pete-watters – can this particular issue be closed or is there more that remains for it specifically?

**Comment by pete-watters** [comment]
This one needs to be open as the work isn't done yet. This one is closed correctly

https://github.com/leather-wallet/extension/issues/4165

**Comment by pete-watters** [comment]
As part of this task, consideration needs to be given to the colour of the header as per: https://github.com/leather-wallet/extension/issues/4253#issuecomment-1789398327

**Comment by markmhendrickson** [comment]
Related: https://github.com/leather-wallet/extension/issues/4615#issuecomment-1834709417

**Comment by pete-watters** [comment]
Checking my new PR and setting the extension + popup width to `390` seems to resolve [this issue](https://github.com/leather-wallet/extension/issues/4615#issuecomment-1834709417)

As we begin to scale up, past `390px` width it starts to look buggy and weird again. I will see if I can improve it at the next breakpoint but I'm unsure how important that is if it looks OK in the standard popup size 


https://github.com/leather-wallet/extension/assets/2938440/94b948b8-110c-45c2-b7d3-ae58e255a2ea

**Comment by mica000** [comment]
@pete-watters Would it work to set the header width to 100% of the view port?

**Comment by pete-watters** [comment]
> @pete-watters Would it work to set the header width to 100% of the view port?

I can give it a try for the header, that will likely work. My point is do we want to have full responsiveness on all screens from `sm` `390px` all the way to `lg` . 

We could need to have an idea how the page responds at different widths. For example the header should stretch here but also the content width should extend too. 

I'll get it working well in the main sizes and then see about the interim widths

**Comment by mica000** [comment]
> My point is do we want to have full responsiveness on all screens from sm 390px all the way to lg .

Yes!!! that would be great: full responsiveness on all screens from sm 390px all the way to lg.

cc @fabric-8

**Comment by pete-watters** [comment]
I've been progressing well on this:
- making the home header consistent 
- improving the page headers

Yesterday @mica000 and I were speaking as for some pages with a two column layout we need to make some slight design tweaks to help us make things more consistent. That overlaps with https://github.com/leather-wallet/extension/issues/4423

To give more context, for the key entry / password screens:
- most of the right column cards are fixed at `600px`
- the password / unlock screen has a fixed width of `500px`
- we don't have a specific header for those pages so we will work on that
- the password session lock / unlock screen also needs to work on `extension` / `popup` mode and look well

**Comment by fabric-8** [comment]
@pete-watters Michelly and I discussed header/footers the other day and would love to update the behaviour — Besides both being sticky, we'd also love to add a divider border to the header once content is scrolled — [Here's a basic documentation of this change](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=11435%3A52079&mode=design&t=VExjCV1J6846EHCO-1).

Please ping me if you have any questions or if there's the need for further discussion!

**Comment by markmhendrickson** [comment]
Note this work will fix the layout issues with the unlock screen during auth:

![image](https://github.com/leather-wallet/extension/assets/28991/06884882-669e-49bd-a2cf-a102e8be1aea)

**Comment by pete-watters** [comment]
@fabric-8, OK that's no problem. Better to do it now. 

I had the footer being sticky so I will update it to also have a sticky header with a border showing for both on scroll.

**Comment by mica000** [comment]
> Note this work will fix the layout issues with the unlock screen during auth:
> 
> ![image](https://private-user-images.githubusercontent.com/28991/295112154-06884882-669e-49bd-a2cf-a102e8be1aea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODgyMTUsIm5iZiI6MTcwNDc4NzkxNSwicGF0aCI6Ii8yODk5MS8yOTUxMTIxNTQtMDY4ODQ4ODItNjY5ZS00OWJkLWEyY2YtYTEwMmU4YmUxYWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA4MTE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNDEwMDk1MTY4M2ZjMTBkYzJhYzBiZDI5Mjg2NGNmOWU4NmZkMDZlN2Y2NGQxYzIxNDQyNmU2MGU3OThjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JdWntPYtQlTlSuGC_vWobJzMkK5OEqMb01ojj3xtlWE)

@markmhendrickson Indeed! Here are the designs covering the onboarding flows: https://www.figma.com/file/2stUYm67q6Tkwe31CshODA/Onboarding?type=design&node-id=1%3A16709&mode=design&t=UX0gMMYcB50sCJHM-1
