### ISSUE TITLE
Design System - Full page extension views

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4371]
When working on https://github.com/leather-wallet/extension/issues/4165 it became apparent that more changes would be needed to support the new design. 

It's desired that for most screens:
- when in extension view we should fill the screen
- a lot of screens we use are modals
- these need to
    - be a modal when in full screen mode
    - change to be a page when in extension view
    - have context specific headers when in extension view

<img width="1429" alt="272258431-c40a35d3-a825-42a1-b2a6-5483bbb90492" src="https://github.com/leather-wallet/extension/assets/2938440/3b5dfcbf-0619-4dd7-a0d6-0adb510b4214">

This task relates to #4370 and builds upon #4165

------

Add resource in designs
<img width="462" alt="Screenshot 2023-11-21 at 17 35 20" src="https://github.com/leather-wallet/extension/assets/119523541/b5e77f9d-ce4c-4a11-81de-2d138de22dd1">

**Comment by pete-watters** [comment]
@markmhendrickson : we had a call yesterday to clear up the scope of #4165 . We have split up the work into two issues #4370 and #4371 

CC @mica000 @kyranjamie @fabric-8

**Comment by pete-watters** [comment]
This issue needs to also fix this: https://github.com/leather-wallet/extension/issues/4477

**Comment by pete-watters** [comment]
Related to issue https://github.com/leather-wallet/extension/issues/4477 this issue also needs to resolve https://github.com/leather-wallet/extension/issues/4549 

When working on this we can also add our own custom scroll bars and fix the other issues listed in
https://github.com/leather-wallet/extension/issues/3488

**Comment by pete-watters** [comment]
We had another report of issues with the account select list we need to solve here https://github.com/leather-wallet/extension/issues/4568

**Comment by markmhendrickson** [comment]
I presume the Ledger-specific modals will also be covered by this general update?

![Image](https://github.com/leather-wallet/extension/assets/28991/5410c23e-d72b-4cb3-a435-437cb3d0e438)

**Comment by pete-watters** [comment]
> I presume the Ledger-specific modals will also be covered by this general update?
> 
> ![Image](https://private-user-images.githubusercontent.com/28991/286298671-5410c23e-d72b-4cb3-a435-437cb3d0e438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODQzOTUsIm5iZiI6MTcwMTE4NDA5NSwicGF0aCI6Ii8yODk5MS8yODYyOTg2NzEtNTQxMGMyM2UtZDcyYi00Y2IzLWE0MzUtNDM3Y2IzZDBlNDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE1MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZWU3Yzg2NjNkNmY0MmM0ODI1OWYyNmFlZWY0YjcwN2QyNjU3ZThkYTYxMGI2ZTUxZTBkMDAzMDExNzk1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ze2a-pq2EpazDoDOgd6URVuwKYo7mjoyRB0OC7U9FCA)

We will have to do it for all modals so they look OK in pop-up mode so we will include Ledger also.

In your screenshot, that's actually in pop-up mode, so I guess we should also include it there too

**Comment by pete-watters** [comment]
I've been working on this as part of [this PR](https://github.com/leather-wallet/extension/pull/4655/). In order to create containers, it first makes sense to fix this issue of modals / full page views

**Comment by pete-watters** [comment]
@markmhendrickson : I've opened a PR with this work done. I added a demo video you can see [here](https://github.com/leather-wallet/extension/pull/4655#issue-2030568178)

**Comment by pete-watters** [comment]
I've made some good progress with this but there are still some bugs I need to fix in the PR. 

I'll fix those and then get to work creating re-usable headers / footers

**Comment by pete-watters** [comment]
Another fix to be included here is https://github.com/leather-wallet/extension/issues/4714

We had an external contributor open [this PR](https://github.com/leather-wallet/extension/pull/4720) which adds a workaround but the issue is more to do with the screen height not responding properly so I will take it into consideration for containers and fix it properly.

**Comment by pete-watters** [comment]
There's [some changes](https://www.figma.com/file/2stUYm67q6Tkwe31CshODA/Onboarding) to make to the onboarding screens that affect the headers so I will tackle those also and do everything together.

**Comment by pete-watters** [comment]
I'm still working on this but giving a progress update. This week I've:

- finished the new onboarding screens which includes keeping the `action popout` bg black regardless of theme
- setup `Header` + `Footer` components in Storybook 
- Swapped out `Footer`s in the extension for the new UI Library version
- Made some updates to storybook to
    - add our own specific breakpoints
    - implement some structure organisation (first draft)

Next up to move on with this is to:
- refactor the `extension` to use the new `Header` component
    - this will take some work as we use some things in `Header` that rely on context - navigation + network
    - I'll refactor those and then replace all the `Header`s with the UI library
- add the remaining layout components to storybook
    - ideally this will allow us to have full demo page in there
- re-work the full PR to clean up loose ends and give a final test

Here's a demo video explaining a bit more:


https://github.com/leather-wallet/extension/assets/2938440/a686cab6-d04e-42d2-b4e9-40a7dec17e4c

**Comment by mica000** [comment]
A MA ZING! Literally clapping over here. Also great demo! Thanks Pete!

About the Ledger hovering state - so it currently only happens when you hover the logo?

**Comment by pete-watters** [comment]
> A MA ZING! Literally clapping over here. Also great demo! Thanks Pete!
> 
> About the Ledger hovering state - so it currently only happens when you hover the logo?

Thanks! My first attempt using Screen Studio. Thanks to Fab for the recommendation. 

Yeah I found some code in the ledger dialogs that was showing this message but only on hover. I'm not sure if it's behaviour we still need. I'll find out when setting up the header there.

**Comment by markmhendrickson** [comment]
Nice work, @pete-watters! The demo is fantastic – thanks for pulling it together.

Also I do recommend we remove that Ledger-specific message: https://github.com/leather-wallet/extension/issues/4689

**Comment by pete-watters** [comment]
> Nice work, @pete-watters! The demo is fantastic – thanks for pulling it together.
> 
> Also I do recommend we remove that Ledger-specific message: #4689

Thanks @markmhendrickson 🙇 

I'll get rid of the Ledger message so. That simplifies things and will help make the headers more generic

**Comment by pete-watters** [comment]
I have been hard at work on this again this week but it will still take some more time to complete. I estimate one more week, maybe even two to have it well tested and reviewed. As I work on this I have been encountering and fixing technical debt issues along the way.

This week I: 
- got a prototype working of using our new `DropDown` for the settings menu
- replaced all existing page and dialog headers with our new `Header` component
    - part of this involved a huge refactor of how we were previously setting headers
        - previously we stored then in `jotai` state management on a per page basis 
        - this meant we were doing a lot of re-renders on each page
        - I have changed this to use a route lookup function to help which is not ideal but is a good temporary solution
    - other work here involved refactoring how we set the `<NetworkModeBade` so it's set at a higher level 
- implemented our new page background colour variants
    - `home` page has a background colour of `accent.background-primary`
    - `page` pages (other non onboarding pages) have a background colour of `accent.background-secondary`

The next work I need to do is to:
- refactor the `popout` pages which are still using a legacy `PopupHeader`
- looking at the design for this and there will be some work for me to do updating the `account` display also
![Screenshot 2024-01-26 at 10 49 06](https://github.com/leather-wallet/extension/assets/2938440/af08cf84-8592-4a5c-864b-986e47092816)
- finish work on two-column layout for mnemonic keys
- finish work on new set-password page + onboarding pages
- add new container pages to `storybook` so we can visualise each page

**Comment by mica000** [comment]
Great to see it's coming along! the hark work will pay off tons in the future!

**Comment by pete-watters** [comment]
I added a progress update of last weeks work [here](https://www.notion.so/trustmachines/for-week-of-db3b33a712b44dd289ca56476391ea52?pvs=4#8df462346f9a4cd594d10b2304d02e91)

I am working on pop-out headers now and documenting the decisions I make here. Please let me know if I miss something or am mistaken. 

Of the **extension headers** we have (screenshot [here)](https://github.com/leather-wallet/extension/issues/4371#issuecomment-1911853557), I am organising into these types. 

### Dialog Headers 

These are shown in dialogs / cards inside the APP 

![Screenshot 2024-01-31 at 13 25 30](https://github.com/leather-wallet/extension/assets/2938440/f86c0aad-3e72-42f0-b5ab-9e12b88846d7)


### Popout Headers 
These are shown in popout windows triggered by interactions

- authentication
- sign 
- psbt etc. 

I checked the code and we have a few different types of these popouts for different reasons. We use different paths to signify their intention. The paths I found are, based on the Test APP are:

- `#/update-profile`
- `#/signature`
- `#/psbt`
- `#/transaction`
- `#/get-addresses` 

Some of these may be outdated or I may have missed some but this is a good start and I will apply the following headers for each. I have provided a screenshot of the old and new behaviour of these popouts. 
**note: The new is WIP so not yet correct**

### update-profile
Will use this new header:
![Screenshot 2024-01-31 at 13 30 30](https://github.com/leather-wallet/extension/assets/2938440/08f37c42-22f1-4f0b-8325-ea07b3b32327)

Current **OLD** and **NEW**
![update-profile](https://github.com/leather-wallet/extension/assets/2938440/7916fd96-25b5-4bc6-aee9-927909dcdf2f)


### signature
Will use this header but with **no action menu** unless desired
![Screenshot 2024-01-31 at 13 31 31](https://github.com/leather-wallet/extension/assets/2938440/2bf4b9b0-f59f-4e2f-ad07-880830189395)

Current **OLD** and **NEW**
![signature](https://github.com/leather-wallet/extension/assets/2938440/44584df5-1ab9-4cca-9458-41b838f845ba)


### psbt
Will use this header:
![Screenshot 2024-01-31 at 13 32 33](https://github.com/leather-wallet/extension/assets/2938440/49c989b8-fe15-4d14-95b0-29bff98b1376)

Current **OLD** and **NEW**
![psbt](https://github.com/leather-wallet/extension/assets/2938440/44125784-1efe-48af-a49b-1f7121c45368)

### transaction
Will use this header:
![Screenshot 2024-01-31 at 13 33 53](https://github.com/leather-wallet/extension/assets/2938440/c9f6f4f8-04ec-4595-99d2-bd273490c846)

Current **OLD** and **NEW**
![transaction](https://github.com/leather-wallet/extension/assets/2938440/c51ea715-a37d-4bad-92ca-f4f3f95ab12e)

### get-addresses
Will have no header as per previous design, unless desired 

![get-addresses](https://github.com/leather-wallet/extension/assets/2938440/f1a6e88a-5d48-4aa7-9378-dd907a12b619)

Of the above, it's unclear to me if some of these should instead use these other headers:
- Logo + right icon
- Logo + account
- Logo approval UX

![Screenshot 2024-01-31 at 13 35 52](https://github.com/leather-wallet/extension/assets/2938440/5143b074-9cb0-460f-b364-5f487b6952de)

@fabric-8 @mica000 @markmhendrickson: My plan is to implement as per detail above but if this is incorrect please let me know so I can make adjustments

**Comment by fabric-8** [comment]
Thanks a lot for all the work and the super clear update @pete-watters ! Guess I'll be blocking out a day soon to fully test the update once it's ready 😅

**Comment by pete-watters** [comment]
> I presume the Ledger-specific modals will also be covered by this general update?
> 
> ![Image](https://private-user-images.githubusercontent.com/28991/286298671-5410c23e-d72b-4cb3-a435-437cb3d0e438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTUyMjYsIm5iZiI6MTcwODQ5NDkyNiwicGF0aCI6Ii8yODk5MS8yODYyOTg2NzEtNTQxMGMyM2UtZDcyYi00Y2IzLWE0MzUtNDM3Y2IzZDBlNDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA1NTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1Nzk5MTA4Yjg1ZWE3ZGI4MzU5MGE0YTZlYjBjYjdhMzI2NzJhZGJlZTFjOTE0YWRkNmRkZjExMDJhZTcxNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vV1MsLuKkQAr4SbNHFDerJPp1P3tukXz94KGH3EdWVk)

I've been checking this @markmhendrickson and I have improved the dialog the ledger notifications show up in but I noticed a lot of them already have padding issues in production. 

It might be prudent to fix those screens also but maybe in a subsequent PR once the main one is merged.

**Comment by mica000** [comment]
### Update Recipe of Dialog with BitTitle:

Designs for [Receive Asset](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=14023-114416&mode=design&t=4aQkudsuBylnB9IO-4), [Receive collectible](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=14023-115948&mode=design&t=4aQkudsuBylnB9IO-4), [Choose asset to send](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=14048-137261&mode=design&t=4aQkudsuBylnB9IO-4)



What we need:

### **1. Remove BigTitle from Recipe**

This is the new recipe for the existing BitTitle Dialog (Maybe we want to call it smt else now that it wont have a BigTile? For now naming it EmptyDialoag;). As you can see the Action pop-up will have the header always present, but only showing the arrow back.

<img width="1490" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/d6a9f31c-cb20-445a-8a51-a1270171ca6e">



---

### **2. Add BigTitle Component to Content Containers**

Steps that need this:
- Send / Choose asset
- Receive asset
- Add collectible

@pete-watters keeping the padding 24px; 

<img width="656" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/6f187a2b-b6e9-4529-9c99-af44b7ce2b55">
<img width="1091" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/fa56c21e-e9a5-4772-bd5b-06b54fc356f3">
<img width="657" alt="Screenshot 2024-02-28 at 17 34 09" src="https://github.com/leather-wallet/extension/assets/119523541/1062437d-b429-40b0-a5f4-2f43a0128c5e">
<img width="726" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/beaa779f-0529-407c-b4ed-97f5ba2a6bec">




**This is how they are build:**
<img width="667" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/58f2f9ba-9ca7-46ca-99ee-56a3477f41b0">


---

### **3. Add logic to show and hide close button**

We need a logic that, 
when on Action Pop-up and on FullPages, hides the close button. 
when on EmptyDialog, shows close button. 

<img width="1382" alt="Screenshot 2024-02-28 at 17 42 09" src="https://github.com/leather-wallet/extension/assets/119523541/ba597c71-f765-4ca7-8854-39dafcd5231d">
<img width="1402" alt="Screenshot 2024-02-28 at 17 41 58" src="https://github.com/leather-wallet/extension/assets/119523541/a70c7f54-cad6-468f-a8cf-753152dda241">
<img width="1399" alt="Screenshot 2024-02-28 at 17 41 48" src="https://github.com/leather-wallet/extension/assets/119523541/b8e17728-ddf2-4547-a374-472f824c8e8c">

**Comment by pete-watters** [comment]
Sounds good @mica000, thanks!

@markmhendrickson This type of thing is why I am pushing for written specs / graphs, something. We need to consider how user flows link together when creating designs. Not just for development, but so we have a clear plan of what we are doing.

This issue of inconsistent flows isn't new, it's actually how Leather already works so we could have planned for this change originally by deciding how we wanted it to work and avoided so much of this re-work and changes
