### ISSUE TITLE
UI bugs on BITCOIN FOR THE REST OF US  page

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4374]
I think we broke this as it used to be working fine?
BITCOIN FOR THE REST OF US is pushing the content down and in turn we cant see the CTA

<img width="1440" alt="Screenshot 2023-10-16 at 12 26 21" src="https://github.com/leather-wallet/extension/assets/119523541/d3d280fb-f7ea-4cec-8cd6-ff2d71ff9f51">

**Comment by kyranjamie** [comment]
I think we had a Stacks.js CSS reset @pete-watters removed that was resetting a locally defined h1 margin. I've removed all local CSS resets in favour of Pandas, which fixes this.
