### ISSUE TITLE
Remove `@stacks/ui`

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4379]
Divide and conquer

- [x] #4380
- [x] #4381
- [x] #4382
- [x] #4383
- [x] #4384

**Comment by pete-watters** [comment]
Thanks for opening this. I tried to remove some of this before in these PRs, just linking to serve as a reference:
- [Stacks UI lib removal](https://github.com/leather-wallet/extension/pull/4196)
- [Stacks Theme Provider removal](https://github.com/leather-wallet/extension/pull/4179)
- [Stacks UI Utils Removal](https://github.com/leather-wallet/extension/pull/4180)

Along the way I found:
- We can get rid of `<Text` and use `<styled.span` etc.
    - We can also do this for `<Title` and other components in `app/components/typography` 
- We sometimes have `<Box as='` which we can replace 
    - `<Box as='li` => `<styled.li`
    - `<Box as='img` => `<styled.img`
    - `<Box as={BtcIcon} />` => `<BtcIcon />`
- We need to replace the old tokens for spacing and font sizes
    - `'base-loose'` doesn't have a size in the new system
        - I think we agreed to change it to `16px` - aka `space.04` / (`base`) 
    - sometimes we have `fontSize={1}`, `fontWeight="500"`  which we need to replace
