### ISSUE TITLE
Duplicate ordinals showing in the wallet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4387]
This looks like the issue we've seen before with Stacks NFT's. https://github.com/leather-wallet/extension/issues/3712 but I have not seen that recently. 

The example below is in wallet version 6.5.1 on Firefox. The user said it showed these duplicate ones after they sent two other ordinals #[26523037](https://mempool.space/tx/fd1d134e923db8c25e74e0ebbf0dfb10496d5b7f6f4f2e04bc53e1756bd48021)and #[26523038](https://ordiscan.com/inscription/26523038). 

This is what is displayed in the wallet:
![image](https://github.com/leather-wallet/extension/assets/33360391/a28ec18f-4a2b-4f87-9179-dade3cbce33c)

Related address, naturally only has one inscription #50600:
https://ordinals.hiro.so/inscriptions?a=bc1p4s45qavhf04ltzfgfhppeuvyac6eavjpqy5g8yk7f0p3wtndcy8qzynh49&p=1

The other user who reported this prior, noticed a similar issue with 6.9.2 of the wallet on Chrome:
Related address: [bc1p98rqntc3xjyq2lurft709q8vw8wluq96tp98r96925hmaezeh09q8qdysj](https://ordinals.hiro.so/inscriptions?a=bc1p98rqntc3xjyq2lurft709q8vw8wluq96tp98r96925hmaezeh09q8qdysj) 
![image](https://github.com/leather-wallet/extension/assets/33360391/db6e463d-006b-436c-aa93-75c1b584d02b)

**Comment by 314159265359879** [comment]
The first user says the bug is not visible when they install 6.9.11 on Chrome and check their wallet. Could this be caused by a caching issue?

**Comment by alter-eggo** [comment]
@314159265359879 yeah, probably, not sure here

**Comment by pete-watters** [comment]
@314159265359879 did we have any more reports of this? It seems like quite an old version - `6.9.11`. Perhaps we can close it off?
