### ISSUE TITLE
Load with dark background in dark mode to prevent white background flash

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4398]
https://github.com/leather-wallet/extension/assets/28991/bddf131b-8e56-448c-9c7e-40591e8de2e2

**Comment by pete-watters** [comment]
I took a look at this as I thought I could fix it easily but it's actually a bit tricky. I'll come back to it soon.

Some WIP branches:
- `fix/4398/darkmode-background-flashs`
- `fix/4398/darkmode-background-flash`
