### ISSUE TITLE
Redirect user to home upon sign out from lock screen

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4405]
Right now they remain on the lock screen which is inconsistent with having no session anymore

**Comment by fbwoolf** [comment]
Just ran into this, and if you try to sign out again you get this error...

<img width="1289" alt="Screen Shot 2023-11-03 at 9 59 32 AM" src="https://github.com/leather-wallet/extension/assets/6493321/8f56ebb5-5e1b-49e0-a152-1736e1424589">
