### ISSUE TITLE
Show fiat value for BRC-20 balances

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4408]

**Comment by markmhendrickson** [comment]
Prices can be found via [the Best in Slot API](https://docs.bestinslot.xyz/reference/api-reference/ordinals-and-brc-20-and-bitmap-v3-api-mainnet+testnet/brc-20)

**Comment by fbwoolf** [comment]
> Prices can be found via [the Best in Slot API](https://docs.bestinslot.xyz/reference/api-reference/ordinals-and-brc-20-and-bitmap-v3-api-mainnet+testnet/brc-20)

Think this one might be on hold too after starting it? Doesn't get logged with the response, and confirmed in docs...

<img width="502" alt="Screenshot 2024-03-26 at 11 47 44 AM" src="https://github.com/leather-wallet/extension/assets/6493321/181183b8-3016-4a2b-8d62-a01f6f32a81b">

**Comment by fbwoolf** [comment]
@markmhendrickson any movement here or should I move back into backlog?

**Comment by fbwoolf** [comment]
@alter-eggo can you update me on why this method and `getBrc20TickerData` are unused for BIS atm? https://github.com/leather-wallet/extension/blob/1cd26250dde7b46146e5da48fbe355e682b8c966/src/app/query/bitcoin/bitcoin-client.ts#L129

Were we waiting for the pro tier to remove Hiro completely?

EDIT: It does appear to work just by swapping out the apis and using `https://leatherapi.bestinslot.xyz/v3` ...but let me know if I am supposed to completely remove use of Hiro api here? PR is up here: https://github.com/leather-wallet/extension/pull/5179

**Comment by alter-eggo** [comment]
@fbwoolf yeah, waiting for pro tier, as free one is too tight for our needs... 
we prob want to leave hiro api as is? in case we need a fallback for BiS?

**Comment by fbwoolf** [comment]
@markmhendrickson @kyranjamie is it possible the price data provided by BiS is in sats and not USD? I may have messed this up bc @brandonmarshall-tm believes the values are off (high). It seems like if I use sats it is more accurate?

![Screenshot 2024-04-24 at 3 24 48 PM](https://github.com/leather-wallet/extension/assets/6493321/c27ee80f-c009-4470-b7ce-17a1c4ca8f04)

EDIT: I asked in the TG channel.

**Comment by brandonmarshall-tm** [comment]
![Screenshot 2024-04-24 at 2 01 45 PM](https://github.com/leather-wallet/extension/assets/122313287/fc97b5c1-6ee2-4abe-8513-793557ea5c24)

For example:
1 TRIO is worth ~0.00005440 BTC so my USD balance should be ~$6960 and unfortunately not the over $100k listed 😉

Price comparisons:
https://www.coingecko.com/en/coins/sats-ordinals
https://www.coingecko.com/en/coins/zbit-ordinals
https://www.coingecko.com/en/coins/trio-ordinals

**Comment by fbwoolf** [comment]
It looks like we should be taking advantage of more pricing data from coingecko? Do we have an api key?
