### ISSUE TITLE
Design System: select

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4417]
**This ticket is about building the radix component [select](https://www.radix-ui.com/themes/docs/components/select)**

![image](https://github.com/leather-wallet/extension/assets/119523541/90d4ebb3-02b6-49e3-bcc7-aab271244a10)
https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=9369-13353&mode=design&t=hjqmbIyJGAvKngKO-4

ps: Design specs for this one are similar to the [dropdown](https://github.com/leather-wallet/extension/issues/4312). Both are triggered by a button, however the selector displays a list of options for the user to pick from.

More resources
https://www.notion.so/trustmachines/Design-system-components-9e2d9e70b1a14e36bd9ed7c08515a5c1

**Comment by mica000** [comment]
@fbwoolf could you also review this one?

**Comment by fbwoolf** [comment]
This issue is dependent on work from: https://github.com/leather-wallet/extension/issues/4312
