### ISSUE TITLE
Design System: Button (and stories)

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4418]
EDIT: This issue will now be tracking the coordination of all button variants and creating stories for them.

I believe we already build this on the swap but not sure if we need to improve it

This ticket for the button with tokens, used for swaps.
I believe we already build this on the swap but not sure if we need to improve it?

These are the states on designs
_Default, Hover, Active, Focused, Disabled_
<img width="974" alt="Screenshot 2023-10-24 at 16 21 08" src="https://github.com/leather-wallet/extension/assets/119523541/de9fc6de-a34d-4d2a-8c70-03a251ec5850">

- [ ] [button with tokens ](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=10031%3A1573&mode=design&t=DJZGBcWaVMjlZYsG-1)
- [ ] [avatars](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=1574-27&mode=design&t=ymvCW615ZgkyuVna-4) (There is a safety border on them now)

**Comment by mica000** [comment]
@fbwoolf and finally, could you also review this one? I believe it's 90% done?

**Comment by fbwoolf** [comment]
I don't think the component should be name here with `token` bc that is too specific, should it be `ButtonWithIcon`? It could be anything, not just a token icon, correct?

**Comment by mica000** [comment]
True! Maybe avatar? since icon there are instances of an avatar with an icon inside.

**Comment by fbwoolf** [comment]
When I look at Radix, I feel like `Avatar` is always associated to a user, is that not how you think about it?
https://www.radix-ui.com/themes/docs/components/avatar

**Comment by pete-watters** [comment]
`token` buttons and `avatar` buttons seem to be the same as `ghost` but with different child elements. 

I would keep the name `Avatar` for user avatars only and maybe we can just have 3 button variants:
- solid
- outline
- ghost

I don't really understand what `token` is for, it looks like a `DropDownTrigger` ? 

In any case, the `Button` doesn't need to know what's inside it. So it could be a `ghost` that has an icon child / a dropdown trigger

**Comment by mica000** [comment]
>I don't really understand what token is for, it looks like a DropDownTrigger ?

Yes, used to trigger the swaps and possibly send in the future.

>So it could be a ghost that has an icon child / a dropdown trigger

Good point.. we could do this - however the icon and token/avatar have different sizes. Considering the new icon package has 24px, avatar/token have 32px, the size of the "button with tokens" is slightly bigger, 48px. Hence, fine to use the `ghost` variant as long as the size adapts to it. The padding all around them should be 8px (this value was also updated recently with the introduction of new icon set - before it was 12px)

**Comment by fbwoolf** [comment]
Yeah, agree with @pete-watters here, I think there is a way to simplify these button variants. I'll rename this issue to handle coordinating all buttons and will propose a solution in a PR where we can make sure to coordinate with Figma if needed for naming, etc. I'll handle making stories for the buttons so we can evaluate them all once done.

**Comment by fbwoolf** [comment]
@kyranjamie do you have any thoughts here too as I work on this one to coordinate the buttons with stories?

**Comment by kyranjamie** [comment]
I think I share Pete's thoughts. The token/avatar/icon is just a child of the button, not part of the button. So we don't need a specific button component just for this type. 

Let's just make sure, and provide some examples in Storybook, of how buttons look with tokens/avatars/icons as children?

```
// Composing components like this
<Button>
  <Image />
  Text
</Button>
// is better than creating a new one that does everything imo
<ButtonWithIcon />
```

@mica000 in atomic design speak, the buttons with images in them are molecules composed of atoms (buttons and image) components

**Comment by fbwoolf** [comment]
> Let's just make sure, and provide some examples in Storybook, of how buttons look with tokens/avatars/icons as children?

Yep, agree, thanks.

**Comment by mica000** [comment]
cc @fabric-8

**Comment by fabric-8** [comment]
Just a small addition: We'd love to try 48px as a default button heught and see how that'll look overall :) The height is already reflected in the [design system button component](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=10031%3A1573&mode=design&t=gJsM5RjuzbArE9DY-1)

Also agree that token buttons should really just be a particular ghost button configuration

**Comment by fbwoolf** [comment]
@mica000 @fabric-8 just a heads up that the links to Figma in this issue description do not lead to the most up-to-date version. I have been working on this w/out knowing there are more updated designs. I'm not sure how to know as a dev when the links become outdated? I should just make sure to see the `Ready for dev` label and question if I don't see it?

**Comment by fabric-8** [comment]
@fbwoolf whoops thanks for the hint, updated — Mistake on our end and you should generally not have to worry about that. Just happened as the ticket has been created a while ago while we reiterated on the button component later on without updating things here
