### ISSUE TITLE
Prevent content from showing up below drawers

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4422]
Such as here where the home screen balances show up below the accounts selector drawer

![Image](https://user-images.githubusercontent.com/28991/277908198-3e7df038-5551-4aee-96bd-62502fb3aa13.png)

**Comment by pete-watters** [comment]
This will get fixed as part of this issue - https://github.com/leather-wallet/extension/issues/4371

We need to stop using these modals in extension view and replace them with a full page view

**Comment by kyranjamie** [comment]
I'd add that, while we still have `@stacks/ui` and have to replace for Panda, it's quite likely we'll introduce visual errors like this. Would be better to get rid of first, then fix all UI issues, that patching midway.

**Comment by markmhendrickson** [comment]
Linking that work here to track as a blocker: https://github.com/leather-wallet/extension/issues/4379
