### ISSUE TITLE
Fix alignment for unlock screen in modal

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4423]
It seems to big on the left and right:

![Image](https://user-images.githubusercontent.com/28991/277914418-bb2bcf9a-5d4a-43aa-8c38-832fc7895ba9.png)

**Comment by markmhendrickson** [comment]
Padding seems fixed but content still needs left-alignment?

<img width="410" alt="Screenshot 2023-11-21 at 12 55 31" src="https://github.com/leather-wallet/extension/assets/28991/6bada49a-7da2-4f79-a3de-3f8b8c6107d0">

**Comment by markmhendrickson** [comment]
The continue button should also be aligned against the bottom of the viewport instead of leaving this margin?

<img width="406" alt="Screenshot 2023-11-22 at 14 00 18" src="https://github.com/leather-wallet/extension/assets/28991/24ec9309-c0df-46cf-8629-26bc10d99f2a">

**Comment by pete-watters** [comment]
This issue continues on from https://github.com/leather-wallet/extension/issues/4435. 

The padding was fixed elsewhere so I:
- gave more margin to the `Continue` button to push it down the page
- left aligned the heading text
  
![Screenshot 2023-11-27 at 06 30 10](https://github.com/leather-wallet/extension/assets/2938440/628407ed-f5ce-43e8-bba0-a699e1594d75)

Moving stuff on the page like this isn't ideal and this will be fixed properly by [adding containers](https://github.com/leather-wallet/extension/issues/4370)

I also couldn't find any design for small versions of this screen. We have design for full screen but not for extension width https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=8109%3A81636&mode=design&t=hRL9HhEHe0fB0DlF-1

**Comment by markmhendrickson** [comment]
@pete-watters for consideration as part of your related containers work:

This screen seems a bit off still in that the header copy doesn't have the same left padding as the input, and the space between that copy and the input vertically looks extraordinarily big to me now.

I'm not sure where this screen's UI stands in Figma atm, but if helpful, we can revert to creating a new issue with implementation detail tweaks if you prefer.

<img width="430" alt="Screenshot 2023-12-08 at 14 58 12" src="https://github.com/leather-wallet/extension/assets/28991/d18d93b4-7a30-4255-a22d-0e35a84dc299">

**Comment by pete-watters** [comment]
Thanks Mark. I'll try and improve this in #4370 but as mentioned [here](https://github.com/leather-wallet/extension/issues/4423#issuecomment-1827205544) there is no visual design for this which would help if we want things to be precise.
