### ISSUE TITLE
Fix Bitcoin Contracts asset styles

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#4429]
- Styles are off
- Rename to `Locked Bitcoin` (possibly?)
- List after BTC

<img width="914" alt="Screen Shot 2023-10-25 at 1 03 13 PM" src="https://github.com/leather-wallet/extension/assets/6493321/bc15eca4-46db-4f24-950d-46ac4c6e0a20">

**Comment by fbwoolf** [comment]
Going to reassign this to myself bc touching this code in my current issue: https://github.com/leather-wallet/extension/issues/4382

**Comment by markmhendrickson** [comment]
@fbwoolf is this resolved in https://github.com/leather-wallet/extension/pull/4490?

**Comment by fbwoolf** [comment]
> @fbwoolf is this resolved in #4490?

Yep, that is correct. I can link it there.
