### ISSUE TITLE
Visual bug: Icon distance should be the same on extension and desktop

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4436]
Issue
<img width="750" alt="Screenshot 2023-10-26 at 13 52 01" src="https://github.com/leather-wallet/extension/assets/119523541/ece7cdf8-204e-4ba4-9509-61547e211a2e">

How it should be
<img width="634" alt="Screenshot 2023-10-26 at 13 42 18" src="https://github.com/leather-wallet/extension/assets/119523541/7b362b55-6717-429c-9717-eda73d031dbb">

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=4655-30434&mode=design&t=YRXnLSivbIWmWorE-4

**Comment by markmhendrickson** [comment]
This appears resolved



![Image](https://github.com/leather-wallet/extension/assets/28991/4bfefe21-24fe-4af6-886d-d8bead94aa6c)
