### ISSUE TITLE
Warning about memo requirement, sending to exchanges: text color blends into the background

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4437]
This visual bug was introduced with version 6.13.0
![image](https://github.com/leather-wallet/extension/assets/33360391/013cd1cf-7745-4a71-8d41-f4ee31e817c1)

In version 6.11.0 it looks like
![image](https://github.com/leather-wallet/extension/assets/33360391/589de058-5781-47d3-96f6-ab7079d0d4c1)

**Comment by markmhendrickson** [comment]
@pete-watters I believe this is resolved already?

**Comment by pete-watters** [comment]
Yes @markmhendrickson , I checked and this has been fixed now 

![Screenshot 2023-12-18 at 05 46 27](https://github.com/leather-wallet/extension/assets/2938440/ac12a32b-38f4-429e-8895-e32d1ca14415)
