### ISSUE TITLE
Swaps: Fix Formik warning

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4438]
<img width="889" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/34c4eb3f-c7e2-4f4c-aaa0-f5a36fe08763">

**Comment by kyranjamie** [comment]
Also get this when going to the confirmation page 
<img width="865" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/4d824006-7b64-4565-9b85-5226d2f2611e">

**Comment by fbwoolf** [comment]
Sorry, not sure how I missed those but will fix.
