### ISSUE TITLE
Swaps: Add relevant analytic events

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4439]
No analytics are fired currently. @markmhendrickson to help @fbwoolf establish which events are needed.

**Comment by fbwoolf** [comment]
We discussed this at one point...wasn't a doc being created to track analytics by the design team?

**Comment by markmhendrickson** [comment]
It's been on my todo list. Will assign myself and dd guidance here.

**Comment by camerow** [comment]
Given that this has sat for a year I'm going to close it. I think we should create a single project that encompasses tracking work we want to do and assign it to a given cycle.

**Comment by markmhendrickson** [comment]
Good idea. I've stubbed our an initiative for improving visibility into extension usage generally [here](https://linear.app/leather-io/initiative/improve-visibility-into-extension-usage-675bbb1c343a/overview).
