### ISSUE TITLE
Swaps: Infinite spinner

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4440]
Navigating back/forward I can get an infinite loading state on the swap button (even though I haven't clicked it)

<img width="909" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/69248c19-156d-4b8a-9a33-ecfecd61c4bf">

**Comment by fbwoolf** [comment]
@kyranjamie I throttled my network but can't produce this, is it possible this issue was created during early testing and it has been resolved?

**Comment by fbwoolf** [comment]
Going to close this bc I can't reproduce, but please reopen if come across it again.
