### ISSUE TITLE
Swaps: min to receive

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4442]
Thanks for noticing/reporting @pradel 

It looks like the amount shown is divided by a hundred million the expected minimum is closer to 6.2 sUSDT (based on slippage tolerance)

![image](https://github.com/leather-wallet/extension/assets/33360391/87b9370f-e1ae-4756-89c8-fb4afcc4f6dc)

**Comment by fbwoolf** [comment]
This was code written by Alex team, not correct? What is correct here?

EDIT: Or, just the formatting is off?

**Comment by fbwoolf** [comment]
Current, `new BigNumber(swapSubmissionData.swapAmountTo).times(1 - swapSubmissionData.slippage)`

**Comment by 314159265359879** [comment]
just formatting?
![image](https://github.com/leather-wallet/extension/assets/33360391/5a6b63a2-f6f0-4f93-bd1f-ea18184b018e)

this looks like it should be ~6.2 in this example not 0.00000...6
