### ISSUE TITLE
Unable to send Ordinals, confirmation screen does not appear

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#4444]
I was trying to preview the "send" flow for sending an Ordinal but encountered a bug.

I am able to input the Send To address and choose my fee, but instead of displaying a confirmation dialog, I am sent to a blank modal.

Video:

https://github.com/leather-wallet/extension/assets/122313287/468a96ce-9a79-4555-b97a-1ab100468363

**Comment by fbwoolf** [comment]
This seems like a routing issue @pete-watters, didn't you change some stuff with routing recently?

**Comment by pete-watters** [comment]
Yes it does. I can take a look at it but I won't get to it until 1/11

**Comment by markmhendrickson** [comment]
@brandonmarshall-tm just to confirm here – the inscription _does_ send in any case?

**Comment by pete-watters** [comment]
Checking this and it's blocking send of ordinals 😭  I'll try fix ASAP. 

It is related to routing and introduced was here: https://github.com/leather-wallet/extension/pull/4325/files 

If you open the app in full tab you can see the problem. 

- AS a user 
- WHEN I try to send an ordinal
- AND after entering an address and pressing `Send` 
- THEN I get send to an incorrect route - `send/ordinal-inscription/send/ordinal-inscription/choose-fee` 
- AND I see the choose fee modal
- WHEN I choose my fee I go to - `send/ordinal-inscription/send/ordinal-inscription/choose-fee/send/ordinal-inscription/review`

This sends users to a non-existant place and they can't send their ordinal

**Comment by markmhendrickson** [comment]
Thanks for jumping on it. Let's also add an integration test to prevent regression in the future, either as part of the patch or fast-follow?

**Comment by brandonmarshall-tm** [comment]
Thanks Pete! Just confirming that this results in the Inscription not being sent because I don't get to the Review screen where I "Confirm" the transaction.

**Comment by pete-watters** [comment]
@markmhendrickson I can spent the next hour or so trying to fix it, then I have to go AFK for a few hours but can continue tomorrow if needed

**Comment by pete-watters** [comment]
I managed to implement a fast fix but when I try and send an ordinal it still fails:

https://github.com/leather-wallet/extension/assets/2938440/69021487-71be-4654-9416-5f4adc68d2d6

I'm not sure if this is related to something I missed or a general fail. I can keep looking at it. 

It's tricky to add an integration test as to test it I need an ordinal to send but I will try and add something to do that
