### ISSUE TITLE
fee calculation bug?

### ISSUE THREAD

**Issue by hozzjss** [blockstack/blockstack-app#4455]
Hey leather folks this might be a misunderstanding but I want to check with you on this, in the `determineUtxosForSpend` function the params passed to calculate the price would pass 0 if only 1 utxo is around and n-1 otherwise
[see here](https://github.com/leather-wallet/extension/blob/24a124c91c592522d1732432649f6aedb2220206/src/app/common/transactions/bitcoin/coinselect/local-coin-selection.ts#L72C28-L72C28)

I have been using your code as reference for my own projects and I really appreciate y'all's hard work!!

**Comment by hozzjss** [comment]
Changed it to be a question haha @314159265359879

**Comment by kyranjamie** [comment]
I think I see what you're describing

https://github.com/leather-wallet/extension/blob/24a124c91c592522d1732432649f6aedb2220206/src/app/common/transactions/bitcoin/coinselect/local-coin-selection.ts#L72

UTXOs should be length + 1?

**Comment by hozzjss** [comment]
Yes that’s what i thought but the extension works so i couldn’t really decide whether this is a bug or not

**Comment by kyranjamie** [comment]
I think you might be right. Feel free to contribute with a PR if you have time :)

**Comment by hozzjss** [comment]
will do!
