### ISSUE TITLE
Error "Unable to find a healthy DLC.link attestor"

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4458]
A user is reporting this error pops up in the wallet while navigate through the wallet participating in the sBTC testnet. 

Original message from the user:
> I was a tester for the stacks network bridge. Was trying to have my connected wallet send testnet btc on the the new stacks bridge to concert to sbtc. The error message would come up as soon as I was even trying to just navigate around the wallet. I uninstalled and then reinstalled it, same error message.

**Comment by 314159265359879** [comment]
The situation in which the bug pops up (wallet version 6.14.0 and Firefox in this case), the error pops up as the user tries to navigate to switch the network, the wallet doesn't show the networks but instead shows balance and then this error:
![image](https://github.com/leather-wallet/extension/assets/33360391/c223f4f3-c9d6-4b6a-8c07-60d1dd5c854f)

**Comment by Polybius93** [comment]
The Bitcoin Contract Interface's error handling and requirements have been revised to prevent the recurrence of this issue. The solution has been integrated into the following PR:
https://github.com/leather-wallet/extension/pull/4460
