### ISSUE TITLE
Investigate uncaught DLC errors

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4459]
We're seeing some errors coming from the DLC link feature in Sentry. Any chance you can have a look at these @Polybius93 

![image](https://github.com/leather-wallet/extension/assets/1618764/2fd3a0c3-a4b5-4a6f-8c8b-e8b9335277ff)

![2023-10-31-000023](https://github.com/leather-wallet/extension/assets/1618764/70755443-f5cf-4811-85b5-da11b6ec781a)

**Comment by 314159265359879** [comment]
This is related to https://github.com/leather-wallet/extension/issues/4458

**Comment by Polybius93** [comment]
This PR should have fixed this issue:
https://github.com/leather-wallet/extension/pull/4460
Please let me know if you still receive error messages like this, in that case I'll look further into it!
