### ISSUE TITLE
STX fee display appears offset during contract call 

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#4462]
User reported an STX fee misalignment that shows when performing a contract call.
The offset doesn't appear when making other transactions.  
Using: Linux (Debian) - Brave browser.

Report from Discord: <https://discord.com/channels/621759717756370964/745197302255321108/1169038073020030976>

<img width="202" alt="offset1" src="https://github.com/leather-wallet/extension/assets/132958967/d0684f11-5ac0-4f17-be21-c84edfd8655a">

<img width="368" alt="offset2" src="https://github.com/leather-wallet/extension/assets/132958967/a8ee878b-d26b-4619-9c0f-2972ce29fe21">

**Comment by pete-watters** [comment]
I checked this out and this is mis-aligned on all send STX flows. You can see that the dropdown for `Fee` and `Custom` also don't line up properly

![Screenshot 2023-11-03 at 12 41 31](https://github.com/leather-wallet/extension/assets/2938440/4f015145-d26c-430e-a8f5-df306ae12042)

I looked at the code and a proper fix will involve swapping out these components for our new ones and getting everything lined up properly

**Comment by pete-watters** [comment]
In our work [removing Stacks UI](https://github.com/leather-wallet/extension/pull/4490/) we changed this component and it is more aligned. 

I did some more work to adjust it and improve how it looks:
![Screenshot 2023-12-04 at 09 03 37](https://github.com/leather-wallet/extension/assets/2938440/032c1b01-c4ac-456a-965c-f97a77e9b0fe)

Here's a short demo:
https://github.com/leather-wallet/extension/assets/2938440/f58af0eb-9842-4f0b-be45-304c5d73f455

@mica000 @fabric-8 - can you please check if this looks OK? I aligned it as best I could but I'm not sure if it's 100% what we want. I checked in the designs [here](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=2069%3A2651&mode=design&t=3jpsBj6BKcp7vs5G-1) and I couldn't find an example of this specific section: `Send Stx -> Custom Fee input`
