### ISSUE TITLE
Hide Bitcoin Contracts from balances on testnet unless non-zero

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4466]
As they're hidden from balances on mainnet until the user has engaged with a contract

![image](https://github.com/leather-wallet/extension/assets/28991/af55d666-b26c-4817-8e9e-dc3d2e4d2e5c)

**Comment by Polybius93** [comment]
The solution for this request has been included in this merged PR. I'll close this issue now.
https://github.com/leather-wallet/extension/pull/4460
