### ISSUE TITLE
chore: add better integration tests for send ordinal

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4467]
The send ordinal flow was [broken critically ](https://github.com/leather-wallet/extension/issues/4444)but we didn't know it as we lacked test coverage there. 

This task involves fixing this and making sure we have tests to cover the send flow

We may need to mock an ordinal or else have a test one available to send so we can enter the flow

**Comment by kyranjamie** [comment]
Agree mocking is the way to go here. As we're not doing much mocking elsewhere in the tests, perhaps this is a good opportunity to consider how we can reuse mocked API responses in other tests, too.

**Comment by pete-watters** [comment]
As part of this task, more time should be spent to check the routing config [as per ](https://github.com/leather-wallet/extension/pull/4449#pullrequestreview-1703492119)

**Comment by pete-watters** [comment]
Lack of tests caught us out again on this flow so I am moving it to my dev backlog. 

We need a test for sending  for sending inscriptions on testnet or at least entering this flow with our test wallet.
