### ISSUE TITLE
When signing a transaction top banner shows "active account (4)" when you are on another account (3 and 8 in the examples)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4472]
Here the extension is signed in with account 3
![image](https://github.com/leather-wallet/extension/assets/33360391/dca6a54c-4bd6-4321-a5e5-b51464d4490d)

Here the extension is signed in with account 8
![image](https://github.com/leather-wallet/extension/assets/33360391/7f82332f-e564-4a2c-840a-03a83421aac5)

It looks like it had something to do with the active account in the Extension. After I changed that to 8 it would correctly show "Account 8" when creating a transaction to sign. 
![image](https://github.com/leather-wallet/extension/assets/33360391/14747784-034d-4321-890b-2ea49b1f0d34)

Tested on ALEX (swap transaction) and asigna.io (arbitrary message signing).

Using Chrome wallet extension 6.13.0 // Windows, also tested on Brave and Opera but didn't see the same behaviors there. Transactions when signed are correctly signed with the address signed into.

**Comment by markmhendrickson** [comment]
Blocked for merge by https://github.com/leather-wallet/extension/issues/4502
