### ISSUE TITLE
Prevent content from showing up below submission button in drawers

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4477]
@mica000 do we have guidance on how to handle so the content doesn't flow under?

![Image](https://github.com/leather-wallet/extension/assets/28991/7a9b5a60-7d05-47fe-9d92-42d7194d9738)

**Comment by pete-watters** [comment]
I think this is the same as this issue - https://github.com/leather-wallet/extension/issues/4422 and will be solved by https://github.com/leather-wallet/extension/issues/4371.

We need to make a sticky footer for this button and have the account list scroll
