### ISSUE TITLE
Account icons color, numbers all appearing same as selected account

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#4483]
User [reported](https://discord.com/channels/621759717756370964/745197302255321108/1170358839812554802) account icons, colors & numbers displaying same as selected.

![user1](https://github.com/leather-wallet/extension/assets/132958967/b6d993db-9b24-40b1-bafb-d1799f955e59)

![user2](https://github.com/leather-wallet/extension/assets/132958967/b35eb4a7-ce49-4952-8990-ef024a940c61)

Confirmed same in 6.15.1:

![same6_15_1](https://github.com/leather-wallet/extension/assets/132958967/4ee89334-82ab-4fb1-869b-25bba0dbc257)

![same2](https://github.com/leather-wallet/extension/assets/132958967/57290706-22c7-4e1a-854f-14cf063ab1d2)

**Comment by DeeList** [comment]
This design appears intentional and highlights the users selected account.

**Comment by 314159265359879** [comment]
Here is a comparison between 6.5.1 and 6.15.0, I don't think this is as intended. 

![image](https://github.com/leather-wallet/extension/assets/33360391/24067a63-bc7b-4e2e-b51d-4fd8ba03240d)
