### ISSUE TITLE
Two inscription in one UTXO on a regenerated address

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4499]
The user who owns these two inscriptions in a single UTXO says they only appear in the wallet sometimes. 
https://ordinals.com/output/554e599ab2691fc67293d6fa49fc9dabdcffbe6b09a3662911116a2d1343b40d:0

Is it caused by the nature of these inscriptions, being two in one UTXO. I would expect only the one at index 0 to show, not the other. I understand that the one at index 0 is only showing some of the times. Perhaps the other one is never showing. 

https://mempool.space/address/bc1padnfqkkxznrs8ge2tu2mx3zh80p8j6zmkkzy3wgwgypc6uud4jascgm3lu

**Comment by 314159265359879** [comment]
Update from the user both of them did get displayed in the wallet. Recently they were not displayed.

**Comment by markmhendrickson** [comment]
Got it – can we close out then or are there more instances?

**Comment by markmhendrickson** [comment]
@314159265359879 I'm closing this out as stale but please reopen if still relevant
