### ISSUE TITLE
Visual bug: auth screens ui issue on resize

### ISSUE THREAD

**Issue by edgarkhanzadian** [blockstack/blockstack-app#4501]
On some auth screens we get an issue with fixed width while resizing. That issue seems to be connected to `TwoColumnLayout` that has fixed 600px width on md, lg and xl screens. https://github.com/leather-wallet/extension/blob/dev/src/app/components/secret-key/two-column.layout.tsx#L37 

https://github.com/leather-wallet/extension/assets/22010816/8c08c8ff-bcbd-45e1-9f1e-4211c8aa4732

https://github.com/leather-wallet/extension/assets/22010816/e3b35f03-c0d7-41e4-b031-b090baf81110

**Comment by pete-watters** [comment]
I checked this and I think it is OK but when using the browser emulated responsive dimensions it looks a bit weird. 

If I test it in extension mode / resizing the browser properly it looks OK:

https://github.com/leather-wallet/extension/assets/2938440/165e6475-4702-43ae-a9b7-dc63c67e54ed

The `Set a Password` screen is only available in full screen mode also. 

What do you think here @kyranjamie ? Is it OK if it works well in the real browser but looks a bit off in the responsive emulator?

**Comment by pete-watters** [comment]
We can fix this in https://github.com/leather-io/extension/issues/5736
