### ISSUE TITLE
Replace Tippy with Radix tooltip

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4506]
We should refactor our tooltips and migrate to use Radix tooltip

**Comment by mica000** [comment]
Yesssss!

**Comment by mica000** [comment]
https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=11733-62874&mode=design&t=3Isi5zWhyxxcp1jr-4



![Image](https://github.com/leather-wallet/extension/assets/119523541/f65692bd-5a6a-471a-82d1-c347be9b171a)

**Comment by mica000** [comment]
@edgarkhanzadian I believe this ticket is currently in progress in development?
