### ISSUE TITLE
Update icons package

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4507]
**Replace/Add new icon**
All new icons are [listed here as exportable SVGs](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=12599%3A48048&mode=design&t=sQBF7dRxQzXGhjDt-1). Faded icons are assumed to not be necessary right now. All icons exist as 16x16 and 24x24 versions. In many cases only either version is actually used.

**Move icons to new UI library**
Move icons to new UI library and demo them with storybook so that it's easier to see what's currently in use and match those with Figma assets.

**TBD/Discussed**
Maybe we should seperate token images/icons from UI icons? Right now it can get a bit confusing when looking at the icon folder. In most cases, token icons are actually logos and not icons.

**Need help?**
- @fabric-8 is happy to jump in and help with the grunt work of getting the icons in, provided an engineer can put a "template" in place of how we'll handle the icon sizes and what the (updated?) react icon components should look like.
- Reach out to @fabric-8 to discuss JSX/TSX export options in case the svg export is just too laborious or annoying ✌️ There might be plugin options for conversion.

**Comment by mica000** [comment]
thread: https://trustmachines.slack.com/archives/C05LRS7G44R/p1699472874122359

**Comment by markmhendrickson** [comment]
@fabric-8 please link related Figma materials here 🙏

**Comment by fbwoolf** [comment]
There are two icons still missing we will need to replace in the code:

1. MegaphoneIcon - currently used in the feedback button
2. RotateLeftIcon - currently used on the backup secret key page next to `Your Secret Key gives access to your wallet`

**Comment by fabric-8** [comment]
@fbwoolf Left comments on FIgma regarding the 2 missing icons:

-  MegaphoneIcon was added
- RotateLeftIcon has been replaced with a different icon (key)
