### ISSUE TITLE
Design System - Button and Link Wrapper

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4523]
We need to improve `LeatherButton` / add a new wrapper that we can use to replace `styled.button`

It can enforce `type=button` so we don't need to keep repeating it

**Comment by kyranjamie** [comment]
@fbwoolf already added default type=button. Is this task to remove all instances of `styled.button`?

**Comment by pete-watters** [comment]
Yes we were going to replace `styled.button` with a wrapper as sometimes we have added it in our big refactor

**Comment by fbwoolf** [comment]
Sometimes we are needing to use `styled.button` outside of the recipes, so this would be nice to have to prevent submit behavior. Not sure if we could just add to the current `LeatherButton` recipe and replace the use of `styled.button` in those cases? Sometimes it is being used to click on a row which was previously an `as="button"` situation.

**Comment by pete-watters** [comment]
I'm not sure of the urgency of this but we can assess. Now we have the new `Button` and `Link` components the codebase is cleaner and more consistent. 

We can assess if it's work refactoring styled tags to use these components only:
- `styled.button`
- `styled.a`

It could be a good idea if we then want to add visual tests to storybook but I don't think it's an urgent task

**Comment by pete-watters** [comment]
Closing this off as I don't think it's necessary to do
