### ISSUE TITLE
Warn user about exceptionally high fees when sending Bitcoin

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4525]
Although we show the transaction size and fee before users confirm. I have found sometimes users are still surprised by the size of the fee when they send a transaction like this, they may make assumptions about current network fees or the transaction size but forget to review/check that their assumptions are right before confirming. 

1. User clicks send
2. Selects BTC
3. Clicks "send max"
4. Chooses fee and confirms
5. And the result can be a transaction like this:
https://mempool.space/tx/7ff1426210e2c07f72e20425028ddfa7aac63d021c1106f463911bb722533e92

36 inputs and 1 output + fee

With the fee rate of this transaction (86 sats/vB), it came down to a 100$ fee which turned out to be over twice as much as what is being transferred: about 40$ worth of BTC. 

What about adding a warning (a) when send max is used or (b) only if in addition the wallet detects a skewed result: (fee amount same or higher than what is left to transfer)? 
_"Send max will include any amount of BTC in your wallet even when they consist of many small UTXO's" this can lead to a significantly higher transaction size. You can prevent this by sending less than the maximum so the wallet can select only those UTXO's, that at the very least, can be sent for less than they are worth."_

Or a simpler warning?
_"Using "Send max" can result in high transaction fees, please double-check the cost of your fee options before confirming. You can try sending a smaller amount, if that includes less inputs in the transaction it will be cheaper to send."_

**Comment by 314159265359879** [comment]
Another user pointed out that after the transaction was confirmed they noticed the fee was 100$ or more. Some exampled warnings as stated above could help, they could be shown whenever the total fee exceeds 10% of the total sum, but also whenever the fee exceeds a certain absolute amount. 100$ or perhaps 40$ value for example. 

Additionally we could show fee options red in such a case (perhaps with an "i" for extra info):
![image](https://github.com/leather-wallet/extension/assets/33360391/78fc10a1-81e7-458d-95c3-b37bd413a18c)

**Comment by markmhendrickson** [comment]
The warning could include the suggestion to reduce the amount being sent to attempt reducing fees, for both send-max and non-send-max cases alike

**Comment by markmhendrickson** [comment]
@mica000 I'm assigning you since I think this is most relevant to the confirmation UX for transactions that you're currently working on, regardless of transaction type

**Comment by markmhendrickson** [comment]
This is resolved in the new approval UX with [a new warning variant](https://www.notion.so/trustmachines/Fee-is-unusually-high-add170c8724f4833a53fc8278b224ed1?pvs=4).
