### ISSUE TITLE
Add support for locking ordinal inscriptions in a DLC

### ISSUE THREAD

**Issue by sosaucily** [blockstack/blockstack-app#4529]
---
### Add Ordinal support within DLCs
Basic DLC signing is now functioning in the Hiro wallet. 

As per https://github.com/stacksgov/grants-program/discussions/923, the DLC.Link team is moving forward on a project to support the inclusion of ordinals in DLC/Bitcoin contracts. 

The support for Ordinals in the core Rust-DLC package is nearly complete, so we can now begin the parallel work of adding support to the DLC.Link platform and the Leather wallet.
---

Primarily this will be a UX/UI project I believe. We're putting together designs now, and the features should include the following.

#### 
When a user wants to locks an Ordinal in a DLC
* The wallet should let them see their ordinals and select one to be locked in the DLC.
* We should investigate how the UTXO of the ordinal will be managed.
* They should be able to also lock collateral, if desired. (this is supported by Rust-DLC, but is an optional feature for this project, as the majority of users will lock *either* an ordinal or collateral, and not both).
* They can see the DLC Bitcoin Contract details page, which will clearly display the orindal that is to be locked.

When a user may receive an Ordinal from a DLC
* That receiving user should see the ordinal, along with any additional collateral they want to lock, clearly in the DLC details page.
* The user should be able to see the possible outcomes, such as the Ordinal swapping hands in exchange for the collateral, or the ordinal not changing hands and neither the collateral.

Sample flow screens, uploading soon!

![Lock_Ordinal](https://github.com/leather-wallet/extension/assets/365420/dfe33a80-196e-433d-8c5e-fdd5f9d1273e)
![Lock_Ordinal_2](https://github.com/leather-wallet/extension/assets/365420/1e8a0df2-8ca6-495c-bf14-1ab98af7a363)
![Lock_Ordinal_3](https://github.com/leather-wallet/extension/assets/365420/fdd2f457-0945-4560-a65e-a56d2a316abb)

**Comment by markmhendrickson** [comment]
DLC.Link team to provide guidance re: specific scenarios

**Comment by markmhendrickson** [comment]
DLC support is deprecated
