### ISSUE TITLE
Add option to cancel pending bitcoin transaction

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4536]
We have a similar issue for Stacks transactions https://github.com/leather-wallet/extension/issues/3406

If we add this option
1. Warn the user this can potentially have a high (fee) cost and won't always be successful.

**Comment by markmhendrickson** [comment]
Let's close this one and track as a general feature addition across chains with https://github.com/leather-wallet/extension/issues/3406?
