### ISSUE TITLE
Stacked STX balance not showing as locked 6.16.0 on Ledger

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4539]
In the assets list is shows all stacks it used to show available amount and (locked amount) separately. 

Total amount is displayed in the assets list instead (saw this on ledger enabled extension, same in software mode?)

**Comment by DeeList** [comment]
Checked showing in 6.16.0 software mode

![soft](https://github.com/leather-wallet/extension/assets/132958967/646dfc2c-3112-46c4-aa82-1d4c96c2b043)

**Comment by markmhendrickson** [comment]
It appears per @DeeList's screenshot that we need to fix relevant styles as well so I've broken that out here: https://github.com/leather-wallet/extension/issues/4552

**Comment by fbwoolf** [comment]
@alter-eggo when you are back, do you know why you created a separate `StacksLedgerAssetsList` for balances bc it doesn't include the locked STX code from `StacksBalanceItem` which is causing the issue here? Just checking if that was intentional? Also cc @kyranjamie in case you know?

**Comment by kyranjamie** [comment]
Not sure either, perhaps to deal with some complexities of the conditionality ledger introduces.

Generally speaking, we should avoid ledger specific components unless absolutely necessary. Here, I think we should remove `StacksLedgerAssetsList`, and instead adjust the existing component to work with Ledger.
