### ISSUE TITLE
Fix inaccurately calculated sats/vB displayed when sending Bitcoin

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4541]
When the user selects a fee option they expect the transaction to be send with that fee. I have gotten a report from a user that the wallet set a lower fee than expected based on the selected fee (111 selected [89 sat/vB was set](https://mempool.space/tx/b41db54487b85eb691d85228fb39dd1ac164ddb292b4e1b31d84b1dc3ce99028)). [This is not caused by a CPFP string of pending transactions](https://github.com/leather-wallet/extension/issues/4037). 

Testing a transaction on mainnet I didn't see the same issue. Perhaps this requires more tests.

On testnet it is reproducible, the wallets sets a different fee than selected consistently (6.16.1):

https://github.com/leather-wallet/extension/assets/33360391/867b080e-a1e8-49c6-9c14-f297c171fd52

**Comment by 314159265359879** [comment]
Kyran noticed that the _sats per vB_ are off but **the total fee displayed when choosing the fee is equal to what is being broadcasted**. 

We'd want sats per vB rate to be accurate too ofc.

**Comment by markmhendrickson** [comment]
Is this more a P3 then?

**Comment by 314159265359879** [comment]
I am making this a P1 again because custom fee is also affected. Users set the custom fee in sats/vB so it doesn't matter if the total amount displayed is what it is being send with, it is wrong. Apparently it can go both ways. A user reported it got transmitted with 40 when they set 50 sats per vB. 

On testnet I see it is transmitted with 148 sats/vB when I set 100 sats/vB. 
(testnet)
![image](https://github.com/leather-wallet/extension/assets/33360391/e6fccdf4-785b-46cc-a120-844ed1505597)

![image](https://github.com/leather-wallet/extension/assets/33360391/e874266f-474c-48be-9504-2fcf191a5e40)

The user who reported their mainnet issue:
![image](https://github.com/leather-wallet/extension/assets/33360391/7234caff-616e-438b-b45e-77cbd3ad33af)

**Comment by fbwoolf** [comment]
@kyranjamie I'm finding some things off with our `txSizer` on testnet ...I haven't confirmed yet if the same on mainnet. It looks like you ported over a tx size extimator: https://github.com/leather-wallet/extension/blob/dev/src/app/common/transactions/bitcoin/fees/btc-size-fee-estimator.ts

Any thoughts on why this might be off just on testnet?

Example:
Our size est: 
<img width="237" alt="Screenshot 2023-11-27 at 12 39 06 PM" src="https://github.com/leather-wallet/extension/assets/6493321/f3473d23-748a-4585-ba80-482146f3e53b">

Broadcast size in explorer ...which makes the fee sat/vB off here:
https://blockstream.info/testnet/tx/6c5bbb86263ed3807c4dcc2d8a5a7eceb3edaf1825b64b8dbc81bfa4f02d818c

<img width="1185" alt="Screenshot 2023-11-27 at 12 39 22 PM" src="https://github.com/leather-wallet/extension/assets/6493321/a3cef0f4-1455-422f-a5e9-d34d72572029">

**Comment by fbwoolf** [comment]
Confirmed on mainnet here @markmhendrickson, just an fyi.

<img width="266" alt="Screenshot 2023-11-27 at 12 57 24 PM" src="https://github.com/leather-wallet/extension/assets/6493321/eb786e66-e9fb-4adf-ab5c-841c9f38a2c1">

<img width="1142" alt="Screenshot 2023-11-27 at 12 56 13 PM" src="https://github.com/leather-wallet/extension/assets/6493321/e4e9b124-8028-4855-a18c-3aaff2432af2">

https://blockstream.info/tx/04a7ba9a023b6e526821e8dba046c6b54e0a1a24442b325badabaebcc73f07b5

**Comment by fbwoolf** [comment]
I figured out the prob here, we add a `+ 1` to the input count when calculating the tx size, but I'm not sure why? If I remove that it fixes the prob, so I'll put up a PR to get feedback on the change.

**Comment by kyranjamie** [comment]
To your q's @fbwoolf, does testnet even have fee rates? Most sources just say 1 right?

**Comment by fbwoolf** [comment]
> To your q's @fbwoolf, does testnet even have fee rates? Most sources just say 1 right?

Blockcypher does return values so the refactor included a change to just use that api on testnet. Mempool just returns `1` so excluded it from the mean average calc on testnet which helped fix the bug here on testnet.
