### ISSUE TITLE
SVG errors on send form

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4542]
Presume related to stacks/ui changes

<img width="648" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/f96f9723-02a5-4135-bf5e-b5d2deec7772">

**Comment by pete-watters** [comment]
I checked and this error comes from one of the react fi icons not yet migrated `FiAlertTriangle`. 

I'm doing an audit of these icons and will migrate the others
