### ISSUE TITLE
Fix flaky bitcoin contract tests > remove skip on tests

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#4547]
These tests became flaky so we had to skip them, we will need to look at them closer to get them fixed properly.

Tests were skipped here: https://github.com/leather-wallet/extension/pull/4544

cc @Polybius93 will assign you to this issue.

**Comment by markmhendrickson** [comment]
Closing in favor of https://github.com/leather-wallet/extension/issues/4664
