### ISSUE TITLE
Button nested within button

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4550]
On home page, I run into 

![image](https://github.com/leather-wallet/extension/assets/1618764/7a289351-0982-4b56-b22a-ac7b6e74de63)

cc/ @fbwoolf @pete-watters if related to stacks/ui changes

**Comment by pete-watters** [comment]
I checked this and we had a nested button on the `Ordinal` container. I just changed the parent to be a `div` as it didn't need to be a button
