### ISSUE TITLE
Fix display of locked vs. unlocked STX balances

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4552]
They appear to have regressed, perhaps due to UI library work:

![image](https://github.com/leather-wallet/extension/assets/28991/64215ac5-1a01-4210-9916-d21ed5a25c21)

**Comment by pete-watters** [comment]
This was broken before style updates but I will fix it 👍

**Comment by kyranjamie** [comment]
Closing as dupe of https://github.com/leather-wallet/extension/issues/4851
