### ISSUE TITLE
On sbtc-devnet, if no fee estimate available, wallet errors and becomes unresponsive

### ISSUE THREAD

**Issue by mijoco-btc** [blockstack/blockstack-app#4555]
Wallet 6.16.1
Chrome

Testing using the sbtc devenv network. If the node returns 400 / NoEstimateAvailable to request for /v2/fees/transaction then the the wallet goes into unrecoverable error state.

The confirm button is active but does nothing on click.

Setting the fee manually makes no difference.

<img width="1664" alt="Screenshot 2023-11-21 at 14 49 23" src="https://github.com/leather-wallet/extension/assets/4384929/63d190f7-ee8f-4520-adf2-3cbadd1817c9">

**Comment by 314159265359879** [comment]
@radicleart this issue should be resolved, would you mind retesting with the latest version (6.26.1) of the wallet, let me know if you still see it.

**Comment by mijoco-btc** [comment]
Thanks @314159265359879 have not seen this behaviour recently - please feel free to close..
