### ISSUE TITLE
"Create new account" button blocking access to existing accounts

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#4568]
When selecting multiple listed accounts, the 'Create new account' button is blocking access to the last listed account.

![create block](https://github.com/leather-wallet/extension/assets/132958967/f78bb7c5-5524-4f8b-8891-9f629bc4b25d)

<img width="286" alt="create block2" src="https://github.com/leather-wallet/extension/assets/132958967/a54163af-9ad4-429b-826d-685a1c8b2204">

Missing slider bar from earlier version that helped display

![slider](https://github.com/leather-wallet/extension/assets/132958967/b043dea7-bd4d-49d5-9c83-b7beabd2eb13)

**Comment by pete-watters** [comment]
Thanks for reporting @DeeList . This is similar to https://github.com/leather-wallet/extension/issues/4549 and will be resolved in https://github.com/leather-wallet/extension/issues/4549

**Comment by 314159265359879** [comment]
I think Pete meant to link https://github.com/leather-wallet/extension/issues/4371 as the item it will ultimately be resolved with.
