### ISSUE TITLE
Ledger enabled extension throws error: No LedgerRequestKeysContext

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4570]
A user reported that this popped up as they tried connecting to a Stacks dapp: app.alexlab.co and pool.xverse.app
Wallet version: 6.16.1
Browser: Chrome

![image](https://github.com/leather-wallet/extension/assets/33360391/271d24e9-f2dd-40b1-825d-d36449671b5c)

I have been unable to replicate the issue but the user mentioned that it was resolved after they reinstalled Leather. 

Logging it here in case someone else runs into it, so they know to reinstall the wallet.

**Comment by markmhendrickson** [comment]
@kyranjamie any initial impressions on what may have caused this?

**Comment by kyranjamie** [comment]
I'm not sure. This means the hook is used out of the context, which shouldn't be possible. Hoping all the Ledger changes will address this.

**Comment by markmhendrickson** [comment]
@314159265359879 ~mind retesting with the new prod build that has all the new Ledger changes?~ I suppose we'll need to wait to see if this pops back up from user reports
