### ISSUE TITLE
PSBT warning shown when inputs are certain

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4576]
@markmhendrickson noted that the PSBT warning shows incorrectly when the tx inputs/outputs are guaranteed.

![image](https://github.com/leather-wallet/extension/assets/1618764/8172171f-93b0-4457-a31a-e3ed52a992e0)

**Comment by fbwoolf** [comment]
I believe this was fixed, correct? It was a bug from the UI refactor where I hardcoded the label to change the styles? I had posted this in Slack, or is this still a bug being seen?

<img width="528" alt="Screenshot 2023-11-27 at 7 22 37 PM" src="https://github.com/leather-wallet/extension/assets/6493321/b01544d7-9499-46b1-9297-cea21f8390ee">

**Comment by markmhendrickson** [comment]
Was this fixed in the past week or so? If so, then we can close out – I don't think we've seen it since then.
