### ISSUE TITLE
Ledger improvements

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4581]
- [x] #4715
- [x] #4863
- [x] #4864
- [x] #4924

**Comment by markmhendrickson** [comment]
Bullet points are still missing here as well:

<img width="582" alt="Screenshot 2023-11-29 at 15 08 29" src="https://github.com/leather-wallet/extension/assets/28991/9052e66b-f1b1-45b9-9652-a7768f710c31">

**Comment by markmhendrickson** [comment]
@kyranjamie Please digest these into individual issues so we can tackle them separately
