### ISSUE TITLE
Fix styles in BRC-20 and Stacks contract execution areas

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4587]
Especially the tiny "Learn more" link

<img width="671" alt="Screenshot 2023-11-28 at 14 27 58" src="https://github.com/leather-wallet/extension/assets/28991/c871805f-a3dc-41d5-b4b9-fc25ad06dd2c">

**Comment by markmhendrickson** [comment]
I presume the same issue is affecting the size of text here in the Stacks contract execution modal as well (e.g. factor attribute)

<img width="427" alt="Screenshot 2023-11-29 at 12 11 23" src="https://github.com/leather-wallet/extension/assets/28991/18d73713-b020-4043-b1f1-e70cf44d4170">

**Comment by pete-watters** [comment]
@mica000 @fabric-8 do we have these designs in Figma anywhere? 

If not can you let me know what font these should be? `body.02`  / `caption.01` / `label.01`

![Screenshot 2023-12-08 at 13 52 56](https://github.com/leather-wallet/extension/assets/2938440/77bfe4b6-9c39-4313-83f6-7079c745ea7f)
![Screenshot 2023-12-08 at 13 46 37](https://github.com/leather-wallet/extension/assets/2938440/b662a1b5-fb54-47b8-806c-e5d025b12883)

I checked and there are a few places where we still specify the font using legacy methods so we probably have this bug in all those places. 

![Screenshot 2023-12-08 at 13 55 21](https://github.com/leather-wallet/extension/assets/2938440/02a89c74-15ad-4776-ac07-c9af92acf4b2)

**Comment by pete-watters** [comment]
We agreed to set these texts as `body.02`
