### ISSUE TITLE
Hide "Bitcoin Contracts" balance on testnet when zero

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4588]
Currently the balance shows up always, even when zero. It should show up only when non-zero

<img width="292" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/21c4d7db-caef-4983-8ab2-af9e93f8be7b">

**Comment by pete-watters** [comment]
@markmhendrickson do you mind checking if this is resolved now? 

I think it may have been fixed by [this commit](https://github.com/leather-wallet/extension/pull/4679/commits/90988c7a69aeac76e691c1fb9f27452570d19622)

**Comment by markmhendrickson** [comment]
@314159265359879 can you recreate this issue and if not, close?

**Comment by 314159265359879** [comment]
This was indeed resolved with the linked commit
