### ISSUE TITLE
Fix overlay icon for inscription transaction in activity

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4591]
The down arrow here is faded out against the image of the inscription itself whereas it should be a fully filled-in element like the BTC transaction below it:

<img width="421" alt="Screenshot 2023-11-29 at 14 08 29" src="https://github.com/leather-wallet/extension/assets/28991/59551a6d-38a4-40de-9a1e-0ff6f783d634">

**Comment by pete-watters** [comment]
The colour was not being applied properly here. I've added a fix but it may need some more work to improve it

**Comment by markmhendrickson** [comment]
Was this fixed for BTC transactions as well? I noticed here that the BTC arrow was also showing funny (2nd item) but not sure if I did before or after your fix via this PR

<img width="1253" alt="irregular inscription displays in activity" src="https://github.com/leather-wallet/extension/assets/28991/28d9d61f-b3a4-45e6-83e7-4d6f335f5829">
