### ISSUE TITLE
Place buttons side-by-side on Ordinal transaction confirmation screen

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4592]
Possible stacks/ui-removal-related regression:

![image](https://github.com/leather-wallet/extension/assets/28991/e9042d27-10fb-4f96-b203-a09babfd3d86)

**Comment by pete-watters** [comment]
This was a stacks UI removal regression and a quick fix so I went for it:
![Screenshot 2023-12-04 at 11 07 06](https://github.com/leather-wallet/extension/assets/2938440/3a90c7df-a3f3-4439-a965-a384ee08f25e)

Note, the page background here is not correct but has been fixed in #4562
