### ISSUE TITLE
Improve DLC styling

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4593]
I need to help Dani with some modal styling for the bitcoin contracts request

**Comment by pete-watters** [comment]
@fabric-8 @mica000 - can you please help with this? I've been working with Dani from DLC to help him adjust their auth pop out. 

I helped him with text size but he is asking me about these two items:

* The network tag in the header still looks a bit off for me.
![Screenshot 2023-11-29 at 11 24 15 (1)](https://github.com/leather-wallet/extension/assets/2938440/2fcbd46a-0134-4181-8c8f-e6b210f98ec0)

* I’ve been working on the bitcoin contract request error page also, been trying to match the other error pages. Does this look good to you? Should it look like this, I couldn’t find the reference.

![Screenshot 2023-11-29 at 11 44 50](https://github.com/leather-wallet/extension/assets/2938440/8da236e6-b91e-43a6-8d71-d53bf2b2b989)

Can you please let me know if these look OK? For the dialog header, even if I [add containers](https://github.com/leather-wallet/extension/issues/4370)  there is not much space there to fit `Locked Bitcoin` and the `DLCLink` tag. Maybe we can get rid of the `X` there? 

This is the containers design:
![Screenshot 2023-12-04 at 11 34 20](https://github.com/leather-wallet/extension/assets/2938440/a2ee694e-ab80-4db9-a25b-5f6f5b49ef7b)

**Comment by markmhendrickson** [comment]
Assigning to @mica000 since she's looking at this as part of general transaction signing UX work, so I imagine it's best to wait until that work is finalized, then we can return to improving the DLC case here specifically

**Comment by pete-watters** [comment]
@markmhendrickson I don't think we will need to do this anymore as we have disabled DLC, correct?

**Comment by markmhendrickson** [comment]
Yep correct
