### ISSUE TITLE
Remove hover effect from logo when not a link

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4597]
Sometimes the logo in the top left of the app is clickable for navigating back home, but if the user is viewing home itself, it's not clickable. Yet it has a hover effect regardless of whether it goes anywhere, which would be best to remove in the case it's not a link:

<img width="199" alt="Screenshot 2023-11-29 at 10 56 54" src="https://github.com/leather-wallet/extension/assets/28991/018cb756-557a-494b-829e-c0c007d447ba">

**Comment by pete-watters** [comment]
I added some improvements to the header code in https://github.com/leather-io/extension/pull/5785 so just fixed this also
