### ISSUE TITLE
Fix styles for receive modal notice

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4600]
We used to have a background color for this area

<img width="543" alt="Screenshot 2023-11-29 at 15 02 21" src="https://github.com/leather-wallet/extension/assets/28991/108dac38-b98c-47c3-a6f3-041af0ee4266">

**Comment by pete-watters** [comment]
This colour wasn't working properly for a long time, I have added it now:

![Screenshot 2023-12-04 at 11 16 08](https://github.com/leather-wallet/extension/assets/2938440/daea868e-b991-4037-abe4-ac5ab47b5b08)
![Screenshot 2023-12-04 at 11 15 53](https://github.com/leather-wallet/extension/assets/2938440/1d5a19b9-a5fc-4675-9853-7558b4822fb4)
