### ISSUE TITLE
Improve guidance / error handling when "wrong" app open for Ledger connection

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4601]
E.g. here I want to send an Ordinal so the app prompts me to connect Bitcoin, but I have the Stacks app open on my device, so it throws an unhelpful error after erroneously saying "Connected!" and a forever spinner appears on the home screen

Instead, we should tell the user they need to ensure that the right app is open on their device, guiding them to close the wrong one and open the other to proceed.

https://github.com/leather-wallet/extension/assets/28991/c5449c20-2431-470e-943d-f89dfc4e9308

**Comment by edgarkhanzadian** [comment]
I think we need to use a behavior of Ledger Live here. We can request on a ledger device to open a particular app
