### ISSUE TITLE
6.17.0 error: No taproot script found, testing new web application

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4604]
I received this report today, would love for one of the devs to take a look. 

What could be causing this? 

_We've developed an internal web application that connects to BTC testnet through the Leather Wallet chrome extension.

Today, my Chrome browser automatically updated the extension to the latest version that was just released (6.17). After the update, the wallet is unable to sign a transaction with the error: "No taproot scripts found". I'm attaching screenshots that include the raw transaction and the message.

I downgraded manually to 6.16.1 and verified that everything is working properly. Could you please investigate why this error is occurring?_

![image](https://github.com/leather-wallet/extension/assets/33360391/1e95eeb7-9681-436a-aaf0-1b90e3f5f6fb)

![image](https://github.com/leather-wallet/extension/assets/33360391/ebb10b1a-7a6a-4092-8bc3-d5ce699d0946)

![image](https://github.com/leather-wallet/extension/assets/33360391/a804578a-7733-4eb1-9d11-c4cb435c9d5b)

**Comment by gbarkhatov** [comment]
@314159265359879 any ideas?

**Comment by 314159265359879** [comment]
@gbarkhatov I was wondering if you are using the legacy Auth we had to ditch that because of Ledger support that was rolled out with 6.17.0 unfortunately Ledger won't work consistently with the legacy auth API. The newer `getAddresses` API provide essentially the same data.

If that is the issue you can upgrade your Leather-based auth to our newer getAddresses API using this doc: https://leather.gitbook.io/developers/bitcoin/connect-users/get-addresses

**Comment by gbarkhatov** [comment]
@314159265359879 thanks, will check it out

**Comment by markmhendrickson** [comment]
@gbarkhatov I'm closing as stale but please let us know if you're still encountering the problem and we'll reopen

**Comment by gbarkhatov** [comment]
Yep, it's working. All good
