### ISSUE TITLE
Fix password-related formatting issues

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4606]
Related to fixes made with https://github.com/leather-wallet/extension/issues/4423

Across the unlock and set-password screens respectively.

## Spacing issues

<img width="410" alt="Screenshot 2023-11-30 at 12 44 55" src="https://github.com/leather-wallet/extension/assets/28991/610da690-64fc-422a-a3c8-945c4c9ca047">

## Alignment issue

<img width="404" alt="Screenshot 2023-11-30 at 12 44 32" src="https://github.com/leather-wallet/extension/assets/28991/700f7ce0-6c72-4e71-94da-42992a36ee25">

## Alignment  issue

<img width="433" alt="Screenshot 2023-11-30 at 12 44 28" src="https://github.com/leather-wallet/extension/assets/28991/192c33ba-d5fa-450c-8cc4-85df80b9942b">

**Comment by pete-watters** [comment]
This seems similar to https://github.com/leather-wallet/extension/issues/4598 and we don't have a proper design for it

**Comment by pete-watters** [comment]
Linking related issues:
- https://github.com/leather-wallet/extension/issues/4423
- https://github.com/leather-wallet/extension/issues/4435
- https://github.com/leather-wallet/extension/pull/4500

**Comment by pete-watters** [comment]
I made a few small changes here to make it look a bit better but we can revisit it once we have a design - https://github.com/leather-wallet/extension/issues/4598 

![Screenshot 2023-12-18 at 12 31 15](https://github.com/leather-wallet/extension/assets/2938440/113564ab-34fb-45fc-87c1-4d2fc7db0c8d)

https://github.com/leather-wallet/extension/assets/2938440/4f332d4f-cf6f-4038-8d2f-96630c791acb

**Comment by markmhendrickson** [comment]
Please move this issue to its updated board status 🙏
