### ISSUE TITLE
Scroll when selecting account is over the button

### ISSUE THREAD

**Issue by anch09** [blockstack/blockstack-app#4615]
I realized that the scrolling list when you select account is over the `create account` button. 
There is also a bug I always see when I have to re enter my password that the content does not fit the pop up window where it is displayed.
Leather version: 6.17.0

<img width="393" alt="Screenshot 2023-11-30 at 10 28 57 AM" src="https://github.com/leather-wallet/extension/assets/77537495/7c8f7b1c-6ab1-4fe6-9cfb-eb2eb257c48c">

![Screenshot from 2023-11-30 11-39-32](https://github.com/leather-wallet/extension/assets/77537495/91705775-4b75-494e-adc8-40f1ad815582)

**Comment by 314159265359879** [comment]
Thanks for reporting! 
This is seriously complicating creating a new account. I ask the devs to take a look. 

Do you still see the second issue in 6.17.0 too?

**Comment by DeeList** [comment]
create account button issue assigned to be fixed #4371

**Comment by anch09** [comment]
> Thanks for reporting! This is seriously complicating creating a new account. I ask the devs to take a look.
> 
> Do you still see the second issue in 6.17.0 too?

Yeah, it's still happening 

<img width="452" alt="Screenshot 2023-11-30 at 4 15 31 PM" src="https://github.com/leather-wallet/extension/assets/77537495/c5cd08de-49ca-4c0c-a195-02f835e42399">
