### ISSUE TITLE
Loading spinner shown when cancelling ledger action

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4618]
Ensure user's can initiate and cancel ledger actions, and the underlying form handles this case correctly.

**Comment by markmhendrickson** [comment]
Let's attach a screen recording for clarity

**Comment by markmhendrickson** [comment]
@kyranjamie assigning you to add screen recording or details

**Comment by markmhendrickson** [comment]
@kyranjamie I'm closing out for lack of details, but please reopen if you have them
