### ISSUE TITLE
Bitcoin review and confirm screen shows total spend and what is being send: also add line with fee

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4622]
Lets make it easier for users to see the **total** fee and put that on a separate line too (we do this for STX transfers too). 

bitcoin transaction confirmed...
![image](https://github.com/leather-wallet/extension/assets/33360391/ac30dea4-febf-422f-af9d-6fc1ea02cba7)

STX transaction review...
![image](https://github.com/leather-wallet/extension/assets/33360391/23461e67-8385-472d-b702-01371b20923a)

STX transaction confirmed...
![image](https://github.com/leather-wallet/extension/assets/33360391/f0830294-1f68-4ab0-8897-c7d76cca9e16)

**Comment by markmhendrickson** [comment]
Related: https://github.com/leather-wallet/extension/issues/3991

**Comment by markmhendrickson** [comment]
This is resolved in the new approval UX
