### ISSUE TITLE
Arguments font size appears too small

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#4626]
Font size appears much smaller

![small0](https://github.com/leather-wallet/extension/assets/132958967/ae9477c8-b6a8-475b-820c-2477470affce)

<img width="307" alt="small2" src="https://github.com/leather-wallet/extension/assets/132958967/2f3158ac-2692-4fce-a918-2e37393d3e7e">

<img width="305" alt="small1" src="https://github.com/leather-wallet/extension/assets/132958967/d7b81a3f-4c17-4f20-a2bc-12da753c3820">

https://discord.com/channels/621759717756370964/745197302255321108/1180224907448156260

**Comment by markmhendrickson** [comment]
Tracked here: https://github.com/leather-wallet/extension/issues/4587
