### ISSUE TITLE
Sending ordinals from regenerated addresses broke

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4628]
Sending from the primary address to an other address is fine. I noticed an issue with Ledger and sending from regenerated addresses too (not sure if that is related: https://github.com/leather-wallet/extension/issues/4620)

Sending from a regenerated address to any other address is blocked at the point of selecting the fee... the wallet does not progress. 

Video about that:

https://github.com/leather-wallet/extension/assets/33360391/5e9e10bd-4508-454b-8897-f135802974e7

**Comment by 314159265359879** [comment]
One of the users who encountered this tested the previous build (6.16.1) and then it works properly. Likely this was introduced with a change in 6.17.0.

**Comment by kyranjamie** [comment]
Oversight on my part. This must've broken in creating a unified signing function.

**Comment by kyranjamie** [comment]
Closed in
