### ISSUE TITLE
Update corner radius scale and components

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4637]
**New corner radius scale:**
- XS: 2px – buttons, rows, collectibles images;
- SM: 4px – menus, drop-down, inputs;
- MD: 8px – modals and drawers;
- LG: 12px – page container;

**Task:**

- [x] Create new scale for corner radius
- [ ] Update components

------

FINAL PROPOSAL: OPTION 1
https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=9972-108739&mode=design&t=oU8qhxS
<img width="3942" alt="border radius" src="https://github.com/leather-wallet/extension/assets/119523541/09645b74-3b17-4060-b60e-39d815db8799">

**Comment by fbwoolf** [comment]
@mica000 it appears in our tokens we have an `xl = 20px` and an `xxl = 24px`, are those ones we need to keep?

**Comment by fbwoolf** [comment]
It looks like `xl` is used when we display some things with tx requests (like structured data), and `xxl` is used just to round out a pill or badge.

EDIT: Thinking these can be removed and edge cases hardcoded separately?

**Comment by mica000** [comment]
Hi! I think Fab set the tokens to 100px so they are always rounded.
https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=1574-27&mode=design&t=7LgsZQErfHZlucS9-4

We do however have collectibles that have a 2px radius, so maybe this rule shouldn’t apply to them?

Let me know if I understood what you mean correctly.

**Comment by fbwoolf** [comment]
> Let me know if I understood what you mean correctly.

Ha, have no idea what you are responding to here - lol. I am updating all radii (tokens). We currently use an xl and xxl, but in the description of this issue those are not included, and in Figma they both have a `??` by them. Are those supposed to be removed as radii tokens?

**Comment by mica000** [comment]
Ah got it! hehe
The xl and xxl are with `??` because we wanted to removed them since the new scale wasn’t using them (forgot to remove the ?? from the handover docs.) Instead, whenever something is rounded, fab suggested to se the radius to 100px and I think that would be manual - cc @fab to confirm.
