### ISSUE TITLE
Always display JSON previews with pretty print e.g. in send modal for inscriptions

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4644]
[See context on Slack](https://trustmachines.slack.com/archives/C05LRS7G44R/p1701097890791789)

https://github.com/leather-wallet/extension/assets/28991/eeddd0d1-703d-4102-a00b-e3382d663d4b

**Comment by pete-watters** [comment]
@markmhendrickson do you mind checking if this is still causing issues? 

I tested it in my wallet and all of mine are appearing formatted correctly. Maybe it was solved by another change recently


https://github.com/leather-wallet/extension/assets/2938440/f0b70b08-5580-47af-928e-35d580a673fb

**Comment by markmhendrickson** [comment]
@314159265359879 can you recreate this issue?

**Comment by 314159265359879** [comment]
This looks resolved to me too, closing this issue.
