### ISSUE TITLE
signPsbt stopped working for taproot leaf scripts

### ISSUE THREAD

**Issue by fess-v** [blockstack/blockstack-app#4645]
Hello! We're in Asigna using the sign psbt method for signing multisig transactions, particularly Taproot leaf scripts. In all previous versions it worked fine, but 
https://github.com/leather-wallet/extension/releases/tag/v6.17.0 after this release this method generates an incorrect signature, even for 1 of 1 leaf script, it doesn't matter how many owners
You can check it here https://btc.asigna.io/, Xverse/Unisat generate a correct signature so you can look into that if it could be helpful.
Let me know if you have any questions, and thanks a lot!

**Comment by fbwoolf** [comment]
I cannot reproduce this on Asigna, my PSBT was signed correctly...

<img width="1247" alt="Screenshot 2023-12-05 at 11 04 38 AM" src="https://github.com/leather-wallet/extension/assets/6493321/0b794ec9-5a6c-4817-b930-ab0fe00842d8">

EDIT: Double checking this bc maybe didn't sign ...not 100% sure here yet.

**Comment by fbwoolf** [comment]
@kyranjamie I confirmed it hits the `tr` case in my `getAddressFromOutScript` changes in the last release, which didn't change how that type is handled. I think it might be something that changed with ledger/signing work? It does hit the code detecting there is no tapInternalKey and we apply it ...that code was relocated and changed slightly. I'm not seeing why the signature would be incorrect here now? Any thoughts, or you able to look at your changes too? 🤔

@fess-v can you confirm the error you see is on your end when the tx is `executed` bc it appears the PSBT is signed successfully on our end and returned to you?

**Comment by fbwoolf** [comment]
Nvm, @kyranjamie found the bug. Ledger work added `tx.finalize()` before passing it back to the app.

**Comment by fess-v** [comment]
@fbwoolf definitely the issue is in the executing phase, singing returns a signed TX but signed incorrectly

**Comment by fbwoolf** [comment]
I think might be bc we are always signing with the tr ~~account~~ address index `0` ...which isn't the address I see here as the input...

<img width="485" alt="Screenshot 2023-12-05 at 12 47 58 PM" src="https://github.com/leather-wallet/extension/assets/6493321/7a5515b9-f2b8-4830-a2a0-0a5fcb13ae5f">

EDIT: I don't think that has changed on our end though? 🤔 Looking into it.

**Comment by fbwoolf** [comment]
I am thinking this has to do with the `addressIndex` not the accountIndex? I might need @kyranjamie to provide feedback tom on the signing code, but my zero index tr address (which we are signing with in the wallet), is NOT what I see in your app once I auth. We sign with the `addressIndexKeychain`.

These are my diff tr addresses:
Yours (input to sign): bc1pd3vc5udsuh9jwayp9e6f86jekyylyq8dvhugh8wnuv8l4yh3yztqs5p2qc
Wallet (signer): bc1p9pnzvq52956jht5deha82qp96pxw0a0tvey6fhdea7vwhf33tarskqq3nr

**Comment by fbwoolf** [comment]
I didn't see this before, maybe fixed with https://github.com/leather-wallet/extension/pull/4646 ???

**Comment by fbwoolf** [comment]
@fess-v do you know why the tr address you all are using for auth is NOT the one we pass you through `getAddresses`, where is that coming from? I think that is causing the issue here. 🤔  I verified `getAddresses` is passing the correct address for me: bc1p9pnzvq52956jht5deha82qp96pxw0a0tvey6fhdea7vwhf33tarskqq3nr ...but you all are using: bc1pd3vc5udsuh9jwayp9e6f86jekyylyq8dvhugh8wnuv8l4yh3yztqs5p2qc

**Comment by fess-v** [comment]
hey @fbwoolf @kyranjamie we're using the payment address, not the ordinals one for signing
![image](https://github.com/leather-wallet/extension/assets/26626714/5515022b-67f7-41a0-a52a-f71f44816bfb)
![image](https://github.com/leather-wallet/extension/assets/26626714/33d46618-abf1-4908-831b-f88fde083d36)

**Comment by fess-v** [comment]
We're using the `p2wpkh` address from Leather @fbwoolf

**Comment by kyranjamie** [comment]
I've tried to test this but I cannot get to the asigna sending page, gets stuck on 

![Image](https://github.com/leather-wallet/extension/assets/1618764/554c111f-6eb5-4dbc-8ec8-9dee858dbce8)

**Comment by fess-v** [comment]
Works now @kyranjamie

**Comment by fbwoolf** [comment]
Posting again here...

`getAddresses`...
<img width="665" alt="Screenshot 2023-12-06 at 9 43 58 AM" src="https://github.com/leather-wallet/extension/assets/6493321/e652eead-6f7d-4c3c-9ea3-7338ddf7134e">

tr address of input to sign...
<img width="485" alt="Screenshot 2023-12-05 at 12 47 58 PM" src="https://github.com/leather-wallet/extension/assets/6493321/b44dd4b0-b133-4696-9375-574efa31d8e4">

**Comment by kyranjamie** [comment]
@fbwoolf the derived multi-sig address is supposed to be different to your own address, as far as I understand? cc @fess-v

**Comment by markmhendrickson** [comment]
@kyranjamie is there a PR to link here?
