### ISSUE TITLE
Investigate flaky tests

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4662]
Several tests are failing intermittently. 

<img width="644" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/c107790e-d3a3-4b71-8a19-d68845402443">

This task is to investigate, and share with the team why this happens, as well as recommending improvements how we can avoid in future. API mocking?

**Comment by fbwoolf** [comment]
The swaps one here must be with how I'm intercepting the broadcast and aborting it. I did follow the doc examples, but maybe I missed something. 🤔 I used it before in the `transactions.spec.ts` which seems to be reliable?

**Comment by fbwoolf** [comment]
It appears I had the wrong route path in the swaps test, so I put a PR up to fix that one here: https://github.com/leather-wallet/extension/pull/4668
