### ISSUE TITLE
Re-enable DLC link tests

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4664]
I recall a while back we had to disable some of the DLC link tests, because they were failing erroneously. @Polybius93, any chance you can have a look at re-nabling these?

[You can see they're disabled in our test reporting.](https://leather-wallet.github.io/playwright-reports/fix/asigna/#?q=s:skipped)

cc/ @fbwoolf @pete-watters to add any additional context that might help

**Comment by pete-watters** [comment]
> You can see they're disabled in our test reporting.

We disabled these as they were failing often and blocking other PRs. We disabled them [here](https://github.com/leather-wallet/extension/pull/4544) 

We have [this issue](https://github.com/leather-wallet/extension/issues/4502) and you can see some fails [here](https://github.com/leather-wallet/extension/actions/runs/6809607394/job/18516225440#step:11:106)

When I was debugging I saw that sometimes calls to `https://devnet.dlc.link` were timing out

**Comment by fbwoolf** [comment]
I am finding that most of our tests, actually, that use the pattern of requesting an rpc method fail often and our flaky. I'm not sure it ended up being theirs specifically? The bip322 fail almost every run, along with transaction-signing, and now sign-psbt. I think we need to investigate how all of these tests are setup and initiate the request?

**Comment by Polybius93** [comment]
Yeah, I am also encountering flaky rpc tests most of the time, and while I was working on our test, I was following the patterns of the already existing rpc tests. Although, the issue with our test is different now and I see the reason why it is failing. We shifted our flow, so the offer is not viewable without interacting with the DLC infrastructure. I'll try to find a solution to this in the next days.

**Comment by markmhendrickson** [comment]
@Polybius93 Thanks – best to assign this issue to you then?

**Comment by Polybius93** [comment]
I did a wrong statement in my last comment, we did not apply the shifted flow yet, so this test is flaky because of the same reason as the other rpc tests, so it would be nice to figure it out together, how to solve the issue of all flaky tests.

**Comment by kyranjamie** [comment]
We axed the feature so can be closed
