### ISSUE TITLE
Align fee warning so it doesn't go out of the modal screen. 

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4674]
Reproduction steps
1. Click send
2. Click STX
3. Put in any amount
4. edit the fee to 0.00018 
5. See the error (fee warning is aligned out of screen)

This is what it looks like on Chrome/windows11
![image](https://github.com/leather-wallet/extension/assets/33360391/a3ab2897-eeaf-412b-b7cb-90a7f3f6d3ff)

This is what it looks like on Chrome/Windows10
![image](https://github.com/leather-wallet/extension/assets/33360391/b1e0de24-3821-4d6a-bfbc-994c5582f433)

**Comment by pete-watters** [comment]
@fabric-8 @mica000 : can we have an up to date design for this screen? I checked and in the Figma flow its quite outdated and even incorrect. 

An external contributor added a fix but it doesn't look good and there is no reference for how we want to do it. 

Should we make this warning full width? Even then it will look weird with `Edit Nonce` below:
![Screenshot 2023-12-14 at 06 38 41](https://github.com/leather-wallet/extension/assets/2938440/f0856a92-4941-4eb5-a360-0c059e1d0b07)

In Figma the flow seems like it has a mistake as it is using a mix of the `Send BTC` flow and there is even a `Password Strength` indicator there. 

Maybe it's worth not fixing this until we do a re-design like we discussed yesterday? cc @markmhendrickson

**Comment by fabric-8** [comment]
Hey Pete, I'm currently working on the send flow and overhauling this screen in general — As a a quick fix to make it look less buggy you could indeed stretch the warning to full width. Feel free to reach out anytime if you're curious or want to check in on the direction and progress :)
