### ISSUE TITLE
Stacks balances not loading with 403 error

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4675]
Maybe this is similar to https://github.com/leather-wallet/extension/issues/4546

User reports that the wallet isn't showing any balances/assets/collectables

But I am seeing different error codes here compared to 4546
![image](https://github.com/leather-wallet/extension/assets/33360391/acd23ec3-4cd2-4dec-bd97-a61c1e45e04d)

In this case reinstalling the extension made no difference

**Comment by kyranjamie** [comment]
~Could it've been this~
<img width="931" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/43a06b15-e9e0-484a-87e3-1dd4ed39dd41">

Edit: probably not, that was a while ago. But looks like some kind of API issue

**Comment by 314159265359879** [comment]
You are right it wasn't the nov 28th outage, this was reported yesterday. The user has tried different computers and browsers already so I think it might be related to their internet connection. 

I have only seen one report like this so far.

**Comment by 314159265359879** [comment]
Hiro Systems has identified the root cause for these 403's, they were thrown by a cloudflare service relied upon. They are discussing a fix internally.
