### ISSUE TITLE
Signing in with hardware wallet sometimes results in "No LedgerRequestKeysContext found" if bitcoin app is on instead of stacks

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4682]
signing in at stacks.gamma.io while the ledger has the bitcoin app active will result in this error

![image](https://github.com/leather-wallet/extension/assets/33360391/c1a7d5a6-d44b-4839-b8ce-ff4471ead82e)

Switching to the stacks app on the ledger device results in the expected behavior.

**Comment by markmhendrickson** [comment]
Dupe? https://github.com/leather-wallet/extension/issues/4601

**Comment by markmhendrickson** [comment]
@edgarkhanzadian this this related to your work on https://github.com/leather-wallet/extension/issues/4786 and worth assigning to yourself as well to tackle concurrently?
