### ISSUE TITLE
Migrate Inscription send flow full page experience

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4684]
Per the designs, let's take users to a new page when they transfer an inscription.

[🎨 Figma link](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=4655-89956&mode=dev)

**Comment by mica000** [comment]
@kyranjamie anything needed from design in this task? if not, could maybe be moved to dev backlog?

**Comment by markmhendrickson** [comment]
Let's do this when we redesign the send flow in general, since this entire existing flow will be replaced
