### ISSUE TITLE
Remove "Ledger device in use" indication 

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4689]
From the top area of Ledger-related modals upon mouse-over since it's currently a confusing experience:

<img width="514" alt="Pasted Graphic" src="https://github.com/leather-wallet/extension/assets/28991/671d3257-adc9-44bc-81b1-d3056852e74f">

**Comment by pete-watters** [comment]
I can either:
- Always show this when the device is in use i.e. not just on hover
- get rid of it completely

I think it should be safe to just get rid of it as with the animation below it's clear the device is in use

**Comment by fabric-8** [comment]
Agree, just 🔥 it

**Comment by pete-watters** [comment]
This was removed and released
