### ISSUE TITLE
Prevent submission of sign-in screen when minimum values not yet entered

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4690]
The button is styled as disabled but I can still click it, and strangely when clicked, it shows an invalidation error and switches the button to enabled styling.

I would expect instead that I can't even submit / select the submit button, and if I tried, I wouldn't see any error message at all

https://github.com/leather-wallet/extension/assets/28991/62506847-8464-458c-ba6f-c7bc27219c96

**Comment by pete-watters** [comment]
This happens as there is slightly different validation needed for:
- when a user types
- when they copy paste a full key

I will try and keep the button in the disabled state and also allow pasting of a key. I tried this before but I can revisit it
