### ISSUE TITLE
Display icons on buy screen properly for dark mode

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4691]
Right now they're faded out. Should we simply display them on white backgrounds within each's square?

## Current

<img width="1208" alt="Screenshot 2023-12-04 at 17 00 05" src="https://github.com/leather-wallet/extension/assets/28991/cbe3c601-ff8c-4b25-afc8-f1c896681470">

## Proposal

<img width="261" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/69d29144-c679-4e3f-8b9f-fb1c226bf7bb">

cc @fabric-8 @mica000

**Comment by fabric-8** [comment]
Agree - Most reasonable solution for now
