### ISSUE TITLE
Fix excessive side padding for account picker within send flow

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4692]
When choosing account as recipient

<img width="1364" alt="Screenshot 2023-12-13 at 18 10 47" src="https://github.com/leather-wallet/extension/assets/28991/bcc925ed-f5f1-4763-b582-80d3d7e2bbd4">
<img width="1251" alt="Screenshot 2023-12-08 at 10 14 36" src="https://github.com/leather-wallet/extension/assets/28991/c077880f-5dc9-4194-8c41-24bd6fea1848">

**Comment by pete-watters** [comment]
Thanks Mark, I'll fix this in #4370

**Comment by pete-watters** [comment]
I'll test this against [this design](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=10155%3A272846&mode=dev) and make sure the spacing is OK
