### ISSUE TITLE
Fix fee selection while sending BRC-20 tokens

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4704]
The fees screen just refreshes without showing an error message in the UI, though I see an error in the console:

  

https://github.com/leather-wallet/extension/assets/28991/00724c18-7fbb-4d96-ba3c-a186a5e07a83

**Comment by pete-watters** [comment]
I was investigating this yesterday and acquired some `SATS` in our shared wallet to try and replicate the issue.

**Comment by kyranjamie** [comment]
The modal you're interacting with in this video is the feature to recover BTC on a taproot address that isn't inscribed. This doesn't have anything to do with BRC-20

**Comment by pete-watters** [comment]
OK, my mistake. I'll get rid of it to remove ambiguity here.

**Comment by markmhendrickson** [comment]
I'm closing this issue since we intend to disable BRC-20 sends per https://github.com/leather-io/extension/issues/5773
