### ISSUE TITLE
Stamps not loading in the wallet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4706]
Several users have reported that stamps are not loading in the wallet and we see that too. There are no errors shown in the console. 

One user mentioned that their stamps are loading in Account 1 but none of them in other accounts. I don't have any wallets with stamps in account 1 so I can't retest that. 

Workaround to see and transfer stamps users can sign in on openstamp.io and login, then go to their profile to see their assets.

**Comment by 314159265359879** [comment]
This was posted in Telegram 15 minutes ago. It looks like openstamp.io's indexer also has an issue now.

![image](https://github.com/leather-wallet/extension/assets/33360391/9ab2b654-5ea1-4c86-91ee-60e75d30a0b5)

**Comment by 314159265359879** [comment]
API Leather shows empty address: 
https://stampchain.io/api/stamps?wallet_address=16ty9iygA4N1uw8Tu7ssGV5SeHscAAXjXP
![image](https://github.com/leather-wallet/extension/assets/33360391/e7b3dc69-9175-43b2-a0c3-6a8b21f53459)

Whereas this is what is displayed on xchain.io
https://xchain.io/address/16ty9iygA4N1uw8Tu7ssGV5SeHscAAXjXP
![image](https://github.com/leather-wallet/extension/assets/33360391/a13d1108-f421-4230-97e5-241f0cc8ae28)

**Comment by brandonmarshall-tm** [comment]
It would be difficult to troubleshoot this issue now due to indexer/API problems, but it has been going on for the past several days now so likely unrelated to this most recent downtime

**Comment by brandonmarshall-tm** [comment]
Perhaps it was just an API issue, I just opened my wallet this morning and am seeing my Stamp for the first time in a while

**Comment by 314159265359879** [comment]
This API is working again now:
https://stampchain.io/api/stamps?wallet_address=16ty9iygA4N1uw8Tu7ssGV5SeHscAAXjXP
 Looks like someone at stampchain.io fixed it for us, we don't have to switch API's then. closing this now. 
 
 
![image](https://github.com/leather-wallet/extension/assets/33360391/78f11877-e124-4c35-9c51-f934ed32a991)

**Comment by 314159265359879** [comment]
@markmhendrickson how do we ever show error states for an error like this by the way. The API looks like it is working but it returns an empty json array instead of the full one. How would the wallet know empty isn't correct? 
An error state is easier when the API returns a 404- or 429-like error I guess. 

For a more general status of all the services the wallet uses we can use known addresses and what they should return then show errors if that doesn't meet the expectation, right? Then it would help in cases like this.

**Comment by markmhendrickson** [comment]
I'll make a note for us to take these sorts of error states into consideration as we redesign the collectibles area.
