### ISSUE TITLE
Unable to see the details on the BTC transfer summary screen

### ISSUE THREAD

**Issue by edgarkhanzadian** [blockstack/blockstack-app#4714]
v6.20.0

The stars are manually added using chrome devTools to hide the address

https://github.com/leather-wallet/extension/assets/22010816/5a936241-d848-4c72-ac15-0f5a200e6399

**Comment by pete-watters** [comment]
I think this has been solved in https://github.com/leather-io/extension/pull/5778 

https://github.com/user-attachments/assets/49427174-aa60-4429-9d34-89e93becfea7

It's unclear if this is a re-sized large window or else a popup window but I think it's solved
