### ISSUE TITLE
Investigate failing tests 

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4718]
Several tests are failing. This task is to investigate the cause of them, and suggest changes as to how we can fix them.

**Comment by markmhendrickson** [comment]
Mind indicating which tests are failing?

**Comment by kyranjamie** [comment]
These can be found in the test reports of all the PRs. The swap tests for example.

**Comment by markmhendrickson** [comment]
These are the same tests for `dev` that we'll host on our own subdomain soon, yea?

**Comment by kyranjamie** [comment]
Yeah. They're failing on all our PRs, so all devs are aware of the troublesome tests

**Comment by pete-watters** [comment]
Tests have been running more reliably lately apart from `Shard 5` which often times out. 

It gives the error:
```
1) [chromium] › specs/send/send-btc.spec.ts:21:9 › send btc › btc send form › that it shows preview of tx details to be confirmed 

    Test timeout of 30000ms exceeded while running "beforeEach" hook.

       9 |
      10 | test.describe('send btc', () => {
    > 11 |   test.beforeEach(async ({ extensionId, globalPage, homePage, onboardingPage, sendPage }) => {
         |        ^
      12 |     await globalPage.setupAndUseApiCalls(extensionId);
      13 |     await onboardingPage.signInWithTestAccount(extensionId);
      14 |     await homePage.enableTestMode();


```

Generally they pass after 1 / 2 re-runs but it would be great if we can make them run reliably or else get rid of un-reliable tests and cover the functionality with better tests.

**Comment by edgarkhanzadian** [comment]
is this issue still relevant? Or should it still have a p2 priority?

**Comment by kyranjamie** [comment]
Let's close until we run into test issues again
