### ISSUE TITLE
UTXOs appear locked to the user

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4723]
A user reported a UTXO (A) as unavailable in Leather. And they had to use another wallet to access the funds 0.007 BTC to send it out. 

It looks like there were only 12 blocks between this confirmation and the other transaction (B) sending it out. So I wonder if there was an error that caused the address balance not to update. Outdated API perhaps? 

The user thinks the UTXO was locked, although it contained no inscription and I see no other reason for it to have been locked/unavailable. 

The user reported seeing this before on sats that return to the wallet after a transaction (leftover inputs basically). I wonder if the wallet is affected because it contains a lot of history 376 transactions. And according to the user a total of 69 UTXO's (mostly minor ones). 

bc1qzl5xt45gazvj2j4su2xdm5tftqkckgst5hhald

**Comment by markmhendrickson** [comment]
Have we seen this again? I'm closing as stale, but please reopen if we have.
