### ISSUE TITLE
Contract call, contract should be clickable to visit it on explorer.hiro.so

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4724]
![image](https://github.com/leather-wallet/extension/assets/33360391/1ae8274c-db48-4fd6-98a4-d163c152808c)

**Comment by markmhendrickson** [comment]
cc @mica000 for approval UX

**Comment by 314159265359879** [comment]
This is live/fixed from version 6.52.0. Is this issue still relevant for the redesign or can we close it? @camerow
