### ISSUE TITLE
Block merge of PRs with failing tests

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4730]
We are able to click `Merge when ready` on PRs that have failing tests which can introduce problems like:
- https://github.com/leather-wallet/extension/issues/4725

I'm not sure if we can stop this happening but we should try

**Comment by kyranjamie** [comment]
I'm confused by Github's UI

<img width="823" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/80dc1248-b6a0-40ad-b62e-35946fdf344f">

I want all statuses to pas, yet it gives me the option to specify individual ones?

[Gosh, it says here that yeah, you have to select them individually....](https://github.com/orgs/community/discussions/75568#discussioncomment-7570257)

**Comment by pete-watters** [comment]
> Gosh, it says here that yeah, you have to select them individually....

Yeah its a bit confusing. I think we may also need to add `dev` as a protected branch but I'm not sure if that would introduce other headaches?

**Comment by kyranjamie** [comment]
It already is, these are the protected branch rules. Added them manually for now, does this change your merge UI?
<img width="726" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/5b1dbd44-3a28-497e-b088-32e7d201ac74">

**Comment by pete-watters** [comment]
It has added these checks and is now blocking merge if checks aren't passing. Thanks for the quick action on this 👍 

Checks show as required:
![Screenshot 2023-12-19 at 10 17 24](https://github.com/leather-wallet/extension/assets/2938440/d03d716d-cfc6-4a64-88a1-a94e11c03171)


You can click `Merge when ready` but its not green anymore
![Screenshot 2023-12-19 at 10 18 52](https://github.com/leather-wallet/extension/assets/2938440/75e8e4be-ec72-44d5-afd3-bb4b6418861a)


When you click it, if the tests aren't passing then you won't be able to merge
![Screenshot 2023-12-19 at 10 19 07](https://github.com/leather-wallet/extension/assets/2938440/2c5982ec-88f2-49a1-adc0-de39cf0b7749)

**Comment by pete-watters** [comment]
We might need to do some more work for external contributor PRs as some of the now required checks don't pass. You can see on this PR: https://github.com/leather-wallet/extension/pull/4751 

The test's can't pass on their PR as they don't have the required key but it would be handy if `lint` / `prettier` / `typecheck` can run.

We should probably change the test code back so the key is available to them. That way we could run the full suite of checks properly on their PR. 

I'm happy to help do this, just wanted to add a note here

**Comment by pete-watters** [comment]
Kyran helped me understand the process for merging external PRs better so we don't need to do this. They won't be able to run all CI actions for security reasons but we have made a good improvement here blocking PRs with failing tests merging.
