### ISSUE TITLE
BRC-20 tokens don't appear in wallet until a re-install is performed

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4732]
I bought some BRC-20 `SAT`s for testing on UNISAT and was worried as they hadn't appeared in my wallet for a long time. 

I could see:
- some BTC available under collectibles that I was told is unrelated
- an ordinal inscription for the `SATS` amount 

@markmhendrickson suggested that I try re-install the wallet and when I did that on a fresh installation I could see my `SATS` and also an ordinal I purchased started showing correctly. I am using Brave browser

https://github.com/leather-wallet/extension/assets/2938440/de231d8e-33b3-434a-b27b-5875dca816f9

**Comment by kyranjamie** [comment]
I wonder if this is just query cache settings not updating quick enough? Un/reinstalling would've cleared cache, but perhaps with time it would've updated?

**Comment by pete-watters** [comment]
> I wonder if this is just query cache settings not updating quick enough? Un/reinstalling would've cleared cache, but perhaps with time it would've updated?

Quite possible but I made this transaction yesterday and it was still waiting today. The ordinal I had also didn't show up properly until I re-installed. 

I can take a look at the caching and do some more investigations

**Comment by kyranjamie** [comment]
If this was prod, @fbwoolf only just made a change such that the ordinals with refresh on reload. So perhaps it's fixed already

https://github.com/leather-wallet/extension/blob/591bb292430e48040c3f1abf6b2e91479e76d28f/src/app/query/bitcoin/ordinals/inscriptions.query.ts#L182

**Comment by fbwoolf** [comment]
It looks like we have a `useGetBrc20TokensQuery` that still has that set to `false`.

**Comment by pete-watters** [comment]
This was on `prod`. I can test it a bit more to see if it's fixed and if updating `useGetBrc20TokensQuery` makes a difference
