### ISSUE TITLE
Empty Test Displayed When Creating a Custom Network Without a Name

### ISSUE THREAD

**Issue by Nithishvb** [blockstack/blockstack-app#4737]
In the header, the network badge text appears empty when a custom testnet network is added without a name.

![Screenshot 2023-12-20 222406](https://github.com/leather-wallet/extension/assets/83941930/8c30d5c5-0e50-40ec-b70e-51066f0843be)

Steps to reproduce:
1. In the settings, select **change network**.
2. click **add network.**
3. Choose from regtest, signet, or testnet.
4. After that, click **add network** without providing the network a name.

**Comment by pete-watters** [comment]
Thanks for raising this issue @Nithishvb. The bug here is that we should enforce validation of custom network names. 

Do you think you would like to tackle that?

**Comment by Nithishvb** [comment]
Hi @pete-watters Thanks for bringing up the issue, and I appreciate the opportunity to contribute. I'm interested in tackling the bug related to enforcing validation of custom network names.
