### ISSUE TITLE
Bitcoin balance not shown on Firefox, console error CORS preflight response did not succeed...

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4739]
The user who reported seeing these blockstream api errors in the console with Firefox and wallet version 6.21.1 they saw it resolved when they switched to Chrome.

![image](https://github.com/leather-wallet/extension/assets/33360391/ab07979a-779d-475f-ab8c-89f1326a3561)

Keeping an eye on this to see if it only pops up in Firefox.

**Comment by markmhendrickson** [comment]
I'm closing this issue since Firefox support is deprecated.
