### ISSUE TITLE
Fix fee recommendations via API to send BTC

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4742]
We've received reports that fee recommendations are way too high sometimes when apps prompt users to transfer BTC via the app (whereas they seem fine when users send BTC via the wallet UI itself).

[See here in Slack](https://trustmachines.slack.com/archives/C05K6H9T545/p1703172165508389)

Also reported here via Discord:

<img width="658" alt="fees bug" src="https://github.com/leather-wallet/extension/assets/28991/364c8cc4-ffdf-40f6-abf5-e3190c86d3ba">

**Comment by 314159265359879** [comment]
I have seen other issue like this reported too. possibly related to UTXO selection, a user reported that setting a fee rate in sats/vB manually still yielded a high absolute fee. Which indicates the wallet is creating a transaction with many inputs and/or outputs making it sizeable and hence expensive to include in a block.
