### ISSUE TITLE
Allow user to customize transaction fee from signing review screen

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4743]
Currently it's only possible only before arriving at the review screen (e.g. as an option in the send form for Stacks transactions, and as an interstitial screen after the send form for Bitcoin transactions).

We should provide an option to customize them on the review screen itself.

**Comment by fabric-8** [comment]
Since we're tackling this in the context of a different project: Does this need to be addressed independently & earlier?

**Comment by markmhendrickson** [comment]
This should be addressed as part of the overall work for [Redesign approval UX](https://github.com/leather-wallet/extension/milestone/75).

**Comment by mica000** [comment]
btw, fees will only be possible to be edited from the review screen and not from the send anymore - correct?

**Comment by markmhendrickson** [comment]
Exactly

**Comment by mica000** [comment]
@fabric-8 adding you since you are tackling the fees component.
