### ISSUE TITLE
Sentry session replay

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#4748]
We could enable Session Replay on Sentry to help us better diagnose bugs: https://docs.sentry.io/product/session-replay/getting-started/

I'm not sure if this would conflict with our decentralised ethos though

**Comment by kyranjamie** [comment]
Security risk to this feature. I was on a call with Sentry team a while back, and one of their EMs also said "Don't use this feature" as it risks leaking keys.
