### ISSUE TITLE
Enable swaps when sponsorship unavailable

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4750]
Using the in wallet swap users are hitting this error:

I think it is happening because the swap provider address has a full queue ~25 transactions. The address sending this is not hitting this issue. It is very likely related to congestion issues due to increased activity on the network. 

![image](https://github.com/leather-wallet/extension/assets/33360391/44195d94-fd94-4f58-b98e-292c86f5475f)

I see two issues
1. Wallet attempts a sponsored transaction when the wallet has STX, it shouldn't it would prevent this issue. 
2. We should do a better job at explaining what is going on here

Reproduce by swapping in the wallet from a SIP010 token like USDA to STX when you have no other pending transactions in your wallet. I have not tested other scenario's.

**Comment by markmhendrickson** [comment]
It seems like we would benefit from enhancing swaps so they fall back to non-sponsored transactions if the sponsorship capability isn't available. 

> I think it is happening because the swap provider address has a full queue ~25 transactions.

Can you confirm with the ALEX team that this is the underlying cause, and @fbwoolf do you know if the SDK has a method already for checking whether the sponsorship capability is available (so we don't have to try and catch errors to handle per se)?

**Comment by fbwoolf** [comment]
> Can you confirm with the ALEX team that this is the underlying cause, and @fbwoolf do you know if the SDK has a method already for checking whether the sponsorship capability is available (so we don't have to try and catch errors to handle per se)?

I see this, but I'm not sure it is a dynamic value based on congestion? https://github.com/alexgo-io/alex-sdk?tab=readme-ov-file#issponsoredswapenabled

**Comment by fbwoolf** [comment]
I asked their team for feedback.

**Comment by 314159265359879** [comment]
@fbwoolf and @markmhendrickson 

I already checked with Chan. ALEX expected us to have a toggle for sponsored or not sponsored. I think we should never use sponsored transactions if the address has STX to cover fees. I think we'll see this error less already after that. 
![image](https://github.com/leather-wallet/extension/assets/33360391/fe131069-5654-460b-8e96-ccc1365e11ec)

![image](https://github.com/leather-wallet/extension/assets/33360391/6e144036-82ee-4d99-8bd2-820ec531d44a)

When the address has no STX we don't need a toggle either because using a sponsored transaction is the only option the user has.

I think it could have better messaging here though because right now this error looks like it is thrown because the user has too much of a pending queue, but they have none. I am not sure if the wallet can make the distinction between toomuchchaining at the sponsor address or the user's address so different errors can be displayed?

**Comment by fbwoolf** [comment]
@314159265359879 thx for the feedback. We were never told by the ALEX team to check for fees first, but I can make that change as part of this issue. Right now, if there is no pending tx we try to broadcast a sponsored tx. If there is a pending tx, the wallet broadcasts the swap with fees applied. I did recreate this error, and it appears to be when using a sponsored tx (the error is from ALEX though shown in generic error page). If the user sends a small tx and tries to swap again while that is pending, the swap should broadcast without an error. I did confirm this is working.

**Comment by 314159265359879** [comment]
I have asked Chan to take another look at this. And asked if they can share the sponsoring address so we can check the queue, see what is causing it to be full. If it is just increased use our solution to use it only when there is no STX in the wallet can help mitigate that in the future. Perhaps there is something else causing it to get locked (nonces/balance or such). It could help ALEX to know in any case.

**Comment by fiftyeightandeight** [comment]
@zhigang1992 would you please confirm `TooMuchChaining` stems from our sponsored service having too many requests to deal with (due to recent network congestion)?
Assuming this is the case, the current strategy of checking pending tx to determine whether to broadcast a sponsored tx would not cover this particular scenario.
Given that we are working to standardise our sponsored service (with user being able to choose aBTC or STX for network fee), instead of trying to do a quick fix, do we think it makes more sense to, temporarily, make available non-sponsored service only (while we upgrade our infrastructure)?

**Comment by fbwoolf** [comment]
>  instead of trying to do a quick fix, do we think it makes more sense to, temporarily, make available non-sponsored service only (while we upgrade our infrastructure)?

@markmhendrickson what is your pref here, to remove the sponsored tx for now in all cases or keep for only when the user has no STX to pay the tx fee? We could also try/catch the sponsored tx and broadcast it ourselves if the sponsored tx fails, but I'm not sure what we would want to do from a UX perspective on this?

**Comment by markmhendrickson** [comment]
If sponsorships are unreliable atm, then let's remove for everyone as a clean hot fix. Then we can move this issue back to the product backlog for further consideration about how to reintroduce.
