### ISSUE TITLE
Transaction Broadcast Error

### ISSUE THREAD

**Issue by pmvault** [blockstack/blockstack-app#4754]
Hi good evening i have leather extension with my ledger connected on my edge browser

and try to increase Stacks(STX) fees to speed up my transaction (i try this also on brave browser and get the same error)

**Your transaction failed to broadcast because of the error: Cannot read properties of undefined (reading 'forEach')**

i made every step correct and in last moment when i need to get confirmation of increase in transaction fees i get the error

![error](https://github.com/leather-wallet/extension/assets/154621392/07db0739-b59f-40e9-9f3a-20576ca63447)

**Comment by 314159265359879** [comment]
Hi @pmvault thanks for reporting sorry, you are running into this issue. We are aware of this issue but we do not have a fix for it yet. It is tracked here: https://github.com/leather-wallet/extension/issues/4503

You can work around it though. Do the following: create a new transaction instead and then give it the same nonce as the pending one (nonce is 1). That way the old transaction is also replaced. Remember to set the fee you want. By setting a higher fee than the pending transaction it is replaced (replace by fee/RBF)

To change the nonce: click "edit nonce" above the confirm button to set it manually. 

You can check the current nonce of your pending transaction by checking the transaction on explorer.hiro.so.

**Comment by pmvault** [comment]
Hi thanks for your help :)

I will give it a try 
i suppose since is my first transaction that nonce need to be 0 ... Right?

Regards

**Comment by 314159265359879** [comment]
Yes start with 0 in that case. You can always check by clicking the transaction in the activities tab, you'll see the details on explorer.hiro.so
