### ISSUE TITLE
"Increase fee" does not replace the existing transaction but create a new transaction

### ISSUE THREAD

**Issue by fyang1024** [blockstack/blockstack-app#4759]
I am not sure if it's the wallet's issue or the stacks blockchain's issue.
When I increase fee for an pending transaction, it does not replace the existing transaction but create a new transaction

https://explorer.hiro.so/txid/0x297dc1eb1417afad7c95836c2f1136f8afcf38e83d677a9d9531f3d21384d215?chain=testnet is the original transaction
https://explorer.hiro.so/txid/0xdf2ff5d9d58fe5bf05ff0a559abbd35f56fda1d0d528181bbfa87e51c2d64323?chain=testnet is the transaction when I increased the fee

**Comment by 314159265359879** [comment]
Thanks for posting. I saw you also posted on the stacks core repo: https://github.com/stacks-network/stacks-core/issues/4221

Quote from my reply there
>I believe this is currently working as intended atleast from the stacks-core perspective, I think what is not intended is that the wallet shows these "duplicate" transactions when they are not completely replaced on all nodes before one of them gets mined (that is what happens in the ideal situation).

>
>They are unprocessable transactions and should be classified as such by the API, wallets use to display the status of transactions. This could help resolve https://github.com/hirosystems/explorer/issues/1038 (API side), https://github.com/leather-wallet/extension/issues/1867 (wallet side)

>
>And perhaps this discussion could mean other solutions entirely if it can be changed at the core: https://github.com/stacks-network/stacks-core/issues/4129

I think hiding these transactions in the wallet is a good idea, they just confuse users as it is now.

**Comment by fyang1024** [comment]
Thank you. I'll close it now since it's been worked on
