### ISSUE TITLE
Fix ability to select last account without having to create new one

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4764]
https://github.com/leather-wallet/extension/assets/28991/e84f213a-e53b-42f6-a7ef-5cd047882fc8

**Comment by pete-watters** [comment]
This will be solved once I can get https://github.com/leather-wallet/extension/issues/4371 merged

**Comment by pete-watters** [comment]
This is fixed in https://github.com/leather-wallet/extension/pull/4655
