### ISSUE TITLE
This type of Stacks NFT is not displayed in Leather, the API does return metadata

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4766]
SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.happy-welsh

https://api.hiro.so/metadata/v1/nft/SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.happy-welsh/749

`{"token_uri":"ipfs://QmTZ7BtjVrxGnELvzb2HXv3K7mf6PQ4Mvgz7nvpWdFKtCQ/749.json","metadata":{"sip":16,"name":"Happy Welsh #749","description":"","image":"ipfs://QmajLS1WEMdBCNPwFh3yRKPxSiYQnfiZqooSyreGsXtzX1/749.png","cached_image":"https://ipfs.io/ipfs/QmajLS1WEMdBCNPwFh3yRKPxSiYQnfiZqooSyreGsXtzX1/749.png","attributes":[{"trait_type":"Background","display_type":"","value":"Green"},{"trait_type":"Body","display_type":"","value":"Plain"},{"trait_type":"Eye","display_type":"","value":"Shy"},{"trait_type":"Neck","display_type":"","value":"Blue Bowtie"},{"trait_type":"Hair","display_type":"","value":"Red Mohican"},{"trait_type":"Mouse","display_type":"","value":"Bone"}]}}`

https://ipfs.io/ipfs/QmajLS1WEMdBCNPwFh3yRKPxSiYQnfiZqooSyreGsXtzX1/749.png

**Comment by markmhendrickson** [comment]
This is best to file in the API repo?
