### ISSUE TITLE
Issues of no (BTC) balance being displayed (error 500)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4775]
User reported not seeing Bitcoin balance. Switching browser from Chrome to Brave or Edge, had no effect. 
![image](https://github.com/leather-wallet/extension/assets/33360391/0d61cc6c-2c98-4a3d-b143-660bf1c646e6)

Although the screenshot appeared to have other errors off screen... these were the only readable ones. 

Checking it again later showed nothing
![image](https://github.com/leather-wallet/extension/assets/33360391/ba20b59d-1186-4fd4-b486-c9b354d3a211)

**Comment by markmhendrickson** [comment]
I'm closing as stale but please reopen if persistent.
