### ISSUE TITLE
No BTC balance displayed in the wallet (error 400)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4776]
User already tried to install leather on a different browser, Brave, Chrome no change. No change turning of their VPN. 

Console error shared
![image](https://github.com/leather-wallet/extension/assets/33360391/30fc3b32-ed69-4ac3-bf59-38a61048f906)

**Comment by markmhendrickson** [comment]
Have we seen more recent incidences of this?

**Comment by 314159265359879** [comment]
Yes, all recent cases were confirmed to be related to https://github.com/leather-wallet/extension/issues/4248 (too many history entries), I am closing this in favor of that issue.
