### ISSUE TITLE
Fee set in Leather is not what it is transmitted with

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4777]
The user reported selecting medium or high, they were likely 34 low, 36 mid, 38 sats/vB high. Average fees went to 45 quickly then 60 and back to 40 again. 

![image](https://github.com/leather-wallet/extension/assets/33360391/f24f8c78-1140-4fe5-abbc-964870ab1321)

Looks like this one that was fixed recently: https://github.com/leather-wallet/extension/issues/4541

**Comment by brandonmarshall-tm** [comment]
Another potential example of this issue: https://twitter.com/cexaline/status/1744720263185637681

**Comment by 314159265359879** [comment]
Another one, send with a custom fee of 50 sats/vB
resulted in fee rate of 40.1 sats/vB
![image](https://github.com/leather-wallet/extension/assets/33360391/4dbddc7a-1448-428b-86a4-01974ee373b4)
https://mempool.space/tx/df304fddd627eb252a384c1c4ca01a4a4cc13e23ab2475a7356032496ed6f27d

**Comment by 314159265359879** [comment]
One more user, wallet version 6.23.0 (software wallet)
User sets a custom fee rate for a normal BTC transfer (1 input, 2 outputs native segwit about 140 vB size)

They have these settings 90 sats/vB (expected total fee about 140*90=13000)
![image](https://github.com/leather-wallet/extension/assets/33360391/60d555ba-5035-4844-85d2-664d1aee7715)
And this result
https://mempool.space/tx/4eeb840748175f88070537f17fb787d724bcaa0f4169ac13d73f8683b2449e6e
![image](https://github.com/leather-wallet/extension/assets/33360391/b6531f0d-d588-40f1-b00c-019964138fde)
![image](https://github.com/leather-wallet/extension/assets/33360391/cb3ee4f0-d3e6-4f9d-9ba6-36d79f5dd128)

The user updated to the latest version (6.25.0)

Trying again, fifth transaction
![image](https://github.com/leather-wallet/extension/assets/33360391/1ec96516-94d9-4787-b988-9cd16c2c78d0)

This time we know the total isn't correct so we double the fee rate to see if we can get it to the target of about 18000 sats, user sets a fee rate of 260 sats/vB...
![image](https://github.com/leather-wallet/extension/assets/33360391/2ba6d2b2-1560-4af8-940c-fc9a9b3a86c0)

resulting in a fee rate of 135 sats/vB
https://mempool.space/tx/c07e5d3d624e513b068c11da05142c11d61ee9854e3760437a4e750aaae33e2b
![image](https://github.com/leather-wallet/extension/assets/33360391/a92bbd94-a8bf-4b42-8e5a-44c8e973641e)

**Comment by 314159265359879** [comment]
I just reproduced the issue with custom fee on testnet. reproduction steps:
Click send
Select bitcoin
enter amount 6000 sats
select account (account 2)
set fee of 12 sats/vB
note the total fee 
Transmit
see error, total fee on mempool.space is reflected as similar while fee rate is ~half.

**Comment by 314159265359879** [comment]
two more examples:
Fee rate set in Leather: 35 sats/vb ( custom setting )
On mempool.space: 28.1 sats/vb
https://mempool.space/tx/19d10a73e72f714ec373fc8dfde93b3206aa9be92cfdf894e329b6f283d92262

Fee rate set in Leather: 45 sats/vb ( custom setting )
On mempool.space: 48.5 sats/vb
https://mempool.space/tx/19d10a73e72f714ec373fc8dfde93b3206aa9be92cfdf894e329b6f283d92262

**Comment by friedger** [comment]
I have experience this as well. Set custom fee to 16 sats/vB and was broadcasted with 8.8 sats/vB using v6.27.2 and ledger.
Using increase fees with ledger worked as expected.

**Comment by markmhendrickson** [comment]
@edgarkhanzadian thoughts on what's causing this behavior?

**Comment by 314159265359879** [comment]
I saw this again today, set a custom fee of 10 sat/vB and transaction transmitted with 8.02 sat/vB
Set a 31 sat/vB fee and it transmitted with 16.1 sat/vB fee, the total fee was accurately displayed in preview (but that resulted in 16.1 fee).

**Comment by brandonmarshall-tm** [comment]
New user report:

Leather wallet keeps broadcasting my transaction at a lower fee than i initial submitted. 

the tnx - 

[mempool.space/tx/f095d8a17a…](https://mempool.space/tx/f095d8a17a8b85f6911253761e27cbb5e75b5e39929a2c2e2ee11bbac2c1574a#accelerate)

[mempool.space/tx/fa00f6865a…](https://mempool.space/tx/fa00f6865a2ba93da4153eee90df3f58a3f1952b2bd7e56fc89d9c8099f0b9fb)

both were set to +90satvb and 120satvb ish 

in the mempool its showing a lower fee 

i would appreciate if u look into it

**Comment by markmhendrickson** [comment]
Related threads over the weekend – [1](https://trustmachines.slack.com/archives/C05114YP8CV/p1713627525210939), [2](https://trustmachines.slack.com/archives/C05LAP952E7/p1713514301692809)

**Comment by 314159265359879** [comment]
> New user report:
> 
> Leather wallet keeps broadcasting my transaction at a lower fee than i initial submitted.
> 
> the tnx -
> 
> [mempool.space/tx/f095d8a17a…](https://mempool.space/tx/f095d8a17a8b85f6911253761e27cbb5e75b5e39929a2c2e2ee11bbac2c1574a#accelerate)
> 
> [mempool.space/tx/fa00f6865a…](https://mempool.space/tx/fa00f6865a2ba93da4153eee90df3f58a3f1952b2bd7e56fc89d9c8099f0b9fb)
> 
> both were set to +90satvb and 120satvb ish
> 
> in the mempool its showing a lower fee
> 
> i would appreciate if u look into it

These are confirmed by now but I see they are also part of a CPFP chain... could be caused by this issue other issue (https://github.com/leather-wallet/extension/issues/4037 ) rather than 4777.
