### ISSUE TITLE
Routing issue: clicking sign out shows the your password page

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4783]
I was able to sign out previously without issue on version 6.21.2 
I have seen one other user report the same issue but couldn't reproduce it then. Also wasn't reproducible after I unlocked the wallet and locked it again. The user who experienced this was unable to unlock their wallet and decided to reset it instead. 

https://github.com/leather-wallet/extension/assets/33360391/b3c66265-43b5-4734-9b38-45a730e26924

**Comment by markmhendrickson** [comment]
Also seeing it 

https://github.com/leather-wallet/extension/assets/28991/0d56963b-9b5e-4abd-b731-644c39140698

**Comment by 314159265359879** [comment]
This is unresolved in version 6.24.0

**Comment by pete-watters** [comment]
This isn't fixed yet as I have been busy trying to finish #4370 . I'll un-assign myself for now and get to it as soon as I can

**Comment by pete-watters** [comment]
I'll just fix this as part of https://github.com/leather-wallet/extension/issues/4370. 

It's very similar to https://github.com/leather-wallet/extension/issues/4826 and relates to problems with our routing from the settings menu.

**Comment by 314159265359879** [comment]
I tested this with the #4655 PR and I see it fixed. Users can sign out when the wallet is locked again once that is released.
