### ISSUE TITLE
Design system: Tags

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4794]
Updated tags ready for review:

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=13136-23521&mode=design&t=D87RVUYDDbUWp8ZU-4

![Image](https://github.com/leather-wallet/extension/assets/119523541/1227627f-0645-4b01-8046-c75a33923afc)

**Comment by 314159265359879** [comment]
Labels look great!

@mica000 I prefer showing the name of the testnet instead of an icon "testnet", "devnet", "custom-alex-testnet" because it can have a custom name too, developers may use different testnets and it is very helpful when it is clear which one you are on in a single glimpse. 
Also convenient for troubleshooting with screenshots because then the testnet is visible on the screenshot.

**Comment by mica000** [comment]
thanks for the input @314159265359879, wasn’t aware of this! 

@markmhendrickson perhaps then we need to keep the text?

**Comment by markmhendrickson** [comment]
How about allowing the user to set a custom emoji per network?

**Comment by fabric-8** [comment]
I like @mica000's suggestion, but given @314159265359879's input I'd also prefer to simply expose the testnet name in case of a testnet being selected. user-selected emoji is a nice touch, but would only partially solve the raised issues while adding more work to build the UI — Let's rather do this for account settings? :)

**Comment by mica000** [comment]
I agree, I think allowing users to set their own emoji will bring more benefits on the accounts, where personalisation is more important.

**Comment by fabric-8** [comment]
If we agree and to clarify: This is the label we're specifically talking about here then right?

Would the task the be: Build the label component as reflected in the design system. Use this label style/config for testnet labels in the app header:

![Image](https://github.com/leather-wallet/extension/assets/4112698/979112c4-709c-4ea6-86d3-a611867c7876)


![Image](https://github.com/leather-wallet/extension/assets/4112698/a5ef22c9-c787-466e-9f6b-fc238d7a33f0)

**Comment by mica000** [comment]
Yes, this and it's color variants

**Comment by mica000** [comment]
@fabric-8 I believe this is ready for implementation?

**Comment by markmhendrickson** [comment]
Per my comments in Figma about this design – it seems confusable with a button?

**Comment by markmhendrickson** [comment]
@kyranjamie any input here from your end as a reviewer?

**Comment by kyranjamie** [comment]
No feedback, these are very easy to build. Though see Mark's point on confusing with a button.

**Comment by mica000** [comment]
hmm true, but if you also look around the tags in github, these could also be confused as a button. Also important to highlight that a tag in screenshot is seem in isolation which can be misleading, it's better to analyse them in context:

<img width="977" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/662c8912-3b40-4f0f-91a8-4659f2807918">

**Comment by markmhendrickson** [comment]
> but if you also look around the tags in github, these could also be confused as a button. 

You mean these tags? They _are_ buttons 🤓 

<img width="253" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/cc657f90-b2f6-42ec-b23f-c69e1cdd2545">

**Comment by markmhendrickson** [comment]
Or maybe you mean this one – which admittedly isn't 

<img width="340" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/ed92d97c-d398-4145-b03a-24c7ec74043d">

**Comment by markmhendrickson** [comment]
It might work well on GitHub since the normal buttons have a different corner radius to distinguish?

<img width="389" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/5c30b466-7de5-4891-ab44-202a3e3541f8">

**Comment by mica000** [comment]
> > but if you also look around the tags in github, these could also be confused as a button.
> 
> You mean these tags? They _are_ buttons 🤓
> 
> <img alt="image" width="253" src="https://private-user-images.githubusercontent.com/28991/299672990-cc657f90-b2f6-42ec-b23f-c69e1cdd2545.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODk1MTMsIm5iZiI6MTcwNjE4OTIxMywicGF0aCI6Ii8yODk5MS8yOTk2NzI5OTAtY2M2NTdmOTAtYjJmNi00MmVjLWIyM2YtYzY5ZTFjZGQyNTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEzMjY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZGZkOWUwOWYzMmRjOGUxYWE3MGFmNzhhOTkwMzQ3ZGM2MGNkOWM0MmY2NzgwNGU1OWZjODlmNjYzZTdlYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._0a4rEbW4wJOLiew2qpfg2z9aweY7LUDz7hxRuPuAoU">

Wouldn’t consider this as buttons because they dont have all the states of a button.. seems more like a clickable label?
But anyhow.. buttons and labels are similar in a way because it a text surrounded by a box, and I guess this is where it gets confusing..

To consider: 
1. Labels with rounded corners are 8px wider than the ones proposed above because of the space they need to form a curve. On the component it's used, which the header, this means we have less space for page titles.

2. It relation to our corner radius scale and branding, this seems a bit strange to me, but adding an image for other to judge: 

<img width="1022" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/e6c99c7f-e587-4bce-8215-a9320e0ec700">

**Comment by mica000** [comment]
With colors:
<img width="975" alt="Screenshot 2024-01-25 at 14 45 01" src="https://github.com/leather-wallet/extension/assets/119523541/4a9a40d0-e105-49e2-8f2c-852131c6a6dd">
<img width="981" alt="Screenshot 2024-01-25 at 14 43 59" src="https://github.com/leather-wallet/extension/assets/119523541/56f1ad0d-14b9-48fb-94d8-36bd746c8b0d">

**Comment by kyranjamie** [comment]
I think that's a good point to raise: Do we intend for labels to be interactive at all? E.g. the testnet label is clickable in some parts of the app

Notice the Github labels do have focus states 
<img width="219" alt="image" src="https://github.com/leather-wallet/extension/assets/1618764/a1fe0f56-f7bc-42af-a1a0-fb8f405a40d5">

**Comment by mica000** [comment]
Could be interesting to have them clickable and hovered but not sure we need to give a visual feedback for both states. Think the only state that might be valid is the focus one - thoughts?

**Comment by mica000** [comment]
@markmhendrickson and @kyranjamie I fixed the color use case for red, yellow, blue and green and now we it also fixes the way we use these colors on the tags. could you please review this new tag proposal?

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=1607-0&mode=design

**Comment by kyranjamie** [comment]
I like option 2. These are much more neutral, background colours. I don't think labels need to have as much contrast/saturation as option 1.

**Comment by mica000** [comment]
ok, let's use these ones then. Ok to move this to dev backlog @kyranjamie ?


![Image](https://github.com/leather-wallet/extension/assets/119523541/433fe678-722c-4bea-9526-f653556ce07e)

**Comment by markmhendrickson** [comment]
Works for me!

**Comment by fbwoolf** [comment]
Going to reassign this to myself bc it is blocked by the colors issue I'm working on atm, and somewhat related to work on Callouts.

**Comment by mica000** [comment]
@fbwoolf forgot to mention this today, but last friday we adjusted the tags so they are also aligned with the color update. This is how the tags are handling the colors now, for **INK**:
<img width="833" alt="Screenshot 2024-02-19 at 20 57 31" src="https://github.com/leather-wallet/extension/assets/119523541/1971b736-47bd-4237-8b61-be039db33bba">

For **RGBY**
<img width="846" alt="Screenshot 2024-02-19 at 20 57 20" src="https://github.com/leather-wallet/extension/assets/119523541/3aa55c84-4434-4ea3-81fd-dd0a7534425f">

**Comment by fbwoolf** [comment]
@mica000 can these have the same `variant` names as the Callouts I made? For Callout we have: `default, error, info, success, and warning`, does that work here too?

**Comment by mica000** [comment]
> @mica000 can these have the same `variant` names as the Callouts I made? For Callout we have: `default, error, info, success, and warning`, does that work here too?

Ah yes! let's do it!
