### ISSUE TITLE
Use animated inline label inputs

### ISSUE THREAD

**Issue by fabric-8** [blockstack/blockstack-app#4810]
![Image](https://github.com/leather-wallet/extension/assets/4112698/99f9eae3-9053-46fa-b7c4-027397922533)

Our current "simple inputs" are label-less. Let's bring back animated inline labels for added affordance/accessibility. There might still be cases where we want to be able to have "label-less" inputs without the animated inline labels, so would be great to have this as an option.

Label and placeholder text will be the same.

[Designs on Figma](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=1319%3A1488&mode=design&t=PWincYIDS45c4Duu-1)
[Slack thread](https://trustmachines.slack.com/archives/C05LRS7G44R/p1705333156769669)

**Comment by kyranjamie** [comment]
I would love to do this one
