### ISSUE TITLE
Add published Storybook link to top of PR

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#4814]
The link to view the deployed Storybook for viewing is hard to find on a new PR, so let's create a link at the top to make it easier for people to find/view it.

<img width="879" alt="Screenshot 2024-01-16 at 1 39 51 PM" src="https://github.com/leather-wallet/mono/assets/6493321/ca4dcdb5-b46f-4f1e-b6f5-7a316a50349a">

**Comment by kyranjamie** [comment]
@fbwoolf see this issue https://github.com/chromaui/chromatic-cli/issues/699

We might need to merge the `build-extension.yml` and `chromatic.yml` jobs so we can set the header once with all info.
