### ISSUE TITLE
Visual issue STX amount /Million in post condition and argument when using signTransactionHex since wallet 6.22.0

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4819]
Since wallet version 6.22.0

_Btw Idk if you guys saw it, but when we're trying to transfer some STX - it shows like 10^6 less like we didn't pass decimals
But in reality we pass decimals properly
After the last update only_
![image](https://github.com/leather-wallet/extension/assets/33360391/383e53c1-5ca8-433a-bdfb-f226de51f9ee)

_and Idk if it is only a problem with signTransactionHex request or with all requests, but seems to be a problem only with signTransactionHex_

This can be reproduced by using the test wallet
1. Visit asigna.io 
2. Sign in with account 1
3. Create a transfer of 1 STX
4. Sign the transaction with account 1
**5. See issue in the confirm screen.** 
6. Sign out with account 1
7. Sign in with account 2 on asigne.io
8. Go to activty in the same multisig wallet
9. Sign transaction
**10. See issue again**

**Comment by 314159265359879** [comment]
![image](https://github.com/leather-wallet/extension/assets/33360391/1483b1d5-f777-4d6c-a2cd-38726f701a49)


Both the post condition and transaction amount are divided by 1 M
![image](https://github.com/leather-wallet/extension/assets/33360391/4d5fb735-6526-414e-b5cb-d0fe6e4aba8e)

It is a visual bug because the actual transaction is send with the proper amount:
https://explorer.hiro.so/txid/0x9b38583f7b8e9c26a007bdc0cbd461557100ba9f482a3097b0abcfe079741330?chain=mainnet
![image](https://github.com/leather-wallet/extension/assets/33360391/eb78d7da-35d0-421b-a4a7-5c66468f3aa9)

**Comment by markmhendrickson** [comment]
I believe this has been fixed
