### ISSUE TITLE
Unable to confirm transaction request on devnet

### ISSUE THREAD

**Issue by Aman-zishan** [blockstack/blockstack-app#4821]
# unable to confirm transaction, gets a fee estimation error in extension console

<img width="1440" alt="Screenshot 2024-01-18 at 11 30 19 AM" src="https://github.com/leather-wallet/extension/assets/55238388/4aa7a8bf-d8e2-4852-880f-058f3d354abd">

- browser - chrome
- network - devnet
- contract call used to work until yesterday noon

**Comment by 314159265359879** [comment]
Hi @Aman-zishan this looks a lot like your extension and dapp are not connecting to the same network. Try signing out on the dapp. Setting your extension to the devnet and selecting the account you want to sign in with. 
Then connect to the dapp again, and try to confirm the transaction again.

**Comment by Aman-zishan** [comment]
Hi @314159265359879 , i followed your steps and i'm getting the same error, i am using micro-stacks in most of my contract calls, so im setting the network directly then and i also checked if it is pointing to the right network. seems like it is, the dapp network switch is working fine as i tried with testnet as selected network option and wallet shows testnet in the confirmation page. Although i did not check if the tx is being confirmed in testnet / mainnet and if this is an issue with only the devnet

**Comment by 314159265359879** [comment]
@Aman-zishan does the wallet still allow you to proceed with a custom fee?

**Comment by Aman-zishan** [comment]
<img width="1440" alt="Screenshot 2024-01-18 at 3 08 16 PM" src="https://github.com/leather-wallet/extension/assets/55238388/1409082e-f80d-4992-a040-4cca0b72c3e7">

@314159265359879 
this is the screen

**Comment by 314159265359879** [comment]
@kyranjamie we expect the fee options to still appear, when fee can't be determined, right? so the user can at least set a custom fee or is that different when operating on devnet?

I guess if none of the devnet API's can be reached it will not matter much because then the wallet will error on "insufficient balance to cover fees" next.

**Comment by Aman-zishan** [comment]
> @kyranjamie we expect the fee options to still appear, when fee can't be determined, right? so the user can at least set a custom fee or is that different when operating on devnet?
> 
> I guess if none of the devnet API's can be reached it will not matter much because then the wallet will error on "insufficient balance to cover fees" next.

@314159265359879  i agree on this, in given scenario a fee field could make matters much easier rather than a dead end, how can i fix this issues i have been stuck at this and cannot proceed with my development

**Comment by 314159265359879** [comment]
I am not sure how to resolve this. 
@Aman-zishan can you work around this issue by using the public Hiro testnet instead?
![image](https://github.com/leather-wallet/extension/assets/33360391/ff385407-a768-464f-94c9-61bb109e70ba)

**Comment by Aman-zishan** [comment]
@314159265359879 testnet is extremely slow for vigorous development flow atleast for now, so unless i have developed the entire flow i dont think testing via testnet is a great idea, that's why devnet development was much easier for such development practices, at this point we particularly depends on devnet

**Comment by obycode** [comment]
I have seen this issue as well. As a workaround, I have been submitting transactions via stacks.js instead of through the wallet, for my testing.

**Comment by ryanwaits** [comment]
> I have seen this issue as well. As a workaround, I have been submitting transactions via stacks.js instead of through the wallet, for my testing.

im starting to get this error when using stacks.js as a workaround
<img width="1046" alt="Screenshot 2024-01-18 at 4 39 53 PM" src="https://github.com/leather-wallet/extension/assets/3207017/a650640d-0a46-4c77-96ae-60447f7f7701">

**Comment by natebuch** [comment]
Experiencing the same issues.  Confirmation window has sBTC devenv selected and unable to change.  Extension is set to devnet.

**Comment by sabbyanandan** [comment]
@markmhendrickson: At your convenience, please have a look at this. Any education would be helpful.

**Comment by obycode** [comment]
> im starting to get this error when using stacks.js as a workaround

In stacks.js, you can hard-code a fee in the options object so that it doesn't rely on the fee estimation endpoint.

**Comment by sabbyanandan** [comment]
@fbwoolf: Thank you for the fix! 

@Aman-zishan: Perhaps you can try out the [extension built off of the PR](https://github.com/leather-wallet/extension/pull/4832#issue-2092211562) and share your findings here or in the PR for validation.

**Comment by Aman-zishan** [comment]
@sabbyanandan the fix works well thanks!, thank you for the fix @fbwoolf , i'll keep an eye here to see when it is going to be merged so that i can switch to production version

**Comment by fbwoolf** [comment]
Merging this into our dev branch today, but we still need to release it to the app stores. Watch for the new release for the fix.
