### ISSUE TITLE
Dollar price of bitcoin fee is sometimes off, on custom it is correct

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4834]
Could this be related to a UTXO selection issue? I see the bitcoin amount and dollar value to match but they are far to high if there are just the minimum number of inputs required. When selecting custom fee, the amount does look normal, does the wallet select different (big) UTXO's now for the payment?.

Original report:

_"so in the first screen you'll see their standard $ priced fee estimation, which is just not correct based on the the mempool or the size of the transaction at all - it's multiples far too high. If you then set a custom mempool fee they seem to then actually calculate the $ value correctly_

_problem is, most people will never set that fee manually, will see that first $70 and just give up
I hope that's clear? I don't think I've necessarily explained myself particularly well"_

![image](https://github.com/leather-wallet/extension/assets/33360391/0b114009-de04-4430-967c-f9ec7166838c)

![image](https://github.com/leather-wallet/extension/assets/33360391/0df0a80a-fade-400a-beb1-42075c50ac58)

**Comment by markmhendrickson** [comment]
I'm closing as stale. Please reopen if this is an ongoing issue.
