### ISSUE TITLE
Broken disabled button styles

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#4840]
When in a disabled state, hover etc interactions with the button should be disabled.

Perhaps introduced in 7d75f4a ?

https://github.com/leather-wallet/extension/assets/1618764/673adbac-f5da-4caa-8fa3-e47e955b59b9

**Comment by kyranjamie** [comment]
@fbwoolf can you take this on?

**Comment by fbwoolf** [comment]
> @fbwoolf can you take this on?

Yep, I think I fixed this on my current branch already working on the items. I will put the PR up today. Learning more abt using these recipes, sorry for bug.
