### ISSUE TITLE
The wallet can't continue when the fee api return an NoEstimateAvailable.

### ISSUE THREAD

**Issue by zhigang1992** [blockstack/blockstack-app#4842]
<img width="554" alt="Screenshot 2024-01-23 at 11 23 50 AM" src="https://github.com/leather-wallet/extension/assets/1057756/68c71dd3-5256-42b4-bf36-5e5718b94b38">

This is a newly deployed contract, and the function was never called before. 
The continue button does not work in this case.
Here is the error from the fee estimate API.
<img width="1798" alt="image" src="https://github.com/leather-wallet/extension/assets/1057756/e3ed2842-9437-4b28-9ee1-bd236db08f25">

After broadcasting the same function with nodejs locally with fixed fee then it would work in the wallet.
<img width="554" alt="image" src="https://github.com/leather-wallet/extension/assets/1057756/901285f4-ff2d-452f-a725-929e915740c4">

Please let me know if there are more info that we can provide.

**Comment by edgarkhanzadian** [comment]
This seems to be already fixed by #4832 PR

**Comment by edgarkhanzadian** [comment]
Related to #4821
