### ISSUE TITLE
Update Stamp API

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4845]
Currently, the wallet checks stamp balances with

````stampchain.io/api/stamps?owner=bc1q5gy8crntfz8hzmq8h4zcgqp2n8r7c6vuxafqd4````

https://stampchain.io/docs has a new version I believe we should update it to:
https://stampchain.io/docs#/default/get_api_v2_balance__address_

````https://stampchain.io/api/v2/balance/bc1q5gy8crntfz8hzmq8h4zcgqp2n8r7c6vuxafqd4````

example the new one returns this recently received asset [A17629508681739106000](https://xchain.io/asset/A17629508681739106000) the old one does not.

**Comment by markmhendrickson** [comment]
I'm classifying as a bug since it sounds like using the old API is resulting in buggy data loading experiences.

**Comment by markmhendrickson** [comment]
@alter-eggo can you tackle this one urgently?
