### ISSUE TITLE
Fix routing for creation of new wallet from action popup

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4848]
It currently goes to the full page view to the wrong route

https://github.com/leather-wallet/extension/assets/28991/0451d2ec-1a9e-4453-a9fd-c2b0eadc9cac

**Comment by pete-watters** [comment]
@markmhendrickson , just to confirm this. 

- As a user
- WHEN I click 'Create new wallet' in the action popout
- THEN the wallet SHOULD create a new wallet 
- AND land on the route `/back-up-secret-key` (below)



![Image](https://github.com/leather-wallet/extension/assets/2938440/b64d6f87-7896-4739-a5cc-6ddd543c5abd)

**Comment by markmhendrickson** [comment]
Yep that's my expectation. cc @mica000 to confirm UX

**Comment by mica000** [comment]
yup!

**Comment by pete-watters** [comment]
@kyranjamie I was going to change this but I just want to double check if there is a reason not to `Create wallet` in popup? 

In `WelcomePage` we have some code that forces the user to go to `Onboarding` if they create wallet in the action popup. 

I can change that but I'd like to make sure it doesn't introduce a regression. 

```
 const startOnboarding = useCallback(async () => {
    if (isPopupMode()) {
      openIndexPageInNewTab(RouteUrls.Onboarding);
      closeWindow();
      return;
    }
    setIsGeneratingWallet(true);
```

**Comment by kyranjamie** [comment]
Yeah, was added intentionally. All it takes it one click to accidentally close the extension, then you have to start again (unless we manage a lot more onboarding state). Further, it's just generally a worse user experience to do it in a tiny mobile-sized viewport, when you could instead use a full page view.

**Comment by pete-watters** [comment]
OK thanks Kyran. @markmhendrickson I won't change this as [per comment above](https://github.com/leather-wallet/extension/issues/4848#issuecomment-1920973990)

**Comment by markmhendrickson** [comment]
We still want to fix the routing though don't we? In that, the user indeed needs the full page view to open, but to the key generation screen, not getting started one.

**Comment by pete-watters** [comment]
In the code we are doing a re-direct before creating anything. 

I can change it but we will first have to create the new wallet in the extension and then do the re-direction. 
```
const startOnboarding = useCallback(async () => {
    if (isPopupMode()) {
      openIndexPageInNewTab(RouteUrls.Onboarding);
      closeWindow();
      return;
    }
    setIsGeneratingWallet(true);
    // #4517 signout other tabs on wallet create
    await keyActions.signOut();
    keyActions.generateWalletKey();
    void analytics.track('generate_new_secret_key');
    if (decodedAuthRequest) {
      navigate(RouteUrls.SetPassword);
    }
    navigate(RouteUrls.BackUpSecretKey);
  }, [keyActions, analytics, decodedAuthRequest, navigate]);
```


I think this should be OK, but maybe @kyranjamie has better insights here. 

To be clear, this is for creation of a new wallet, not recovery of a key.

**Comment by pete-watters** [comment]
@kyranjamie - is it OK if I make this change so that:
- when users click `Create account` in extension mode
- we actually create the wallet for them and bring them [here](chrome-extension://dbbkfepagfalpohacffnpaodaklhamif/index.html#/back-up-secret-key)

You confirmed this was done intentionally [here](https://github.com/leather-wallet/extension/issues/4848#issuecomment-1920973990) but Mark thinks [we should still change it ](https://github.com/leather-wallet/extension/issues/4848#issuecomment-1921602914)

**Comment by kyranjamie** [comment]
Mark and I are discussing complimentary, not contradictory, behaviours in these comments. I was saying that we should force the user to go to full screen mode. Mark is saying, yes do that, but take them directly to the _save secret key_ page not the _welcome_ page.

It is not a discussion about begin able to do onboarding entirely in the action popup.
