### ISSUE TITLE
Fix formatting issue for locked STX

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4851]
The spacing is off generally:

<img width="400" alt="Screenshot 2024-01-12 at 22 35 53" src="https://github.com/leather-wallet/extension/assets/28991/b39b01e5-c7ad-4da8-8e08-a365d8393480">

**Comment by pete-watters** [comment]
Seems similar to https://github.com/leather-wallet/extension/issues/4552
