### ISSUE TITLE
Prevent flicker upon scroll to bottom of accounts list

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4852]
https://github.com/leather-wallet/extension/assets/28991/f6bd2752-667b-40b8-aa24-eace5d2ce92f

**Comment by pete-watters** [comment]
@markmhendrickson I re-tested this and it's no longer causing issues. I fixed it as part of work on https://github.com/leather-io/extension/issues/5310 

PR : https://github.com/leather-io/extension/pull/5289
