### ISSUE TITLE
Fix network picker and home formatting within popup window

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4869]
I encounter some unexpected routing and formatting when selecting the network label from within the popup window:

1. The route changes to home when displaying the network drawer instead of staying on the same route (e.g. transaction signing here)
2. The home formatting is messy in general when I dismiss the network drawer

https://github.com/leather-wallet/extension/assets/28991/76a0f0fd-7bff-4631-aff9-f38c5b68c09e

**Comment by pete-watters** [comment]
I'll check this in #4370

**Comment by pete-watters** [comment]
I [spoke with](https://trustmachines.slack.com/archives/C05LRS7G44R/p1706709234375309) @mica000  about this and we agreed to change this behaviour by removing the ability to change network by clicking this tag. 

The tag is now a visual indicator only and you need to use the menu to change network. I have implemented this in https://github.com/leather-wallet/extension/issues/4370. 

I think this is a good improvement to simplify things and make them less buggy. If we wish to re-add this behaviour I suggest we add it as a new feature in the backlog.

**Comment by mica000** [comment]
@pete-watters One thing Im confused is the header. I thought that as this being part of the containers work, it shouldn’t be in production yet but maybe I'm confused?

**Comment by pete-watters** [comment]
In Marks video you can see that the clickable `network` tag is in production in the old UI. 

The new UI with the new header isn't released yet but I had to build a new network badge to have in that header. 

In the new header you cannot click the network badge anymore to change network

**Comment by pete-watters** [comment]
This is fixed and released
