### ISSUE TITLE
UI differences between Windows and MacOS

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#4882]
Recently I have noticed that Leather looks different on my Windows PC, with the scaling and colors looking a bit off.

MacOS with Brave:
![Screenshot 2024-01-30 at 11 11 36 AM](https://github.com/leather-wallet/extension/assets/122313287/996b866a-8426-458b-990a-ea33823cccb1)
![Screenshot 2024-01-30 at 11 13 34 AM](https://github.com/leather-wallet/extension/assets/122313287/102ec640-56e9-489a-a9f0-0d5befb6fa57)

Windows with Brave:
![image](https://github.com/leather-wallet/extension/assets/122313287/c3884e78-b885-40e6-845e-97663bf71ca4)
![image](https://github.com/leather-wallet/extension/assets/122313287/d4b3812a-2d94-46f0-bebf-cf06b9857b0c)

Another user reported the problem with the collectibles taking up the whole width, Windows with Chrome:
![image](https://github.com/leather-wallet/extension/assets/122313287/38a172af-8909-48ea-b468-ef9188b2bb93)

**Comment by pete-watters** [comment]
Thanks @brandonmarshall-tm 👍  I'll take a look at this soon. It could be we need to add some windows specific styling to keep things consistent

**Comment by kyranjamie** [comment]
Suggest we try and hide the scrollbar on windows too

**Comment by brandonmarshall-tm** [comment]
I suspect that the scrollbar is what's causing the issue. I don't remember it being there, and I think that is making the window a little less wide and causing the issue

**Comment by badonyx** [comment]
Collectibles take the full width with a single column on macos for me. I have scroll bars set to always show: system settings - appearance - show scroll bars - always.

**Comment by pete-watters** [comment]
Thanks @badonyx and @brandonmarshall-tm . UI wise, we have a huge update coming soon to rectify a lot of these issues and polish the product - #4370 . I'll be including assessing and fixing this issue as part of that

**Comment by 314159265359879** [comment]
The modal wide NFT/Ordinal previews seem to be showing up on Chromium based browsers since 6.26.1, I can confirm seeing it on Edge, Brave, Chrome and Brave. (I did not see it with 6.22.0 and 6.23.0, I believe it was introduced after those). Firefox looks unaffected (tested with 6.26.1). Side-by-side comparison below

![image](https://github.com/leather-wallet/extension/assets/33360391/b5026f12-e048-4748-b6d4-e059815bc9a3)

**Comment by brandonmarshall-tm** [comment]
It seems like Brave updated and now I have a similar UI on my Mac.

![Screenshot 2024-02-09 at 8 28 57 AM](https://github.com/leather-wallet/extension/assets/122313287/f3ba8563-9851-43ec-bb55-b11d2b14cd13)

**Comment by pete-watters** [comment]
Thanks for the update guys 👍 I've setup a windows VM so will be ironing out these differences soon

**Comment by pete-watters** [comment]
The issue with collectibles have 1 / 2 entries per row is related to the width of the popup. Trying to fix this now. 

I have improved the layout of this screen and will try and hide the scrollbar on windows/ other platforms which should give the extra width needed. We can also even slightly tweak our smallest breakpoint to account for this if that doesn't work.

Now it kicks in once we go below `370px`. Standard extension size will be `390px` 


https://github.com/leather-wallet/extension/assets/2938440/a0ee385f-6c75-443e-8e22-07e097254201

**Comment by badonyx** [comment]
Why would you hide the scroll bar? It is important for accessibility.

**Comment by kyranjamie** [comment]
> Why would you hide the scroll bar? It is important for accessibility.

Lots of other wallets do this, e.g. Rainbow, Coinbase Wallet. Without it, the UI jumps around when going between views that do/don't scroll.

**Comment by pete-watters** [comment]
@314159265359879 is there any chance you can test the build on [this branch](https://github.com/leather-wallet/extension/pull/4655) on Windows to measure improvements here?

**Comment by brandonjamesmarshall** [comment]
Yes collectibles are showing in 2 columns now!
![leather-1](https://github.com/leather-wallet/extension/assets/12146612/1cb2d912-d6ed-4b79-a66c-2be67a1ea6b6)
![leather-2](https://github.com/leather-wallet/extension/assets/12146612/03821125-6fd6-4d9a-9205-34bc73973593)

**Comment by 314159265359879** [comment]
This looks good, I see it resolved too.

**Comment by pete-watters** [comment]
OK that's great 👍  If you notice any other weird issues let me know.

**Comment by pete-watters** [comment]
This is now resolved and will be released soon
