### ISSUE TITLE
Contract call window bg color changes with window size

### ISSUE THREAD

**Issue by aryzing** [blockstack/blockstack-app#4886]
[2024-01-31 20-37-32.webm](https://github.com/leather-wallet/extension/assets/4924405/f3c67a33-c60d-4683-b510-d273d9dc9b50)

**Comment by pete-watters** [comment]
Thanks @aryzing, this is fixed in #4370 which I hope to get released soon

**Comment by pete-watters** [comment]
This issue was fixed https://github.com/leather-wallet/extension/pull/5183 and will be released soon

**Comment by pete-watters** [comment]
This fix was released
