### ISSUE TITLE
Failed to load resource: the brc20api.bestinstlot.xyz... server responded with a status of 403

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4890]
This 403 error typically means the connection is not allowed even though the server/service is available. Adding this here in case other users run into this in the future. 

We can help users understand this type of issue by adding error handling and info when services can't be reached. Could also be covered with https://github.com/leather-wallet/extension/issues/4787 or Similar to guidance when rate limits are reached https://github.com/leather-wallet/extension/issues/4623

A user noticed this error when balances weren't showing as expected. 

![image](https://github.com/leather-wallet/extension/assets/33360391/0c503b11-c4f9-4301-bee2-c89bae1f9d43)

It turned out the connection was being blocked by an antivirus program (AVG):
![image](https://github.com/leather-wallet/extension/assets/33360391/fe7bc07e-0679-4526-8f31-df271c169d0b)

Workaround: allow this connection in AVG

**Comment by kyranjamie** [comment]
Is there any action to be taken here? There's nothing we can do to fix AVG. FAQ entry?

**Comment by markmhendrickson** [comment]
I'm closing as stale, especially since we're no on a dedicated instance with BIS. We can reopen if it resurfaces.
