### ISSUE TITLE
Design System: Label

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4894]
- [ ] [Label](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=8912-82624&mode=design&t=NgdRMaZJg3Jp3Hmr-4)
![Image](https://github.com/leather-wallet/extension/assets/119523541/d1b93dd2-1fb9-4ca6-86cc-505dbc6c35be)

- [ ] [CopyLabel](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=8912-82424&mode=design&t=NgdRMaZJg3Jp3Hmr-4)
![Image](https://github.com/leather-wallet/extension/assets/119523541/5d95938e-2676-44f7-ae69-1b6b54fdc408)

**Comment by mica000** [comment]
@kyranjamie Also curious on your take around this component.

**Comment by kyranjamie** [comment]
Looks fine to build, but a few thoughts:

- Is _CopyLabel_ used for anything else other than copying things? What should the default state say, if so "Copy"? It says caption right now. Would it change in certain cases or always be the same?

- Re the _Label_ component. Curious where this is used? How is it different than just a textStyle of `label.02`? When should the tick be shown?

**Comment by mica000** [comment]
> Is CopyLabel used for anything else other than copying things? What should the default state say, if so "Copy"? It says caption right now. Would it change in certain cases or always be the same?

@kyranjamie Here is an example of how both being used for the current UI. The idea is the have the address replace "copy" and allow the user to copy from this screen.

![Image](https://github.com/leather-wallet/extension/assets/119523541/d906d020-2fdc-4605-8439-c868f36e5948)

**Comment by fbwoolf** [comment]
I am still unclear here about why these need to be shared components? The checkmark next to a piece of text seems pretty minor. Typically we just add a `CheckmarkIcon` next to the span text. With the radix Select, the checkmark icon is placed automatically for us, this really can't be shared bc it is specific to the radix primitive.

The `CopyLabel` might be if it is interactive, but I'm unclear abt it atm. So, when a user hovers over the address in your example, the text changes to `copy` with the `CopyIcon` beside it?

**Comment by mica000** [comment]
> Typically we just add a CheckmarkIcon next to the span text. With the radix Select, the checkmark icon is placed automatically for us, this really can't be shared bc it is specific to the radix primitive.

Ah ok! this I didnt knew. We added it this component because it was needed for Radix. Then Radix primitives are not going to be shared with the rest of the design system? In this case, would make sense to move the Label to the ElevatedList page in Figma, right?

----
>The CopyLabel might be if it is interactive, but I'm unclear abt it atm. So, when a user hovers over the address in your example, the text changes to copy with the CopyIcon beside it?

Yes, that was the intended behavior for this one. The rational behind was to allow users to copy their address quickly from the accounts modal. However, I'm thinking that since this area will be redesigned in the Wallet UX, pherhaps we can discard this functionality from this step for now. cc @markmhendrickson

**Comment by fbwoolf** [comment]
Looking at Radix, they do have a Label primitive, but it is important to keep in mind that the word `Label` is referring to `an accessible label associated with controls`. I think our use of the term in designs/Figma for just text anywhere is slightly confusing.

https://www.radix-ui.com/primitives/docs/components/label

**Comment by fbwoolf** [comment]
@kyranjamie I don't think this component is nec, is it?
