### ISSUE TITLE
Design System: Layout

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4895]
-[ ] [Flag](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=12916-83502&mode=design&t=NgdRMaZJg3Jp3Hmr-4)

![Image](https://github.com/leather-wallet/extension/assets/119523541/9708e9d5-66ab-4ed3-95ad-05db8984a18a)

-[ ] [Itemlayout](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=12916-93310&mode=design&t=NgdRMaZJg3Jp3Hmr-4)
![Image](https://github.com/leather-wallet/extension/assets/119523541/246626cd-1068-48ac-825d-6e93fcddd2ab)

cc @kyranjamie to add more context on how to build this as a compnent

**Comment by kyranjamie** [comment]
Thanks @mica000. @fbwoolf is working on the `ItemLayout` in her PR right now. The Flag we have already.

Notes on the designs, ItemLayout doesn't have the Circle, that's part of the flag.

**Comment by fbwoolf** [comment]
Can I move this into dev and link to my PR?
