### ISSUE TITLE
Design System: Item (Non interactive)

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4896]
- [ ] [SelectLabel](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=8945-112587&mode=design&t=NgdRMaZJg3Jp3Hmr-4)
![image](https://github.com/leather-wallet/extension/assets/119523541/59f388b5-2933-42d1-8a45-5dd42a66e32c)

- [ ] [ItemButtons](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=8912-67099&mode=design&t=NgdRMaZJg3Jp3Hmr-4)
![image](https://github.com/leather-wallet/extension/assets/119523541/1670eb92-a1b2-4b76-ad9e-859f5f80dd76)

- [ ] [ItemSimple](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=12745-92119&mode=design&t=NgdRMaZJg3Jp3Hmr-4)
![image](https://github.com/leather-wallet/extension/assets/119523541/d5fc132b-0f6d-4aa7-907e-c4cc13382894)

**Comment by mica000** [comment]
@kyranjamie ok to move this one as well now that we have the flag and item layout?

**Comment by fbwoolf** [comment]
I have already implemented this here: https://github.com/leather-wallet/extension/pull/4881
