### ISSUE TITLE
Design System: Address

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4897]
- [ ] [ItemAddress](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=11410-32620&mode=design&t=NgdRMaZJg3Jp3Hmr-4)
![image](https://github.com/leather-wallet/extension/assets/119523541/a669f043-ea34-4876-8c7c-0443e0189f0a)

- [ ] [AddressDisplayer](https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=12916-92662&mode=design&t=NgdRMaZJg3Jp3Hmr-4)
![image](https://github.com/leather-wallet/extension/assets/119523541/d1c7ce74-0d8e-41de-9b70-ed7b0b75caeb)

**Comment by mica000** [comment]
FYI @fabric-8 added the address as a ticket

**Comment by fbwoolf** [comment]
What dev feedback is needed here?

**Comment by kyranjamie** [comment]
Saw some conversation on Figma, but curious why we landed on removed the alternating colour? 

The spacing and the colour are the two visual "hooks" that help you easily refer back to the last place you looked when checking it's correct when depositing to a exchange, or writing down on paper. I thought it's a really clever technique, and that it's something we do better than other wallets. Removing one of them is a backwards step imo.

**Comment by mica000** [comment]
@kyranjamie Yes, we were debating because since the updated radix on the colors, the alternative we would have to rely on would be text-subdued, however this was lacking on contrast, hence result wasn't good. 

Last week I saw that 1password is solving this by applying blue to numbers, and it seems to solve it better. Here is how it could possibly work. Let me know your thoughts

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=11410-32620&mode=design&t=WRVcQ8oVMuk8v73S-4
![image](https://github.com/leather-wallet/extension/assets/119523541/4cc78832-8b25-4ccd-87b0-e5953b2e2199)

**Comment by mica000** [comment]
@fbwoolf this component is now ready in designs. We settled for the alternating color to be `color-subdued`
