### ISSUE TITLE
Connecting on console.xyz sometimes errors

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4902]
I ran some tests but haven't been able to reproduce this. Tried signing in with another account than the active account. Tried signing in with Ledger (doesn't accept payload, [known issue](https://github.com/leather-wallet/extension/issues/2725) unrelated). 

_From Console: We see a fairly common error with Leather whereby they get a signature signing error when joining Console. It's mostly reported with Leather, but I assume it might have to do with Stacks.js because I've also seen it with Xverse. Typically clearing cache and trying again solves the issue._ 

_We'd love to keep supporting Leather login, but would you be able to help us understand how to reduce this error for our users? We're a bit stuck._ 

![image](https://github.com/leather-wallet/extension/assets/33360391/54d52c15-a74d-42b7-a8de-88b0a184bc86)

I saw error 0021 once (instead of 0012 above) after signing in with two accounts then signing out on the dapp and connecting again (active account 1), and tried signing in with account 3... I see this in the console
![image](https://github.com/leather-wallet/extension/assets/33360391/8cf29b99-1810-48f6-b9fb-d208753be1ff)
![image](https://github.com/leather-wallet/extension/assets/33360391/a13e47d3-77ff-4966-9a09-5e120897c64f)

Then singing in again, there is no issue. Connected to account 3. 

I try to reproduce
1. visit app.console.xyz
2. Ctrl+F5
3. Switch Leather extension to account 1
4. Connect Leather on console dapp
5. Select account 1
6. Sign message, sign
7. Go to profile, then settings
8. Then click wallets
9. Connect another leather account
10. Now connect account 2 (active account in leather still set to account 1)
11. See it appear...
12. Close global settings popover
13. Click profile upper right and sign out
14. Connect Leather again
15. Select account 3
16. but I only saw the error once... not sure what caused it

Did some connecting of wallets, 2 is connected, I try to connect account 1 and I see this, but it isn't connected yet...
![image](https://github.com/leather-wallet/extension/assets/33360391/b70e052e-298c-4fbd-86fc-9e22b45c4d7c)

**Comment by markmhendrickson** [comment]
Is this with Ledger or software mode?

**Comment by kyranjamie** [comment]
I spoke with the Console devs earlier. They'll try replacing the Stacks Connect methods with our RPC methods and report back.

**Comment by markmhendrickson** [comment]
Confirmed by Console as fixed with Leather

**Comment by markmhendrickson** [comment]
Reopening since this is apparently not fixed yet after all

**Comment by castig** [comment]
@kyranjamie Hi! This issue doesn't seem to be resolved. Would you be able to look at our code? Is it possible we are implementing something incorrect, or that the bug is on the Stacks side? Unclear. But we get a few of these errors every week. Thanks!

**Comment by kyranjamie** [comment]
Happy to audit implementation. Did you migrate to the RPC [`getAddresses`](https://leather.gitbook.io/developers/bitcoin/connect-users/get-addresses) method?

**Comment by markmhendrickson** [comment]
I'm closing out as stale. Please reopen as needed.
