### ISSUE TITLE
Ledger: user sees empty page while trying to sign in with stacks account in stacks.gamma.io but has only connected bitcoin account to Leather

### ISSUE THREAD

**Issue by edgarkhanzadian** [blockstack/blockstack-app#4921]
On ledger, when user has only connected their bitcoin wallet but tries to sign in with stacks account in stacks.gamma.io, they see this empty page.
Should we present some kind of a message to connect / create stacks account?

<img width="845" alt="emptyPage" src="https://github.com/leather-wallet/extension/assets/22010816/8e02a69b-40d8-41c8-873c-c741e5db44e2">

**Comment by markmhendrickson** [comment]
Related? https://github.com/leather-wallet/extension/issues/4611

**Comment by edgarkhanzadian** [comment]
Yeap! Closing this one
