### ISSUE TITLE
Throttle queries when viewing many accounts for selection

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4926]
To avoid going over 100 RPMs for any given user with many (e.g. over 50) accounts to view and scroll through here:

<img width="404" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/b19575b0-6679-4142-951e-60ad31a93568">

**Comment by markmhendrickson** [comment]
@mica000 Could you indicate a simple solution for how to display placeholders for balances and account label values (i.e. BNS names) in the scenario in which we can't load them for over 1+ more minutes given the user has been rate limited by the API?

I imagine for the account label, we'd simply show "Account 1, 2, etc." and for the balances something like "–" instead of the value?

We can improve our loading state UX in general for this component as part of [our accounts UX redesign project](https://github.com/leather-wallet/extension/milestone/50), so this particular issue is meant to be a short-term solution as we roll out throttling to prevent errors related to lower rate limits from Hiro.

**Comment by mica000** [comment]
@markmhendrickson my initial thought would be to have a ghost state added the to the [InteractiveItem](https://www.chromatic.com/component?appId=65982789c7e2278518f189e7&csfId=item-interactive&buildNumber=232&k=65c46766e6ffd388886f6ae5-1200px-interactive-true&h=10&b=-1). Wdyt?
cc @fbwoolf  

If so, I can add the state to the designs and we just need to add this state to the same component on Storybook. 

Bonus point to being able to use the same behavior in all other places were we use the component

**Comment by kyranjamie** [comment]
@mica000 in this case, the row is still interactive, but only the money values are unknown.

I don't think we should change InteractiveItem, because then we are extending the scope of the base component, for one specific instance. Asked chatgpt for help explaining difference between a component, and an instance of a component.

> A component is like the blueprint for a house—it outlines the structure, design, and functionalities the house will have. An instance of a component is like a house built from that blueprint. There can be many houses built from the same blueprint (component), but each house (instance) is a separate entity, can be customized with different colors or interior designs, and is located in a different place."

Using same analogy, we shouldn't change the blueprint for all houses, just to solve a problem specific to one house.

**Comment by markmhendrickson** [comment]
Would the ghost state apply to just the balances part of the item rather than the item in its entirety? Because we'd want the user to be able to view and select each account item even if the remaining label and balance data hasn't loaded yet.

**Comment by kyranjamie** [comment]
Can we just remove the balances entirely? They consume a huge number of requests and cause 429 issues. What other information could we display to help users identify accounts?

**Comment by fbwoolf** [comment]
I was thinking here @mica000 was meaning to provide a 'loading' state for the data passed into the `InteractiveItem` which would render in the `ItemLayout`, not changing the base component itself ...I think I misunderstood her comment.

**Comment by mica000** [comment]
> @mica000 in this case, the row is still interactive, but only the money values are unknown.
> 
> I don't think we should change InteractiveItem, because then we are extending the scope of the base component, for one specific instance. Asked chatgpt for help explaining difference between a component, and an instance of a component.
> 
> > A component is like the blueprint for a house—it outlines the structure, design, and functionalities the house will have. An instance of a component is like a house built from that blueprint. There can be many houses built from the same blueprint (component), but each house (instance) is a separate entity, can be customized with different colors or interior designs, and is located in a different place."
> 
> Using same analogy, we shouldn't change the blueprint for all houses, just to solve a problem specific to one house.

@kyranjamie What I meant was the opposite. The ghost state would be a state in any InteractiveItem before data is fetched. In doing so we would be able to use in all the other places, like Approval, Activity, Home etc.. Maybe a better term is LAZY LOADING?

<img width="499" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/ac308504-8764-42ec-9340-7791301dc85f">

<img width="1350" alt="Screenshot 2024-02-08 at 20 56 46" src="https://github.com/leather-wallet/extension/assets/119523541/d52158f2-bbb6-4574-8449-49d56386491d">

**Comment by mica000** [comment]
> Can we just remove the balances entirely? They consume a huge number of requests and cause 429 issues. What other information could we display to help users identify accounts?

cc @314159265359879

**Comment by mica000** [comment]
> I was thinking here @mica000 was meaning to provide a 'loading' state for the data passed into the `InteractiveItem` which would render in the `ItemLayout`, not changing the base component itself ...I think I misunderstood her comment.

I wasn't going to this extend in how we would build in the FE. The proposal is mostly on how the component would work visually but that could be a good direction!

**Comment by fbwoolf** [comment]
@mica000 I think the confusion might be when you ref the state of `InteractiveItem` as being something specific to the data laid out as the content in it? The `InteractiveItem` (the blueprint) is just a rectangular button that has the click behavior and handles these states, that is it. It wouldn't know if there is data or not, or care. 

<img width="381" alt="Screenshot 2024-02-08 at 3 43 55 PM" src="https://github.com/leather-wallet/extension/assets/6493321/1da0208c-d330-4e86-8d48-ffe4989cfbeb">

You can see here in the `AccountListItem` (the instance) where it is used, that we currently use an `isLoading` conditional to pass a loading spinner in for the balance as the content to the `titleRight` of the `ItemLayout` component, which lays out the content inside of `ItemInteractive`.

<img width="765" alt="Screenshot 2024-02-08 at 3 53 17 PM" src="https://github.com/leather-wallet/extension/assets/6493321/91bcaa9d-4d6c-4dad-afd6-178be920f65a">

This is `ItemLayout`:
<img width="833" alt="Screenshot 2024-02-08 at 3 45 26 PM" src="https://github.com/leather-wallet/extension/assets/6493321/f587036c-2653-46bd-b2ca-4b9e6cd86971">

I think if we want to share a `Skeleton` component which uses `ItemLayout`, that would be it's own component not a new state of `ItemInteractive`, but imo we are just passing in a loading state to the `ItemLayout` to render when data isn't available yet.

**Comment by markmhendrickson** [comment]
> Can we just remove the balances entirely? 

I'd prefer to avoid removing entirely unless we can't come up with a better solution here since the information is quite important for distinguishing and identifying accounts.

**Comment by mica000** [comment]
> I'd prefer to avoid removing entirely unless we can't come up with a better solution here since the information is quite important for distinguishing and identifying accounts.

Agree. Im not aware of any other element we could use to identify accounts besides the amount, specially since users can't edit the name of their accounts.

**Comment by kyranjamie** [comment]
Very important comment from Fara. `InteractiveItem` doesn't ever know what's in it. This is a crucial concept of how components work. The source of most confusion between developers and designers stems from this mixed understanding. Let us know we if can help explain better what we mean by this, happy to demo examples.

Understood on balance. I know it's important just very resource intensive. Another options is to show the _most recent_ balance? Or just load successfully but very slowly.

**Comment by pete-watters** [comment]
@markmhendrickson just to chime in on this bug. If you test Leather with the login for `Leather Development Wallet` and simply login, you will start hitting `429` errors when viewing the landing page for the first time. 

That wallet only has 3 accounts so I think we have some work to do in general
- account 1 - 17 inscriptions - 3 assets - 1 BNS
- account 2 - 2 assets - 1 BNS
- account 3 - 2 assets 

That's hardly a lot of data but it will still hit the 100 RPM limit on initial page load only

**Comment by markmhendrickson** [comment]
> you will start hitting 429 errors when viewing the landing page for the first time.

How many of these queries are generated by the landing page itself for each of those assets to display in particular?

**Comment by 314159265359879** [comment]
> Can we just remove the balances entirely? They consume a huge number of requests and cause 429 issues. What other information could we display to help users identify accounts?

@mica000 I think users use four factors that help users find the right address when they switch account. 
1. BNS name, Balance, Address and Account number (= orientation/order compared to other accounts). 
2. The more we show the easier it is for users to choose the address they intended, especially when they have many. 

I see the benefit of making this page less heavy on API calls. If we remove fetching balance for every address automatically can we add a button to force it for a specific address instead? Something like a "load balance" button in case a user needs more info to find their address they can use it selectively? but it would have the benefit of limiting the number of calls greatly. 

I don't think we should stop showing BNS names, they are the most useful (most used) to identify accounts. They also change less often (compared to balance) so perhaps they can be shown from memory/persisted and only be reloaded when the user forces a "reload" button?

**Comment by pete-watters** [comment]
> > you will start hitting 429 errors when viewing the landing page for the first time.
> 
> How many of these queries are generated by the landing page itself for each of those assets to display in particular?

I did a quick investigation of this but it's hard to tell without diving in. For the leather dev wallet we seem to make a lot more queries than my standard wallet. I can share a video of it internally in case it helps. We seem to call `balances` quite often and for more accounts than we have.

I can help investigate this once I clear my plate as it's important to do what we can client side if we can't avoid the api limits. 

An idea I have is for Leather to use a graphQl proxy as an interface to the hiro API but that would require a lot of work and setup of our own graphQl server etc. and even then I'm not sure its a good idea. 

We can first assess the requests we are making and how often we do it and try and be more efficient

**Comment by mica000** [comment]
Proposed designs 
![image](https://github.com/leather-wallet/extension/assets/119523541/dfa6f03e-7d76-42f2-8f47-56855fcca399)

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=8912-67205&mode=dev

**⚠️ To keep in mind that:** 
We store "loading" and "refreshing" inside the states of ItemIteractive ONLY in figma. On the Front End this state is a independent component which property is applied to the Label

**In relation to the gradient animation:** 
Name of the component: Refreshing data (?);
Where it takes place: Any existing piece of data that;

**Question:** 
- Does anyone know a library we could use that animates the gradient over the text? 
- Will it get stored on Storybook?
- Dark/lightmode: for the color to work on both themes, do we need to create a gradient use case?

**Comment by fbwoolf** [comment]
I think we should only keep the 'interactive' states of the item in this component in Figma. We prob don't want to leave data states in the Figma component.

**Comment by mica000** [comment]
> I think we should only keep the 'interactive' states of the item in this component in Figma. We prob don't want to leave data states in the Figma component.

If we were to remove the data, it would break ~80% of ApprovalUx so I Would rather not because this is super important for us when designing. This is because we cant rely on FlagLayout or ItemLayout in Figma hence we will need to have a shared team understanding that this component doesn't map 1:1 to Storybook. 

Maybe it's smt we can fix with a different naming, by giving a different name in Figma that is different than IntemInteractive? How do we call components that are built using the FlagLayout?

**Comment by fbwoolf** [comment]
We can have a call to talk thru the difference in how you are using them in Figma, but we should have design system `primitive` components that we build both designs and the UI from, like @kyranjamie pointed out, blueprints vs instances. Like here, as a ref, the `Pressable` component doesn't care how it is used: https://docs.nativebase.io/pressable ...there only exists an example of how it COULD be used.

You could create instances of the `ItemInteractive` to use specifically in the Figma designs and call them what is best for that instance, like `AccountListItem` which would use the primitive component `ItemInteractive`. You could use `ItemLayout` like we do in code to layout the content in that instance. In doing so, you would have to handle the data states of the content for that specific use case ...which then might be able to be reused itself in other places.

So, to answer your question, when we use the `Flag` layout component it is named specific to the use case, like `AccountListItem`. If you need a reusable component in the designs that is built from our design system components, maybe you could create something like `ItemInteractiveWithFlagContent` which is reused separately in your designs?

**Comment by mica000** [comment]
> We can have a call to talk thru the difference in how you are using them in Figma, but we should have design system `primitive` components that we build both designs and the UI from, like @kyranjamie pointed out, blueprints vs instances. Like here, as a ref, the `Pressable` component doesn't care how it is used: https://docs.nativebase.io/pressable ...there only exists an example of how it COULD be used.
> 
> 
> 
> You could create instances of the `ItemInteractive` to use specifically in the Figma designs and call them what is best for that instance, like `AccountListItem` which would use the primitive component `ItemInteractive`. You could use `ItemLayout` like we do in code to layout the content in that instance. In doing so, you would have to handle the data states of the content for that specific use case ...which then might be able to be reused itself in other places.
> 
> 
> 
> So, to answer your question, when we use the `Flag` layout component it is named specific to the use case, like `AccountListItem`. If you need a reusable component in the designs that is built from our design system components, maybe you could create something like `ItemInteractiveWithFlagContent` which is reused separately in your designs?

Yep, let's schedule a call tomorrow so I can show how we are handling in Figma.

**Comment by kyranjamie** [comment]
We keep going back and forward on this, would love to hash it out on a call today 🙏🏼. Writing these notes as a reference for when we speak.

> let's schedule a call tomorrow so I can show how we are handling in Figma

**Our design system should be tool agnostic**. As developers, we don't mind whether you use Figma, Photoshop, Sketch, MS paint. For us, it shouldn't be important how the tool works, so I don't think it's helpful to go into much detail on it (plus I think developers understand how it works already).

What's important is that the design system doesn't expose implementation details of the tool in which it was built. That's where a lot of the confusion stems from. E.g. originally `ItemInteractive` was presented as one component with content and styles mixed together because ....that's how it's built in Figma.

Figma components can be created in whatever way works for the designers. How the components are _built_ in Figma, and how they're _displayed_ in Figma are two different things.

...we're getting there. @mica000 it's a super helpful change you've made in `ItemInteractive`, making it absolutely clear the content doesn't belong inside the component. Breaking it down to just the core styles that can be reused anywhere.

![image](https://github.com/leather-wallet/extension/assets/1618764/04682962-641d-41df-bf94-ea73609f8207)

Content is just the example of a component being used, an instance of a component. Presenting these concepts separately would improve our design system I think:
  1. Component blueprint with no content
  2. Examples of a component instance with content

**Comment by mica000** [comment]
### **InteractiveItem**

Cool! Updated the naming to reflect the suggestions above. This is how it looks in Figma now:
<img width="1216" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/b147a2e9-f48a-4e1e-bd37-b87092cdb5bb">

https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=8912-67205&mode=dev

----

###  "Refreshing data" and (maybe) "Ghost" states - How would we like to proceed?

Here is the proposal:

**State 1 - Initial data:** 
We could show a ghost skeleton with a pulsating animation until the initial data loads; 
(This might not be necessary but curious to understand wether is needed or not);

**State 2 - Refreshing data:** 
The idea would be to have a gradient animation pulsating over the existing balance; 

<img width="1319" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/06bfbb32-6feb-4cc3-b5f1-01fd1ed4ab0c">



### **Few questions:**
- How do we call them?
- Will both "states" exist for any piece of data?
- Will it get added in Storybook? 
- Are there existing libraries recommended to use that animates the gradient over the text?
- Dark/lightmode: for the color to work on both themes, do we need to create a gradient use case or this can be solved using the animation?

**Comment by kyranjamie** [comment]
This organisation will help developers a lot Michelly, thanks.

- `RefetchingTextAnimation` might work as a name?
- Not exactly sure how we'll build the loading animation. Something along the lines of https://codepen.io/propagandjw/pen/WNVPRK
- Demos and examples of how this is used in a generic way would be a great addition to storybook if we reuse this pattern elsewhere
- Imagine we'll have to use a different underlaying background animation for the text mask in lightmode vs dark mode

**Comment by mica000** [comment]
What are the next steps here? Are we are aligned on the design  and what needs to be built? And if so, should this be moved to development backlog?

Cc @markmhendrickson @kyranjamie

**Comment by kyranjamie** [comment]
I'd say in order of

1. Making the generic loading components separately
2. Applying these to the account selection list

**Comment by mica000** [comment]
> I'd say in order of
> 
> 1. Making the generic loading components separately
> 2. Applying these to the account selection list

Coolio. Can we can move to dev backlog then?

**Comment by kyranjamie** [comment]
Also to look into query cancellation https://tanstack.com/query/v3/docs/framework/react/guides/query-cancellation

**Comment by alter-eggo** [comment]
some links from quick research
https://stackoverflow.com/questions/76030996/how-to-use-debounce-with-usequery-in-react-query
https://github.com/TanStack/query/issues/293
