### ISSUE TITLE
Unable to send large quantity (500M) of SIP10 token

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#4930]
We had a user report that they were unable to send a large quantity (500M) of a SIP10 token called $BITTY.

They wanted to send 500,000,000 but our wallet only allowed him to enter up to 50,000,000.

Do we have an artificial limit in place on our end that prevents this?

Report: https://twitter.com/mindful_service/status/1755349154241392984

**Comment by kyranjamie** [comment]
@fbwoolf @alter-eggo did we set a max length when working on the animated amount input?

**Comment by alter-eggo** [comment]
@kyranjamie 
```
const maxLengthDefault = STX_DECIMALS + 2; // + 1 for decimal char
const maxLength = decimals === 0 ? maxLengthDefault : decimals + 2;
```

**Comment by brandonmarshall-tm** [comment]
Got another inquiry about this yesterday. Would this be a quick fix?
