### ISSUE TITLE
Enable visual regression testing with Storybook

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4937]

**Comment by pete-watters** [comment]
Also to include this task: https://github.com/leather-wallet/mono/issues/21#issue-2007891929 

This will be a great addition, that should be [fairly straightforward to add when we have Storybook](https://storybook.js.org/docs/react/writing-tests/visual-testing)

it'll make visual bugs like this a thing of the past
![285174159-49abf75d-841f-49b7-a24b-b812a5c3d6d8](https://github.com/leather-wallet/extension/assets/2938440/9aebc3c7-5877-4c11-94fa-b486e4fcee63)

**Comment by kyranjamie** [comment]
Closed in https://github.com/leather-wallet/extension/pull/5103
