### ISSUE TITLE
Using ordinalsbot.com integration to send BRC-20 looks stalled at "paying for transfer inscription"

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4939]
I just created some transfer inscriptions. The first two were confirmed 2 hours ago (10+ bitcoin confirmations ago). One of which has already been transferred to another wallet. Yet they still remain displayed with the status "paying for transfer inscription". 
![image](https://github.com/leather-wallet/extension/assets/33360391/42ff5129-efec-469f-a321-033a08a53027)

And displayed in the collectables area:
![image](https://github.com/leather-wallet/extension/assets/33360391/696ff538-bb29-4824-a8d6-032f4d935584)

I see this in the console:
![image](https://github.com/leather-wallet/extension/assets/33360391/ee179219-86d7-4429-a596-c9cd21e2d21b)

Is this related to changes on the ordinalsbot side? 
Does the new package help to fix it? https://github.com/leather-wallet/extension/issues/4854

**Comment by markmhendrickson** [comment]
@alter-eggo can you confirm if this is still a bug?

**Comment by alter-eggo** [comment]
we can close this exact issue, but problem with orders still exists

**Comment by markmhendrickson** [comment]
Maybe we should indeed migrate to the SDK per #4854 for resolving this particular issue?

**Comment by alter-eggo** [comment]
problem here is that we use wrong id for checking orders. migration to sdk itself won't fix it.
fixed here https://github.com/leather-wallet/extension/pull/5088
