### ISSUE TITLE
BRC-20 balance from recent incoming transfers not displayed in the wallet under assets

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4940]
This was received a couple hours ago
https://ordinals.hiro.so/inscription/87d7cae137476635ef0c936533c9dd837b5bb6845281b463aacdb8d5d57ddd62i0

Yet balance is not displayed in the wallet (Dev wallet acc 4), no BRC-20 balance is displayed. This was first reported a days ago. And users have reported that there is no change after days.
![image](https://github.com/leather-wallet/extension/assets/33360391/9895bf78-e0ad-4f29-8c8b-c96ece030f57)
(no connection issues displayed in the console)

The inscription is valid and the balance is displayed on bestinslot.xyz and ordinals.hiro.so for this address
bc1pxrspfqdunl9kj6uuttfht6wgfl7e037027mgqt9wesl6j8pgr3asqp6qvk

[![image](https://github.com/leather-wallet/extension/assets/33360391/6eceb82b-28ce-4e42-ab98-593f3d7b4824)](https://bestinslot.xyz/bc1pxrspfqdunl9kj6uuttfht6wgfl7e037027mgqt9wesl6j8pgr3asqp6qvk#type=brc20)

[![image](https://github.com/leather-wallet/extension/assets/33360391/1988fbe1-17a7-47b5-a4e9-ad02f579ab73)
](https://ordinals.hiro.so/address/bc1pxrspfqdunl9kj6uuttfht6wgfl7e037027mgqt9wesl6j8pgr3asqp6qvk)

The workaround is to use a third party service to inscribe a new transfer inscription to transfer the funds or interact with a marketplace to make the tokens tradable. They would be displayed as available on those typically.

**Comment by alter-eggo** [comment]
closed as fixed here https://github.com/leather-wallet/extension/issues/4970
