### ISSUE TITLE
Error: transaction size must be defined" when trying to send BRC-20 tokens (send flow) or an UTXO with multi inscriptions

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4941]
To reproduce use wallet with BRC-20 wallet displayed under assets and no ~500 sat balance and take these steps:
1. Click send
2. Click BRC20 token
3. Input amount of tokens to send, i.e. 4
4. Click continue
5. See error
![image](https://github.com/leather-wallet/extension/assets/33360391/21b60c84-694d-4c99-b3b1-5791a1728214)

![image](https://github.com/leather-wallet/extension/assets/33360391/eefe3f67-b9a6-401f-aa1f-be5d0f78b290)

TODO: Test if this only occurs when the BTC balance has a dust amount of BTC or also when the BTC balance is 0 (use dev wallet account 3 (small BTC balance) and 4 (no btc balance). Test blocked by #https://github.com/leather-wallet/extension/issues/4940 because BRC20 balance isn't displayed. 

If the dust amount or low amount of BTC is causing this error. We should handle this better, show low balance error so the user can fix that. This error doesn't help the user understand why this is happening.

**Comment by 314159265359879** [comment]
This issue is more general. 

Reproduction steps 2 (BTC balance amount doesn't matter)
1. dev wallet account 2
2. Hover over inscription ...9900 to send
3. input a valid bitcoin address
4. click continue
5. See error
![image](https://github.com/leather-wallet/extension/assets/33360391/cdd03509-68cd-4331-982c-cea14ae2bf4f)

By the way this is not a normal inscription we are selecting it is paired with another inscription in the same UTXO.

**Comment by markmhendrickson** [comment]
@kyranjamie any idea what's up here?

**Comment by kyranjamie** [comment]
I believe this is an unhandled error where a user that has no spendable UTXOs attempts to make a transaction.

**Comment by markmhendrickson** [comment]
Is that because the remaining UTXOs in the user's balance are protected?

**Comment by kyranjamie** [comment]
That, or they're just uneconomical.

**Comment by 314159265359879** [comment]
When I [reproduced it](https://github.com/leather-wallet/extension/issues/4941#issuecomment-1947994596) there is enough BTC (well beyond dust/uneconomical amount) in account 2, the unhandled issue though, I think it is related to the UTXO holding multiple inscriptions in that case. That is different from the very first case reported here though.

**Comment by 314159265359879** [comment]
Here is another case of this same error popping up. I am increasing the severity of this bug to P1 based on this. 

Here is a transaction
https://mempool.space/tx/029b6de94608d27156920b00957ca87a48e0c2be4260b05b4385648eaf63854e
the wallet would normally have no issue with, it would allow increasing the fee because the inputs/outputs allow for a three-four fold increase. Yet when the user clicks "increase fee" in the activities tab in Leather they hit this error instead:
![image](https://github.com/leather-wallet/extension/assets/33360391/309baded-1aec-456c-a7fd-a6be567384ba)

![image](https://github.com/leather-wallet/extension/assets/33360391/a379a0d6-fb9d-4577-8a3b-7d19fbc6e4de)

**Comment by 314159265359879** [comment]
> This issue is more general.
> 
> Reproduction steps 2 (BTC balance amount doesn't matter)
> 
> 1. dev wallet account 2
> 2. Hover over inscription ...9900 to send
> 3. input a valid bitcoin address
> 4. click continue
> 5. See error
>    ![image](https://private-user-images.githubusercontent.com/33360391/305359307-cdd03509-68cd-4331-982c-cea14ae2bf4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjM1NDgsIm5iZiI6MTcwOTc2MzI0OCwicGF0aCI6Ii8zMzM2MDM5MS8zMDUzNTkzMDctY2RkMDM1MDktNjhjZC00MzMxLTk4MmMtY2VhMTRhZTJiZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDIyMTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Mzk5N2FjYWI3Y2UyNWUzZjhiNGY4NjMyZWJiODgwNzkwMGM1NmU0YjZhYmVmMzVkOGM1ODliMDlmYzY2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cYwJOQXH2ZNvUslKBHXzLKPhh48-v3kFbxsFLyZ15tU)
> 
> By the way this is not a normal inscription we are selecting it is paired with another inscription in the same UTXO.

Retested with PR5011, looks LGTM
