### ISSUE TITLE
Dark mode issue in structured data signature popup

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-app#4944]
Dark mode in Leather doesn't handle the signed structured data popup:

<img width="426" alt="image" src="https://github.com/leather-wallet/extension/assets/1109058/34e42e84-aae7-41ef-b497-8ff9a28446a3">

**Comment by pete-watters** [comment]
I've fixed this and it will be released along with https://github.com/leather-wallet/extension/pull/4655/
