### ISSUE TITLE
Unable to sign structured data on Ledger

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-app#4945]
I'm working on an app that makes structured data signature requests, and I was testing out using a Ledger to make the signature. When I click "sign", nothing happens, and I get an error message about "cannot serialize a bigint". The structured data does have `uint` fields in the `message`.

I've also tested this with other messages (like a `tuple` without `uint`, and a plain `string-ascii` message) and I get the same error. So it must not be related to the `uint` field.

<img width="623" alt="image" src="https://github.com/leather-wallet/extension/assets/1109058/91c89124-8b7a-4d60-b3a2-b1d07f8a26ff">

<img width="399" alt="image" src="https://github.com/leather-wallet/extension/assets/1109058/a206224b-363d-4317-9664-165862f9730b">

For my use case (related to Nakamoto signers) it's important that we can generate these signatures using a hardware wallet.

**Comment by hstove** [comment]
It looks like the error is because comes from [`use-ledger-navigate`](https://github.com/leather-wallet/extension/blob/dev/src/app/features/ledger/hooks/use-ledger-navigate.ts#L55) because `domain` will always have a BigInt (`chainId`) and the router fails to serialize it.

**Comment by 314159265359879** [comment]
@kyranjamie  Would this be resolved by the fix we have for https://github.com/leather-wallet/extension/issues/2725

**Comment by kyranjamie** [comment]
This is a known problem. I understand it's been fixed but needs to be audited and released to appear on LL.

**Comment by hstove** [comment]
So maybe it'll be a problem once it reaches Ledger, but my read of the issue after looking at the code is that the error stems from the serialization of the route change in `react-router`

**Comment by markmhendrickson** [comment]
@kyranjamie thoughts on this being perhaps a separate issue, as @hstove indicates?

**Comment by kyranjamie** [comment]
My apologies for passing this off so quickly as the Ledger app error.

Indeed, we run into serialisation errors when passing it through the routes. Further, I noticed `stx_signMessage` was never implemented for Ledger.

I'll push a PR shortly fixing some issues, so you'll be able to successfully get through to another error page 🙃
