### ISSUE TITLE
Remove display of unsuppported tokens from token picker for buy flow

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4949]
It appears that our reuse of the token picker here has allowed BRC-20 tokens to display in the buy flow inadvertently when only BTC and STX should appear:

![Image](https://github.com/leather-wallet/extension/assets/28991/67593799-183a-4c0b-9d6d-e16295c9d0f2)

**Comment by pete-watters** [comment]
Closing this to fix in https://github.com/leather-wallet/extension/issues/5071 as it seems related to incorrect usage of shared BRC-20 components.

**Comment by pete-watters** [comment]
I included a fix for this in https://github.com/leather-wallet/extension/pull/4655, I can't link anymore issues to that PR as the max is 10.
