### ISSUE TITLE
Remove confirmation drawer

### ISSUE THREAD

**Issue by fabric-8** [blockstack/blockstack-app#4953]
Instead of displaying the confirmation drawer upon confirming the transaction, let's bring the user back to their transaction history and display a toast to confirm the tx broadcast.

Can we ensure the transaction being present in the history when the user gets to that screen?

https://github.com/leather-wallet/extension/assets/4112698/a979d311-fd79-4f9b-978a-e6ee99795037

[Mockup on figma](https://www.figma.com/file/FlmF7ropcijOb7iVSDqNn0/%F0%9F%9F%A7-Web-App-Explorations-2024-H1?type=design&node-id=2313%3A113613&mode=design&t=ZUtICC6IrfFhijdu-1)

**Comment by markmhendrickson** [comment]
I believe we can close this since we do want to keep the confirmation screen after all?
