### ISSUE TITLE
Stacks: Hide walls of assets/arguments/etc in wallet

### ISSUE THREAD

**Issue by tycho1212** [blockstack/blockstack-app#4954]
99% of users aren't interested in this kind of stuff, or rather scared by it

A default view with this stuff hidden and an advanced view where this information shows would be great

<img width="1126" alt="Screenshot 2024-01-28 at 15 03 22" src="https://github.com/leather-wallet/extension/assets/32067484/a1b691ce-1ab3-4780-a59e-455148ea6254">

**Comment by markmhendrickson** [comment]
I think you already filed this one? https://github.com/leather-wallet/extension/issues/2764

We've already redesigned this screen in general, with these contract details going into an advanced view. The redesign should be live this quarter.
