### ISSUE TITLE
UI bug in activity feed

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack-app#4955]
![image](https://github.com/leather-wallet/extension/assets/6131188/0942db67-b304-47b4-a2f7-a99b5dbbd34e)

Chome: Version 121.0.6167.184 (Official Build) (64-bit)

**Comment by cuevasm** [comment]
And getting strange overflow now on the sign in screen: 

![](https://github.com/leather-wallet/extension/assets/6131188/e2a53aaf-41c7-4556-ab93-8bb4a3144b26)

**Comment by markmhendrickson** [comment]
Thanks! We have a fix in progress for the unlock screen overflow already, and we'll get the activity one cleaned up as well. Note that we're currently undertaking a large redesign process across the app so a lot of these details are getting 🧹'ed.

**Comment by pete-watters** [comment]
This issue is now fixed. Issues related to session lock are fixed in https://github.com/leather-io/extension/issues/5248

![Screenshot 2024-08-19 at 06 07 13](https://github.com/user-attachments/assets/3a55fe20-6571-48de-8a22-4fe137b4649c)
