### ISSUE TITLE
Refactor `TextInputField` to use new `Input` component

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4959]
![Image](https://github.com/leather-wallet/extension/assets/28991/ec1e9e96-f000-4529-88a3-70236e302c24)

[See Slack thread](https://trustmachines.slack.com/archives/C05LRS7G44R/p1708011840189869)

**Comment by kyranjamie** [comment]
This uses an older input field, which I think someone updated to kinda look like the new one, but isn't really. Renaming this issue to be a refactor task to use our new component.
