### ISSUE TITLE
Find a better QR generator library

### ISSUE THREAD

**Issue by edgarkhanzadian** [blockstack/blockstack-app#4967]
We currently utilize a library called @vkontakte/vk-qr but it is not well maintained. We should find a better alternative (maybe smth like https://github.com/rosskhanas/react-qr-code)

**Comment by pete-watters** [comment]
I had to change the size of the QR code so I just swapped it for the new library while I was doing it.

**Comment by pete-watters** [comment]
This work was included in https://github.com/leather-wallet/extension/pull/5176/
