### ISSUE TITLE
Fix collectible hover button

### ISSUE THREAD

**Issue by fabric-8** [blockstack/blockstack-app#4971]
When hovering the callout button that appears on top of the collectible preview, the button becomes transparent. Instead we'd like the button to stay opaque while applying the hover effect as an overlay.

![Image](https://github.com/leather-wallet/extension/assets/4112698/73a0e89b-d9ba-40ea-871b-5aa6bb2f802e)

Solution suggestion: At this point this is a one-off case for collectibles. Hence we suggest to solve this locally vs. systematically. For example, we could simply wrap the button in a container with bg background-primary, with the button staying transparent and using the transparent hover effect via the corresponding component background hover token (as is applied now).

_PS: New icon is assuming new icon library is in place_

**Comment by pete-watters** [comment]
I made this change as requested @fabric-8 . Let me know if it looks OK 

https://github.com/leather-io/extension/assets/2938440/e4f6da19-eccc-4584-b8bf-3dad0c6db171

**Comment by fabric-8** [comment]
@pete-watters Thanks for improving this! Minor thing I am wondering about: It's still using the rounded shape / prior size, any chance we can [align this with the design system](https://www.figma.com/design/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?node-id=6710-40273&t=g9ZTB9Y1DsbkDcX4-1) so it uses a 32x32 rectangular shape with border-radius?

**Comment by pete-watters** [comment]
> @pete-watters Thanks for improving this! Minor thing I am wondering about: It's still using the rounded shape / prior size, any chance we can [align this with the design system](https://www.figma.com/design/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?node-id=6710-40273&t=g9ZTB9Y1DsbkDcX4-1) so it uses a 32x32 rectangular shape with border-radius?

Sure. I hadn’t noticed that, I will standardise it with the design system ASAP

**Comment by pete-watters** [comment]
Does this look OK now? I don't have a good eye for these small changes

New:
![Screenshot 2024-07-02 at 07 29 20](https://github.com/leather-io/extension/assets/2938440/ca73fdd6-7eba-4b5a-8b4d-bb85d876117c)

Old:
![Screenshot 2024-07-02 at 07 29 33](https://github.com/leather-io/extension/assets/2938440/8568c828-7fbe-4777-a8f5-22c1312fd98a)

https://github.com/leather-io/extension/pull/5592

**Comment by markmhendrickson** [comment]
@pete-watters are you referring to this design guidance in the description of this issue? It looks quite different than your latest change, in terms of icon asset and styles

<img width="376" alt="image" src="https://github.com/leather-io/extension/assets/28991/62716331-ca5f-4758-9249-a5e08bb17102">

**Comment by markmhendrickson** [comment]
> I don't have a good eye for these small changes

Let's pull the details directly from Figma so they don't have to be eye-balled?

**Comment by fabric-8** [comment]
@pete-watters All that needs to be done here:

- Change button border-radius to `xs` (2px)
- Change button-size: 30px → 32px
- use external-link icon (From what I can tell we're currently rotating the arrow which won't be necessary anymore)

**Comment by pete-watters** [comment]
Thanks @markmhendrickson & @fabric-8 . I was working on this yesterday evening but forgot to update the ticket. 

My mistake here was I focused on fixing the hover effect and didn't actually realise I had to replace the icon also. (@fbwoolf helped me spot that)

I have it working as you say above Fab but when I [check Figma](https://www.figma.com/design/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?node-id=6710-40273&t=g9ZTB9Y1DsbkDcX4-1) this button has a padding of `8px` around the icon so the hover isn't working perfectly there. 

No button padding: 

![Screenshot 2024-07-02 at 17 28 38](https://github.com/leather-io/extension/assets/2938440/cd92846d-bb57-4721-a603-1c18af313b6d)

Padding:

![Screenshot 2024-07-02 at 17 29 05 (1)](https://github.com/leather-io/extension/assets/2938440/af561813-9a70-47a7-af16-688f4b303fdf)

I take it that this padding is necessary so it looks right? When I add padding it is effecting the hover state and there is a small gap around the edges. I can continue to work on that

**Comment by fabric-8** [comment]
Yes with padding looks good and sorry for the hassle 🙈

**Comment by pete-watters** [comment]
> Yes with padding looks good and sorry for the hassle 🙈

No need to be sorry, it's my fault, I should have checked the screenshot in more detail before. 

I'll open a PR for review with the padding as it doesn't look 100% right. It's hard to see in the screenshot but there is a slight visible gap in the hover overlay due to the padding

**Comment by pete-watters** [comment]
@fbwoolf said she can add the final touches here and get the hover effect working in the `IconButton` component itself https://github.com/leather-io/extension/pull/5600#issuecomment-2207729165 

Thanks Fara!

**Comment by fbwoolf** [comment]
@pete-watters the fix ended up being real simple here based on my changes in this commit:
https://github.com/leather-io/extension/pull/5600/commits/ea297d9ac4a4f70af6cfbe457602ec993a7f07a4

All I had to do was add a `bg="ink.background-primary"` to the div wrapping the entire `IconButton` so it always had a background underneath it.

![Screenshot 2024-07-04 at 8 42 36 AM](https://github.com/leather-io/extension/assets/6493321/b14924d4-11ce-4fd2-b4d0-60cc8257adcf)

![Screenshot 2024-07-04 at 8 42 41 AM](https://github.com/leather-io/extension/assets/6493321/71781d03-b574-4b6b-975c-7c3e48e834ae)

**Comment by pete-watters** [comment]
> @pete-watters the fix ended up being real simple here based on my changes in this commit: [ea297d9](https://github.com/leather-io/extension/commit/ea297d9ac4a4f70af6cfbe457602ec993a7f07a4)
> 
> All I had to do was add a `bg="ink.background-primary"` to the div wrapping the entire `IconButton` so it always had a background underneath it.
> 
> ![Screenshot 2024-07-04 at 8 42 36 AM](https://private-user-images.githubusercontent.com/6493321/345852725-b14924d4-11ce-4fd2-b4d0-60cc8257adcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDM4MTAsIm5iZiI6MTcyMDEwMzUxMCwicGF0aCI6Ii82NDkzMzIxLzM0NTg1MjcyNS1iMTQ5MjRkNC0xMWNlLTRmZDItYjRkMC02MGNjODI1N2FkY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMTQzMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2E3ZjZlOTUwOWQ5NTgyZWM2NTY3YWM0MjRhOWM1N2QzOTY5OWUxMDEzMzIzYjhlY2JkZDFkMzc4MTZiNGZhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j9zAJZKTLkxK-EvwxXHoD29JHLF1s6bV9LwpFB4-VOc)
> 
> ![Screenshot 2024-07-04 at 8 42 41 AM](https://private-user-images.githubusercontent.com/6493321/345852829-71781d03-b574-4b6b-975c-7c3e48e834ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDM4MTAsIm5iZiI6MTcyMDEwMzUxMCwicGF0aCI6Ii82NDkzMzIxLzM0NTg1MjgyOS03MTc4MWQwMy1iNTc0LTRiNmItOTc1Yy03YzNlNDhlODM0YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMTQzMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDVkNzMyNjE3ZWZkNzVkMDU0Y2U2YmI3NzNkZWNkM2I0ZjdlYWYyZjk3MDA3NWM1ZDhkYTc5MjJhY2FiMjFiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y35H1b4AVB6DE5vNdgrsNBKm5wG6qwYfnL7pNnjftZ4)

Thanks @fbwoolf 👏 I tested it and it's looking great. 

I'm not sure how I didn't figure this out but glad to be part of a great team
