### ISSUE TITLE
Fix hover glitch for copy option in PSBT approval modal

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4972]
https://github.com/leather-wallet/extension/assets/28991/590d386b-9e43-4904-8443-2270634c7662

**Comment by pete-watters** [comment]
I'll fix this in https://github.com/leather-io/extension/pull/5671

**Comment by pete-watters** [comment]
I just fixed it in https://github.com/leather-io/extension/pull/5724 as https://github.com/leather-io/extension/pull/5671 needs more testing
