### ISSUE TITLE
Ledger and sigle authentication: Data invalid

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-app#4978]
When signing in to app.sigle.io using a ledger device, I see the following error (Ledger connected successfully to the Stacks on the popup before this error)

```
Data invalid
Your Ledger device has rejected the payload stating it is invalid
```
![Screenshot_20240226_095325](https://github.com/leather-wallet/extension/assets/1449049/9c780334-6d86-478a-9496-52599e9538b9)

Leather extension version: v6.27.2
Ledger stacks app version: v0.23.3
Ledger OS version: v2.2.2

**Comment by markmhendrickson** [comment]
I believe this is the same as https://github.com/leather-wallet/extension/issues/2725, which has been fixed awaits release.
