### ISSUE TITLE
Increase accounts access from 5 to 10 for Ledger

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack-app#4983]
Very strange issue. I have one wallet setup without a Ledger, on another computer I have one setup with a Ledger. In one interface I'm given the option to create another account as expected: https://leather.gitbook.io/guides/accounts/how-do-additional-accounts-work-in-leather

In the Ledger one, this area is blank (no create new account button). I've tried connecting/disconnecting, etc. Can't do anything to give me the option to setup another account. In both instances, I am running the latest Windows, latest Chrome, latest version of the extension.

![unnamed (3)](https://github.com/leather-wallet/extension/assets/6131188/e8a452ec-18c2-431e-bf99-46efd8aa936b)

**Comment by markmhendrickson** [comment]
This is due to https://github.com/leather-wallet/extension/issues/2502

@kyranjamie would it be much work to hardcode 10 rather than just 5, until we make this extensible as part of our upcoming accounts UX redesign work?

**Comment by kyranjamie** [comment]
Sure. Trivial change.

**Comment by kyranjamie** [comment]
Closed by #5345
