### ISSUE TITLE
Increase hardcoded fee for swaps

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#4984]
Users are reporting our hardcoded fee for swaps is set too low and often txs are not getting through. We can temporarily 'fix' this by hardcoding a higher fee until we can revisit swap fees with the UX work.

**Comment by markmhendrickson** [comment]
I'm seeing 0.75 STX recommended via app-based flow for ALEX swaps so perhaps 1 STX is a safe hardcode for now. 

<img width="461" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/8ecc3cb5-3fa5-47ce-bc76-fccbdb20e95f">
