### ISSUE TITLE
Some icons are too large on dev

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#5018]
Some icons are now too large on `dev` / Production. e.g. the tick icons for `Onboarding`

<img width="909" alt="Screenshot 2024-03-04 at 15 58 07" src="https://github.com/leather-wallet/extension/assets/2938440/58c37016-ffcd-4991-b471-3020dececd06">

**Comment by fbwoolf** [comment]
@mica000 can you link here with the new onboarding designs? What are the `right` icon sizes at this point?

**Comment by pete-watters** [comment]
I think you found them Fara but linking here for the record - https://www.figma.com/file/2stUYm67q6Tkwe31CshODA/Onboarding?type=design&node-id=1%3A16709&mode=dev

**Comment by mica000** [comment]
@pete-watters Correct, all icon by default are 24px, however because that's too big for this case, let's use the small size which is 16px. Updated the designs on the link to reflect this

**Comment by fbwoolf** [comment]
Going to close this bc was fixed on @pete-watters container branch.

**Comment by fbwoolf** [comment]
O, nvm, I see @pete-watters linked his PR here. I will reopen.

**Comment by fbwoolf** [comment]
I don't think this needs to stay open bc it is fixed in the container work and very minor. I am going to close.
