### ISSUE TITLE
User can't connect to dapp

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5021]
A user reported after clicking this to connect to a dapp:
![image](https://github.com/leather-wallet/extension/assets/33360391/d0e83a7f-5834-484f-aeed-f7fbf61813b9)

It will show this indefinitly...
![image](https://github.com/leather-wallet/extension/assets/33360391/ac413388-9654-4475-a429-5c78c18445cb)
Nothing happens even after the balances load, nothing happens. just the "loading icon" remains. 

After clicking to connect and then hundreds of 429 errors. 

This can happen on any dapp

errors like this indicating API limit is reached
![image](https://github.com/leather-wallet/extension/assets/33360391/cf3c6c5a-3cc5-4afa-8759-e7ed941acc84)

Workaround: scroll to the account you want to use. Wait until the balance loads. Then select the account. 
![image](https://github.com/leather-wallet/extension/assets/33360391/83b9fed6-74ab-45a8-a387-5abbaacacc58)

**Comment by 314159265359879** [comment]
This enhancement can resolve this issue: https://github.com/leather-wallet/extension/issues/4926

**Comment by markmhendrickson** [comment]
Let's close this out in favor of #4926?

**Comment by 314159265359879** [comment]
I am seeing this again in 6.36.0, why?
![image](https://github.com/leather-wallet/extension/assets/33360391/a178ef7c-dba1-4388-95d2-cd58ff9e4f09)

I can't connect to a dapp... I click it while it is loading balances. And then it won't connect while loading the balances of all the addresses around this one. You have to close the pop over.

**Comment by markmhendrickson** [comment]
@314159265359879 are you seeing this across various apps or just one in particular?

**Comment by 314159265359879** [comment]
@markmhendrickson this is happening across apps.

**Comment by markmhendrickson** [comment]
We may need more diagnostic info to figure out why some apps and/or accounts are affected. Do you find that other accounts work on the apps affected, or are all accounts affected? Which particular apps? And do the accounts that don't work with those apps work for other ones?
