### ISSUE TITLE
Fix request cancellation

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5058]
We can limit the number of requests we make by cancelling pending requests that are no longer needed.

Consider a very long _Choose Account_ list fetching many balances and BNS names per item. If a user scrolls quickly past an account before it's had a chance to load, React Query would trigger the request. It would be throttled by `RateLimiter`, but placed in a queue.

The request will be made, even though it's no longer needed.

The [`AbortController` API](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) and [React Query query cancellation](https://tanstack.com/query/v4/docs/framework/react/guides/query-cancellation) give us the tools to prevent these unnecessary requests.

This issue is to identify where, and propose a solution for how we can reduce unnecessary requests.

**Comment by fbwoolf** [comment]
Related? https://github.com/leather-wallet/extension/issues/4926

**Comment by markmhendrickson** [comment]
@alter-eggo Let's indeed tackle this alongside #4926 ?

**Comment by alter-eggo** [comment]
@markmhendrickson yeah, will take it as well

**Comment by markmhendrickson** [comment]
This was implemented but appears broken per [thread](https://trustmachines.slack.com/archives/C069V6G48F7/p1713306677387529)

**Comment by kyranjamie** [comment]
Let's audit that request cancellation is working for:
- [ ] BNS name requests
- [ ] Balance requests
- [ ] UTXO requests

Having worked with the queue for a while now, I think the unused address checks are the most request-hungry and eating up the queue relative to their value/use in our wallet. Let's reduce the number of empty addresses ahead we look to 5 or 10. 20 is too many.
