### ISSUE TITLE
[Feature request] Click to show contract

### ISSUE THREAD

**Issue by obycode** [blockstack/blockstack-app#5059]
I'd like to be able to click on the function in the prompt for signing a transaction and have it open the contract in the explorer in a new window.
<img width="554" alt="wallet-request" src="https://github.com/leather-wallet/extension/assets/1473715/72f58e1d-eeb7-45af-839a-4f2b12d45158">

**Comment by friedger** [comment]
This used to work.

**Comment by markmhendrickson** [comment]
Good call. We're currently redesigning this screen in general and will make sure to link.

**Comment by badonyx** [comment]
This is critical functionality, without it the user cannot verify the contract they are interacting with. It needs to be restored with high priority. In the mean time I found that the full contract address can be found with the browser's inspector tool.

**Comment by 314159265359879** [comment]
Same as https://github.com/leather-io/extension/issues/4724

**Comment by Rapha-btc** [comment]
This would be useful. I'm sometimes confirming tsx just to be able to grab the contract code.

**Comment by Rapha-btc** [comment]
I agree with [badonyx](https://github.com/badonyx) words: it's critical functionality.

**Comment by 314159265359879** [comment]
This is fixed/live again from 6.52.0
