### ISSUE TITLE
Implement error screen for failure to transfer asset due to address on denylist

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5060]
This error case needs to be implemented separately from the [approval UX redesign](https://github.com/leather-wallet/extension/milestone/75) generally given its urgency.

[See error details](https://www.notion.so/trustmachines/Failed-to-transfer-asset-due-to-address-on-denylist-0bea608855024bf1abdd8511813fb0f3)

**Comment by markmhendrickson** [comment]
@kyranjamie mind linking the relevant PR?

**Comment by kyranjamie** [comment]
For some reason it won't let me link, but https://github.com/leather-wallet/extension/pull/5122

**Comment by markmhendrickson** [comment]
This is already live and controllable via a config switch?

**Comment by kyranjamie** [comment]
It's disabled on prod, not via switch. I was going to put in behind the config, but this would've required changing the implementation too much at the time.

**Comment by markmhendrickson** [comment]
Event `non_compliant_entity_detected` is now tracked in production so we can see how often it is triggered before enabling the error screen.

**Comment by markmhendrickson** [comment]
@kyranjamie is this live now?

**Comment by kyranjamie** [comment]
@markmhendrickson The check is live. When triggered, it would hit the generic error screen @alter-eggo worked on
