### ISSUE TITLE
Fix redirect to relevant screen for API request instead of home upon unlock

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5066]
The user should see the PSBT signing modal here instead of going home within the popup:

https://github.com/leather-wallet/extension/assets/28991/b638eeb7-f0a3-4cb1-8ec7-4516db4e0a1b

**Comment by kyranjamie** [comment]
Let's write a test for this one.

When wallet is locked, and user triggers PSBT signing, user signs in, assert that we land on correct page

**Comment by pete-watters** [comment]
This will be fixed by https://github.com/leather-wallet/extension/pull/5281
