### ISSUE TITLE
Reintroduce retrieving uninscribed BTC from taproot (inscription) address

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5067]
Reasons this was disabled:
1. Sometimes it would display sats erronously as uninscribed due to API connection issue
2. Or due to the sats still pending incoming
3. Or due to the indexer not yet having processed the state

We believe the API is now more reliable because there are two checks, filtering UTXO with inscriptions for displaying and again when assessing available balance for sending. Did I understand this correctly @alter-eggo?

To prevent issues due to 2-3 in addition we could do the following:
A. Never display UTXO's with a size of 10000 sats or less as uninscribed. Inscriptions are often in small UTXO's that are often not even worth retrieving.
B. And/or do not display them until they have 6-12 confirmations (ca. 1-2 hours) something central exchanges do to avoid issues associated with reorgs/double spending. 

Related 
https://github.com/leather-wallet/extension/issues/4513

**Comment by markmhendrickson** [comment]
> We believe the API is now more reliable because there are two checks, filtering UTXO with inscriptions for displaying and again when assessing available balance for sending. 

@alter-eggo is this correct? 

And @kyranjamie remind me – is this why we disabled this feature in the first place (because there was a delay sometimes in the API recognizing recently deposited inscriptions, leading to their possible expenditure as as fees during retrieval)?

> To prevent issues due to 2-3 in addition we could do the following:
> A. Never display UTXO's with a size of 10000 sats or less as uninscribed. Inscriptions are often in small UTXO's that are often not even worth retrieving.
> B. And/or do not display them until they have 6-12 confirmations (ca. 1-2 hours) something central exchanges do to avoid issues associated with reorgs/double spending.

How difficult would either of these solutions be technically?

**Comment by alter-eggo** [comment]
@314159265359879 @markmhendrickson yeah, we filter utxos with request to hiro and then check utxos when broadcasting with request to ordinals.com

**Comment by alter-eggo** [comment]
@markmhendrickson I believe both are quite easy to implement
