### ISSUE TITLE
Remove tooltips from swap details

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5069]
Neither of these are needed, and the sponsorship-related one isn't true when we disable sponsorships generally / it has conditionality issues as implemented so we might as well remove.

<img width="399" alt="Screenshot 2024-03-13 at 11 31 54" src="https://github.com/leather-wallet/extension/assets/28991/4c2f7353-1462-4120-abc1-e4e5b796d4f2">
<img width="400" alt="Screenshot 2024-03-13 at 11 32 12" src="https://github.com/leather-wallet/extension/assets/28991/6d402b94-f836-4421-b2e5-4401d7327ea1">

**Comment by mica000** [comment]
@markmhendrickson if this is just for remove - should this be assigned for design backlog?

**Comment by markmhendrickson** [comment]
I figure it requires a tweak to the new approval UX designs as well?

**Comment by mica000** [comment]
Let's see.. this is the current designs do you think we need to show tooltips on each subtitle?

<img width="347" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/90b28ec1-d2c4-4a19-8824-a49298fe19d2">

**Comment by markmhendrickson** [comment]
Ah no – this design for the new approval UX looks good in that it _doesn't_ have tooltips per listed value.

I'll close this issue out since it'll get resolved implicitly with the new design. 🙏
