### ISSUE TITLE
Fix formatting for transactions in submitted state in activity

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5070]
<img width="439" alt="Screenshot 2024-03-13 at 11 32 23" src="https://github.com/leather-wallet/extension/assets/28991/8deb5e2a-217d-4eea-a3c9-a3400d8921c7">

**Comment by fbwoolf** [comment]
This is driving me bonkers, so fixing here to match other txs in activity list: https://github.com/leather-wallet/extension/pull/5500

<img width="916" alt="Screenshot 2024-06-10 at 7 14 16 PM" src="https://github.com/leather-wallet/extension/assets/6493321/95621cfa-7a92-401d-a2cf-31e1649ef555">
