### ISSUE TITLE
Remove hover effect for BRC-20 tokens under balances

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5071]
They shouldn't have any hover effect, like the other token types don't:

![image](https://github.com/leather-wallet/extension/assets/28991/208c42c3-d89b-4183-81e2-8408fb10fc92)

**Comment by pete-watters** [comment]
I checked this and we show a hover on this element as it's wrapped in another tooltip element that shows when we don't have enough BTC in balance. 

I am forcing it to show below now: 
![Screenshot 2024-03-21 at 06 40 14](https://github.com/leather-wallet/extension/assets/2938440/e2f67995-077e-43c5-abca-2314675b3392)

@markmhendrickson - should this tooltip show on the home page balances? Or should it be in other flows when choosing BRC20. e.g. on `Send` ? 

We have a lot of almost identical code sharing components but in different flows. Its related to this also https://github.com/leather-wallet/extension/issues/4949 where we show BRC-20 under the fund flow

My thoughts are that:
- this tooltip is only supposed to show on the Send flow where you can click BRC-20 then go to send
- BRC-20 should not appear at all on fund flow
- On the home assets page we never show a tooltip or click ability for this


https://github.com/leather-wallet/extension/assets/2938440/1ca7325c-3df5-448c-afab-ffcf017ce207

**Comment by markmhendrickson** [comment]
Those thoughts are indeed correct.

I'm not even sure we should show this tooltip within the send flow (when picking the token for send), since it seems like we could handle better through some other UX pattern. But we can tackle that later during send UX redesign so it's okay to leave it there (while removing from home) for now – or just remove from both if easier. cc @fabric-8

**Comment by pete-watters** [comment]
Thanks @markmhendrickson 👍 

It feels confusing how this was working:
- If you don't have funds the row showed hover but you can't click
- on hover it gave the tooltip warning

I went with removing the tooltip as it was faster and more effective for now. I kept having the row disabled on 0 balance as I don't want it to cause another issue like the form crashing. 

Lets think of how to improve it later. My gut says we should let people go to BRC-20 send form and then have form validation there if they don't have enough balance for fees. 

Right now the check we had is to let them progress if they have a BTC balance greater than `0`, which is not really accurate as they still might not have enough to cover fees:
```
  const hasPositiveBtcBalanceForFees =
    btcCryptoCurrencyAssetBalance.balance.amount.isGreaterThan(0);
```

We use a similar check in `PendingBrcTransfer` so we can consider our preferred flow and improve both together.

**Comment by pete-watters** [comment]
I included a fix for this in https://github.com/leather-wallet/extension/pull/4655, I can't link anymore issues to that PR as the max is 10.

**Comment by pete-watters** [comment]
This has been release
