### ISSUE TITLE
Fix profile test

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#5072]
This test still seems to be a problem, though it passes locally. I believe there are multiple requests happening in this test and we are only handling one of them.

In this PR I skipped the test: https://github.com/leather-wallet/extension/pull/5063

Assigning to myself to fix now, just wanted an issue to track it.

**Comment by pete-watters** [comment]
Thanks for opening this. There is another task about test reliability, check my comment [here](https://github.com/leather-wallet/extension/issues/3919#issuecomment-1983978072)

I found that sometimes we may be over-using `beforeEach` to relogin etc. and that is causing us to get rate limited and then hit 429 errors. 

A lot of times I saw the tests stuck, not being able to change to Testnet as it was hitting a 429 error.
