### ISSUE TITLE
Display STX-20 balances

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5077]
[See API information](https://www.notion.so/trustmachines/STX-20-API-d0c71bcf41fa48dca566cb631ef42170)

**Comment by fbwoolf** [comment]
Oops, I linked my PR to the wrong issue. I will reopen this one.

**Comment by fbwoolf** [comment]
Removed the requirement to included this in total balance calc bc we opened another issue to address refactoring our total balance code. https://github.com/leather-wallet/extension/issues/5159

**Comment by fbwoolf** [comment]
@markmhendrickson the link in the description here goes to SRC-20, and there doesn't appear to be a link for a STX-20 api?

**Comment by markmhendrickson** [comment]
Oops, the URL was wrong – I've fixed in the description.
