### ISSUE TITLE
Display collectible previews for inscriptions with "model/gltf+json" mimetype

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5091]
Runestones (e.g. [this one](https://www.ord.io/64409883)) have a "model/gltf+json" mimetype. I'm seeing Ord.io displays these with a `model-viewer` HTML tag. @fbwoolf @kyranjamie are these tags safe to use in the wallet? 

<img width="1028" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/f0347e36-4836-4ec5-895e-20b015887cee">

**Comment by kyranjamie** [comment]
@markmhendrickson looks like it's an instance of https://modelviewer.dev

Requires a script, so no way we can render without an iframe.
