### ISSUE TITLE
Provide option to hide values

### ISSUE THREAD

**Issue by BTCAlchemist** [blockstack/blockstack-app#5096]
When the user clicks the browser extension, the extension shows their account's total USD value. This can be a security issue for users who are in public locations or in a location where they don't want others to see their USD value. Trust Wallet on iOS is a good example where clicking the balance masks all balances as asterisks. Would you please add a feature where the user clicks the USD value to hide/unhide the amounts in the wallet?

**Comment by markmhendrickson** [comment]
Good idea! We've been discussing this recently as well 🙏

**Comment by pete-watters** [comment]
A contributor has implemented this feature and it will be available in the next release.  

Thanks again @adrianocola 👏
