### ISSUE TITLE
visual bug secret key input (Firefox) 6.31.0

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5102]
![image](https://github.com/leather-wallet/extension/assets/33360391/d4958598-617c-48f3-a97b-96f0a8e88bc7)

![image](https://github.com/leather-wallet/extension/assets/33360391/e7fab552-0063-46b5-8a79-fe01a64b7c88)

**Comment by 314159265359879** [comment]
It looks off in more of the pages in the wallet, here is the send flow:
![image](https://github.com/leather-wallet/extension/assets/33360391/3d5f8141-546c-4a76-bfed-ea6f143a1412)

**Comment by markmhendrickson** [comment]
I'm closing this issue since Firefox is deprecated.
