### ISSUE TITLE
Signing PSBT with Ledger Nano X throws Error

### ISSUE THREAD

**Issue by Polybius93** [blockstack/blockstack-app#5113]
I am trying to sign a *PSBT* on *Testnet* with *Ledger Nano X*.  On the *Leather* review page, everything seems fine, inputs and outputs defined, but on the *Ledger* review window, the inputs' sats are *undefined*:
<img width="957" alt="Screenshot 2024-03-21 at 13 12 57" src="https://github.com/leather-wallet/extension/assets/99192647/9e856ca4-d1ef-4417-9986-382bf1f973b4">
<img width="1471" alt="Screenshot 2024-03-21 at 13 13 10" src="https://github.com/leather-wallet/extension/assets/99192647/fbcfb240-7d09-4952-bed1-ed8f520c79f9">
_then_ I get an *error*: 
```
logger.ts:51 Unable to sign tx with ledger TransportStatusError: Ledger device: Invalid data received (0x6a80)
    at TransportWebUSB.<anonymous> (Transport.js:53:1)
    at Generator.next (<anonymous>)
    at fulfilled (Transport.js:4:43)
```
Here is the raw transaction:
```
{
  "value": {
    "global": {
      "unsignedTx": {
        "version": 2,
        "segwitFlag": false,
        "inputs": [
          {
            "txid": "7a952ccafda7d8f2e1ecfbd6b4b6384966694950d3bfaf4eb68fb42d9e1bea36",
            "index": 0,
            "finalScriptSig": "",
            "sequence": 4294967295
          },
          {
            "txid": "331cdc3c85c1ec26529153077c8f237b64963c50e5cb98032c902c3c3264b67e",
            "index": 0,
            "finalScriptSig": "",
            "sequence": 4294967295
          }
        ],
        "outputs": [
          {
            "amount": "100000",
            "script": "512095933dcde5a8bcec1da4d834225c6b2fd4ae56bd3e030f2ddae15298b98dabcb"
          },
          {
            "amount": "79558",
            "script": "0014050d6838a98c0118a3c0c9f6b29113a92786d11b"
          }
        ],
        "lockTime": 0
      }
    },
    "inputs": [
      {
        "nonWitnessUtxo": {
          "version": 2,
          "segwitFlag": true,
          "inputs": [
            {
              "txid": "c1d258fe34626edd15be7fe0d7ffe975ed831ca73b8b04212f2a23f11049c396",
              "index": 0,
              "finalScriptSig": "",
              "sequence": 4294967295
            }
          ],
          "outputs": [
            {
              "amount": "90000",
              "script": "0014050d6838a98c0118a3c0c9f6b29113a92786d11b"
            }
          ],
          "witnesses": [
            [
              "16de8eb3bceb84b68384a1fa2aa3c675d51b7717e1e8ec65797fe10647a5d50614a53cb8c216e62dadb54936ada15d24ec827dcc2e1bc1d2d7692eaea09ebc3c",
              "75d1682915951b2e6494e07faacebf10c66667174037ecf95c9d57678d934b55d8268a4dae43d4296425f85ff5af7a5f60cfc09b3e23c5113c6bdfbafe49e0bb",
              "20dc544c17af0887dfc8ca9936755c9fdef0c79bbc8866cd69bf120c71509742d2ad200c0bf55fa1ab72462467b973b13e556b07d2fdd8d7a30cdfc10f337e23c7ac00ac",
              "c050929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0"
            ]
          ],
          "lockTime": 0
        }
      },
      {
        "nonWitnessUtxo": {
          "version": 2,
          "segwitFlag": true,
          "inputs": [
            {
              "txid": "57530af690be0da316e2a6869580c8f0c5a7d57361a2ea3c66bbe678767375a3",
              "index": 0,
              "finalScriptSig": "",
              "sequence": 4294967295
            }
          ],
          "outputs": [
            {
              "amount": "90000",
              "script": "0014050d6838a98c0118a3c0c9f6b29113a92786d11b"
            }
          ],
          "witnesses": [
            [
              "aa18c92b2a49598ab2bb527d3a9309d74ac59671420f478caa89a045c210f7bae0b5984e528cdc31e63c882347d7edb928aea53ad279b8733f940e91a27cd082",
              "8da9e2d051bfcaa877732dd065e2c9f9bb9360bead9522b7d81305c2fe374601a068296bc4dc44e25d1c9b849cc68bfc2bee369ff1a260c89d0bda72823f3135",
              "20dc544c17af0887dfc8ca9936755c9fdef0c79bbc8866cd69bf120c71509742d2ad200c0bf55fa1ab72462467b973b13e556b07d2fdd8d7a30cdfc10f337e23c7ac00ac",
              "c050929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0"
            ]
          ],
          "lockTime": 0
        }
      }
    ],
    "outputs": [
      {},
      {}
    ]
  }
}
```

*Bitcoin Testnet app* on my *Ledger* is up to date.

**Comment by Nithishvb** [comment]
Hey @Polybius93 can you please tell me how to reproduce this bug.

**Comment by Polybius93** [comment]
Hey @Nithishvb ! Sure, if I send you a PSBT hex, would that help you to recreate?

**Comment by Polybius93** [comment]
In case if it does help, here is the _hex_ of a *PSBT* i was trying to sign with *Ledger*:
```
70736274ff01007d0200000001097aa7c8af01cc084b6ed1f1de027156c92a1b09f255f8a1184b5eaec6cf81d30100000000ffffffff02a0860100000000002251203528c22a161bd4da764f9149baf7dc9235c661940e1c1eb6416eb536606dbe237403cb0e000000001600145a81f36535980769bccc23c196337a78458abd1e00000000000100eb02000000000101cba5625039d25b2aeb462b7236a88d6351fe7e27609245486569c93f0716b2a80100000000ffffffff02a0860100000000002251203528c22a161bd4da764f9149baf7dc9235c661940e1c1eb6416eb536606dbe23468bcc0e000000001600145a81f36535980769bccc23c196337a78458abd1e02483045022100d4fad0650ed4d4d18d84d1c99acfc58a5059c301221e956c69fccb83baddbf1a02203a42d4a43f786b2554e477b2e5d1af0e2c1e47674778ae28be47051581f807e5012103c9fc819e3c26ec4a58639add07f6372e810513f5d3d7374c25c65fdf1aefe4c500000000220203c9fc819e3c26ec4a58639add07f6372e810513f5d3d7374c25c65fdf1aefe4c54730440220336b67277a6a8a2a16482dc09958c540a33b6168cecb423017e7cb109387576002206db85aa7b51c14f6af09f75a15e6fcbf303499aab1829bffc5a2486104964ade01000000
```

**Comment by Polybius93** [comment]
Hey @pete-watters ! Any updates on this issue? Thanks!

**Comment by pete-watters** [comment]
Hey @Polybius93 ,

Unfortunately not as I have had to switch to another task but this is at the top of my priorities and hope to progress it soon. Apologies for the delay

**Comment by pete-watters** [comment]
I found that this PSBT is failing to sign as it contains a `nonWitnessUtxo` input and currently our code is only handling `witnessUtxo`. I am investigating adding a fix for this

**Comment by kyranjamie** [comment]
> I found that this PSBT is failing to sign as it contains a nonWitnessUtxo input and currently our code is only handling witnessUtxo

Unless I'm mistaken, this is only the cause of the bug where input values are presented as `undefined`. Ledger txs should be able to sign `nonWitnessUtxo`s, we have explicit handling of older utxos here, as Ledger requries the entire tx to be passed.

https://github.com/leather-wallet/extension/blob/f19a80dbae9808ae83c20e0d4c2808d597e7485d/src/app/store/accounts/blockchain/bitcoin/native-segwit-account.hooks.ts#L138-L156

**Comment by pete-watters** [comment]
@Polybius93 and I spent a while investigating this issue and determined that the underlying issue here relates to a current lack of multisig signing support in Ledger. 

In this issue there are several problems:
1. incorrectly displaying an `undefined` input amount for `nonWitnessUtxo`s
2. lack of support currently for multisig signing
3. signing with `nonWitnessUTXOs` isn't working

I will add small code to address issue `1`. To address `2` more efforts are needed and we will need to update our `signPsbt` API to accept a custom policy to allow for multisig signing

@Polybius93 was only able to sign non-multisig transaction with Ledger if it contained witnessUTXOs instead of nonWitnessUTXO

**Comment by pete-watters** [comment]
I made some small changes to improve how we display amounts and handle non-witness UTXOs. 

To process the multi-sig transaction this bug is trying to sign, more work needs to be done to add support for multi-sig on Ledger
