### ISSUE TITLE
Fix delete icon alignment for network

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5124]
<img width="502" alt="Screenshot 2024-03-26 at 11 39 04" src="https://github.com/leather-wallet/extension/assets/28991/097ea1b4-358f-400b-aea0-61ec55b27b71">

**Comment by markmhendrickson** [comment]
@fabric-8 do we have guidance on the 🗑️  icon placement in Figma to link here?

**Comment by fabric-8** [comment]
[Just added some guidance here](https://www.figma.com/design/zuHTXp7zEBpKJXxhOIVejK/%F0%9F%9F%A7-Web-App-Explorations-2024-H1?node-id=5985-316428&t=AFkd0o93tfZm6g0F-1). I assume we'd also want to let people edit networks they've added?

<img width="675" alt="CleanShot 2024-03-26 at 18 11 58@2x" src="https://github.com/leather-wallet/extension/assets/4112698/644a5914-ddc7-4ef1-bd74-7f61468a3a40">

**Comment by pete-watters** [comment]
Another task to complete as part of this is to truncate the network name in the dropdown menu if its too long: 
https://github.com/leather-io/extension/issues/2248 

It's not breaking the UI now but could do with some ellipsis
![Screenshot 2024-06-28 at 11 26 45](https://github.com/leather-io/extension/assets/2938440/3a793147-5b15-4ba1-85ae-2df910edc3ff)
