### ISSUE TITLE
Fix overflow of balances in account selection

### ISSUE THREAD

**Issue by fabric-8** [blockstack/blockstack-app#5131]
![image](https://github.com/leather-wallet/extension/assets/4112698/cd3b4bd6-8ff1-4579-8df2-7d86cf04c64c)

cc @kyranjamie I guess this might be somewhat fixed via #5125 ?

**Comment by kyranjamie** [comment]
@fabric-8 nope, I only changed home page

**Comment by pete-watters** [comment]
I checked this and the change in https://github.com/leather-wallet/extension/pull/5125 modifies `useTotalBalance` which is in turn used in the account switcher `AccountTotalBalance` so this issue is resolved
