### ISSUE TITLE
Fix network bitcoin API dropdown menu

### ISSUE THREAD

**Issue by fabric-8** [blockstack/blockstack-app#5132]
![Image](https://github.com/leather-wallet/extension/assets/4112698/e026d8c0-a8c6-42cc-bce2-7f3478cff9fe)

**Comment by pete-watters** [comment]
I took a look at this and tried swapping in the new `Select` component we have but I couldn't get it working fully. I postponed it for now but can return to it soon.

**Comment by pete-watters** [comment]
@alter-eggo fixed this a few weeks ago and added the `Select` component
