### ISSUE TITLE
Tweak onboarding: Add borders to onboarding containers, fix back arrow alignment

### ISSUE THREAD

**Issue by fabric-8** [blockstack/blockstack-app#5134]
- [Should look like this](https://www.figma.com/file/2stUYm67q6Tkwe31CshODA/Onboarding?type=design&node-id=1%3A2060&mode=design&t=ddSDFKCm6fkkBmrn-1)
- Add border to main container
- Make sure padding diff between arrow back on top and content is as little as possible

![Image](https://github.com/leather-wallet/extension/assets/4112698/6269fae1-3709-4609-b816-15976d5d7fb3)

**Comment by pete-watters** [comment]
I added a border here and moved the back button to the left for onboarding screens by reducing padding. 

Looking at the design and I think it's close now as in the design it doesn't fully align either:
![317788075-9c3fb392-79e4-4ce8-806b-edf0422425ef](https://github.com/leather-wallet/extension/assets/2938440/3e81567e-22ed-4efe-b53a-62f9aaeec16b)

Here's how I have implemented it:
![Screenshot 2024-03-28 at 15 41 09](https://github.com/leather-wallet/extension/assets/2938440/86f0d4f1-a9f5-44ba-9265-956e902df593)

**Comment by markmhendrickson** [comment]
> Looking at the design and I think it's close now as in the design it doesn't fully align either:

@fabric-8 @mica000 please review 🙏
