### ISSUE TITLE
Unable to send more than 100m STX

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-app#5136]
In Leather's "send STX" flow, you can't type in an amount larger than 100m STX (or maybe technically 999m STX). If you enter more zeros, they're just not accepted. This is a pretty reasonable behavior for mainnet, but on testnet/devnet it's common to have more than that. This is an issue when working with some of the genesis accounts on the Nakamoto Testnet, because the Stacking minimum is 1B STX.

**Comment by fbwoolf** [comment]
@markmhendrickson ^
