### ISSUE TITLE
Pending outgoing STX transfer, amount is not displayed

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5141]
Top one is an outgoing transfer for 1 STX, amount is not displayed. 

Below is an incoming pending transfer there the amount is displayed. 
![image](https://github.com/leather-wallet/extension/assets/33360391/2ec3de44-a9f8-44cb-8a53-58d32ae9abc6)

**Comment by 314159265359879** [comment]
I expect the amount to be displayed in both cases.

**Comment by markmhendrickson** [comment]
This appears to be a dupe of https://github.com/leather-io/extension/issues/5826, which is now resolved
