### ISSUE TITLE
Ledger routing issue when rejecting

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5143]
When rejecting an action, and pressing the `×` button, the user is navigated to the homepage, rather than to the beginning of the signing flow.

This bug is likely caused by the `/*` routing used, breaking the `navigate('..')` action.

https://github.com/leather-wallet/extension/assets/1618764/223e4a49-6706-431c-8578-e8a56b4d5462

**Comment by pete-watters** [comment]
I have come up with a fix here where we determine where to go back based on the initial path of the current route. This is similar to what `../` was doing. 

I tried to change the routing to remove `/*` which I agree is likely breaking the `../` navigation but couldn't get it to work without causing more problems.
