### ISSUE TITLE
Can not transfer token bitcoin with api 

### ISSUE THREAD

**Issue by louisdangw3** [blockstack/blockstack-app#5161]
hi every one . i want to transfer token bitcoin với body as address from , to , amount but i dont see the api in leather can be support this in bitcoin net work . i check the api in blockstrem but can not be transfer token BTC in my wallet. . POST /tx
Broadcast a raw transaction to the network.

The transaction should be provided as hex in the request body. The txid will be returned on success. plz help me

**Comment by markmhendrickson** [comment]
Does this help? https://leather.gitbook.io/developers/bitcoin/sign-transactions/sending-bitcoin
