### ISSUE TITLE
Fix button states in dark mode

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#5166]
![image](https://github.com/leather-wallet/extension/assets/6493321/a5742987-2a2e-48ff-991b-6acab8971660)

**Comment by fabric-8** [comment]
There's now https://github.com/leather-wallet/mono/pull/90 — Once it's merged and the package in the extension updated, we can update occurences of non-interactive to use the new text or background tokens which fix this

**Comment by markmhendrickson** [comment]
@fabric-8 does https://github.com/leather-io/mono/pull/90 above include everything needed for development here?

**Comment by fabric-8** [comment]
@markmhendrickson I just double checked, this is done and resolved by now
