### ISSUE TITLE
Increase Fee gets cut off

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#5173]
User-reported issue when a contract name is too long, the "Increase Fee" button gets cut off.

![image](https://github.com/leather-wallet/extension/assets/122313287/193a8f31-9166-4f47-bfc7-24a3172ea822)

**Comment by 314159265359879** [comment]
Thanks adding. 

Workaround: open the wallet in a new tab via the top right corner menu. 

Lets check if this is resolved with the containers PR which is going out in the next release (Monday).

**Comment by kyranjamie** [comment]
The styles more generally look broken here. This is prod version @brandonmarshall-tm ?

**Comment by 314159265359879** [comment]
@kyranjamie This is on production, I see it too. (Chrome/Windows)

**Comment by pete-watters** [comment]
I'm pretty sure this issue will be fixed once we do the next release which contains https://github.com/leather-wallet/extension/pull/4655. 

As I can see the scrollbar in the screenshot I am guessing the user is using chrome on Windows. Lets check if it is still broken once we do the next release and if it is I can check it further. 

It would be good to get some more details regarding the browser / OS

**Comment by markmhendrickson** [comment]
I believe the new containers work improves this issue in some regards, but it ends up cutting off "Increase" leaving just "Fee"

<img width="417" alt="Screenshot 2024-03-22 at 17 43 30" src="https://github.com/leather-wallet/extension/assets/28991/9976ccb0-31c5-4f64-93fe-49721283ded5">

**Comment by pete-watters** [comment]
I fixed this and made sure we always say `Increase Fee`. We had some code there that was explicitly only showing `Fee` in popup mode
