### ISSUE TITLE
Activity tab doesn't update for minutes after a transaction is completed (Bitcoin and Stacks)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5175]
Transactions shown as pending one moment are not displayed the other moment. This is possibly related to switching between addresses and throttling being applied to prevent the wallet from hitting certain limits. 

![image](https://github.com/leather-wallet/extension/assets/33360391/13a076b7-1550-457c-9b1a-0e7136dd1c37)

Opening the wallet in a tab and refreshing the page can help resolve it. 

Some steps that made my reproduce for a Stacks transaction.
1. Create stacks transaction for example a swap on Velar
2. Confirm transaction **and see it pending in the activities tab**
![image](https://github.com/leather-wallet/extension/assets/33360391/a314a7e6-1110-4471-b49c-b4a329de328e)

3. Switch to different account and check activity
4. Leave it for a while: 30 minutes for example (enough time for the transaction to confirm)
5. Go back to the account that created the transaction
6. See the following: (4th of April that was 4 days ago... new transaction is confirmed but doesn't show)... waiting minutes, no difference.
![image](https://github.com/leather-wallet/extension/assets/33360391/7e7f2c64-eb2b-436d-8769-64c223837397)

7. Open wallet in a new tab and see the most recent transaction:
![image](https://github.com/leather-wallet/extension/assets/33360391/84092ca9-da51-4516-8ac1-9fb889524c0c)

**Comment by 314159265359879** [comment]
I see pending transactions showing one moment, then if I switch between assets and activity the pending transaction can be gone for a second before it shows again too.

**Comment by 314159265359879** [comment]
It takes 10-20 sec when I switch to another account and load the activity (wallet with 25 accounts).
![image](https://github.com/leather-wallet/extension/assets/33360391/d0ec3d08-2ae0-4af7-a860-68b242f390f6)

**Comment by markmhendrickson** [comment]
@alter-eggo is this resolved by the migration to Mempool?

**Comment by alter-eggo** [comment]
@markmhendrickson yes

**Comment by markmhendrickson** [comment]
@314159265359879 for integration review as part of https://github.com/leather-io/extension/pull/5726

**Comment by 314159265359879** [comment]
Confirmed resolved in 6.45.2
