### ISSUE TITLE
Fix build warning about `colors.focus` 

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#5225]
The build currently gives a warning about not being able to find `colors.focus` in the button recipe. I think after our colour changes

```
<i> [webpack-dev-server] Content not from webpack is served from '/Users/petew/src/leather/extension/build' directory
Starting server on http://localhost:8080
  build [==========          ] 50%🐼 warn [token] Reference not found: `colors.focus` in "3px solid {colors.focus}"
🐼 warn [token] Reference not found: `colors.focus` in "3px solid {colors.focus}"
🐼 warn [token] Reference not found: `focus` in "3px solid {focus}"
🐼 info [hrtime] Extracted in (910.13ms)
```

@fbwoolf do you have an idea about how to solve this?

**Comment by fbwoolf** [comment]
This one must have been removed, but never updated in our code. I can assign to myself to fix. I'm not sure what it is supposed to be at this point, but will look into it.
