### ISSUE TITLE
PNG inscription not displaying in Collectibles 

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#5236]
Not quite sure why, but just want to report this inscription that is not displaying correctly in my wallet, even though it seems like a basic PNG file?

https://www.ord.io/68700091
![Screenshot 2024-04-15 at 3 43 37 PM](https://github.com/leather-wallet/extension/assets/122313287/3835faa1-0288-4135-ada7-975697ae338d)

**Comment by pete-watters** [comment]
I think this happens when you are rate limited / get 429 issues from the API

**Comment by markmhendrickson** [comment]
@brandonmarshall-tm can you check your network panel to see what the API query returns for this particular inscription, and share the URL of the API call here for diagnosis?

**Comment by brandonmarshall-tm** [comment]
Someone will have to help me figure out how to do that!

**Comment by markmhendrickson** [comment]
@314159265359879 or @DeeList mind taking a look with @brandonmarshall-tm?

**Comment by DeeList** [comment]
https://api.hiro.so/ordinals/v1/inscriptions/a77c2fda458fc67028cb444b3b3fdcdf36b168d89ceb7286630d2fc76b21a714i476


<img width="1152" alt="hiro2" src="https://github.com/leather-wallet/extension/assets/132958967/d0e45d6a-5f27-4b8d-8e76-0792efeda0f8">

**Comment by markmhendrickson** [comment]
It does appear the API is simply failing to return it: https://api.hiro.so/ordinals/v1/inscriptions/a77c2fda458fc67028cb444b3b3fdcdf36b168d89ceb7286630d2fc76b21a714i476/content

@DeeList mind asking Hiro to investigate?

**Comment by DeeList** [comment]
Issue reported to Hiro https://github.com/hirosystems/explorer/issues/1591

**Comment by DeeList** [comment]
https://github.com/hirosystems/explorer/issues/1591#issuecomment-2093829686

**Comment by markmhendrickson** [comment]
I've followed up [here](https://github.com/hirosystems/explorer/issues/1591#issuecomment-2109872002).
