### ISSUE TITLE
Cannot connect Ledger in Testnet

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#5239]
There is a bug where if you:
- login to a wallet without ledger
- change the network to testnet
- logout
- you cannot login with ledger as it has persisted the network as testnet

You will see this error:
![Screenshot 2024-04-16 at 16 23 19](https://github.com/leather-wallet/extension/assets/2938440/cba38f94-7655-44b2-8a6d-d848427abb4d)

Then if you try and sign in with a key you can see its on `Testnet`:
![Screenshot 2024-04-16 at 16 23 29](https://github.com/leather-wallet/extension/assets/2938440/56a932d4-bd9f-47f2-8e7a-c88a7cadf642)

We used to let users change the network from the header but we deprecated this. 

I think a good fix would be to reset the wallet to mainnet on sign out

**Comment by kyranjamie** [comment]
We should reset the network to network when signing out.
