### ISSUE TITLE
Can't scroll to last couple of accounts on the account selection screen

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5242]
I can reproduce this sometimes the last 5 accounts are not displayed. when scrolling the select account screen. 

See the issue after clicking account 1 (or any)
to open the account selection page
then add account
switch account again scroll up then down
try this on an wallet with 50 or more accounts (that is what the user was testing with, and I saw it on a wallet with 500 accounts too).

 

https://github.com/leather-wallet/extension/assets/33360391/4d9347cb-7015-4b4f-875d-ca434d5efe75

**Comment by 314159265359879** [comment]
workaround, add some additional accounts so you can always scroll to the one you want to reach anyway.

**Comment by brandonmarshall-tm** [comment]
+1 another user report of the same issue

**Comment by pete-watters** [comment]
Thanks for the report, I'll fix this ASAP. I had to add an urgent fix on top for https://github.com/leather-wallet/extension/pull/5171 which resulted in this.

It also relates to historical issues we have had here https://github.com/leather-wallet/extension/issues/4764
