### ISSUE TITLE
`__rust_start_panic` wasm error with DLC lib

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5244]
We've started encountering lots of wasm errors with the dlc lib. Not sure what change would have triggered this, however Sentry reports thousands of these errors in the last month.

First appears in v6.31.0

**Comment by pete-watters** [comment]
I hit this issue today when working on something else. 

I was logged into `testnet` and when I tried to change back to `mainnet` the UI was blocked on the change network screen with no options loading then threw this error:

![TestnetChangeNetworkTimeout](https://github.com/leather-wallet/extension/assets/2938440/f576f675-9905-4b4e-be52-e298dddcde73)

**Comment by markmhendrickson** [comment]
@fbwoolf I assume this is related to the work you're tackling with https://github.com/leather-io/issues/issues/69?

**Comment by fbwoolf** [comment]
> @fbwoolf I assume this is related to the work you're tackling with [leather-io/issues#69](https://github.com/leather-io/issues/issues/69)?

Yep!
