### ISSUE TITLE
Fix viewport-responsive formatting in popup window

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5248]
Is a standard width expected to be enforced?

![image](https://github.com/leather-wallet/extension/assets/33360391/16ff559c-1826-47e8-abb0-3d249b2f12cf)

version 6.33.0 and 6.34.0 on Chrome browser

**Comment by pete-watters** [comment]
Is this on Windows?

**Comment by kyranjamie** [comment]
@314159265359879  is this because the window is resized smaller? I noticed this too.

I think we should use max-widths, rather than fixed widths, so that users can resize the window.

**Comment by 314159265359879** [comment]
> Is this on Windows?

Yes this is on windows.

It pops up with this size, it used to pop up wider and shorter.

**Comment by 314159265359879** [comment]
when the popover is wider the button goes off screen, I am only seeing this for the first time in Vivaldi browser
(connecting on stacks.gamma.io while the wallet is locked)
![image](https://github.com/leather-wallet/extension/assets/33360391/23ade898-a44c-4919-8222-d9b269e0aabc)
It pops up with this width 


On chrome I can widen and see the same issue with the button here when signing a PSBT
![image](https://github.com/leather-wallet/extension/assets/33360391/1c0426d4-3312-4c8d-816a-1375fd1126a8)


As opposed to the button view when not so wide
![image](https://github.com/leather-wallet/extension/assets/33360391/781f7bf3-cb61-4539-a81f-78b38b2b34a5)

**Comment by pete-watters** [comment]
I had a quick look at this and I do need to fix it. The unlock screen in popup is something I missed. 

When you try and use the settings menu in popup it also looks really bad:

![Screenshot 2024-04-26 at 15 53 41](https://github.com/leather-wallet/extension/assets/2938440/1bc8e133-eaee-4124-b7ca-efb6ac63db82)

**Comment by pete-watters** [comment]
A similar issue was reported in https://github.com/leather-io/extension/pull/5561 , based on https://trustmachines.slack.com/archives/C05114YP8CV/p1718960758669539. 

I will resolve that here also

**Comment by markmhendrickson** [comment]
> I think we should use max-widths, rather than fixed widths, so that users can resize the window.

+1 as a general principle across views

**Comment by pete-watters** [comment]
> > I think we should use max-widths, rather than fixed widths, so that users can resize the window.
> 
> +1 as a general principle across views

I will fix it so it scales on resize and also opens properly. We need both a width and a max-width here I think. 

If there is no standard width set then the extension won't open properly: https://github.com/leather-io/extension/issues/5565

**Comment by kyranjamie** [comment]
> If there is no standard width set then the extension won't open properly: https://github.com/leather-io/extension/issues/5565

This is only needed for the action popup. It isn't needed for window pop ups.

We need a way to target different styles to both the action popup, and window pop ups. Previously, these had a separate HTML file (`popup-centre.html` was removed). Either we need to reintroduce that, or find another way to target them individually.

**Comment by pete-watters** [comment]
There are also bugs with the footer when resizing reported [here](https://trustmachines.slack.com/archives/C05LRS7G44R/p1720691531557929)

**Comment by pete-watters** [comment]
I spent some time on this and have a draft PR in final testing now - https://github.com/leather-io/extension/pull/5671. 

As part of this I:
- re-instated a different file for the action popup - now called `action-popup.html` 
- the `popup.html` file is then used for standard approval popups
- refactored the footers [to fix](https://trustmachines.slack.com/archives/C05LRS7G44R/p1720691531557929) 
- updated the popup to have a max width of `640px` [as per](https://trustmachines.slack.com/archives/C05LRS7G44R/p1720693446892839?thread_ts=1720691531.557929&cid=C05LRS7G44R)
- fixed https://github.com/leather-io/extension/issues/4972

I'll test this extensively as I audit the headers in  https://github.com/leather-io/issues/issues/157

**Comment by pete-watters** [comment]
I made good progress here in https://github.com/leather-io/extension/pull/5671 , building on top of https://github.com/leather-io/extension/pull/5715 but I need to do more testing to make sure I don't introduce any un-expected issues. 

I'll get it finished ASAP

**Comment by pete-watters** [comment]
I've finished testing this and it is looking good. PR is in code review. 

Here is a demo:

https://github.com/user-attachments/assets/915e5b9a-c9f2-4434-a8d8-a836ff245f1e

I also updated the popup window to have a max width of 640px [as per](https://trustmachines.slack.com/archives/C05LRS7G44R/p1720693446892839?thread_ts=1720691531.557929&cid=C05LRS7G44R) . 

A suggested future improvement would be to also open the window a little taller as for the initial `SIGN MESSAGE` screen, the action buttons are always below the fold:
![Screenshot 2024-08-19 at 06 44 35](https://github.com/user-attachments/assets/5791d47c-940c-4b02-81c5-85877665fea8)

I can quickly make it look a bit better by removing top padding above the text? What do you think @fabric-8 @mica000 

![Screenshot 2024-08-19 at 06 46 28](https://github.com/user-attachments/assets/7709343b-b7cf-44da-b3cc-f4d043548a63)

**Comment by markmhendrickson** [comment]
> I can quickly make it look a bit better by removing top padding above the text?

I'd recommend against this, since the message content for signing itself has a variable height. So we wouldn't be fixing this for this view generally, across message lengths. If we want the actions to always show above the fold, there are more consistent solutions (e.g. absolutely positioning actions as fixed to bottom of viewport)

**Comment by pete-watters** [comment]
> > I can quickly make it look a bit better by removing top padding above the text?
> 
> I'd recommend against this, since the message content for signing itself has a variable height. So we wouldn't be fixing this for this view generally, across message lengths. If we want the actions to always show above the fold, there are more consistent solutions (e.g. absolutely positioning actions as fixed to bottom of viewport)

OK 👍 The bottom buttons for this screen aren't using the standardised absolutely positioned footer. I can refactor it so it's the same as PSBT but a potential issue with that is that there is more content below the buttons:
![Screenshot 2024-08-19 at 13 40 47](https://github.com/user-attachments/assets/78987b70-5fbc-4ec6-878f-2fb3074f4b23)

**Comment by markmhendrickson** [comment]
Let's not worry about improving this further for now. I believe a fixed footer will be applied to all signing variants with our new approval UX when we build it.
