### ISSUE TITLE
Unable to calculate fee (Bitcoin transaction)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5249]
This has been popping up since version 6.33.0

I saw this myself when I just updated to this version but it was gone a couple minutes later and I couldn't reproduce it. 
Two other user who experienced this also saw it resolved after a clear cache and refresh. 

A third user saw this on two computers, with two different networks and it persisted after clearing cache and refreshing. They even reinstalled the wallet with no change. I have asked them for console logs but they haven't shared those yet. I will add it here when they do. 

![image](https://github.com/leather-wallet/extension/assets/33360391/be1a0aca-c3bf-46d8-ba4d-45403ac0e1f3)

**Comment by alter-eggo** [comment]
@314159265359879  this should be fixed in 6.34.0

**Comment by alter-eggo** [comment]
@314159265359879 I believe this is no more relevant?

**Comment by 314159265359879** [comment]
This is confirmed fixed 👍🏼
