### ISSUE TITLE
Switching accounts and loading account name... displays wrong account name/number until reloaded

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5252]
See here I am on account 2, but it shows "account 1" as loading. 

![image](https://github.com/leather-wallet/extension/assets/33360391/65ac6f28-c2e4-4ef3-a16c-e63d74e9d5ce)

**Comment by 314159265359879** [comment]
Stacks is not even connected in this example, I don't know why it would try to load a BNS name, it wouldn't know the stacks address to check.

**Comment by fbwoolf** [comment]
This was fixed in: https://github.com/leather-io/extension/pull/5571
