### ISSUE TITLE
Ledger with extension sending inscriptions broken in version 6.34.0

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5253]
Steps to reproduce
1. Connect ledger with bitcoin app to leather extension
2. Hover over inscription to send
3. input address and click continue
4. select fee
6. see error: wallet confirm screen closes and you see a blank asset page

https://github.com/leather-wallet/extension/assets/33360391/835d3657-67c8-4e76-bc65-4066099e6f2d

**Comment by pete-watters** [comment]
I fixed this and am testing it right now.
