### ISSUE TITLE
Fix submit button styling in dark mode for feedback form

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5259]
Currently it's washed out:

<img width="406" alt="Screenshot 2024-04-15 at 09 59 06" src="https://github.com/leather-wallet/extension/assets/28991/eebfd925-eed1-4ef9-99fd-f2c513afb261">

**Comment by pete-watters** [comment]
I checked this and it seems this specifically happens when we have Leather set to a different mode than the users system. 

E.g. if the users sets Leather in Dark mode but the system is different. 

We are using the system setting in the sentry config.
