### ISSUE TITLE
Fix formatting of "Show hash" area for arbitrary message signing

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5261]
The arrow and text are misaligned vertically

<img width="454" alt="Screenshot 2024-03-25 at 11 12 45" src="https://github.com/leather-wallet/extension/assets/28991/23755062-6375-4eeb-8701-a692ba500036">

**Comment by pete-watters** [comment]
I can fix this pretty quickly. Do you know how we want to align the text? 

I can have it centered or stretching? 

https://github.com/leather-wallet/extension/assets/2938440/4bb7b0a2-b141-4e86-af91-bef62d8db58e

**Comment by pete-watters** [comment]
I opened a PR changing it to be like this:
![Screenshot 2024-04-19 at 13 05 57](https://github.com/leather-wallet/extension/assets/2938440/6a0f12c4-6ae0-4685-ac66-31ed2b4382f8)

I'm not sure if thats exactly what we want but it fixes the misalignment at least.
