### ISSUE TITLE
"Unexpected Application Error" after updating Chrome

### ISSUE THREAD

**Issue by ryujjam** [blockstack/blockstack-app#5266]
![image](https://github.com/leather-wallet/extension/assets/104407661/dffb669e-42e9-4f64-937a-22a13b815cb1)

After updating my Chrome browser, Leather extension doesn't work well.

I uploaded the screenshot.

**Comment by pete-watters** [comment]
Thanks for reporting @ryujjam . This is something we are aware of and will have a fix available soon

**Comment by pete-watters** [comment]
@ryujjam this issue is now resolved in the latest release. Let me know if you are still having issues.
