### ISSUE TITLE
Seeing reports of "insufficient funds" error when trying to make a bitcoin transfer transaction

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5267]
In most cases when we see this it is due to an addresses having only small UTXO's and they can't be send out economically. Adding a single UTXO to a transaction means you add about 68 vB to a transaction (minimum depends on script type) so at current rates 50 sats/vB it will cost you about 3500 sats to include any UTXO. And a transaction typically has a size of 140-200 vB if not more

The wallet is confirmed to have sufficiently large UTXO to cover this transaction. Although I also see several much smaller UTXO's in this wallet. Current fee rate is high so it is possible that those can't be send out cost effectively. 

![image](https://github.com/leather-wallet/extension/assets/33360391/d8c706a2-4348-40ec-bd33-c82c628e16a7)

![image](https://github.com/leather-wallet/extension/assets/33360391/08f5dad3-da03-4e09-8dd5-12bdcd09975e)
bc1q8dzvunhlz63pfr4ts64r3ls6h2qljjyl9q0v7a
![image](https://github.com/leather-wallet/extension/assets/33360391/3b579fb8-4cf1-4bde-981a-b2ea2fe6c92d)

![image](https://github.com/leather-wallet/extension/assets/33360391/7cf903e2-6d0e-4834-bd15-9a97af21f5f6)

**Comment by 314159265359879** [comment]
![image](https://github.com/leather-wallet/extension/assets/33360391/8715c4a7-7d8c-457e-9d5b-fed405a11b50)

**Comment by 314159265359879** [comment]
Seeing more reports like this. Another wallet with sufficiently large UTXO's, I confirmed seeing this in 6.34.0 (extension with Ledger) but not in 6.35.0 with ledger. 
![image](https://github.com/leather-wallet/extension/assets/33360391/66d550e2-1008-4c34-aacd-58e3ad8a28dd)

When I click that link in the error I get a HTTP error 450 visiting this:
`https://[o4504203991318528.ingest.sentry.io](https://o4504203991318528.ingest.sentry.io/api/4504204000952320/envelope/?sentry_key=21db7427cf1f4681885f4e20451abf8e&sentry_version=7&sentry_client=sentry.javascript.react%2F7.106.0)/api/4504204000952320/envelope/?sentry_key=21db7427cf1f4681885f4e20451abf8e&sentry_version=7&sentry_client=sentry.javascript.react%2F7.106.0`

**Comment by 314159265359879** [comment]
There is something wrong with coin selection the particular wallet had one big UTXO about 0.0083 BTC and 20 smaller 600 sat UTXO's it should have no problem sending the 0.0082 out with a fee of about 7000 sats. But all it will do is send out less with a much higher fee 50k sats. That tells me it is selecting the smaller UTXO's first here. 

Tested my assumption that the big UTXO could be send with lower fee, leave more with sparrow where I can select the UTXO's manually and that proved correct. (selecting the 0.0083 UTXO and sending just that one was possible with a 7000 sat fee and high priority). 

What is causing this?

**Comment by kyranjamie** [comment]
Investigating, though quietly hope that the changes to coin selection have improved the situation.

I wonder if the situation might be such that, if the user wants to spend nearly all of their 1 sufficiently-sized UTXO, then we calculate they need another, but, because they're all uneconomical, we say it isn't possible.

@314159265359879 please let me know if we see this situation arrise again in the next week or so, when the fee fixes are live

**Comment by 314159265359879** [comment]
@DeeList and I will keep an eye on this.

**Comment by markmhendrickson** [comment]
I'm closing as stale.
