### ISSUE TITLE
Extension errors about action commands and third-party cookie notice

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5276]
These errors pop up for a user. 
<img width="424" alt="GLeB8YfWoAAfsF5" src="https://github.com/leather-wallet/extension/assets/33360391/8cc2cf9f-a492-47a4-b381-3bbcf12d7399">

![image](https://github.com/leather-wallet/extension/assets/33360391/eff33bb1-0663-4109-96b8-286a73037460)

**Comment by kyranjamie** [comment]
These are warnings only, they don't impact the wallet in any way
