### ISSUE TITLE
[Bug] Redirect back to action

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5279]
User is sent to homepage immediately after signing in, rather than the _Connect Account_ page.

As shown in video, when the wallet is signed in already, it opens on the correct page.

In resolving this bug, a test must be written that ensures, when signing in, the user is redirected to the correct page

https://github.com/leather-wallet/extension/assets/1618764/f25e6caf-b9b7-4216-aabd-3da149f7928d

**Comment by markmhendrickson** [comment]
Dupe: https://github.com/leather-wallet/extension/issues/5066
