### ISSUE TITLE
v.6.35.1 last 3 wallet addresses not shown in GUI

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/blockstack-app#5282]
I have a wallet with 20 addresses.  The last 3 or 4 in the list don't show up.
Using Xverse web wallet they show up.
This just started happening today.  Worked fine before.
Using Chromium on Linux: Version 124.0.6367.60 (Official Build) (64-bit)
Locking and logging back in doesn't fix the issue.

**Comment by pete-watters** [comment]
Thanks @fluidvoice, I'll check this

**Comment by pete-watters** [comment]
This is the same issue as https://github.com/leather-wallet/extension/issues/5242 . I'll fix it there
