### ISSUE TITLE
`sendTransfer` should default to `mainnet` if no `network` provided

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5284]
`sendTransfer` request should default to `mainnet` and not be required. 

We need to be very careful as making changes to APIs, as for any apps using `sendTransfer` without defining a network, relying on our default, would have broken with this change.

**Comment by markmhendrickson** [comment]
Note the API parameters will need updating [here](https://leather.gitbook.io/developers/bitcoin-methods/sendtransfer#parameters) in the docs to indicate this default once available.
