### ISSUE TITLE
Firefox disable "use ledger" button

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5287]
Use Ledger button should be disabled on Firefox because ledger is not supported there
![image](https://github.com/leather-wallet/extension/assets/33360391/794e3651-c7a8-485f-b9d2-66482845db3c)

**Comment by pete-watters** [comment]
I started working on this as it seemed like a quick fix but @kyranjamie  helped me by pointing out we already have a screen for this that says 'Unsupported Browser' when users choose this 

![Screenshot 2024-06-28 at 10 51 34](https://github.com/leather-io/extension/assets/2938440/b88fc001-5fa4-42bc-ac2b-1ef543566584)

We also don't support Firefox
