### ISSUE TITLE
Cannot scroll settings menu in action popup

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#5298]
When the action popup is open, it's not supporting scroll. 

This means that on a fresh install, you can't scroll to `Sign out` until you hit `X` on the survey

<img width="402" alt="Screenshot 2024-04-23 at 15 41 00" src="https://github.com/leather-wallet/extension/assets/2938440/f4a3e689-970d-453e-8fc5-82df6924a21f">

**Comment by mica000** [comment]
Thanks for flagging this @pete-watters - What would you expect to happen in this case? 
Should the page scroll or should the content on the menu scroll?

**Comment by pete-watters** [comment]
@mica000 I can try and get the menu to scroll? Then they could sign out without having to first decline the survey. 

When the menu is open in any scenario the page doesn't scroll, even on large sizes. Would you prefer if users can always scroll down when the menu is open? In that case it would be better to fix it so the full page can scroll
