### ISSUE TITLE
Unable to scroll and select last accounts

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#5310]
I was able to reproduce this issue after adding 15 accounts. Unable to scroll and select past account 9. 

Reported using 6.35.1 - Chrome browser.
https://discord.com/channels/621759717756370964/745197302255321108/1232730207807344755

![image1](https://github.com/leather-wallet/extension/assets/132958967/9dc7ca1d-aa08-44c1-8138-af8ce635c620)
![image2](https://github.com/leather-wallet/extension/assets/132958967/c4418b78-5aca-4f67-a13c-82476fe7c93f)
![image3](https://github.com/leather-wallet/extension/assets/132958967/e8377d5c-b3b5-4063-9b8b-ec91edd37145)

**Comment by DeeList** [comment]
The issue appears after adding 15 accounts in Chrome.

![accounts](https://github.com/leather-wallet/extension/assets/132958967/fb4624a3-0927-421e-acdc-f4b4bb03d32b)

**Comment by pete-watters** [comment]
This is the same issue as https://github.com/leather-wallet/extension/issues/5242 and will be solved soon in the latest release

**Comment by pete-watters** [comment]
This fix was released
