### ISSUE TITLE
Type for window.LeatherProvider

### ISSUE THREAD

**Issue by SakthiVelRajan-dev** [blockstack/blockstack-app#5314]
I am working on typescript in next js. In that project, I need to define a type for LeatherProvider in global.d.ts. currently, am using any type for define a LeatherProvider type. Is there any specific type instead of any type

**Comment by markmhendrickson** [comment]
Does [this documentation](https://leather.gitbook.io/developers/overview/typings) help? 

cc @kyranjamie

**Comment by SakthiVelRajan-dev** [comment]
I've consulted the document and followed the instructions to implement the solution, but I encountered some issues. Please see the attached screenshots for reference.


![image](https://github.com/leather-wallet/extension/assets/22374175/fe278f5a-9ce9-41f9-a4f6-cf0832f50cb6)


In the getAddress response, I got only id and jsonRPC as type. But in my console, I got id, jsonRPC and Result as Object. I think response success or failure object is not added in type. Can you please validate from your side also

![Screenshot from 2024-04-25 13-01-47](https://github.com/leather-wallet/extension/assets/22374175/3a015e87-ea5e-41e6-adea-5554091903b3)


CC: @markmhendrickson

**Comment by markmhendrickson** [comment]
Thanks, @SAKTHIMAGESH! It's best that @kyranjamie follows up in regards to your observation since he'd know best.

**Comment by kyranjamie** [comment]
Helpful report, thanks. Will be fixed soon.
