### ISSUE TITLE
Add email form for support and feedback

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5325]
Proposed solution after discussion: https://www.notion.so/trustmachines/Triage-support-inquiries-and-product-feedback-efficiently-a934773d790140109de7166d91086319

This requires design and can then be added. 

related https://github.com/leather-wallet/extension/issues/4747

**Comment by markmhendrickson** [comment]
Replacing with a task [here](https://app.asana.com/0/1205498919873637/1207107122469138/f)
