### ISSUE TITLE
Odd reloading behavior of activity tab custom testnet vs mainnet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5326]
This is on the nakamoto testnet so not necessarily similar to the mainnet but it does illustrate something I am also seeing on mainnet. Whenever more data is loaded or updated the whole activity tab goes into loading. 

I expect new data to be loaded I don't expect all the history that is already loaded to vanish meanwhile. 

https://github.com/leather-wallet/extension/assets/33360391/eb4139ce-8af9-449c-8cd3-3ae7aae7a7f2

Note that in this case bitcoin is still configured to mainnet api's because with this custom testnet it wouldn't save the settings otherwise. 

On mainnet we wait for the initial load
![image](https://github.com/leather-wallet/extension/assets/33360391/da6e3164-4efd-4663-9afe-8e0194849df7)

Then when I do something else for a while and return to the wallet, click the extension. I often see this again. 

![image](https://github.com/leather-wallet/extension/assets/33360391/9a1241c1-50d8-44aa-8c19-f47444d9803d)

This is on version 6.36.0

@markmhendrickson

**Comment by 314159265359879** [comment]
You can also see this on mainnet when switching between accounts, this can take a couple seconds... sometimes it takes a minute or more (I think it is longer when the wallet is throttling). 

![image](https://github.com/leather-wallet/extension/assets/33360391/8b3ebf2d-fcad-4f8f-85a2-0aed8d542128)

**Comment by alter-eggo** [comment]
@314159265359879 couldn't reproduce, is this still relevant?

**Comment by 314159265359879** [comment]
The custom testnet had very rigorous api limits, which likely played a role, I have not seen this recently, closing this
