### ISSUE TITLE
Nakamoto testnet activity links to regular testnet when clicked.

### ISSUE THREAD

**Issue by muthusleuths** [blockstack/blockstack-app#5328]
Performing test transactions in Nakamoto testnet and when clicking on a transaction in Leather wallet browser extension it takes you to regular testnet and throws a 404 not found. The transaction is available on the nakamoto testnet. 

https://github.com/leather-wallet/extension/assets/115091323/b72225aa-b29d-41a5-948c-0e2b738c4fae

**Comment by markmhendrickson** [comment]
Thanks for reporting! We're tracking the enhancement [here](https://github.com/leather-wallet/extension/issues/5123) so I'll close this particular issue 🙏
