### ISSUE TITLE
Investigate insufficient fee error sending inscription

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5330]
Currently hitting this error  `Insufficient funds to cover fee. Deposit some BTC to your Native Segwit address.`

**Comment by markmhendrickson** [comment]
Related or dupe? https://github.com/leather-wallet/extension/issues/5267

**Comment by kyranjamie** [comment]
I think this is a different issue entirely.

**Comment by markmhendrickson** [comment]
@kyranjamie is this issue still outstanding given the above commits?

**Comment by kyranjamie** [comment]
I think this might've been a development-time error I was running into, closing
