### ISSUE TITLE
Broken Stacks high fee warning

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5362]
Investigating #5361 revealed that our high fee warning isn't working for Stacks chain transfers. 

This also prevents users from submitting a custom fee transaction, as they're unable to submit the form.

**Comment by 314159265359879** [comment]
Workaround for users running into this
Set a fee below 5 STX, then increase the fee afterwards if you want a fee to be set higher than 5 STX anyway. 

Steps to reproduce
1. Create a transaction: send STX via Leather or a swap on app.alexlab.co for example
2. Set custom fee to 5.1 STX
3. See error: Continue/confirm button can't be clicked.
