### ISSUE TITLE
Account name is wrong in Ledger Bitcoin only mode

### ISSUE THREAD

**Issue by alter-eggo** [blockstack/blockstack-app#5374]
Account index on home page doesn't match that one from switch acc dialog
![Screenshot 2024-05-15 at 17 50 24](https://github.com/leather-wallet/extension/assets/46521087/a2c446af-9ad0-4a68-a3b8-6db340f8dbd7)

**Comment by fbwoolf** [comment]
This was fixed in: https://github.com/leather-io/extension/pull/5571
