### ISSUE TITLE
Switching accounts, starts loading, and then the wallet can throttle making the user wait for balances to load

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5395]
The user reporting this said 
_I see this when I switch using my wallet, scroll over 10 or a hundred addresses then select the address I need and... I have to wait a couple minutes before I can see the balances:_

https://github.com/leather-wallet/extension/assets/33360391/7a46ab9d-a2b1-46a9-a550-ffca51876bd0

We expect the BNS name to be loaded first, that is what we see here, and then the Stacks and Bitcoin balance. When it is slow like this, typically it is due to the wallet throttling so it doesn't hit the current API limits. 

Related: https://github.com/leather-wallet/extension/issues/5326

**Comment by markmhendrickson** [comment]
@alter-eggo might more robust request cancellation (in which we cancel some or all calls needed for the account switcher popup when it's closed) help with this issue?

**Comment by alter-eggo** [comment]
@markmhendrickson not sure here, you can see from the video [in this pr](https://github.com/leather-wallet/extension/pull/5366) that all requests related to balances are cancelled

**Comment by alter-eggo** [comment]
can we setup lots of accounts in our dev wallet? this will help a lot in working/testing

**Comment by DeeList** [comment]
This user support case, unable to transfer $NOT and experiencing load delays/balance display seems related

UPDATE: Seeing additional reports that fees are not loading for other tokens. 

<img width="481" alt="slow" src="https://github.com/leather-wallet/extension/assets/132958967/da94f9ae-430b-40fa-afe1-61a796f7c6c0">

![slow3](https://github.com/leather-wallet/extension/assets/132958967/5ebc1393-eb7a-40d3-adc4-7d5f282d4665)

**Comment by DeeList** [comment]
A few issues reporting this error I believe could be related to account delays or throttling, as it seems to eventually work and is no longer reported - possibly their wallet completes loading?.

![slow2](https://github.com/leather-wallet/extension/assets/132958967/d2eaa341-9170-4a28-bce1-47b68ece3c76)

**Comment by pete-watters** [comment]
> can we setup lots of accounts in our dev wallet? this will help a lot in working/testing

I added an account called `Multi Account Wallet` you can find it in our shared login

**Comment by 314159265359879** [comment]
> can we setup lots of accounts in our dev wallet? this will help a lot in working/testing 

I gave the dev wallet 123 accounts with STX balance and about 90 have a BNS name.

You can always use debug.setHighestAccountIndex() to reveal more or less

**Comment by markmhendrickson** [comment]
With latest build, may still take up to 1 minute to switch accounts
