### ISSUE TITLE
Fix hover effect for disabled button

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5406]
Currently, disabled buttons show a dark hover effect when a lighter one is expected (in light mode):

https://github.com/leather-wallet/extension/assets/28991/83b9203e-3a0b-49ac-ab61-8007598ce214

**Comment by antoinefamibelle** [comment]
@markmhendrickson Hi, I would like to contribute to your project by fixing this little issue.
I've looked at the contribution of Jeeanribeiro to avoid to commit the same solution.
I've been able to fix this issue by disabling the hover effect on the button whenever its disabled but I saw that you would like an hover effect to be lighter than the normal state. Do you want me to keep my solution of disabling the hover effect on a disabled button or do you want me to rework it to make the color a bit lighter if so can you please provide a precise color code.
Best Regards,

Antoine

**Comment by markmhendrickson** [comment]
@fabric-8 any input on the above? 🙏

**Comment by fabric-8** [comment]
Thx @antoinefamibelle! Removing the hover effect for disabled elements makes absolute sense

**Comment by antoinefamibelle** [comment]
#5448 Hi, I've managed to disabled every animation on hover of a disabled button.
