### ISSUE TITLE
Sending SIP010 tokens blocked because fee doesn't load

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5415]
Reproduce by
1. Clicking send in the wallet
2. Select a SIP010 token
3. See error, fee not loading

It doesn't stop showing the loading animation, and the fee never loads. 

https://github.com/leather-wallet/extension/assets/33360391/5cc40797-d356-461a-83e8-6d5a38876d3e

I expect the fee to load... and 
When the fee can't be loaded within 3(?) seconds how about showing a warning about and setting a low fixed fee (0.003 STX) so the user can proceed beyond this point?

**Comment by dabuchera** [comment]
Looks like the segment.io API is causing that.
