### ISSUE TITLE
Fix title alignment for sign out

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5419]
It's offset to the left too much

![Image](https://github.com/leather-wallet/extension/assets/28991/ee7b3ad3-e5c7-4e02-9ef0-743f1f593cad)

**Comment by antoinefamibelle** [comment]
@markmhendrickson 
Hi, I would like to contribute by helping you on this issue.
Changing the offset of this title would result on changing the alignment of every part where the component DialogHeader is called. I would like your approval before updating it and doing my commit.

Best regards,

Antoine

**Comment by pete-watters** [comment]
Hi @antoinefamibelle , 

Thanks for offering your help. Please contribute and change the alignment for all `DialogHeader`. 

If there is a title the text needs to be centered.

**Comment by markmhendrickson** [comment]
+1 on @pete-watters's guidance 🙏
