### ISSUE TITLE
Account name doesn't update, shows "account 1" when switching between accounts.

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5449]
I see this while connected to Ledger device, Account 1 is always displayed even when switched.  And it looks related to being only connected to Bitcoin.
When I also connect Ledger to Stacks I do see the Account number/Name changing. 

It probably has something to do with one of the Throttling/loading related work for which the order was changed when we loaded things. Account names are checked first, but they are checked for BNS names (on Stacks). They are not checked for names when only Bitcoin is connected, but they should still update the account number.  @alter-eggo 

https://github.com/leather-wallet/extension/assets/33360391/b99e7eb7-117d-4a4b-a614-b39089dbc75d

**Comment by alter-eggo** [comment]
will look into it, I feel like I fixed it once, not sure why this bug happens again, will write test as well

**Comment by fbwoolf** [comment]
This was fixed in: https://github.com/leather-io/extension/pull/5571
