### ISSUE TITLE
UI bug with submitted txs

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#5451]
Saw this today...

<img width="952" alt="Screenshot 2024-05-24 at 1 08 34 PM" src="https://github.com/leather-wallet/extension/assets/6493321/3bb4d748-9fdf-4874-bcb1-15f074aa4bef">

**Comment by markmhendrickson** [comment]
Tracked here: https://github.com/leather-wallet/extension/issues/5070
