### ISSUE TITLE
Regression in Runes formatting

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#5452]
I'm seeing some slight regression with Runes formatting after the latest update. It's great that they are back, but they are no longer showing their symbol next to the amount. When you roll over to see the actual number, it's also not taking decimals into account so displaying as a bigger whole number than it actually is.

![image](https://github.com/leather-wallet/extension/assets/122313287/e396ac14-d301-46bd-a3c1-0b7f083ff408)

**Comment by 314159265359879** [comment]
@brandonmarshall-tm are you seeing this in the latest version of the wallet or is this a user?
Any chance the wallet is outdated.

In the latest version 6.41.1 I see decimals displayed correctly
![image](https://github.com/leather-wallet/extension/assets/33360391/49adc498-9c9b-465c-a9be-c4c73cdb2732)
