### ISSUE TITLE
STX-20 Hide 0 balances

### ISSUE THREAD

**Issue by dabuchera** [blockstack/blockstack-app#5457]
Hi

It would be nice to hide STX-20 tokens where the balance is 0.
Right now they are showed and clogging a bit the view.

![image](https://github.com/leather-wallet/extension/assets/53481997/2c53d44c-8aa1-4f2c-805e-d24b20efe816)

**Comment by 314159265359879** [comment]
Thanks for the suggestion! that is a good idea.

**Comment by brandonmarshall-tm** [comment]
Duplicate issue here: https://github.com/leather-wallet/extension/issues/5384
