### ISSUE TITLE
Update Panda to latest version

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5461]
@pete-watters maybe you can take this on as well while you're in 🐼  land 

Following along with [Panda's changelog](https://github.com/chakra-ui/panda/blob/main/CHANGELOG.md), there are some nice features coming out

**Comment by pete-watters** [comment]
Sure thing, I'll update it

**Comment by pete-watters** [comment]
I opened a PR to update panda in the extension. I will update it in the mono-repo as part of https://github.com/leather-wallet/issues/issues/83
