### ISSUE TITLE
Remove double gap above view more/fewer

### ISSUE THREAD

**Issue by fabric-8** [blockstack/blockstack-app#5469]
There's currently a double gap above the view more / fewer button in the asset list. That's because there's a 0-height div in between of which I'm not sure why it's there 🤷‍♂️

![Image](https://github.com/leather-wallet/extension/assets/4112698/709952b3-2607-4a8e-ae6b-801888702680)

**Comment by pete-watters** [comment]
This was merged and will be in the next release
