### ISSUE TITLE
Add new bitcoin testnet when it is ready

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5491]
I see a notice on the testnet explorer that testnet3 will be replaced
https://mempool.space/testnet/tx/40c6a9ca8ad6f1c6a9ae054f6dc608e64e1083003c12960422ad7a44c9252d59
![image](https://github.com/leather-wallet/extension/assets/33360391/5e5acaee-f23e-4b4c-a8a1-a86c64cae9cd)

It has been unreliable due to blockstorms. 

Testnet4 is not yet ready and can still be reset
https://mempool.space/testnet4
![image](https://github.com/leather-wallet/extension/assets/33360391/a21ea50a-927f-4744-ace2-22332b8de3ef)

We should also address this: https://github.com/leather-wallet/extension/issues/5228
Would it make sense to show users two network selection buttons instead of one?
Stacks network: Mainnet, Publid regtest, Nakamoto prelaunch, Local
Bitcoin network: Mainnet, Testnet3, Testnet4, Signet, etc.

**Comment by kyranjamie** [comment]
This has been done as part of some other work
