### ISSUE TITLE
No manifest.json in the source files

### ISSUE THREAD

**Issue by cryptodescriptor** [blockstack/blockstack-app#5526]
As title states, I am trying to run from source and there's no manifest.json in the folder.

**Comment by kyranjamie** [comment]
```
❯ ll leather-chromium-v6.42.1 | grep manifest.json
.rw-r--r--@ 1.6k kyranjamie 17 Jun 17:19  manifest.json
```

There is in the release build output. If you're trying to build from source, run `pnpm dev` and it'll build the manifest.
