### ISSUE TITLE
Fix problem with popup width in dev build

### ISSUE THREAD

**Issue by cbadawi** [blockstack/blockstack-app#5565]
I'm loading the extension from dev branch latest.

<img width="170" alt="Screenshot 2024-06-21 at 11 10 06 PM" src="https://github.com/leather-io/extension/assets/55446273/96f52f69-72cb-4799-858d-fc75c097fcfc">

**Comment by 314159265359879** [comment]
@cbadawi thanks for sharing, that is a new one. I see you are using a developer build of the wallet (inverted icon). Could you share the version this is related to?

**Comment by cbadawi** [comment]
@314159265359879  v6.42.1 Latest

**Comment by markmhendrickson** [comment]
Is this issue happening with the same version of the production build via Chrome Web Store for you as well? Or just the dev build, and are there any console errors if so?

**Comment by Aman-zishan** [comment]
I ran across this problem too, was working on #5533 . @markmhendrickson there were no console errors. Except a warning
<img width="684" alt="Screenshot 2024-06-24 at 3 41 22 PM" src="https://github.com/leather-io/extension/assets/55238388/7f125b4c-7762-4a68-a866-0b0136dc73e3">

**Comment by cbadawi** [comment]
> Is this issue happening with the same version of the production build via Chrome Web Store for you as well? Or just the dev build, and are there any console errors if so?

@markmhendrickson  just dev, no console errors. its just a minor css problem,  `mode__popup` in `theme/global/global.ts` needs a `width` or a `minWidth` property

**Comment by kyranjamie** [comment]
This might've been introduced with the change I just made, though I thought that was being applied to only the popup window.

@Aman-zishan it is unrelated to this manifest warning
