### ISSUE TITLE
PSBT with runes, inputs seem displayed with incorrect units

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5566]
Original convo https://discord.com/channels/621759717756370964/745197302255321108/1253414727695077427
They also reached out to @markmhendrickson directly, perhaps has more context to share. 

In this example
1000 BTC is displayed but the UTXO is 546 sats, it is a 1000 Runes. 
![image](https://github.com/leather-io/extension/assets/33360391/3a528eff-439a-48c2-8f19-00a96d06aa4b)

And this is what is displayed for signing (note fee)
![image](https://github.com/leather-io/extension/assets/33360391/8ccb50f3-54a9-47cc-810d-42f0557e17f3)

**Comment by markmhendrickson** [comment]
The dev has indicated now that this was a result of erroneous PSBT construction on their end.
