### ISSUE TITLE
Filter URLs from display of token metadata

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5589]
To prevent phishing URLs from displaying as part of malicious airdrops

**Comment by pete-watters** [comment]
I double checked this and we already have code to filter out URLs from token names and captions:
- https://github.com/leather-io/extension/pull/4295
- https://github.com/leather-io/extension/pull/4318 

Right now the code removes anything that looks like a URL. You can see the test cases in here:
https://github.com/leather-io/mono/blob/dev/packages/utils/src/spam-filter/spam-filter.spec.ts 

We match anything beginning with `https://` , `http://`, `ftp://` or containing `.com`. 

That will block us displaying `zsstx.com`. 

@markmhendrickson @314159265359879 - Does this suffice or do you want me to add specific handling of `bitflow.fund`? That will show if it is a normal string without a url path but users would need to select it and paste it into their browser. 

- Did we get a specific report of this issue in Leather? 
- Do you want me to add code to blacklist these two tokens as suggested in https://x.com/megapontnft/status/1807328780760879557?s=46&t=r3QgOd7NEYbkf4eSWxrM8Q ? 
    - Show `zsstx` and `bitflow` as unknown tokens?

**Comment by markmhendrickson** [comment]
I suspect we could match anything with a dot (`.`) in it safely, on the assumption that these indicate domains / URLs, since token names and tickers don't generally have them. @314159265359879 wdyt?

> Do you want me to add code to blacklist these two tokens

It's best we don't, given the operational and centralization concerns. [See thread](https://trustmachines.slack.com/archives/C05234EMBUL/p1719830908540549?thread_ts=1719744467.635279&cid=C05234EMBUL)

**Comment by pete-watters** [comment]
Based on discussions on our standup, we want to implement this in a better way but don't have a clear plan for this. 

For now I will:
- update the spam filter to catch any token names / symbols containing any `.` 
- change our replacement string from `Unknown token` to `Suspicious token` 

On the design side the preferred route is to add a warning icon and keep the token name but this will need more work from both product and design

**Comment by pete-watters** [comment]
Upon testing our existing code, its better than I thought so we are already protected against this now and are filtering any tokens with a  `.` in their name or symbol. 

I opened a small PR anyway to:
- change the text from Unknown to Suspicious
- add an explicit test case to show we filter these urls
https://github.com/leather-io/mono/pull/255

We can get this released but we are already safe against this in production
