### ISSUE TITLE
Add a token details page

### ISSUE THREAD

**Issue by cbadawi** [blockstack/blockstack-app#5602]
Sometimes when I get airdropped token I would like to investigate its contract, token supply etc. (can potentially add socials links). Adding a token page when a user clicks on a token would be helpful.

Some minor refactoring would have to be made to make sure the `interactive` variant doesnt break things. 

Adding here the phantom token details page as an example.
<img width="359" alt="Screenshot 2024-07-04 at 10 44 01 AM" src="https://github.com/leather-io/extension/assets/55446273/59dea6ff-1b5d-43a3-94e8-2afb2b608944">
<img width="353" alt="Screenshot 2024-07-04 at 10 44 07 AM" src="https://github.com/leather-io/extension/assets/55446273/f21a3eb6-377f-4eee-87f8-b787c281d52f">

**Comment by cbadawi** [comment]
Happy to work on this. A figma design would be helpful.

**Comment by markmhendrickson** [comment]
Good idea, though filed here already so I'll close it out in favor of the existing one: https://github.com/leather-io/extension/issues/4660

The team designers expect to address this soon as they redesign the overall tokens UX. They can provide guidance on that issue once available.
