### ISSUE TITLE
Display Brc20 & Rune prices

### ISSUE THREAD

**Issue by cbadawi** [blockstack/blockstack-app#5603]
You might need a backend proxy, a DB, a caching mechanism etc ... for this to hide the API key of the prices provider.

It might be a big task but I think it would really boost the user experience (mine at least :) ).

again, happy to work on this.

**Comment by markmhendrickson** [comment]
I believe this data is all provided by the Best in Slot API, which is already integrated so it'd be a matter of adding support for the relevant endpoint: https://docs.bestinslot.xyz/reference/api-reference/ordinals-and-brc-20-and-runes-and-bitmap-v3-api-mainnet+testnet+signet

**Comment by cbadawi** [comment]
Nice. I can give it a go after the manage-tokens pr merges.

**Comment by brandonmarshall-tm** [comment]
BRC20 prices were previously supported but a later update broke it, should be back up soon: https://github.com/leather-io/extension/issues/5626

Fiat value for Runes we have an existing request here: https://github.com/leather-io/extension/issues/5300

Runes is a highly requested feature! Would love to see this happen.

**Comment by markmhendrickson** [comment]
I'm closing out this issue in favor of the others linked above.
