### ISSUE TITLE
WBIP Web Providers compatibility

### ISSUE THREAD

**Issue by kilianmh** [blockstack/blockstack-app#5615]
Leather is part of [WBIP](https://wbips.netlify.app/) but is
not pushed on the `window.btc_providers` array.  
The Xverse extension does it.
See [WBIP004 — Web Providers](https://wbips.netlify.app/wbips/WBIP004).

Is this intended or a missing feature?

**Comment by kyranjamie** [comment]
Thanks for the reminder @kilianmh
