### ISSUE TITLE
BRC-20 USD balances no longer appearing

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#5626]
It looks like BRC20 USD balances are no longer displaying in Leather, tested this on multiple wallets.

![Screenshot 2024-07-08 at 8 54 05 AM](https://github.com/leather-io/extension/assets/122313287/ce531793-227d-47ca-b335-84b34f8ffdaa)

![Screenshot 2024-07-08 at 8 54 45 AM](https://github.com/leather-io/extension/assets/122313287/25a21b8d-8be4-4589-9fd7-b5e014ad9171)

**Comment by DApps-Representative** [comment]
> It looks like BRC20 USD balances are no longer displaying in Leather, tested this on multiple wallets.
> 
> ![Screenshot 2024-07-08 at 8 54 05 AM](https://private-user-images.githubusercontent.com/122313287/346632612-ce531793-227d-47ca-b335-84b34f8ffdaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTc1ODYsIm5iZiI6MTcyMDYxNzI4NiwicGF0aCI6Ii8xMjIzMTMyODcvMzQ2NjMyNjEyLWNlNTMxNzkzLTIyN2QtNDdjYS1iMzM1LTg0YjM0ZjhmZmRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMzE0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDc3MmJmNWUxMjk4NTg0YWUxOTU0MGEwM2M0ZjczNTU1N2FkZWNjZWU0MzRjNDc2Y2Q2ZWM3MDU0ZGNjMTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xfOJy5keQCSHGvhc5JzHv8fJBk_V6sEegkAc-hEF1Jk)
> 
> ![Screenshot 2024-07-08 at 8 54 45 AM](https://private-user-images.githubusercontent.com/122313287/346632849-25a21b8d-8be4-4589-9fd7-b5e014ad9171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTc1ODYsIm5iZiI6MTcyMDYxNzI4NiwicGF0aCI6Ii8xMjIzMTMyODcvMzQ2NjMyODQ5LTI1YTIxYjhkLThiZTQtNDU4OS05ZmQ3LWI1ZTAxNGFkOTE3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMzE0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGJiNmRmYjZjMmRkYTRiMGI0NTcxNzFlNjY0N2U4ZjNkZWJlNzc0Zjk1YmRiYzE1ZDJlZjRlMjFkYmZlMzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iInIKWOJ6iU46Ellu8YEcBuKBwqnylJdgVfIsldP0PE)

Hey there @brandonmarshall-tm !

Thank you for reaching out! kindly refresh your wallet, if the issue persists,then your query would be best dealt with by Leather Wallet support team.
 I’ll have to refer you to the official support Team with the ticket ID LED7463
 
Please see the link below to our dedicated support line: 
 [Leather  Wallet Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.
