### ISSUE TITLE
Loading activity tab, users wait for data to load

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5651]
We're seeing more of this
![image](https://github.com/user-attachments/assets/79e482f3-3be7-47df-890c-02152fb7d521)

It looks about the same in the build with enhanced throttling, it takes upto a minute for anything to get displayed. In the current build, (6.42.2) it can take longer. 

I don't think it should show any history at all when downloading the latest. It should look more like there is something loading at the top while displaying everything that was already loaded. 

Related thread and video https://trustmachines.slack.com/archives/C069V6G48F7/p1720813477811579?thread_ts=1720806080.553669&cid=C069V6G48F7

**Comment by brandonmarshall-tm** [comment]
I will add this happens if I have simply not opened Leather in a few days. Not when switching accounts or logging out. Just after a bit of inactivity.

**Comment by markmhendrickson** [comment]
Related: https://github.com/leather-io/extension/issues/5175

**Comment by alter-eggo** [comment]
problem with waiting for activity list to show is in blockstream. on the screenshot request for our dev wallet taproot address txs list.
we save request response, but on initial load some active users with lots of inscription txs will need to wait
query options for `useGetBitcoinTransactionsByAddressesQuery`:
```
const queryOptions = { staleTime, gcTime: Infinity, refetchInterval: staleTime };
```
![Image](https://github.com/user-attachments/assets/88d1f6b9-2185-4c43-bcd1-cfce20bc9f40)

**Comment by markmhendrickson** [comment]
Fixed with https://github.com/leather-io/extension/pull/5690
