### ISSUE TITLE
Users want an option to see more transaction history in the wallet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5672]
I am only seeing the last 50 stacks transactions in the Leather activity tab. In a lot of cases that is likely enough but sometimes a user will want to view more of their history.

![image](https://github.com/user-attachments/assets/928acbba-6c22-45b7-a727-3efa50c252a1)

a. Can we load more in Leather, with the push of a button or as the user scrolls down?

b. If not can we display a button "see more history" (and direct to [Stacks explorer](https://explorer.hiro.so) for their Stacks address history or [Bitcoin explorer](https://mempool.space) (native segwit or taproot address?)?)

**Comment by Kerrypinny** [comment]
Hey @314159265359879 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID BTC07638
Please see the link below to our dedicated support line:
[Bitcoin Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by markmhendrickson** [comment]
We're tracking [here](https://github.com/leather-io/extension/issues/3616) already.
