### ISSUE TITLE
Improve formatting of long token names (e.g. Runes)

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#5673]
SUSDH•SUSDH•SUSDH•SUSDH has quite a long name as-is, when combined with a number featuring lots of decimals the formatting looks a bit off in the wallet. There are likely other examples but this is the first one I have come across in my own wallet.

![Screenshot 2024-07-22 at 4 06 24 PM](https://github.com/user-attachments/assets/df0bd26e-6465-4f26-ac02-8fb791488902)

**Comment by pete-watters** [comment]
Thanks for reporting this @brandonmarshall-tm . I have a PR with a fix I hope to get merged and released soon. 

https://github.com/leather-io/mono/pull/310
