### ISSUE TITLE
Clarify solution: Insufficient funds to cover fee. Deposit some BTC to your Native Segwit address. 

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5689]
A user will see this when they try to send an ordinal inscription when they do not have enough uninscribed BTC on their BTC balance address to cover the network fee. 

"native segwit address" is not a term well known by (novice) users. What about calling it the "BTC balance address that starts with bc1q...") instead? or is that to lengthy?

![image](https://github.com/user-attachments/assets/db1b3366-4b24-4153-b645-7bab02ef5776)

![image](https://github.com/user-attachments/assets/83dad1db-7823-4f87-9458-0ca84efd8579)

**Comment by markmhendrickson** [comment]
We've included a solution to this case in our new approval UX, in which we'll have a clear embedded prompt for depositing funds for covering the transaction even in the case of inscription transfers.
