### ISSUE TITLE
Visual bug account selection screen when using Ledger

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5706]
The last account is not fully displayed

**Comment by 314159265359879** [comment]
![image](https://github.com/user-attachments/assets/948ebd99-e1d7-444f-a94b-61e7d73393db)

**Comment by markmhendrickson** [comment]
@314159265359879 want to confirm resolution in https://github.com/leather-io/extension/pull/5690?

**Comment by 314159265359879** [comment]
confirmed resolved by #5690, not live yet, should be with the rerelease, right?

**Comment by markmhendrickson** [comment]
@alter-eggo to confirm release

**Comment by alter-eggo** [comment]
@markmhendrickson @314159265359879 yes, this should be fixed once latest release is published

**Comment by 314159265359879** [comment]
Seeing it live now on 6.45.2 closing this.
