### ISSUE TITLE
Resolve Bitcoin balances not loading, bestinslot.xyz error 429 perhaps others too

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5707]
A user is reporting that they haven't seen BTC loading in the wallet for a couple weeks. The console shows these errors:

![image](https://github.com/user-attachments/assets/f9b22706-fa0a-4e86-b5ef-9a641c0dbd4c)

**Comment by 314159265359879** [comment]
A bit more info
related addresses:
https://mempool.space/address/bc1qvgg0kasdc36cxjmgmzd4ltwlxqja7y7d7mvjgl
This has no inscriptions/runes (as expected): https://ordinals.hiro.so/address/bc1qvgg0kasdc36cxjmgmzd4ltwlxqja7y7d7mvjgl

And 
https://mempool.space/address/bc1p07cccat0s4efvlqlzlu8cxw2tt06qzecslxvdnq5cuvglr7h87kq6zms2f 

Both addresses have a modest amount of history ~50-60 transactions

This has 94 inscriptions
https://ordinals.hiro.so/address/bc1p07cccat0s4efvlqlzlu8cxw2tt06qzecslxvdnq5cuvglr7h87kq6zms2f

There are inscriptions in here of an unknown type
![image](https://github.com/user-attachments/assets/bb2bbfac-0600-47e1-8454-37b838939fdf)

Looks like they are displayed normally on ord.io
https://www.ord.io/bc1p07cccat0s4efvlqlzlu8cxw2tt06qzecslxvdnq5cuvglr7h87kq6zms2f

None of this looks out of the ordinary.

**Comment by markmhendrickson** [comment]
@alter-eggo Do you have a sense here how we could end up generating 429s from BIS? I would presume that our client-side throttling prevents this, though perhaps the BRC-20 queries to BIS aren't throttled?

**Comment by 314159265359879** [comment]
two more cases like this. I am asking for more details and will add them here as I receive them.

**Comment by 314159265359879** [comment]
This is from the user that said that it remains in loading state
![image](https://github.com/user-attachments/assets/62c5b3e8-1a61-4cce-97c1-8b5a3aee3ff7)

about 40 transactions history on the bitcoin balance address: bc1qwew8znxjfrmn4ez9jnxrwc2ua3rmvkhud0ny4k

**Comment by alter-eggo** [comment]
@markmhendrickson just checked and yes, request was not rate limited

**Comment by 314159265359879** [comment]
I got a report that this is unresolved for one user after updating to 6.45.2 (another user reported it resolved).
![image](https://github.com/user-attachments/assets/e9b96eff-5a6c-4b00-a786-240f2e621f5b)

**Comment by 314159265359879** [comment]
The above user shared these
![image](https://github.com/user-attachments/assets/837e4f3b-bcdd-45d3-a844-a7656b23cee0)

![image](https://github.com/user-attachments/assets/bfd9e12a-bec3-4cdb-ac40-1ce6111d9295)

**Comment by alter-eggo** [comment]
This should be resolved by BiS team. @314159265359879 can we close this task?

**Comment by markmhendrickson** [comment]
I'm moving to integration review so @314159265359879 can confirm with the relevant users who've reported this that they don't see the issue anymore.

**Comment by 314159265359879** [comment]
This is confirmed resolved.
