### ISSUE TITLE
Prevent failed Gaia response from blocking authentication

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5714]
I tried authenticating (via the legacy API) to Console but upon selecting an account, the UI stalled and I noticed Sentry threw a 429 in the console. Upon trying to connect again, I was able to select successfully. Is it possible that Sentry's 429 was the culprit and we need to make its response handling non-blocking?

![image](https://github.com/user-attachments/assets/e72cc152-db38-4a6d-862d-7026adf5ad66)

**Comment by markmhendrickson** [comment]
I'm also surprised by the number of 429s thrown by Hiro since presumably we should be catching all these. @alter-eggo is it possible that the legacy auth screen isn't using the client-side throttling?

**Comment by kyranjamie** [comment]
Pretty sure this is related to Gaia request failing, not Sentry

**Comment by markmhendrickson** [comment]
Ah so this issue basically? https://github.com/leather-io/extension/issues/3564

**Comment by kyranjamie** [comment]
Yep
