### ISSUE TITLE
Prevent reload of data for Stacks NFTs without metadata

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5716]

**Comment by kyranjamie** [comment]
Suggest that we persist known-missing NFT metadata (by `queryKey`), and disable the query if missing.

**Comment by markmhendrickson** [comment]
Do we have the same problem / need for other asset types, not just Stacks NFTs?

**Comment by kyranjamie** [comment]
Not really, it's only with the Hiro Metadata API I've seen this be a problem

**Comment by markmhendrickson** [comment]
Cool, though that API also affects Stacks _FTs_ (fungible) as well presumably (e.g. token images)?

**Comment by kyranjamie** [comment]
From what I've observed, Stacks NFTs from this API are the real offenders
