### ISSUE TITLE
Lower fixed minimum sendable amount in Leather

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5739]
Currently the wallet has a hard set limit of 6000 sats when sending bitcoin. In most cases this is helpful because it prevents users from accidentally sending small amounts that are likely to become uneconomical to use after sending. 

It turns out sometimes users want to send a small amount even if the resulting UTXO is likely to be uneconomical afterwards. For example to meet whitelist/mint conditions for an ordinal inscription series. 

I suggest lowering to 515 sats. 

Another option would be to show a notice when a user tries to send less then 6000 sats but then let the user proceed after clicking they understand the risk. So we do not prevent sending small amounts but we do caution the user when they try it. Much like we do when we detect abnormally high fees.

**Comment by markmhendrickson** [comment]
@kyranjamie wdyt of the above proposal?

**Comment by kyranjamie** [comment]
Thanks for the proposal @314159265359879. Why 515 specifically? [Per advice here](https://bitcoin.stackexchange.com/questions/86068/how-was-the-dust-limit-of-546-satoshis-was-chosen-why-not-550-satoshis), perhaps `546` is better, while still almost dust.

[See PR here with suggested change →](https://github.com/leather-io/extension/pull/5753)

**Comment by 314159265359879** [comment]
Ignore my 515, that was a mistake 546 is excellent. PR, looks good.
