### ISSUE TITLE
BTC & BRC20 Balances not loading with latest update

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#5745]
I just updated to the latest version and BTC balances are not loading for me. Confirmed with multiple users.

![image](https://github.com/user-attachments/assets/93e04065-7973-4900-ac7b-e4fa2c491bc8)

![Screenshot 2024-08-08 at 9 25 25 AM](https://github.com/user-attachments/assets/4bf3db7d-ffd1-430b-a7b0-f7def8f831c8)

**Comment by 314159265359879** [comment]
This is fixed in 6.45.2 now that the service provider also finished an update. Do let me know if you see this persist @brandonmarshall-tm
