### ISSUE TITLE
Version number in top right corner menu not updating after 6.44.2

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5751]
What is going on here?
I see this in Chrome (latest version), restarting and clearing cache doesn't change this. The old version is still displayed in the top right corner menu:

![image](https://github.com/user-attachments/assets/da76f29a-4d61-476e-ad34-84df1f5648a3)

**Comment by kyranjamie** [comment]
Likely because of rollback performed yesterday

**Comment by 314159265359879** [comment]
the rerelease has resolved this 6.45.2 now.
