### ISSUE TITLE
Prevent unnecessary re-query of Stacks fungible tokens

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5755]

**Comment by markmhendrickson** [comment]
Related: https://github.com/leather-io/extension/pull/5747

**Comment by markmhendrickson** [comment]
@alter-eggo please link PR for review

**Comment by alter-eggo** [comment]
@markmhendrickson there is no pr for this task yet

**Comment by markmhendrickson** [comment]
Ah I saw you move it into code review? Is it actually WIP?

<img width="512" alt="image" src="https://github.com/user-attachments/assets/20b4c2e7-f79e-40d0-a4c6-c0dcb0c547ad">

**Comment by alter-eggo** [comment]
@markmhendrickson hm, it was accidentally
