### ISSUE TITLE
Enable Signing Transaction via Ledger

### ISSUE THREAD

**Issue by MicaiahReid** [blockstack/blockstack-app#5756]
Currently, Leather prevents signing transactions via Ledger ([source](https://github.com/leather-io/extension/blob/686a8238cd40c2900ae606ba0b727c7dfa05af6a/src/app/pages/rpc-sign-stacks-transaction/use-rpc-sign-stacks-transaction.ts#L17)). Is this check something that could be removed? 

I'm creating an application that helps developers manage contract operations and deployments, and it would be great for them to be able to use Leather. This feature works with xverse, so users that want to use a ledger with our app can only use xverse.

**Comment by kyranjamie** [comment]
Hi @MicaiahReid thanks for the reminder. I've opened a PR here that adds Ledger support for this endpoint https://github.com/leather-io/extension/pull/5757
