### ISSUE TITLE
Disable BRC-20 sends

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#5773]
The BRC-20 form crashes with `TypeError: sum.amount.lt is not a function` if you initiate a send then try to go back to the amount input form. 

- Go to Send -> BRC-20, 
- enter some amount and continue to the `Choose fee` screen
- hit the back arrow in the top navigation 
- the application crashes 

Stacktrace: 
```
TypeError: sum.amount.lt is not a function
    at formatInsufficientBalanceError (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:6790:43)
    at tokenAmountValidator (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:20037:14)
    at useBrc20SendForm (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:20106:85)
    at Brc20SendForm (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:20159:97)
```

https://github.com/user-attachments/assets/a77e4e58-8c58-4ba8-a294-ba52d3af488f

**Comment by kyranjamie** [comment]
Think you missed the discussion @pete-watters but plan is to remove BRC-20 send support entirely. It's hardly used.

**Comment by pete-watters** [comment]
> Think you missed the discussion @pete-watters but plan is to remove BRC-20 send support entirely. It's hardly used.

I did, thanks! I can close this off

**Comment by markmhendrickson** [comment]
I'm reopening to tackle the disabling of these sends. We can simply remove BRC-20 tokens from the token selector view during the send flow for now, and come back later to either re-add support or guidance for how users can otherwise send them via apps.

**Comment by pete-watters** [comment]
Thanks @markmhendrickson . Disabling BRC-20 sends is straightforward and [I have a PR open here](https://github.com/leather-io/extension/pull/5804) for it

**Comment by pete-watters** [comment]
@alter-eggo is going to instead add it to the config so we can turn it on / off

**Comment by pete-watters** [comment]
I will enable visibility on Ledger while I am at it https://github.com/leather-io/extension/issues/5797
