### ISSUE TITLE
When the wallet is locked users want to see the top right menu to sign out

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5777]
![image](https://github.com/user-attachments/assets/31f9a5c7-84cf-431c-8d69-03557168b87e)

This is a bug, we used to have the menu and options available even when the wallet was locked. 

If someone wants to reset their password, they have to reinstall the extension to work around this issue.

**Comment by pete-watters** [comment]
Thanks @314159265359879 , I'll get this fixed quickly

**Comment by markmhendrickson** [comment]
Let's get a (screenshot-based) integration test in place?

**Comment by pete-watters** [comment]
> Let's get a (screenshot-based) integration test in place?

To get screenshot based testing in place I will need to do some investigations in [here](https://github.com/leather-io/issues/issues/264) first. 

For this issue, I will be able to capture it with a standard test which I should have done initially. I will schedule some time this week to add better coverage for these latest introduced regressions
