### ISSUE TITLE
When I edit network settings I expect to see the current data not default data

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5795]
Here I added stacks granite API, then when I edit the Stacks API url  shown as the hiro api url again. I expect to see leather.granite.world there. Expected:
![image](https://github.com/user-attachments/assets/134e2b85-28a1-4746-afd2-f1408f107fd6)

To reproduce. 
1. Top right corner menu
2. click network
3. add network, any name, use leather.granite.world for the stacks API, leave rest unchanged but ad a unique bitcoin key for example 335
4. Then add network
5. top right corner menu again
6. click network
7. go to three dots and click... to "edit" next to the granite network you just added
8. See error

Video from 6 onwards:

https://github.com/user-attachments/assets/4e2a7cad-6920-4888-845f-471d80559ac2

**Comment by markmhendrickson** [comment]
Let's add an integration test when resolving

**Comment by markmhendrickson** [comment]
While fixing this, we should also update the title and button label to "Edit network" since it says "Add network" atm when editing a network:



https://github.com/user-attachments/assets/f0a33ba6-8882-49df-be5a-e53e87a9a51a

**Comment by markmhendrickson** [comment]
Related visual fix:

One of these links has a visual treatment (underline) but the other doesn't for some reason



![Image](https://github.com/user-attachments/assets/df235b3a-71e5-41e0-af04-266b6174ce38)
