### ISSUE TITLE
Display BRC20 on Leather with Ledger device

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5797]
We had this fix a while back and they were displayed https://github.com/leather-io/extension/issues/5028

It looks like it is no longer the case. I confirmed it with one of my wallets.

**Comment by markmhendrickson** [comment]
Let's get an integration test in place for when we resolve as well

**Comment by markmhendrickson** [comment]
Needs linked PR

**Comment by pete-watters** [comment]
@markmhendrickson I have fixed this but I didn't add integration tests yet 😬 

I have this task on my plate next https://github.com/leather-io/extension/issues/5802 where I need to add a few tests so I will make a note to add one for this while working on that
