### ISSUE TITLE
Open the Leather extension programmatically (API needed)

### ISSUE THREAD

**Issue by renashah** [blockstack/blockstack-app#5800]
Hey Leather eng team! We need a way to open the Leather extension programmatically.  Is there a way for Leather to allow our app to do this?  Right now, Chrome will not allow it.

We'll need it to launch .locker TLD.

**Comment by renashah** [comment]
@bilalanees98 would be able to provide more context re timeline and specifications

**Comment by bilalanees98** [comment]
Hey team
Here's a little context around this.
We're using `@stacks/connect v7.5.0` to interact with the leather wallet extension. While we are able to open up wallet popups for specific things e.g. transaction broadcast, message signing etc we cannot open up the extension 'generically'.

We tried hitting the chrome-extension url and opening it from there, but that ends up giving us a `ERR_BLOCKED_BY_CLIENT` error.
This is the url we try to hit: chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.html#/

Wondering if we can get an API that will help us open up the wallet extension. The goal is to navigate users directly from the dotlocker dashboard to either the leather extension popup or to the maximized version in a new tab (preferred).

We're on a bit of a tight deadline with the launch, would be great if this could be ready by mid next-week (28th August). Happy to work towards finding a better date as well.

**Comment by pete-watters** [comment]
Hi @bilalanees98 , 

Thanks for providing this information. I will discuss it with the team and report back shortly.

**Comment by markmhendrickson** [comment]
Let's look into whether we can add a generic API for opening the extension to any page / route.

**Comment by pete-watters** [comment]
Hi @bilalanees98 ,

I have got to work on this and have a draft PR ready where I have added a new RPC call - `openWallet`.  You will be able to access this by running `LeatherProvider.request('openWallet')`. There is still some work to do - adding docs, tests and extending it to accept the page you wish to open as a parameter. 

If you wanted, you could download and [install this build](https://github.com/leather-io/extension/actions/runs/10527726211) of Leather wallet from [my draft PR ](https://github.com/leather-io/extension/pull/5810) to check if it's working for you.

**Comment by bilalanees98** [comment]
Thanks @pete-watters 

I'll get someone to try this out and report back.

**Comment by Imamah-Zafar** [comment]
hey @pete-watters tried this on my end and its working 👍

**Comment by pete-watters** [comment]
> hey @pete-watters tried this on my end and its working 👍

Thanks for confirming @Imamah-Zafar 👍 

FYI we have decided to rename the API as `open` so you can access it with `LeatherProvider.request('open')`. 

I have [created a release ](https://github.com/leather-io/extension/pull/5817) that includes this work and will get it out ASAP

**Comment by pete-watters** [comment]
@bilalanees98 @Imamah-Zafar : I just published a release of Leather that includes this API update - `v6.47.0`. It's awaiting Chrome Store approval right now but I expect it to go live soon. 

@markmhendrickson: I opened [this new task](https://github.com/leather-io/extension/issues/5821) for extending the API. I just wanted to get this out to meet the deadline

**Comment by pete-watters** [comment]
I can confirm this update is now live. Let me know if you experience any issues. 

Good luck with the launch 🚀

**Comment by kyranjamie** [comment]
Sorry for the late follow up. 

@renashah @bilalanees98 Curious what the .locker user flow is. What is the user expected to do after you've opened the wallet? What page do you open on? I wonder if the API should be more narrowly scoped to the task the user needs to perform, rather than just opening it.

@pete-watters I wonder what the promise does in your implementation? If the wallet opens, and no return value is expected, I'd imagine the promise to return immediately, rather than hang indefinitely.

**Comment by pete-watters** [comment]
> this new task

Thanks @kyranjamie , let me improve it. Do you have any thoughts on this task - https://github.com/leather-io/extension/issues/5821. Mark suggested extending this to allow the page to be opened to be passed but I'm unsure if that has other security implications

**Comment by markmhendrickson** [comment]
[See this Slack thread for context](https://trustmachines.slack.com/archives/C076M3Y8AJ1/p1724238567732139)
