### ISSUE TITLE
bug: fix alignment of page header logo and menu

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#5802]
There are some visual issues regarding alignment of page headers we need to address. Reported by @fbwoolf[here](https://github.com/leather-io/extension/pull/5798#issuecomment-2303299071)

I have some Q's about how things should line up here: https://trustmachines.slack.com/archives/C05LRS7G44R/p1724305603462199

**Comment by pete-watters** [comment]
We have a few types of header and I want to make sure each one is exactly correct: 

https://github.com/user-attachments/assets/06b8be25-7cdc-42bb-bbf3-7e9c254ca470

![Screenshot 2024-08-22 at 07 07 41](https://github.com/user-attachments/assets/95e9e6ed-0a50-4083-b785-76ef1275949c)

https://github.com/user-attachments/assets/7fedce5a-c08c-4c9d-9d03-1b3e96ea6831


https://github.com/user-attachments/assets/204556c6-b631-4aeb-bdb1-e1322d2dcf60

**Comment by pete-watters** [comment]
@mica000 kindly came back to me with some [precise details](https://trustmachines.slack.com/archives/C05LRS7G44R/p1724346724812739?thread_ts=1724305603.462199&cid=C05LRS7G44R ) on this. I will spend a bit more time on it making it perfect.

Ideally I will also then spend time [adding visual tests](https://github.com/leather-io/issues/issues/264)

**Comment by mica000** [comment]
Review here: https://trustmachines.slack.com/archives/C05LRS7G44R/p1724346724812739?thread_ts=1724305603.462199&cid=C05LRS7G44R

**Comment by pete-watters** [comment]
As part of this task I need to add some more integration tests for header items and also to capture BRC-20 on Ledger as oer https://github.com/leather-io/extension/issues/5797#issuecomment-2302485537

**Comment by pete-watters** [comment]
Opened [this PR](https://github.com/leather-io/mono/pull/406) to fix issues with the `BigTitle` header

**Comment by pete-watters** [comment]
Released in https://github.com/leather-io/extension/pull/5838
