### ISSUE TITLE
Show scroll bar in some places such as, when selecting an account, or a token in de send flow, and allow scrolling on the change "network page". 

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5803]
I was under the impression we do not show a scroll bar for a clean look of the product. It is also possible this is a bug. At the moment I am missing a scroll bar on several pages even when I hover to the side with the mouse it does not appear.

These are the pages identified thus far:
* Account selection page
* Selecting a token to send
* receiving token list (also needs a filter)
* Change network page

Related discussion: https://trustmachines.slack.com/archives/C069V6G48F7/p1724194546535279

**Comment by pete-watters** [comment]
We intentionally hide the scroll bar for aesthetic reasons.

Scrolling definitely still works but perhaps we can reach out to this user (Prince Troy (PrinceTroyC} on Twitter ) and ask for more information?

Perhaps it is an actual bug on the platform they are using, in which case we should fix it

**Comment by 314159265359879** [comment]
I will reach out to them.

**Comment by 314159265359879** [comment]
Reaching out to the user lead to my twitter account getting suspended :exploding_head:

Without speaking to this particular user, I have seen reports like this before and in those cases they didn't realize how to scroll because they do not see the scroll bar. Probably mostly due to conditioning and doing it a certain way. Sometimes a user doesn't have a scroll wheel (or way to swipe) but that is rare.
In case you can't swipe or scroll through, they are locked. In addition some users in the past have complained that it was inefficient scrolling when you have to go through hundreds of tokens or accounts it is much faster to click the scroll bar and move it down with the mouse.

![image](https://github.com/user-attachments/assets/1472e11d-d749-4162-8acf-81c002fee160)

It is working as intended and will not be changed.

**Comment by pete-watters** [comment]
Adding my update from Slack:

Can you double double check that on a Windows laptop, with no mouse that you can scroll using the trackpad?

- I've confirmed that this works on a MAC but I can't test it on windows

We could consider a possible enhancement whereby if users have say 100+ accounts then we show the scroll bar
- before doing that it would be interesting to know what % of our user base this is

I get that they would be frustrated trying to access account 250. If this is a large proportion of users we could also investigate adding pagination
