### ISSUE TITLE
Change link/functionality of Get support and Give feedback buttons in the wallet menu

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5813]
Change the link/function:
Get support → [leather.io/contact](https://leather.io/contact)
Give feedback → [leather.io/contact](https://leather.io/contact)

Currently the page is up on leather.io/support, but we'll move to /contact instead lets make sure that is finished before merging this change.

**Comment by pete-watters** [comment]
@314159265359879 let me know when these links are live and I can update them in Leather. I checked and right now they aren't working

**Comment by aypei** [comment]
hi @pete-watters ! I updated these links just now on our website, they're live

**Comment by 314159265359879** [comment]
We'll also want to take this out of the product here (the "give feedback" button):
![image](https://github.com/user-attachments/assets/6914edc9-455b-4fda-b2e7-5f51d85d693d)

**Comment by pete-watters** [comment]
I've made this change in https://github.com/leather-io/extension/pull/5842 and hope to get it released soon

**Comment by kyranjamie** [comment]
I think it's a poor decision to kill the in app feedback tool. We'll receive much less feedback this way. Fewer bugs and interesting ideas will be surfaced via the Slack integration. 

To receive feedback _it is crucial_ the friction to do so is very low. Taking them out the app to a separate webpage that requires additional info, is too much work. It also loses metadata about the wallet version.

Sometimes users ignore the message saying "Don't use this for support". So what? That doesn't mean we need to kill the whole feedback tool.

**Comment by pete-watters** [comment]
> I think it's a poor decision to kill the in app feedback tool. We'll receive much less feedback this way. Fewer bugs and interesting ideas will be surfaced via the Slack integration.
> 
> To receive feedback _it is crucial_ the friction to do so is very low. Taking them out the app to a separate webpage that requires additional info, is too much work. It also loses metadata about the wallet version.
> 
> Sometimes users ignore the message saying "Don't use this for support". So what? That doesn't mean we need to kill the whole feedback tool.

I can add this back if needed as I also think it's good. 

Perhaps I was too quick to implement this based on a comment @markmhendrickson @314159265359879 - do you have some agreement to remove this?
