### ISSUE TITLE
bug: BTC send on Testnet says insufficient funds even if available

### ISSUE THREAD

**Issue by pete-watters** [blockstack/blockstack-app#5854]
There is a bug that is causing CI test failures in shard 8. To reproduce:
- Login to Leather and switch to `Testnet`
- Try and send some BTC
- Observe the error `Insufficient funds` even if you have funds available

![Screenshot 2024-09-11 at 08 44 01](https://github.com/user-attachments/assets/b38b5857-34b5-4650-913d-6620114936e3)

**Comment by pete-watters** [comment]
I tried on production `v6.47.1` and it seems like I can send a smaller amount there. I can also see `Send max` which is no longer appearing on the latest `dev` build.

![Screenshot 2024-09-11 at 08 48 15](https://github.com/user-attachments/assets/e69124a9-febf-4839-a16c-86c61cf37b8b)

**Comment by pete-watters** [comment]
@markmhendrickson we started seeing this fail in the CI and it's blocking us merging any PRs to the extension at the moment.

**Comment by DeeList** [comment]
This user reported the same error, they're unable to send tBTC after trying a few different amounts.

'I got tBTC, but wallet says I have not enough funds even when I try to send only a piece of it'


![Screenshot 2567-09-26 at 07 59 34](https://github.com/user-attachments/assets/2734ae6e-d2a7-4e47-a4db-6951e18e40cb)
![Screenshot 2567-09-26 at 07 56 46](https://github.com/user-attachments/assets/ca0bdc7a-e682-40ee-9b36-d340314add15)

**Comment by kyranjamie** [comment]
This fix was tested as part of @fbwoolf's PR https://github.com/leather-io/extension/pull/5859/files
