### ISSUE TITLE
Group NFT's into collections

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5862]
For stacks NFT's there are smart contracts that help organise NFT's into collections, collections share the same smart contract. 

For bitcoin, it is possible we'll need to get this from metadata; older collections have external metadata with all the inscription numbers in them. It may help to work with a ordinals marketplace that has that data already.

**Comment by 314159265359879** [comment]
This would also work: https://github.com/leather-io/extension/issues/5863

When a user wants a better overview of all their collectables.

**Comment by markmhendrickson** [comment]
Dupe? https://github.com/leather-io/extension/issues/3613

**Comment by 314159265359879** [comment]
> Dupe? #3613

Yes it does look like it. I will make an explicit comment there that we'd want to see the same thing for Stacks NFT's.
