### ISSUE TITLE
Add support for BNSv2

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5877]
Prior discussion: https://trustmachines.slack.com/archives/C05T570TNQJ/p1726223496583099?thread_ts=1725474426.269799&cid=C05T570TNQJ

![image](https://github.com/user-attachments/assets/18cf05b7-8cbd-4990-a147-8df354612b10)![image](https://github.com/user-attachments/assets/1fc10f7c-c543-45db-abf9-a899d00e4f42)
I see gamma has adopted showing a "V1 (legacy)" and "V2" label. I'd prefer to show BNSv2 without a label and BNS V1 with  "V1 deprecated" label, what do you think?

There was an issue with the first airdrop (expiration times were not right) and the airdrop process has restarted. 

Here is the (updated BNSv2 v2) contract: P2QEZ06AGJ3RKJPBV14SY1V5BBFNAW33D96YPGZF.BNS-V2
https://explorer.hiro.so/txid/SP2QEZ06AGJ3RKJPBV14SY1V5BBFNAW33D96YPGZF.BNS-V2?chain=mainnet

We are waiting for Hiro to finalise work on the BNS API/docs. Then, we should be able to adopt it (they promised to make it as easy as possible for wallet providers).

The logo for BNSv2 has been changed slightly, new logo:

![image](https://github.com/user-attachments/assets/8adfdcfd-fb8c-4706-a296-a7a0e46880c4)
https://images.gamma.io/ipfs/QmUDBKgiCDW8J8db3bFBhnnVLHwguspGQLZ3zZ6t76ne45

**Comment by 314159265359879** [comment]
By the way airdrop of names to V1 owners is still ongoing. about 1/7th to go I think.

**Comment by 314159265359879** [comment]
I updated the first post with the BNSv2 contract. Airdrop was well on its way but there was an issue so it was redeployed and the airdrop is being replayed. You can read more about the details in this forum post: https://forum.stacks.org/t/megathread-bns-upgrade-discussion/14899/71

It is expected to take about 1 week to complete.

**Comment by markmhendrickson** [comment]
Note we have a project for these enhancements generally [here](https://www.notion.so/trustmachines/Upgrade-to-BNS-v2-00f16e244cb04b36be662dcc86cf02a3?pvs=4#933d574155d94d2eabcabcc537e92bfa). Let's capture distinct issues for that project in [this related milestone](https://github.com/leather-io/extension/milestone/97) instead of lumping into one issue.
