### ISSUE TITLE
How to display BNS names v1 and v2 in the wallet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5884]
v1
v2 contract address: SP2QEZ06AGJ3RKJPBV14SY1V5BBFNAW33D96YPGZF.BNS-V2
v2 with a mistake/bug, this will not be used, want to hide these completely in the wallet? users can still see them on an explorer if they want. 

This is what it looks like now:
![Image](https://github.com/user-attachments/assets/1ebdebc6-1ce7-4e5c-a76c-821657ddd9b0)

**Comment by 314159265359879** [comment]
If a user has multiple BNSv2 names in their wallet do we also allow them to change the primary name in their account?

The SDK does support this functionality. 

When a user has an account name it is displayed instead of the default "account 1"

I propose we do the following when we add support for BNSv2:
Show Account 1 
If there is a BNSv2 name, then display the primary name.
Do not display BNSv1 names as the account name anymore. If a user has only a BNSv1 name in their account, which should be rare, they'll get in touch and we can explain they'll have to register a 

Any BNSv1 names registered after the cut-off for snapshot for BNSv2 name airdrop (after September 19th 2024) would not automatically have had their BNSv2 equivalent airdropped. 
There are still BNSv1 registers available, and the contract will always remain available. if users want. The expectation is that users will want to transition to the BNSv2 names because of the advantages (SIP009 compatibility, non-custodial listing, multiple names per account, optional managed namespaces).

**Comment by 314159265359879** [comment]
This is the final version on how they are displayed on gamma.io
![Image](https://github.com/user-attachments/assets/7c20e062-ec0a-4535-be7b-43d97864dca6)

new logo, and just "BNS: Bitcoin Name System" for BNSv2 lets adopt the same. 


And then the v1 name: BNS: Bitcoin Name System (V1 - Legacy)
![Image](https://github.com/user-attachments/assets/686eebf0-79f6-466e-bfc0-870fdc5f5e35)

**Comment by Asparex** [comment]
Hi, i think i register BNS v1 name after 19 september how can i register same bns name v2?

**Comment by camerow** [comment]
> Hi, i think i register BNS v1 name after 19 september how can i register same bns name v2?

@Asparex you will need to register that name in the BNSv2 system.

**Comment by alter-eggo** [comment]
is this task still relevant? @camerow @314159265359879

**Comment by camerow** [comment]
@alter-eggo I don't think so - closing this one.

**Comment by Wrenart** [comment]
Hello all, I am a complete newbie, So please forgive my lack of knowledge. I need to ask. I have multiple accounts with BNS v1 names and they show the bbs names well on all platforms. A few weeks ago, I got a few Bns 2 names and my accounts (New ones with no bns names) did not update to the new bns names. I tried sending the bns names to different accounts but they still don’t update there as well. Am I doing something wrong or bns 2 names do not appear as account names?

**Comment by 314159265359879** [comment]
@Wrenart I believe I answered your question here: https://github.com/leather-io/extension/issues/5976#issuecomment-2548130453

There is a bug preventing the wallet from showing the BNSv2 names right away. Also note that dapps may still need some additional time before they fully support BNSv2 so for a while you may see BNSv1 names there and BNSv2 in wallet in case they are not held by the same address.
