### ISSUE TITLE
Connecting wallet to dapps on Bitcoin fails with version 6.48.0

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5899]
Account picker when connecting to Bitcoin dapps seems to prevent users from connecting at all in some cases. 

here is what happens on stampscan.xyz, the dapp never connects to Leather

https://github.com/user-attachments/assets/1b823931-23ca-4776-a591-1f7fd99cd540

On Openstamp.io nothing happens when "Leather" is clicked to connect. 

On magiceden I can't connect either
![Image](https://github.com/user-attachments/assets/cbd87945-3526-4198-8aee-ccbf63739ffc)
Clicking confirm, nothing happens. 
![Image](https://github.com/user-attachments/assets/8d03a3c4-87db-42f2-a023-0c951eb05af3)

Same on gamma.io

**Comment by 314159265359879** [comment]
Chrome
It doesn't look as serious now. The pop-over looks like it popped with a delay or behind the browser instead of over, atleast for magiceden
and sometimes I have to enter a password, even though in the extension windows it doesn't look locked

Opera (restarted, fresh install)
Retesting on a fresh browser (Opera) there is no issue with these
Now it looks fine on Gamma.io and on magiceden.io too no issue, pop-overs also come up where I expect them.

Same with Openstamp.io, I get the expected popover (first I can select account and confirm) then sign the arbitrary message and I am connected.

**Comment by kyranjamie** [comment]
Thanks for reporting @314159265359879 

Obviously this sounds like a very alarming issue...  ~but I haven't been able to replicate~ Edit, I was testing with windows side-by-side so missed this focus issue, so silly. Pushing a fix now.
