### ISSUE TITLE
Balance doesn't load in the wallet, when there is only one transaction

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5911]
Reproduction steps
1. Create new account in wallet
2. Send 1 STX to it
3. See error 0 STX balance but history of incoming transfer showing

See account 125 in dev wallet.

Expected issue: something wrong with the Hiro API. 

-----------------------------------------------------------------------------

I have seen two cases today that were similar and I could not explain. 

> 1. The [Ledger-associated address](https://explorer.hiro.so/txid/0x4c965d5a346128bac0712b7f59bbd01ccd04bf3230afcb9bab17807c872dc774?chain=mainnet) I mentioned in my first email is still having this issue. I did try removing and reconnecting the account via Ledger connection with no success on updating the balance. Hard refresh with a maximized Leather page also did not work.
> 2. I have a [non-Ledger address](https://explorer.hiro.so/address/SPW2XE9MFKG13WJNBM2GHYY46MT352K8DBB8H2H7?chain=mainnet) with a different instance of Leather which was also having this same problem (confirmed transfer but no balance displayed). The balance updated correctly as soon as I asked a friend to transfer 1 STX to that address, even before the txn was confirmed (see screenshot below). When I only had transfer 1, I had 0 balance even though it was confirmed. When transfer 2 was pending, I suddenly had a balance display and was able to send him his 1 STX back before his send was even confirmed.

> ![Image](https://github.com/user-attachments/assets/67f62f8f-f2ee-499f-89a1-c091e7aa547e)

> Given this behavior, I tried sending 1 STX from my burner wallet to my Ledger wallet to see if that resolved my original wallet issue just like it did when my friend sent me 1 STX, and sure enough, the same thing happened. I can now see my correct balance in the Ledger wallet (immediately, even before confirmation).

> ![Image](https://github.com/user-attachments/assets/a510ea52-08aa-4568-b9d2-e75bb2990555)![Image](https://github.com/user-attachments/assets/11e75c65-6241-413e-acb2-ba4481d57960)

> I'm wondering if there's a bug where the wallet isn't registering a balance when it's the very first STX transaction in the wallet in some cases? These were both transfers from Coinbase if that matters.

These are normal STX transfers, not sure if the sender could have any influence on this bug we see. 

An address still affected by the issue:
SPPKH9HJD6PAVA52TQQFGS33T8DD877X6SR84BZM
![Image](https://github.com/user-attachments/assets/2e6d448c-3d92-4cbb-a1db-56b83ef0ea52)
![Image](https://github.com/user-attachments/assets/7a8df0bc-d276-4e5c-b439-647764e4ad4a)

Signing in on app.alexlab.co the balance is registered normally: ![Image](https://github.com/user-attachments/assets/16b894ad-60e8-44b5-b1cd-1d9631dc3012)
They run their own API server, so could be unaffected by the issue experienced in Leather.

This is unusual and unexpected. I can't help but wonder if this issue we found the other day with CSV exports from the Hiro explorer has anything to do with it or if another underlying issue with the API is causing both these issues. https://github.com/hirosystems/explorer/issues/1857

Resetting the wallet does not resolve this. Sending another transaction to the same wallet, can be a small transfer, does show the balance normally, apparently already when the incoming transaction is still pending. 
Checking the wallet 10 hours later, does not resolve this.

**Comment by 314159265359879** [comment]
Also confirmed with one more user that sending another STX transfer transaction to the account resolved the issue. Balance is showed normally.

**Comment by ar-radcliff** [comment]
Just noting that I was one of the reporters for this and confirming that I observed the following:
- Reproduced on two different wallet instances (Ledger and Non-Ledger) in Chrome on MacOS, my transfers came from Coinbase
- Txn confirmed on Explorer, Explorer shows a balance for wallet address
- Leather wallet reports a $0 balance and 0 STX tokens (but confirmed token transfer activity is displayed in Wallet activity log)
- Resetting does not fix balance
- Checking the wallet hours later does not fix balance
- Sending a small amount of STX from another address after the initial transfer DOES fix balance immediately, before 2nd txn is confirmed on chain

**Comment by 314159265359879** [comment]
This issue has been resolved.
