### ISSUE TITLE
Auth popup window doesn't close after unlocking account

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-app#5918]
When I log into a web app with Leather, if the wallet is locked (and I need to type in my password), the popup doesn't close when I'm "done" logging in (ie after I select my account). I'm still logged in to the web app as expected.

Looking in the logs, it appears that the problem is likely this "scripts can only close windows that it opened" error message.

When I log into an app and the wallet is already unlocked, everything behaves as normal. I can't be positive that the "scripts can only close windows that it opened" message isn't shown, because the window is closed and I can't see the logs anymore.

![Image](https://github.com/user-attachments/assets/e0ff46f2-a701-4003-b3fc-2097d743acf6)

Leather: 6.48.1
Browser: Vivaldi on Mac

**Comment by 314159265359879** [comment]
Thanks for reporting @hstove

**Comment by 314159265359879** [comment]
These should fix the issue [Pull Request #5921](https://github.com/leather-io/extension/pull/5921) and [Pull Request #5922](https://github.com/leather-io/extension/pull/5922)
