### ISSUE TITLE
Connection issue when connecting to Magic Eden and Unisat for atleast one user

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5950]
Feature: Connecting with Leather wallet on the decentralized app
  As a user
  I want to connect to the decentralized app using my Leather wallet
  So that I can access my account profile and interact with the app

  Scenario: Verification process fails after signing with Leather wallet
    Given the user is on the decentralized app's connection page
    When the user clicks the "Connect" button
    And selects their Leather wallet account
    And signs the prompted arbitrary message
    Then the user should be successfully connected
    And the user's account profile should be displayed on the app
    But instead, an error is thrown in the console
    And the app remains in the disconnected state

For this user it is failing on Magic Eden and Unisat, but not on Mintify, connecting works there without issue. The user has also tried clearing cache, turning off other extensions to avoid interference. Using another browser also made no difference. 

I am unable to reproduce this on my end so I still suspect something on their end to specifically cause this. 

The user has shared some logs Magic Eden site (The green one is the only difference between a succesfully connecting account and this users log):
![Image](https://github.com/user-attachments/assets/81ede7cb-6517-49f9-a9ca-ea5d0f7e5e8c)

This video also shows some Magic Eden errors in the console after the arbitrary message is signed:
https://github.com/user-attachments/assets/6b27d043-2c12-4dc7-9618-8e23bbec8bcf

![Image](https://github.com/user-attachments/assets/052e0265-87a3-47b6-adcd-c1f9f23acc27)

I am trying to get a video of the "Leather pop-over console" as the user goes through the process of connecting. Logging this here for future reference.

**Comment by kyranjamie** [comment]
This is partly the apps responsibility to fix. They should be using `LeatherProvider` not `StacksProvider`. Further, it's not clear from this error that it's even coming from Leather, could equally be an Xverse error.

**Comment by bc1pbutter** [comment]
I'm experiencing this in my application as well. I believe there may be a race condition or conflict between Xverse and Leather when the browser is loading the providers attached to the window object. The error is intermittent but happens ~50% of the time.

If I disable the Xverse or Leather extensions the error doesn't happen. Will be debugging this today and hopefully find a solution or more information to share.

**Comment by kyranjamie** [comment]
The race condition for the `StacksProvider` is expected, as both wallets attempt to use it. `StacksProvider` should be considered deprecated in favour of `LeatherProvider` and `XverseProvider`

**Comment by camerow** [comment]
Going to close this issue as it doesn't appear to be an issue on our end. Developers should use `StacksProvider`

**Comment by JavierCervilla** [comment]
this is still an issue a year after...

**Comment by pete-watters** [comment]
> this is still an issue a year after...

See [this comment](https://github.com/leather-io/extension/issues/5950#issuecomment-2471339816)
