### ISSUE TITLE
Extension breakpoint issue with sign in screen

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5951]
![Image](https://github.com/user-attachments/assets/0a26bdbc-5e2f-4776-beca-c0786b130620)

This page should be full width and not framed by a box,

**Comment by camerow** [comment]
@kyranjamie can you expand on this a bit? The issue isn't clear to me looking at the screen shot

**Comment by pete-watters** [comment]
> [@kyranjamie](https://github.com/kyranjamie) can you expand on this a bit? The issue isn't clear to me looking at the screen shot

The problem is that the border shouldn't be showing around the card:

https://github.com/user-attachments/assets/0a20a09a-3284-4c01-a82a-7f68b1a237aa

We probably need to adjust the breakpoints we have to make it respond better

**Comment by kyranjamie** [comment]
Yep, as you can almost see in @pete-watters's ultra-highly compressed video (lol) the breakpoints should adjust such that we do not show the border on the sign in card in the popup. This should only be displayed with greater viewport widths.
