### ISSUE TITLE
Sending to BNS names

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5958]
---- **Stacks** ----
Sending to a BNS name on stacks can still direct to an address that is holding the BNSv1 name after the BNSv2 name has been transferred. 

I think we should only send to the address holding the BNSv2 name from now on. 

Here is an example (address displayed is holding only the BNSv1 name, not the BNSv2 name):
![Image](https://github.com/user-attachments/assets/97426ad6-1959-47df-90a2-055d4667c80e)

Expected address (holding BNSv2 name): SP3TMEPFJJBVKVFVHYZTY0D3VXPQ8JMQ2DWP49H90

---- **Bitcoin** ----
Sending to BNS names on Bitcoin is supported through bitcoin addresses stored in zonefiles. I think we may need users to send a new transaction to create these updates for the BNSv2 names if they do not reset when a BNSv2 name is transferred and the BNSv1 name remains in the old address. 

Upon registering a .locker a Stacks and Bitcoin address are registered with the name. Right now these are not yet found by the API we use, should they?

**Comment by 314159265359879** [comment]
I see Phillip just posted this he's working on a document with more details about the migration and updates in BNSv2 to zonefiles:

![Image](https://github.com/user-attachments/assets/4834d2e2-3f6e-48f2-a3cd-3de4e3adb1fc)

https://discord.com/channels/621759717756370964/895784652630032384/1305685686065823816

**Comment by alter-eggo** [comment]
@314159265359879 re: stacks address, I've checked `cristina.btc`, and seems wallet shows right address? check bns v2 api:
https://api.bnsv2.com/names/cristina.btc
![Image](https://github.com/user-attachments/assets/805c0962-f012-4788-9aee-a5daf1c62159)

**Comment by alter-eggo** [comment]
@314159265359879 `SP3TMEPFJJBVKVFVHYZTY0D3VXPQ8JMQ2DWP49H90` this address owns `cristina.stx`, not `cristina.btc` 🤔

**Comment by 314159265359879** [comment]
@alter-eggo that is silly, I see it now too ( will edit the first post). and the current wallet is resolving cristina.stx to the BNSv1 owner
![Image](https://github.com/user-attachments/assets/983e85bc-1b85-4230-82a6-89618e2a1dd0)

**Comment by alter-eggo** [comment]
@314159265359879 I believe we can close this one right ?

**Comment by camerow** [comment]
Yeah, I believe this one is done! Thanks @alter-eggo
