### ISSUE TITLE
"MEME" token not displaying in Leather

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#5981]
A new memecoin launched on STXCITY and is not displaying in Leather

Contract: SP3HNEXSXJK2RYNG5P6YSEE53FREX645JPJJ5FBFA.meme-stxcity::MEME
https://explorer.hiro.so/txid/SP3HNEXSXJK2RYNG5P6YSEE53FREX645JPJJ5FBFA.meme-stxcity?chain=mainnet

It does show in Hiro Explorer under tokens, ex: https://explorer.hiro.so/address/SP3HNEXSXJK2RYNG5P6YSEE53FREX645JPJJ5FBFA?chain=mainnet

User confirmed it is not hidden behind "Manage Tokens"

**Comment by eriqferrari** [comment]
Hi there, a fren just posted a quick fix. refreshing the collectibles let appear my tokens under the token manager tab and I can unhide it.
I was holding and trading from yesterday, but i noted it was only visible in hiro explorer.

**Comment by brandonmarshall-tm** [comment]
User saw them after manually refreshing, then it showed up in Manage Tokens and they were able to unhide it

**Comment by camerow** [comment]
@kyranjamie possibly just a state issue here? I'm going to put this in a future cycle to at least investigate.

**Comment by kyranjamie** [comment]
I think I see the potential problem here in our query settings. We have these for the Alex/Bitstamp queries.

https://github.com/leather-io/mono/blob/298c303aa011ac9c7e8d2d3101990227bf861dff/packages/query/src/common/alex-sdk/alex-sdk-swappable-currency.query.ts#L5-L11

```
const queryOptions = {
  refetchOnMount: false,
  refetchOnReconnect: false,
  refetchOnWindowFocus: false,
  retryDelay: 1000 * 60,
  staleTime: 1000 * 60 * 10,
} as const;
```

With all 3 of these refetch settings set to `false`, even if the query is stale, we tell it not to refetch the data. I've made a PR in mono repo to change some of these settings.

https://github.com/leather-io/mono/pull/650

**Comment by eriqferrari** [comment]
Hi there, would like to circle back on this issue.. 
When a user update his primary name on BNS v2, or transfer/receive a new name you have always to manually refresh the collectible to update the wallet info.
I noted the refresh icon is rotating when i switch my wallets, but only when i click it manually it really refresh.
